### ISSUE TITLE
ui: Transparent Screen

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1001]
Now Ebiten uses GLFW 3.3, this is possible 🤔

**Comment by sylba2050** [comment]
I want this.

**Comment by hajimehoshi** [comment]
Note to myself: In the current implementation, `NSOpenGLContext`'s method.

https://github.com/glfw/glfw/blob/2c519709be0dacc7af2908982a7ab80b889a8126/src/nsgl_context.m#L350-L355

We need to implement the counterpart for Metal.
