### ISSUE TITLE
graphics: Use 3D textures to reduce graphics commands

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1003]

**Comment by hajimehoshi** [comment]
WebGL does not have this (but WebGL2 does)

**Comment by hajimehoshi** [comment]
This requires a bigger vertex data 🤔

**Comment by hajimehoshi** [comment]
https://www.khronos.org/opengl/wiki/Array_Texture

**Comment by hajimehoshi** [comment]
Actual usage is rendering cells in Kitty:

https://github.com/kovidgoyal/kitty/blob/e3e02c72719b2ceff0c0445b9441f989d00063d8/kitty/cell_fragment.glsl

**Comment by beoran** [comment]
IIRC, Allegro 5 also uses this feature, so you might be inspired by reading the source code of it as well. ;)
