### ISSUE TITLE
Support for XM / Mod files ?

### ISSUE THREAD

**Issue by c0ze** [hajimehoshi/ebiten#1005]
I was wondering, how hard would it be to implement support for playing XM audio ? Maybe a wrapper over a C library ?

https://github.com/Artefact2/libxm

(or js ?)

https://github.com/steffest/BassoonTracker

**Comment by hajimehoshi** [comment]
I'm afraid I know nothing about these formats.

As Ebiten's audio can play any PCM by representing `io.Reader`, you can play it by creating your own binding (with Cgo).

**Comment by beoran** [comment]
This is a great module library for C: https://github.com/kode54/dumb. It would be not so hard to either wrap it with CGO port it to Go language, I think.

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen this.
