### ISSUE TITLE
internal/graphicsdriver: use DirectX on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1007]
- Remote desktop doesn't work with OpenGL (#903)
- Windows on ARM doesn't work with OpenGL 2 (https://docs.microsoft.com/en-us/windows/uwp/porting/apps-on-arm-troubleshooting-x86)
  - https://arstechnica.com/gadgets/2018/02/windows-10-on-arm-limits-briefly-confirmed-no-virtualization-no-opengl/
- A mysterious bug with OpenGL might be solved by DirectX (#993)
- OpenGL doesn't work on a virtual machine (#742)
- G-sync issue (I'm not sure DirectX solves this) (#1467)
- Xbox doesn't support OpenGL (probably)

**Comment by beoran** [comment]
That's exactly what we do for Allegro as well. There's a lot of code in Allegro 5 that can be used as an example of hop to use Directx 9 (not 12, sorry) on Windows, which you could use as an inspiration.

**Comment by hajimehoshi** [comment]
Thanks. BTW, I'll adopt Direct X 10, which is the oldest Direct X we don't have to care about device-lost.

**Comment by beoran** [comment]
That might be a great idea, since DeviceLost extremely annoying, and Allegro5 needed a lot of handling for that as well. And I guess most people can user DirecxtX 10 now. :+1:

**Comment by hajimehoshi** [comment]
As #993 was fixed (probably), I de-prioritize this work.

**Comment by hajimehoshi** [comment]
https://docs.microsoft.com/en-us/windows/uwp/gaming/porting-your-directx-9-game-to-windows-store DirectX 11 seems better for UWP rather than DirectX 10.

**Comment by hajimehoshi** [comment]
If Ebiten games are UWP, Ebiten games will work on Xbox. DirectX is necessary for this.

I tend to think I'll go with DirectX 12 rather than 11. Windows 10 should preinstall DirectX 12. I'm not sure about 11. As a fallback, OpenGL implementation will remain.

**Comment by silbinarywolf** [comment]
Came across this in my travels and thought it might be a useful resource if you decide on DirectX11 rather than DirectX12.

"re-pin: minimal d3d11 reference / tutorial implementation; a small uncluttered direct3d 11 setup and rendering primer for newcomers to the api. complete, runnable single-function app. no modern c++ / oop / obscuring cruft."
https://gist.github.com/d7samurai/261c69490cce0620d0bfc93003cd1052

From this tweet: https://twitter.com/d7samurai/status/1331659636232085505

**Comment by hajimehoshi** [comment]
Thanks, that's a brief tutorial, but I don't think DX12 will be drastically complex compared to DX11...

**Comment by hajimehoshi** [comment]
I prioritized this work as requested.
