### ISSUE TITLE
Question : Can Ebiten be used without "update" ?

### ISSUE THREAD

**Issue by serge-hulne** [hajimehoshi/ebiten#1009]
Can Ebiten be used without "update", i.e. not like a game engine, but simply as a sort of substitute for Canvas ( playing for Go, the role that "Canvas" plays for JS in a browser).

I am looking for an Ebiten kind of library which could display a graph, and modify (parts of) said graphism, but not in a cyclical way (not in a synched way using "update()", but where goroutines could actually *independently* redraw parts of the canvas without resorting to "update()" cycles).

**Comment by hajimehoshi** [comment]
Unfortunately Ebiten is not available without `update` function due to portability reason (e.g., Android requires the main loop to use GL functions so far). However, you can use write the code like this:

```go
t := errors.New("regular termination")
if err := ebiten.Run(func(screen *ebiten.Image) error {
  // image manipulations as you like
  return t
}, 16, 16, 1, ""); err != nil && err != t {
  panic(t)
}
```

Then the game terminates with only one iterate. Does this make sense?

**Comment by hajimehoshi** [comment]
> I am looking for an Ebiten kind of library which could display a graph, and modify (parts of) said graphism, but not in a cyclical way (not in a synched way using "update()", but where goroutines could actually independently redraw parts of the canvas without resorting to "update()" cycles).

Oh I think I was misunderstanding.

You can use a goroutine, but note that the screen image at the end of the iterate is always adopted, and each image is not concurrent safe (you can treat an image in one same goroutine safely, but not in multiple different goroutines without mutex or something).

**Comment by serge-hulne** [comment]
Thank you!
