### ISSUE TITLE
Can't build for darwin

### ISSUE THREAD

**Issue by servusDei2018** [hajimehoshi/ebiten#1015]
I'm on a Linux system. When I type `GOOS="darwin" GOARCH="386" go build main.go` (using the example found in `examples/fullscreen/main.go`, I get:
```
/home/pi/go/src/github.com/hajimehoshi/ebiten/internal/glfw/glfw_notwindows.go:24:2: build constraints exclude all Go files in /home/pi/go/src/github.com/go-gl/glfw/v3.3/glfw
/home/pi/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/driver.go:27:2: build constraints exclude all Go files in /home/pi/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
/home/pi/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/view_macos.go:24:2: build constraints exclude all Go files in /home/pi/go/src/github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ns
```

`go version`: `go version go1.13.4 linux/arm`

**Comment by hajimehoshi** [comment]
In general, when you cross-compile, you need to specify `CGO_ENABLED=1` to enable Cgo.

BTW, even though you specify it, I think compiling would not succeed since linking requires macOS's Metal/OpenGL frameworks or other libs.

**Comment by servusDei2018** [comment]
Ok, thanks :)
