### ISSUE TITLE
ui: native text input components to input texts with IMEs (macOS and browsers)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1029]
I'm not sure this should be in Ebiten core, but this should be useful.

**Comment by hajimehoshi** [comment]
Related #286

**Comment by hajimehoshi** [comment]
Note: If we want to support only keyboards, we can have transparent text fields.

**Comment by hajimehoshi** [comment]
Hi,

The intention of this issue is to use OS's API so that we can input texts with IMEs (e.g. Japanese texts). IMEs cannot be handled only with the current Ebiten API unfortunately.

Thanks,

**Comment by hajimehoshi** [comment]
I don't think I can make it for v2.4 unfortunately.

**Comment by hajimehoshi** [comment]
For GUI applications, not only IME inputting but also a lot of features like accesibility matter [1]. So, just introducing a rich text input would not solve the issue. What about integrating a browser rendering engine and enabling to composite both Ebitengine and browser rendering? Even a native-look application can use a browser renderer (e.g. [2]).

[1] https://raphlinus.github.io/rust/gui/2022/07/15/next-dozen-guis.html
[2] https://blog.jim-nielsen.com/2022/inspecting-web-views-in-macos/

**Comment by bjorndm** [comment]
There is a patch available for GLFW that enables IME on all platfoms:

https://github.com/glfw/glfw/pull/2130 

If we apply this to the internal GLFW we can solve this issue . However, seeing that GLFW is not well supported it is probably better if we try to port as much of the code to Go as is possible.

**Comment by hajimehoshi** [comment]
Yeah I know it and I decided to implement the API by myself

**Comment by bjorndm** [comment]
OK, I didn't know you knew, so I just wanted to inform you. 
It is a good idea to implement it yourself, since GLFW is really not moving forward anymore.

**Comment by hajimehoshi** [comment]
I'll close this. For other platforms, I'll create other separate issues.
