### ISSUE TITLE
proposal: add an error when completed successfully ( or add some document to use existing one )

### ISSUE THREAD

**Issue by eihigh** [hajimehoshi/ebiten#1031]
Hi, 

I suppose there was a standard way to return an error when it completed successfully. There is no standard method at present, so I think it is the part where beginners often get lost.

I've been used `io.EOF` for that, but it'll also be fine to add some new error value in `ebiten` package. Thanks.

**Comment by hajimehoshi** [comment]
Hi,

[`Run`'s comment](https://godoc.org/github.com/hajimehoshi/ebiten#Run) says:

> On non-GopherJS environments, Run returns error when 1) OpenGL error happens, 2) audio error happens or 3) f returns error. In the case of 3), Run returns the same error.

Then you can define your own error representing success, and return it. I thought this was enough, but your request is that you want a standard way, right?

My another concern is that terminating itself is an irregular thing: applications on browsers and mobiles don't have termination basically. Then I'm hesitate to have such standard way. Rather, applications should not have termination for portability. Any thoughts?

**Comment by eihigh** [comment]
Hmm, I recognized it wouldn't work in a browser or mobile environment. Quitting and debugging in a desktop environment often returns "successful completion" error which I thought was a common problem, but it turned out to be a bad idea to avoid.

So ebiten shouldn't have such an error. I didn't immediately realize it was an anti-pattern for portability, so adding documentation might be a good idea, but I haven't thought of it yet.

I'm convinced! Thank you.
