### ISSUE TITLE
ui: Add IsForeground

### ISSUE THREAD

**Issue by superloach** [hajimehoshi/ebiten#1037]
I would like to be able to detect when the game window loses focus.

Possible ways:
 - Allow the registration of hooks for focus loss and focus gain.
 - Allow the polling of focus state.

Use cases:
 - Bringing up a "pause" menu, so the user has time to prepare before resuming play.
 - Pausing concurrent operations which must run on a separate timing than `Update()`.

**Comment by hajimehoshi** [comment]
Hi,

I think introducing a new API would make sense.

My understanding is:

- We want a new API like `IsFocused` or `IsActive`
- The new API works only when running-in-background is true (`SetRunningInBackground(true)`).
- If running-in-background is false (default), the new API would not make sense (probably this would return always true)

CC @zacharyburkett

**Comment by superloach** [comment]
Even if running-in-background is false, other goroutines will continue to run, which is my use case.

Otherwise that sounds good, yes!

**Comment by hajimehoshi** [comment]
Ah that makes sense.

**Comment by beoran** [comment]
It would be nice to make this event based using the glfwSetWindowFocusCallback function, and not with ISXXX functions.

**Comment by hajimehoshi** [comment]
I'd like to go with `IsXXX` style for consistency.

I understand event-driven way is important (and actually this should be an underlying thing), but this sounds a very long-term work (#926).

**Comment by zacharyburkett** [comment]
I've added the partial implementation of this API, for GLFW targets.
As discussed in Slack, @hajimehoshi please review and implement the mobiles API. We may need to discuss web as well.

**Comment by hajimehoshi** [comment]
We need to implement this for browsers (and perhaps mobiles).

Note to myself: There is an issue on Windows workspace: https://github.com/hajimehoshi/ebiten/blob/master/internal/uidriver/glfw/ui.go#L785-L790
