### ISSUE TITLE
keyboard/gamepad: calling IsGamepadButtonPressed and IsKeyPressed is noticeably slower

### ISSUE THREAD

**Issue by silbinarywolf** [hajimehoshi/ebiten#1038]
**The problem**
Calling `IsGamepadButtonPressed` and `IsKeyPressed` in my game now makes the game take roughly 50% of the frame time for a 60FPS in the `master` branch rather than 5% it takes in the `1.10` branch.

From eye-balling two different profiles, my understanding is that all these `thread.Thread.Call` methods add noticeable overhead to most of these function calls.

**Zip file of two SVGs from 5 second CPU profile of my game**
[giveupthedupe_ebiten_svgs.zip](https://github.com/hajimehoshi/ebiten/files/4006827/giveupthedupe_ebiten_svgs.zip)

**Comment by hajimehoshi** [comment]
Thanks. I'm a little doubtful that `thread.Thread.Call` is the culprit, since this has already existed since 1.10.

**Comment by silbinarywolf** [comment]
It has existed since then but it wasn't used for these glfw input functions :)

Compare these:
- PR for master
  - https://github.com/hajimehoshi/ebiten/pull/1035/files#diff-fb2377282e9f0ca0be79720c7c4af108R99
- My fork for 1.10
  - https://github.com/silbinarywolf/ebiten/blob/1.10-gamepad-name-support-fork/internal/uidriver/glfw/input.go#L132

**Comment by silbinarywolf** [comment]
Sorry I wasn't clear in my above post. So the difference is that `1.10` does not wrap getting these values in `i.ui.t.Call` calls. Looking at how it works, I'm making an assumption that the channels are slowing things down.

In any case this isn't a high-priority problem for me for the time-being and I'm ok with it being deferred until I provide you with some code so you can reproduce + profile it.

**Comment by hajimehoshi** [comment]
Thank you for updating!

**Comment by silbinarywolf** [comment]
Closing this issue. The slow overhead from `thread.Thread.Call` is seemingly being tracked better in this issue:
https://github.com/hajimehoshi/ebiten/issues/1466
