### ISSUE TITLE
Feature: New Example using 2D isometric RTS Game

### ISSUE THREAD

**Issue by risooonho** [hajimehoshi/ebiten#1041]
Hi.
It would be interesting to create an example of a small futuristic starcraft-like game using 2D isometric RTS Game, as it would involve all the other examples already presented in the /examples folder and would help very newcomers to this topic.

The bigger simple examples of small and complete game genres in the /examples folder I think there will be greater adoption of the engine, which by the way is very good in my opinion.

Sorry for basic English.

**Comment by hajimehoshi** [comment]
Hi,

Thank you for your suggestion! I agree such examples would be very nice. I'd be happy to review if someone could offer one.

**Comment by hajimehoshi** [comment]
Let's continue the discussion at #1112 .
