### ISSUE TITLE
SetVsyncEnabled(false) Doesn't Persist Between Monitors

### ISSUE THREAD

**Issue by zamadatix** [hajimehoshi/ebiten#1043]
Hey there,

I have the following monitor setup:
![image](https://user-images.githubusercontent.com/343550/71644486-0d1e6100-2c97-11ea-8dd0-3e00048a6faa.png)

Where:
1. 4k 120hz ("main display" in Windows 10)
2. 4k 60hz
3. 1080p 120hz

I have "ebiten.SetVsyncEnabled(false)" in a program that simply draws the FPS to the window. Launching the application on monitor 1 shows ~120 fps but if I move it to monitor 2 the app runs at ~1700 FPS. Move it back to monitor 1 and it drops down to ~120. Move it to monitor 3 and it's also ~120.

It seems for some reason Vsync is only being disabled when the window is on monitor 2, perhaps related to that being the only 60 FPS display?

**Comment by hajimehoshi** [comment]
Hi,

I feel like this inconsistent behavior comes from GLFW. I'll take a look later, but this might be hard to fix.

**Comment by hajimehoshi** [comment]
Does this happen with Ebiten on master, which uses GLFW 3.3 (not 3.2)?

**Comment by zamadatix** [comment]
New to Go but I think "go get github.com/hajimehoshi/ebiten/..." pulls from the default branch which seems to be master so yes as long as that's true.

**Comment by hajimehoshi** [comment]
This depends on whether you use Go modules or not. Do you have `go.mod` file in your project?

**Comment by zamadatix** [comment]
No go.mod, just the single source file with these imports at the top:

```
import (
	"log"
	"strconv"
	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/ebitenutil"
)
```

**Comment by hajimehoshi** [comment]
Thanks. So it looks like you don't use Go modules. I think you have the master branch of Ebiten at `$HOME/go/src/github.com/hajimehoshi/ebiten`, is that correct?

**Comment by zamadatix** [comment]
Yep!

I was able to reproduce with go-raylib which also uses GLFW 3.3 so I think the issue is actually somewhere downstream and not in this project.

Going to close this issue for now and try to figure out the root cause elsewhere, thanks for looking into it!
