### ISSUE TITLE
Update loop does not start if window is too big

### ISSUE THREAD

**Issue by megapctr** [hajimehoshi/ebiten#1065]
**OS:** Windows 10
**go:** go1.13.6 windows/amd64
**ebiten:** v1.10.3

<hr>

When using `ebiten.Run` to create a window with size similar to (or above) my screen resolution, the update loop does not start and a white window is opened. CPU usage is high, but the update function is not called at all.

Some insights:

**The error can be resolved by minimizing and restoring the window.**
Sometimes the update loop will start when minimizing the window. Sometimes it will start after restoring the window.
You have to minimize the window - losing and restoring focus (e.g. alt-tab) does not fix the issue.

**It seems correlated to screen resolution**
The error occurs with 1080p window on 1080p laptop screen, but the same binary ran on the same laptop will work fine when connected to a 4k display.

<details>
<summary>example.go</summary>

```go
package main

import (
        "fmt"
        "github.com/hajimehoshi/ebiten"
        "image/color"
)

var wasUpdateRun bool

func main() {
        // enter your screen resolution
        width, height := 3840, 2160

        reproduceError := false
        if reproduceError {
                // this causes the error for me
                // it seems like the window is too high?
                height -= 16
        } else {
                height -= 32
        }
        ebiten.Run(update, width, height, 1/ebiten.DeviceScaleFactor(), "test")
}

func update(screen *ebiten.Image) error {
        if !wasUpdateRun {
                fmt.Println("update")
                wasUpdateRun = true
        }
        _ = screen.Fill(color.NRGBA{0x00, 0x66, 0xcc, 0xff})
        return nil
}
```
</details>

**Comment by hajimehoshi** [comment]
Thank you for reporting! I'll take a look later.

> ebiten.DeviceScaleFactor()

This returns 1.5 in your environment, right?

**Comment by megapctr** [comment]
yes

**Comment by hajimehoshi** [comment]
I could not reproduce the issue. I adjusted the scale 1.5, and the FPS and TPS kept near 60. Could you try the latest master branch of Ebiten?

**Comment by megapctr** [comment]
Thanks for your patience, I tried with master today and can't reproduce the problem as well. Looks like it was resolved at some point
