### ISSUE TITLE
text.Draw does not support newline characters

### ISSUE THREAD

**Issue by zacharyburkett** [hajimehoshi/ebiten#1074]
As the title suggests, text.Draw does not support newline characters. It appears that the debug text drawing does support this.

**Comment by hajimehoshi** [comment]
The problem is that 'line-height' is not a clear thing. An appropriate line height depends on the context.

**Comment by hajimehoshi** [comment]
Ah, I didn't realize this: https://godoc.org/golang.org/x/image/font#Metrics

```
    // Height is the recommended amount of vertical space between two lines of
    // text.
```
