### ISSUE TITLE
Android project creation errors

### ISSUE THREAD

**Issue by alejandro-a** [hajimehoshi/ebiten#1076]
Hi,

I tried to create and Android project following this [guide](https://ebiten.org/documents/mobile.html)

<img width="1680" alt="Schermata 2020-02-12 alle 22 19 07" src="https://user-images.githubusercontent.com/11943746/74378203-cff4d500-4de5-11ea-9548-58ee8f1331b6.png">

But, every time I execute the following command:
```
ebitenmobile bind -target android -javapkg com.myproject.deepspaceoperation -o ./mobile/Android/ebiten/ebiten.aar ./mobile
```
I get this error

```
com/myproject/deepspaceoperation/mobile/EbitenView.java:53: error: method layout in class Ebitenmobileview cannot be applied to given types;
        Ebitenmobileview.layout(widthInDp, heightInDp);
                        ^
  required: long,long,ViewRectSetter
  found: double,double
  reason: actual and formal argument lists differ in length
com/alejandro/deepspaceoperation/mobile/EbitenView.java:61: error: cannot find symbol
        Ebitenmobileview.suspend();
                        ^
  symbol:   method suspend()
  location: class Ebitenmobileview
com/alejandro/deepspaceoperation/mobile/EbitenView.java:69: error: cannot find symbol
        Ebitenmobileview.resume();
                        ^
  symbol:   method resume()
  location: class Ebitenmobileview
3 errors
```

Go version: go1.13.7

Can I have a suggestion about why this happen?

**Comment by hajimehoshi** [comment]
Hi,

I think your `ebitenmobile` is a little old. Could you update `ebitenmobile`?

**Comment by hajimehoshi** [comment]
> I think your ebitenmobile is a little old. 

Oh I think this was opposite. `ebitenmobile` is too new. You'd need to install ebitenmobile for Ebiten 1.10.x. I'll update the document.

**Comment by airtonix** [comment]
> Hi,
> 
> I tried to create and Android project following this [guide](https://ebiten.org/documents/mobile.html)
> 
> <img alt="Schermata 2020-02-12 alle 22 19 07" width="1680" src="https://user-images.githubusercontent.com/11943746/74378203-cff4d500-4de5-11ea-9548-58ee8f1331b6.png">
> 

That page doesn't guide you on creating an android project, how did you know what `.gradle` / `.xml` files to create base on that document?

I'm trying to follow that and none of the commands listed on that page produce the folder/file structure in your screenshot.

I actually ended up just copying the `mobile/android` folder from https://github.com/hajimehoshi/go-inovation.git and replaced all instances of `inovation` with my app name and all instances of `com.hajimehoshi.goinovation` with my own appid.

surely there is a one liner command that autogenerats this kind of thing? (I loathe opening up a billion gigabyte application just to generate files and folders)

**Comment by hajimehoshi** [comment]
> That page doesn't guide you on creating an android project, how did you know what .gradle / .xml files to create base on that document?

This is a general Android thing and out of scope of Ebitengine. Have you tried Android Studio?
