### ISSUE TITLE
Webassembly does not work

### ISSUE THREAD

**Issue by valtsu41** [hajimehoshi/ebiten#1079]
This migh be my fault if I have missed something, but when I try to run the Hello World code with webassembly I get this error 
`Uncaught (in promise) LinkError: WebAssembly.instantiate(): Import #3 module="go" function="runtime.nanotime" error: function import requires a callable`
My code:
```package main

import (
	"log"

	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/ebitenutil"
)

func update(screen *ebiten.Image) error {
	if ebiten.IsDrawingSkipped() {
		return nil
	}
	ebitenutil.DebugPrint(screen, "Hello, World!")
	return nil
}

func main() {
	if err := ebiten.Run(update, 320, 240, 2, "Hello, World!"); err != nil {
		log.Fatal(err)
	}
}
```
(I took the wasm_exec.js file from the repo of golang and copied the index from the website of Ebiten)

**Comment by hajimehoshi** [comment]
Hi,

My guess is that your Go version and wasm_exec.js's version didn't match. If you are using Go 1.13, you need to copy wasm_exec.js of Go 1.13. It is safe to copy `$(go env root)/misc/wasm/wasm_exec.js` on your local machine.

**Comment by valtsu41** [comment]
That command does not work for some reason, but I'll try to download the 1.13 version.

**Comment by valtsu41** [comment]
Yeah, it worked. Thanks for help.
