### ISSUE TITLE
Can we use native go-gl/glfw on windows?

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#1091]
I notice that go-gl/glfw supports every platform including windows: https://github.com/go-gl/glfw/blob/master/README.md

However, we aren't using it on Windows. Is there any reason that we can't?

I'm continuing to root out unnecessary allocations in ebiten, and discovered that on windows, our platform-specific bindings are sending some params to the heap unnecessarily (I also see some CPU perf gains we can make there)

If possible, I'd like to switch us to go-gl/glfw natively on windows. It will reduce our code size!

If there is a specific reason blocking that, then I will instead focus on optimizing ebiten's windows bindings.

**Comment by corfe83** [comment]
@hajimehoshi Curious to hear your thoughts on this.

**Comment by hajimehoshi** [comment]
> However, we aren't using it on Windows. Is there any reason that we can't?

Yes. I want to avoid using Cgo on Windows for ease to use.

**Comment by corfe83** [comment]
I understand, thanks!
