### ISSUE TITLE
Mirror/flip image

### ISSUE THREAD

**Issue by coupez** [hajimehoshi/ebiten#1098]
Ebiten has a bunch of functions to rotate, translate, skew images. Is there a way to use these to flip/rotate an image along the horizontal or vertical axis, and thus basically mirroring the sprite? Or is this a missing feature?

**Comment by hajimehoshi** [comment]
You can use a negative scale of GeoM. For example, if you want to mirror the image in X axis, you can write a code like this:

```go
op.GeoM.Scale(-1, 1)
op.GeoM.Translate(width, 0)
```

**Comment by coupez** [comment]
Thanks a lot, exactly what I am looking for! This by itself does the trick: `op.GeoM.Scale(-1, 1)`
