### ISSUE TITLE
Newlines in text aren't being rendered

### ISSUE THREAD

**Issue by SamusAranX** [hajimehoshi/ebiten#1100]
I'm experiencing the weirdest problem right now and I'm not sure where to start debugging it.

I used this package (https://github.com/AndreKR/multiface) to construct a `font.Face` that can fall back to other fonts in case of an unsupported character and I'm trying to use it to render text that contains newlines, but for some reason, they're not being rendered.

What makes this weird is that in an older build of my program, it worked. Here's the string that was rendered and a screenshot of the newlines working:
```go
const testText = "You are already dead.\nお前はもう死んでいる。\nLots of stuff going on here"
```

![Newlines working](https://user-images.githubusercontent.com/676069/76710788-8d872680-670a-11ea-933a-2304a64041c5.png)

Now, a few days later, I of course changed a few things in the program, but to my knowledge none of these things should affect the text rendering. And yet:
![Newlines not working](https://user-images.githubusercontent.com/676069/76711284-e789eb00-670e-11ea-8ba7-a131b54e958e.png)

This is the entirety of my `main.go`:
https://gist.github.com/SamusAranX/630eb50fb4b67da19dd3cc92cb7827ee

What could cause this?

**Comment by hajimehoshi** [comment]
Linebreaking was introduced recently https://github.com/hajimehoshi/ebiten/commit/bb60818e8d363f731717629f325c0d4414ef5b89#diff-779a691a4ced9509e0436d663a60db2e

You need to use Ebiten 1.11.* if you want to use this feature.

**Comment by SamusAranX** [comment]
That would explain it! 😅 
Between the first and the second screenshot, I created a go.mod file and it defaulted to 1.10.5, as that's the last proper release. Going with the latest commit fixed the problem.

**Comment by hajimehoshi** [comment]
OK, thank you for confriming!
