### ISSUE TITLE
examples: Add a basic isometric example

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1112]
@zacharyburkett will do this :-)

**Comment by hajimehoshi** [comment]
@zacharyburkett What's going on this?

**Comment by hajimehoshi** [comment]
I'll defer this to v1.12.0

**Comment by zacharyburkett** [comment]
Apologies for a delay, things got very busy the past two weeks. I will be submitting a PR this week

**Comment by jrcichra** [comment]
If you need any help with an example I ported the pixel isometric example over (with some extras for my project):

https://github.com/jrcichra/gollercoaster/tree/ebiten

I have the math to convert iso to Cartesian and back. Still working through optimizations with movement.

**Comment by hajimehoshi** [comment]
@zacharyburkett Any updates on this?
