### ISSUE TITLE
Consider using github.com/go-gl/glow/gl/2.1/gl instead of github.com/go-gl/gl

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#112]
The former doesn't rely on GLEW, which means it would be easy to install on Windows.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/tree/glow Started

**Comment by hajimehoshi** [comment]
Done

**Comment by tmc** [comment]
FWIW glew isn't that hard to run on windows and this doesn't affect the behavior on windows.

**Comment by hajimehoshi** [comment]
Oh, really? I read http://www.reddit.com/r/golang/comments/2tvw3k/minigw_gogl_problem/ and the GLEW seemed to make it difficult to install a little bit. I didn't try actually that and I wasn't sure. Thank you.

According to this post and other posts, go-gl/gl is (or will be) deprecated and go/glow is recommended, and fortunately Ebiten doesn't require GLEW features, so I think this ticket was a right task.

**Comment by tmc** [comment]
:+1:
