### ISSUE TITLE
Remove all the deprecated functions and constants

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1127]

**Comment by CurtisMIT** [comment]
How do you know if a function is deprecated?

**Comment by hajimehoshi** [comment]
https://pkg.go.dev/github.com/hajimehoshi/ebiten?tab=doc

All the deprecated functions are noted as 'deprecated' in the API document.

**Comment by CurtisMIT** [comment]
ok thanks!

**Comment by hajimehoshi** [comment]
All done
