### ISSUE TITLE
Immediate mode

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1135]
See also https://eliasnaur.com/blog/immediate-mode-gui-programming

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/1132 might be enough?

**Comment by hajimehoshi** [comment]
My understanding is that this is a framework to reduce the draw calls, and then I think this will not be in the Ebiten core.

**Comment by gabstv** [comment]
For anyone that needs imGUI (for placeholder GUI and things), I created a imGUI renderer for Ebiten:
https://github.com/gabstv/ebiten-imgui

![preview](https://github.com/gabstv/ebiten-imgui/raw/master/assets/preview.png)
