### ISSUE TITLE
buffered: (*Image).At can be unnecessarily slow

### ISSUE THREAD

**Issue by dim13** [hajimehoshi/ebiten#1137]
Minimal working example:

```go
package main

import (
	"flag"
	"image"
	"image/color/palette"
	"image/draw"
	"log"

	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/ebitenutil"
)

type Game struct {
	n   int
	bug bool
}

func (g *Game) Update(dst *ebiten.Image) error {
	src := image.NewUniform(palette.Plan9[g.n])
	g.n = (g.n + 1) % len(palette.Plan9)
	if g.bug {
		// broken, leads to infinity loop, consumes all memory
		draw.Draw(dst, dst.Bounds(), src, image.ZP, draw.Over)
	} else {
		// works
		draw.Draw(dst, dst.Bounds(), src, image.ZP, draw.Src)
	}
	ebitenutil.DebugPrint(dst, fmt.Sprintf("TPS: %0.2f", ebiten.CurrentTPS()))
	return nil
}

func (g *Game) Layout(_, _ int) (int, int) { return 320, 200 }

func main() {
	bug := flag.Bool("bug", false, "trigger bug")
	flag.Parse()
	if err := ebiten.RunGame(&Game{bug: *bug}); err != nil {
		log.Fatal(err)
	}
}
```

Tested with v1.10.5 and v1.11.0 on MacOS 10.15.4

**Comment by hajimehoshi** [comment]
Thank you for reporting! I'll take a look.

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
I think this is not an infinite loop, but it takes much longer than necessary.

**Comment by dim13** [comment]
Wrong wording perhaps. It looks like infinite recursion on (*Image).Set / (*Image).At.
At least application, like in example, consumes all available memory and gets killed.

**Comment by hajimehoshi** [comment]
Thanks. Is this issue still reproduceable with the latest commit?

**Comment by dim13** [comment]
Tested. It seems to solve the issue. Thank you a lot!

**Comment by hajimehoshi** [comment]
>  It looks like infinite recursion or similar on (*Image).Set / (*Image).At.

I could not find the infinite loop with Set and At. Even before the fix, the test took very long but finished without deadlocking. Now I believe this doesn't happen with the latest patch anyway.

> PS: one thing, I've noted: it runs just fine now, but way slower with Over then with Src.

Hmm, what kind of machine are you using? On my MacBook Pro, Over now works quickly.

**Comment by dim13** [comment]
Judging on TPS: with Src I get around ~40, with Over only ~25.

Machine is MB Pro i7/16G

**Comment by hajimehoshi** [comment]
In the view of memory, Draw consumed a lot of memory actually before the fix.

> Judging on TPS: with Src I get around ~40, with Over only ~25.
> Machine is MB Pro i7/16G
> PS: I've updated the snipplet to show the TPS.

Thanks! I'll take a look more.

**Comment by hajimehoshi** [comment]
On my Machine (MB Pro 2018 i7/16G), both kept 60TPS.

**Comment by hajimehoshi** [comment]
@dim13 I'd appreciate it if you could take a CPU profiling on your program for Src and Over. Thanks!

**Comment by dim13** [comment]
[src.pdf](https://github.com/hajimehoshi/ebiten/files/4496071/src.pdf)
[over.pdf](https://github.com/hajimehoshi/ebiten/files/4496072/over.pdf)

**Comment by hajimehoshi** [comment]
Thank you! Both are recorded after the fix, right?

**Comment by hajimehoshi** [comment]
I got a similar result ('over' case, after the fix)

https://i.gyazo.com/2a111864bd439d84004ca130badc336e.png

On my machine, it keeps 60 TPS though.

**Comment by dim13** [comment]
Out of curiosity I've executed same tests on my old Air and got consistent results.

With `Src` I've got around 29 TPS: ![src](https://user-images.githubusercontent.com/4006042/79641443-e4fc3480-8197-11ea-8ecc-b3b7491c5084.png)

With `Over` only around 18 TPS: ![over](https://user-images.githubusercontent.com/4006042/79641457-f9d8c800-8197-11ea-8ad1-1b667b9b17c2.png)

There was also a considerable 'warm-up' time on start in second case, as it run only with about 6 TPS or less for a first couple of frames.

**Comment by hajimehoshi** [comment]
Based on the graphs you given, I've added some optimizations (e.g., avoiding mutex when possible).

> Out of curiosity I've executed same tests on my old Air and got consistent results.

Thanks! I'm not sure what I can do other than the optimization I did. I guess `draw.Draw` itself is slow.

Another thing I was not sure is what's the difference between on your MacBook Pro and my MacBook Pro.

**Comment by dim13** [comment]
Thank you a lot! I would consider the issue as fixed.

I'm not quite sure about `draw.Draw`, as I did also some other simple tests. For example:
```go
func BenchmarkOver(b *testing.B) {
	dst := image.NewRGBA(image.Rect(0, 0, 320, 200))
	src := image.NewUniform(color.Black)
	for n := 0; n < b.N; n++ {
		draw.Draw(dst, dst.Bounds(), src, image.ZP, draw.Over)
	}
}

func BenchmarkSrc(b *testing.B) {
	dst := image.NewRGBA(image.Rect(0, 0, 320, 200))
	src := image.NewUniform(color.Black)
	for n := 0; n < b.N; n++ {
		draw.Draw(dst, dst.Bounds(), src, image.ZP, draw.Src)
	}
}
```

with the results:

```
BenchmarkOver-4   	   75843	     14196 ns/op
BenchmarkSrc-4    	   81663	     14353 ns/op
```

which suggest, there shouldn't be much difference. But anyway, the performance is kind of completely different story and should be IMHO investigated separately.

Thank you again!

**Comment by hajimehoshi** [comment]
Sure, I agree a critical issue has already been solved.

I appreciate your cooperation!
