### ISSUE TITLE
Docs: how to get files (images, fonts) in a cross-platform way?

### ISSUE THREAD

**Issue by Zireael07** [hajimehoshi/ebiten#1141]
My toy project finally compiles to WASM, but it can't find the font file. I moved it from a folder above the /src, but it still has trouble, I suspect Font.new("./fonts/font_terminal_16_16.png") is not cross-platform somehow?

**Comment by hajimehoshi** [comment]
https://ebiten.org/tour/image.html#How_the_code_works

This page shows various ways to load an image :-)

**Comment by hajimehoshi** [comment]
Even a filesystem is not portable (No filesystem on browsers, current directory is unclear on mobiles). So the most portable way is embed a file as a Go bytes.

**Comment by Zireael07** [comment]
Huh, https://github.com/BigJk/ramen/blob/master/font/font.go is already using ebitenUtil.openPath(), which according to the link should be fine for both browser and desktop (I don't need mobile) so why does it work on desktop but not browser?

**Comment by hajimehoshi** [comment]
`ebitenutil.OpenFile` with a relative path works as a relative path from the current URL. You'd need to upload the font/image files at the appropriate directory.

**Comment by Zireael07** [comment]
I figured that out after compiling the game myself manually (i.e. not using wasmserve).
The fact that wasmserve doesn't seem to use/copy resources over seems to deserve an issue over in the other repo :P

**Comment by hajimehoshi** [comment]
> The fact that wasmserve doesn't seem to use/copy resources over seems to deserve an issue over in the other repo :P

If you specify a relative path with `wasmserve` and a resource is in the current project, the server should take a look at the file.
