### ISSUE TITLE
Add cmd/ebitenmonogame

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1144]
This command generates a C# project, that can run on Visual Studio.

The target OS is Windows, and there is no plan to enable the change the OS so far. It is because MonoGame on other platforms cannot treat shaders well. (e.g., 2MGX.exe works only on Windows now)

**Comment by hajimehoshi** [comment]
CC @SolarLune

**Comment by SolarLune** [comment]
Oh, cool! So it's possible to output a Monogame project to load into VS on Windows. At that point, you have an ordinary Monogame project generated, right?

**Comment by hajimehoshi** [comment]
Yes, that's right :-)

**Comment by SolarLune** [comment]
Great to hear - can't wait to try it out sometime!
