### ISSUE TITLE
Example in the install doc page doesn't work on Ubuntu 20.04

### ISSUE THREAD

**Issue by tommyblue** [hajimehoshi/ebiten#1146]
On a fresh Ubuntu 20.04 I was following the install page https://ebiten.org/documents/install.html
so I installed suggested packages but then I got this error while running the example:

```shell
~$ go run -tags=example github.com/hajimehoshi/ebiten/examples/rotate

go: finding github.com/hajimehoshi/ebiten v1.11.0
go: downloading github.com/hajimehoshi/ebiten v1.11.0
go: extracting github.com/hajimehoshi/ebiten v1.11.0
go: downloading github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200222043503-6f7a984d4dc4
go: extracting github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200222043503-6f7a984d4dc4
go: finding github.com/go-gl/glfw/v3.3/glfw v0.0.0-20200222043503-6f7a984d4dc4
# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status
```
To solve I installed `xorg-dev`. It could be added to the docs, though it's a meta package installing too many packages, but I don't know which was the exact one that was missing

**Comment by griffithsh** [comment]
This Stackoverflow suggests it's `libxxf86vm-dev` that you need.

https://stackoverflow.com/questions/12186494/opengl-setup-for-codeblocks-cannot-find-lxxf86vm

**Comment by hajimehoshi** [comment]
Thank you for reporting.

Actually .travis.yml https://github.com/hajimehoshi/ebiten/blob/master/.travis.yml installs `libxxf86vm-dev`. I'll add this to the document soon.

On the other hand, GLFW's readme https://github.com/go-gl/glfw/blob/master/README.md says `libgl1-mesa-dev` and `xorg-dev` are required. I might update the document to follow this.
