### ISSUE TITLE
Remove MonoGame support

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1148]
Unfortunately, we found that the generated C# was so big that some tools didn't work well. Originally, the purpose was to enable Ebiten games to run on some special environments that MonoGame supports. From the current maturity of the tools, we concluded that supporting the environments via MonoGame was not feasible.

Instead, we plan to support converting Ebiten games to C++ by [go2cpp](https://github.com/hajimehoshi/go2cpp). We have already confirmed that generated C++ code worked on the special environments. Stay tuned!

**Comment by fossegutten** [comment]
Is the reason for C++ conversion to add console support? I hope it is 👍

**Comment by hajimehoshi** [comment]
Yes :-)
