### ISSUE TITLE
ebiten: Better error messages when NewImage is called after RunGame finishes

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1149]
Ebiten should raise more explicit errors.

CC @wasedaigo

**Comment by stacew** [comment]
I also experienced in gopherjs and wasm.

**Comment by hajimehoshi** [comment]
I have not expected what happens after RunGame. Every operation should be forbidden...

**Comment by stacew** [comment]
There is no problem in window about new image open after run ().
Chrome, edge, i.e. using gopherjs All browsers freeze.
The wasm version of the chrome browser is also stopped.

**Comment by hajimehoshi** [comment]
Do this after #1122
