### ISSUE TITLE
Need help with drawn string bounding box calculation

### ISSUE THREAD

**Issue by SamusAranX** [hajimehoshi/ebiten#1151]
I just spent a few hours trying to implement a method that measures drawn text size, but I can't get it to work reliably in conjunction with [the multiface package](https://github.com/AndreKR/multiface) that I use to get fallback font support. I need this for a small UI framework I'm working on for a personal project, and I need to be able to measure strings *before* drawing them to enable text alignment in UI controls. Currently, it works well enough for my default sans serif font, but utterly fails with the monospace one: 
![image](https://user-images.githubusercontent.com/676069/81512546-91f24900-9321-11ea-955e-b2be52880226.png)

I was hoping to open a PR later on, but I got stuck. Here's the relevant commit in my fork of ebiten: https://github.com/SamusAranX/ebiten/commit/d8f1dbdc21ec5b06fafbb8978d0ae924cd5b4e96

Here's my helper file that handles font loading and multiface construction: https://gist.github.com/SamusAranX/2672324335cca4fd80e26c1b4fb40c1a

And here's the code responsible for drawing what's in the screenshot: 
```go
func DrawTextInBox(dst *ebiten.Image, str string, font font.Face, x, y int) (int, int) {
	w, h := text.MeasureString(str, res.UIFont)
	wf, hf := float64(w), float64(h)

	m := font.Metrics()

	ebitenutil.DrawRect(dst, float64(x), float64(y - (m.Height.Round() - m.Descent.Round())), wf, hf - float64(m.Descent.Round()), color.Black)

	text.Draw(dst, str, font, x, y, color.White)

	return w, h + m.Descent.Round()
}

func (s *DebugScreen) Render(image *ebiten.Image) {
	fps := int(math.Round(ebiten.CurrentFPS()))
	w, h := image.Size()

	c := colorful.Hsv(s.hue, 1, 0.5)

	_ = image.Fill(c)

	strings := []string{
		s.GetTitle(),
		"Line 1",
		"    Line 2 with four spaces",
		"Line 3 abcdefg \nダミーテキスト",
	}

	strX := 10
	strY := 32

	for _, s := range strings {
		_, boxH := DrawTextInBox(image, s, res.UIFont, strX, strY)
		strY += boxH
	}

	strY += 4

	for _, s := range strings {
		_, boxH := DrawTextInBox(image, s, res.MonoFont, strX, strY)
		strY += boxH
	}

	_ = ebitenutil.DebugPrint(image, fmt.Sprintf("%02d FPS | %d×%d", fps, w, h))
}
```

I noticed that the black boxes for the sans-serif and monospace fonts have the same sizes, almost as if the sans-serif font face's metrics are being reused. Curiously, the monospace font's boxes are still out of whack even if I comment out the first for loop. Despite that, is anything getting cached anywhere or am I missing something else?

**Comment by hajimehoshi** [comment]
Hi,

Just a quick response: what about using BoundString? https://pkg.go.dev/golang.org/x/image/font?tab=doc#BoundString

I'll take a look at your issue carefully later.

**Comment by SamusAranX** [comment]
Turns out I had a copy/paste error in the first line of my DrawTextInBox function. 🤦
Instead of using the passed in font face, it always used the sans serif font to measure strings.
Changing that line to read `w, h := text.MeasureString(str, face)` makes it work with the monospace font as well:
![screenshot of fixed DrawTextInBox output](https://user-images.githubusercontent.com/676069/81614758-c973fa80-93e0-11ea-9f8e-e9a4701a46fb.png)

Thanks for the BoundString suggestion, I didn't even know that function existed!
It doesn't seem to handle newlines or spaces very well though:
![screenshot of BoundString output](https://user-images.githubusercontent.com/676069/81614651-a9dcd200-93e0-11ea-805f-fbb21a34d03f.png)

I also slightly adjusted my MeasureString function to handle ascending and descending accents better. The code's in my ebiten fork. Given that Go's built-in function doesn't handle whitespace, I'd say this would be a pretty good addition to ebiten's toolbox.
![screenshot of adjusted DrawTextInBox output](https://user-images.githubusercontent.com/676069/81619112-1cea4680-93e9-11ea-90f9-1f4cde8794df.png)

**Comment by hajimehoshi** [comment]
Now I've replaced this function with BoundString. The size of BoundString should be the same with MeasureString.
