### ISSUE TITLE
Smooth translation without vsync locked logic

### ISSUE THREAD

**Issue by KuliuTho** [hajimehoshi/ebiten#1156]
Heads up: Sorry if this is a broad question it might not even be ebiten specific but a hunch tells me it might be

So I've been working a small project to test out ebiten and thus far its really nice. I've ran into a small snag with the game im writting where unless I stick all of my player movement and camera logic into the render function with vsync enabled I get small micro jitters and the translation on my camera matrix isn't smooth

I've tried to make all of my logic snap to pixels but that doesn't help any

**Heres a quick example of my issue:** https://www.youtube.com/watch?v=SxVVSnb_Z98
**Heres the code used when jittering:** https://pastebin.com/kQEad4Dj
**and Heres the code used when I get smooth results:** https://pastebin.com/AVer7SNS

This is my window setup:

> 	ebiten.SetVsyncEnabled(true)
	ebiten.SetMaxTPS(ebiten.UncappedTPS)

Not sure if related but the screen is pixel perfect for the size of the sprites. layout size of 384, 216

Sorry again if this isnt ebiten related

**Comment by hajimehoshi** [comment]
Hi, thank you for using Ebiten! And thank you for sharing the issue. The video helps me to understand what's the problem!

I'd like to confirm when `(*PlayerControlComponent).Update` and `(*PlayerControlComponent).Render` are called. Which are you using `Run` or `RunGame`?

**Comment by KuliuTho** [comment]
> Hi, thank you for using Ebiten! And thank you for sharing the issue. The video helps me to understand what's the problem!
> 
> I'd like to confirm when `(*PlayerControlComponent).Update` and `(*PlayerControlComponent).Render` are called. Which are you using `Run` or `RunGame`?

I'm using ebiten.RunGame you're just seeing the top of my ECS system but the Update and Render functions are being routed down from the original Game struct

**Comment by KuliuTho** [comment]
> Hi, thank you for using Ebiten! And thank you for sharing the issue. The video helps me to understand what's the problem!
> 
> I'd like to confirm when `(*PlayerControlComponent).Update` and `(*PlayerControlComponent).Render` are called. Which are you using `Run` or `RunGame`?

Ultimately my issue is if I progress my entity by 1 pixel per display refresh and update my translation at the same time the result is a butter smooth camera translation. On the contrary if I move play player by some amount multiplied by the time since last frame (whether that be update or render) to keep it frame rate independent. It's not moving at a synced rate with the display anymore and it ends up jittering as its updating at a different rate to the screen. I am not entirely sure how I can fix this

**Comment by hajimehoshi** [comment]
So my question is, 

1) If you are using `ebiten.Run`, are you calling `Update` before `IsDrawingSkipped` and `Render` after `IsDrawingSkipped`?
2) If you are using `ebiten.RunGame`, are you calling `Update` in `Update` and `Render` in `Draw`?

**Comment by hajimehoshi** [comment]
> I'm using ebiten.RunGame you're just seeing the top of my ECS system but the Update and Render functions are being routed down from the original Game struct

Ah Ok, thanks

**Comment by KuliuTho** [comment]
> So my question is,
> 
> 1. If you are using `ebiten.Run`, are you calling `Update` before `IsDrawingSkipped` and `Render` after `IsDrawingSkipped`?
> 2. If you are using `ebiten.RunGame`, are you calling `Update` in `Update` and `Render` in `Draw`?

So yes sorry I forgot to mention Render is Draw yikes haha. But yes number 2 is what I’m doing.

**Comment by hajimehoshi** [comment]
First, TPS affects how often Update is called, while FPS (vsync) affects how often Draw is called.

https://pastebin.com/kQEad4Dj

I think the reasons why the above code fails are:

1) Render is called 60 times per second (if the display is 60 [Hz]), while Update is called much more times per second due to the uncapped TPS. With the uncapped TPS, there is no guarantee how often Update is called.
2) Then renderDelta is always around 1/60 [s]. However, as Update is called more often, this causes mismatches.

In general:

1) Handle inputting in Update, not Renderer. It is because logical updating should be done in Update.
2) As time-delta involves in the logical updating, you should take time-delta in Update rather than Render.

I was wondering why you are using the uncapped TPS, but if you use the default TPS (60), you can assume that the time delta is always 1/60 [s], which should be easier. What do you think?

**Comment by KuliuTho** [comment]
> First, TPS affects how often Update is called, while FPS (vsync) affects how often Draw is called.
> 
> https://pastebin.com/kQEad4Dj
> 
> I think the reasons why the above code fails are:
> 
> 1. Render is called 60 times per second (if the display is 60 [Hz]), while Update is called much more times per second due to the uncapped TPS. With the uncapped TPS, there is no guarantee how often Update is called.
> 2. Then renderDelta is always around 1/60 [s]. However, as Update is called more often, this causes mismatches.
> 
> In general:
> 
> 1. Handle inputting in Update, not Renderer. It is because logical updating should be done in Update.
> 2. As time-delta is related to the logical updating, you should take time-delta in Update rather than Render.
> 
> I was wondering why you are using the uncapped TPS, but if you use the default TPS (60), you can assume that the time delta is always 1/60 [s], which should be easier. What do you think?

See at first that’s exactly what I had. I had TPS set to 60 and my frame rate vsync. For whatever reason with vsync at 60hz and the update also at 60 they were still out of sync. It’s really just set to uncapped because I’ve been fiddling with settings to no avail. If I set TPS as 60 and uncap or vsync the update still isn’t synced with the display and I still get jittery camera movement ☹️

**Comment by KuliuTho** [comment]
> First, TPS affects how often Update is called, while FPS (vsync) affects how often Draw is called.
> 
> https://pastebin.com/kQEad4Dj
> 
> I think the reasons why the above code fails are:
> 
> 1. Render is called 60 times per second (if the display is 60 [Hz]), while Update is called much more times per second due to the uncapped TPS. With the uncapped TPS, there is no guarantee how often Update is called.
> 2. Then renderDelta is always around 1/60 [s]. However, as Update is called more often, this causes mismatches.
> 
> In general:
> 
> 1. Handle inputting in Update, not Renderer. It is because logical updating should be done in Update.
> 2. As time-delta is related to the logical updating, you should take time-delta in Update rather than Render.
> 
> I was wondering why you are using the uncapped TPS, but if you use the default TPS (60), you can assume that the time delta is always 1/60 [s], which should be easier. What do you think?

And I’m fully aware about doing logic in update. My ultimate goal is for handling all input in logic in update using delta time since last frame so I can have frame rate Independent movement and logic etc. but at the same time I need the camera to be smooth. The jittering is too distracting.

**Comment by hajimehoshi** [comment]
> I had TPS set to 60 and my frame rate vsync. For whatever reason with vsync at 60hz and the update also at 60 they were still out of sync. 

How did you take time-delta, or didn't take? Using time-delta in Render and using it in Update should not be correct anyway.

**Comment by KuliuTho** [comment]
> > I had TPS set to 60 and my frame rate vsync. For whatever reason with vsync at 60hz and the update also at 60 they were still out of sync.
> 
> How did you take time-delta, or didn't take? Using time-delta in Render and using it in Update should not be correct anyway.

So if you look at my last paste bins I tried doing it kinda through my component system to see if I could figure out if using time since last render would change but nothing really. For update delta time on my game struct I’m storing the lastTime the update was called (time.Time) and then when update is called again I’m getting the time.Since(lastTime).Seconds() to get the time in seconds since the last update call. Hints why I was using uncapped update so I can use this method instead of a locked 60 FPS. I’m then multiplying some fixed value for speed by the time since the last frame so that it’s always the same regardless on if the update was slower or faster. Ultimately it’s not really my issue.

**Comment by hajimehoshi** [comment]
Sorry let me confirm: you tried to use the default TPS and handling input in Update, but you found jittering, right? If so, I was wondering where you took the time delta.

**Comment by hajimehoshi** [comment]
> originally I was using the update deltatime but it’s no different from getting the render deltatime, issue still persists

OK so you took time-delta in Update but jittering remained, right?

**Comment by KuliuTho** [comment]
> > originally I was using the update deltatime but it’s no different from getting the render deltatime, issue still persists
> 
> OK so you took time-delta in Update but jittering remained, right?

Correct

**Comment by hajimehoshi** [comment]
I'd like to see and test your program. Would it be possible to share your entire program?

**Comment by KuliuTho** [comment]
> I'd like to see and test your program. Would it be possible to share your entire program?

Give me 5 minutes I'll condense it down into a smaller code base so easier to understandable

**Comment by hajimehoshi** [comment]
Thank you!

**Comment by KuliuTho** [comment]
> Thank you!

So I guess I'm not fully there or something because apon writing this little project I managed to get it working. I swore I tried 60 TPS with VSync enabled and it jitter but apon setting it like that now its working fine? So sorry for wasting your time...

**Comment by hajimehoshi** [comment]
No problem, I'm fine that you problem solved! :-)

Please feel free to reopen if you find the issue again.
