### ISSUE TITLE
graphicsdriver/opengl: Use an explicit way to detect GL context lost

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1176]
https://developer.android.com/reference/android/opengl/GLSurfaceView.Renderer.html#egl-context-lost

> There are situations where the EGL rendering context will be lost. This typically happens when device wakes up after going to sleep. When the EGL context is lost, all OpenGL resources (such as textures) that are associated with that context will be automatically deleted. In order to keep rendering correctly, a renderer must recreate any lost resources that it still needs. The onSurfaceCreated(javax.microedition.khronos.opengles.GL10, javax.microedition.khronos.egl.EGLConfig) method is a convenient place to do this.

**Comment by tomlister** [comment]
We can use onSurfaceCreated or I think we could just check if the texture atlas == null (but checking textures isn't best practice according to what I've read)

**Comment by hajimehoshi** [comment]
Yes, I think I'll be working on this now. Thanks.

**Comment by hajimehoshi** [comment]
> texture atlas == null

I'm not sure this, but I don't think we can take this way. A texture is held by Ebiten and cannot be null.

**Comment by tomlister** [comment]
Well I mean textures that make up the atlas in the gl context

**Comment by hajimehoshi** [comment]
The reference will never be null (but invalidated) when the context is lost.

**Comment by tomlister** [comment]
Oh so the pointer points to address that's invalid. Got it 👍
