### ISSUE TITLE
ebiten: Change the default of `RunnableOnUnfocused` to be true

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1180]
Now an Ebiten application suspends on unfocused by default. I thought this was a good default behavior, but now I am not sure as many existing games don't do this. Then, I'm thinking to change this behavior. As this is be a breaking change, this would be introduced in v2.

Any thoughts?

**Comment by silbinarywolf** [comment]
I think it makes sense to be unfocused by default.

- If I'm playing a single player game, I'd expect the game to pause/stop running on unfocus.
- If I'm playing a multiplayer game, then I'd expect it to keep running if I lost focus. (When testing a networked game too, you end up naturally realizing you need to disable pausing on unfocus and so you do so)

With that in mind I'd say most folks are going to be making single player games with Ebiten, so it probably makes sense to keep things that way.

**Comment by hajimehoshi** [comment]
> I think it makes sense to be unfocused by default.

You mean the game should be suspended when unfocused?

> With that in mind I'd say most folks are going to be making single player games with Ebiten, so it probably makes sense to keep things that way.

Makes sense, but Ebiten's suspension seems a little strong (e.g., stopping music) and I'm not confident this is a good way for the majority.

BTW, even if IsRunnableOnUnfocused() is true, the game developer can handle it by `IsFocused` and render a pause screen for example.
