### ISSUE TITLE
question: how do you count how many characters can be per line and how many lines can be per screen?

### ISSUE THREAD

**Issue by Huholoman** [hajimehoshi/ebiten#1186]
Hello,
Iam not sure this qeustion belongs here, but I have to ask somewhere O:)

I want to create "dialog box" and render text in it. But I need to know what is the width of one character (I do take a look at source code of text.Draw, so if there is not easier way, that should do it). Also there is DPI parameter and I have no idea how to work with it as Ebiten solves scaling automaticly.

Can someone give me at least some hint?

Thanks a lot,
Tobias

**Comment by hajimehoshi** [comment]
Hi,

I think this is a question about font.Face rather than Ebiten. 

For the character size, BoundString should work: https://godoc.org/golang.org/x/image/font#BoundString

For the DPI, TBH I'm not sure the details, but 72 would work in most cases.

**Comment by Huholoman** [comment]
Cool, thanks a lot! I did take a look at font.Face source code, but i didnt notice this function for some reason..

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen this when you find another issue.

**Comment by mortenson** [comment]
I did this recently for a game: https://github.com/mortenson/trianglovers/blob/8fe554fe1ed9583066a5c5ea505487243bfc9a21/shared.go#L131-L156

BoundString seems much easier if it works though!
