### ISSUE TITLE
Graphics are broken on Raspberry Pi 4

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1208]
Reported by @gravestench (OpenDiablo 2 team)

![image](https://user-images.githubusercontent.com/16950/85247349-6918b400-b488-11ea-959d-1f5248f1d5b5.png)

![image](https://user-images.githubusercontent.com/16950/85247326-569e7a80-b488-11ea-8638-5b07941b12d2.png)

**Comment by usedbytes** [comment]
Any thoughts on where to start debugging this one? I'm seeing issues on Raspberry Pi 4 which might be the same thing or related.

Yesterday, my sprites were just disappearing after a few frames (64-bit OS). Today I did a test on the 32-bit OS, and the sprites turn to corruption after a few frames and eventually disappear.

If I only draw a single thing, then it works OK. i.e. this works:
```
        op := &ebiten.DrawImageOptions{}
        op.GeoM.Translate(100, 100)
        screen.DrawImage(image1, op)
```

If I draw the same thing twice, it works:
```
        op := &ebiten.DrawImageOptions{}
        op.GeoM.Translate(100, 100)
        screen.DrawImage(image1, op)

        op = &ebiten.DrawImageOptions{}
        op.GeoM.Translate(200, 200)
        screen.DrawImage(image1, op)
```

But if I draw two different things, it doesn't:
```
        op := &ebiten.DrawImageOptions{}
        op.GeoM.Translate(100, 100)
        screen.DrawImage(image1, op)

        op = &ebiten.DrawImageOptions{}
        op.GeoM.Translate(200, 200)
        screen.DrawImage(image2, op)
```

**Comment by hajimehoshi** [comment]
Thanks. Which commit did you try? What about the latest one on the master branch?

**Comment by usedbytes** [comment]
The behaviour is the same on current tip of master (283de9b84740)

**Comment by hajimehoshi** [comment]
My guess is that there is an issue in Raspberry Pi's OpenGL driver. I'll try to omit VBO, which seems suspicious.

**Comment by hajimehoshi** [comment]
@usedbytes Could you try f73f940fe797aada979d5a9053961f61521c2d6d ? Thanks!

**Comment by hajimehoshi** [comment]
@gravestench tested that and it looks like this worked!

I'm trying to add a way to detect whether the machine is Raspberry Pi or not. Maybe reading /proc/cpuinfo would work?

**Comment by usedbytes** [comment]
Wow that was fast. That looks like it fixed it for me :-) To be honest it seems like the V3D driver does generally have some issues at the moment, hopefully it will mature over time.

Is there any way you can get at GLX extensions? e.g. I see this in `glxinfo`:
```
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Broadcom (0x14e4)
    Device: V3D 4.2 (0xffffffff)
    Version: 19.3.2
    Accelerated: yes
    Video memory: 7816MB
    Unified memory: yes
    Preferred profile: compat (0x2)
    Max core profile version: 0.0
    Max compat profile version: 2.1
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL vendor string: Broadcom
OpenGL renderer string: V3D 4.2
OpenGL version string: 2.1 Mesa 19.3.2
OpenGL shading language version string: 1.20
```
You could check for `V3D 4.2`.

`glxinfo` source is here: https://cgit.freedesktop.org/mesa/demos/tree/src/xdemos/glxinfo.c

**Comment by hajimehoshi** [comment]
That's a great information! I think I can detect the device by the GLX function!

> To be honest it seems like the V3D driver does generally have some issues at the moment, hopefully it will mature over time.

What about VC4 driver (for Raspberry Pi 3)? IIUC, V3D is for Raspberry Pi 4.

**Comment by usedbytes** [comment]
Yeah indeed, V3D is only for Pi 4, and VC4 (or the Broadcom proprietary driver) for all other versions of the Pi.

My guess is VC4 is much more mature. I don't currently have an older Pi set-up, and I've never tried ebiten on one, but probably it works fine if no-one has complained? I can dig one out and try it over the weekend if it will be useful.

The GPU in the Pi 4 is totally different, which is the reason for the separate (new) driver.

**Comment by hajimehoshi** [comment]
Acknowledged. Hmm, I'll try to disable PBO only when the graphics driver is V3D. Let's revisit when we find issues on VC4. Thanks!

**Comment by hajimehoshi** [comment]
eb1e2802a298993e37df7c3876b42be1a1ec0666 I created a commit disabling PBO only when the graphics driver is V3D based on https://github.com/hajimehoshi/ebiten/issues/1208#issuecomment-662675241. @usedbytes @gravestench does this commit work on your Raspberry Pi 4? Thanks!

**Comment by usedbytes** [comment]
I left a comment over there. "VENDOR" should be "DEVICE" - but with that it works great. Thanks!
```
diff --git a/internal/graphicsdriver/opengl/gl/package_x.go b/internal/graphicsdriver/opengl/gl/package_x.go
index 16f9402e..26c2a9c9 100644
--- a/internal/graphicsdriver/opengl/gl/package_x.go
+++ b/internal/graphicsdriver/opengl/gl/package_x.go
@@ -17,7 +17,7 @@ package gl
 //
 //   static const char* rendererDevice;
 //   if (!rendererDevice) {
-//     rendererDevice = queryString(GLX_RENDERER_VENDOR_ID_MESA);
+//     rendererDevice = queryString(GLX_RENDERER_DEVICE_ID_MESA);
 //   }
 //
 //   return rendererDevice;
```
