### ISSUE TITLE
Do not create independent images with padding for SubImage

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1218]
Now sub-images are allocated independently on an internal texture atlas (https://github.com/hajimehoshi/ebiten/issues/896). This was good to simplify shaders by removing source-region checks. However, this caused some issues:

1) The number of graphics commands to replace pixels on GPU has been much increased
2) If `SubImage` function is called many times with a-little different regions, images on the texture atlas are allocated for each call and this consumes a lot of memory.

Then, I have decided to add following changes:

1) Don't let Ebiten create an independent image on the texture atlas for `SubImage`.
2) The original image is still allocated with paddings on the texture atlas.
3) A sub-image is a part of its original image on the texture atlas.

As the shader no longer has source-region checks, rendering sub-images with rotating or scaling GeoM can expose their adjacent pixels in the texture atlas, but I believe this is rare. Although this is a breaking change to be exact, this should be a good solution to balance the shader performance, the shader simplicity (which is important for custom shaders in the future), and backward compatibility.

CC @wasedaigo

**Comment by gabstv** [comment]
Is this change better for when you use an already defined atlases? I tend to create atlases externally and use sub images of it for the sprites.

**Comment by hajimehoshi** [comment]
If you use subimages with scaling or rotating GeoM, I recommend to add gaps (paddings) between the images. I think most of texture packer should have such option to add gaps.

**Comment by hajimehoshi** [comment]
I think I'll write a blog article about this change.

**Comment by hajimehoshi** [comment]
Wrote an article about this: https://ebiten.org/blog/subimage.html
