### ISSUE TITLE
examples/shader: Add an example for lighting with a normal map

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1234]

**Comment by kyeett** [comment]
I can probably do this if you want. 

Do you have anything special in mind? 

This is pretty cool:
https://blog.selfshadow.com/sandbox/normals.html

**Comment by hajimehoshi** [comment]
That'd be a great help! I don't have any special requests. Do we need handling multiple images?

**Comment by kyeett** [comment]
I think multiple images is not required, but would be make the example a bit cooler. 

I didn't know normal maps existed before today, so I'll take a while to familiarize myself with the concept :-)

**Comment by kyeett** [comment]
![normal_map](https://user-images.githubusercontent.com/737646/87338424-73891380-c545-11ea-8bff-635b8e48503b.gif)

First go

**Comment by kyeett** [comment]
This is fantastic :-) 
http://mattdesl.github.io/kami-demos/release/normals-pixel.html

**Comment by hajimehoshi** [comment]
https://gyazo.com/71694373d534a1e1e6e57a14197a3630

I found a tool (https://www.codeandweb.com/spriteilluminator) and succeeded to create a normal map.

@kyeett I'll be working on adding a new example with this. Sorry if you've already started, but is that fine to you?

**Comment by kyeett** [comment]
@hajimehoshi no problem! Glad you got it to work!
