### ISSUE TITLE
shader: wrap: repeat

### ISSUE THREAD

**Issue by kyeett** [hajimehoshi/ebiten#1240]
A very useful thing in shadertoy is that you can say what will happen if the coordiate `uv` that is outside of the image. 
The options are wrap and clamp. Repeat just repeats the image, and clamp takes the highest possible value of the image. 

**Example:**

The following code
```c
void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
    vec2 uv = fragCoord/iResolution.xy;
    uv.x *= 4.0;
    
    fragColor = texture(iChannel0,uv);
}
```

**wrap:repeat**
![image](https://user-images.githubusercontent.com/737646/86540686-7bbece80-bf07-11ea-8429-209bcec1cd80.png)

This is done by the dropdown here:
![image](https://user-images.githubusercontent.com/737646/86540695-92652580-bf07-11ea-9214-9cffcbabc05d.png)

**wrap:clamp**
![image](https://user-images.githubusercontent.com/737646/86540702-ad379a00-bf07-11ea-8c72-72c579d2ded6.png)

**code**:
https://www.shadertoy.com/view/tlSczm

**Comment by hajimehoshi** [comment]
Hi,

This is not so simple for Ebiten because Ebiten has automatic texture atlases. Then we cannot use OpenGL's default feature.

You would be able to emulate this by calculating based on the position and the region. (This requires the functions to get the sizes of the images)

**Comment by kyeett** [comment]
I understand. I'll close this request then :-)
