### ISSUE TITLE
Error running example from documentation documents//install.html

### ISSUE THREAD

**Issue by alexandreliberato** [hajimehoshi/ebiten#1244]
When running this command:
`
go run -tags=example github.com/hajimehoshi/ebiten/examples/rotate
`
I got theses errors:
![image](https://user-images.githubusercontent.com/300424/87237375-ee2e2380-c3cb-11ea-9e1f-1a17fdd624dc.png)

Yes, I do have a gamepad plugged in the computer.

[error.log](https://github.com/hajimehoshi/ebiten/files/4907913/error.log)

**Comment by hajimehoshi** [comment]
Thanks. This seems the same issue as #1229, and this is an external issue...
