### ISSUE TITLE
shader: can't use variables in for-loop condition

### ISSUE THREAD

**Issue by kyeett** [hajimehoshi/ebiten#1246]
### Code
```go
func Fragment(position vec4, texCoord vec2) vec4 {
	v := texCoord
	someVariable := 4.0
	for i := 0; i < someVariable; i++ {
		v.x += 0.01
	}
	return texture0At(v)
}
```

### Error
```
for-statement must follow this format: for (varname) := (constant); (varname) (op) (constant); (varname) (op) (constant) { ...
```

**Comment by hajimehoshi** [comment]
Unfortunately this is a specification (derived from GLSL ES)

**Comment by hajimehoshi** [comment]
See Appendix A 4 Control flow:
https://www.khronos.org/registry/OpenGL/specs/es/2.0/GLSL_ES_Specification_1.00.pdf

**Comment by kyeett** [comment]
Cool. It seems I should be able to use an if-statement plus break to achieve the same behavior. I'll try it later
