### ISSUE TITLE
Use github.com/go-gl/gl instead of go-gl/glow

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#125]

**Comment by peterhellberg** [comment]
I was just about to open a new issue about this when I noticed this one.
I currently have to locally change it to `github.com/go-gl/gl/v3.2-core/gl` in order to build my code.

(Also the go-gl/glow import doesn’t work on Travis-CI)

**Comment by hajimehoshi** [comment]
Thank you for noticing me. I'll be working on this asap.

**Comment by hajimehoshi** [comment]
Now it seems that Ebiten can be built on Travis CI.
