### ISSUE TITLE
gpu: Export globals NvOptimusEnablement and AmdPowerXpressRequestHighPerformance to force high-perf rendering

### ISSUE THREAD

**Issue by silbinarywolf** [hajimehoshi/ebiten#1252]
**The problem**
For laptops with multiple GPUs, its likely that applications wont launch using the discrete GPU, but rather than integrated GPU. This can lead to games under-performing by default which is less than ideal.

**Proposed solution**
Investigate possible ways we can set these global variables so that Ebiten applications will use the more powerful CPU.
Ideally, I'd like to see if we could achieve this without CGo, but at the very least, someone was able to get this behavior working (see the last reply in this thread)
https://groups.google.com/forum/#!topic/golang-nuts/7OHZcXUegF0

**Examples of other lib implementations**
- SFML uses an opt-in #define: https://github.com/SFML/SFML/commit/9a453ed9e3846e9f7998295b8966428a9a0b86f6#diff-93134bfcdd8e19cbd5fe05a57a658950R63

**Other related resources:**
- https://gist.github.com/statico/6809850727c708f08458
- https://docs.nvidia.com/gameworks/content/technologies/desktop/optimus.htm

**Comment by hajimehoshi** [comment]
Hi, thank you for your suggestion.

Is this issue only for Windows?

**Comment by hajimehoshi** [comment]
> Ideally, I'd like to see if we could achieve this without CGo, but at the very least, someone was able to get this behavior working (see the last reply in this thread)

Hm, as long as this requires Cgo, Ebiten cannot adopt this.

As this option can be applied on the user side, adding a tip to the documentation sounds fine. What do you think?

**Comment by silbinarywolf** [comment]
I think that sounds like a good idea. I spent some of the day exploring some options but couldn't find a way to do this without CGo unfortunately :(

I was able to put a library together with tests though, so should the documentation on Ebiten just point here?
https://github.com/silbinarywolf/preferdiscretegpu

**Comment by hajimehoshi** [comment]
Thanks! I think I'll update [performance tips](https://ebiten.org/documents/performancetips.html) with your link. Thank you for your experiments!
