### ISSUE TITLE
ebiten: Disable the user-defined vertex (not fragment) shader

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1253]
I think a user-defined vertex shader is less useful than a fragment shader. I'd like to omit the capability to enable to define the user-defined vertex shader in order to simplify the API. In the future, we might add a feature to enable to define one.

@kyeett any thoughts?

**Comment by kyeett** [comment]
Makes sense to me! Ive only used fragment shaders, really.
