### ISSUE TITLE
use //go:embed to embed files

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1258]
https://go.googlesource.com/proposal/+/master/design/draft-embed.md

**Comment by gabstv** [comment]
TIL! Great!

**Comment by hajimehoshi** [comment]
I'll use this when Go 1.17 is released (not Go 1.16). Then probably in August 2021.

**Comment by dnnnvx** [comment]
My two cents: works fine using the new `embed` feature in `go v1.16`, like this

```go
import (
	"bytes"
	"embed"
	"image"
	"log"

	_ "image/png"

	"github.com/hajimehoshi/ebiten/v2"
)

//go:embed assets/*
var assetsFolder embed.FS

imgByte, err := assetsFolder.ReadFile("assets/main/idle.png")
if err != nil {
	log.Fatalln(err)
}
img, _, err := image.Decode(bytes.NewReader(imgByte))
if err != nil {
	log.Fatalln(err)
}
ebitenImg := ebiten.NewImageFromImage(img)
```

**Comment by hajimehoshi** [comment]
Let's do this after Debian's default Go version is 1.16 or newer.

**Comment by hajimehoshi** [comment]
Debian Bookworm (probably with Go 1.19) will be released in 2023-09, maybe.

**Comment by hajimehoshi** [comment]
Note to myself:

We deterine the Go version by min(Debian's stable [1], Ubuntu's stable [2])

[1] https://packages.debian.org/stable/golang
[2] https://packages.ubuntu.com/jammy/golang (The URL indicates Ubuntu 22, rather than the stable)
