### ISSUE TITLE
Broken JavaScript in Safari due to use of $global.AudioContext

### ISSUE THREAD

**Issue by peterhellberg** [hajimehoshi/ebiten#126]
The experimental audio support breaks the JavaScript in the current Safari on OS X (and Mobile Safari)

```js
TypeError: undefined is not a constructor (evaluating 'new($global.AudioContext)()')
```

### A quick workaround (by disabling audio)
Returning directly at the start of the `initialize()` and `start()` functions of `audio_js.go` "solves" this issue in the desktop version of Safari, still broken in Mobile Safari though.

**Comment by hajimehoshi** [comment]
Made sure I could reproduce that. I'm fixing this now.

**Comment by hajimehoshi** [comment]
Fixed. There is still no sound on Safari, and this is another new bug.
