### ISSUE TITLE
ebiten: Remove the argument from Game.Update

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1260]
As we can get the size via Layout, we don't have to use the argument at Update.

I set the milestone at v2.1.0, but might change this later.

**Comment by andreykaipov** [comment]
Hi - I'm new to this library and game programming in general. I was looking through the docs for a better understanding of the two different game loops `Update` and `Draw`, and I think this issue just answered my question. I tried drawing my screen from the `Update` loop, but nothing happened, so it made me wonder why `Update` even takes a screen argument in the first place. I guess it doesn't need one at all!

What's the intended interaction between the two game loops? Is `Update` meant for modifying our game's state, while `Draw` strictly only reads from it? We shouldn't ever modify the state while drawing as good practice, right?

**Comment by hajimehoshi** [comment]
Update's argument is just for backward compatibility. This is confusing and I plan to remove this at v2.

>  Is Update meant for modifying our game's state, while Draw strictly only reads from it? We shouldn't ever modify the state while drawing as good practice, right?

Yes, that's correct! Update is called 60 times per second by default (you can change this by SetMaxTPS), while Draw depends on the refresh rate of your display.

**Comment by andreykaipov** [comment]
Thanks so much for the quick response and clarification! I appreciate it. 😄
