### ISSUE TITLE
Please Consider exposing a NewImage() that is volatile (for multiple offscreen buffers)

### ISSUE THREAD

**Issue by gabstv** [hajimehoshi/ebiten#1265]
Hello! I was fiddling with offscreen buffers (split screens), and I exposed a variant of `ebiten.NewImage()` that is volatile.
By the test results, my assumption seems to be correct. That it would be more performant if we could use the volatile version of `NewImage` for offscreen buffers.

Here's the example using `ebiten.NewImage(w/2, h, ebiten.FilterDefault)` (x2):
https://ppusers-temp-github.s3.amazonaws.com/gabs/ebiten_drawimage.mp4

As soon as the split screen scene is loaded, on the background you can notice some stuttering (it's a tiled 256x256 image). It seems to get a little better after the 30 second mark.

Here's the same scene, but with a forked version Ebiten to expose `ebiten.NewScreenBufferImage(w/2, h, ebiten.FilterDefault)` (x2):
https://ppusers-temp-github.s3.amazonaws.com/gabs/ebiten_volatileimage.mp4

The background plane seems to be running with no stuttering at all! This is great news!

Here's the code I used for the volatile image. The only difference from the `NewImage` is `volatile=true`:

```go
// NewScreenBufferImage returns an empty image optimized to be used as an offscreen buffer.
//
// If width or height is less than 1 or more than device-dependent maximum size, NewScreenBufferImage panics.
//
// filter argument is just for backward compatibility.
// If you are not sure, specify FilterDefault.
func NewScreenBufferImage(width, height int, filter Filter) *Image {
	return newImage(width, height, filter, true)
}
```

Binaries (macOS only):
[default version](https://ppusers-temp-github.s3.amazonaws.com/gabs/camera_default_ebiten_macos)
[volatile version](https://ppusers-temp-github.s3.amazonaws.com/gabs/camera_volatile_ebiten_macos)

**Comment by hajimehoshi** [comment]
Hi,

I'm not sure what is the stuttering in your videos. Perhaps this scene in the first video?

![image](https://user-images.githubusercontent.com/16950/88461618-016ae400-cee0-11ea-8023-0ff6936e1397.png)

Even if so, I'm not sure why the volatile image solved this.

I'd like to avoid exposing a new state for an image as much as possible, then I hesitate to expose the volatile option. Moreover, in theory, volatile images are efficient only when 'restoring' from the context lost is enabled (i.e., only on Android).

**Comment by gabstv** [comment]
Maybe it's not very noticeable on the videos, but I guess that another benefit of the current implementation of volatile images is that they don't calculate mipmaps.

**Comment by hajimehoshi** [comment]
Mipmap images are created on the fly, so they should not be burden. I don't think the calculation cost really matters.

>  The background scrolling seems to be more smooth.

What about FPS? (TPS seems 60 in both cases)

**Comment by gabstv** [comment]
I did a stress test. Thousands of quads being created and destroyed every second. While the average FPS isn't very different, the actual background scrolling is.

Default `ebiten.NewImage()` (x2):
https://ppusers-temp-github.s3.amazonaws.com/gabs/stress_test_default.mp4

I think that in this case, the avg FPS differs too much from the lowest FPS. Maybe a single frame is taking like 1/3 of a second, and the other frames are faster (so the avg FPS is still 10~14).

Volatile (x2):
https://ppusers-temp-github.s3.amazonaws.com/gabs/stress_test_volatile.mp4

**Comment by hajimehoshi** [comment]
That's a very interesting result. Would it be possible to take a CPU profile? (e.g., by https://github.com/pkg/profile)

**Comment by gabstv** [comment]
[default.pdf](https://github.com/hajimehoshi/ebiten/files/4976251/default.pdf)
[volatile.pdf](https://github.com/hajimehoshi/ebiten/files/4976252/volatile.pdf)

**Comment by hajimehoshi** [comment]
Thanks! Hmm, I don't see a significant differences from the two pprof results.

> Thousands of quads being created and destroyed every second. 

Are you calling NewImage every frame or every second? I'm afraid this doesn't reflect the actual usage of Ebiten API.

> If the mipmaps are not the issue, something else is.

From the code, mipmap is suspicious, but we cannot say anything about this. At least, the pprof results doesn't say anything about mipmap...

**Comment by hajimehoshi** [comment]
I'll try to skip mipmap calculation when possible (e.g., we can detect the possibility of skipping from the GeoM value)

**Comment by hajimehoshi** [comment]
Now the mipmap calculation is skipped when possible. Could you take a look?

**Comment by gabstv** [comment]
> Are you calling NewImage every frame or every second? I'm afraid this doesn't reflect the actual usage of Ebiten API.

I only create two images at the start (half width; full height). They would only be recreated if the screen resized. 

I tested again after your changes, and the performance is now the same as the volatile image!

Default:
https://github.com/gabstv/primen/blob/feature/camera/examples/camera/main.go

Volatile:
https://github.com/gabstv/primen/blob/gtvebiten/examples/camera/main.go

I guess there's no need to use volatile anymore. Thank you! (I guess this can be closed now)

**Comment by hajimehoshi** [comment]
Thank you for experimenting!
