### ISSUE TITLE
Broken mobile build on windows?

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#1266]
I regularly build for android from a windows machine, and recently found this error on my build machine:

```
gomobile: go build -ldflags -w -trimpath -buildmode=c-shared -o C:\Users\corfe\AppData\Local\Temp\gomobile-work-312184635\lib\armeabi-v7a\libgo_.so goincremental failed: exit status 2
# pkg-config --cflags  -- gl gl
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
Package gl was not found in the pkg-config search path.
Perhaps you should add the directory containing `gl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'gl' found
pkg-config: exit status 1
```

I checked various commits until I found this commit was the culprit (syncing before it, the problem goes away): https://github.com/hajimehoshi/ebiten/commit/75d34ab585a06ab2210ac1a9fee48c7bc1d914d0

I suspect file "internal/graphicsdriver/opengl/gl/package_x.go" isn't supposed to build on windows, but accidentally is.

**Comment by hajimehoshi** [comment]
Thanks.

`package_x.go` specified build tags and should not affect Windows, but let me check.

**Comment by hajimehoshi** [comment]
Reproduced this on my macOS.
