### ISSUE TITLE
vector: Add GeoM to FillOptions

### ISSUE THREAD

**Issue by nanoslayer** [hajimehoshi/ebiten#1268]
It would be useful to add `ebiten.GeoM` to `vector.FillOptions`, so that you do not have to manually translate, scale, and rotate each point.

**Comment by hajimehoshi** [comment]
I'm leaning toward avoiding GeoM for APIs specifying vertices directly, as vertices are kind of low-level things. Let me think.

**Comment by nanoslayer** [comment]
After thinking about it more I realized that you could use `(*ebiten.GeoM).Apply` to easily transform the vertices. So I don't think it is necessary to add it to `vector.FillOptions`.
