### ISSUE TITLE
text: Please add more detailed documentation to text.Draw

### ISSUE THREAD

**Issue by Anthony-Fiddes** [hajimehoshi/ebiten#1271]
Hello! I was kindly wondering what it means for text to be rendered at a "'dot' (period position)"? I'm creating a little Sudoku program with this library and I'm having trouble figuring out how to calculate the x and y for this function such that the number is rendered in the exact center of each tile. 

If it helps, you can see my code [here](https://github.com/Anthony-Fiddes/sudoku/tree/draw). Thank you very much! 

P.S. This is an amazing library and I've been having a lot of fun using it thus far!

**Comment by hajimehoshi** [comment]
Hi,

The document says that " (x, y) represents a 'dot' (period) position.", and this means that if a given text consists of a single character `.`, this is positioned at the given position (`x`, `y`). Does this make sense? I'm not sure how to improve the text (disclaimer: I'm not an English native speaker).

**Comment by Anthony-Fiddes** [comment]
Your English is awesome! I was just having trouble because I was not familiar with the concept of a dot position, and I can't find it in a Google search.

In regards to the documentation, what you just said gives me some better insight! I think you could add what you just said to make it more clear. An additional sentence like: "This means that if the given text consisted of a single character ".", it would be positioned at the given position (x, y)." 

Some additional questions I have are:
  - When there is more than a single character, does this mean that the text begins rendering at that dot position? e.g. ".A" would render with the "." at the given (x, y) (I assume so)
 - Do you know how to adjust for this dot positioning in calculating how the text might be centered in a given window?

**Comment by hajimehoshi** [comment]
Thank you for the feedback!

> When there is more than a single character, does this mean that the text begins rendering at that dot position? e.g. ".A" would render with the "." at the given (x, y) (I assume so)

Yes, that's correct.

> Do you know how to adjust for this dot positioning in calculating how the text might be centered in a given window?

You can get the bounds of the text by BoundsString (https://pkg.go.dev/golang.org/x/image/font?tab=doc#BoundString). The rectangle's origin point should be the dot position. Then you can adjust the position as you like with this information.

**Comment by Anthony-Fiddes** [comment]
Thank you so much for working on such a wonderful tool and clarifying for me! I really appreciate it!

**Comment by hajimehoshi** [comment]
Added some comments based on your feedback. Thank you for the feedbacks, and using Ebiten!

**Comment by hajimehoshi** [comment]
Based on the feedback, I've added `BoundString` function, which returns the actual rendered area, and the origin position is the dot position. This should be useful to adjust the text position as you like.
