### ISSUE TITLE
shader: Builtin functions: image[N]TextureBoundsAt

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1287]
As multiple images can be on one texture atlas, it is sometimes necessary to know the source region of the image.

BTW, for consistency, we might rename the functions:

* texture[N]At should be renamed to image[N]At?
* textureDstSize and texture[N]Size remain as they return the texture atlas' size.
  * image[N]TextureSize might be better.

CC @tomlister

**Comment by hajimehoshi** [comment]
I realized that the region can be calculated from the image size:

`(0, 0) - ((the image width) / texture[N]Size.x, (the image height) / texture[N]Size.y)`

**Comment by nanoslayer** [comment]
After updating Ebiten to the latest version, I noticed that my frame rate was really slow. I traced the issue to this commit (`69f87d5`).

The camera example seems to replicate this behavior as well. Zooming and moving around causes it to stagger.

**Comment by hajimehoshi** [comment]
Thanks! This seems relatively critical. I'm investigating now.

**Comment by tomlister** [comment]
Yeah same here

**Comment by nanoslayer** [comment]
Note that the problem was resolved in commit [`d4042a5`](https://github.com/hajimehoshi/ebiten/commit/d4042a5cfa6fe02258f6abb1d6465d18346adc28) (see issue #1293).
