### ISSUE TITLE
shader: Implement casting float to integer

### ISSUE THREAD

**Issue by nanoslayer** [hajimehoshi/ebiten#1289]
Sometimes it is necessary to cast a float to an integer, or vice versa.

```go
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
	// Get the x coordinate in pixels
	x := int(texCoord.x * imageDstTextureSize())
	// Do stuff with x
}
```

**Comment by hajimehoshi** [comment]
Thanks. Now i'm looking for how to do this in Metal.

**Comment by tomlister** [comment]
Supporting material.
[https://developer.apple.com/metal/Metal-Shading-Language-Specification.pdf](MSL Spec PDF) **Page: 52**

**Comment by hajimehoshi** [comment]
This is different. as_type is a reinterpret cast.

**Comment by tomlister** [comment]
Ah my bad.

**Comment by hajimehoshi** [comment]
As C/C++'s convention, just a cast `(int)(x)` should work.

**Comment by hajimehoshi** [comment]
Oh `static_cast` is available!

> The static_cast operator is used to convert from a scalar or vector type to another scalar or
vector type with no saturation and with a default rounding mode. (When converting to floatingpoint, round to nearest; when converting to integer, round toward zero.) If the source type is a
scalar or vector Boolean, the value false is converted to zero and the value true is converted
to one.

**Comment by hajimehoshi** [comment]
@nanoslayer Does the latest commit work to you?

**Comment by nanoslayer** [comment]
It seems to be working so far.

**Comment by hajimehoshi** [comment]
Thanks!
