### ISSUE TITLE
Performance regression after passing source-region rectangles

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1293]
The culprit: 69f87d5fd144d641ac6781067a09e994c7d0dab2

Reported by @nanoslayer

**Comment by hajimehoshi** [comment]
Simply examples/sprites shows much lower FPS.

**Comment by hajimehoshi** [comment]
Confirmed that the number of draw calls were much increased.

**Comment by nanoslayer** [comment]
That seems to have resolved the issue. Thanks!

**Comment by nanoslayer** [comment]
Unfortunately I still get some stuttering when running my game with full zoom out.

**Comment by hajimehoshi** [comment]
Oh, is there a difference in CPU usages? 🤔
