### ISSUE TITLE
shader: Faster way to pass textures

### ISSUE THREAD

**Issue by nanoslayer** [hajimehoshi/ebiten#1300]
I began using arrays instead of textures to pass colors to the shader because storing images and calling `ReplacePixels` was very slow. Since my arrays are sufficiently large, they exceed OpenGL's limits, so I can no longer use them. Is there a faster way of sending texture data to the shader?

**Comment by hajimehoshi** [comment]
I don't think it is (portably) possible. Even though you could pass byte arrays as a uniform variable, this means passing a data from CPU side to GPU side, and would be substantially same as ReplacePixels.

**Comment by nanoslayer** [comment]
Is it possible to speed up `ReplacePixels`? Would passing floats instead of integers make a difference?

Or perhaps there can be a lower-level API to directly manipulate the texture data?

**Comment by hajimehoshi** [comment]
I don't think so: there are no other way to make it faster as far as I know.

> Or perhaps there can be a lower-level API to directly manipulate the texture data?

Ebiten already does a similar thing (Pixel Buffer Object). However, as long as the GPU memory is separated from the CPU side, it is inevitable to pay the cost of sending the data.

**Comment by nanoslayer** [comment]
Thank you for taking the time to answer my questions!
