### ISSUE TITLE
ebiten/audio - Clicking or popping distortion when playing certain wavs.

### ISSUE THREAD

**Issue by tomlister** [hajimehoshi/ebiten#1312]
All of the files are the same sample rate.

Shorter files seem to have the most clicking.

**Comment by hajimehoshi** [comment]
Could you give me the file, and the code to reproduce the issue if possible?

**Comment by tomlister** [comment]
Code: https://github.com/tomlister/tilegame/blob/b693740b18a0986db6b5181675d505689588d2b9/crafting.go#L38
Audio File: https://github.com/tomlister/tilegame/blob/master/assets/hover.wav

**Comment by hajimehoshi** [comment]
I'm trying your tilegame. When does the audio play?

**Comment by tomlister** [comment]
A lot of stuff is superficial for now. Press c and hover over a craftable item.

**Comment by hajimehoshi** [comment]
You are loading wav file directly at `importSound`. You need to decode wav file by [`github.com/hajimehoshi/ebiten/audio/wav`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/audio/wav?tab=doc)

**Comment by tomlister** [comment]
Cheers. Interesting, WAV must be close enough to PCM for the audio player to play some files well enough.

**Comment by hajimehoshi** [comment]
>  Interesting, WAV must be close enough to PCM for the audio player to play some files well enough.

It's close, but different. WAV file includes some chunks for meta data.

Let me close this :-)
