### ISSUE TITLE
ebiten: Rename `SetClearingScreenSkipped` / `IsClearingScreenSkipped`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1315]
There are some candidates like

* `SetScreenClearedEveryFrame` / `IsScreenClearedEveryFrame`
* `SetSkipClearScreen` / `IsSkipClearScreen`
* `EnableClearScreen` / `DisableClearScreen` / `IsScreenCleared`
* `SkipClearScreen`?

CC @tomlister

**Comment by tomlister** [comment]
SetScreenClearing? IsScreenClearing?

**Comment by hajimehoshi** [comment]
`ScreenClearing` seems concise but a little unclear. I think I'll go with `SetScreenClearedEveryFrame` / `IsScreenClearedEveryFrame` for explicitness.
