### ISSUE TITLE
How to  enable antialias?

### ISSUE THREAD

**Issue by ZhouGongZaiShi** [hajimehoshi/ebiten#1321]
Does `ebiten` support `antialias`?   
On some android devices with lower pixels, the edges of the drawn text have obvious jagged edges. I want to improve it.

**Comment by hajimehoshi** [comment]
Hi,

If you are talking about rendering, that's the glyph's responsibility and not Ebiten's responsibility.

Some devices might have >1 device pixel ratio. For high quality rendering with such devices, see https://github.com/hajimehoshi/ebiten/blob/master/examples/highdpi/main.go#L102-L107

Thanks,

**Comment by ZhouGongZaiShi** [comment]
Thank you very much! 
referring to the highdpi example, my issue was solved.
