### ISSUE TITLE
shader: NewShader doesn't return error for "No definition of main in fragment shader"

### ISSUE THREAD

**Issue by tomlister** [hajimehoshi/ebiten#1323]
NewShader doesn't return any error when the shader program in Kage is converted to its respective shader language.
This causes the shader program to crash when OpenGL or Metal (I presume) fails to find a main function.

`2020/08/31 20:56:45 opengl: program error: ERROR: No definition of main in fragment shader`

**Comment by hajimehoshi** [comment]
Thanks! I'll be addressing on this

**Comment by tomlister** [comment]
👍
