### ISSUE TITLE
Consider to change Uniform variables from []interface

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1324]
`[][]float32`?

**Comment by hajimehoshi** [comment]
Or, `map[string][]float32`?

CC @tomlister

**Comment by tomlister** [comment]
Additionally you could then write a function to set variables similar to Unity, eg: `op.setUniform("LightPos", []float32{})`

**Comment by hajimehoshi** [comment]
Decided to adopt `map[string]interface`.
