### ISSUE TITLE
ebiten: Brush up shader APIs

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1325]
Now there are APIs to use shaders

  * DrawImage
  * DrawRectShader
  * DrawTrianglesShader

And there are some builtin functions for shaders

  * imageSrcTextureSize / imageDstTextureSize
  * imageSrcTextureSourceRegion
  * image[N]TextureAt
  * image[N]TextureBoundsAt

I'm not satisfied with this yet. I think the API can be more minimal and simple. For example, I think it is fine to merge DrawTriangles and DrawTrianglesShader, like what DrawImage does. For builtin functions, they can be more consistent and concise.

**Comment by hajimehoshi** [comment]
I'll rename

 * imageSrcTextureSourceRegion -> imageSrcTextureRegion
 * image[N]TextureAt -> imageSrc[N]At
 * image[N]TextureBoundsAt -> imageSrc[N]BoundsAt

CC @tomlister @nanoslayer

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/dd7b0d81ae0e872d7ca59c38a8c44cb7a21eb5a1

**Comment by tomlister** [comment]
Seems like a good fit 👍

**Comment by hajimehoshi** [comment]
`imageSrc[N]BoundsAt` sounds a little odd but I didn't come up with a better name. `imageSrc[N]AtWithBoundaryCheck` seems verbose.

**Comment by hajimehoshi** [comment]
My current plan:

* `imageSrc[N]At` -> `imageSrc[N]Color`
* `imageSrc[N]At` -> `imageSrc[N]ColorUnsafe`

**Comment by hajimehoshi** [comment]
Now there are APIs to use shaders

* `DrawImage`
* `DrawRectShader`
* `DrawTriangles`

And there are some builtin functions for shaders

* `imageSrcTextureSize` / `imageDstTextureSize`
* `imageSrcTextureRegion`
* `image[N]UnsafeAt`
* `image[N]At`

**Comment by tomlister** [comment]
Good stuff 👍

**Comment by hajimehoshi** [comment]
||Number of source images|How source images are specified|
|-|-|-|
|DrawImage [1]|1|An argument|
|DrawRectShader [2]|0 to 4|An option|
|DrawTriangles|0 to 4|An argument and an option [3]|

[1] DrawImage now can take a shader, but is this needed?
[2] DrawRect seems more consistent?
[3] This might be changed in the future #1352

**Comment by hajimehoshi** [comment]
I'll change the API like this for consistency:

||Number of source images|How source images are specified|Shader|
|-|-|-|-|
|DrawImage|1|An argument|No|
|DrawRectShader|0 to 4|An option|Yes|
|DrawTriangles|1|An argument|No|
|DrawTrianglesShader|0 to 4|An option|Yes|

Sorry for going back and forth.

**Comment by hajimehoshi** [comment]
OK let's go with them and see how things go!
