### ISSUE TITLE
Different game and screen sizes

### ISSUE THREAD

**Issue by nanoslayer** [hajimehoshi/ebiten#1335]
My game has a lot of detailed art in it. The screen is treated as 960x540 pixels, but I would like to use all the available pixels on the screen to show more detail. Is there a way to treat the screen as 960x540 pixels for position calculation while actually drawing to a 1920x1080 pixel screen? Could this be achieved with a global scale factor?

**Comment by hajimehoshi** [comment]
Yeah, in this case, you need to have your own scale factor 2 and adjust positions like geometry scaling and inputting.

**Comment by nanoslayer** [comment]
The problem is that it is tedious to manually scale everything by two, but even more so for drawing and positioning text.

**Comment by hajimehoshi** [comment]
I understand it is tedious, but Ebiten doesn't support such thing. As Ebiten images are bitmaps and not vector images, it is not obvious how to treat the global scale even if Ebiten adopts this.

**Comment by nanoslayer** [comment]
Thanks for the response.

**Comment by nanoslayer** [comment]
Is there any chance that this can be implemented? I want to be able to separate the logical size of the screen from the actual size of the screen in pixels. Some games provide an option to set the screen resolution of the game. It would be nice to be able to do that without using GeoM.Scale everywhere.

What about setting the scale per image instead of using a global scale?

**Comment by hajimehoshi** [comment]
> What about setting the scale per image instead of using a global scale?

It is not obvious how to treat offscreens.
