### ISSUE TITLE
ebiten: Add 'difference' compositing mode

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1347]
Suggested by @gravestench 

Let me investigate this is possible and would make sense.

**Comment by hajimehoshi** [comment]
https://www.w3.org/TR/compositing-1/#blendingdifference

Unfortunately, abs function is not available at OpenGL/Metal blending.

**Comment by hajimehoshi** [comment]
See #1450

**Comment by hajimehoshi** [comment]
Rather than duplication, I think this impossible to achieve the same effect as CSS's 'difference'

**Comment by gravestench** [comment]
`:sadge:`
