### ISSUE TITLE
examples/windowsize: Transparent screen + fullscreen sometimes doesn't make the window transparent

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1357]
Confirmed this on Vaio Z Canvas. This might be an issue in GLFW.

**Comment by gukz** [comment]
will this help?
https://stackoverflow.com/questions/62857438/how-to-make-the-background-transparent-in-fullscreen-mode-in-opengl

**Comment by hajimehoshi** [comment]
Sorry but I forgot the context of this issue. Let me close this once.
