### ISSUE TITLE
examples/shader: Add CRT effect

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1359]
http://slack.net/~ant/libs/ntsc.html

**Comment by tomlister** [comment]
I'll have a go at this.

**Comment by hajimehoshi** [comment]
I think SNES, thanks!

**Comment by hajimehoshi** [comment]
What's going on this?

**Comment by hajimehoshi** [comment]
Any updates?

**Comment by tomlister** [comment]
Hi yes sorry,

I'll try get this out this afternoon, been very busy with work.

**Comment by hajimehoshi** [comment]
OK please take your time :-)

As this is not an urgent task, I'll remove the milestone. Of course I'll reapply the milestone when you finish this work.

**Comment by Zyko0** [comment]
Was this a duplicate of https://github.com/hajimehoshi/ebiten/issues/2008 ?

**Comment by hajimehoshi** [comment]
Oh right
