### ISSUE TITLE
shader: Implement `cap` function

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1361]
https://play.golang.org/p/c2WPoBQqWcC

`cap` is also available as a constant value!

**Comment by tomlister** [comment]
Would it be faster to precalculate the capacity of arrays into variables.
Replace the function calls with references to the variables?
Eg: 
```c
vec2 A0[2] = {vec2(0.0,0.0),vec2(0.0,0.0)};
int A0_CAP = 2;
```

**Comment by hajimehoshi** [comment]
> Would it be best at compile time to precalculate the capacity of arrays into variables then replace the function calls with references to the variables?

Yes, and actually this is how `len` is implemented now.

**Comment by tomlister** [comment]
Just for reference, in which file does len get precalculated. I'm struggling to navigate the shader ir code. Cheers

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/blob/master/internal/shader/expr.go#L223-L239 Here you are
