### ISSUE TITLE
example/spriteshd: vsync doesn't work on Windows

### ISSUE THREAD

**Issue by xrx666** [hajimehoshi/ebiten#1363]
In full-screen mode, mac and windows fps performance is inconsistent, mac stable at 60 frames, windows can reach 1600 frames.

**Comment by xrx666** [comment]
Isn't vsync not set to be consistent?

**Comment by hajimehoshi** [comment]
This can be an environment where vsync doesn't work with the fullscreen mode. What about the other applications?

**Comment by xrx666** [comment]
Just vsync initialization, under windows full screen, not true.

**Comment by hajimehoshi** [comment]
I don't understand. Did you run the other fullscreen application? Did vsync work in this case?

**Comment by xrx666** [comment]
demo: examples/spriteshd.
Run under windows and mac, respectively, this is a full-screen program, but vsync in 2 operating systems, inconsistent, window program for the time being no problem.

**Comment by xrx666** [comment]
Windows full screen, vsync is not the default true.

**Comment by hajimehoshi** [comment]
I meant I'd like you to try other applications than ebiten.

**Comment by xrx666** [comment]
But ebiten vsync defaults to true, why is it inconsistent under windows fullScreen?

**Comment by hajimehoshi** [comment]
What I want to know is whether vsync works in fullscreen mode in your environment with any applications or not. I'd like to know this is an Ebiten-specific issue or not.

**Comment by hajimehoshi** [comment]
At least in my Windows environments (Vaio Z Canvas and Parallels VM), vsync works as expected.

**Comment by xrx666** [comment]
But ebiten vsync defaults to true, why is it inconsistent under windows fullScreen?

**Comment by hajimehoshi** [comment]
> At least in my Windows environments (Vaio Z Canvas and Parallels VM), vsync works as expected.

Now I've confirmed `examples/spritehd`'s FPS is higher than expected. Let me investigated.

> But ebiten vsync defaults to true, why is it inconsistent under windows fullScreen?

Again, this might be an Ebiten-specific issue or not. I want to know which.

**Comment by xrx666** [comment]
Yes, it works, but in windows fullScreen mode, vsync behavior is not the default true.

**Comment by xrx666** [comment]
For the time being, I'll just ebiten.

**Comment by hajimehoshi** [comment]
I've confirmed this issue with `examples/spritehd` anyway. I'll investigate this. Thank you.

**Comment by hajimehoshi** [comment]
Related to #375

**Comment by hajimehoshi** [comment]
https://github.com/glfw/glfw/issues/1072

Apparently this is an issue in GLFW.

**Comment by hajimehoshi** [comment]
The interesting thing is that `examples/windowsize` with `-fullscreen` flag doesn't cause this issue. Then, there should be a hack or a workaround.

**Comment by xrx666** [comment]
Call ebiten.SetVsyncEnabled in update, can return to normal, I updated the latest driver, examples/spriteshd vsync, not the default behavior.

**Comment by hajimehoshi** [comment]
I think this is fixed. Thank you!
