### ISSUE TITLE
examples/windowsize: SetVsyncEnabled(false) before the main loop doesn't work on MacBook Pro 2020?

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1364]

**Comment by xrx666** [comment]
vsync's behavior on mac and on documents is consistent.

**Comment by hajimehoshi** [comment]
Switching off vsync on macOS now doesn't work, as the title says.

**Comment by hajimehoshi** [comment]
This is tricky. Disabling vsync works on MacBook Pro 2018 (macOS Catalina 10.15.5), but not on MacBook Pro 2020 (macOS Catalina 10.15.6)

**Comment by xrx666** [comment]
macbook pro 2016 (10.15.6) vsync is valid.

**Comment by hajimehoshi** [comment]
Have you succeeded to disable vsync at `examples/windowsize`?

**Comment by xrx666** [comment]
That's right.

**Comment by xrx666** [comment]
yes

**Comment by hajimehoshi** [comment]
OK thanks for the info!
