### ISSUE TITLE
#feature `ebiten.InputChars` byte array support

### ISSUE THREAD

**Issue by goisgreat** [hajimehoshi/ebiten#1365]
I would like a method similar to `ebiten.InputChars` except `ebiten.InputBytes`. This new function would take no arguments and return the input characters (just like `ebiten.InputChars`). However, the return value would be of type `[]byte` instead of `[]rune`.

**Comment by hajimehoshi** [comment]
Hi, thank you for the suggestion.

I was wondering what's the motivation.

BTW, does `([]byte)(string(ebiten.InputChars()))` work for you?

**Comment by hajimehoshi** [comment]
I think the above code should solve your request. Let me close this.

**Comment by goisgreat** [comment]
Thanks for the code @hajimehoshi! Will try

**Comment by goisgreat** [comment]
Also I'm a complete noob when it comes to github. How do you add labels like feature?

**Comment by hajimehoshi** [comment]
> Also I'm a complete noob when it comes to github. How do you add labels like feature?

You cannot add labels to the repositories you don't own or manage.
