### ISSUE TITLE
ebiten: Include Draw() method in an interface

### ISSUE THREAD

**Issue by Kangaroux** [hajimehoshi/ebiten#1368]
https://github.com/hajimehoshi/ebiten/pull/1107

There is no interface for the `Draw` method. Instead checks use an inline interface, e.g.

```go
i.game.(interface{ Draw(*Image) }).Draw(screen)
```

This is used in multiple areas. It's a DRY issue and also is a bit of an inconvenience if you want to refer to it in an interface, e.g.

```go
type Engine interface {
	ebiten.Game
	Draw(screen *ebiten.Image)  // Not obvious this is an ebiten method

	// Other stuff...
	Entities() EntityManager
	Events() EventManager
	Scenes() SceneManager
	Systems() SystemManager
}
```

------

Perhaps a better approach (as far as clarity goes) would be to just extend the `ebiten.Game` interface. Not sure on the wording (`ebiten.GameExtended`?)

```go
type Game interface {
    Update(screen *Image) error
    Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int)
}

type GameExtended interface {
    Game
    Draw(screen *Image)
}
```

```go
if ext, ok := game.(GameExtended); ok {
    ext.Draw(...)
}
```

**Comment by hajimehoshi** [comment]
As this is a breaking change, we plan to do this in 2.0.0 actually. With the current roadmap, we'll do this next month.

Related: #1260
