### ISSUE TITLE
graphics: HTML5-Canvas-like API

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#137]
# Random note

## How to implement

For simple primitives, GLSL would work. For complex things like filling polygon, GLSL would also work but stencil buffers might be better.

Or, how about implementing scan-line algorithm on GLSL without vertices?

## What kind of features there are in HTML5 Canvas

Ref: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D

* Shapes / Paths
  * Line
  * Rectangle
  * Polygon
  * Arc
    * Circle
    * Ellipse
  * Bezier Curve
  * Quadratic Curve

* Line style
  * Width
  * Cap
  * Join
  * Miter Limit
  * Dash

* Fill/Stroke Style
  * Solid
  * Gradient
  * Pattern

* Shadow
  * Blur
  * Color
  * Offset

* Paths
  * Fill (non-zero / even-odd) (NanoVG supports only even-odd)
  * Stroke
  * Clip

* Others
  * imageSmoothingEnabled (Anti alias)

I don't think we need all the above items though...

## Text

As for text rendering, we already have `github.com/hajimehoshi/ebiten/text` and that's fine. For true type fonts, using bezier curves might be more effective, but the `text` package accepts more general `font.Face` interface, that can be any rasterized data.

## Filling pattern / Clip

We already have composition modes, so I don't think we need API to specify complex filling pattern and clipping. Just filling with a solid color might be enough.

## Actual use cases

I need actual use cases before considering API. This is similar way to Go2 language change.

* Prototyping
* Graphs or charts
* UI

**Comment by hajimehoshi** [comment]
Let's see what NanoVG https://github.com/memononen/nanovg is doing and decide if I should convert this into Go or take another way.

**Comment by hajimehoshi** [comment]
# Random note

## How to implement

I was thinking how to implement this. For simple primitives, GLSL would work. For complex things like filling polygon, GLSL would also work but stencil buffers might be better.

## What kind of features there are

Ref: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D

* Shapes / Paths
  * Line
  * Rectangle
  * Polygon
  * Arc
    * Circle
    * Ellipse
  * Bezier Curve
  * Quadratic Curve

* Line style
  * Width
  * Cap
  * Join
  * Miter Limit
  * Dash

* Fill/Stroke Style
  * Solid
  * Gradient
  * Pattern

* Shadow
  * Blur
  * Color
  * Offset

* Paths
  * Fill (nonzero / evenodd)
  * Stroke
  * Clip

I don't think we need all the above items though...

# Text

As for text rendering, we already have `github.com/hajimehoshi/ebiten/text` and that's fine. For true type fonts, using bezier curves might be more effective, but the `text` package accepts more general `font.Face` interface, that can be any rasterized data.

**Comment by hajimehoshi** [comment]
It looks like pygame has not-so-complex API

http://www.pygame.org/docs/ref/draw.html

**Comment by joeblew99** [comment]
@hajimehoshi my use case is to design high quality UI. 

The first comment you make in this issue pretty much sums it up. It also makes sense to use Canvas2D Web as a basis.

I guess its a matter of implementing these for opengl also ? These i assume woudl be GLSL accelerated ?

--

i am fiddling around with how to make it easier to design with these primitives. Almost like a higher level markup. I knwo that is out of scope, but just letting you know.

**Comment by hajimehoshi** [comment]
> my use case is to design high quality UI.

Speaking of high quality, you might need https://github.com/hajimehoshi/ebiten/issues/395. Ebiten now treats only platform-independent pixels and can't draw high resolution images that matches high-dpi displays.

I understand your use case but introducing such big feature is very risky and I'd like to consider it very carefully.

> The first comment you make in this issue pretty much sums it up. It also makes sense to use Canvas2D Web as a basis.
> I guess its a matter of implementing these for opengl also ? These i assume woudl be GLSL accelerated ?

I'm thinking to use GLSL. Canvas is useful but it would make Ebiten internal implementation more complex.

**Comment by joeblew99** [comment]
I noticed the DPI problem too so glad you mentioned it.

Regarding using glsl, I think your right.
If you have a basic example of doing it with glsl I can try out different use cases to extent it and see how I go and push it's back if I get anything worthwhile going.

**Comment by hajimehoshi** [comment]
No examples here.

BTW, if you want to make a UI, doesn't 9-patches way work?

**Comment by joeblew99** [comment]
yeah i saw the 9 patches technique you used.
Its basically just a raster image though ? 
My main reason for bringing this up is to support different screen sizes. That tends to mean
- making the source of controls vector based. I was thinking about an idea of creating raster images at compile time and embedding them as a work around.
- detecting DPI at runtime.
- layout constraints to allow the different GUI components to resize based on screen size differences and window resizes.

**Comment by hajimehoshi** [comment]
OK, so how about detecting the platform's DPI and using 9-patches? You'd need to prepare same images for multiple resolutions.

**Comment by hajimehoshi** [comment]
http://godoc.org/github.com/hajimehoshi/ebiten/ebitenutil#DrawLine Added DrawLine and DrawRect mainly for debugging or prototyping purpose. These are just for debugging, and we might still need HTML5-Canvas-like APIs.

**Comment by joeblew99** [comment]
great . thanks for the update. THat a perfect base.

next wil be to try out constraint solvers for different layouts and resizes. There are good ones in match that can be used.

**Comment by hajimehoshi** [comment]
> Regarding detecting the DPI can we do that now ?

I wanted to know whether you really need vector graphics instead of 9-patches. If we can know DPI, I think 9-patches would work even in high-definition.

**Comment by joeblew99** [comment]
Maybe it's best if I just explain what I am doing with ebiten and where I am hitting problems.

On desktop I need to run full screen.
At the moment this results in the ebiten canvas getting scaled up to fit the entire window / full screen.

So I guess knowing the DPI will allow us to start to render elements at the right size.

Most of my GUI uses the lines and reactances primitives in ebiten. I also do use images for logos and things like that 

So I am guessing then that once we know the DPI we can start to do some logic in the way we scale things...

Sorry about late reply !

**Comment by joeblew99** [comment]
I am currently using the constraints engine in matcha to layout UI and have it adapt to new content and screen sizes in terms of responsive design.

Thought this is relevant since you asked for use cases.

His code does the layout calc at golang level and then sends all sizes to native GUI over protocol buffers, which is if course a different architecture stack to ebiten. But the point is that the layout / constraints code works fantastically and could be used to help with the scaling aspects that all developers will inevitably hit with different screen sizes and DPI.

https://github.com/gomatcha/matcha/tree/master/layout

**Comment by hajimehoshi** [comment]
OK so probably what you want is to detect the native DPI. Let's discuss at #395 if needed.

**Comment by joeblew99** [comment]
Ok i asked over at #395

**Comment by seebs** [comment]
As a person who wants and uses primitives: Pixel's interface to these is moderately useful. Of particular note/import are polylines. Polyline support is very helpful for a lot of use cases. But even just line segments that can specify world-space width and length and transforms are pretty handy. And honestly, a "rect" type that can do arbitrary transforms is probably fine, but there are definite performance advantages to being able to specify more stuff in fewer vertexes. (Polyline approaches one point per line segment; rectangles are two triangles per line segment, and require you to compute four or six points, depending.)

For my immediate purposes, I'll probably just make a generic texture that's all-pixels-FFFFFFFF, and draw scaled/rotated copies.

**Comment by hajimehoshi** [comment]
> For my immediate purposes, I'll probably just make a generic texture that's all-pixels-FFFFFFFF, and draw scaled/rotated copies.

`ebitenutil.DrawRect` and `DrawLine` do the same thing. Please take a look: https://godoc.org/github.com/hajimehoshi/ebiten/ebitenutil#DrawLine

**Comment by seebs** [comment]
They do, but DrawLine doesn't seem to have a width specification, and DrawRect doesn't provide a rotatable thing. So if I want a pretty antialiased line-segment-like-thing, I think I need to draw an "image", even if it's an all-pixels-white image, so I have all the transforms available.

**Comment by hajimehoshi** [comment]
Ah, that makes sense.

**Comment by hajimehoshi** [comment]
Speaking of performance, rendering lines by rects would not be good, but I
guess this would matter when 20k or so many lines are rendered. How many
like segments do you plan to render?

2017年12月31日(日) 4:25 seebs <notifications@github.com>:

**Comment by seebs** [comment]
As many as I can. 20k sounds good. Fewer is probably fine. depends on other issues also.

**Comment by hajimehoshi** [comment]
Current idea:

* Add a new API to Ebiten to draw just polygons with solid color
* Add a new package to offer new APIs to draw shapes implemented by the new API and [poly2tri](http://sites-final.uclouvain.be/mema/Poly2Tri/) algorithm

The good thing is that only one API is required in Ebiten. This is very generic and minimalistic.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/go-libtess2 Ported a tessellation lib to Go. Theoretically, any shapes can be drawn if Ebiten has an API to draw given vertices.

**Comment by Splizard** [comment]
What's the status of drawing shapes in ebiten? Rectangles are trivial, is there an efficient way to draw triangles / circles ?

**Comment by hajimehoshi** [comment]
No progress so far. Now I'm busy with working on performance optimization especially for mobiles.

**Comment by hajimehoshi** [comment]
> The standard use case for me would be debugging collisions, having an easy way to draw circles and triangles is a quick way to visualize collision boxes.

Ah, that makes sense...

**Comment by hajimehoshi** [comment]
This can be indirectly supported by `DrawTriangle`. I think adding a package to draw primitive shapes would be very useful.

**Comment by lei-cao** [comment]
What about directly using other libraries like 
https://github.com/fogleman/gg and 
https://github.com/llgcode/draw2d/

**Comment by hajimehoshi** [comment]
They manipulates pixels and doesn't use polygons, right?

**Comment by hajimehoshi** [comment]
As the first step, I think I'll implement these features:

  * Shapes:
    * Line
    * Rectangle
    * Circle
    * Ellipse
    * Arc
  * Option to fill or not

Reference: https://www.pygame.org/docs/ref/draw.html

**Comment by hajimehoshi** [comment]
https://godoc.org/github.com/hajimehoshi/ebiten/vector Created a 'vector' package. I think I'll add more various functions to `Path`.

**Comment by hajimehoshi** [comment]
Let me close this issue by the following issues:

* vector: Add various shapes
* vector: Fill
