### ISSUE TITLE
How to use the Miscellaneous Symbols and Pictograph unicde set?

### ISSUE THREAD

**Issue by tetravalence** [hajimehoshi/ebiten#1376]
Hi! the `font.go` example is rendering glyphs of a TrueType font using `text.Draw`. I have tried to manually change the CJK Unified Ideograph how is listed in `table` constant with some miscellaneous symbols character (range 1F300-1F5FF) but it's not working. 
What package should I import in Go to get the rendering of these Unicode characters with `text.Draw`?

**Comment by hajimehoshi** [comment]
Hi,

The font used in the example (M+) doesn't include glyphs for Emojis. You need to import another TrueType/OpenType fonts instead.

You can load an OpenType font with golang.org/x/image/font/opentype.

For testing, I recommend to use Noto font: https://www.google.com/get/noto/#emoji-zsye

**Comment by tetravalence** [comment]
OK thank you
