### ISSUE TITLE
Recommended technique for getting touch/mobile input for WASM

### ISSUE THREAD

**Issue by rootVIII** [hajimehoshi/ebiten#1383]
Is there a recommended way to get input from a mobile device's browser to a WASM game?

I have a small [game](https://github.com/rootVIII/evilpoopemoji) that uses your libraries. I have also been running it using  wasmserve to see it in the browser.

My code uses the ```ebiten.IsKeyPressed() ``` for directional arrows and space bar. Is there a way to get an HTML5 canvas element and maybe an addEventListener() to interact with the WASM build or somehow call a corresponding IsKeyPressed() method?

**Comment by hajimehoshi** [comment]
Hi,

What about using `IsMouseButtonPressed` or `TouchIDs` APIs besides `IsKeyPressed`?

**Comment by rootVIII** [comment]
Oh yeah just saw that in your docs. Sorry I was looking on ebiten.org instead of the ebiten godocs. I'll give that a shot... thanks!
