### ISSUE TITLE
cannot install v2.1.0-alpha - issue with v2 identifier in go.mod?

### ISSUE THREAD

**Issue by TheMightyGit** [hajimehoshi/ebiten#1384]
I'm not really sure what this means, but it doesn't like the `v2` at the top of the go.mod file when I try and go get `v2.1.0-alpha`. I think perhaps that version identifier is not for your package version but is actually the format version of the go.mod file itself? (i'm not clear on this)

```
$ go get github.com/hajimehoshi/ebiten@v2.1.0-alpha
go get github.com/hajimehoshi/ebiten@v2.1.0-alpha: github.com/hajimehoshi/ebiten@v2.1.0-alpha: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

I've tried totally removing all 'old' ebiten modules and src ad clearing all caches - nothing helps.

If I use `@master` it gives me `v1.13.0-alpha`.

go version go1.15.2 darwin/amd64

**Comment by TheMightyGit** [comment]
my bad! I needed...

```
$ go get github.com/hajimehoshi/ebiten/v2
```

**Comment by TheMightyGit** [comment]
Cool! I used to get a 4fps dip at regular intervals (macos+metal v.1.12) but now it's a 0.02fps dip \o/ 

thank you <3

**Comment by hajimehoshi** [comment]
Hi, thank you for trying Ebiten v2!

> Cool! I used to get a 4fps dip at regular intervals (macos+metal v1.12) but now it's a 0.02fps dip \o/

Oh, do you mean the FPS is very very low? 0.02 fps looks unexpectedly slow and you cannot play the game...

**Comment by TheMightyGit** [comment]
> Oh, do you mean the FPS is very very low? 0.02 fps looks unexpectedly slow and you cannot play the game...

Sorry, 0.02 variance, almost rock solid 60fps all the time :D

**Comment by hajimehoshi** [comment]
OK, I'm glad to hear that!

>

**Comment by TheMightyGit** [comment]
<img width="1279" alt="Screenshot 2020-10-10 at 17 56 20" src="https://user-images.githubusercontent.com/888751/95660767-ee9c9e80-0b21-11eb-8a48-735412141224.png">

**Comment by hajimehoshi** [comment]
Nice screenshot!

I haven't added changes for performance between 1.12 and 2.0, and 2.0 is just an API changes from 1.12. So that's a little odd, but thank you for reporting!
