### ISSUE TITLE
graphicsdriver/opengl: Call OpenGL functions directly instead of golang.org/x/mobile/gl

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1387]
1. `golang.org/x/mobile/gl`'s GL functions require gl.Context, which makes Ebiten complicated.
2. `golang.org/x/mobile/gl`'s GL functions use channels, and this might be overheads (#1367)

This might mean giving up supporting gomobile-build.

**Comment by Noofbiz** [comment]
I believe OpenGL ES has to use the context as well as the multi-threaded worker method used by the mobile/gl package. It’s fairly easy to roll it yourself, and I think you already do with the ebitenmobile, but just a heads up, but I’m not sure if it’ll actually reduce the thread count any more than `golang.org/x/mobile/gl` already does. I believe it’s a limitation of OpenGL ES’s low power stuff more than the library.

**Comment by hajimehoshi** [comment]
Hi,

My aim is not to reduce the thread count but reduce the switching-goroutine count. golang.org/x/mobile/gl's issue is that they require switching goroutines for every function call.

I've already succeeded for desktops and Metal at #1367.

**Comment by Noofbiz** [comment]
Very interesting, you'd think it would make it faster. Do you think it's a bug in how go handles goroutine switching? Or is it just that big of a bottleneck?

**Comment by hajimehoshi** [comment]
Yeah, that is just a performance bottleneck. I guess gomobile's GL aims a Go-style API design and doesn't consider performance very much.

**Comment by hajimehoshi** [comment]
gomobile-build uses its own thread for GL context, and this is untouchable. That's unfortunate. The fix will be only for gomobile-bind.
