### ISSUE TITLE
Error in audioinfiniteloop example

### ISSUE THREAD

**Issue by tommyblue** [hajimehoshi/ebiten#1390]
https://github.com/hajimehoshi/ebiten/blob/master/examples/audioinfiniteloop/main.go#L54

Line 54 returns an error:
```
cannot use bytes.NewReader("github.com/hajimehoshi/ebiten/v2/examples/resources/audio".Ragtime_ogg) (type *bytes.Reader) as type "github.com/hajimehoshi/ebiten/audio".ReadSeekCloser in argument to vorbis.Decode:
	*bytes.Reader does not implement "github.com/hajimehoshi/ebiten/audio".ReadSeekCloser (missing Close method)
```

It works if `bytes.NewReader` is replaced by `audio.BytesReadSeekCloser`

**Comment by hajimehoshi** [comment]
This is replaced at v2: https://ebiten.org/documents/to_v2.html

Which version are you using?

**Comment by hajimehoshi** [comment]
Note that v2.0.0 is not released yet, but v2.0.0-rc.1 is available.

**Comment by tommyblue** [comment]
I'm using v1

**Comment by tommyblue** [comment]
oh, I see: so I copied from master that is v2 but my local version is v1, right?

**Comment by hajimehoshi** [comment]
Exactly. 1.12 branch shows the latest v1 state: https://github.com/hajimehoshi/ebiten/tree/1.12
