### ISSUE TITLE
SetMaxTPS(N) with low N value skip Game.Update() calls  

### ISSUE THREAD

**Issue by mxv** [hajimehoshi/ebiten#1417]
OS: Windows
GO: go1.15.3

**Issue:** 
Setting `ebiten.SetMaxTPS(N)`  with a low N value (  `1<=N<=4` )
only calls `Game.Update()` 2 times and then stops indefinitely.

**Expectation:**
Update() should be called at least N times , given N is  actually lower than actual Draw per second(FPS) 

**Reproduction Code:**
```GO
package main

import (
	"fmt"
	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/ebitenutil"
	"log"
)

type Game struct {
	updates int
	draws   int
}

func (g *Game) Update() error {
	g.updates++
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	g.draws++

	ebitenutil.DebugPrint(screen, fmt.Sprintf("updates:%d  draws:%d", g.updates, g.draws))

}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return outsideWidth / 2, outsideHeight / 2
}

func main() {

	g := &Game{}

	ebiten.SetMaxTPS(1)
	if err := ebiten.RunGame(g); err != nil {
		log.Fatal(err)
	}
}

```

![image](https://user-images.githubusercontent.com/11780450/98591442-41db4b80-229e-11eb-9180-1ad4faace097.png)

**Comment by hajimehoshi** [comment]
Confirmed.
