### ISSUE TITLE
ebiten: add an option to choose `texels` or `pixels` to `DrawRectShaderOptions` and `DrawTrianglesShaderOptions`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1431]
The difficult part is how to keep the efficiency of the shaders.

**Comment by hajimehoshi** [comment]
In OpenGL, `texelFecth` might solve this issue: https://registry.khronos.org/OpenGL-Refpages/es3.0/html/texelFetch.xhtml

**Comment by hajimehoshi** [comment]
Oops, as this requires WebGL2, I cannot add this immediately.

**Comment by hajimehoshi** [comment]
#1911 is a blocker.

**Comment by hajimehoshi** [comment]
I'll remove the option for the texels in v3.

**Comment by hajimehoshi** [comment]
We can revisit https://github.com/hajimehoshi/ebiten/issues/1171 after this fix.

**Comment by hajimehoshi** [comment]
I realized that the pixel mode might introduce another confusion. If anti-alias is enabled, the destination image is 2x big and this might be surprising to users.

**Comment by hajimehoshi** [comment]
My current idea:

* Introduce `FragmentPixels`, which is exclusive with `Fragment`. In `FragmentPixels`, `texCoord` will be in pixels instead of texels.
* Introduce these new functions:
  * `imageSrcNAtInPixels`
  * `imageSrcNUnsafeAtInPixels`
  * `imageSrcRegionOnTextureInPixels`
  * `imageDstRegionOnTextureInPixels`

The names might be too long, but this is the core of my idea.

**Comment by hajimehoshi** [comment]
From a discussion with @Zyko0, adjusting `position`, `texCoord`, and new functions (`imageSrcNAtInPixels`, etc.) to treat origins automatically so that the left-upper position is always (0, 0)? My concern is whether this is really intuitive when a sub-image is used.

**Comment by hajimehoshi** [comment]
Here, 'origin' is an origin position for a image on a texture atlas.

> My concern is whether this is really intuitive when a sub-image is used.

1) If a subimage's origin is adjusted to (0, 0), this would be different from `(*ebiten.Image).Bounds` so this seems inconsistent.
2) If a subimage's origin is NOT adjusted to (0, 0), shader users might be confused but this is still consistent.

Probably always not adjusting the origin might be the most consistent.

**Comment by SolarLune** [comment]
> My current idea:

I feel like there probably shouldn't be a "pixel mode" or pixel functions - Kage should just move from texels to pixels, with no deprecation in-between. Having both options (especially for a new Fragment function specifically designed for pixels) feels like it overly complicates how a Kage shader works.

**Comment by hajimehoshi** [comment]
I added the latest proposal at https://docs.google.com/document/d/1lJTKxMqyyO-LxNS4KmuNakQwlhdBgzkmP2LNwpJk5bg/edit#bookmark=id.wjopj34pm9gh

A special comment `//kage:pixel-mode` seems the best to me so far.

**Comment by hajimehoshi** [comment]
https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)

OpenGL 3 is required for `texelFetch` (GLSL 1.30)!

**Comment by hajimehoshi** [comment]
This requries OpenGL 3, but perhaps, OpenGL 3 is not available under the Steam SDK...?? https://github.com/hajimehoshi/ebiten/actions/runs/4773500647/jobs/8486607065

> panic: VersionUnavailable: Requested OpenGL version 3.2, got version 2.1

**Comment by hajimehoshi** [comment]
I think we should use 'sniper' instead of 'scout'.

https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/blob/main/docs/slr-for-game-developers.md
