### ISSUE TITLE
ebiten: add 'Subtract' composite mode, or expose APIs to set the blend function

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1450]
This is similar to #1347.

Requested by @wasedaigo 

We might have to consider to expose the composite functors to be specified directly.

**Comment by hajimehoshi** [comment]
OpenGL: https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendEquation.xhtml
Metal: https://developer.apple.com/documentation/metal/mtlblendoperation?language=objc

**Comment by hajimehoshi** [comment]
For example, if some part of the source is (0, 0, 0, 0), the result of the part will always be (0, 0, 0, 0). This seems unacceptable. Would subtraction really make sense?

**Comment by eliquious** [comment]
@hajimehoshi I'm trying to draw a circle with a stroke and a fill. I can draw the circle with lines and it looks ok. However, for larger stroke widths it looks terrible. I'm trying a second solution which is to draw a filled circle with `vector.Path` and then a smaller circle with the fill color. This is working except for transparent fills. I think the Subtract composite mode might do it.

Is there another way to subtract a center from a filled path using the existing composites?

**Comment by hajimehoshi** [comment]
Hi. So you want to render a torus, right? The subtract composition is not for this, and Ebiten should provide a way to fill a polygon with holes like a torus, but does not yet. If you want, you can do it with `DrawTriangles` by doing triangulation (splitting a polygon into triangles) by yourself so far.

**Comment by hajimehoshi** [comment]
Now I'm not sure we really need this 🤔

**Comment by hajimehoshi** [comment]
There have been various request about blending. Probably exposing everything about blending and letting uses use as they like seems the best so far.

**Comment by hajimehoshi** [comment]
Implemented `Blend` API. https://github.com/hajimehoshi/ebiten/issues/2382#issuecomment-1279994360
