### ISSUE TITLE
Blurry fonts (possible kerning problem?)

### ISSUE THREAD

**Issue by tapir** [hajimehoshi/ebiten#1451]
I'm on a 2K display with Windows settings setup to 125% scaling.
Tried to render Liberation family of fonts. Attached is the serif-regular on 96 dpi at 9pt and 12pt with vertical hinting (however looks pretty much the same with no hinting or full hinting)

As can be seen it's blurry but also looks like the kerning between letters are all over the place. This can be an illusion due to blurriness of the text though. Can't tell.

What are my options for a crisp text rendering regardless of the device scaling settings of my users?

![fonts](https://user-images.githubusercontent.com/223984/103137278-cd326400-46c7-11eb-8e76-fda7440d7038.png)

**Comment by hajimehoshi** [comment]
I was wondering how to render the text. Are you using golang.org/x/image/font/opentype?

**Comment by tapir** [comment]
Yes took the example text rendering code [here](https://github.com/hajimehoshi/ebiten/blob/master/examples/font/main.go) and changed the font, dpi, size and hinting settings.

**Comment by hajimehoshi** [comment]
I'm not confident but this might be an issue in golang.org/x/image/font/opentype with too small size fonts (9pt). For a tentative solution, rendering a big glyphs on an offscreen and render it on the final target with a scale.

> What are my options for a crisp text rendering regardless of the device scaling settings of my users?

Use DeviceScaleFactor at Layout like https://github.com/hajimehoshi/ebiten/blob/master/examples/highdpi/main.go#L102-L107 so that you can get a big screen. Then you can render texts in the way you like (e.g., enlarging it with the nearest filter). However, Ebiten tries to enlarge the entire screen to keep the quality of crisp.

**Comment by tapir** [comment]
with layout scaling it's already much better! still needs improvement but I guess that's an issue for golang.org/x/image/font/opentype

thanks

**Comment by tapir** [comment]
Before opening up an issue on font/opentype I wanted to double check that this is not an ebiten issue. Below is the same text rendered with Arial on 18pt with 72dpi. First line is `HintingNone`, second line is `HintingVertical` and the third line is `HintingFull`.
However the output is the same for each line pixel-by-pixel. Tried different fonts too and got the same result.

![image](https://user-images.githubusercontent.com/223984/103141883-5020e200-46fb-11eb-8160-0cc72182446f.png)

Here is my test code
```go
package main

import (
	"image/color"
	"io/ioutil"
	"log"

	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/text"

	"golang.org/x/image/font/inconsolata"
)

const (
	screenWidth  = 640
	screenHeight = 480
	dpi          = 72
)

const sampleText = `The quick brown fox jumps over the lazy dog.`

type game struct {
	face14pthint0 font.Face
	face14pthint1 font.Face
	face14pthint2 font.Face
	inco          font.Face
}

func (g *game) Update() error {
	return nil
}

func (g *game) Draw(screen *ebiten.Image) {
	const x = 20
	text.Draw(screen, sampleText, g.face14pthint0, x, 80, color.White)
	text.Draw(screen, sampleText, g.face14pthint0, x, 110, color.White)
	text.Draw(screen, sampleText, g.face14pthint0, x, 140, color.White)
}

func (g *game) Layout(outsideWidth, outsideHeight int) (int, int) {
	s := ebiten.DeviceScaleFactor()
	return int(float64(outsideWidth) * s), int(float64(outsideHeight) * s)
}

func main() {
	ttfb, err := ioutil.ReadFile("arial.ttf")
	if err != nil {
		log.Fatal(err)
	}

	ttfs, err := opentype.Parse(ttfb)
	if err != nil {
		log.Fatal(err)
	}

	face14pthint0, err := opentype.NewFace(ttfs, &opentype.FaceOptions{
		Size:    18,
		DPI:     dpi,
		Hinting: font.HintingNone,
	})

	face14pthint1, err := opentype.NewFace(ttfs, &opentype.FaceOptions{
		Size:    18,
		DPI:     dpi,
		Hinting: font.HintingVertical,
	})

	face14pthint2, err := opentype.NewFace(ttfs, &opentype.FaceOptions{
		Size:    18,
		DPI:     dpi,
		Hinting: font.HintingFull,
	})

	if err != nil {
		log.Fatal(err)
	}

	g := &game{
		face14pthint0: face14pthint0,
		face14pthint1: face14pthint1,
		face14pthint2: face14pthint2,
		inco:          inconsolata.Regular8x16,
	}

	ebiten.SetWindowSize(screenWidth, screenHeight)
	ebiten.SetWindowTitle("Font Demo")
	if err := ebiten.RunGame(g); err != nil {
		log.Fatal(err)
	}
}
```
