### ISSUE TITLE
Controller vibrations

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1452]

**Comment by tomlister** [comment]
GLFW doesn't support this yet, but there is an inactive issue for implementing this.
Some thoughts:

- Write platform specific implementations for accessing controller apis.
- MacOS: https://developer.apple.com/documentation/gamecontroller/gcdevicehaptics
- Windows: https://docs.microsoft.com/en-us/windows/win32/xinput/getting-started-with-xinput
- Linux: 🤔

**Comment by hajimehoshi** [comment]
@wasedaigo requested to specify the strength of the device vibration in addition to the controller vibration. Let me think.

**Comment by hajimehoshi** [comment]
Windows: https://source.chromium.org/chromium/chromium/src/+/main:device/gamepad/xinput_data_fetcher_win.cc;l=247;drc=2897d5bfa4c77b10282805ee096036ece7dd58e3
Nintendo?: https://source.chromium.org/chromium/chromium/src/+/main:device/gamepad/nintendo_data_fetcher.cc;l=219;drc=2897d5bfa4c77b10282805ee096036ece7dd58e3
Linux: https://source.chromium.org/chromium/chromium/src/+/main:device/gamepad/gamepad_platform_data_fetcher_linux.cc;l=333;drc=2897d5bfa4c77b10282805ee096036ece7dd58e3

What about macOS?

**Comment by hajimehoshi** [comment]
Another option is SDL. Would it be really OK to call `write` https://github.com/libsdl-org/SDL/blob/c878d9a0aaed2431a66ff1e1f221b83317286402/src/haptic/linux/SDL_syshaptic.c#L1021-L1037 with GLFW's gamepad implementation? If we want to use this, should we switch the gamepad implementation part from GLFW to SDL entirely?

**Comment by hajimehoshi** [comment]
With #172 and #1903,

* Moving the gamepad part from GLFW to SDL
  * Converting this from C to Go?
* Adding the haptic part with SDL
  * Converting this from C to Go?

seem the way to go. 🤔

**Comment by hajimehoshi** [comment]
This is partially implemented. I'll create a more specific issue for this.
