### ISSUE TITLE
Ebiten vs MonoGame,there are too many performance differences

### ISSUE THREAD

**Issue by chengxuge** [hajimehoshi/ebiten#1457]
Use github.com/hajimehoshi/ebiten/examples/sprites to set up sprite num to 50,000, cpu usage is more than twice that of monogame, and ebiten's fps limit is 30, and monogame is 60fps.

### **this c# code:**
`using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using Microsoft.Xna.Framework.Input;

namespace monogame
{
    public static class Const
    {
        public static readonly int screenWidth = 800;
        public static readonly int screenHeight = 600;
        public static readonly int maxAngle = 360;
        public static readonly int minSprites = 0;
        public static readonly int maxSprites = 50000;
    }

    public class Sprite
    {
        public int imageWidth;
        public int imageHeight;
        public int x;
        public int y;
        public int vx;
        public int vy;
        public int angle;

        public void Update()
        {
            this.x += this.vx;
            this.y += this.vy;

            if (this.x < 0)
            {
                this.x = -this.x;
                this.vx = -this.vx;
            }
            else
            {
                var mx = Const.screenWidth - this.imageWidth;
                if (mx <= this.x)
                {
                    this.x = 2 * mx - this.x;
                    this.vx = -this.vx;
                }
            }
            if (this.y < 0)
            {
                this.y = -this.y;
                this.vy = -this.vy;
            }
            else
            {
                var my = Const.screenHeight - this.imageHeight;
                if (my <= this.y)
                {
                    this.y = 2 * my - this.y;
                    this.vy = -this.vy;
                }
            }
            this.angle++;
            if (this.angle == Const.maxAngle)
            {
                this.angle = 0;
            }
        }
    }

    public class Sprites
    {
        public Sprite[] sprites;
        public int num;

        public void Update()
        {
            for (var i = 0; i < this.num; i++)
            {
                this.sprites[i].Update();
            }
        }
    }

    public class Game1 : Game
    {
        private GraphicsDeviceManager _graphics;
        private SpriteBatch _spriteBatch;
        private SpriteFont _defaultFont;
        private Texture2D _texture2D;
        private Sprites _sprites;
        private Matrix _matrix;
        private Point _mouse;

        public Game1()
        {
            _graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
            IsMouseVisible = true;
        }

        protected override void Initialize()
        {
            // TODO: Add your initialization logic here
            // _matrix = Matrix.CreateScale((float)_graphics.GraphicsDevice.Adapter.CurrentDisplayMode.Width / (float)Const.screenWidth,
            // (float)_graphics.GraphicsDevice.Adapter.CurrentDisplayMode.Height / (float)Const.screenHeight, 1);
            _matrix = Matrix.CreateScale(1f, 1f, 1f);

            // _graphics.PreferredBackBufferWidth = _graphics.GraphicsDevice.Adapter.CurrentDisplayMode.Width;
            // _graphics.PreferredBackBufferHeight = _graphics.GraphicsDevice.Adapter.CurrentDisplayMode.Height;
            _graphics.PreferredBackBufferWidth = Const.screenWidth;
            _graphics.PreferredBackBufferHeight = Const.screenHeight;
            //_graphics.IsFullScreen = true;
            _graphics.ApplyChanges();

            System.Console.WriteLine(_graphics.GraphicsDevice.Viewport);
            System.Console.WriteLine(_matrix);

            base.Initialize();
        }

        protected override void LoadContent()
        {
            _spriteBatch = new SpriteBatch(GraphicsDevice);

            // TODO: use this.Content to load your game content here
            _defaultFont = Content.Load<SpriteFont>("DefaultFont");
            _texture2D = Content.Load<Texture2D>("ebiten");

            this._sprites = new Sprites()
            {
                sprites = new Sprite[Const.maxSprites],
                num = 50000,
            };
            var random = new System.Random();
            for (var i = 0; i < this._sprites.sprites.Length; i++)
            {
                this._sprites.sprites[i] = new Sprite()
                {
                    imageWidth = _texture2D.Width,
                    imageHeight = _texture2D.Height,
                    x = random.Next(Const.screenWidth - _texture2D.Width),
                    y = random.Next(Const.screenHeight - _texture2D.Height),
                    vx = 2 * random.Next(2) - 1,
                    vy = 2 * random.Next(2) - 1,
                    angle = random.Next(Const.maxAngle),
                };
            }

        }

        protected override void Update(GameTime gameTime)
        {
            if (GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed || Keyboard.GetState().IsKeyDown(Keys.Escape))
                Exit();

            // TODO: Add your update logic here
            if (Keyboard.GetState().IsKeyDown(Keys.Left))
            {
                this._sprites.num -= 20;
                if (this._sprites.num < Const.minSprites)
                {
                    this._sprites.num = Const.minSprites;
                }
            }

            if (Keyboard.GetState().IsKeyDown(Keys.Right))
            {
                this._sprites.num += 20;
                if (Const.maxSprites < this._sprites.num)
                {
                    this._sprites.num = Const.maxSprites;
                }
            }

            _mouse = Mouse.GetState().Position;

            this._sprites.Update();

            base.Update(gameTime);
        }

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.Black);

            // TODO: Add your drawing code here
            _spriteBatch.Begin(transformMatrix: _matrix);

            for (var i = 0; i < this._sprites.num; i++)
            {
                var s = this._sprites.sprites[i];
                _spriteBatch.Draw(_texture2D, new Rectangle(s.x + s.imageWidth / 2, s.y + s.imageHeight / 2, s.imageWidth, s.imageHeight), sourceRectangle: null,
                color: new Color(128, 128, 128, 128), rotation: (float)(2 * System.Math.PI * (double)s.angle / (double)Const.maxAngle),
                origin: new Vector2(s.imageWidth / 2, s.imageHeight / 2), effects: SpriteEffects.None, layerDepth: 0);
            }

            _spriteBatch.DrawString(_defaultFont, string.Format("FPS:{0}, Num of sprites:{1}",
             System.Math.Round(1.0d / gameTime.ElapsedGameTime.TotalSeconds, 2), this._sprites.num), Vector2.Zero, Color.White);

            _spriteBatch.DrawString(_defaultFont, string.Format("X:{0}, Y:{1}",
              _mouse.X / _matrix.M11, _mouse.Y / _matrix.M22), new Vector2(0, 100), Color.White);

            _spriteBatch.End();

            base.Draw(gameTime);
        }
    }
}`

**Comment by hajimehoshi** [comment]
Thank you for reporting, but I think there are no obvious issues in this comparison: Ebiten and MonoGame are much different in terms of API philosophies.

**Comment by hajimehoshi** [comment]
No action items here. Let me close this.
