### ISSUE TITLE
text: Make Draw take a GeoM argument

### ISSUE THREAD

**Issue by nanoslayer** [hajimehoshi/ebiten#1461]
Some sort of GeoM equivalent for text.Draw could be useful, especially for scaling text. The Draw function could take a GeoM argument instead of an x, y coordinate pair.

This might also allow rotating text.

**Comment by nanoslayer** [comment]
It seems like an option for scaling text should be very easy to add. Rotating text, however, seems more difficult to achieve.

What do you think of adding a DrawScaled function with two extra parameters: scaleX and scaleY.

```go
func Draw(dst *ebiten.Image, text string, face font.Face, x, y int, clr color.Color)
func DrawScaled(dst *ebiten.Image, text string, face font.Face, x, y int, clr color.Color, scaleX, scaleY float64)
```

The scale would be passed to drawGlyph, which would then scale the glyphs after translating them.

An alternative approach would be to introduce an Options struct, and a new function called DrawOptions:

```go
type Options struct {
    X, Y int
    Face font.Face
    Color color.Color
    ScaleX, ScaleY float64
}

func DrawOptions(dst *ebiten.Image, text string, options Options)
```

The advantage of this approach is that we can add new options (like Rotation) later on.

**Comment by hajimehoshi** [comment]
Sorry I forgot the context at the first comment.

Wouldn't it be enough to render the text on an offscreen once, and scale it, or have we already discussed about this idea?

**Comment by nanoslayer** [comment]
> Wouldn't it be enough to render the text on an offscreen once, and scale it, or have we already discussed about this idea?

That seems like it would be very expensive for a simple scaling of the text.

Here's my use case: I want to allow the user to configure the screen resolution. This can be achieved by scaling images to the resolution of the screen with ebiten.GeoM.Scale (this was discussed in #1335). I also need to be able to scale text for this to work properly.

Here's a patch that adds the DrawScaled function:

```diff
diff --git a/text/text.go b/text/text.go
index b9648e37..da934d87 100644
--- a/text/text.go
+++ b/text/text.go
@@ -49,7 +49,7 @@ func fixed26_6ToFloat64(x fixed.Int26_6) float64 {
        return float64(x>>6) + float64(x&((1<<6)-1))/float64(1<<6)
 }
 
-func drawGlyph(dst *ebiten.Image, face font.Face, r rune, img *ebiten.Image, x, y fixed.Int26_6, clr ebiten.ColorM) {
+func drawGlyph(dst *ebiten.Image, face font.Face, r rune, img *ebiten.Image, x, y fixed.Int26_6, clr ebiten.ColorM, scaleX, scaleY float64) {
        if img == nil {
                return
        }
@@ -57,6 +57,7 @@ func drawGlyph(dst *ebiten.Image, face font.Face, r rune, img *ebiten.Image, x,
        b := getGlyphBounds(face, r)
        op := &ebiten.DrawImageOptions{}
        op.GeoM.Translate(float64((x+b.Min.X)>>6), float64((y+b.Min.Y)>>6))
+       op.GeoM.Scale(scaleX, scaleY)
        op.ColorM = clr
        dst.DrawImage(img, op)
 }
@@ -173,6 +174,10 @@ var textM sync.Mutex
 //
 // Draw is concurrent-safe.
 func Draw(dst *ebiten.Image, text string, face font.Face, x, y int, clr color.Color) {
+       DrawScaled(dst, text, face, x, y, clr, 1, 1)
+}
+
+func DrawScaled(dst *ebiten.Image, text string, face font.Face, x, y int, clr color.Color, scaleX, scaleY float64) {
        textM.Lock()
        defer textM.Unlock()
 
@@ -201,7 +206,7 @@ func Draw(dst *ebiten.Image, text string, face font.Face, x, y int, clr color.Co
                }
 
                img := getGlyphImage(face, r)
-               drawGlyph(dst, face, r, img, fx, fy, colorm)
+               drawGlyph(dst, face, r, img, fx, fy, colorm, scaleX, scaleY)
                fx += glyphAdvance(face, r)
```

**Comment by hajimehoshi** [comment]
> That seems like it would be very expensive for a simple scaling of the text.

Hmm, have you actually measured the performance? Of course it is less performative than having a scaling argument though.

If we adopt a new API, I prefer having an 'option' argument as you already suggested. I'd suggest this:

```
DrawWithOptions(dst *ebiten.Image, face font.Face, text string, op *ebiten.DrawImageOptions)
```

* A font face is not an option and should be a regular argument.
* Not only scaling, there are other useful options like `Filter`.

**Comment by nanoslayer** [comment]
> If we adopt a new API, I prefer having an 'option' argument as you already suggested. I'd suggest this:
> 
> ```
> DrawWithOptions(dst *ebiten.Image, face font.Face, text string, op *ebiten.DrawImageOptions)
> ```

This API would actually be a lot nicer! I would prefer it over the DrawScaled function mentioned earlier. I just wasn't sure exactly how it would work.
