### ISSUE TITLE
Solus need additional dependency

### ISSUE THREAD

**Issue by nullptr023** [hajimehoshi/ebiten#1463]
Hi,

I started installing ebiten to Solus Distro to try out game development. I'm getting error regarding glfw when trying to install.
# github.com/go-gl/glfw/v3.3/glfw
/usr/bin/ld: cannot find -lXxf86vm
collect2: error: ld returned 1 exit status

I saw another issue similar to this with Ubuntu and fixes it with installing another dependency 'libxxf86vm-dev'.
For Solus the equivalent dependency is '**libxxf86vm-devel**'

It would be helpful to add it ebiten documentation

Thank you

**Comment by hajimehoshi** [comment]
Thank you for pointing this out!
