### ISSUE TITLE
glfw (opengl) SwapBuffers skips frames when shareable.Image.makeShared has just run

### ISSUE THREAD

**Issue by windo** [hajimehoshi/ebiten#1464]
I'm observing a progressively worsening stuttering once every second in my new ebiten-based app. I'm using the v2 branch on Linux, with glfw UI using opengl.

The app is a music visualization app - based on music notes sent to it, it generates scrolling tracks visualizing the music being played. As such, I create a bunch of images (in a tiled manner) all the time to scroll them across the screen. However, it seems like the `SwapBuffers` call will get progressively more and more slower, in steps, as I generate more of these scrolling images over time - and `Dispose` does not seem to help.

I've added some instrumentation to the `UserInterface.loop` function [here](https://github.com/hajimehoshi/ebiten/blob/master/internal/uidriver/glfw/ui.go#L803):

```go
func logIfLonger(msg string, t time.Duration) func() {
    start := time.Now()
    return func() {
        d := time.Now().Sub(start)
        if d > t {
            log.Printf("%s: %dms exceeded: %dms\n", msg, t.Milliseconds(), d.Milliseconds())
        }
    }
}
```

```go
        f := logIfLonger("swap", 50*time.Millisecond)
        _ = u.t.Call(func() error {
            u.swapBuffers()
            return nil
        })
        f()
```

These calls start off taking a few hundred microseconds, then after a few seconds they start to take 80ms ~once every second, then ~minute later still ~180ms:

```
2021/01/16 22:59:00 New track
2021/01/16 22:59:08 swap: 50ms exceeded: 88ms
2021/01/16 22:59:09 swap: 50ms exceeded: 85ms
2021/01/16 22:59:10 swap: 50ms exceeded: 84ms
2021/01/16 22:59:11 swap: 50ms exceeded: 83ms
...
2021/01/16 23:00:31 swap: 50ms exceeded: 87ms
2021/01/16 23:00:31 swap: 50ms exceeded: 88ms
2021/01/16 23:00:32 swap: 50ms exceeded: 84ms
2021/01/16 23:00:34 swap: 50ms exceeded: 197ms
2021/01/16 23:00:34 swap: 50ms exceeded: 191ms
2021/01/16 23:00:35 swap: 50ms exceeded: 192ms
...
```

There is some type of a slow memory leak happening with images too, so I wonder if they are building up somewhere where they get in the way of swapping buffers? I've sort of been careful to not leak anything but I guess I could have missed something too. A heap profile seems to think most of the memory is allocated in `internal.shareable.image` though:

```
(pprof) top
Showing nodes accounting for 180.98MB, 100% of 180.98MB total
Showing top 10 nodes out of 18
      flat  flat%   sum%        cum   cum%
  178.23MB 98.48% 98.48%   178.23MB 98.48%  github.com/hajimehoshi/ebiten/v2/internal/shareable.(*Image).replacePixels
    1.38MB  0.76% 99.24%     1.38MB  0.76%  github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*context).framebufferPixels.func2
    1.37MB  0.76%   100%   179.60MB 99.24%  github.com/hajimehoshi/ebiten/v2/internal/shareable.(*Image).makeShared
         0     0%   100%   179.60MB 99.24%  github.com/hajimehoshi/ebiten/v2.(*uiContext).Update
         0     0%   100%   179.60MB 99.24%  github.com/hajimehoshi/ebiten/v2.(*uiContext).update
```

It's getting late here, I'll poke more tomorrow. But I thought I'd post it here just in case there is an obvious answer to this.

**Comment by hajimehoshi** [comment]
> As such, I create a bunch of images (in a tiled manner) all the time to scroll them across the screen. 

Does this mean you create images every frame? I don't recommend to do that. As the pprof result saids, replacing pixels (at creating images) is the heaviest task.

**Comment by windo** [comment]
Not every frame. I create at least 1 image every second for a new tile (actually, more like a time slice I guess) and re-create that image if there are any new notes played that have to be shown - this will happen a few times.

In case it helps:

 * capture of what the sort of idea is: https://www.youtube.com/watch?v=5FjgZ76NO14
 * code so far: https://github.com/windo/trosces

The pprof is for a heap dump, so it's heavy in the sense that it uses a lot of memory. Looks the memory "leak" and your comment did lead me closer to the problem - I added some extra logging on new image allocation and this is what I got:

```
2021/01/17 08:59:39 restorable newimage
2021/01/17 08:59:39 restorable newimage
2021/01/17 08:59:39 restorable newimage
2021/01/17 08:59:39 new node on backend: *shareable.backend
2021/01/17 08:59:39 restorable newimage
2021/01/17 08:59:39 glfw SwapBuffers: 50ms exceeded: 86ms
2021/01/17 08:59:39 swap: 50ms exceeded: 87ms
2021/01/17 08:59:39 restorable newimage
2021/01/17 08:59:39 restorable newimage
2021/01/17 08:59:39 restorable newimage
```

So the long SwapBuffers happen whenever a new node is created here:

https://github.com/hajimehoshi/ebiten/blob/master/internal/shareable/image.go#L631

Based on your suggestion to avoid new images, I've now changed my code to reuse `ebiten.Image` objects (see usage of cached and unused in https://github.com/windo/trosces/blob/main/track.go) by collecting the sliced/tiles that went off screen and then redrawing them, but that new node is still allocated about once a second and the next `SwapBuffer` after it will take 80ms:

```
2021/01/17 10:27:01 Starting cleanup
2021/01/17 10:27:01 Adding 2021-01-17 10:26:53 +0000 GMT to unused
2021/01/17 10:27:01 Adding 2021-01-17 10:26:52 +0000 GMT to unused
2021/01/17 10:27:01 Adding 2021-01-17 10:26:54 +0000 GMT to unused
2021/01/17 10:27:01 Adding 2021-01-17 10:26:55 +0000 GMT to unused
2021/01/17 10:27:01 Adding 2021-01-17 10:26:56 +0000 GMT to unused
2021/01/17 10:27:01 Finished cleanup
2021/01/17 10:27:01 new node on backend: *shareable.backend
2021/01/17 10:27:01 Stack: goroutine 21 [running]:
github.com/hajimehoshi/ebiten/v2/internal/shareable.(*Image).allocate(0xc0004868a0, 0xc000745a01)
	/home/siim/projects/ebiten/internal/shareable/image.go:617 +0x223
github.com/hajimehoshi/ebiten/v2/internal/shareable.(*Image).replacePixels(0xc0004868a0, 0xc001636000, 0x145800, 0x145800)
	/home/siim/projects/ebiten/internal/shareable/image.go:435 +0x2d6
github.com/hajimehoshi/ebiten/v2/internal/shareable.(*Image).makeShared(0xc000476c90, 0xc00009a2a0, 0xc000487860)
	/home/siim/projects/ebiten/internal/shareable/image.go:264 +0x271
github.com/hajimehoshi/ebiten/v2/internal/shareable.makeImagesShared(0x3c9, 0x15f)
	/home/siim/projects/ebiten/internal/shareable/image.go:86 +0xd1
github.com/hajimehoshi/ebiten/v2/internal/shareable.init.0.func1(0x0, 0x0)
	/home/siim/projects/ebiten/internal/shareable/image.go:62 +0x76
github.com/hajimehoshi/ebiten/v2/internal/hooks.RunBeforeUpdateHooks(0x0, 0x0)
	/home/siim/projects/ebiten/internal/hooks/hooks.go:38 +0xb8
github.com/hajimehoshi/ebiten/v2.(*uiContext).update(0x8987e0, 0x0, 0x0)
	/home/siim/projects/ebiten/uicontext.go:194 +0x94
github.com/hajimehoshi/ebiten/v2.(*uiContext).Update(0x8987e0, 0xc000745dc0, 0x6e7b60)
	/home/siim/projects/ebiten/uicontext.go:158 +0xaa
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).update(0x880460, 0xc000486840, 0x696775)
	/home/siim/projects/ebiten/internal/uidriver/glfw/ui.go:871 +0x2fc
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0x880460, 0x0, 0x0)
	/home/siim/projects/ebiten/internal/uidriver/glfw/ui.go:929 +0x172
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).run(0x880460, 0x0, 0x0)
	/home/siim/projects/ebiten/internal/uidriver/glfw/ui.go:772 +0x2e4
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run.func1(0x880460, 0xc0000b2420)
	/home/siim/projects/ebiten/internal/uidriver/glfw/ui.go:605 +0x72
created by github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run
	/home/siim/projects/ebiten/internal/uidriver/glfw/ui.go:597 +0x131

2021/01/17 10:27:01 glfw SwapBuffers: 50ms exceeded: 92ms
2021/01/17 10:27:01 swap: 50ms exceeded: 92ms
```

So something is happening within ebiten that will trigger expensive operations regularly. Looking around, I saw the logic with `nonUpdatedCount` and `MaxCountForShare`. So I changed MaxCountForShare from 10 to 1000. Now my app runs smooth without the ~80ms UI pauses every ~second.

I'm sure I haven't understood the issue to the core, but it appears that in this case, the creation of shared images is causing a hiccup. But maybe there's more to it? I can do local builds and disable the sharing, but it would be cool to figure out if this could be improved in ebiten, too.

I suppose it has something to do with the expensive GL ops that somehow get sent as part of making images shared that take 80ms on my laptop (5-years old, integrated intel graphics) to render. And since I redraw an the current timeslice image then whenever I switch to the next, soon a new image will be ready to be "shared", triggering the artifact.

I guess I'm hitting this because I'm dynamically creating the images using `vector.Path.Fill`, which I understand is an experimental feature. That might explain why I'm hitting this but others are not?

**Comment by hajimehoshi** [comment]
I have updated Ebiten one or two hours ago. Is your problem reproduced even on the latest Ebiten (0c578f1670d6a312f8922950a738a5fd08d096e2)?

**Comment by hajimehoshi** [comment]
> I'm sure I haven't understood the issue to the core, but it appears that in this case, the creation of shared images is causing a hiccup. But maybe there's more to it? I can do local builds and disable the sharing, but it would be cool to figure out if this could be improved in ebiten, too.

I think this is the point. In Ebiten, an offscreen image becomes an independent image when the image is used as a rendering target, and became on a shared image when the image was NOT used as a rendering target for a while. With the latest Ebiten's change, Ebiten tries to make the image on the shared image only when the image is used as a rendering source for a while.

**Comment by windo** [comment]
I did try the latest master, it still has the stuttering/frame skips - now there are 2 in a row.

**Comment by hajimehoshi** [comment]
Thank you for trying. I'll take a look at your code.

**Comment by hajimehoshi** [comment]
![image](https://user-images.githubusercontent.com/16950/104839825-1d879500-5907-11eb-903d-ff3a0d29934f.png)

BTW, is this an expected screenshot?

**Comment by windo** [comment]
Yes, run with `--simulate-input` to get some simulated inputs (it's intended to visualize events sent from a music production system).

**Comment by hajimehoshi** [comment]
Thanks. My understanding is that a new image is created at least every second. In my environment (MacBook Pro 2020) I don't observe any delays, but I understand the current implementation might slow the application down.

My intuition is that you can rewrite the code without using offscreens, i.e., you can rewrite the code without NewImage calls at Update. It's unfortunate that Ebiten cannot run your application faster without changing your code, but sometimes it is inevitable on some environment.

**Comment by windo** [comment]
Images (as in `ebiten.Image`) are now reused, so only about 10 are created (well, a few more because new ones are created when keyboard size changes). So in steady state, no new images should be created, but they will be cleared and redrawn.

**Comment by hajimehoshi** [comment]
A log `Creating new` is recorded every second. Doesn't this mean an image is created every second?

**Comment by windo** [comment]
That's happening while the keyboard size changes and the image layout changes. Once it stabilizes, it starts logging "reusing unused". That's also about the time where I start seeing the hiccups, it takes a minute or so.

**Comment by hajimehoshi** [comment]
OK so should I wait for a minute or so to see the issue...? Would it be possible to make a minimized test case to reproduce the issue?

**Comment by windo** [comment]
I'll give it a go!

**Comment by windo** [comment]
This is a bit trippy, but reproduces the issue for me:

```go
package main

import (
	"fmt"
	"image/color"
	"math"

	"github.com/hajimehoshi/ebiten"
)

const ImageCount = 10
const ImageSize = 500
const Area = 800

type Game struct {
	counter int
	images  []*ebiten.Image
}

func (g *Game) Draw(screen *ebiten.Image) {
	for i := 0; i < ImageCount; i++ {
		op := ebiten.DrawImageOptions{}
		band := float64(Area / ImageCount)

		op.GeoM.Translate(
			float64(i)*band+math.Mod(float64(g.counter)*math.Pow(1.02, float64(i)), band),
			math.Mod(float64(g.counter)*math.Pow(1.03, float64(i)), Area),
		)

		screen.DrawImage(g.images[i], &op)
	}
}
func (g *Game) Update() error {
	i := (g.counter / 5) % ImageCount
	c := i*0xff/ImageCount + g.counter*0xff/60
	image := g.images[i]
	image.Clear()
	image.Fill(color.RGBA{uint8(c), uint8(c + 80), uint8(c + 160), 0xff})

	g.counter++
	return nil
}
func (g *Game) Layout(w, h int) (int, int) { return w, h }

func main() {
	g := Game{
		images: []*ebiten.Image{},
	}

	for i := 0; i < ImageCount; i++ {
		g.images = append(g.images, ebiten.NewImage(ImageSize, ImageSize))
	}

	ebiten.SetWindowResizable(true)
	err := ebiten.RunGame(&g)
	if err != nil {
		fmt.Printf("Error: %v", err)
	}
}
```

Try with `MaxCountForShare` set to 10 and then with 1000. For me locally:

 * with 10 the UI updates are choppy throughout
 * with 1000 the UI updates are choppy for the first few seconds (looks like until each image has had it's pixels updated at least once?) then smooth

The logging around SwapBuffers indicates that some expensive GL stuff (I guess updating buffers?) is happening behind the scenes to cause the choppiness.

**Comment by hajimehoshi** [comment]
> 	"github.com/hajimehoshi/ebiten"

Doesn't this use v2?

**Comment by hajimehoshi** [comment]
I understood the issue. In the code, an image is used both for a source and a destination (Fill). The point is that the images are *sometimes* used as a destination, and Ebiten tries to put the images on a texture atlas after the images are used as sources.

So, this problem can be fixed by not using an image as a source and a destination at the same time. There might be a fix in Ebiten, but I don't come up with a good idea so far. Let me think.

**Comment by windo** [comment]
I wrote this in a temp directory, I don't know how to specify modules for standalone go files. This ran against the latest master, that should be the correct, right?

**Comment by hajimehoshi** [comment]
Without /v2, this doesn't work with the latest Ebiten. The issue seems to exist both in v1 and v2 anyway.

**Comment by hajimehoshi** [comment]
> So, this problem can be fixed by not using an image as a source and a destination at the same time. 

In your application, would it be possible to render grid images (`getGrid`) to the destination image instead of a cached image (`getCached`) directly?

**Comment by windo** [comment]
That sounds entirely OK - it would double the `screen.DrawImage()` calls but it would remove the `cachedImage.DrawImage()` calls entirely - the cached time slice images would then only be manipulated with `Fill` and `path.Fill`.

**Comment by hajimehoshi** [comment]
Thanks. I'll add more notes that using an image for a rendering source and a target at the same time might be problematic to the performance tips: https://ebiten.org/documents/performancetips.html#Avoid_changing_render_sources'_pixels (actually there already exists a note, but this is for different reasons)

**Comment by hajimehoshi** [comment]
I couldn't come up with a good tip for this issue.

Instead, I improved the internal logic of Ebiten. @windo, perhaps you have already avoided this issue in some ways, but I hope the latest Ebiten should fix the issue you reported.

I'll keep this issue open but I might close this later.
