### ISSUE TITLE
FPS is unstable when using inpututil.IsKeyJustPressed in window mode on Windows

### ISSUE THREAD

**Issue by rainyFy** [hajimehoshi/ebiten#1473]
The FPS dropped to around 30 to 50 from time to time when using `inpututil.IsKeyJustPressed` in window mode. All I did was render an image and move it according to keyboard inputs by `ebiten.IsKeyPressed` and use `inpututil.IsKeyJustPressed` to check the Ecs key to close the game and use a font to show FPS and TPS, then I noticed stutters and the FPS dropped sharply from time to time. After I played with it for a while, I found that this problem only occurs when using `inpututil.IsKeyJustPressed` and in window mode.

Then I did a test for the total length of time where FPS is below some specific values during the first 2 minutes (excluding the first 2 seconds), the results are as follows:

|                                            | FPS < 59 | FPS < 57 | FPS < 50 |
| ------------------------------------------ | -------- | -------- | -------- |
| without `IsKeyJustPressed` in window mode  | 2 s      | 0        | 0        |
| with `IsKeyJustPressed` in window mode     | 52 s     | 39 s     | 19 s     |
| with `IsKeyJustPressed` in fullscreen mode | 0        | 0        | 0        |

I also have noticed issue #1467 which has a similar problem, but that has some relation to G-Sync, since my problem accours on both the integrated Intel GPU and the discrete NVIDIA GPU in my laptop, and the test was run on the Intel GPU, so this should has no relation to G-Sync. (By the way my laptop was bought in 2018, not too old and still runs smoothly. (^_^) )

The test code is attached here.
[main.go.txt](https://github.com/hajimehoshi/ebiten/files/5871360/main.go.txt)

**Comment by cdrpl** [comment]
I've noticed a similar issue with inpututil.IsKeyJustPressed using up double the CPU percentage compared to ebiten.IsKeyPressed. My computer is a laptop running Windows 10 with ebiten running in windows mode.

**Comment by hajimehoshi** [comment]
Thanks. What version of Ebiten did you test? Does this happen on the latest commit (master branch)?

**Comment by hajimehoshi** [comment]
My intuition is that `update` might be heavy (https://github.com/hajimehoshi/ebiten/blob/master/inpututil/inpututil.go#L69). Then, just importing `_ "github.com/hajimehoshi/ebiten/inpututil"` without using `IsKeyJustPressed` might also be problematic.

**Comment by rainyFy** [comment]
I tested on v2.0.3, and as you said the problem occurs if just importing `_ "github.com/hajimehoshi/ebiten/inpututil"`, then I just tested on master branch and the problem didn't occur when importing `inpututil` with or without `IsKeyJustPressed`. Looks like it is already solved?

**Comment by hajimehoshi** [comment]
Thank you for confirming! It looks like so :)

Actually I added some optimizations to `inpututil` two days ago!

https://github.com/hajimehoshi/ebiten/commit/2b77b57b7597ede5fd9d1447c072f6d23feffe6d
