### ISSUE TITLE
Kage shaders: allow uniforms in loop bounds

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1496]
It'd be nice to allow uniforms in loop boundaries, which helps with loop unrolling (at least in the DarkPlaces game engine, in the OFFSETMAPPING_RELIEFMAPPING case, this works pretty well).

In my concrete case, I need two blurs with different radii. My shader is:

```
 package main
 
 var Size float
 var Step vec2
 var Scale float
 
 func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
        srcOrigin, srcSize := imageSrcRegionOnTexture()
        srcMax := srcOrigin + srcSize
        acc := imageSrc0UnsafeAt(texCoord)
        srcStep := Step * srcSize
        for y := 1.0; y <= 12.0; y++ {
                if y <= Size {
                        d := y * srcStep
                        acc += imageSrc0UnsafeAt(clamp(texCoord-d, srcOrigin, srcMax))
                        acc += imageSrc0UnsafeAt(clamp(texCoord+d, srcOrigin, srcMax))
                }
        }
        return acc * Scale
 }
```

I call this shader 4 times per frame (once with large radius (12) and horizontally, once vertically, once with small radius (1) and horizontally, one vertically) on a Lenovo X1 Carbon v4 at 640x360 textures. Changing this shader to two separate shaders, with the radii hardcoded (the loop now being for y := 1.0; y <= 12.0; y++ and the conditional gone), saves 1ms per frame according to apitrace, and according to show_fps brings my top framerate from 220fps to 280fps. Yes, sounds like first world problems, but I'd like to support weaker devices than this, after all :)

So, it'd be really nice if it were allowed to write for y := 1.0; y <= Size; y++. As a temporary workaround I plan to use some form of templating on the shader code so I can perform this as a textual replacement.

**Comment by hajimehoshi** [comment]
Hi,

Unfortunately, for-loop's condition must have a constant value (e.g., GLSL ES 2.0), then I think it'd be hard or impossible to have a uniform variable there. I'd use a big enough value in the condition and use `break`.

**Comment by hajimehoshi** [comment]
> As a temporary workaround I plan to use some form of templating on the shader code so I can perform this as a textual replacement.

This should also work as long as the variety is not so big.

**Comment by divVerent** [comment]
Thanks; I had wrongly assumed uniforms count as constants in GLSL (and I am absolutely aware that to graphics drivers they tend to be treated as such, e.g. I've caught the nvidia driver at relinking a shader program for uniform values being zero vs nonzero as an optimization).

Benchmarked now the "break" approach too, but in my concrete case a separate shader program is substantially faster and the way to go anyway. Kinda sad I have to use my own templating, because when I try to use text/template and {{ .Size }}, the kage code is no longer supported by gofmt, which is unfortunate.

Would then be nice to maybe have some kind of "nice" built-in templating in kage to simulate such constants, with code maybe looking like:

```
const Size int = Param("Size")
```

(too bad it can't just be "const Size int" or similar; although very tempting, gofmt no longer likes the code then)

**Comment by hajimehoshi** [comment]
Instead of `text/template`, I'd use a usual constant name like `__SIZE__` and replace it with `strings.ReplaceAll` so that I could use gofmt. I think `text/template` is overkill there.

**Comment by divVerent** [comment]
I ended up writing it as PARAMS["Size"] and doing textual replacement - mainly because it kinda looks like it could be a real future extension to Kage and gofmt likes it.
