### ISSUE TITLE
Examples in gh-pages branch do not work

### ISSUE THREAD

**Issue by martinkirsche** [hajimehoshi/ebiten#150]
The examples within your gh-pages branch (e. g. https://hajimehoshi.github.io/ebiten/example/blocks.html) do not work when visiting `hajimehoshi.github.io/ebiten` using `https`. When I manually switch back to `http` it works. When visiting the Ebiten homepage from google then `https` is the default. So for almost all new potential users of Ebiten (including me) the examples do not work within there browser.

**Comment by hajimehoshi** [comment]
Thank you for reporting. I'll fix this asap.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/5762f5e3548b2c94000f380de88ad2633cae6a76 Fixed!
