### ISSUE TITLE
On windows, examples\fullscreen does not allow alt-tabbing to other windows

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#1504]
It seems like the reason is this line in internal\uidriver\glfw\ui.go:

`glfw.WindowHint(glfw.AutoIconify, glfw.False)`

If I change it to this, it works as I expect:

`glfw.WindowHint(glfw.AutoIconify, glfw.True)`

Is this the intended behavior of ebiten? It feels like alt-tab only works as expected if I set AutoIconify to True. I'm happy to submit a PR if others agree with the change.

**Comment by hajimehoshi** [comment]
Hmm, auto-iconifying caused an issue: #1405 then the current implementation is intended.

**Comment by hajimehoshi** [comment]
I agreed that the window should be iconified (or windowed?) when alt+tab or ⌘+tab is pressed. However, auto-iconifying iconifies the window even when the virtual desktop is switched on macOS and Windows, which is problematic. I'm now investigating how to satisfy both the conditions.

**Comment by hajimehoshi** [comment]
I'll just revert the change.

The ideal implementation is:

* When the user switches (virtual) desktops, the application should remain fullscreen.
* When the user switches the application in a different monitor, the application should remain fullscreen.
* When the user switches the application in the same monitor and the same desktop, the application should be iconified.

This is not an obvious task, then I'll just revert the fix so far.
