### ISSUE TITLE
Fullscreen -> windowed mode crash

### ISSUE THREAD

**Issue by essial** [hajimehoshi/ebiten#1505]
It seems with the latest master version, if you fullscreen, then restore to window you can get a mutex panic at line 706 of image.go (restorable.RestoreIfNeeded()). The specific error is "sync: unlock of unlocked mutex".

**Comment by hajimehoshi** [comment]
Hi, thank you for reporting! Which environment are you using (macOS or Windows)?

**Comment by essial** [comment]
It happens to me on Mac but there's a Windows guy who's also having this issue.

**Comment by essial** [comment]
I'm calling it right at the start of Update if that makes any difference..

`func (m *MainWindow) Update() error {
	if inpututil.IsKeyJustPressed(ebiten.KeyEnter) && ebiten.IsKeyPressed(ebiten.KeyAlt) {
		ebiten.SetFullscreen(!ebiten.IsFullscreen())
		return nil
	}`

**Comment by hajimehoshi** [comment]
Could you show the log at the crash?

**Comment by hajimehoshi** [comment]
Reproduced with this:

```go
package main

import (
        "github.com/hajimehoshi/ebiten/v2"
        "github.com/hajimehoshi/ebiten/v2/inpututil"
)

type Game struct {
}

func (g *Game) Draw(screen *ebiten.Image) {
}
func (g *Game) Update() error {
        if inpututil.IsKeyJustPressed(ebiten.KeyEnter) && ebiten.IsKeyPressed(ebiten.KeyAlt) {
                ebiten.SetFullscreen(!ebiten.IsFullscreen())
        }
        return nil
}
func (g *Game) Layout(w, h int) (int, int) {
        return 640, 480
}

func main() {
        ebiten.SetWindowResizable(true)
        if err := ebiten.RunGame(&Game{}); err != nil {
                panic(err)
        }
}
```

**Comment by hajimehoshi** [comment]
git bisect says 9400efa9a5ca92b3059682b9826b801507bd709b is the culprit.

**Comment by hajimehoshi** [comment]
@essial reported this was not fixed yet.

**Comment by hajimehoshi** [comment]
Looks like this can be reproduced on `examples/windowsize`, not 100% though.
