### ISSUE TITLE
enable to hide from a taskbar on Windows

### ISSUE THREAD

**Issue by matthewwiese** [hajimehoshi/ebiten#1518]
I am playing around with the [mascot example](https://github.com/hajimehoshi/ebiten/tree/master/examples/mascot) for use as a [desktop pet](https://en.wikipedia.org/wiki/Digital_pet).

I would like the application to not appear in the user's taskbar (instead in the system tray).

It is my understanding a common method to hide an application from the taskbar (on Windows) is to pass the [WS_EX_TOOLWINDOW](https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles) constant as an argument when creating the window. Since my use-case is an an idle virtual companion, this window style seems appropriate.

I have searched through the documentation and have not found a way to "intercept" or otherwise modify how the window is created. An ignorant perusal through the source yielded [`glfw_windows.go`](https://github.com/hajimehoshi/ebiten/blob/master/internal/glfw/glfw_windows.go) as a potential place to handle this. However, brief research suggests that it [isn't currently implemented in GLFW](https://github.com/glfw/glfw/issues/1179#issuecomment-356427430)?

Is this functionality possible?

**Comment by hajimehoshi** [comment]
There is no way to pass arguments to CreateWindowEx so far. So the answer is no so far, but let me consider to make it possible in the future.

**Comment by hajimehoshi** [comment]
Let me keep this opened for the future task.

**Comment by matthewwiese** [comment]
Apologies!

**Comment by hajimehoshi** [comment]
It's in theory possible to do without Ebiten's change: https://stackoverflow.com/questions/1462504/how-to-make-window-appear-in-taskbar

**Comment by hajimehoshi** [comment]
GLFW might have this feature in the future: https://github.com/glfw/glfw/issues/293

**Comment by hajimehoshi** [comment]
Hmm, I couldn't come up with a good name. The API would work only on Windows...

**Comment by matthewwiese** [comment]
> Hmm, I couldn't come up with a good name. The API would work only on Windows...

An effort was made! :muscle:

**Comment by hajimehoshi** [comment]
We need more time to investigate how to implement this on every platform including macOS and Linux

**Comment by hajimehoshi** [comment]
Note that this is probably possible by calling Win32API directly like this

```
// Win32API functions can be called by golang.org/x/windows
hw := GetActiveWindow()
style := GetWindowLong(hw, GWL_EXSTYLE)
SetWindowLong(hw, GWL_EXSTYLE, (style & ~WS_EX_APPWINDOW) | WS_EX_TOOLWINDOW)
```

**Comment by hajimehoshi** [comment]
https://github.com/glfw/glfw/issues/293

**Comment by hajimehoshi** [comment]
This might be a little risky but I'm thinking to apply `WS_EX_TOOLWINDOW` automatically when the window's decoration is hidden, rather than providing an API for this.

**Comment by hajimehoshi** [comment]
https://github.com/electron/electron/blob/184ac2b382e8324a0b3db1944fd17cdd6ccffff9/shell/browser/native_window_views.cc#L353-L355

In Electron, `toolbar` option is available only for Windows

**Comment by hajimehoshi** [comment]
I don't implement this for macOS so far. I'll revisit when we find it necessary.
