### ISSUE TITLE
Performance drop from v2.1.0-alpha.12 to v2.1.0-alpha.13

### ISSUE THREAD

**Issue by countcb** [hajimehoshi/ebiten#1520]
From time to time I check the alpha releases of ebiten.
I noticed that the performance of my game was much better with v2.1.0-alpha.12 than with v2.1.0-alpha.13.

I could reproduce this with the "sprites" example. I modified the example so that it runs without vsync (via `ebiten.SetVsyncEnabled(false)`). That's the only change I made to the example in both versions.

v2.1.0-alpha.12
500 sprites: ~2600 FPS
7000 sprites: ~1700 FPS

v2.1.0-alpha.13
500 sprites: ~1190 FPS (~45% of alpha 12)
7000 sprites: ~200 FPS (~12% of alpha 12)

I do not think that this the performance of alpha 13 is not good enough. But the performance of 12 was much better.
So I just wanted to give this feedback so that in case that this was not done by a change on purpose you can have a deeper look what might have caused this drop in performance.

I'm sorry if this kind of feedback is not wanted for the alpha releases. Feel free to close this issue. :)

Thanks alot for this great engine!

**Comment by hajimehoshi** [comment]
Which environment are you using? Thanks!

**Comment by hajimehoshi** [comment]
OK the culprit was 0b30ed595955b5f3d76808c135f739a0ec29944b.

**Comment by countcb** [comment]
Sorry that I didn't reply to your question in time!
But it seems like you already found the culprit without my input.
If you have any questions feel free to ask though. :)

**Comment by hajimehoshi** [comment]
I'm afraid I reverted the change for this issue, as we found an issue #1595: The value of FPS doesn't match with the number of Draw calls per second, and becomes meaningless. I'll consider to add a new API to skip Draw calls for v2.2.
