### ISSUE TITLE
Update GLFW to v3.3.3

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1523]
This seems important for M1 Mac. See also https://github.com/go-gl/glfw/issues/303

**Comment by hajimehoshi** [comment]
We have to update GLFW also for Windows.

**Comment by pwaller** [comment]
You probably want to make sure you've got go-gl/glfw@8b90140a4ccf937fdda7f198ea18d9e1e7af1711, otherwise you or your users may hit go-gl/glfw#269 with confusing effects.

**Comment by hajimehoshi** [comment]
Thank you for the heads up, I'll try 87ff8d237f3bf23ca84a97276ac71b06e1709692, which is the latest commit now.
