### ISSUE TITLE
Mode to call Update/Draw not by timings but by events for relatively static applications

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1556]
Requested by @nadimkobeissi

`glfwWaitEvents` is the key https://www.glfw.org/docs/3.3/group__window.html#ga554e37d781f0a997656c26b2c56c835e

**Comment by hajimehoshi** [comment]
Desktops: `glwWaitEvents`
Browsers: Probably handling various event handlers would work
Mobiles: Hmm 🤔

**Comment by Zyko0** [comment]
Could the eventual `SetMaxFPS` be part of this new design ? https://github.com/hajimehoshi/ebiten/discussions/1563

**Comment by hajimehoshi** [comment]
I think I'll add a new option for vsync

- Vsync off
- Vsync on
- Vsync off but waits for events

FPS and TPS values would not make sense in the last mode.

**Comment by hajimehoshi** [comment]
@nadimkobeissi Hi, is this an urgent task (i.e., if I implemented this, will you use this asap)? If not, I'll de-prioritize this.

**Comment by liamg** [comment]
I'd love to see this feature in order to release a new project I've been working on - normally I'd submit a PR, but this is outside of my area of expertise - happy to help witt any testing etc. if required though!

**Comment by hajimehoshi** [comment]
Note to myself

GLFW: `glfwWaitEvents`
browsers: `setTimeout`?
Android: `RENDERMODE_WHEN_DIRTY`
iOS: ?
Nintendo Switch: cannot have this mode (I think)

**Comment by liamg** [comment]
@hajimehoshi Thanks for this, it works great. It makes `KeyPressDuration` being measured in frames... interesting for this scenario, but that's my problem to solve and shouldn't be too difficult. Really appreciate the work, thank you! :+1:
