### ISSUE TITLE
ebiten: Support the mappings for the common gamepad buttons, d-pad, and hats

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1557]
For many gamepads, the d-pad (left/right/up/down digital controller) is exposed as "hats" in the GLFW API, but Ebiten currently only queries buttons and axes.

As Ebiten has an API returning the SDL GUID of a game controller, I assume the intention is to be compatible to `gamecontrollerdb.txt` regarding labelling of axes, buttons and hats (it currently is regarding axes and buttons).

However that'd require exposing "hats" as an extra API (currently they are, due to a compatibility mode in GLFW, exposed as additional buttons):

```
// For backward compatibility with earlier versions that did not have GetHats,
// the button array also includes all hats, each represented as four buttons.
// The hats are in the same order as returned by GetHats and are in the order
// up, right, down and left. To disable these extra buttons, set the
// JoystickHatButtons init hint before initialization.
```

I guess that works, but a clearer way to expose this would be nice. In the long run, maybe by supporting the GLFW gamepad API rather than the joystick API (which applies the `gamecontrollerdb.txt` mappings already for the developer)?

**Comment by hajimehoshi** [comment]
Hi,

Sure, exposing the hats API makes sense.

BTW, I'd like to remove GLFW/gamecontrollerdb.txt dependencies for gamepads in the future, since this causes some issues (e.g., #1229).

**Comment by hajimehoshi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad Hmm, how do I implement the hats API for the web? Perhaps there is no way to do that?

I'll take a look at GLFW implementation, but the notion of dpad might not be universal unfortunately.

**Comment by hajimehoshi** [comment]
> IIRC the web based mapping maps hats to buttons, so the web API normally
> doesn't need any support there. See https://w3c.github.io/gamepad/#remapping

OK so on the web, we cannot distinguish hats and buttons, right?

It's possible to expose the hats API only for desktops (and maybe mobiles), but this doesn't sound portable. Hmm

**Comment by hajimehoshi** [comment]
> so in my game, I had to write my own parser for it and do my own button/axis mapping

IIUC the button mappings vary among desktop OSes, mobiles and browsers. Even Chrome and Firefox have differences! I think gamepad configuration is necessary on the game side in any cases. Unfortunately it is hard for Ebiten to offer consistent mappings.

**Comment by divVerent** [comment]
Yeah... ultimately there are just too many different pads.

Sadly, in my game I have a good reason to NOT have an input settings dialog, as some input features are only introduced later in the game and I don't want to reveal them to people going through the menu before playing (but instead I map the actions to "sufficiently many buttons" so >99% of controllers in gamecontrollerdb.txt can work). But that is the exception.

Also, for now I am lucky that there seems to be no controller yet with more than one hat - so I can rely on the hat as declared in gamecontrollerdb.txt to occupy the last four buttons. In general I am not opposed to keeping hats exposed as buttons, but it'd be nice to then expose an API to tell where buttons end and hats start, so I can interpret gamecontrollerdb.txt more reliably.

**Comment by SolarLune** [comment]
I know it's a little rough to ask just right after the gamepad issue (#1229, #1489) being (hopefully) resolved, but since it has been, would it be possible to work on adding cross-platform gamepad support rather than just joystick support? It'd be so comfortable to specify buttons rather than just button indices. 

> It's possible to expose the hats API only for desktops (and maybe mobiles), but this doesn't sound portable. Hmm

I think this sounds like a fine idea. 

An idea would be to make an additional API that handles gamepads as opposed to joysticks, much like GLFW has; that way, you could just make the API return 0 values on platforms that don't support them (like browsers) and leave the decision of which API to use and how to handle it to the developer rather than coming up with an immediate solution that works on browsers as well. Or maybe have the current joystick API return an indication of whether it's in gamepad mode (if on desktop / mobile and the joystick is a supported gamepad) or joystick mode (on browsers or otherwise)?

**Comment by hajimehoshi** [comment]
Well, supporting the d-pad buttons only on desktops and giving up on other platforms seem to make sense. Let me think.

CC @wasedaigo, who wants better joystick support in Ebiten

**Comment by hajimehoshi** [comment]
My understanding is what we want is enums for https://www.glfw.org/docs/latest/group__gamepad__buttons.html. Is that correct?

**Comment by hajimehoshi** [comment]
For hats, https://www.glfw.org/docs/latest/group__input.html#ga2d8d0634bb81c180899aeb07477a67ea seems fine. I'm a little confused, but would having the enums for Xbox/PS button names be enough?

**Comment by hajimehoshi** [comment]
Hm, perhaps, d-pad (buttons) and hats are different things. Which do we want? @divVerent

**Comment by SolarLune** [comment]
I had something more detailed typed up, but I don't know much about GLFW; I'd just be speculating based off of the API docs you linked / memory with other frameworks. So instead, here's something shorter.

I think additional functions for hats would be good as that mirrors GLFW's approach. I also think we should use the GLFW Gamepad API if supported on the target platform so the enums actually work as they should. The enums allow you to refer to buttons by their name, but I believe the GLFW gamepad API is what actually maps the inputs of the joystick device to these enums so that "GLFW_GAMEPAD_BUTTON_A" actually is the A button on your controller.

**Comment by hajimehoshi** [comment]
Note to my self

https://gamepad-tester.com/ This detects the gamepad correctly (more correct than GLFW??)

**Comment by hajimehoshi** [comment]
> I think additional functions for hats would be good as that mirrors GLFW's approach. I also think we should use the GLFW Gamepad API if supported on the target platform so the enums actually work as they should. The enums allow you to refer to buttons by their name, but I believe the GLFW gamepad API is what actually maps the inputs of the joystick device to these enums so that "GLFW_GAMEPAD_BUTTON_A" actually is the A button on your controller.

I'm still not sure what are hats, but I'll investigate more. Probably my gamepads don't have hats.

And, I think supporting the standard mapping whenever possible should be very useful, like what the above website does. I agree we should add some enum or something.

**Comment by hajimehoshi** [comment]
Note to myself:

From the GLFW implementations, [`glfwGetGamepadState`](https://www.glfw.org/docs/latest/group__input.html#gadccddea8bce6113fa459de379ddaf051) is necessary to use mappings correctly. `glfwGetJoystickButtons` ignore the mappings. Oops...

**Comment by hajimehoshi** [comment]
The action items are:

* Use [`glfwGamepadState`](https://www.glfw.org/docs/latest/group__input.html#gadccddea8bce6113fa459de379ddaf051) and create a new API for hats (this should be done at the same time. As `glfwGamepadState` treats at most 16 buttons, creating a new API for hats is mandatory. For example, a PS4 controller has 18 'buttons', and 4 of them will be hats.)
* Add new enum values representing [the common (Xbox?) gamepad buttons](https://www.glfw.org/docs/latest/group__gamepad__buttons.html).
* Update the mappings with [`glfwUpdateGamepadMappings`](https://www.glfw.org/docs/latest/group__input.html#gaed5104612f2fa8e66aa6e846652ad00f) GLFW 3.3's mapping seems pretty old.

**Comment by hajimehoshi** [comment]
Finally, I abandoned the above action items, and implemented these APIs:

 * `func HasGamepadStandardLayoutMapping`
 * `func IsGamepadStandardButtonPressed`
 * `func GamepadStandardAxisValue`
 * `type StandardGamepadButton`
 * `type StandardGamepadAxis`

This should work on desktops and mobiles so far.

Hats are a notion introduced by SDL and don't exist in the web standard. Hats are just a d-pad game buttons, so Ebiten just treats buttons. In the `StandardGamepadButton` values, `StandardGamepadButtonLeft*` are the hats / d-pad buttons.

I'll be working on other small tasks like adding new APIs for inpututil.
