### ISSUE TITLE
ebiten: Add LeftShift / RightShift and other counterparts for Ctrl, Alt and Super

### ISSUE THREAD

**Issue by AldoReset** [hajimehoshi/ebiten#1561]
Prb:
keyboard do not distinguish ; left shift and right shift, also alt left and alt right(altgr).

miss excl ! , sharp #,  & .

bst regards.

**Comment by hajimehoshi** [comment]
> keyboard do not distinguish

Could you explain why you need to distinguish left and right shifts? (It's ok e.g., you want to do it just for your applications)

> miss excl ! , sharp #, & .

! is represented with '1' and 'shift'. Or you can use `InputChars` if you want input runes.

**Comment by AldoReset** [comment]
i make an emulator, i want use altleft for appleclose and altright for apple open.

bst regards

**Comment by hajimehoshi** [comment]
OK that makes sense.
