### ISSUE TITLE
Shader docs typo: invertsqrt doesn't exist, but inversesqrt does

### ISSUE THREAD

**Issue by henrahmagix** [hajimehoshi/ebiten#1568]
I would submit a PR to fix it but I can't find the docs repo, sorry

https://ebiten.org/documents/shader.html

<img width="376" alt="image" src="https://user-images.githubusercontent.com/1429026/114318635-d2e07800-9b05-11eb-9673-3751e33e2455.png">

**Comment by hajimehoshi** [comment]
Thank you!
