### ISSUE TITLE
ebiten: Add more CursorShapeTypes

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1571]
For example, Ebiten doesn't add cursors `GLFW_HRESIZE_CURSOR` and `GLFW_VRESIZE_CURSOR` since they seem different on macOS from other platforms. Actually they seem like `col-resize` and `row-resize` in CSS on macOS instead of `ew-resize` and `ns-resize` shapes in CSS (See [the NSCursor API document](https://developer.apple.com/documentation/appkit/nscursor?language=objc)). To show `ew-resize` and `nw-resize` on macOS, we'd need to use [undocumented APIs](https://stackoverflow.com/questions/27242353/cocoa-predefined-resize-mouse-cursor) unfortunately. Then, instead of relying on GLFW APIs, we'd need to use native APIs directly.

If we could use [native APIs](https://github.com/glfw/glfw/issues/427#issuecomment-78484813) directly, we could add more various system cursors.

**Comment by tomlister** [comment]
I'd like to tackle this issue. Could you assign it?

**Comment by tomlister** [comment]
This is what I have so far...
```c
static void setNativeCursor(int cursorID) {
  id cursor = [[NSCursor class] performSelector:@selector(arrowCursor)];
  switch(cursorID){
    case 0:
      cursor = [[NSCursor class] performSelector:@selector(_horizontalResizeCursor)];
      break;
    case 1:
      cursor = [[NSCursor class] performSelector:@selector(_verticalResizeCursor)];
      break;
  }
  [cursor push];
}
```
```go
func (u *UserInterface) setNativeCursor(cursor driver.CursorShape) {
	switch cursor {
	case driver.CursorShapeHorizontalResize:
		C.setNativeCursor(C.int(0))
	case driver.CursorShapeVerticalResize:
		C.setNativeCursor(C.int(1))
	}
}
```

**Comment by tomlister** [comment]
Extended to support existing cursors.

**Comment by hajimehoshi** [comment]
Awesome! Please go ahead.

**Comment by tomlister** [comment]
Unsure as how to approach Windows. https://docs.microsoft.com/en-us/windows/win32/menurc/using-cursors
Need access to the winapi message loop 🤔

**Comment by hajimehoshi** [comment]
How does GLFW do to change the cursor shape?

**Comment by tomlister** [comment]
Hmm maybe we don't.
I'll test later if it's possible to call anywhere
```c
static void updateCursorImage(_GLFWwindow* window)
{
    if (window->cursorMode == GLFW_CURSOR_NORMAL)
    {
        if (window->cursor)
            SetCursor(window->cursor->win32.handle);
        else
            SetCursor(LoadCursorW(NULL, IDC_ARROW));
    }
    else
        SetCursor(NULL);
}
```

**Comment by tomlister** [comment]
Currently tearing apart the current chain of functions from ebiten to glfw

**Comment by tomlister** [comment]
We need to load a cursor https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-loadcursora

**Comment by hajimehoshi** [comment]
Yes. Actually Ebiten loads system cursors at the initialization phase.

**Comment by tomlister** [comment]
Any idea where that location is?

**Comment by hajimehoshi** [comment]
This part:

https://github.com/hajimehoshi/ebiten/blob/091e51ae4cedd4ccdc98ef6cb610b35e662cf6d0/internal/uidriver/glfw/ui.go#L188-L192

**Comment by tomlister** [comment]
Ah yes. So I guess for MacOS we only need the native implementation. Windows and Unix should already support horizontal and vertical resize.

**Comment by hajimehoshi** [comment]
For horizontal and vertical resize shapes, yes. For other shapes that GLFW doesn't have, we'd have to implement by ourselves.

**Comment by tomlister** [comment]
Should I make stubs for setNativeCursor in ui_unix.go and ui_windows.go?

**Comment by tomlister** [comment]
Then I just do this
```
func (u *UserInterface) SetCursorShape(shape driver.CursorShape) {
	old := u.setCursorShape(shape)
	if old == shape {
		return
	}
	if !u.isRunning() {
		return
	}
	if runtime.GOOS == "darwin" {
		_ = u.t.Call(func() error {
			u.setNativeCursor(shape)
			return nil
		})
	} else {
		_ = u.t.Call(func() error {
			u.window.SetCursor(glfwSystemCursors[shape])
			return nil
		})
	}
}
```

**Comment by hajimehoshi** [comment]
> Should I make stubs for setNativeCursor in ui_unix.go and ui_windows.go?

Yes, just an empty functions should be fine.

**Comment by tomlister** [comment]
It calls an objc function that sets the cursors
```go
func (u *UserInterface) setNativeCursor(cursor driver.CursorShape) {
	switch cursor {
	case driver.CursorShapeHorizontalResize:
		C.setNativeCursor(C.int(0))
	case driver.CursorShapeVerticalResize:
		C.setNativeCursor(C.int(1))
	case driver.CursorShapeDefault:
		C.setNativeCursor(C.int(2))
	case driver.CursorShapePointer:
		C.setNativeCursor(C.int(3))
	case driver.CursorShapeText:
		C.setNativeCursor(C.int(4))
	}
}
```
=>
```objc
static void setNativeCursor(int cursorID) {
  id cursor = [[NSCursor class] performSelector:@selector(arrowCursor)];
  switch(cursorID){
    case 0:
      cursor = [[NSCursor class] performSelector:@selector(_windowResizeEastWestCursor)];
      break;
    case 1:
      cursor = [[NSCursor class] performSelector:@selector(_windowResizeNorthSouthCursor)];
      break;
    case 2:
      cursor = [[NSCursor class] performSelector:@selector(arrowCursor)];
      break;
    case 3:
      cursor = [[NSCursor class] performSelector:@selector(openHandCursor)];
      break;
    case 4:
      cursor = [[NSCursor class] performSelector:@selector(IBeamCursor)];
      break;
  }
  [cursor push];
}

**Comment by hajimehoshi** [comment]
Thanks. Let's have setNativeCursor with `u.window.SetCursor` for Windows and Linux/UNIX, and leave TODO comment to use the native APIs in the future.

**Comment by tomlister** [comment]
Got a weird issue where the cursor enum is only returning 0 :/

```go
func (u *UserInterface) setNativeCursor(shape driver.CursorShape) {
	print(driver.CursorShapeDefault)
	C.setNativeCursor(C.int(driver.CursorShapeDefault))
}
```
```
tom.lister@FVFXMDTTJ1WK cursor % go run main.go
00000000000000000^Csignal: interrupt
```

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/bea5ab3335e45e5f99bb8826ce656d8fb33bcef6
