### ISSUE TITLE
ebiten: Enable to handle the timing when the window is closed

### ISSUE THREAD

**Issue by DataDrake** [hajimehoshi/ebiten#1574]
I would like to be able to catch the Window Closing so that I can prompt the user to save before closing and/or to confirm that they would like to exit. Right now I can't do that because the necessary functions are not exposed in the `internal/glfw` API. I can submit a PR for this if you'd like, but wasn't sure if this had been asked already or if it was already planned / implemented somewhere else. Cheers

**Comment by hajimehoshi** [comment]
Hi,

Prompting a closing window makes sense. Let me think about the API design. I'd like to avoid callback style API for consistency

**Comment by DataDrake** [comment]
Thank you! Looking forward to it.

**Comment by tomlister** [comment]
Perhaps a function in the game loop could return true or false, i.e `ebiten.IsWindowClosing()` and then the game can open a prompt if desired.

**Comment by tomlister** [comment]
```go
func (g *Game) Update() error {
    if (ebiten.IsWindowClosing()) {
        g.ShowExitPrompt = true
    }
    return nil
}
func (g *Game) Draw(screen *ebiten.Image) {
    if (g.ShowExitPrompt) {
        //draw prompt here.
    }
}
```

**Comment by hajimehoshi** [comment]
Not bad. If we do so, we have to modify the implementation so that Update and Draw are called once after the window is being closed.

**Comment by tomlister** [comment]
But what if the developer wants to draw their own interactive (ingame) prompt?

**Comment by hajimehoshi** [comment]
Ah good point. This sounds like an `unload` event on websites. So probably

```
// reports whether the user tries to close the window. This becomes true only at one frame.
func IsWindowBeingClosed() bool

// If this is true, the window is not closed even when the user tries to do. Instead, `IsWindowBeingClosed` returns true.
// The default state is false (i.e., the window is closed immediately).
func SetWindowClosingHandled(handled bool)

func IsWindowClosingHandled() bool
```

might work. Perhaps callback style might be better.

**Comment by tomlister** [comment]
Instead of those last two, couldn't the program just call a close function when the prompt is finished?

**Comment by hajimehoshi** [comment]
For backward compatibility, the window should be closed immediately when the user closes as the default behavior.

**Comment by DataDrake** [comment]
Judging by the [docs for window closing](https://www.glfw.org/docs/3.3/window_guide.html#window_close) and how UI interacts with a window, I think the following approach would work, with the least amount of change and disruption to non-GLFW APIs:

1. `ebiten/internal/glfw.SetWindowClosingHandled(true)` can be called before `ebiten.RunGame()` to indicate that the program wants to control window closing.
2. After it is called, any new window that is created by `internal/uidriver/glfw` will set a flag to indicate that closing is handled.
3. `ebiten/internal/glfw.Window.ShouldClose()` remains unchanged.
4. A new function `Window.CloseRequested()` is created which returns false if closing is handled or `Window.ShouldClose()` if it is not.
5. `Window.ShouldClose()` is replaced with `Window.CloseRequested()` in ` internal/uidriver/glfw/ui.go` to allow masking of close events
6. `ebiten/internal/glfw.IsWindowBeingClosed()` is called from `Game.Update()` and returns true if `Window.ShouldClose()` is true.
7. `ebiten/internal/glfw.RequestClose()` is called from `Game.Update()` and clears the flag, allowing `Window.CloseRequested()` to return true from `Window.ShouldClose()`.
8. ` internal/uidriver/glfw/ui.go` sees `Window.CloseRequested()` as true and knows to shut down.

This approach avoids changes to the other `uidrivers`, but provides a pattern that could be followed for other drivers if that is something you think make sense moving forward.

**Comment by hajimehoshi** [comment]
Yeah, I think your suggestion (modifying `uideriver`.Window) should work. However, I realized that this feature should be generalized for other platforms, where there is no 'window'. On browsers, `beforeunload` event handler might work. If we want the same feature for browsers, we should avoid the term 'window'. So then, the new API will be like this

```
// reports whether the user tries to close the window. This becomes true only at one frame.
func IsScreenBeingClosed() bool

// If this is true, the screen is not closed even when the user tries to do. Instead, `IsScreenBeingClosed` returns true.
// The default state is false (i.e., the screen is closed immediately).
func SetScreenClosingHandled(handled bool)

func IsScreenClosingHandled() bool
```

I don't think 'screen' is the best choice here (probably 'game' might be better?) Or, perhaps we could stick with 'window' and ignore the browsers. I have not decided yet.

On mobiles, there is no way to handle the timing when the application is destroyed.

**Comment by DataDrake** [comment]
Sounds good. I just didn't want to ask you to try to generalize this to the other platforms, since I know it may be difficult to generalize the behavior.

**Comment by hajimehoshi** [comment]
On second thought, handling this on browsers might be too aggressive: Ebiten games are often in an iframe and they should not control the window closing.

So I'll go with the term `window`. I'm implementing this soon:

```
// reports whether the user tries to close the window. This becomes true only at one frame.
func IsWindowBeingClosed() bool

// If this is true, the window is not closed even when the user tries to do. Instead, `IsWindowBeingClosed` returns true.
// To close the window by ending the game, let Update return an error.
// The default state is false (i.e., the window is closed immediately).
func SetWindowClosingHandled(handled bool)

func IsWindowClosingHandled() bool
```
