### ISSUE TITLE
FPS and the number of Draw calls per second don't match when vsync is off

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#1595]
It seems ebiten doesn't always call `Draw` once a tick.
From my understanding, if ebiten tells I'm at 3k+ fps instead of 240 when vsync is enabled (always smooth this way btw), `Draw` should be called at called at least the same amount.

Following `main.go` produces below output for me:
```go
package main

import (
	"fmt"

	"github.com/hajimehoshi/ebiten/v2"
)

// App *
type App struct {
	ticks int64
}

// Update *
func (g *App) Update() error {
	fmt.Println("upd8 ticks:", g.ticks)
	g.ticks++
	return nil
}

// Draw *
func (g *App) Draw(screen *ebiten.Image) {
	fmt.Println("draw ticks:", g.ticks)
}

// Layout *
func (g *App) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 1920, 1080
}

func main() {
	ebiten.SetVsyncEnabled(false)
	ebiten.SetWindowSize(display.WindowWidth, display.WindowHeight)
	ebiten.SetWindowResizable(true)
	ebiten.SetWindowTitle("Test")
	ebiten.SetFullscreen(false) // TODO: reset to full screen
	ebiten.SetScreenClearedEveryFrame(true)
	ebiten.SetMaxTPS(120)

	app := &App{}
	if err := ebiten.RunGame(app); err != nil {
		fmt.Println("Error at RunGame:", err)
	}
}
```

Output (only picked first 50 ticks):
```
upd8 ticks: 0
upd8 ticks: 1
draw ticks: 2
upd8 ticks: 2
draw ticks: 3
upd8 ticks: 3
upd8 ticks: 4
draw ticks: 5
upd8 ticks: 5
upd8 ticks: 6
draw ticks: 7
upd8 ticks: 7
upd8 ticks: 8
upd8 ticks: 9
upd8 ticks: 10
upd8 ticks: 11
upd8 ticks: 12
draw ticks: 13
upd8 ticks: 13
upd8 ticks: 14
draw ticks: 15
upd8 ticks: 15
upd8 ticks: 16
draw ticks: 17
upd8 ticks: 17
upd8 ticks: 18
draw ticks: 19
upd8 ticks: 19
upd8 ticks: 20
draw ticks: 21
upd8 ticks: 21
upd8 ticks: 22
draw ticks: 23
upd8 ticks: 23
upd8 ticks: 24
draw ticks: 25
upd8 ticks: 25
upd8 ticks: 26
draw ticks: 27
upd8 ticks: 27
upd8 ticks: 28
draw ticks: 29
upd8 ticks: 29
upd8 ticks: 30
draw ticks: 31
upd8 ticks: 31
upd8 ticks: 32
draw ticks: 33
upd8 ticks: 33
upd8 ticks: 34
draw ticks: 35
upd8 ticks: 35
upd8 ticks: 36
draw ticks: 37
upd8 ticks: 37
upd8 ticks: 38
draw ticks: 39
upd8 ticks: 39
upd8 ticks: 40
draw ticks: 41
upd8 ticks: 41
upd8 ticks: 42
upd8 ticks: 43
upd8 ticks: 44
draw ticks: 45
upd8 ticks: 45
upd8 ticks: 46
draw ticks: 47
upd8 ticks: 47
upd8 ticks: 48
draw ticks: 49
upd8 ticks: 49
upd8 ticks: 50
```

Output when vsync is enabled (still first 50 ticks, but many more lines):
```
upd8 ticks: 0
upd8 ticks: 1
draw ticks: 2
upd8 ticks: 2
upd8 ticks: 3
draw ticks: 4
upd8 ticks: 4
draw ticks: 5
draw ticks: 5
upd8 ticks: 5
upd8 ticks: 6
draw ticks: 7
draw ticks: 7
draw ticks: 7
draw ticks: 7
upd8 ticks: 7
upd8 ticks: 8
draw ticks: 9
draw ticks: 9
upd8 ticks: 9
upd8 ticks: 10
draw ticks: 11
draw ticks: 11
draw ticks: 11
upd8 ticks: 11
upd8 ticks: 12
draw ticks: 13
draw ticks: 13
draw ticks: 13
upd8 ticks: 13
upd8 ticks: 14
draw ticks: 15
draw ticks: 15
draw ticks: 15
upd8 ticks: 15
upd8 ticks: 16
draw ticks: 17
draw ticks: 17
draw ticks: 17
draw ticks: 17
upd8 ticks: 17
upd8 ticks: 18
draw ticks: 19
draw ticks: 19
draw ticks: 19
upd8 ticks: 19
upd8 ticks: 20
draw ticks: 21
draw ticks: 21
draw ticks: 21
upd8 ticks: 21
upd8 ticks: 22
draw ticks: 23
draw ticks: 23
draw ticks: 23
upd8 ticks: 23
upd8 ticks: 24
draw ticks: 25
draw ticks: 25
draw ticks: 25
upd8 ticks: 25
upd8 ticks: 26
draw ticks: 27
draw ticks: 27
draw ticks: 27
upd8 ticks: 27
upd8 ticks: 28
draw ticks: 29
draw ticks: 29
draw ticks: 29
upd8 ticks: 29
upd8 ticks: 30
draw ticks: 31
draw ticks: 31
draw ticks: 31
upd8 ticks: 31
upd8 ticks: 32
draw ticks: 33
draw ticks: 33
draw ticks: 33
upd8 ticks: 33
upd8 ticks: 34
draw ticks: 35
draw ticks: 35
draw ticks: 35
upd8 ticks: 35
upd8 ticks: 36
draw ticks: 37
draw ticks: 37
draw ticks: 37
draw ticks: 37
upd8 ticks: 37
upd8 ticks: 38
draw ticks: 39
draw ticks: 39
draw ticks: 39
draw ticks: 39
upd8 ticks: 39
upd8 ticks: 40
draw ticks: 41
draw ticks: 41
draw ticks: 41
draw ticks: 41
upd8 ticks: 41
upd8 ticks: 42
draw ticks: 43
draw ticks: 43
draw ticks: 43
draw ticks: 43
upd8 ticks: 43
upd8 ticks: 44
draw ticks: 45
draw ticks: 45
draw ticks: 45
draw ticks: 45
upd8 ticks: 45
upd8 ticks: 46
draw ticks: 47
draw ticks: 47
draw ticks: 47
draw ticks: 47
upd8 ticks: 47
upd8 ticks: 48
draw ticks: 49
draw ticks: 49
draw ticks: 49
draw ticks: 49
upd8 ticks: 49
upd8 ticks: 50
```

I read from this comment https://github.com/hajimehoshi/ebiten/blob/v2.1.0-alpha.17/uicontext.go#L193-L202 that performance should matter in this case, so it might be appropriate (also read the related issue), but I'm not sure I get the logic behind this or if it's just my code failing 😅 

edit: Feel free to flag this as a question because I can't say it's a bug since I'm fairly new to gamedev

**Comment by hajimehoshi** [comment]
Ah yes, when vsync is disabled, there is no guarantee how often Draw is called (See #1520).

> From my understanding, if ebiten tells I'm at 3k+ fps instead of 240 when vsync is enabled (always smooth this way btw), Draw should be called at called at least the same amount.

Good point. Actually Ebiten is in a chaotic situation about FPS and Draw. Let me think about think. I might add a document, or add a new API to make the behavior more explicit and clearer.

**Comment by hajimehoshi** [comment]
In the current Ebiten implementation:

1. When vsync is enabled, the number of Draw calls per second = FPS
2. When vsync is disabled, the number of Draw calls per second != FPS. Draw is called only when Update is called.

The second behavior is performant but not intuitive. The most serious problem is that the value of FPS becomes meaningless when vsync is disabled. As #1520 is the change for v2.1 and we have not released v2.1 yet, we can reconsider this change fortunately :-)

So probably
1. Revert the change for #1520
2. Introduce a new API like `SkipDrawWhenVsyncIsDisabled`
?

**Comment by Zyko0** [comment]
> The most serious problem is that the value of FPS becomes meaningless when vsync is disabled.

Yes, I do agree with this, I believe it's important for FPS to match the number of calls to `game.Draw()`

> 1. When vsync is enabled, the number of Draw calls per second = FPS

This seems very true, but it also looks like some `Draw` calls are being made multiple times for a single `Update` logic tick, while 0 time for another logic tick.
From my logs, the game data (here `g.ticks`) is not always shared from an `Update` to a `Draw`.
Should it be ? (if my game data is a character's position that is intended to be smoothly translating)

> 2. When vsync is disabled, the number of Draw calls per second != FPS. Draw is called only when Update is called.

Okay `!= FPS` but also likely `<= FPS` in a 120tps 240hz setup, right ?

> 1. Revert the change for #1520
> 2. Introduce a new API like SkipDrawWheneverPossible

Imo the thing is:
* I believe we still want `Draw` to be called even when there has not been any update in order to be able to smoothly interpolate sprite positions for example (or animations, etc..) which stays independent from the game state, and does not edit it
* But at the same time, if FPS are unleashed, it's still important to have at least one being done in-between `Update` calls

What do you have in mind with your point 2 ? 😅

**Comment by hajimehoshi** [comment]
> This seems very true, but it also looks like some Draw calls are being made multiple times for a single Update logic tick, while 0 time for another logic tick.

Yes, the logic ticks and the frames don't have to be the same. The number of Update calls per second is TPS (tick per second) while the number of Draw calls per second is FPS (frame per second). TPS is determined purely by Ebiten's logic, while FPS is determined by the display's refresh rate.

> From my logs, the game data (here g.ticks) is not always shared from an Update to a Draw.
> Should it be ? (if my game data is a character's position that is intended to be smoothly translating)

I don't t think it shouldn't be, as Update and Draw are called in a different timings. Especially, Draw depends on environments.

> Okay != FPS but also likely <= FPS in a 120tps 240hz setup, right ?

Mostly likely, yes. Good point.

> I believe we still want Draw to be called even when there has not been any update in order to be able to smoothly interpolate sprite positions for example (or animations, etc..) which stays independent from the game state, and does not edit it

Yeah, that make sense. So even though the game's logical state is not changed, Draw should be called.

> But at the same time, if FPS are unleashed, it's still important to have at least one being done in-between Update calls

Yes. If vsync is off,

1. A frame comes regardless of the display's refresh rate
2. A frame might call Update one or more times, and might not call. Update timings are determined by the tick, not by the frame.
3. A frame should call `Draw` once, but now a 'frame' might skip `Draw`

So I think we have already reached the agreement: call `Draw` once for a frame. Don't skip it.

> What do you have in mind with your point 2 ? 😅

My suggestion 2. is an opt-out API. If an Ebiten user want Ebiten to skip Draw when Update is not called, the user can call it. By default, Draw should be called for any frame. I think this API doesn't have to be in 2.1. I'll create another issue for this.

**Comment by hajimehoshi** [comment]
As the discussion at https://github.com/hajimehoshi/ebiten/discussions/1486, we reached the same agreement. Ugh, I'm sorry for going back and forth...
