### ISSUE TITLE
Linux: Ebiten window is always tiny size in latest master

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#1602]
For example, this screenshot is running the "airship" example:

![image](https://user-images.githubusercontent.com/61067263/115287661-61a45480-a105-11eb-9c8c-60b7e9881a36.png)

**Comment by hajimehoshi** [comment]
If this doesn't happen on 2.0 branch, this is a regression. Would it be possible to git-bisect and detect the culprit commit?

**Comment by corfe83** [comment]
1. This is v2, commit hash (latest as of right now): 08c302556053c60d20eb98dd13b1034ac749ed8c
2. 
![image](https://user-images.githubusercontent.com/61067263/115288789-b2687d00-a106-11eb-9b8d-62d73f8ce214.png)

I will see if I can find it with git-bisect soon!

**Comment by corfe83** [comment]
It seems multiple commits are involved. This commit begins the problem -- once I sync to this commit, the window starts normal size, but slowly changes size (shrinks) as the program runs:

https://github.com/hajimehoshi/ebiten/commit/585f173d1ccae8bc1e1bbeaf2a71602233ac66e2

And this commit makes it worse, now it just starts and stays like the screenshot I pasted above in the bug filing:

https://github.com/hajimehoshi/ebiten/commit/b5d4c834b8b1116468cc1722ba0f413401d4dddf

**Comment by hajimehoshi** [comment]
Thanks! So this is definitely a regression. I'll take a look tomorrow!

**Comment by hajimehoshi** [comment]
I think this was fixed (18ce150495b5e91b6e10161c9ec88d8e1910ce7f and after). Please take a look.

**Comment by corfe83** [comment]
Works fine now, thanks for the fast response!
