### ISSUE TITLE
Fullscreen by `requestFullscreen` on browsers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1611]
Now `SetFullscreen` doesn't work on browsers. I'm thinking if an Ebiten application in Wasm in an iframe could be fullscreen by `SetFullscreen(true)` by using Web API `requestFullscreen`.

**Comment by shoebsd31** [comment]
> _No description provided._

Hi could you please add some description ?

**Comment by hajimehoshi** [comment]
> Hi could you please add some description ?

Updated :)

**Comment by tomlister** [comment]
Hi,

As requestFullscreen works on any element, simply calling requestFullscreen on the canvas element will trigger the browser to make ebiten fullscreen.
Caveats:
According to MDN
> Note: This method must be called while responding to a user interaction or a device orientation change; otherwise it will fail.
As a result of this during testing I noticed that sometimes I'd have to double tap "F" to trigger a successful fullscreen. Any quick input previous to the triggering key works too, i.e clicking or pressing WASD, and then pressing "F" to trigger fullscreen.
```go
func (u *UserInterface) SetFullscreen(fullscreen bool) {
	canvas.Call("requestFullscreen")
	return
}
```

**Comment by tomlister** [comment]
Updating IsFullscreen and any documentation is also necessary.

**Comment by hajimehoshi** [comment]
Yeah, good point! A user gesture is required like Pointer Lock API (https://github.com/hajimehoshi/ebiten/issues/1604#issuecomment-822946880).

So, we have to handle [`fullscreenerror`](https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenerror_event) and show an error message on the console like what Ebiten has already done for Pointer Lock API.

> Updating IsFullscreen and any documentation is also necessary.

Yes!

**Comment by tomlister** [comment]
SetFullscreen
- Should check if the canvas is initialised
- Enter fullscreen when fullscreen argument is true
- Exit fullscreen when fullscreen argument is false
```go
func (u *UserInterface) SetFullscreen(fullscreen bool) {
	if !canvas.Truthy() {
		return
	}
	if fullscreen {
		canvas.Call("requestFullscreen")
		return
	}
	canvas.Call("exitFullscreen")
	return
}
```

**Comment by hajimehoshi** [comment]
Yes, the direction seems correct :-)

**Comment by tomlister** [comment]
We can also check if the current ebiten canvas is fullscreen or not, but for now it just checks if there is any element in fullscreen.
```
func (u *UserInterface) IsFullscreen() bool {
	if document.Get("fullscreenElement").isNull() {
		return false
	}
	return true
}
```

**Comment by hajimehoshi** [comment]
I think this works. `document` might be null in a very special environment. So let's add

```go
if !document.Truthy() {
    return false
}
```

**Comment by tomlister** [comment]
> I think this works. `document` might be null in a very special environment. So let's add
> 
> ```go
> if !document.Truthy() {
>     return false
> }
> ```

PR addresses this 👍
