### ISSUE TITLE
ebiten/internal/glfw.(*Monitor).GetPos(...) panic on linux at monitor power off or disconnect.

### ISSUE THREAD

**Issue by waltrapa** [hajimehoshi/ebiten#1627]
Platform: Xubuntu 20.04 x86_64
OpenGL renderer string: AMD RAVEN (DRM 3.35.0, 5.4.0-72-generic, LLVM 11.0.0)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 20.2.6

ISSUE: After power off or disconnect hdmi monitor produces this panic:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x596bf2]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/internal/glfw.(*Monitor).GetPos(...)
	.../go/src/github.com/hajimehoshi/ebiten/internal/glfw/glfw_notwindows.go:79
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).deviceScaleFactor(0x773560, 0xc070a00000000000)
	.../go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:679 +0x32
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*Input).update(0x773680, 0xc000092010, 0x65ad90, 0x7aa640)
	.../go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/input.go:307 +0x30e
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).update(0x773560, 0xc000018240, 0xc00010bdc0, 0xc00010bdc0, 0x41432b, 0xc0000181e0)
	.../go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:914 +0xe5
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).loop.func2(0xc0000181e0, 0xc00010bdf8)
	.../go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/ui.go:955 +0x45
github.com/hajimehoshi/ebiten/internal/thread.(*OSThread).Loop(0xc000012590)
	.../go/src/github.com/hajimehoshi/ebiten/internal/thread/thread.go:51 +0x99
github.com/hajimehoshi/ebiten/internal/uidriver/glfw.(*UserInterface).Run(0x773560, 0x65ad90, 0x7aa640, 0x9, 0x59695c)
	.../go/src/github.com/hajimehoshi/ebiten/internal/uidriver/glfw/run_notsinglethread.go:58 +0x1ab
github.com/hajimehoshi/ebiten.RunGame(0x65a9b8, 0xc00015c000, 0x0, 0x0)
	.../go/src/github.com/hajimehoshi/ebiten/run.go:172 +0xe6

**Comment by hajimehoshi** [comment]
Does this error still happen?

**Comment by waltrapa** [comment]
> Does this error still happen?

In version 2.1.6 this issue continues to happen.

**Comment by hajimehoshi** [comment]
Thanks. What about the latest version `c279d0c1cf69b2c133088beb694a6084b98cf047` ?

**Comment by waltrapa** [comment]
> Thanks. What about the latest version `c279d0c1cf69b2c133088beb694a6084b98cf047` ?

Unfortunately I don't know a specific pull in go.mod.
In tag v2.2.0-alpha.15 this issue continues to happen.  I think that label matches what you ask of me.

https://www.glfw.org/docs/3.3/monitor_guide.html#monitor_event
https://www.glfw.org/docs/3.3/group__monitor.html#ga102f54e7acc9149edbcf0997152df8c9

I think when all monitors are turned off or unplugged the glfwGetMonitorPos function returns nulls.

**Comment by hajimehoshi** [comment]
OK thanks. This tag should be the same as alpha15. My guess is that the monitor became disabled and nil.

> Unfortunately I don't know a specific pull in go.mod.

`go get github.com/hajimehoshi/ebiten/v2@c279d0c1cf69b2c133088beb694a6084b98cf047` should work.

**Comment by hajimehoshi** [comment]
As #1878 is already fixed, this should already be fixed.

**Comment by waltrapa** [comment]
Fixed. If all monitors power off or disconnect not panic. :+1:
