### ISSUE TITLE
audio/internal/go2cpp: Confirm that pausing and resuming a player works

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1628]
It looks like the loop ends when the player pauses. Is this expected?

**Comment by tomlister** [comment]
I might buy a switch just to make games for it. What's the dev kit process like?

**Comment by hajimehoshi** [comment]
> I might buy a switch just to make games for it. What's the dev kit process like?

You have to get a permission from Nintendo to access documentations for Switch first.

**Comment by hajimehoshi** [comment]
Confirmed examples/audio worked perfectly.
