### ISSUE TITLE
audio/internal/readerdriver: Crash when an appended buffer size is exactly 0

### ISSUE THREAD

**Issue by oddstream** [hajimehoshi/ebiten#1635]
Panic in WASM (but not other builds) when playing/rewinding a mono .wav file

panic: JavaScript error: Failed to execute 'createBuffer' on 'BaseAudioContext': The number of frames provided (0) is less than or equal to the minimum bound (0).

github.com/hajimehoshi/ebiten/v2/audio/internal/readerdriver.(*playerImpl).appendBuffer(0xc715e0, 0x7ff80001000000a5, 0x30e7270, 0x3665bc0, 0x1, 0x1, 0x7ff8000100000c89, 0x30e7278)

Looks similar to https://stackoverflow.com/questions/58829016/failed-to-execute-createbuffer-on-baseaudiocontext

**Comment by hajimehoshi** [comment]
Could you give me the audio file? Thanks!

**Comment by hajimehoshi** [comment]
And, which version of Ebiten are you using?

**Comment by hajimehoshi** [comment]
Aha, I found this bug can happen when the audio file size is multiples of 4096.

**Comment by oddstream** [comment]
There you go!

It seems to happen just when the audio files finishes ... very weird. May
just be a rogue file?

Very best wishes

And thank you for all your work!

**Comment by oddstream** [comment]
Lastest ebiten

**Comment by hajimehoshi** [comment]
Hm, apparently the attached file via an email is not available.

>  It seems to happen just when the audio files finishes ... very weird. May just be a rogue file?

Aha, this explains what is happening, and apparently my guess was correct. The fix itself should be easy.

> Lastest ebiten

v2.1.0? Thanks.

**Comment by hajimehoshi** [comment]
The minimum change to reproduce this issue:

```diff
diff --git a/examples/wav/main.go b/examples/wav/main.go
index af39cccd..8430e905 100644
--- a/examples/wav/main.go
+++ b/examples/wav/main.go
@@ -65,9 +65,10 @@ func init() {
        if err != nil {
                log.Fatal(err)
        }
+       _ = d
 
        // Create an audio.Player that has one stream.
-       g.audioPlayer, err = audio.NewPlayer(g.audioContext, d)
+       g.audioPlayer, err = audio.NewPlayer(g.audioContext, bytes.NewReader([]byte{}))
        if err != nil {
                log.Fatal(err)
        }
```

Unfortunately this is hard to write a unittest for browsers. Anyway I'll apply a fix asap.

**Comment by oddstream** [comment]
v2.1.0

It's the 'complete.wav' file at
https://github.com/oddstream/gosol/tree/main/sound/assets

**Comment by hajimehoshi** [comment]
Thanks. I think this has already been fixed. If you want to try the fix before the newer version is released, please use the patched commit:

```
go get github.com/hajimehoshi/ebiten/v2@97fa948e5e67831277bf128d224b7c6a0d0f4089 
```
