### ISSUE TITLE
Too small window at launching on ChromeOS (PixelBook Linux VM)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1651]
Reported at the Discord by user1919#2039

![image](https://user-images.githubusercontent.com/16950/119935899-36920800-bfc3-11eb-895c-dc6f22326560.png)

**Comment by superloach** [comment]
For a bit of further explanation - Chrome OS uses a container inside a virtual machine to allow running Linux applications, and X apps are forwarded to the Wayland server using something called sommelier. GPU passthrough is possible, on some models, but I'm not sure if it's being used here.

The real issue for now is figuring out why the window is tiny. I've had weird issues with resize policy in Linux apps on Chrome OS before, so it could be out of our control.

**Comment by hajimehoshi** [comment]
>  it could be out of our control.

Hmm, I don't think all the applications have the same issue, and I think there is a workaround. I'd need some hack in GLFW for example.

**Comment by hajimehoshi** [comment]
This might be already fixed at the latest commit `f8097eb45d93c0df91f3fee57db3819711febc75`. Could anyone take a look?
