### ISSUE TITLE
ebiten: Performance regression due to ColorM cache

### ISSUE THREAD

**Issue by jstaf** [hajimehoshi/ebiten#1655]
I tried upgrading to 2.1.1 today and there is a massive performance regression caused by https://github.com/hajimehoshi/ebiten/issues/1474 - my game goes from a steady 60fps down to 25fps. (I'm doing a lot of ColorM scaling each frame to draw primitive shapes like lines, circles, etc.)

Can the changes to ColorM caching be reverted? I have pinpointed the performance regression to this commit: https://github.com/hajimehoshi/ebiten/commit/a6dd6196b460dfd1e576588fa9c6080deaa2a223 (using `go get github.com/hajimehoshi/ebiten/v2@14abc28d3ab97ee7d8976f11019fe5a38b150ea0` works great, `go get github.com/hajimehoshi/ebiten/v2@a6dd6196b460dfd1e576588fa9c6080deaa2a223` results in the massive FPS drop described above). I can supply profiles if that helps.

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look.

**Comment by hajimehoshi** [comment]
I was wondering how many ColorM you created per frame on average. I guess this can be an issue only when you create extremely many ColorMs per frame...

**Comment by jstaf** [comment]
I don't have an exact count, but its somewhere in the range of 10-20k ColorM per frame. 

The reason I'm doing this is that I need a fast way of drawing lines/shapes (https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2@v2.1.1/vector is too slow and doesn't allow drawing color gradients or plain-old lines). I am basically doing a modified version of this to draw large numbers of lines/shapes quickly: https://github.com/hajimehoshi/ebiten/blob/d05bd7a58c324e5162406328f9a28595a4a1aa15/ebitenutil/shapes.go#L45

It would be *extremely* helpful to have a fast way of drawing lines and triangles that did not rely on DrawTriangles or DrawImage. I don't know too much about OpenGL, but I'm assuming there's a faster way of directly drawing these without using a 1px white image to draw from. I would be comfortable keeping the changes to ColorM if there was a better/faster way of drawing lines and triangles that didn't rely on ColorM to set a color (or use DrawTriangles/DrawImage at all).

**Comment by hajimehoshi** [comment]
OK I reverted the problematic commit (and its related commit). I'll consider another way to reduce the memory allocation.

> It would be extremely helpful to have a fast way of drawing lines and triangles that did not rely on DrawTriangles or DrawImage. I don't know too much about OpenGL, but I'm assuming there's a faster way of directly drawing these without using a 1px white image to draw from.

Yes but this means that we have to make Ebiten implementation a little complicated: now we can assume all the rendered things are triangles. Then, this is not feasible so far. I didn't image you rendered so many lines.

Another suggestion is to use `DrawTriangles` which can specify colors directly without ColorM. If you are satisfied with this way, I might re-revert the changes, but I'm not sure.

**Comment by jstaf** [comment]
I took your suggestion and implemented line drawing via `DrawTriangles` and that seems to solve my original issue. I'll submit a PR to update `DrawLine` so other people can benefit from the faster line drawing as well. You can re-revert the changes :slightly_smiling_face:

**Comment by hajimehoshi** [comment]
Sure, I'll re-revert the change.
