### ISSUE TITLE
audio: Update the document about PulseAudio for Linux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1663]

**Comment by nanoslayer** [comment]
Is there a specific reason why Ebiten now requires PulseAudio instead of ALSA? Or is it just an implementation detail? I'm asking because some Linux users might not have PulseAudio installed.

**Comment by hajimehoshi** [comment]
It's because ALSA couldn't mix multiple sources while PulseAudio could, which I wanted to do. An ALSA driver is correspondence with one hardware and it might be problematic when multiple application wants to play audio at the same time if I use ALSA directly. (The situation is more complex: ALSA can emulate an audio device only for one application and mix sources from multiple applications with underlying PulseAudio. In this case, PulseAudio seems 'lower' layer than ALSA.)

My understanding is PulseAudio is as common as ALSA. In general, PulseAudio seems a better choice for common applications as ALSA could be too primitive. What do you think?

(However, In the current implementation, mixing is done by myself (again). I was getting back and forth about the implementation, so I might change this in the future.)

**Comment by nanoslayer** [comment]
> My understanding is PulseAudio is as common as ALSA. In general, PulseAudio seems a better choice for common applications as ALSA could be too primitive. What do you think?

While PulseAudio is very common, there is still a small amount of Linux users that don't use it.

It might be worth supporting ALSA as a fallback if PulseAudio is not available. This might be relevant: https://github.com/godotengine/godot/issues/20978

**Comment by hajimehoshi** [comment]
Acknowledged. Let me think more. It should be easy to switch the implementation back to ALSA for the current implementation, which mixes sources by Ebiten, not an audio device.

**Comment by hajimehoshi** [comment]
Now ALSA was adopted again. Close this.
