### ISSUE TITLE
Incorrect kerning

### ISSUE THREAD

**Issue by polyscone** [hajimehoshi/ebiten#1671]
I've been playing around with Ebiten along with some of my own projects that also use the excellent `x/image/font/opentype` package, and I've noticed that the value returned by the `face.Kern` method is always a fixed amount, no matter the size of the font.

In other words, whether you set the font size as, say, `12pt` or `72pt`, the kern value returned never changes.

I believe that Ebiten is currently treating the value returned from `face.Kern` as a final number of pixels to adjust the `fx` position by here: https://github.com/hajimehoshi/ebiten/blob/main/text/text.go#L194

Unfortunately this means that the `fx` isn't adjusted enough when the font is large, and too much when the font is really small.
Because of this the kern value actually needs to be scaled up or down.

Since documentation on the method itself is a bit thin I've done some experiments myself and I've come to the conclusion that you can scale the kern value by a value derived using this formula:
```go
kernScale := fixed.Int26_6(facePtSize * (faceDPI / fontUnitsPerEm) * 64.0)
fx += face.Kern(prevR, r).Mul(kernScale)
```
I'm not sure if this is 100% accurate, but it's worked well in various font tests I've done myself so far, and seems to result in much more accurate kerning than is currently happening.
It's still off by a pixel or two still when I compare against word processors etc., but that could be because of floating point inaccuracies, font hinting, etc.

The reason for bringing the font's units per em into this is because they typically vary between `1000` and `2048`, so they're needed to get the correct scaling factor.
The `fontUnitsPerEm` value can be found using this method: https://pkg.go.dev/golang.org/x/image@v0.0.0-20210607152325-775e3b0c77b9/font/sfnt#Font.UnitsPerEm

Of course, fixing this would mean that you need to cache the units/em value for each font and the point size of each font to pass in to do the calculation, but I think it would be worth doing if it results in more accurate font rendering.

**Comment by hajimehoshi** [comment]
Thank you for reporting!

Hm, that seems pretty odd since the package `golang.org/x/image/font` itself uses `Kern` values without scaling:

https://cs.opensource.google/go/x/image/+/775e3b0c:font/font.go;l=228;drc=3f4726a040e860b3702c9dab9e3b94cad413328f

This might be an issue in `golang.org/x/image/font/opentype` rather than Ebiten. What do you think?

**Comment by polyscone** [comment]
> This might be an issue in golang.org/x/image/font/opentype rather than Ebiten. What do you think?

Actually, as soon as I posted this issue I thought the same thing!
The API in the `opentype` package certainly seems like it's supposed to return the actual number of pixels, especially since that's what the other methods do (`GlyphBounds` etc.)

I'll try to post an issue about this for `opentype` a bit later and reference this issue in there as well.
If it can be fixed in `opentype` that would be much nicer.

**Comment by hajimehoshi** [comment]
Yeah, thanks! Let me close this issue.
