### ISSUE TITLE
ebiten: Detect whether the thread is main or not at RunGame

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1673]
Related to #1670

1. Get the thread ID at init by a native API
2. Check the thread ID at RunGame is the same as the init's.

?

**Comment by Zyko0** [comment]
We can use `syscall.Gettid()`, right ? (I don't know if it's supported by all OS)
Also as Go runtime can spawn a goroutine in the same thread as the main one, the thread id would be the same, but it doesn't matter as long as it's the same thread ?

**Comment by hajimehoshi** [comment]
> We can use syscall.Gettid(), right ? (I don't know if it's supported by all OS)

This is not portable :-) but well, it is possible to get the thread ID by this.

> Also as Go runtime can spawn a goroutine in the same thread as the main one

No, if you use `LockOSThread`.

**Comment by hajimehoshi** [comment]
This issue is no longer valid after `RunOnMainThread` was removed...

#1945
