### ISSUE TITLE
Windows and WASM performance

### ISSUE THREAD

**Issue by benc-uk** [hajimehoshi/ebiten#1676]
I'm building a CHIP-8 emulator in Go using ebiten

I've spent quite a lot of time optimizing performance, esp for my rendering and how I output the display. My graphics are _incredibly_ basic, just a monochrome 64x32 image (1-bit so pixels are either on or off) which is then output scaled to the screen inside the Draw() function. I'm seeing a few things

I'm seeing a couple of things:
 - On Linux (WSL2) everything performs extremely well, so much so I have to slow the emulator processor loop down quite a lot to make programs playable
 - Windows is **significantly** slower, I have to set vsync disabled and ebiten.UncappedTPS set to make things playable even then it's not great. The difference here is not slight, it's probably several orders of magnitude, which I don't think is down to my code.
 - WASM is even slower still, I'm using 1000 x 500 output size which doesn't seem too outrageous, but nothing is really playable, everything just crawls 

My question is ebiten really only optimised for Linux? Should I continue trying to tune my code or is the slower performance on Windows and WASM a known problem?

**Comment by hajimehoshi** [comment]
> My question is ebiten really only optimised for Linux?

No, the program should work well on Windows as well. Could you shared the code? Thanks!
