### ISSUE TITLE
More graphics features for vector graphics (stencil buffers)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1684]
I'm reading [NanoVG](https://github.com/memononen/nanovg)'s implementation. To render a complex polygon (e.g., with holes), NanoVG uses stencil buffers, cull modes, and primitive types (e.g., triangle strips). Using these features seems much more efficient than rendering triangles by triangulation.

Before working on vector graphics (#844), what about introducing these features to Ebiten? Or, should we offer vector graphics API and hide these features?

**Comment by hajimehoshi** [comment]
A new primitive type should be optional. I'll add another issue for it.

**Comment by hajimehoshi** [comment]
The flow to render a complex polygon will be like this:

```
glEnable(GL_STENCIL_TEST)
glSetStencilFunc(GL_ALWAYS, 0x00, 0xff)
glColorMask(false, false, false, false)

// Unset uniform variables for textures here?
glStencilOp(GL_KEEP, GL_KEEP, GL_INVERT)

glDisable(GL_CULL_FACE)
glDrawElements
glEnable(GL_CULL_FACE)

glColorMask(true, true, true, true)
// Set uniform variables for textures here?

glSetStencilFunc(GL_NOTEQUAL, 0x00, 0xff)
glStencilOp(GL_ZERO, GL_ZERO, GL_ZERO)
glDrawElements

glDisable(GL_STENCIL_TEST)
```

**Comment by Jack-Ji** [comment]
Just bumped into a pure golang implementation of [nanovg](https://github.com/shibukawa/nanovgo) , a bit old, but should be useful.

**Comment by hajimehoshi** [comment]
Yeah I read it (I know the author). The essence is actually the same as https://gist.github.com/983/79c20c447457b1259ae1380ba591a42f.

**Comment by hajimehoshi** [comment]
I've succeeded to implement new vector implementation with stencil buffers on browsers!

https://github.com/hajimehoshi/ebiten/commit/9ee2a56fc7bff6ddf744cffc0099e94fdc17d362 (the implementation is only for browsers so far)


https://user-images.githubusercontent.com/16950/124313300-a770a500-dbab-11eb-8332-a5f035d6ac96.mp4



I'll port is to the other platforms one by one.
