### ISSUE TITLE
dfdx not in a entry-point function failed to be compiled with OpenGL

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1701]
```
package main

func foo(p vec4) vec4 {
        return vec4(abs(dfdx(p.r)), abs(dfdy(p.g)), 0, 1)
}

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
        p := imageSrc0At(texCoord)
        return foo(p)
}
```

This fails with this message:

```
vertex shader compile error: opengl: shader compile failed: ERROR: 0:33: Invalid call of undeclared identifier 'dFdx' 
```

This succeeded with Metal.

Reported by @Zyko0

**Comment by Zyko0** [comment]
The error mentions `vertex shader compile error`, tho dfdx, dfdy are known to be fragment shader restricted.
Is it possible this function is compiled to a vertex shader ?

Error seems to be coming from here : https://github.com/hajimehoshi/ebiten/blob/4c520581b89b05c1dd06baaa7c646f095f37980a/internal/graphicsdriver/opengl/shader.go#L57-L61

**Comment by hajimehoshi** [comment]
Ah, I think I got it! Then we have to eliminate this function from vertex shaders.

**Comment by Zyko0** [comment]
Now we're at it, I think it's the same for `fwidth`
