### ISSUE TITLE
Ebiten generally consumes more CPU power than Raylib-go

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1703]
I compared performances between Ebiten's Hello-World example (https://ebiten.org/tour/hello_world.html) and Raylib-go's example (https://github.com/gen2brain/raylib-go/blob/master/examples/core/basic_window/main.go) on MacBook Pro 2020. The former consumes about 20% CPU, while the latter less than 10% CPU. I'll investigate how we can improve the performance of Ebiten.

**Comment by hajimehoshi** [comment]
```
(pprof) top
Showing nodes accounting for 1.36s, 97.84% of 1.39s total
Showing top 10 nodes out of 129
      flat  flat%   sum%        cum   cum%
     0.49s 35.25% 35.25%      0.49s 35.25%  runtime.cgocall
     0.39s 28.06% 63.31%      0.39s 28.06%  <unknown>
     0.26s 18.71% 82.01%      0.26s 18.71%  runtime.pthread_cond_signal
     0.11s  7.91% 89.93%      0.11s  7.91%  runtime.pthread_cond_wait
     0.05s  3.60% 93.53%      0.05s  3.60%  runtime.nanotime1
     0.02s  1.44% 94.96%      0.02s  1.44%  github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/ca.MetalDrawable.Present.func1
     0.01s  0.72% 95.68%      0.01s  0.72%  github.com/go-gl/glfw/v3.3/glfw.(*Window).GetMonitor.func1
     0.01s  0.72% 96.40%      0.01s  0.72%  github.com/go-gl/glfw/v3.3/glfw._Cfunc_workaround_glfwGetCocoaWindow
     0.01s  0.72% 97.12%      0.01s  0.72%  github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*drawTrianglesCommand).CanMergeWithDrawTrianglesCommand
     0.01s  0.72% 97.84%      0.01s  0.72%  github.com/hajimehoshi/ebiten/v2/internal/restorable.ResolveStaleImages
```

So, the most expensive calls are GLFW calls? 🤔

**Comment by hajimehoshi** [comment]
My current guess:

* Ebiten's APIs are almost concurrent-safe, while Raylib-go doesn't mention about this. To make API concurrent-safe, I had to use some goroutines and context-switching seems to have some overhead. This can be removed by ebitensinglethread tag, but this is unsafe.
* Both Ebiten and Raylib-Go uses GLFW. Ebiten uses go-gl/glfw via Cgo while Rayilb-Go calls C functions and Raylib itself contains GLFW. This might make some overhead differences

**Comment by Jack-Ji** [comment]
The second one makes more sense in my opinion. BTW, have you tried windows os?

**Comment by hajimehoshi** [comment]
Yes but I've not measured the performance

**Comment by chunqian** [comment]
@hajimehoshi 
I made bunny-mark test In [Ebiten v2](https://github.com/hajimehoshi/ebiten), [raylib 3.5](https://github.com/raysan5/raylib/tree/3.5.0), [go-raylib](https://github.com/chunqian/go-raylib)(create myself) 
MacBook Pro (Retina, 15-inch, Mid 2015) 
Intel Iris Pro 1536 MB 
Screenshots 
raylib 3.5: 
<img width="800" alt="c-raylib" src="https://user-images.githubusercontent.com/13447930/168461756-640f2d2e-2945-4691-b031-4e071b6baf86.png"> 
go-raylib: 
<img width="800" alt="go-raylib" src="https://user-images.githubusercontent.com/13447930/168461769-1f199209-8eba-44c1-a3c6-0d19a63a1727.png"> 
ebiten: 
<img width="800" alt="ebiten" src="https://user-images.githubusercontent.com/13447930/168461779-19665135-65b5-4569-b5f5-6950c956fd19.png"> 
ebiten is 240% for raylib 3.5

**Comment by chunqian** [comment]
@hajimehoshi 
I don't think ebiten has any problems with performance 
You can change the title.

**Comment by hajimehoshi** [comment]
Thanks, but there is still a difference between CPU usages, right?

**Comment by hajimehoshi** [comment]
I updated the title to clarify the issue.

**Comment by chunqian** [comment]
@hajimehoshi 
bunny-mark test, 60fps limit, 1000 bunnies
cpu usages screenshots 
raylib 3.5: 
<img width="838" alt="c-raylib" src="https://user-images.githubusercontent.com/13447930/168472048-ad4bbb15-c276-4d3b-adb1-1a18ee8ab531.png"> 
go-raylib: 
<img width="846" alt="go-raylib" src="https://user-images.githubusercontent.com/13447930/168472053-d475ddad-f201-4004-9342-7a34331fa848.png"> 
ebiten: 
<img width="838" alt="ebiten" src="https://user-images.githubusercontent.com/13447930/168472059-90b97fff-31f5-4080-9e8b-dd21717ba130.png"> 
ebiten is 88% for raylib 3.5, 68% for go-raylib 
ebiten still the best performer

**Comment by chunqian** [comment]
@hajimehoshi 
[raylib-go](https://github.com/gen2brain/raylib-go) binding raylib, with default settings, can only run 57fps is problematic, so it is meaningless to compare with raylib-go, go-raylib and raylib I have adjusted to 60fps to compare

**Comment by hajimehoshi** [comment]
Interesting. I'll revisit this later. Thank you for the measuring!

**Comment by hajimehoshi** [comment]
Let me close this until we find an actual issue (again)
