### ISSUE TITLE
No CGO at least on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#171]
This would make it easier to install, I don't even know this is possible though.

**Comment by otraore** [comment]
I doubt this is possible but it would certainly help alot with installing on windows.

**Comment by hajimehoshi** [comment]
Thanks. IIUC, Bash on Windows enables to run ELF binaries on WIndows but I don't think this is appropriate for regular game users, who would not know how to execute Bash.

I think this is theoriticaly possible by using x/sys/windows' LoadDLL or other functions, but not sure.

**Comment by hajimehoshi** [comment]
Note: There is an Windows GUI example without cgo: https://gist.github.com/nathan-osman/18c2e227ad00a223b61c0b3c16d452c3

**Comment by otraore** [comment]
@hajimehoshi That's using win32

**Comment by hajimehoshi** [comment]
Yes. That's what I expected. Though GLFW would be very hard to replace, I could replace all cgo calls for Windows with that way in theory.

**Comment by otraore** [comment]
Removing cgo would be very difficult if not near-impossible. I personally think it's not worth the effort, all that's needed is a C compiler that go supports like mingw.

**Comment by hajimehoshi** [comment]
Well, I agree the cost would be too huge to compensate the benefit.

I'm fine with MinGW so far, but the less tools are required, the happier. I wish Go had a multi-platform C compiler...

**Comment by hajimehoshi** [comment]
It looks like that we can have .a binary files and use them without C lib: e.g. https://github.com/andlabs/ui

**Comment by hajimehoshi** [comment]
Oops, this still requires a linker...

**Comment by Splizard** [comment]
> I'm fine with MinGW so far, but the less tools are required, the happier. I wish Go had a multi-platform C compiler...

There is a new tool that does that, have a look at [xgo](https://github.com/karalabe/xgo).
I can confirm that Ebiten cross compiles to windows from Linux using xgo.
I can add a tutorial on the wiki if you like :)

**Comment by hajimehoshi** [comment]
Seems a great tool! Yes, I'd very happy if you could add info to the Wiki.

**Comment by hajimehoshi** [comment]
I understand the tool. This tool creates Docker environment installing GCC for platforms? Still great, but I expected the users could `go get` on Windows without C compiler. Hmm

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/wiki/Cross-Compiling 👍 👍 👍

**Comment by hajimehoshi** [comment]
I'm wondering if https://github.com/elliotchance/c2go is available for GLFW

**Comment by hajimehoshi** [comment]
As feasible steps, I think these are needed:

* Make gl bindings pure Go
* Make the window part of GLFW pure Go
* Make the input part of GLFW pure Go (Keyboard, mouse, gamepads)

**Comment by Noofbiz** [comment]
Have you seen oak? https://github.com/oakmound/oak ? It claims to use pure Go instead of GLFW/openGL. I haven't actually looked at it in detail, but it sounds really neat, and could give you insight in how you might implement it yourself.

**Comment by hajimehoshi** [comment]
Yeah, I know oak, thanks. However I'm not sure oak has the same capability as GLFW like gamepads, text inputs and so on. I'll check it out later anyway.

**Comment by hajimehoshi** [comment]
Ok, oak uses Shiny, that is not maintained actively unfortunately. Also, this doesn't have gamepads or text inputs...

**Comment by hajimehoshi** [comment]
Can we use 99c? https://github.com/cznic/99c

**Comment by hajimehoshi** [comment]
Note: I feel like C interpreter (instead of compiler) would be enough

**Comment by silbinarywolf** [comment]
I'm interested in cgo being not needed for the Ebiten library in general. For two reasons:
- It would make cross-compiling from Windows to Linux easier.
- Increase compile times drastically on Windows. (cgo compile times cause compilation to be 1-3 seconds rather than instant, not a huge problem but this would be a nice-to-have!)


I was able to circumvent the need for cgo by making my wrapper library around Ebiten have a "headless" tag though. This was done also because the box has no gl libraries installed, so it crashed when trying to open a GLFW window IIRC.

**Comment by hajimehoshi** [comment]
Yes, these reasons the main reasons why I'd like to eliminate necessity of cgo.

Headless Ebiten is one of the ideas. This is useful when testing your program, but is useless if you want to compile your game for Windows on Linux.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/tree/glfw-nocgo

I don't know when this is finished...

**Comment by hajimehoshi** [comment]
I've succeeded to embed a C DLL into Go program: https://github.com/hajimehoshi/embeddll

Hm, isn't this the way to go?

**Comment by Noofbiz** [comment]
Interesting idea! What about something like a webview? I know android has a webview, not so sure about ios though it has to for the phaser / cocoapod stuff to work. And for desktop there's something like https://github.com/zserge/lorca or even https://github.com/zserge/webview

**Comment by hajimehoshi** [comment]
Using webview is not my option for Windows just to avoid Cgo. We'd want to develop a native game with Ebiten for performance :-)

Lorca is interesting, but as this uses Chrome itself, even backforwarding is not forbidden.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/tree/glfw

I've created an experimental branch. It looks like go building is available without Cgo! I'll be testing this.

**Comment by hajimehoshi** [comment]
Merged to `master`!

**Comment by gonutz** [comment]
Hey, do you still have problems with the `float64`s? I have found in [my SDL2 DLL port](https://github.com/gonutz/go-sdl2) that you seem to be able to pass the `float64` bit pattern as two `uintptr` parameters. I have yet to try that on `float64` but it seems to work for `uint64` and `int64` for me. See [RWops.Seek](https://github.com/gonutz/go-sdl2/blob/800774610c6bd14470fb3a4fc0fd922639d21ac1/sdl/sdl_windows_386.go#L58) where I split `offset int64` into two `uint32` values. The same should be possible for `float64`.

I assume that these values are put on the call stack of the called function and if two `uint32`s are back to back they can be interpreted as one `uint64` just as well.

**Comment by hajimehoshi** [comment]
I found the problem when passing `float64` directly, so I used pointers for such case.

https://github.com/hajimehoshi/ebiten/blob/master/internal/glfw/glfw_windows.go#L198-L200
(I have fixed the original GLFW to solve this)

I have not tried `uint64` and `int64` and they would not work well with 32bit Windows.

**Comment by gonutz** [comment]
I see, that is a solution as well but if you want to pass 64 bit values to 32 bit DLLs my idea seems to be right. I have found [this issue](https://github.com/golang/go/issues/29092#issuecomment-444340448) which proposes the same thing - split your 64 bit values into two 32 bit values on 386.

I also just confirmed that it works for the `SDL2.dll` where the `angle` in `Renderer.CopyEx` is a `float64` and it works fine when split up into two `uint32`s for Windows 32. The only thing is that you cannot cast the `float64` to `uint64` directly, you need to use `math.Float64bits` which basically uses `unsafe.Pointer` to treat the `float64` as a `uint64`. See [my code](https://github.com/gonutz/go-sdl2/blob/845365f4c155c95d76508e98605ed1db9380414d/sdl/sdl_windows_386.go#L174) for an example.

This means that you can have the same API as the original GLFW which is probably a nice feature. You also do not have to maintain a slightly different GLFW version all the time.

**Comment by hajimehoshi** [comment]
Wouldn't splitting arguments mean we'd need to maintain two different types of calls for 32bit and 64bit Windows?

> This means that you can have the same API as the original GLFW which is probably a nice feature. You also do not have to maintain a slightly different GLFW version all the time.

Good point, but as this is not so much (just 1 or 2 lines), I don't think this is problematic so far.

**Comment by gonutz** [comment]
Yes, you need two versions for 32 and 64 bit systems. I use [this one for 386](https://github.com/gonutz/go-sdl2/blob/845365f4c155c95d76508e98605ed1db9380414d/sdl/sdl_windows_386.go#L174) and [this one for amd64](https://github.com/gonutz/go-sdl2/blob/845365f4c155c95d76508e98605ed1db9380414d/sdl/sdl_windows_amd64.go#L148). The 386 version splits the `float64` into two parameters.

I am going to write a little something about everything I learned about the `syscall` stuff in the last years. I found that these Windows syscall information are very rare to find. All that I know now was from studying others' code and extending it, from reading a section on it in different contexts of blog articles every now and then and of course - trying a lot of things myself and figuring it out by trial and error. I think it is time we get a comprehensive guide for people to use the Windows specific Go parts. A guide that I wish I had.
