### ISSUE TITLE
ebiten: a new API to limit internal texture atlas size OR a feature to warn when the texture atlas is extended

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1714]
I just suddenly hit a performance "wall" in my game - my atlas size jumped from 2048x2048 to 4096x4096, and it turns out on my Chromebook (Asus C101PA), updating part of a texture uploads the whole texture.

Ignoring the GPU issue, I found the atlas needlessly grew in size; there are massive unused areas in the current atlas (sorry, alpha channel removed and 4x downscaled so I can keep size down for this post):

![atlas2-byname](https://user-images.githubusercontent.com/251568/125616115-0859b793-ccb7-4c81-9f55-cda330a4600b.jpg)

Adding even a bit more small stuff actually jumped the atlas size to 4096x4096, even though there are massive amounts of free space in the top left and bottom right. After reading how the atlas building works (basically a greedy BSP approach), I suspect that there might be a bug when extending atlas size from 512 to 1024 and then to 2048: the extended area may not be fully utilized, so maybe the nodes bordering the to be expanded border aren't always properly upsized?

As a workaround I tried loading the images in decreasing size order (basically to minimize fragmentation during atlas building - a common optimization when faced with a greedy algorithm), and got this much better atlas:

![atlas2-largestfirst](https://user-images.githubusercontent.com/251568/125616399-5716f481-4d0c-4007-988e-9fff635e2a28.jpg)

Note that the bottom right quarter is entirely unused and there's basically no fragmentation of free space. So I guess I can live with this workaround, but I do wonder if there's a bug in the atlas building itself, thus filing this bug.

PS: I am aware there are a few duplicate images; I will fix those anyway, but found the likely atlas building bug sufficiently interesting to file :)

**Comment by hajimehoshi** [comment]
As texture packing is an online algorithm (i.e., we cannot expect what kind of image sizes in what order), then basically we cannot do such automatic optimization unfortunately.

> updating part of a texture uploads the whole texture.

2.2 should improve this part. Could you try the latest commit?

**Comment by hajimehoshi** [comment]
> Adding even a bit more small stuff actually jumped the atlas size to 4096x4096, even though there are massive amounts of free space in the top left and bottom right. After reading how the atlas building works (basically a greedy BSP approach), I suspect that there might be a bug when extending atlas size from 512 to 1024 and then to 2048: the extended area may not be fully utilized, so maybe the nodes bordering the to be expanded border aren't always properly upsized?

Yeah that's right. the borders don't change and still exist even when the atlas is extended.

**Comment by divVerent** [comment]
First of all, I am not thrilled about a minimum 256 MB atlas size now
(8192x8192 minimum), which could be a major issue especially on mobile
platforms; I would actually like to stick with 2048x2048 in my game if
possible, and 4096x4096 if not. Maybe it'd be a good idea if the
minimum atlas size could be set before initializing graphics?

But yes, performance on this small laptop did improve noticeably but
at the expense of an increased startup time by about 2 seconds (likely
because a 256MB texture actually puts some strain on it).

**Comment by hajimehoshi** [comment]
> First of all, I am not thrilled about a minimum 256 MB atlas size now (8192x8192 minimum),

The minimum size was 8192 once, but this should be already changed. Which commit did you try?

**Comment by hajimehoshi** [comment]
> I would actually like to stick with 2048x2048 in my game if
> possible, and 4096x4096 if not. Maybe it'd be a good idea if the
> minimum atlas size could be set before initializing graphics?

So, are you suggesting to add a limitation of maximum texture atlas size?

**Comment by divVerent** [comment]
Oh, sorry, my mistake; I got this from commit messages.

Using v2.2.0-alpha.9.0.20210714035519-b249fe889da5 now.

And yes, looks like that change indeed got reverted. The longer loading
time isn't a major issue - so thanks! Clearly I am on a chipset where PBO
didn't really help.

**Comment by divVerent** [comment]
It'd actually be great if both minimum and maximum could be set - I'd then
set the minimum to 2048 as I know my stuff won't fit on 1024 (thus saving
an extend step), and the maximum to 2048 during debugging so I learn if I
accidentally end up on 4096, while releases would keep the maximum "bounded
by the GPU only" to minimize crashes.

**Comment by hajimehoshi** [comment]
Thank you for testing! It looks like the serious performance issue is already solved. PBO is no longer used anywhere :-)

And thank you for suggesting the API! My concern to limit the maximum texture atlas is increase of draw calls. In your case, even if the maximum size is 2048, doesn't the number of draw calls matter?

**Comment by divVerent** [comment]
Oh, I had actually hoped to get a fatal error when exceeding the specified
maximum, for debugging purposes - not a second atlas.

But indeed, if the limit is due to the GPU maximum texture size, a second
atlas is more appropriate.

Well, even if not - setting the minimum would already be helpful and speed
up loading time.

**Comment by hajimehoshi** [comment]
Thanks, please give me time to think.

**Comment by hajimehoshi** [comment]
> It'd actually be great if both minimum and maximum could be set - I'd then
> set the minimum to 2048 as I know my stuff won't fit on 1024 (thus saving
> an extend step),

So setting the minimum size would make sense, but

> and the maximum to 2048 during debugging so I learn if I
> accidentally end up on 4096, while releases would keep the maximum "bounded
> by the GPU only" to minimize crashes.

Now extending a texture should not be so expensive, is there a strong reason to limit the maximum size?

**Comment by divVerent** [comment]
My only reason for asking to limit the size is so I know during game
development when I am exceeding it.

My game currently uses a 2048x2048 atlas and thus 16 MB VRAM - I simply
want to know during development when I accidentally cause it to bump to 64
MB VRAM.

Of course, an API to query the current atlas size and count would be just
as good - I would then build whatever I want in my own game code.

**Comment by hajimehoshi** [comment]
Yeah, it's possible to limit the maximum size, but in this case another texture atlas is just created and you might not notice this if Ebiten doesn't notify you. Probably I'll add an API to know the status of texture atlases when `ebitendebug` build tag is enabled. My concern is that the state of texture atlas is an internal thing and it is in general risky to do something based on the state.

**Comment by hajimehoshi** [comment]
The safest way would be to create your own atlas with 2048x2048 size, allocate regions on it by yourself by `ReplacePixels` and use them by `SubImage`. The issue is that you have to do it by yourself instead of Ebiten. Hmm

**Comment by divVerent** [comment]
I like this idea - could just include atlas info in one extra line of the
per frame ebitendebug spam.

**Comment by hajimehoshi** [comment]
Yes, but do you plan to parse it by yourself?

**Comment by divVerent** [comment]
I will just look at it manually - the output of the last frame will be good
enough as I almost no longer generate textures at runtime.
