### ISSUE TITLE
Use SDL2 instead of GLFW

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#172]
- SDL2 is more portable.
- Thanks to SDL_audio, it would be easy to implement audio part.
- SDL2 is licensed under the zlib license, which I think is non-problematic.

**Comment by otraore** [comment]
The only possible issue I see with this is web support would be hindered. While for languages like C, C++ you have Emscripten to handle this for you, it wouldn't work as well with go. Maybe I'm wrong.

**Comment by hajimehoshi** [comment]
Thank you for comments! I'd be able to use SDL2 for desktop or other devices backend, not for web browsers. As for web, I've already implemented and there is no reason replacing this with SDL (possibly with Emscripten).

**Comment by otraore** [comment]
You're right, I didn't think about that.

**Comment by hajimehoshi** [comment]
Note: When moving to Metal for Apple, SDL2 would be better (I'm not sure if GLFW supports Metal, but I think currently no)

**Comment by Noofbiz** [comment]
There's rudimentary Metal support in GLFW 3.2.1 but full support isn't until 3.3 which is still in active development and has been for almost 2 years now... no idea when it'll be stable. 

Another benefit for SDL2 is it compiles to Switch / Xbox / PS4 if you have the dev kits. That's very nice.

**Comment by hajimehoshi** [comment]
> There's rudimentary Metal support in GLFW 3.2.1 but full support isn't until 3.3 which is still in active development and has been for almost 2 years now... no idea when it'll be stable.

Note that I've succeeded to use Metal with the current GLFW 3.2 with 'no api' mode.

**Comment by hajimehoshi** [comment]
https://partner.steamgames.com/doc/store/application/platforms/linux SteamOS requires SDL?

**Comment by Noofbiz** [comment]
I don’t believe so, I think those are just recommendations. The only time I built something for steam it was, conveniently, using SDL so I’m not 100% sure, but all it needs to be able to do is run in the [Steam Runtime Environment](https://github.com/ValveSoftware/steam-runtime), which has gcc so *should* work with glfw just fine.

**Comment by hajimehoshi** [comment]
I see. I now think GLFW should work as long as X works. Thanks!

**Comment by hajimehoshi** [comment]
Probably I'll start to implement this under a build tag. After a while, I'll switch this by default. I have not decided to when to make this default.

**Comment by hajimehoshi** [comment]
Hmm, porting SDL in the same way as go-gl/glfw seems pretty difficult especially for X11. The configuration file (`SDL_config.h`) is generated for each environment, so just putting `*.c` and `*.h` files might not work. Hmm

**Comment by tomlister** [comment]
It'd be cool to just build our own utility library to replace glfw.
Obviously make it a seperate project though.

**Comment by hajimehoshi** [comment]
This means that we have to expose `internal/driver`. That'd be cool, but I'd not want to do as it is hard to keep the backward compatibility.

**Comment by tomlister** [comment]
Yeah fair enough, just thinking of ways to resolve other issues such as system tray on windows.

**Comment by hajimehoshi** [comment]
We'll do the gamepad part (#1489) for the next milestone.

**Comment by hajimehoshi** [comment]
Maybe I don't go in this direction. I'd like to port the current GLFW implementation into pure Go.
