### ISSUE TITLE
Add an API to provide one's own game controller mapping

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1723]
https://github.com/hajimehoshi/ebiten/commit/aa694be6f6b98106318bc5aac37d3a034a840cfa - first of all, this is awesome! Will allow me to delete a lot of code in my game.

However, for my own gamepad, I for quite a long time needed to provide my own mapping, which SDL supports by environment variable:

```
SDL_GAMECONTROLLERCONFIG=03000000d62000000228000001010000,PowerA Wired Controller for Xbox One,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux
```

Can the same mechanism be supported by ebiten? Not sure if it should be an EBITEN or a SDL variable, don't really care, but it may be nice to stick to this exact format.

Thanks!

**Comment by hajimehoshi** [comment]
Hi,

1. Wouldn't it be possible to add this line to the original [gamecontrllerdb.txt](https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt)? 
2. Does your gamepad have the standard layout on browsers?

**Comment by hajimehoshi** [comment]
Thank you for requesting a feature! Let me think this later.

**Comment by TheMightyGit** [comment]
That line is in the db on line 770 ...

https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L770

**Comment by divVerent** [comment]
Yes, I added my gamepad to the DB via pull request.

My point is, for users of another unsupported gamepad, this allows getting
the pad supported by the game without recompiling.

**Comment by divVerent** [comment]
As for browsers, it does work in there with standard layout. No idea how
Chrome does that.

**Comment by hajimehoshi** [comment]
Chrome has its own gamepad controller table.

OK I understand your point. Let me think an API (or an environment variable).

**Comment by TheMightyGit** [comment]
> Yes, I added my gamepad to the DB via pull request. My point is, for users of another unsupported gamepad, this allows getting the pad supported by the game without recompiling.

🤦 I read back and I realised I misinterpreted the point of what you said, sorry.

**Comment by hajimehoshi** [comment]
Maybe a function is better than an environ variable. (If you want to use an environment variable, you can call `os.Getenv` and call the new API by yourself.)

**Comment by hajimehoshi** [comment]
On second thought, if you want to play a game that is made by another person, an environment variable would work for your special gamepad but a function doesn't as the person unlikely calls the new function. Hmm

**Comment by divVerent** [comment]
An alternative would be having a way to provide a replacement or additional
gamecontrollerdb.txt file. Doesn't match what SDL does, but might actually
be more user friendly.

**Comment by SolarLune** [comment]
If you simply make it a function to add a custom mapping, that would leave it to the developer to tie it into an environment variable or text file. That seems like a good option.

**Comment by hajimehoshi** [comment]
> If you simply make it a function to add a custom mapping, that would leave it to the developer to tie it into an environment variable or text file. That seems like a good option.

The concern I wrote above is that if you want to play other people's ebiten game which doesn't call the function, the gamepad doesn't work.

**Comment by SolarLune** [comment]
Ah, I see. 

I don't think an environment variable would be that useful as developers probably wouldn't know you _could_ read gamepad layouts through an environment variable, and so they wouldn't suggest it to the end-user. But if it's well-documented, it could work. 

I think there should still be a function for adding custom gamepads mapping strings in Ebiten, though.

**Comment by hajimehoshi** [comment]
@divVerent would a function work in your case? Or, do you need an environment variable rather than a function?

I tend to think that a function is cleaner way. We can revisit about an environment variable anytime later.

**Comment by divVerent** [comment]
A function would work for me, but of course the way I'd use that is to
precisely copy SDL's mechanism (same variable name).

**Comment by divVerent** [comment]
FYI this is now my only blocker to removing legacy gamepad support and my
own controller parsing in my game - so would be really nice if this could
still go into 2.2 in some form (and be it just a function I can call to
provide a new mapping, ideally in form of the same string as SDL used so I
do not need to parse it; an alternative that would also work could be me
providing a replacement for the entire txt file; this actually would also
be useful so I can keep this file up to date automatically in daily builds
rather than waiting for ebiten to update).

I would also be fine if it is marked as experimental API and going to be
revamped later, as long as some way to add custom mappings to standard
layout at runtime remains. I will similarly document the variable or option
I create for this purpose as temporary and will recommend users to send PRs
to the game controller DB as a more permanent solution.

**Comment by hajimehoshi** [comment]
The implementation is just invoking [`glfw.UpdateGamepadMappings`](https://pkg.go.dev/github.com/go-gl/glfw/v3.3/glfw#UpdateGamepadMappings) which adds or replaces a mapping with SDL's format. As the implementation is pretty easy, I (or a contributor) will do this for 2.2.

**Comment by divVerent** [comment]
Filed https://github.com/hajimehoshi/ebiten/pull/1775 but didn't test it yet - any comments about doing the API this way though (including the part about not supporting this on web by returning an error)?

Will otherwise test it properly next week.

**Comment by hajimehoshi** [comment]
Thank you for implementing this!

BTW, I started to think that `[]byte` sounds better than `string` as an argument, though go-gl/glfw takes string. It's because you will be able to pass `[]byte` from `os.Getenv` or a file as it is. @divVerent  What do you think?

**Comment by divVerent** [comment]
As for []byte vs string:

- Indeed, GLFW uses string already, so even if we accepted []byte, we'd be
causing an extra copy.
- What speaks for string is that the data is all plain text, UTF-8 or ASCII
encoded, so semantically it's more like a string.
- What speaks for []byte is that indeed, file reading returns []byte by
default, and thus passing file contents is slightly easier when using
[]byte.
- What also speaks for []byte is that it emphasizes that Ebiten does not
process the data but just forwards it elsewhere. OTOH, this will not
actually be true for the mobile implementation, so IMHO this one is moot.
- os.Getenv actually returns string, though - so does os.LookupEnv.

I'd personally stick with string; but if you want to change it to []byte,
let's do this now and not later.

**Comment by hajimehoshi** [comment]
> - Indeed, GLFW uses string already, so even if we accepted []byte, we'd be
> causing an extra copy.

It depends on how Go optimizes this. Here, I care ease to use rather than copying costs.

> - os.Getenv actually returns string, though - so does os.LookupEnv.

Oh sorry I was misunderstanding.

> What also speaks for []byte is that it emphasizes that Ebiten does not
> process the data but just forwards it elsewhere.

You mean a string, which is immutable?

> but if you want to change it to []byte,
> let's do this now and not later.

Agreed.

**Comment by hajimehoshi** [comment]
> but if you want to change it to []byte,

So I suppose you are OK with both :)

OK let me think, I'll revisit this tomorrow.

**Comment by hajimehoshi** [comment]
Let's keep this a string. Probably setting it with `os.Getenv` or `flag.String` is common. Giving an entire file should be rare.

**Comment by divVerent** [comment]
ACK; indeed, flag.String could also be a source of this data, especially as
a line in this database tends to not use any characters one needs to escape
other than spaces (so just double quotes will be enough).

Actually a good idea to add this to my game too - not only are flags more
discoverable (-help), in my concrete case I also implemented persisting
previously set flag values in a JSON file (with a few exceptions). Thanks
for the idea!
