### ISSUE TITLE
text: Allow configuring line height in DrawWithOptions

### ISSUE THREAD

**Issue by nanoslayer** [hajimehoshi/ebiten#1760]
It would be nice if we could configure the line height when drawing text with `text.DrawWithOptions`.

This could probably happen by introducing a new struct, `text.DrawOptions`, with a `LineHeight` field (as well as the other fields in `ebiten.DrawImageOptions`). `text.DrawWithOptions` could then accept a `*text.DrawOptions` instead of an `*ebiten.DrawImageOptions`.

Eventually I think `text.DrawWithOptions` should be renamed to `text.Draw`, and the current `text.Draw` function should be deprecated and removed.

**Comment by hajimehoshi** [comment]
That sounds a good idea. Would it be fine to give a line-height scale like 1.5, or do you want to use an absolute value like 24px?

> Eventually I think text.DrawWithOptions should be renamed to text.Draw, and the current text.Draw function should be deprecated and removed.

Good idea. Such API change will happen in the next major version if it happens.

**Comment by nanoslayer** [comment]
> That sounds a good idea. Would it be fine to give a line-height scale like 1.5, or do you want to use an absolute value like 24px?

I think that an absolute value (float64) would be more flexible. The user can use a scale themselves if they want.

**Comment by hajimehoshi** [comment]
The challenging things are:

 * Backward compatibility: If I add `LineHeight float64` to `DrawOptions`, the zero value `0` should work as the current behavior. But, how do we distinguish the explicit `0` or just default `0`?
 * How should we give the line height value to `BoundString` function?

**Comment by nanoslayer** [comment]
Perhaps this should be implemented as a wrapper around font.Face. The wrapper would override Face.Metrics and return a custom Height.

Advantages of this approach:
- Backwards compatible, requires no changes to existing functions
- One source of truth for font line height

Disadvantages:
- Requires wrapping a font.Face for every function call
- Limited to a fixed.Int26_6 instead of a float64

This wrapper probably doesn't even need to live in Ebiten, but it might be nice to provide it.

The API could look something like the following:

```go
// FaceWithHeight returns a font.Face with the given line height.
// The returned face will otherwise have the same glyphs and metrics as face.
func FaceWithHeight(face font.Face, height fixed.Int26_6) font.Face
```

---

Another option would be to make the DrawOptions line height field private with a method to set the custom line height. For example:

```go
type DrawOptions struct {
    // ...
    customLineHeight bool
    lineHeight float64
}

func (op *DrawOptions) LineHeight(lineHeight float64) {
    op.customLineHeight = true
    op.lineHeight = lineHeight
}
```

This would only work for the DrawWithOptions and not for BoundString, however. Unless we add a new function BoundStringWithOptions.

**Comment by hajimehoshi** [comment]
Thanks! `FaceWithHeight` seems the way to go. This is simple and powerful.

Perhaps, the `height` argument can be `float64` instead of `fixed.Int26_6` for Ebiten users. If this function was in `golang.org/x/image`, the argument would have to be `Int26_6`, but probably I allow `float64` here. What do you think?

**Comment by nanoslayer** [comment]
It would be nice if we could use a float64, but how would this be exposed to Draw and BoundString?

**Comment by hajimehoshi** [comment]
We will be able to use this like this

```go
text.DrawWithOptions(img, "Foo", text.FaceWithHeight(face, 100), op)
```

Does this make sense?

**Comment by nanoslayer** [comment]
That makes sense, but how will the line height be exposed to DrawWithOptions? Through an unexported interface?

**Comment by hajimehoshi** [comment]
The new face's `Metrics` just inherits original `Metrics` but overwrites `Height` value.

**Comment by nanoslayer** [comment]
Ah, so it will still use a `fixed.Int26_6` then.

**Comment by hajimehoshi** [comment]
Yes, internally. `float64` should be converted internally.

**Comment by hajimehoshi** [comment]
```go
func FaceWithLineHeight(face font.Face, lineHeight float64) font.Face {
        return faceWithLineHeight{
                face:       face,
                lineHeight: fixed.Int26_6(int32(lineHeight * (1 << 6))),
        }
}

type faceWithLineHeight struct {
        face       font.Face
        lineHeight fixed.Int26_6
}

func (f faceWithLineHeight) Close() error {
        return f.face.Close()
}

func (f faceWithLineHeight) Glyph(dot fixed.Point26_6, r rune) (dr image.Rectangle, mask image.Image, maskp image.Point, advance fixed.Int26_6, ok bool) {
        return f.face.Glyph(dot, r)
}

func (f faceWithLineHeight) GlyphBounds(r rune) (bounds fixed.Rectangle26_6, advance fixed.Int26_6, ok bool) {
        return f.face.GlyphBounds(r)
}

func (f faceWithLineHeight) GlyphAdvance(r rune) (advance fixed.Int26_6, ok bool) {
        return f.face.GlyphAdvance(r)
}

func (f faceWithLineHeight) Kern(r0, r1 rune) fixed.Int26_6 {
        return f.face.Kern(r0, r1)
}

func (f faceWithLineHeight) Metrics() font.Metrics {
        m := f.face.Metrics()
        m.Height = f.lineHeight
        return m
}
```

Does this work for you?

(I've not determined whether I should add this function to `text` package yet...)

**Comment by nanoslayer** [comment]
> Does this work for you?

That seems like it would work.
 
> (I've not determined whether I should add this function to `text` package yet...)

I'm not sure. I can't really think of another place for it, though.

**Comment by hajimehoshi** [comment]
> I'm not sure. I can't really think of another place for it, though.

I mean I've not determined I should add this utility function to Ebiten or not. (another candidate can be `ebitenutil` but probably not)

I'll revisit this tomorrow.
