### ISSUE TITLE
audio: Use ALSA again for Linux

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1761]
Now mixing happens on Ebiten side, there is no strong reason to keep using PulseAudio.

See also #1663

CC @nanoslayer

**Comment by divVerent** [comment]
FYI getting a lot of clicking noise with the new version; going to bisect. Pulseaudio being at fault is a common theme, but I am gonna verify for real :)

**Comment by hajimehoshi** [comment]
Thank you for the reporting!
