### ISSUE TITLE
Audio/Linux: massive clicking noises

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1766]
Bisecting found that

https://github.com/hajimehoshi/ebiten/commit/be7bc5ae4cb46b51fa662495e4996323244b8128

introduced really strong clicking when starting new sounds which is still present in `main`.

Attempted to prefix sounds by some silence, didn't do anything. Even replacing sounds by silence retained clicking in background music when starting new sounds.

Attached screenshot of the broken audio samples - looks like silence was inserted spuriously:

![20210817-055315](https://user-images.githubusercontent.com/251568/129729307-d6a54f18-4622-4f60-aa85-1b20a164f35c.png)

**Comment by hajimehoshi** [comment]
I think this is a buffer size issue, but please wait for #1761.

**Comment by hajimehoshi** [comment]
> I think this is a buffer size issue

On second thought, this is an issue in the mixing. Let me investigate.

**Comment by hajimehoshi** [comment]
> Attached screenshot of the broken audio samples 

I'm not sure what is indicated there. Is this an output audio wave, or an input audio wave?

**Comment by divVerent** [comment]
That was the output audio wave.

I also found a similar (but not same) bug in the Windows audio output that wasn't there in 2.1.4, so I'll file a separate bug for the Windows side - including "actual" and "intended" audio wav file - and will then see if I can do the same for the Linux binary.

**Comment by divVerent** [comment]
WAV files attached here too:

It clearly shows that the empty samples are not replacements but insertions, and that during these sections of silence, music is also not playing (so it seems a post-mix, not pre-mix issue).

[linux-sounds.zip](https://github.com/hajimehoshi/ebiten/files/7001341/linux-sounds.zip)

**Comment by hajimehoshi** [comment]
So the problem is that output wave includes unexpected values whenever a new player is played, right?

**Comment by hajimehoshi** [comment]
I think I understand the issue and this seems a performance issue. Hmm

**Comment by hajimehoshi** [comment]
Could you try the new ALSA version? a6c52b55ca03daae64bd6372690ac3eba33ddcbc

**Comment by divVerent** [comment]
As I wrote elsewhere - substantially better. There's still some minor
clicking noise (got it ONCE by trying to spam sounds for two minutes) but
that may have been pre-existing.

Certainly "good enough" for now, at least on this machine, and I guess if
there's really anything remaining, a larger buffer size will be all it
takes.

**Comment by hajimehoshi** [comment]
Thank you for testing! I'll merge this to main anyway, and I'll take a look further at this issue when I'm available. I'm happy that ALSA mitigated this issue.

**Comment by hajimehoshi** [comment]
> a larger buffer size will be all it takes.

Now 2048[samples] (= 0.043[s] for 48000[Hz]) is the buffer size. We might be able to adjust this to, e.g., 4096 [samples], but I'm worried about noticeable delay.

**Comment by divVerent** [comment]
Yeah, I sure don't want to go above 0.1s in my game, but some other games
probably require even smaller buffer.

And thanks for the fast fix! Will later try on low-end machines to see if
it's bad there or also OK.

**Comment by divVerent** [comment]
Considering fixed by these commits.

**Comment by hajimehoshi** [comment]
Thanks!
