### ISSUE TITLE
text: Export getGlyphImage

### ISSUE THREAD

**Issue by eihigh** [hajimehoshi/ebiten#1767]
Is it possible to export getGlyphImage?

I'm trying to do some advanced text rendering like line-height and letter-spacing. (related: #1760 ) Also, we may want the data of the glyphImage itself, rather than drawing the glyphImage on another image. What do you think?

(ja)
getGlyphBoundsをexportすることは可能ですか？

私はline-heightやletter-spacingのような高度なテキスト描画を行おうと考えています。(related: #1760 ) また、我々はglyphImageを他の画像に描画するのではなく、glyphImage自体のデータが欲しい場合があるかもしれません。いかがでしょうか？

**Comment by hajimehoshi** [comment]
Let me consider this in 2.3.

**Comment by hajimehoshi** [comment]
This might be related to #1871.

What about having a callback or a function for rendering?

```go
text.EachRune("The quick brown fox blah blah blah", face, func(r rune, glyph *ebiten.Image, x, y float64) {
    // (x, y) is a left-upper position where to render the glyph image.
    // You can render glyph as you wish
})
```

**Comment by hajimehoshi** [comment]
Or,

```go
type GlyphAndPosition struct {
    Glyph *ebiten.Image
    X float64
    Y float64
}

func AppendGlyphsAndPositions(glyphsAndPositions []GlyphAndPosition, text string, face font.Face)
```

**Comment by eihigh** [comment]
The latter looks like a good idea.

Since what I wanted to do was calculate advanced positions such as text wrapping, I would simply ignore X and Y when calculating the positions myself. I also wanted to include Advance for a more correct calculation.

```go
type Glyph struct {
    Rune rune
    Image *ebiten.Image
    X float64
    Y float64
    Advance fixed.Int26_6
}
```

**Comment by hajimehoshi** [comment]
You can get the Advance value from your `font.Face`, right?

**Comment by eihigh** [comment]
Yes, but I thought I could reduce the process of calculating the Advance by using the Advance value cached by Ebiten (although I am not sure of the actual cost).

**Comment by hajimehoshi** [comment]
Makes sense. Let me consider this.

**Comment by hajimehoshi** [comment]
1. Bounds

```go
type Glyph struct {
    Rune rune
    Image *ebiten.Image
    Advance fixed.Int26_6
    Bounds fixed.Rectangle26_6
}
```

```go
glyphs = text.AppenGlyphs(nil, "The brown fox develops games with Ebiten", face)
op := &ebiten.DrawImageOptions{}
var x, y fixed.Int26_6
for _, g := range glyphs {
    op.GeoM.Reset()
    op.GeoM.Translate(float64(x + g.Bounds.Min.X)>>6), float64(y + g.Bounds.Min.Y)>>6))
    dst.DrawImage(g.Image, op)
    x += g.Advance
}
```

2. Add Position in fixed.Point26_6

```go
type Glyph struct {
    Rune rune
    Image *ebiten.Image
    Advance fixed.Int26_6
    Position Point.Int26 // Position is a already-calculated image position
}
```

```go
glyphs = text.AppenGlyphs(nil, "The brown fox develops games with Ebiten", face)
op := &ebiten.DrawImageOptions{}
var x, y fixed.Int26_6
for _, g := range glyphs {
    op.GeoM.Reset()
    op.GeoM.Translate(float64(x + g.PositionX)>>6), float64(y + g.Position.Y)>>6))
    dst.DrawImage(g.Image, op)
}
```

3. Position in float64

```go
type Glyph struct {
    Rune rune
    Image *ebiten.Image
    Advance fixed.Int26_6
    X float64
    Y float64
}
```

```go
glyphs = text.AppenGlyphs(nil, "The brown fox develops games with Ebiten", face)
op := &ebiten.DrawImageOptions{}
var x, y float64
for _, g := range glyphs {
    op.GeoM.Reset()
    op.GeoM.Translate(x + g.X), float64(y + g.Y)
    dst.DrawImage(g.Image, op)
}
```

**Comment by eihigh** [comment]
Hmm, perhaps can all Int26_6s be substituted with float64 for convenience?

**Comment by hajimehoshi** [comment]
I realized that converting an `Int26_6` value to `float64` that can render glyphs correctly is pretty hard (and I'm not quite sure the current implementation in `drawGlyph` is correct). I think I'll provide an API with `float64` for positions.

> Hmm, perhaps can all Int26_6s be substituted with float64 for convenience?

Even for 'advance' values? Hmm

**Comment by eihigh** [comment]
> Even for 'advance' values? Hmm

Yes, in almost all cases, replacing Advance with float64 appears to be fine.

**Comment by hajimehoshi** [comment]
Sure, probably float64 would make sense for consistency.

I'd like to know more about your purpose to use 'advance' values in the first place. Could you explain it?

BTW you can get 'advance' value like this even if :

```go
var prevX float64
for i, g := range glyphs {
    if i > 0 {
        advance := g.X - prevX
        // Use advance
    }
    prevX = g.X
}
```

**Comment by hajimehoshi** [comment]
The current implementation's example on my local machine is like this:

```go
               const x, y = 240, 400
               op := &ebiten.DrawImageOptions{}
               for i, gl := range g.glyphs {
                       op.GeoM.Reset()
                       op.GeoM.Translate(x, y)
                       op.GeoM.Translate(gl.X, gl.Y)
                       op.ColorM.Reset()
                       r := 1.0
                       if i%3 == 0 {
                               r = 0.5
                       }
                       g := 1.0
                       if i%3 == 1 {
                               g = 0.5
                       }
                       b := 1.0
                       if i%3 == 2 {
                               b = 0.5
                       }
                       op.ColorM.Scale(r, g, b, 1)
                       screen.DrawImage(gl.Image, op)
               }
```

![image](https://user-images.githubusercontent.com/16950/141328532-836cd9d6-1e3e-4efb-8c39-d0f588c1ef0e.png)

**Comment by hajimehoshi** [comment]
@eihigh and I discussed on Discord and concluded that `Advance` is not needed so far. Let's revisit this later.
