### ISSUE TITLE
Audio/Windows: some audio clicking at start of every sound

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1768]
This is a regression from v2.1.4 - at current HEAD, there is some noticeable audio clicking in every sound.

NOTE: I don't actually have Windows - there is a slight chance this is actually a WINE issue, but even if it is, it is a regression of ebiten under WINE then.

I recorded the same game audio with WINE/PulseAudio/Audacity and my game's internal audio dumper to demonstrate the difference. At v2.1.4, this clicking does not happen.

Investigation of the wav file shows that the corruption always happens about 400 samples from start of any sound; not sure if there is any relevance to this number. To be clear, it quite surely isn't 512.

[windows-sounds.zip](https://github.com/hajimehoshi/ebiten/files/7001276/windows-sounds.zip)

**Comment by divVerent** [comment]
BTW issue doesn't differ between win32 and win64 builds.

**Comment by hajimehoshi** [comment]
> This is a regression from v2.1.4 

Is this a problem in 2.1 but in main branch?

**Comment by divVerent** [comment]
The issue never happened in any 2.1 release, but exists in the main branch - yes.

**Comment by hajimehoshi** [comment]
Sure, thanks.

Could you try ALSA version? `a6c52b55ca03daae64bd6372690ac3eba33ddcbc`

**Comment by divVerent** [comment]
I don't have that commit yet - for me issue-1761-alsa is at
d443f1d226d43c4e4d0c45da16ed30ca67ef0f3f. Mean that one?

With that one I still have clicks, but very seldomly (once in about two
minutes). May even have been pre-existing, it's certainly not at an
annoying level and just spamming sounds using arrow keys in my menu also
doesn't make it bad.

**Comment by hajimehoshi** [comment]
Sorry the change is for Linux, not for Windows (then I said I had a wrong number).

**Comment by divVerent** [comment]
Sorry from my end too - responded to the correct bug too now. I assume
this change will not affect the Windows binary, so didn't retest on
Windows.

**Comment by hajimehoshi** [comment]
Could you try `045b14ba2111f13ed1da7c62ec722e387d138284` for Windows? Thanks!

**Comment by hajimehoshi** [comment]
`ded679c07135db8699e06cb270a32308da984051` I added further improvements based on other people's feedbacks.

**Comment by divVerent** [comment]
Substantially better. There is some rather minor clicking left which I can
repro even in Audacity by creating a sine wave, fading it out and adding a
lot of silence at the end - this is likely a HW issue and not ebiten
related.

So, considering this fixed.

**Comment by hajimehoshi** [comment]
Thanks! We've also confirmed some slight clicking noises, but this should be much better than before.

Probably we have to switch a better audio API like WASAPI, but I'll take a look in another milestone.

Thank you for feedbacks and experiments!
