### ISSUE TITLE
ebiten: `SetScreenFilterEnabled` to switch the screen filter

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1772]
On my system here, the final blit from game output resolution to screen (both 3840x2160) takes 4.3ms.

However, I want to be able to customize this filtering to apply a CRT-style filter.

This however has a massive framerate cost as ebiten still performs a final blit from the output image I can write to to the screen. Is there any way how we can either skip or customize that blit?

As for how I measured the impact: I made a custom ebiten built with this delta:

```
diff --git a/uicontext.go b/uicontext.go
index 18ae973d..11096e81 100644
--- a/uicontext.go
+++ b/uicontext.go
@@ -190,6 +190,12 @@ func (c *uiContext) updateFrameImpl(updateCount int) error {
                uiDriver().ResetForFrame()
        }
 
+       if IsScreenClearedEveryFrame() {
+               c.screen.Clear()
+       }
+       c.game.Draw(c.screen)
+       return nil
+
        // Even though updateCount == 0, the offscreen is cleared and Draw is called.
        // Draw should not update the game state and then the screen should not be updated without Update, but
        // users might want to process something at Draw with the time intervals of FPS.
```

Clearly this can't seriously be applied that way, especially as it also flips the screen upside down. Other than that, everything worked perfectly and I got a massive fps boost with my changes:

- 88.7fps to 144fps with my CRT shader (and previously regularly dropping frames with vsync enabled, not with the change)
- 128fps to 263fps with a simpler CRT-ish shader
- 112fps to 222fps with a simple linear-filtered DrawImage call
- 141fps to 369fps with a simple nearest-filtered DrawImage call

GPU is: Mesa Intel(R) UHD Graphics (CML GT2)

So I suggest one of the following as a future API change:

- Optimize processing in case game-written screen image and output image are the same size. This is complicated due to flipping still being required - wonder though if the flipping could be handled while rendering to the image. Also due to the int/float conversions regarding Layout(), it is not always possible for a game to cause these two to be the same size, breaking this optimization on some odd HiDPI systems or window sizes.
- Provide a way to replace the current FilterLinear/filterScreen logic by a custom shader and a DrawRectShader call instead.
  - As flipping may be enabled or disabled at that point, and some shaders may not be symmetric regarding this (mine is), this may require providing an Uniform to the shader containing the flip status. Not sure, this may also be inferrable another way, although dfdy on the texcoord of the input texture sounds like a bad idea.

I could implement this and send a PR, but would first like to have your input regarding which option you would prefer. The former seems cleaner to be but might not be feasible - the latter is a rather trivial addition but has a weird tradeoff to make too:
- Could require a callback or pixel ratio query API so the game code can also replicate the current pixel ratio based decision between FilterLinear and filterScreen (but with its own shaders).
- Could also just say that game code that really wants to make this decision shall have to compute this on its own in the Layout() method by querying the device scale factor as well.

**Comment by divVerent** [comment]
Temporary workaround for me: I am now limiting output resolution to 4x game resolution, at which point my CRT filter hardly shows any Moiré patterns at all.

Boosts fps with the filter to 133fps.

Will undo that change though when this is resolved and the extra render step entirely elided (which would yield 144fps).

**Comment by hajimehoshi** [comment]
Quick reply: As I'd like to release v2.2 next month, let's consider whether to add this feature or not later. I'll read your suggestion carefully and reply later. Thanks!

**Comment by divVerent** [comment]
Sure, no problem. Have a sufficient workaround for now (as well as graphics
settings that switch to ebiten's built in filterScreen).

And indeed, already looking forward to the release.

**Comment by hajimehoshi** [comment]
Note to myself: Let's rewrite the 'screen' shader in Kage to enable to switch this.

**Comment by divVerent** [comment]
I now know much better what I really want here, and I think there are basically two options:

- Option 1 (simple): allow a hook into Ebiten that allows providing a custom screen shader.
- Option 2 (more flexible): provide a way to have no screen shader call at all, but by having the game's Draw() render directly to the screen surface.

Sadly, Layout() is currently incapable of enforcing a 1:1 pixel ratio (just returning w, h is only 1:1 when the screen scale is 100%, and applying a screen scale multiplier may differ from what Ebiten does in roundoff errors). If it weren't for this, I would actually like to suggest

- Option 3 (simple and flexible): if and only if Layout() caused a 1:1 translation of coordinates, pass a subimage of the screen to Draw() instead of using a temporary image. Ebiten stays responsible for clearing the "letterbox area", though (sadly this means extra render calls - but a game can clearly disable letterboxing from its Layout, skipping those too).

This could be enabled by e.g. optionally extending the Game interface to add a second kind of Layout() that works in terms of physical pixels, or maybe some option that toggles how Layout() operates. Or an API to query the actual outside width and height with scale factors applied (so new-style code would ignore the outsideWidth/outsideHeight arguments, but instead fetch ebiten.OutsideSize() except named better).

**Comment by divVerent** [comment]
BTW I have recently acquired a Dell E6500 laptop, which is rather underpowered for anything Ebiten specifically due to this issue; it's rather fillrate bound. Even the Ebiten examples hardly ever reach 60fps there when run at fullscreen.

Reducing the screen resolution with `xrandr` before starting a game clearly helps. But basically I'd like anything there that could help with performance at fullscreen, and this certainly sounds like a promising option to get fillrate reduced or to spend the fullscreen fill on a simpler shader than Ebiten's screen shader.

The screen texture being "special" is indeed a problem - this means that option 3 can't be offered automatically given constraints, but will absolutely need its own special API. Which in turn makes option 1 more attractive again.

**Comment by hajimehoshi** [comment]
What about:

```diff
diff --git a/gameforui.go b/gameforui.go
index 523c6072..c7ea2f76 100644
--- a/gameforui.go
+++ b/gameforui.go
@@ -107,9 +107,12 @@ func (c *gameForUI) Draw(screenScale float64, offsetX, offsetY float64, needsCle
 
        // filterScreen works with >=1 scale, but does not well with <1 scale.
        // Use regular FilterLinear instead so far (#669).
-       if s >= 1 {
+       switch {
+       case s > 1:
                op.Filter = filterScreen
-       } else {
+       case s == 1:
+               op.Filter = FilterNearest
+       default:
                op.Filter = FilterLinear
        }
        c.screen.DrawImage(c.offscreen, op)
```

? This is similar to (3) but still uses the offscreen image. However, this is better than doing nothing...

**Comment by divVerent** [comment]
Just forcing Nearest filter instead of Screen brought my game AAAAXY (BTW, finished Ebiten game, basically!) from 23fps to 36fps on that Dell laptop when at fullscreen (in windowed mode, about half total screen area, it's always >50fps).

Linear oddly is not faster than nearest BTW.

**Comment by divVerent** [comment]
So to summarize:

- A way to progammatically force Nearest would already be a sizable speedup.
- Maximum possible speedup and quality still probably requires a custom shader or raw screen texture access feature.
- However, for my concrete use case, forcing Nearest will already be optimal for the lowest-quality render mode. I mean, I gotta upscale _somewhere_ anyway...
- Slight distraction, is the built-in shader for FilterNearest already optimal or can it be improved further? Do we anywhere needlessly use AddressClampToZero or AddressRepeat where AddressUnsafe would do?

**Comment by divVerent** [comment]
Curious detail: when I force the nearest filter, I get no single glUseProgram call in render frames. I.e. ALL my glDrawElements calls use the same shader.

The calls are for purposes:

- clear screen
- render tilemap
- clear output screen (redundant here as I have real 16:9 aspect here on this other computer)
- render game

Vertex shader is trivial (declarations omitted):

```
void main(void) {
  varying_tex = A1;
  varying_color_scale = A2;

  mat4 projection_matrix = mat4(
    vec4(2.0 / viewport_size.x, 0, 0, 0),
    vec4(0, 2.0 / viewport_size.y, 0, 0),
    vec4(0, 0, 1, 0),
    vec4(-1, -1, 0, 1)
  );
  gl_Position = projection_matrix * vec4(A0, 0, 1);
}
```

Fragment shader is, after preprocessing and stripping comments and declarations:

```
void main(void) {
  highp vec2 pos = varying_tex;
  vec4 color;
  color = texture2D(T0, pos);
  vec4 s = varying_color_scale;
  color *= vec4(s.r, s.g, s.b, 1.0) * s.a;
  color = min(color, color.a);
  gl_FragColor = color;
}
```

It might be possible to optimize this further by removing the min() with color.a (probably unnecessary, prevents generating overbright premultiplied colors though but seems to only guard against rounding errors), as well the color_scale stuff.

In particular the handling of varying_color_scale is very weird but it may be necessary - varyings are linearly interpolated, but is a linear combination of a valid premultiplied color still a valid premultiplied color? Pretty sure it is, because the space of valid color quadruplets is convex. Meaning it might be better to do this computation on CPU in Ebiten, and to pass premultiplied color scales in already. Did not evaluate what it takes to support this in the other color modes, though.

Also note that I use color scale in my game in quite a bunch of places - so stripping this out when not needed adds a pair of glUseProgram calls again, which also costs performance. I still wonder if a refactor to make the colors premultiplied would be better. An ebiten.ColorM that operates on unpremultiplied colors may not be convertible to a premultiplied one, so this is not very nice, though.

**Comment by divVerent** [comment]
For now trying this next:

- varying_color_scale gets premultiplied in the vertex shader (doing this in Ebiten is probably better)
- no more min()

This yields this fragment shader:

```
void main(void) {
  highp vec2 pos = varying_tex;
  vec4 color;
  color = texture2D(T0, pos);
  vec4 s = varying_color_scale;
  color *= s;
  gl_FragColor = color;
}
```

which is basically optimal.

Note that this has subtle behavioral differences when interpolating color and alpha together in `DrawTriangles` - right now, a gradient from 0,0,0,0 to 1,1,1,1 will have 0.25,0.25,0.25,0.5 in the center (which darkens white, unlike the two colors at the border), while after my change, the center will be 0.5,0.5,0.5,0.5 (which still leaves white alone). So the change is more correct, but... possibly a problematic change for compatibility?

Gonna benchmark this soon.

**Comment by divVerent** [comment]
With these changes I reach 48fps with nearest (and 27fps with screen filter).

I'm going to send a PR for the change to varying_color_scale; as for a way to force nearest, not yet sure how this should look API-wise.

**Comment by hajimehoshi** [comment]
Let me fork this issue to change the milestone.
