### ISSUE TITLE
Fullscreen broken on X11 with HiDPI

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1774]
Repro:

- Set display DPI to something other than 96:
  `echo Xft.dpi: 144 | xrdb -merge`
- Run `examples/windowsize`
- Press `F`

Observe that a large part of the screen is cut off (see screenshots).

![20210820-100222](https://user-images.githubusercontent.com/251568/130268663-dda4ca73-ae10-4879-a530-d5753591052a.png)
![20210820-100226](https://user-images.githubusercontent.com/251568/130268665-cf6a5e7e-3621-4000-8d7c-9709e1b2e907.png)

Note how `Xft.dpi` does not influence the Device Scale Factor, but it does change the initial window size and causes this weird fullscreen scale up.

Reproduced on:
- X11/i3
- Wayland/Sway/Xwayland

Does NOT reproduce on:
- Cinnamon

Most likely because ebiten has its own support for querying device scale that is specific to Cinnamon and GNOME, while not supporting anything else; at the same time, glfw has its different support and these two disagree.

Maybe we should just always use glfw's content scale?

Note though:

```
// deviceScaleFactor() is a scale by desktop environment (e.g., Cinnamon), while GetContentScale() is X's scale.
```

I do not quite understand this - when do these two ever differ, except when there simply is no desktop environment managing this at all? In fact, do we ever handle the case of these two differing right?

**Comment by hajimehoshi** [comment]
Yeah, so this means that we have to support i3 and the other desktop environments at `deviceScaleFactor`.

> I do not quite understand this - when do these two ever differ, except when there simply is no desktop environment managing this at all? In fact, do we ever handle the case of these two differing right?

IIUC a scale by a desktop environment and a scale by X are independent. Ebiten tries to follow the former to make the window size more natural to users. 

I'm not familiar with X's scalings but IIUC, if X is in HiDPI mode, everything is small unless the desktop environment specifies a scale. In your case, doesn't i3 have a scale like 200%?

**Comment by divVerent** [comment]
Generally there are two places where X tracks scale:

- Physical size of the monitor (usually rather unused)
- Font sizing (this is what `Xft.dpi` does)

i3 does not really care about anything else, and all X11 window sizes are measured in actual device pixels.

**Comment by divVerent** [comment]
Having said that, in the specific case of fullscreen mode, all this should not matter. The texture should just be rendered from screen corner to corner (with potential letterboxing), so the only influence scale factors should have there is in the arguments to Layout().

While at it - should a game that returns w, h from Layout(w, h) be assumed to have a screen in device pixels (so all scaling is done by the game) or device independent pixels (so ebiten scales)? It _seems_ based on the implementation that the latter is the case - which means a game that wants to avoid all scaling needs to return w*deviceScaleFactor, h*deviceScaleFactor.

So assuming that this is how Layout() works, it gets device independent pixel size of the window/screen as input and returns the intended texture size in "raw" pixels as output.

Now the current impl calls Layout() on toFramebufferPixel(fromGLFWMonitorPixel(videoModeSize, deviceScaleFactor)) or toFramebufferPixel(fromGLFWPixel(windowSize)).

Expanding these terms, we actually pass videoModeSize/deviceScaleFactor*contentScale/deviceScaleFactor in the former case (VERY WEIRD), and windowSize/contentScale*contentScale/deviceScaleFactor (device independent pixels, assuming windowSize is truly the _raw_ window size in physical pixels) in the latter case.

Sadly I don't know what kind of scaling GLFW itself applies.

**Comment by divVerent** [comment]
Hm.

On Windows, the conversions are:

- fromGLFWMonitorPixel is /deviceScale
- fromGLFPixel is /deviceScaleFactor
- toGLFWPixel is *deviceScaleFactor
- toFramebufferPixel is the identity

Assuming this, Layout() gets called on `videoModeSize/deviceScale` or `windowSize/deviceScaleFactor`, respectively. Not sure why window and fullscreen mode sizes would be measured in different units, but maybe that's just the reality - don't know. Or actually... it just LOOKS that way, as on Windows deviceScale and u.deviceScaleFactor() are always the same.

Generally it'd help if these functions were clearer named, to indicate what units they expect on the respective "other end". Like, what kind of pixel is toFramebufferPixel converting _from_?

**Comment by hajimehoshi** [comment]
Hmm, that's interesting. I'm not sure what is the best solution so far. I'd like to understand Linux's desktop environments more.

> Font sizing (this is what Xft.dpi does)

If this value changes to like 72, is the fullscreen scale's result affected?

> While at it - should a game that returns w, h from Layout(w, h) be assumed to have a screen in device pixels (so all scaling is done by the game) or device independent pixels (so ebiten scales)? It seems based on the implementation that the latter is the case - which means a game that wants to avoid all scaling needs to return w*deviceScaleFactor, h*deviceScaleFactor.

Yes this is correct and intended. And your comments following this seem correct.

> Generally it'd help if these functions were clearer named, to indicate what units they expect on the respective "other end". Like, what kind of pixel is toFramebufferPixel converting from?

Yeah right, sorry for confusion. All the 'from' functions convert from a device-independent unit to something, and 'to' functions convert to a device-independent unit from something. I'll rename this.

**Comment by divVerent** [comment]
Trying to use other conversions as a "proxy" to find a chain that should be the identity.

- Mouse position handling: window.GetCursorPos() (physical pixel) -> fromGLFWMonitorPixel(., deviceScaleFactor) -> AdjustPosition(multiplies with deviceScaleFactor, divides by screenScale)
- Drawing: multiply by screenScale to get from texture pixel to physical pixel

This suggests that the combination of all these conversions should always be the identity.

Thus, `fromGLFWMonitorPixel . (* deviceScaleFactor) . (/ screenScale) . (* screenScale)` must be the identity, so fromGLFWMonitorPixel can always just divide by deviceScaleFactor.

Let's see if I can find more such relations to solve this.

**Comment by divVerent** [comment]
By naming, toFramebufferPixel sounds like it must be the exact inverse of fromGLFWMonitorPixel; however then we call Layout() wrong. It seems like to call Layout correctly, toFramebufferPixel must be the identity in ui_unix too.

However, just changing that breaks windowed mode for me - it now is "letterboxed". So this isn't all.

One thing that does work is making toFramebufferPixel the identity and using deviceScaleFactor in all three functions. It does not seem to make sense to me that GLFW would use different units for monitor pixels and window pixels, although _maybe it does_? This would be "happy" on my system - it'd then entirely ignore `Xft.dpi` and just use the Cinnamon or GNOME provided data when in those, and 1.0 otherwise.

**Comment by hajimehoshi** [comment]
FYI: I found a comment of an investigation: https://github.com/hajimehoshi/ebiten/issues/1307#issuecomment-694393662

**Comment by divVerent** [comment]
I cannot yet confirm that GLFW ever returns a scaled monitor size.

However there are some interesting tidbits in GLFW source:

- Content scale is applied to window sizes when wndconfig->scaleToMonitor is set. Do we set that?
- Otherwise GLFW appears to nowhere ever use the content scale.

What I did:

- Search for contentScaleX, contentScaleY.
- Used only where it's computed, and:
  - _glfwPlatformGetMonitorContentScale
    - Only called from glfwGetMonitorContentScale
      - Only exported API + called from tests
  - _glfwPlatformGetWindowContentScale
    - Only called from glfwGetWindowContentScale
      - Only exported API + called from tests
  - inside createNativeWindow if wndconfig->scaleToMonitor is set

So if we make sure scaleToMonitor is off, then GLFW's scaling is nowhere used on X11. Didn't also track this down for Windows and OS X though.

**Comment by divVerent** [comment]
Another way to verify this independently: with my proposed change - never using GLFW's scale, always ebiten's - things work fine. If I then mess around with `Xft.dpi`, nothing at all changes. That seems a pretty strong sign that after my changes, GLFW's own scaling stops mattering.

Now for trying the same out in Cinnamon...

**Comment by divVerent** [comment]
Tried a bit more - and found a case that breaks with my changes.

To break it, you need to set up a fractional device scale in Cinnamon (like 150%).

The regular normal/HiDPI setting does NOT break.

So let's see what that setting even does...

**Comment by divVerent** [comment]
In the with my changes failing, without working, Cinnamon configuration, we indeed have deviceScaleFactor=1.500023 (seems to come from Xft.dpi: 192) and ContentScale=2 (seems to indicate the screen is 2x upscaled). It seems like the Cinnamon monitor dialog allows setting these two separately.

According to xrandr, my monitor now has 1.3333x its normal resolution, so Cinnamon is using xrandr-based scaling for this.

**Comment by divVerent** [comment]
Clearly there is _something_ special going on when Cinnamon is involved that I do not know - it does not appear to be GLFW's doing.

I am beginning to get somewhere...

If I set XDG_DESKTOP_NAME=None, I am disabling ebiten's Cinnamon logic while keeping GLFW's scaling as is. And voila, the bug appears.

Adding debug prints to Layout() shows that despite my xrandr screen size being 2560x1440, Layout() gets passed 3840x2160 when I do this.

It basically appears as if Cinnamon has some special nonstandard handling for fullscreen windows. In particular, according to xwininfo I still have a 2560x1440 window.

First of all I should mention, SuperTux has broken fullscreen in Cinnamon with this setup; only ebiten stuff appears to work. This speaks very much for a bug in Cinnamon that you're working around than anything else... so maybe the solution is to turn on this handling only if Cinnamon is actually used? In other words, if we default the scale factor to "whatever glfw returns", but only override when there IS a DE with this hackery, things should work everywhere.

**Comment by divVerent** [comment]
Next experiment: making all the from/to functions return x as-is and setting XDG_CURRENT_DESKTOP=None to disable Cinnamon hackery. Result: still broken fullscreen.

If only I could trace what actually happens at X11 level...

**Comment by divVerent** [comment]
Running an xtrace shows that the only place the value 3840 could be coming from is GetScreenResourcesCurrent.

Sudden realization: what if GLFW returns the MAXIMUM mode, but we need the CURRENT mode?

**Comment by divVerent** [comment]
I've figured it out.

The issue is that Cinnamon doesn't use a lower video mode, but the Xrandr scale feature.

So a Cinnamon-less repro (broken in current code TOO) is:

```
xrandr --output DP-1 --scale 1.5x1.5
./whatever-ebiten-game
```

This is broken in ALL environments. And I strongly suspect the issue needs to be fixed in GLFW, not Ebiten. The cause is that GLFW requests the current mode's resolution, BUT does not scale it by the current output scale factor.

Once fixed, Ebiten can remove the Cinnamon-specific hackery and just a single deviceScaleFactor for everything (I'd propose to be using the GLFW provided one). This then will be consistent with font rendering, which is usually the right way to go.

**Comment by divVerent** [comment]
Having said that, I'd strongly like to have a workaround I can use till then for my game; as xrandr --scale generally leads to poor display quality (blurry) and as Cinnamon even advises against it in its tooltip, I assume the majority of users aren't using the fractional scaling feature.

Also, given SDL has precisely the same bug, I'd like to make the "political decision" for my game to be equally broken as SDL when xrandr --scale is used, rather than ONLY working in GNOME and Cinnamon and not anywhere else (status quo).

So, what if we for now create a setting (be it a build tag or a runtime variable of some sort) to toggle the behavior to just use one scale factor for everything?

**Comment by divVerent** [comment]
Minimal workaround that works for me in EVERY configuration (i3, sway, ebiten, no matter if scaled or not):

```
diff --git a/internal/uidriver/glfw/ui.go b/internal/uidriver/glfw/ui.go
index 6c18f6a4..c25bc31c 100644
--- a/internal/uidriver/glfw/ui.go
+++ b/internal/uidriver/glfw/ui.go
@@ -929,7 +929,7 @@ func (u *UserInterface) updateSize() (float64, float64, bool) {
        u.toChangeSize = false
 
        var w, h float64
-       if u.isFullscreen() {
+       if u.isFullscreen() && false {
                v := currentMonitor(u.window).GetVideoMode()
                ww, wh := v.Width, v.Height
                s := u.deviceScaleFactor()
```

Yes, I'm just turning off the fullscreen-specific handling in updateSize(), thereby not using the broken data from GetVideoMode().

The contentScale provided by Cinnamon is still used this way and is used solely to decide sizes of new windows; for rendering including fullscreen, everything works as it should.

Note that this does not fix everything; in partiuclar, ebiten functions that return the screen size before creating a window will keep returning wrong (too large) data. It does seem good enough for me, at least if on all platforms `u.window.GetSize()` is valid and correct when fullscreen. If not, maybe this workaround is only OK for Linux.

So as a temporary hack, could I get a way to toggle this? The proper GLFW fix then can wait a bit longer (I'll have to find a pure GLFW repro for this first).

**Comment by divVerent** [comment]
Sorry, this temp hack alone is NOT enough - it only works when toggling into fullscreen, not when starting as fullscreen to begin with (well, of course I could just do the toggling myself in the first Update() call).

Any idea how to better handle this?

**Comment by divVerent** [comment]
The GLFW boing.c example does NOT exhibit this bug.

But reading its code, it does not rely on monitor sizes - it instead uses the framebuffer size callback from GLFW to get informed about a successful resize.

Ebiten already waits for this callback but optionally with a timeout. The timeout seems to be there to guard against a race condition (#1618).

Also, I can no longer reproduce any issues with my temp hack from https://github.com/hajimehoshi/ebiten/issues/1774#issuecomment-902923730; I guess I just hit the odd case of it taking more than one second to get the new window size.

**Comment by hajimehoshi** [comment]
> This is broken in ALL environments. And I strongly suspect the issue needs to be fixed in GLFW, not Ebiten. The cause is that GLFW requests the current mode's resolution, BUT does not scale it by the current output scale factor.

I'm not sure what is correct, but if you are right, can we add something or ignore GLFW's API to treat the 'correct' values?

**Comment by hajimehoshi** [comment]
> Also, given SDL has precisely the same bug, I'd like to make the "political decision" for my game to be equally broken as SDL when xrandr --scale is used, rather than ONLY working in GNOME and Cinnamon and not anywhere else (status quo).
> 
> So, what if we for now create a setting (be it a build tag or a runtime variable of some sort) to toggle the behavior to just use one scale factor for everything? I personally don't care which one to use, although I'd be leaning towards "just force all scale factors to 1.0" given I already compute a "good window size" in my game anyway by multiplying game size by an integer factor "as big as possible" to leave some desktop environment borders.

Hmm, so are you suggesting to make things broken for consistency rather than hacks only for Gnome and Cinnamon, which seems inconsistent? Would it be feasible to make everything work, which is also consistent and ideal?

**Comment by divVerent** [comment]
Making everything work seems almost possible:

- Do not rely on the monitor sizes for computing fullscreen size; instead
update based on the GLFW callback for framebuffer size. This is what the
example that comes with GLFW does, although you apparently had a case where
the callback never came.
- Failing that, use the window size approach always (which is what my
attempted patch does).

Catch is, if we call GetSize too early, we will stay at the wrong size -
and I believe this happened to me once, although I cannot repro. Would it
actually be OK to just call GetSize every frame, or is that call expensive?

What this can NOT fix (which is why this is just an "almost") is predicting
the screen size BEFORE entering fullscreen. This is plain impossible using
GLFW's API. I guess the way to fix this is filing a GLFW feature request to
either return "adjusted for scale" resolutions, or to include the scale
factor as an additional struct member in the monitor info.

Impact of this breakage to many games would be displaying the wrong
fullscreen size in the graphics settings menu, but everything else would
work.

Impact of this breakage to my game in specific would be that I will
calculate a too large initial window size in windowed mode on such systems.
Luckily it appears that the desktop environments clip this overly large
size to the screen size then, so this is kinda OK (plus I provide a setting
for window size anyway).

**Comment by divVerent** [comment]
Okay, so from what I see I guess the first thing to decide is, what _should_ Ebiten's device scale factor be?

It seems like Ebiten primarily uses it to map from game-defined to actual window sizes, but also - sadly - in lots of other places.

So my very first question would be: why? Can't this be simplified and deviceScaleFactor be used way less?

Then there is GLFW's own content scale. This is entirely unnecessary but "nice to have".

What I would suggest as correct behavior:

- In GLFW, ebiten.DeviceScaleFactor() shall return GLFW's content scale.
- When querying video modes (ScreenSizeInFullscreen), translate GLFW resolution using BOTH ebiten.DeviceScaleFactor() AND "the XRandR scale".
- For internal usage, however, do not rely on this conversion; instead create a fullscreen window, wait for it to be done and then query its size to find what you actually got.
- In order to call Layout(), first translate the input using ebiten.DeviceScaleFactor() only.
- Similarly, translate CursorPosition(), TouchPosition(), WindowSize(), SetWindowPosition(), SetWindowSize().
- Internal code outside these API calls shall not use the device scale factor at all. I.e. Ebiten internally "thinks" in window system pixels (post-XRandR, pre-ContentScale).

This way should work perfectly on X11. Can't tell it will work this way on Windows or Mac - depends on what kind of coordinates GLFW returns on these platforms.

**Comment by divVerent** [comment]
Now wondering though if there could be a fix without this massive refactor.

What about this:

- deviceScaleFactor is always GLFW's
  - this is somewhat tricky as the devicescale library can't use our GLFW window - that'd cause a dependency cycle. For this I'd probably put this in the glfw ui driver itself, and ignore the devicescale library for anything GLFW (meaning devicescale library can entirely drop its X11 and Windows support, and only remains used for JS and mobile)
- ONLY when converting the fullscreen resolution, also apply the XRandR scale factor (i.e. what you currently get via cinnamon and GNOME config files or commands)

Speaking of XRandR - it seems like the GLFW issue we are primarily fighting with - and why you needed the Cinnamon and GNOME hacks - is that GLFW gives you the wrong kind of resolution. When I run xrandr:

```
XWAYLAND0 connected 1360x768+0+0 (normal left inverted right x axis y axis) 310mm x 170mm
   1360x768      59.98*+
```

Ebiten needs the "upper" 1360x768, but GLFW provides the "lower" 1360x768. It appears that the upper one comes from XRRCrtcInfo, the lower one from XRRModeInfo. Indeed, GLFW exclusively uses XRRModeInfo, except where matching against Xinerama screen indexes. The problem with XRRCrtcInfo for GLFW's use case is that it does not help when one wants to know the output resolution when a specific different video mode is selected.

I am now somewhat tempted to suggest Ebiten shall have its own X11 connection in addition to GLFW's, so it can query the XRandR stuff itself (e.g. via https://pkg.go.dev/github.com/BurntSushi/xgb/randr). Or, given you seemed to be OK with spawning an external utility anyway... could even just do this: https://github.com/vcraescu/go-xrandr (but then the xrandr utility must be installed).

Failing that, we could also just give up on predicting fullscreen size properly, and just do that:

- deviceScaleFactor is always GLFW's (same as above)
- do not rely on predicted screen size; somehow fix initialization of fullscreen mode so we always eventually get the correct size

That'll yield the minimum size patch, rather sure, but ebiten.ScreenSizeInFullscreen would remain broken with that.

I can try making the patch - however I only have Linux systems so I won't be able to test on Windows or Mac.

**Comment by hajimehoshi** [comment]
Thank you for the details! Sorry I was quite busy today. I'll reply tomorrow when I'm available.

**Comment by hajimehoshi** [comment]
Hmm, I'm confused.

Xrandr's scale and Gnome/Cinnamon's scale match. Is this correct? (and are you suggesting we should use Xrandr's?)

> I am now somewhat tempted to suggest Ebiten shall have its own X11 connection in addition to GLFW's, so it can query the XRandR stuff itself (e.g. via https://pkg.go.dev/github.com/BurntSushi/xgb/randr). Or, given you seemed to be OK with spawning an external utility anyway... could even just do this: https://github.com/vcraescu/go-xrandr (but then the xrandr utility must be installed).

I tend to allow this, but the concern is that this would not work with non-X system like Wayland or Mir.

**Comment by divVerent** [comment]
On Fri, Aug 27, 2021 at 11:32 AM Hoshi, Hajime (星一) <
***@***.***> wrote:

> OK so, in the current implementation, what we should do is
>
>    1. DeviceScaleFactor should use XRandR's scale.
>    2. fromGLFWMonitorPixel should use XRandR's scale
>    3. fromGLFWPixel can remain as it is (the monitor's content scale)
>
>
I am not 100% convinced. Let's see how they interact:

- Let XRandr scale be r (i.e. 2 if physical resolution is 2x window
system's)
- Let dpi based scale be d (i.e. dpi of rendered pixels is 96*d). This is
the one GLFW returns as ContentScale.

Here are the "backwards" conversions for window size:
monitor res -> fromGLFWMonitorPixel -> toFramebufferPixel must apply factor
1 / (r * d), as this is the proper conversion from physical to device
independent resolution
window res -> fromGLFWPixel -> toFramebufferPixel must apply factor 1 / d,
as this is the proper conversion from window to device independent
resolution

Here are the "forward" conversions for window size:
requested res -> toGLFWPixel must apply factor d

Also, as this is clearly intended:

fromGLFWPixel and toGLFWPixel must be inverses.

From this we get:

- fromGLFWPixel(x) = x / d
- toGLFWPixel(x) = x * d
- toFramebufferPixel(x) = x
- fromGLFWMonitorPixel(x) = x / (r * d)
- DeviceScaleFactor generally should be d, too.

This is basically the same implementation as in ui_windows, with
deviceScaleFactor() being somehow initialized using GLFW's value.  The only
difference is in fromGLFWMonitorPixel, which will in addition also apply
the XRandR scale.


>
> Are these correct? Sorry if I'm wrong. I'm not sure about especially the
> third item.
>
>
>    - XRandR's (and also GNOME's and Cinnamon's scale - the thing
>    currently set
>    as DeviceScaleFactor) should only be used for converting GLFW's screen
>    resolution data to "window system pixels".
>
>
Yes. And arguably this might actually be a GLFW bug.


>    - The alternative I suggested was instead skipping GLFW's functions to
>    return video modes, and to instead trust XRandR itself on this.
>
>
Yes; breaks with Wayland of course.

>
>    - Another alternative would be not querying video modes at all but to
>    instead accept the window size we actually get, although this is
>    currently
>    not feasible as Ebiten provides an API to query the fullscreen
>    resolution
>    before creating the window.
>
> Yes.


>
>
> Your suggestions are:
>
>    1. Use XRandR's scale only for fromGLFWMonitorPixel
>    2. Use XRandR's scale for fromGLFWMonitorPixel and DeviceScaleFactor
>    3. Use GLFW's monitor size: (don't we already do this)?
>
>
Not quite; see above where I actually resolved the equations.


>
>
> Are these correct?
>
> I'm fine to fix the issue only for X, and let's keep the current behavior
> for non-X system if possible.
>

Sounds good.

**Comment by hajimehoshi** [comment]
Let the current DeviceScaleFactor call r'. r' is very similar to r but makes sense only on Gnome and Cinnamon.

The current implementation is:

* fromGLFWMonitorPixel(x) = x / r'
* fromGLFWPixel(x) = x / d
* toGLFWPixel(x) = x * d
* toFramebufferPixel(x) = x * d / r'
* DeviceScaleFactor() = r'

And your suggestion is to adjust them like this:

* fromGLFWMonitorPixel(x) = x / r
* fromGLFWPixel(x) = x / d
* toGLFWPixel(x) = x * d
* toFramebufferPixel(x) = x / d / r
* DeviceScaleFactor() = d

My current questions are:

* toFramebufferPixel seems completely different, but is this really correct?
* If DeviceScaleFactor is d, can we really achieve Hi-DPI resolution?

**Comment by divVerent** [comment]
On Sat, Aug 28, 2021, 02:33 Hoshi, Hajime (星一) ***@***.***>
wrote:

> Let the current DeviceScaleFactor call r'. r' is very similar to r but
> makes sense only on Gnome and Cinnamon.
>
> The current implementation is:
>
>    - fromGLFWMonitorPixel(x) = x / r'
>    - fromGLFWPixel(x) = x / d
>    - toGLFWPixel(x) = x * d
>    - toFramebufferPixel(x) = x * d / r'
>    - DeviceScaleFactor() = r'
>
> And your suggestion is to adjust them like this:
>
>    - fromGLFWMonitorPixel(x) = x / r
>    - fromGLFWPixel(x) = x / d
>    - toGLFWPixel(x) = x * d
>    - toFramebufferPixel(x) = x / d / r
>    - DeviceScaleFactor() = d
>
> My current questions are:
>
>    - toFramebufferPixel seems completely different, but is this really
>    correct?
>
>
No; toFramebufferPixel should be the identity (just x). Exactly like on
Windows and OS X - basically this conversion will no longer be needed
anywhere. All fullscreen specifics go into fromGLFWMonitorPixel.


>    - If DeviceScaleFactor is d, can we really achieve Hi-DPI resolution
>    when we want?
>
> Absolutely. Ebiten will always allocate the internal screen as Hi-DPI, and
a game that wants to render to Hi-DPI will have to multiply the input by
DeviceScaleFactor() in Layout(). Like now.

**Comment by hajimehoshi** [comment]
Thanks, so is your suggestion

 * fromGLFWMonitorPixel(x) = x / r
 * fromGLFWPixel(x) = x / d
 * toGLFWPixel(x) = x * d
 * toFramebufferPixel(x) = x
 * DeviceScaleFactor() = d

?

I'd be very happy if you could send a PR for this. I'm not confident this would work perfectly yet as I don't understand about XRandR, but I'd like to test this on my some Linux machines.

**Comment by divVerent** [comment]
Sounds good, will try.

The main complication will be that I can't use the devicescale mode or it'd
cause a cyclic dependency. I'll probably at least at first just skip that
module entirely for the GLFW/X11 code path.

The other complication is that there's no "explicitly intended" way to get
the scale from XRandR - one can get a matrix, or the current mode and the
current output size. I think I'll go for the latter and just divide. Have
to see though how that interacts with panning (which one can set up too in
XRandR).

**Comment by divVerent** [comment]
Working on it now - https://github.com/divVerent/ebiten/tree/devicescale

Not filed the PR yet - first want to get it to work on all platforms I can
try. In particular Linux/Sway (tested), Linux/Cinnamon, Linux/GNOME,
Windows/WINE (sorry, don't have real Windows anywhere, but at least I can
set up HiDPI there).

I am unsure about OS X; the previous code looked horribly wrong (like not
supporting device scale at all). I believe my changes are NOP for OS X, but
can I ask you to test/fix OS X support once I have tested for the above
listed platforms?

**Comment by hajimehoshi** [comment]
Thank you for your dedicating work!

>  but can I ask you to test/fix OS X support once I have tested for the above listed platforms?

Sure, I'll test on my macOS and Windows!

**Comment by divVerent** [comment]
Filed these GLFW bugs:

* https://github.com/glfw/glfw/issues/1960
* https://github.com/glfw/glfw/issues/1961

Note that a fix to any of these might need an Ebiten update in response. As Ebiten's go.mod controls the GLFW version used, this can then be in sync.

For now, I figured out that querying the workarea only _sometimes_ works (namely, when the desktop environment is setting one), so I am now switching to an approach that doesn't use the workarea query but really operates at XRandR level.

**Comment by divVerent** [comment]
Okay, now switched to using the `xgb` module to query RANDR data. Works so far on sway and i3. Now testing Cinnamon.

**Comment by divVerent** [comment]
Windows/WINE/XWayland/Sway at 144dpi also working.

**Comment by divVerent** [comment]
WINE with `xrandr --scale` _broken_.

Not sure if this is WINE's bug though. Will see if I can repro with other fullscreen games in WINE.

**Comment by divVerent** [comment]
WINE breakage predates my changes (happens on Ebiten main too). Strongly suspect WINE has the exact same bug as GLFW does - it returns the hardware video modes, not the logical resolutions.

**Comment by divVerent** [comment]
I'm rather confident about correctness for Windows now.

Relevant deltas for Windows:
- fromGLFWMonitprPixel applies the given scale and the deviceScaleFactor. The given scale is always 1.0; previously the deviceScaleFactor was given, so this should be a NOP, but a potentially broken refactor. Worth verifying.
- Otherwise, although GLFW and Ebiten have both their own implementation of device scale factor querying, I assume the changes are NOP. It appears they use the same APIs though.

Relevant deltas for OS X:
- Added device scale support at all. Not sure if that was a good or a bad idea. It is possible that the OS X conversions actually should just be "return x" with my changes too, which would imply that GLFW wants device independent coordinates on OS X (even though it wants frame buffer pixels anywhere else).
- Am unsure about fromGLFWMonitorPixel, as it depends on what kind of data GLFW returns. Might have to be x or x / (screenScale * u.deviceScaleFactor()) like in all other backends.
- Am unsure if screenScale is relevant on OS X at all. Suspecting it isn't and always having it 1.0 is right.
- Mouse cursor position conversion changed; previous code just returned coordinates as is, new code divides by device scale factor. Rather sure this is a positive improvement.

**Comment by hajimehoshi** [comment]
Awesome work!

I think I'd like to see the actual code, which would be easier to understand what to do. Anyway I'm looking forward to your PR.

**Comment by divVerent** [comment]
Filed https://github.com/hajimehoshi/ebiten/pull/1797 but let's consider it
WIP for now.

**Comment by divVerent** [comment]
PR #1800 will fix most of this, and https://github.com/divVerent/ebiten/commit/1449b68d0beb6adc4c2cb5da0973a134df9ca36d (PR to be filed when #1800 is in, as it can't be merged independently) will then fix the rest. Can't really split that commit up further, sadly, but at least the OS-dependent stuff is mostly out of there already.
