### ISSUE TITLE
Using FPSModeVsyncOffMinimum breaks IsKeyJustPressed

### ISSUE THREAD

**Issue by tslocum** [hajimehoshi/ebiten#1791]
To reproduce:

Code: https://code.rocketnine.space/tslocum/kibodo/src/branch/vsync
```
go install code.rocketnine.space/tslocum/kibodo/demos/kibodo@vsync
~/go/bin/kibodo
```
- Press the A button on your physical keyboard, not on the screen, and `IsKeyJustPressed: A` will be printed to stdout when the press is detected.
- Notice that when there is no additional input (the mouse remains still and no mouse buttons are pressed), `IsKeyJustPressed: A` is only printed once or a few times, rather than every time the key is pressed.

This issue only occurs after setting `ebiten.SetFPSMode(ebiten.FPSModeVsyncOffMinimum)`.  `ebiten.AppendInputChars` continues to function as expected.

Tested on Gentoo Linux with Go 1.17.

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look.

**Comment by hajimehoshi** [comment]
I tried your demo. `IsKeyJustPressed: A` was not printed on stdout regardless of the FPS mode.

**Comment by hajimehoshi** [comment]
The cause is that we adopted 'sticky' input mode: https://github.com/hajimehoshi/ebiten/commit/5d2393c3c13e306cb082365b654c95463d91f3cf
