### ISSUE TITLE
affine: Avoid allocating arrays at UnsafeElements

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1796]
What about taking slices there?

**Comment by Zyko0** [comment]
I'd take slices here, having a pointer to an array is basically rebuilding a slice I believe
Since you're using pointers, I'm not sure there would be a direct benefit (since you avoid N elements copies already) but I think it's better anyway

**Comment by hajimehoshi** [comment]
> I'd take slices here, having a pointer to an array is basically rebuilding a slice I believe

Now this uses a pointer to an array since the number of elements are always same

The problem I realized now is that UnsafeElements is used to a shader's uniform variables, and copies seem inevitable. Then, even if UnsafeElements took slices, nothing would change.

**Comment by hajimehoshi** [comment]
Apparently `UnsafeElements` calls happened often at `mipmap` package, and now this is replaced with `At`, which takes an element directly.
