### ISSUE TITLE
Crash with Dual Shock 4

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1802]
Reported https://github.com/go-gl/glfw/issues/333 by @TeddyDD

```
[...]
GLFW: An uncaught error has occurred: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)
GLFW: Please report this bug in the Go package immediately.
panic: InvalidValue: Invalid button in gamepad mapping 030000004c050000cc09000011810000 (PS4 Controller)

goroutine 1 [running]:
github.com/go-gl/glfw/v3.3/glfw.acceptError({0x0, 0x0, 0xc00011a9e0})
	/home/teddy/src/darktile/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:174 +0x186
github.com/go-gl/glfw/v3.3/glfw.panicError(...)
	/home/teddy/src/darktile/vendor/github.com/go-gl/glfw/v3.3/glfw/error.go:185
github.com/go-gl/glfw/v3.3/glfw.WindowHint(0xc00018e000, 0xb49400)
	/home/teddy/src/darktile/vendor/github.com/go-gl/glfw/v3.3/glfw/window.go:275 +0x3f
github.com/hajimehoshi/ebiten/v2/internal/glfw.WindowHint(...)
	/home/teddy/src/darktile/vendor/github.com/hajimehoshi/ebiten/v2/internal/glfw/glfw_notwindows.go:372
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.initialize()
	/home/teddy/src/darktile/vendor/github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw/ui.go:179 +0x85
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.init.1()
	/home/teddy/src/darktile/vendor/github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw/ui.go:159 +0x19
```

I'd be happy if you could give a minimized code to reproduce this issue. Thanks!

**Comment by SolarLune** [comment]
Hello~

It seems like something might have gotten broken or reverted in between the last commit that worked with gamepads successfully and master? As of master, or `v2.2.0-alpha-13`, I can't start Ebiten with my 8BitDo SN30 Pro+ controller connected. However, I can prior to this commit: https://github.com/hajimehoshi/ebiten/commit/93a156a718609007533c9ba7401b0d85addf6dab

While I don't have the same controller as @TeddyDD, these two issues might be related. Perhaps something was changed that causes this issue to re-arise? For clarification, my issue is the same as the one that you resolved earlier in July, where [starting Ebiten with controllers connected causes a crash](https://github.com/hajimehoshi/ebiten/issues/1229).

**Comment by hajimehoshi** [comment]
OK so probably the issue is in GLFW's button mappings. 93a156a switches the implementation from my original to GLFW's and that's the cause...
