### ISSUE TITLE
Create examples/lifegame

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#182]

**Comment by hajimehoshi** [comment]
Wow, this is awesome! And thank you for saying I can include this into Ebiten. I appreciate your contribution.

BTW, what is the license of gol? README.md says it's MIT but LICENSE says BSD-2 clause.

**Comment by martinlindhe** [comment]
Oh... lol.
I have copy-pasted this license all over my projects, i think i need to fix multiple repositories. Thanks for paying attention. 

It should be MIT license, see https://github.com/martinlindhe/gol/commit/19fa4fa3e2d9978b2b05500d79a9601138d2a7e6

**Comment by hajimehoshi** [comment]
Yeah, license is very important especially when introducing a third party library. I'm glad that to be fixed.

**Comment by martinlindhe** [comment]
:+1:

**Comment by hajimehoshi** [comment]
Added. Please let me know if you find any problems. Thank you very much again.
