### ISSUE TITLE
Regression: invisible window, wrong fullscreen size

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1829]
On my system (Linux/Sway/XWayland), 77664ff0575c8f51e1ba5cd3604a57808fbf95f4 causes a regression:

- Before the commit, Ebiten windows get created on the correct screen and get centered correctly.
- After the commit, I don't get any visible window, and in fullscreen it displays too small in the bottom left corner.

Commenting out the `initializeWindowAfterCreation(window)` in createWindow() fixes it, although I do not yet know why. What the function does looks reasonable to me (other than the window being way too small, 16x16).

Checking with xwininfo reveals that the window actually gets created but outside the visible area of my dual screen setup. Fullscreen oddly uses the wrong size.

I suggest backing out the commit for now, unless it fixes similar issues on other systems. Or maybe have it temporarily controlled by an environment variable until fixed for good?

**Comment by divVerent** [comment]
Monitor setup:

```
$ xrandr
Screen 0: minimum 16 x 16, current 3840 x 1440, maximum 32767 x 32767
XWAYLAND0 connected 1280x720+0+720 (normal left inverted right x axis y axis) 310mm x 170mm
   1280x720      59.86*+
XWAYLAND7 connected 2560x1440+1280+0 (normal left inverted right x axis y axis) 700mm x 400mm
   2560x1440     59.96*+
```

dpi: 96 (i.e. 1:1 mapping, device scale is 1 and should be)

**Comment by divVerent** [comment]
`examples/fullscreen/main.go` reproduces the fullscreen issue (creates window on my right monitor, while using size of my left monitor).

**Comment by divVerent** [comment]
Does NOT repro with `examples/windowsize/main.go`.

DOES repro once I add `ebiten.SetRunnableOnUnfocused(false)` right above the "minw, minh, ..." line.

Don't yet know why.

**Comment by divVerent** [comment]
If I defer `ebiten.SetRunnableOnUnfocused(false)` to the first frame in my game, window size is fixed; fullscreen remains broken.

**Comment by hajimehoshi** [comment]
Thank you for reporting! The commit 77664ff0575c8f51e1ba5cd3604a57808fbf95f4 is needed to put the initial window on a correct monitor instead of the primary monitor. I'll take a look but probably I cannot reproduce this issue.

**Comment by divVerent** [comment]
Well, for me the initial window ends up on the correct monitor (the one with focus) without that commit; but of course this is likely due to a difference in window management.

Will later test using i3, but for now I am on XWayland/Sway.

**Comment by divVerent** [comment]
Also, don't yet know why the window would be entirely invisible with the bug. It does seem mapped, yet I can't find or switch to it.

**Comment by hajimehoshi** [comment]
With Cinnamon, the primary monitor was always used without the fix.

**Comment by divVerent** [comment]
```
     0x100001e "Window Size (Ebiten Demo)": ("glfw-application" "GLFW-Application")  480x360+400+840  +400+840
```

So the range is 400..880 for x and 840..1200 for y.

My left monitor spans 0..1280 for x and 720..1440 for y. My right monitor spans 1280..3840 for x and 0..1440 for y.

So I do not understand yet - the window should be intersecting with the left monitor, yet I don't see it.

**Comment by divVerent** [comment]
Anyway, as observed before, the fullscreen issue is probably rather easy to explain - we don't get the monitor we expect. A fix would thus be explicitly requesting the "expected" monitor from GLFW when fullscreening, i.e. query the monitor of the window then set it explicitly before going fullscreen.

The window mode issue is more peculiar.

**Comment by divVerent** [comment]
In any case, if we can't fully fix this, can we at least have an environment variable to toggle behavior?

Anyway, have an idea why SetRunnableOnUnfocused would even change anything here?

**Comment by hajimehoshi** [comment]
SetRunnableOnUnfocused doesn't invoke any GLFW functions so that's very odd...

**Comment by hajimehoshi** [comment]
```
func initializeWindowAfterCreation(w *glfw.Window) {
        // Show the window once before getting the position of the window.                                                                                                                                                                                                            
        // On Linux/Unix, the window position is not reliable before showing.                                                                                                                                                                                                         
        w.Show()
        w.Hide()
}
```

So, how is the window position changed before `Show`, before `Hide` and after `Hide`?

**Comment by divVerent** [comment]
Not sure yet how to find that.

I did notice that commenting out the w.Hide() call already fixes everything for me.

Hm.

**Comment by hajimehoshi** [comment]
`w.GetPos()` should return the position.

**Comment by divVerent** [comment]
It's 0, 0 after each.

What if Show()/Hide() simply don't wait till the window manager actually applies the change (you then get a ConfigureNotify)?

**Comment by hajimehoshi** [comment]
I don't know how these function works asyncly or not.

So would removing `Hide()` fix your issue? I think that's fine.

**Comment by hajimehoshi** [comment]
Or if time matters, I want to know a proper way to sync the state. time.Sleep would be too hacky.

**Comment by divVerent** [comment]
I am currently looking at xtrace output.

Yes, it appears that removing the Hide() is at least a temporary workaround that works for me. Don't know why yet, though.

In the trace, I see the first difference after the UnmapWindow call from the Hide() as follows:

Without hiding:

```
000:<:007d: 16: Request(40): TranslateCoordinates src-window=0x00c00007 dst-window=0x00000525 src-x=0 src-y=0
000:>:007d:32: Reply to TranslateCoordinates: same-screen=true(0x01) child=0x00c00007 dst-x=0 dst-y=0
```

With hiding:

```
000:<:007d:  8: Request(10): UnmapWindow window=0x00c00007
000:<:007e: 16: Request(40): TranslateCoordinates src-window=0x00c00007 dst-window=0x00000525 src-x=0 src-y=0
000:>:007e: Event UnmapNotify(18) event=0x00c00007 window=0x00c00007 from-configure=false(0x00)
000:>:007e:32: Reply to TranslateCoordinates: same-screen=true(0x01) child=None(0x00000000) dst-x=0 dst-y=0
```

However, this difference _seems_ harmless to me - both returned 0, 0.

**Comment by hajimehoshi** [comment]
My guess is that the window position might be broken a while after this function is called and the window is hidden. That's interesting.

What's the value of `w.GetPos()` at `currentMonitor`?

**Comment by divVerent** [comment]
First of all, it seems like TranslateCoordinates starts "working" as soon as we receive a ConfigureNotify event. In the "good" path, the window starts out as 16x16, gets reconfigured to 75x50 and finally becomes 480x360. In the "bad" path, it only gets notified once for 480x360.

**Comment by divVerent** [comment]
When broken, w.GetPos() returns 0 0 in the first 8 calls to currentMonitor().

When good, w.GetPos() returns 0 0  in the first 5 calls, then 2320 528 every time.

**Comment by hajimehoshi** [comment]
What is 'good' and 'broken' here? Is the behavior flaky?

**Comment by divVerent** [comment]
With and without the Hide call.

**Comment by hajimehoshi** [comment]
Or, maybe, is this a better solution in addition to remove Hide?

```
func initializeWindowAfterCreation(w *glfw.Window) {
        // Show the window once before getting the position of the window.                          
        // On Linux/Unix, the window position is not reliable before showing.
        w.Show()

        // Hiding the window makes the position unreliable again. Do not call w.Hide() here (#1829)

        // Wait until the position is reliable.
        for i := 0; i < 10; i++ {
          x, y := w.GetPos()
          if x != 0 || y != 0 {
            break
          }
          time.Sleep(time.Millisecond)
        }
}
```

**Comment by divVerent** [comment]
Lifecycle differences of the window 0x00c001e (the one that matters):

"Good" (not hiding): mapped in request 0x0109, unmapped only at exit.

"Bad" (hiding): mapped in request 0x010a, unmapped in request 0x010e, mapped in request 0x0146.

First TranslateCoordinates that in the good case gets the proper position is 0x0131 - specifically during the phase where the window would be hidden.

So I think I figured this out. While unmapped, a window manager does not position a window. XMapWindow doesn't actually "do" much, but it requests the window manager to actually place the window (and the client, if it cares about the position, then has to wait for that to happen, which will be confirmed by a sequence of MapNotify and ConfigureNotify events).

Now TBH I do not know how a client _should_ wait for a Map request to "finish", i.e. when it is safe to query its position - but so much is for sure:

- MapRequest is what ultimately directs the window manager to position the window. Client receives MapNotify eventually, BUT the mapping may not be done yet as it's not the WM sending this but the X server!
- Window managers tend to not assign unmapped windows to screens. As observed here.
- ConfigureNotify is how you know you've been positioned, BUT a window manager may never do that.
- Window managers however do usually intercept XConfigureWindow requests so they can influence window placement, and that will reliably give you a ConfigureNotify back. WMs tend to just forward ConfigureRequests to the X server while a window is not mapped (as seen here).

Sadly this means there's no "perfect" sequence, however given Ebiten already starts out with a "wrong" size and then resizes, Ebiten can just wait for the ConfigureNotify indicating the window has been placed.

As for waiting till GetPos returns nonzero, this actually seems wrong - if the window isn't mapped, there's no guarantee, and it also may just spawn at the origin.

I'll look in GLFW source what is there to wait for a proper position.

**Comment by divVerent** [comment]
Okay, this is... sad. GLFW is entirely async there and nowhere _waits- for a ConfigureNotify directly.

However, ConfigureNotify calls _glfwInputWindowSize and/or _glfwInputWindowPos (in THAT order), but ONLY if anything changed.

In other words, it's kinda sad, so polling GetPos() may actually be right, due to GLFW not providing a better mechanism.

GLFW however _does_ wait for the VisibilityNotify event when showing a window; for setting window position or size, there is NOTHING it waits for.

**Comment by divVerent** [comment]
BTW with the waiting added, I still get 5 times 0, 0 and then the correct window pos.

**Comment by divVerent** [comment]
Of course the GetPos() calls actually spam XTranslateCoordinates requests. Should be rather harmless though, if it's just 16 times.

**Comment by hajimehoshi** [comment]
Aha, that's a good information. So probably 

```
func initializeWindowAfterCreation(w *glfw.Window) {
        // Show the window once before getting the position of the window.                          
        // On Linux/Unix, the window position is not reliable before showing.
        w.Show()

        // Hiding the window makes the position unreliable again. Do not call w.Hide() here (#1829)

        // Call GetPos until the position is reliable.
        // GLFW doesn't provide any mechanism to sync the X client and server states.
        // By spamming XTranslateCoordinates requests, we can get the correct position (#1829).
        for i := 0; i < 10; i++ {
                if x, y := w.GetPos(); x != 0 || y != 0 {
                        break
                }
        }
}
```

**Comment by divVerent** [comment]
Yeah. I still am trying to figure out why we get 0, 0 the first few calls. This seems wrong.

**Comment by hajimehoshi** [comment]
OK I'll wait for your investigation. Thank you for the investigation every time!

**Comment by divVerent** [comment]
The second one:

* Created as 16x16.
* Translating fails.
* Then it changes properties WM_NORMAL_HINTS of type WM_SIZE_HINTS with PWinGravity, PMinSize, PMaxSize set.
* Then calls ConfigureWindow.
* Then sets WM_NAME, WM_ICON_NAME, WM_CLIENT_MACHINE, WM_LOCALE_NAME, _NET_WM_NAME, _NET_WM_ICON_NAME.
* Then TranslateCoordinates starts working.

In comparison, the "bad" window never calls ConfigureWindow, but does set WM_SIZE_HINTS with PWinGravity set.

This makes no sense.

**Comment by divVerent** [comment]
Explicitly doing w.SetSize(400, 300) before or after showing does NOT change the result. We still don't get positioned. Why?!?

**Comment by divVerent** [comment]
So...

it appears like calling SetPos() right after Show() makes sure I always get sensible coordinates. If I don't call SetPos(), I only get sensible coordinates much later.

However this makes no sense, as according to my trace we also get the WM to place the window properly before that.

Hm... what if our problem is actually a lack of flushing?

**Comment by divVerent** [comment]
Nah, then SetSize() would have worked too, but it doesn't.

One difference between SetPos() and SetSize() is that SetPos() may also call XSetWMNormalHints() - except that it actually does not as the trigger code path for that is not run. So the delta is really the XMoveWIndow call and what Sway does with it.

Sorry, I cannot investigate further today - will see tomorrow if I find anything.

**Comment by divVerent** [comment]
Tried on i3 now - issue does NOT happen on i3.

So I'd say, for now let's just remove the Hide() call and document it as a workaround for XWayland and/or Sway - but right now it doesn't really make any sense. Nevertheless removing the Hide() call seems appropriate given the two use cases of this:

- The window created by init() gets destroyed soon after anyway, so this doesn't change much.
- The window created by createWindow() gets resized and shown anyway. Main behavioral difference is that there may be different "glitchy" effects during window creation, but this affects both the create/show/hide/resize/show way (if we leave things as is) and the create/show/resize way (if we remove the Hide).

**Comment by divVerent** [comment]
Given it works for me fine without the loop despite getting 0, 0 the first few times - I guess you can leave that out.
