### ISSUE TITLE
vector: add functions for lines

### ISSUE THREAD

**Issue by dasnellings** [hajimehoshi/ebiten#1843]
I am attempting to generate lines with the vector package in ebiten. My implementation in ebiten results in a rasterized image (top:canvas, bottom:ebiten). 

I am generating the lines using 
```
LineTo(bottomLeft)
LineTo(bottomRight)
LineTo(topRight)
LineTo(topLeft)
LineTo(bottomLeft)
Fill(color)
```
since there is no line width option afaik.

From looking through past issues it seems that the vector package is still in an early state. Is this an issue with my implementation or is this package still a WIP?

<img width="538" alt="canvas" src="https://user-images.githubusercontent.com/37418559/136631840-85912347-f398-42b1-8599-783f4b8c4531.png">
<img width="497" alt="ebiten" src="https://user-images.githubusercontent.com/37418559/136631842-2ac26417-f10d-4b2b-881e-a38be9fe1562.png">

**Comment by hajimehoshi** [comment]
I'm still considering APIs to render strokes.

> since there is no line width option afaik.

Not only a width, we have to consider these attributes

* [A join](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineJoin)
* [A cap](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap)
* [A miter limit](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/miterLimit)

So this is not an easy task, and I'm still not sure what is the nice line APIs for Ebiten.

**Comment by hajimehoshi** [comment]
Here is the example (examples/lines):


https://user-images.githubusercontent.com/16950/195886728-15b3efad-4479-40f7-9ee4-f3049893b38b.mp4
