### ISSUE TITLE
Massive FPS drop from commit d9967c53e50d66dfde7ba5e49badf9de319760ad on RPi 400

### ISSUE THREAD

**Issue by TheMightyGit** [hajimehoshi/ebiten#1861]
Commit https://github.com/hajimehoshi/ebiten/commit/d9967c53e50d66dfde7ba5e49badf9de319760ad drops my FPS to 8 from 60 on a Raspberry Pi 400 (Raspbian, fully updated as of yesterday).

tslocum said in discord "Same on Gentoo Linux fyi" - so this may be a more general Linux audio problem than specific to the RPi?

**Comment by TheMightyGit** [comment]
CPU usage is very low on RPi when this happens (8%), so perhaps this is lock contention rather than overwork?

**Comment by hajimehoshi** [comment]
That's pretty odd. So what if just reverting the change?

**Comment by hajimehoshi** [comment]
OK confirmed this issue with examples/audio

**Comment by TheMightyGit** [comment]
It's not the oto verasion. I tried the faulty commit without the oto change and it still happens. And I tried the working commit with just the code changes and it does happen. The problem is in ebiten.

**Comment by hajimehoshi** [comment]
> It's not the oto version. I tried the faulty commit without the oto change and it still happens. And I tried the working commit with just the code changes and it does happen. The problem is in ebiten.

I've confirmed this fixed on Linux by fixing Oto.

**Comment by TheMightyGit** [comment]
Tested and working on RPi at 60fps. Thank you <3
