### ISSUE TITLE
Drag and drop a file (path)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1868]
https://www.glfw.org/docs/3.4/group__input.html#gab773f0ee0a07cff77a210cea40bc1f6b

**Comment by hajimehoshi** [comment]
Mobiles should support this.

e.g. https://developer.android.com/guide/topics/ui/drag-drop

**Comment by tomlister** [comment]
Should the api be a callback?

Something along the lines of

`SetFileDropCallback`

Or perhaps something that can be captured in the update func.

**Comment by hajimehoshi** [comment]
Good point. I don't like callback-style API, but, it might be odd to have a function returning the file path and check it every frame. Let me think...
