### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by aprchen** [hajimehoshi/ebiten#1878]
system: macos Apple M1  11.5.2 

go: 1.17.2

tag: github.com/hajimehoshi/ebiten/v2 v2.2.2

After running for a period of time, the following error appears, during which the computer is in a hibernation state，
It should be a bug, right?

Code is here : https://github.com/aprchen/tower

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x102a6c090]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).deviceScaleFactor(0x1031b5000, 0x0)
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:702 +0x20
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*Input).update(0x1031b5130, 0x1400009a430, {0x102c09f70, 0x1031bdd80})
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/input.go:308 +0x300
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).update(0x1031b5000)
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:1039 +0x19c
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop.func2()
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:1084 +0x40
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0x14000012010)
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/thread/thread.go:51 +0x7c
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0x1031b5000, {0x102c09f70, 0x1031bdd80})
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/run_notsinglethread.go:60 +0x1e0
github.com/hajimehoshi/ebiten/v2.RunGame({0x102c06c90, 0x140000d4000})
	/Users/cf/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/run.go:160 +0xf4
main.main()
	/Users/cf/work/tower/main.go:371 +0x2f4

**Comment by hajimehoshi** [comment]
Hi, thank you for reporting.

Does this happen even when you sleep your macOS explicitly?

**Comment by aprchen** [comment]
> Hi, thank you for reporting.
> 
> Does this happen even when you sleep your macOS explicitly?

Not sure, it seems to happen accidentally, it only appeared twice in the past few days.

**Comment by hajimehoshi** [comment]
What is "a hibernation state" btw? Is this different from "sleeping"?

**Comment by aprchen** [comment]
It’s the same meaning, the translation software I use

> What is "a hibernation state" btw? Is this different from "sleeping"?

**Comment by aprchen** [comment]
> I couldn't reproduce the issue. Are you using multiple monitors?

Yes

**Comment by hajimehoshi** [comment]
OK I'll try this with multiple monitors later...

**Comment by hajimehoshi** [comment]
I couldn't reproduce this even with another monitor. Is it possible to reproduce this issue in a deterministic way?

**Comment by aprchen** [comment]
Yes, it will definitely appear when the program is running on another monitor

> I couldn't reproduce this even with another monitor. Is it possible to reproduce this issue in a deterministic way?

**Comment by aprchen** [comment]
![image](https://user-images.githubusercontent.com/13740363/142346040-a726d9d0-4b49-4e43-a18a-9d8090340692.png)
I tried to reproduce this error proactively, but it did not reproduce, but when I left the computer for a period of time and turned on the computer, I found that the program had stopped running and the above error appeared, which was very strange. I'm sorry I can't provide some useful information.

**Comment by divVerent** [comment]
It happened to me too, on Linux, when I was not looking and the screen was locked (but no suspend/hibernate). Also only one screen active, although this IS a laptop and it may have temporarily toggled to the internal screen, who knows.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x669834]

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).deviceScaleFactor(0xc0013759f0, 0x38)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:702 +0x14
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).fromGLFWPixel(...)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui_unix.go:126
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).registerWindowSetSizeCallback.func1.1.1()
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:778 +0x8b
github.com/hajimehoshi/ebiten/v2/internal/thread.(*NoopThread).Call(0x0, 0x0)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/thread/thread.go:85 +0x1a
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).registerWindowSetSizeCallback.func1.1()
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:776 +0x12f
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).runOnAnotherThreadFromMainThread(...)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/run_singlethread.go:51
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).registerWindowSetSizeCallback.func1(0x8, 0x334, 0x412)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:769 +0xa6
github.com/hajimehoshi/ebiten/v2/internal/glfw.ToSizeCallback.func1(0x8d73a0, 0xc00005caa0, 0x5fbe0a)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/glfw/callback_notwindows.go:86 +0x53
github.com/go-gl/glfw/v3.3/glfw.goWindowSizeCB(0x4128c6, 0x334, 0x412)
	/home/rpolzer/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/window.go:213 +0x4b
github.com/go-gl/glfw/v3.3/glfw._Cfunc_glfwPollEvents()
	_cgo_gotypes.go:1574 +0x45
github.com/go-gl/glfw/v3.3/glfw.PollEvents()
	/home/rpolzer/go/pkg/mod/github.com/go-gl/glfw/v3.3/glfw@v0.0.0-20211024062804-40e447a793be/window.go:964 +0x17
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents(...)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/glfw/glfw_notwindows.go:325
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).update(0xc0a4a0)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:1047 +0x1ef
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop.func2()
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:1084 +0x38
github.com/hajimehoshi/ebiten/v2/internal/thread.(*NoopThread).Call(0xda89a8, 0xc0088b5290)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/thread/thread.go:85 +0x1a
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).loop(0xc0a4a0)
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/ui.go:1082 +0x1a3
github.com/hajimehoshi/ebiten/v2/internal/uidriver/glfw.(*UserInterface).Run(0xc0a4a0, {0x94e4e8, 0xd570a0})
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/internal/uidriver/glfw/run_singlethread.go:42 +0xdd
github.com/hajimehoshi/ebiten/v2.RunGame({0x949318, 0xc0014ceb40})
	/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.2.2/run.go:160 +0xf9
main.main()
	/home/rpolzer/src/aaaaxy/main.go:52 +0x1b4
```

**Comment by divVerent** [comment]
Line in question:

```
        mx, my := monitor.GetPos()
```

Is monitor maybe nil?

That was called by fromGLFWPixel, which looks harmless; that in turn by:

```
w := int(u.fromGLFWPixel(float64(width), u.currentMonitor()))
```

Can currentMonitor be nil? Don't really see how; it falls back eventually to glfw.GetPrimaryMonitor which would be rather odd if nil.

**Comment by hajimehoshi** [comment]
> Can currentMonitor be nil? Don't really see how; it falls back eventually to glfw.GetPrimaryMonitor which would be rather odd if nil.

Yeah that's the point. So would it be possible that `GetPrimaryMonitor` return nil?

https://www.glfw.org/docs/3.3/group__monitor.html#ga721867d84c6d18d6790d64d2847ca0b1

> The primary monitor, or NULL if no monitors were found or if an error occurred.

Apparently it is in theory possible.

**Comment by divVerent** [comment]
Based on how glfw's callbacks work (
https://github.com/glfw/glfw/blob/575d2971d414ef9f7a47899f44664168537d26c8/src/monitor.c#L116),
it is very much conceivable that e.g. when switching monitors, there's an
intermediate state in which glfwGetPrimaryMonitor returns NULL.

It's just, I never intentionally switched.

So I'd recommend handling that case - could e.g. remember the previous
scale factor and keep using that one if there's currently no monitor?

**Comment by hajimehoshi** [comment]
> So I'd recommend handling that case - could e.g. remember the previous
> scale factor and keep using that one if there's currently no monitor?

Yeah that makes sense, or just `1` might work?

**Comment by divVerent** [comment]
Not sure how safe it is to change the scale factor without changing the
window size - OTOH during these situations it's likely that nobody can see
it anyway, so yeah, 1 may actually be just fine.

**Comment by hajimehoshi** [comment]
@divVerent @aprchen 

Could you try `73bf7a0939784976d61bd555b686cd7af508f252`? Thanks,

**Comment by aprchen** [comment]
> @divVerent @aprchen
> 
> Could you try `73bf7a0939784976d61bd555b686cd7af508f252`? Thanks,

I will try later

**Comment by hajimehoshi** [comment]
friendly ping

**Comment by divVerent** [comment]
I never got the crash again, with or without the fix, but the fix would
obviousy have fixed what my backtrace showed.

I would recommend auditing for other primary monitor uses, though.

**Comment by hajimehoshi** [comment]
> I would recommend auditing for other primary monitor uses, though.

Yeah that makes sense, I'll try to make follow-up changes. 

@aprchen Does the error happens with the latest change?

**Comment by aprchen** [comment]
> > I would recommend auditing for other primary monitor uses, though.
> 
> Yeah that makes sense, I'll try to make follow-up changes.
> 
> @aprchen Does the error happens with the latest change?

It hasn't happened again these days, this fix should be effective, thanks. I love this project, it gives me a lot of fun

**Comment by hajimehoshi** [comment]
Thanks for confirming!
