### ISSUE TITLE
Inappropriate description in docs

### ISSUE THREAD

**Issue by nighca** [hajimehoshi/ebiten#1881]
Hi

Doc page address: https://ebiten.org/documents/gopherjs.html

It says

>  As GopherJS is not actively maintained now, it is recomended to use WebAssembly if possible.

Actually, [GopherJS](https://github.com/gopherjs/gopherjs) is still under maintenance now. You can find it [here](https://github.com/gopherjs/gopherjs#whats-new).

The statement here may cause misunderstanding :)

**Comment by hajimehoshi** [comment]
Thanks, I'll update that soon!
