### ISSUE TITLE
shader: the program freezes in a white screen

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#1898]
```
package main

var Time float
var ScreenSize vec2

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
	vec2(position)
	return position
}
```

When I tried to run my program with the above definition of Kage, it suspends the screen without any error message

**Comment by hajimehoshi** [comment]
This (unexpectedly) worked on macOS w/ OpenGL, and didn't work on macOS w/ Metal. We should cause an error in both cases anyway.

Have you checked that an error is returned at NewShader?
