### ISSUE TITLE
ebiten: add `KeyName`

### ISSUE THREAD

**Issue by eliasdaler** [hajimehoshi/ebiten#1904]
Suppose that I want to make the game display the message "Press "W" to walk forward".
However if the person playing the game has the French layout, I'd like to show "Press "Z" to walk forward" instead (because in AZERTY "Z" is in the same position as "W" on QWERTY)

glfw has [glfwGetKeyName](https://www.glfw.org/docs/3.3/group__input.html#gaeaed62e69c3bd62b7ff8f7b19913ce4f) function to obtain the name of the key, it looks like we can use it for obtaining this mapping for some platforms. 

The interface can be as follows for Ebiten:

```go
func GetLocalizedKeyName(key Key) string { ... }
```

And finally, the end users will be able to do this:
```go
DisplayMessage(fmt.Sprintf("Press %q to walk forward", ebiten.GetLocalizedKeyName(ebiten.KeyW)))
```

**Comment by hajimehoshi** [comment]
@wasedaigo might want this?

**Comment by hajimehoshi** [comment]
https://github.com/go-gl/glfw/blob/a6c407ee30a0/v3.3/glfw/input.go#L444

This would work. Unfortunately I need to (re)implement this for Windows (internal/glfwwin)

**Comment by hajimehoshi** [comment]
Unfortunately there seems no easy porable way to implement this. Let me change the milestone.

**Comment by hajimehoshi** [comment]
Hm, how can I implement this for browsers?

**Comment by hajimehoshi** [comment]
I've implemented `KeyName` for desktops and browsers.

For mobiles, I'll create a separate issue.

For consoles, I don't implement this.
