### ISSUE TITLE
Improved details on setting up an Xcode project for use with whiten mobile

### ISSUE THREAD

**Issue by jacobsalmela** [hajimehoshi/ebiten#1906]
If you provide me a quick and dirty list of the steps needed, I can covert that into a PR.  

I have been trying to follow examples in go-innovation, but the docs on https://ebiten.org/documents/mobile.html#iOS

But it's a bit vague on connecting a UIViewController to a UIView.

**Comment by hajimehoshi** [comment]
As this requires a general knowledge about iOS application development and might change frequently, I hesitate to add more details in the instructions. Have you succeeded to run go-innovation btw?

**Comment by jacobsalmela** [comment]
Yes, I can get go-innovation to run just fine.  You're right in the fact that things change fast with Apple.  Running the latest Xcode, it already does things different than what you have in go-innovation.  I'll play with it some more and would be happy to add my findings.

**Comment by jacobsalmela** [comment]
I was able to get it to work... I'll document some stuff as I go and can contribute if you'd like.

**Comment by hajimehoshi** [comment]
Sure, could you send a PR at ebiten/ebiten.org by editing the HTML under content? Thanks!
