### ISSUE TITLE
enable to custom allocations in Ebiten

### ISSUE THREAD

**Issue by eliasdaler** [hajimehoshi/ebiten#1910]
I was checking out DrawTriangles impl and found this: https://github.com/hajimehoshi/ebiten/blob/57c45a13e4289a9e0ef270a6030540d8ce191e8e/image.go#L359
Is this allocation really necessary? Or can we somehow avoid it by allowing the user to store this slice and then pass it along with other stuff?

I know that this makes interface harder, but maybe we can hide it somehow? Because when I profile memory with a big batch, I get this:
![image](https://user-images.githubusercontent.com/1285136/147304034-b3c008be-9c86-449a-99c9-45fee197dd5f.png)

Looks like this allocation is unnecessary if nothing changes about vertices

One API we can have is something like `VertexBuffer` which will store underlying vertex slice (which `DrawTriangles` now recomputes on each frame when calling `graphics.Vertices`). I see that there's some caching of vertices in implementation, but it still seems to cause unnecessary allocs on each frame.
(**UPD**: my bad, no allocations are done on each frame once the internal slice grows large enough)

So, the interface could be like this:

```go
buf := ebiten.NewVertexBuffer(4) // this will contain the needed slice which `graphics.Vertices` allocates
buf.AddVertex(ebiten.Vertex{...})
...
screen.draw(buf, ...)
```

**Comment by Zyko0** [comment]
This certainly causes an allocation (and a bigger one if there are many vertices required), but from what I read, it only "frees" allocated vertices if they have been unused for a while, and it's only reallocated if more are required.
But once you drew N vertices and need <=N next frames, this doesn't necessarily reallocate "each" frame, right ?

Do you suggest something along these lines ?
```go
type VertexBuffer struct {
	vertices []ebiten.Vertex
	slice []float32 // The one that was previously managed graphics.Vertices(n int)
}

func (vb *VertexBuffer) AddVertex(vertices ebiten.Vertex...) {
	// Also growing vb.slice here instead of /graphics one ?
}
```

Could be nice !

I don't know what else it would imply for ebiten, maybe breaking changes / making ebiten's API more complex for user+maintainer :/

**Comment by eliasdaler** [comment]
> But once you drew N vertices and need <=N next frames, this doesn't necessarily reallocate "each" frame, right ?

Indeed, I've tested and it doesn't allocate more memory once the buffer grows large enough.

> Do you suggest something along these lines ?
Yes. This will also make allocations a lot more predictable - they won't happen during the first draw - they will happen during VertexBuffer setup (which is usually done during resource loading, tile map loading, etc.)

I think that it's not necessary to make breaking changes for this - we just need an additional "overload" for DrawTriangles which will essentially work the same way.

The growing API is indeed an issue, but I don't see another way of resolving this, unless there's some API which will allow us to "preallocate" internal vertex slice (but this solution is not ideal since it's hard to predict how large of a slice you'll need)

**Comment by hajimehoshi** [comment]
> Is this allocation really necessary?

Yes, as we cannot predict exactly when the vectors are actually used. Rendering commands are queued first (`graphicscommand` package) and the vectors might be recorded there. Does this make sense?

**Comment by eliasdaler** [comment]
Yes, I understand now. I'm wondering what you think of giving user a control over how these allocations are performed and provide "allocation-free" overloads.
This example shows that it's possible to let user create vertex buffers manually and not rely on internal ones.

**Comment by hajimehoshi** [comment]
>  I'm wondering what you think of giving user a control over how these allocations are performed and provide "allocation-free" overloads.

I was wondering how a user can control the allocations.

User-control allocations seem very interesting and should be worth considering, but at the same time I don't want to 'expose' the internal implementation in Ebiten. It is risky to expose an allocation details in any forms.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/blob/2b1e9615407726fe7484e2f0813110a810fe4940/uicontext.go#L160

Note that the vertices slice position is reset every frame and the capacity is reused for next frames.

**Comment by eliasdaler** [comment]
> User-control allocations seem very interesting and should be worth considering, but at the same time I don't want to 'expose' the internal implementation in Ebiten. It is risky to expose the allocation details in any forms.

I think that allowing user to allocate memory themselves and not have to rely on Ebiten's internal implementation actually hides a lot of detail. 

This is the way SFML and SDL_Renderer work. They don't allocate unless you tell them to do it. You create buffers/sprites/textures yourself and "Draw" methods don't allocate/batch in background.
Yes, it's a bit more complicated for users (and might have some maintenance cost...), but might be worth it for performance-intensive games. And in WASM you need to optimize a lot.

**Comment by hajimehoshi** [comment]
Enabling a custom allocation sounds interesting, but I'd like to keep this low-priority unless we really think this is needed... Allocations in third party libraries cannot be modified anyway.

**Comment by eliasdaler** [comment]
Sure, it's OK to keep it low-priority. 
And I don't mind allocations of third-party libraries if they can't be avoided. :)

**Comment by hajimehoshi** [comment]
Now the situation should be much changed. I'll close this once, but feel free to reopen this if you think this is still an issue.
