### ISSUE TITLE
internal/shader: support for integer vectors (ivec2, ivec3, and ivec4)

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#1911]
I was wondering if it was possible to provide support for more vector types since scalar types are already handled by Kage ?

I know glsl supports a vector type for each of them:
>Each of the scalar types, including booleans, have 2, 3, and 4-component vector equivalents. The n digit below can be 2, 3, or 4:
>
> * bvecn: a vector of booleans
> * ivecn: a vector of signed integers
> * uvecn: a vector of unsigned integers
> * vecn: a vector of single-precision floating-point numbers
> * dvecn: a vector of double-precision floating-point numbers
>
> Vector values can have the same math operators applied to them that scalar values do. These all perform the component-wise operations on each component. However, in order for these operators to work on vectors, the two vectors must have the same number of components.

**Comment by hajimehoshi** [comment]
Sure, I don't determine the priority but I can do.

**Comment by hajimehoshi** [comment]
This requires a lot of work. Let me defer this to v2.4.0.

**Comment by hajimehoshi** [comment]
I'm working on ivec. bvec would be another issue. I don't support uvec or dvec as WebGL doesn't.

**Comment by hajimehoshi** [comment]
https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf

> vec3(float) // initializes each component of the vec3 with the float
> vec4(ivec4) // makes a vec4 with component-wise conversion
> vec4(mat2) // the vec4 is column 0 followed by column 1

**Comment by hajimehoshi** [comment]
Some vary basic tests didn't pass.
