### ISSUE TITLE
A bug about DeviceScaleFactor

### ISSUE THREAD

**Issue by aprchen** [hajimehoshi/ebiten#1915]
[<video id="video" controls="" preload="none" poster="">
      <source id="mov" src="" type="video/mov">
</videos>](https://user-images.githubusercontent.com/13740363/147462690-9184511f-9e77-4087-84e1-faea8bf572b7.mov)

code :
```
package main

import (
	"fmt"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

type Test struct {
	isHighDPI bool
	c         WindowDragCoordinator
}

func (t *Test) Update() error {
	t.c.Update()
	return nil
}

func (t *Test) Draw(screen *ebiten.Image) {
	return
}

func (t *Test) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	if t.isHighDPI {
		s := ebiten.DeviceScaleFactor()
		return int(s) * outsideWidth, int(s) * outsideHeight
	}
	return outsideWidth, outsideHeight
}

func NewTest() *Test {
	return &Test{}
}

func main() {
	g := NewTest()
	g.isHighDPI = false
	ebiten.SetWindowSize(200, 200)
	err := ebiten.RunGame(g)
	if err != nil {
		fmt.Println(err)
	}
}

type Point struct {
	x, y int
}

type mouse struct {
	current, init Point
}

func (m mouse) String() string {
	return fmt.Sprintf("x %d y %d  fx %d fy %d", m.current.x, m.current.y, m.init.x, m.init.y)
}

func (m mouse) Diff() (dx, dy int) {
	return m.current.x - m.init.x, m.current.y - m.init.y
}

func (m *mouse) SetInitPosition() {
	m.init.x, m.init.y = ebiten.CursorPosition()
}

func (m *mouse) RefreshCurrentPosition() {
	m.current.x, m.current.y = ebiten.CursorPosition()
}

type window struct {
	current, init Point
}

func (w *window) RefreshCurrentPosition() {
	w.current.x, w.current.y = ebiten.WindowPosition()
}

func (w *window) GetSize() (width, height int) {
	return ebiten.WindowSize()
}

func (w *window) SetInitPosition() {
	w.init.x, w.init.y = ebiten.WindowPosition()
}

func (w *window) GetMax() (x, y int) {
	wWidth, wHeight := w.GetSize()
	mx, my := ebiten.ScreenSizeInFullscreen()
	return mx - wWidth, my - wHeight
}

func (w *window) MoveBy(dx, dy int) {
	w.current.x += dx
	w.current.y += dy
	maxX, maxy := w.GetMax()
	if w.current.x < 0 {
		w.current.x = 0
	}
	if w.current.x > maxX {
		w.current.x = maxX
	}
	if w.current.y < 0 {
		w.current.y = 0
	}
	if w.current.y > maxy {
		w.current.y = maxy
	}
	ebiten.SetWindowPosition(w.current.x, w.current.y)
}

type WindowDragCoordinator struct {
	mouse  mouse
	window window
	isHold bool
}

func (c *WindowDragCoordinator) Update() {
	if inpututil.IsMouseButtonJustPressed(ebiten.MouseButtonLeft) {
		c.mouse.SetInitPosition()
		c.window.SetInitPosition()
		c.isHold = true
		return
	}
	if inpututil.IsMouseButtonJustReleased(ebiten.MouseButtonLeft) {
		c.isHold = false
		return
	}
	if !c.isHold {
		return
	}
	c.mouse.RefreshCurrentPosition()
	c.window.RefreshCurrentPosition()
	c.window.MoveBy(c.mouse.Diff())
}

```

**Comment by hajimehoshi** [comment]
Are you using macOS?

**Comment by aprchen** [comment]
> 

yes

**Comment by hajimehoshi** [comment]
I cannot reproduce this. 

* What does `DeviceScaleFactor` return?
* Are you using multiple monitors?

**Comment by hajimehoshi** [comment]
From your code, I don't think this is a bug. Two types of units are mixed:

* `SetWindowPosition` accepts a device-independent pixel that is NOT affected by `DeviceScaleFactor`
* `CursorPosition` returns a logical position that is affected by `DeviceScaleFactor`

So, in hi-DPI mode, you should divide `m.current.x` and `m.current.y` by `DeviceScaleFactor`.

Does this make sense?

**Comment by aprchen** [comment]
I usually use another monitor, but after unplugging the monitor, it still appears.
I hope the following information is useful.

OS: MacBook Pro (13-inch, M1, 2020) Apple M1

DeviceScaleFactor  return 2


> I cannot reproduce this.
> 
> * What does `DeviceScaleFactor` return?
> * Are you using multiple monitors?

**Comment by aprchen** [comment]
Thanks, i'll try right away

> From your code, I don't think this is a bug. Two types of units are mixed:
> 
> * `SetWindowPosition` accepts a device-independent pixel that is NOT affected by `DeviceScaleFactor`
> * `CursorPosition` returns a logical position that is affected by `DeviceScaleFactor`
> 
> So, in hi-DPI mode, you should divide `m.current.x` and `m.current.y` by `DeviceScaleFactor`.
> 
> Does this make sense?

**Comment by aprchen** [comment]
> Thanks, i'll try right away
> 
> > From your code, I don't think this is a bug. Two types of units are mixed:
> > 
> > * `SetWindowPosition` accepts a device-independent pixel that is NOT affected by `DeviceScaleFactor`
> > * `CursorPosition` returns a logical position that is affected by `DeviceScaleFactor`
> > 
> > So, in hi-DPI mode, you should divide `m.current.x` and `m.current.y` by `DeviceScaleFactor`.
> > Does this make sense?

Thanks for telling this, but it didn't work after I tried

```
func (m mouse) DiffWithDeviceScaleFactor(scale float64) (dx, dy int) {
	dx, dy = m.Diff()
	dx /= int(scale)
	dy /= int(scale)
	return
}


....

	if c.isHiDPI {
		c.window.MoveBy(c.mouse.DiffWithDeviceScaleFactor(ebiten.DeviceScaleFactor()))
	} else {
		c.window.MoveBy(c.mouse.Diff())
	}
```

**Comment by aprchen** [comment]
The branch version I use : master
commitId: dd4d2f6aa046

**Comment by hajimehoshi** [comment]
> `c.mouse.DiffWithDeviceScaleFactor(ebiten.DeviceScaleFactor())`

What kind of values are obtained here?

**Comment by aprchen** [comment]
> > `c.mouse.DiffWithDeviceScaleFactor(ebiten.DeviceScaleFactor())`
> 
> What kind of values are obtained here?

Sorry, my fault, I did not assign the c.isHiDPI variable correctly, which caused the logic to not take effect. Now the problem is solved.
Thank you so much again

**Comment by hajimehoshi** [comment]
I'm happy that you have solved the issue!
