### ISSUE TITLE
ebiten: Allow `NewImageFromImage` with an `*ebiten.Image` even before `ebiten.Run`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1917]
Now `NewImageFromImage` with an `*ebiten.Image` before `ebiten.Run` is not allowed as this invokes `At`, which is not allowed before `Run`.

So what about using `DrawImage` instead of `At` in this case?

**Comment by MrWormHole** [comment]
can definitely volunteer on this, 2 solutions I can think of are 

- check before it panics and panic before it with custom message or 
- copying the buffer of image and creating a deep copied ebiten image

I am not fond of both solutions but panic with custom message seems more reasonable, I am looking at sourcegraph usages for this NewImageFromImage function to understand what people were using as std Image interface [sourcegraph usages](https://sourcegraph.com/search?q=context:global+ebiten.NewImageFromImage&patternType=literal)

**Comment by hajimehoshi** [comment]
Hm, we need more discussion. Let me think more.
