### ISSUE TITLE
ebitenmobile compile takes too long

### ISSUE THREAD

**Issue by gongzhxu** [hajimehoshi/ebiten#1919]
compile is too inefficient，is there ways to implement incremental compilation？

**Comment by hajimehoshi** [comment]
Unfortunately this is inevitable so far. I think the main reason is that Oto requires Oboe, which is written in C++.

https://github.com/hajimehoshi/oto/tree/main/internal/oboe

**Comment by jacobsalmela** [comment]
I have noticed it takes a while, too, but it's less of a hinderance when plugged into an automated pipeline.  I just kick it off and look at other code until it's done.

**Comment by hajimehoshi** [comment]
The situation should be fixed by

* https://github.com/golang/go/issues/37902
* https://github.com/golang/go/issues/54770
