### ISSUE TITLE
ebiten: unexpected black edges with `ebiten.SetScreenClearedEveryFrame(false)`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1938]
```go

package main

import "github.com/hajimehoshi/ebiten/v2"
import "image/color"
import "math/rand"

const Size = 128
func main() {
        ebiten.SetScreenClearedEveryFrame(false)
        ebiten.SetWindowSize(Size, Size)
        _ = ebiten.RunGame(&Game{})
}

type Game struct {}
func (self *Game) Layout(int, int) (int, int) { return Size, Size }
func (self *Game) Update() error { return nil }

func (self *Game) Draw(screen *ebiten.Image) {
        if rand.Intn(60) == 0 {
                r := uint8(rand.Intn(256))
                g := uint8(rand.Intn(256))
                b := uint8(rand.Intn(256))
                clr := color.RGBA{ r, g, b, 255 }
                screen.Fill(clr)
        }
}
```

https://gyazo.com/b5b535d885e48d5c880c373b5df7ffe1

**Comment by sedyh** [comment]
Hello, I also have same issue on Linux Mint Cinnamon 20.0 without `ebiten.SetScreenClearedEveryFrame(false)`.

**Comment by hajimehoshi** [comment]
Have you confirmed the latest version of Ebiten?

**Comment by sedyh** [comment]
Yeah, its Ebiten 2.2.4
![image](https://user-images.githubusercontent.com/19890545/149659328-f21251ab-43e1-4960-983a-e6bef90a57f9.png)

**Comment by hajimehoshi** [comment]
I cannot see the black edges from the screenshot... 🤔

**Comment by sedyh** [comment]
![IMG_20220117_134654](https://user-images.githubusercontent.com/19890545/149755731-78c38c25-f9c1-43ed-9a8a-d93c6261c547.jpg)

**Comment by hajimehoshi** [comment]
I read the code and found this could happen in theory, though I cannot reproduce this yet.
