### ISSUE TITLE
ebiten: forbid `RunOnMainThread` before the main loop

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1945]
For example, there is no way to make this case work:

```go
func init() {
  go func() { ebiten.RunOnMainThread() }
}
```

/CC @changkun

**Comment by changkun** [comment]
Is it platform specific? I tested the case on Linux X11, it seems to work.

```
package main

import (
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

func init() {
	go func() {
		ebiten.RunOnMainThread(func() {
			log.Println("called on main")
		})
	}()
}

type Game struct {
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(w, h int) (int, int) {
	return w, h
}

func main() {
	ebiten.SetWindowTitle("runonmain")
	ebiten.RunGame(&Game{})
}
```

**Comment by hajimehoshi** [comment]
> Is it platform specific?

No. There is no guarantee that an arbitrary goroutine runs on the main thread.

In the current implementation, the function is (unexpectedly) called, but on an arbitrary thread.

**Comment by changkun** [comment]
> but on an arbitrary thread.

I suspect this is not true. The RunOnMain block until mainthread is avaliable for executing the given function. The printed goroutine ID seems to suggest that the function is called expectedly:

```
func init() {
	go func() {
		ebiten.RunOnMainThread(func() {
			log.Println("called on: ", GoID())
		})
	}()
}

func GoID() (id uint64) {
	var buf [30]byte
	runtime.Stack(buf[:], false)
	for i := 10; buf[i] != ' '; i++ {
		id = id*10 + uint64(buf[i]&15)
	}
	return id
}
```

```
2022/01/11 08:39:06 called on:  1
```

**Comment by hajimehoshi** [comment]
> I suspect this is not true. The RunOnMain blocks until mainthread is avaliable for executing the given function. The printed goroutine ID seems to suggest that the function is called expectedly:

I see, but this seems an implementation details of the Go runtime.

What about a goroutine in main?

```go
func main() {
  go func() { RunOnMainThread(func() { ... }) }

  ebiten.RunGame(&Game{})
}
```

**Comment by changkun** [comment]
Still behaves the same. It's quite strange that I didn't notice the mainthread is extablished until the RunGame is called. Perhaps need a closer look..

**Comment by hajimehoshi** [comment]
```
func GoID() (id uint64) {
	var buf [30]byte
	runtime.Stack(buf[:], false)
	for i := 10; buf[i] != ' '; i++ {
		id = id*10 + uint64(buf[i]&15)
	}
	return id
}
```

Does this indicate a thread ID instead of a Goroutine ID?

**Comment by hajimehoshi** [comment]
I'd take a thread id with `gettid` for example.

**Comment by changkun** [comment]
> 

The goroutine ID. But as the main goroutine is locked on the main thread, hence that ID also indicates it is on the main thread.

**Comment by hajimehoshi** [comment]
Hmm, I see. So if a for-ever loop happens in the goroutine, is the application frozen?

**Comment by changkun** [comment]
> Hmm, I see. So if a for-ever loop happens in the goroutine, is the application frozen?

That's for sure, a scheduled function must return soon otherwise the entire application can be blocked by that function because other functions will not be scheduled anymore.

**Comment by hajimehoshi** [comment]
So even a goroutine from main uses the same thread, I'm not sure when a different thread is used... `RunOnMainThread` before the main loop just calls the argument and does nothing special, right?

**Comment by changkun** [comment]
> `RunOnMainThread` before the main loop just calls the argument and does nothing special, right?

I am not entirely sure at the moment. That's why I was surprised the thread package sets the thread only when RunGame is called, meaning that 

```
func main() {
  go func() { ebiten.RunOnMainThread(func() { ... }) }()

  ebiten.RunGame(&Game{})
}
```

this call should not be called on the main thread (goroutine==1) whereas the reality prints 1...

**Comment by hajimehoshi** [comment]
Before trying to fix this, let's make the problem clear. I think a different thread should be used for a different goroutine (even with runtime.LockOSThread).

**Comment by changkun** [comment]
> I think a different thread should be used for a different goroutine

I agree with this. Yesterday I looked quickly on how Ebiten was managing the mainthread execution calls. Then I concluded that the problem is the thread package does not really schedule calls but simply call them if the ebiten.RunGame has not been called.

This was fine before exporting the API to public, because internals are not calling graphicscommand.RunOnMain before ebiten.RunGame executes. However, since it is not exported to public, user could call it at any time before giveup the main function's goroutine.

Similarly to what you proposed in #1952, we need a flag to indicate if the ebiten.RunGame is called or not, if so, we could start to run all scheduled calls.

**Comment by changkun** [comment]
I could not figure what should be an expected behavior for this:

```
	go func() {
		ebiten.RunOnMainThread(func() {
			ebiten.SetWindowTitle("runonmain")
		})
	}()
```

The SetWindowTitle already trying to schedule to the mainthread, it we call it nested on the RunOnMainThread, the entire application will lead to deadlock.

**Comment by hajimehoshi** [comment]
> The SetWindowTitle already trying to schedule to the mainthread, if we call it nested on the RunOnMainThread, the entire application will lead to deadlock.

Yeah right... I'll take a look. Unfortunately we might have to revert RunOnMainThread since it can be impossible to use it correctly...

**Comment by hajimehoshi** [comment]
That's unfortunate, as I plan to remove RunOnMainThread since

* This is not portable: RunOnMainThread cannot be implemented on some environments. For example, there is no way to access the main thread when gomobile-build is used.
* This is hard to use: Before the main loop starts, RunOnMainThread can cause dead lock very easily.

**Comment by hajimehoshi** [comment]
> This is not portable: RunOnMainThread cannot be implemented on some environments. For example, there is no way to access the main thread when gomobile-build is used.

Hm, on Android, we can use `app.RunOnJVM`. On iOS, we can use iOS library.

> This is hard to use: Before the main loop starts, RunOnMainThread can cause dead lock very easily.

Probably just panicking should be fine.
