### ISSUE TITLE
ebitenutil: add NewImageFromFileSystem()

### ISSUE THREAD

**Issue by neni** [hajimehoshi/ebiten#1948]
Is it possible to add a function like ebitenutil.NewImageFromFile() for generic FS?
```

// NewImageFromFileSystem loads the file from fs.FS with path and returns ebiten.Image and image.Image.
func NewImageFromFileSystem(fsFs fs.FS, path string) (*ebiten.Image, image.Image, error) {

```
This is compatible with Go 1.15 and allow to use "embed" with Go1.16+.

_PS: Sorry for my previous chaotic PR (and my poor English). Thank all for your revues._

**Comment by hajimehoshi** [comment]
Hi, thank you for your suggestion!

> This is compatible with Go 1.15 and allow to use "embed" with Go1.16+.

I think `io/fs` itself was introduced in Go 1.16. Is this correct?

**Comment by neni** [comment]
You are right, `io/fs` itself was introduced in Go 1.16. Sorry.
As you said before: "Let's do this after Debian's default Go version is 1.16 or newer."

**Comment by hajimehoshi** [comment]
> As you said before: "Let's do this after Debian's default Go version is 1.16 or newer."

Yes. I might change the policy later.

Anyway, let's keep this issue open and revisit this later.

**Comment by hajimehoshi** [comment]
Though io/fs.FS is as of Go 1.16, we can define our own compatible interfaces.

**Comment by hajimehoshi** [comment]
```go
// FS is a compatible interface as io/fs.FS.
type FS interface {
	// Open opens the named file.
	Open(name string) (File, error)
}

// NewImageFromFileSystem create an image from the specified file system.
func NewImageFromFileSystem(fs FS, path string) (*ebiten.Image, image.Image, error) {
	// ....
}
```

**Comment by hajimehoshi** [comment]
The problem is that `File` is still a new interface. Would it be fine to seperate the definition for Go 1.15 and Go 1.16?

**Comment by hajimehoshi** [comment]
`fs_go115.go`

```go
//go:build !go1.16
// +build !go1.16

import (
	"os"
)

// FS is a compatible interface as io/fs.FS.
type FS interface {
	// Open opens the named file.
	Open(name string) (File, error)
}

// File is a compatible interface as io/fs.File
type File interface {
	Stat() (os.FileInfo, error)
	Read([]byte) (int, error)
	Close() error
}

// FileInfo is a compatible interface as io/fs.FileInfo
type FileInfo = os.FileInfo
```

`fs_go116.go`

```go
//go:build go1.16
// +build go1.16

import (
	"io/fs"
)

// FS is a compatible interface as io/fs.FS.
type FS = fs.FS

// File is a compatible interface as io/fs.File
type File = fs.File

// FileInfo is a compatible interface as io/fs.FileInfo
type FileInfo = fs.FileInfo
```

Would this work? 

/CC @raa0121

**Comment by hajimehoshi** [comment]
OK let's give up supporting Go 1.15 and add this API only for Go 1.16+

```go
//go:build go1.16
// +build go1.16

import (
	"io/fs"
)

// NewImageFromFileSystem create an image from the specified file system.
func NewImageFromFileSystem(fs fs.FS, path string) (*ebiten.Image, image.Image, error) {
	// ....
}
```

@raa0121 Thank you for waiting.

**Comment by raa0121** [comment]
I would like to reflect.
