### ISSUE TITLE
Panic when switching to radial blur example

### ISSUE THREAD

**Issue by gabstv** [hajimehoshi/ebiten#1963]
Hello, I encountered a panic when I switch to the radial blur example shader. All other shaders are working fine.

Error:
`35:2: invalid operation: mismatched types vec4 and int`
At:
`./examples/shader`
Built with:
`go build -tags="example"`
Shader:
radial blur (radialblur_go)
OS:
macOS Catalina 10.15.7 (Metal)
Ref: f5edc189e66be4c8cff40859116cd7569f1ac6ca

**Comment by gabstv** [comment]
Apparently, if I change the line:
```
sum /= 10 + 1
```
to
```
sum /= vec4(11.0)
```
Then it works.

**Comment by hajimehoshi** [comment]
Thanks! I'll take a look later...

**Comment by hajimehoshi** [comment]
Confirmed
