### ISSUE TITLE
ebiten: make `UpdateStandardGamepadLayoutMappings` atomic

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#1978]
Getting this error on some last week's gamecontrollerdb mappings:

> 2022/01/31 07:38:36 [ERROR] could not add included gamepad mappings line 1480: gamepaddb: unepxected mapping: ~a1

Note that SDL supports tilde only at the end of a definition:

https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_gamecontroller.c#L859

So this definition is actually invalid - however the issue is that due to this error, Ebiten refuses the entire file. This got introduced in SDL_GameControllerDB 17bf199518f7bc363cc0930cc92691babd8caef4 and fixed in c6d4acd279ab8021df99602712dbad09d1253e04

As a workaround, I made my game resilient to a single line not parsing by sending them one by one to Ebiten:

https://github.com/divVerent/aaaaxy/blob/main/internal/input/gamepad.go#L194

Would be nice if I didn't have to, though :)

**Comment by hajimehoshi** [comment]
Hi,

Sorry but let me confirm: the gamecontrollerdb has already been fixed so that it no longer includes the prefix ~: is this correct? If so, I don't think Ebiten should fix anything, but am I missing something?

**Comment by divVerent** [comment]
The database has been fixed, yes, but syntax errors in its master branch seem common recently. And as I want to ship as current mappings as possible, being resilient to that would be great.

I would recommend changing https://github.com/hajimehoshi/ebiten/blob/v2.2.3/internal/gamepaddb/gamepaddb.go#L494 so that if processLine fails, it remembers the error but continues parsing further lines; then the first error could be returned at the end. Bonus points for including the line number in the error message.

**Comment by divVerent** [comment]
This would BTW match SDL: https://github.com/libsdl-org/SDL/blob/main/src/joystick/SDL_gamecontroller.c#L1632 - it also simply ignores any broken entries but proceeds parsing the next one.

**Comment by hajimehoshi** [comment]
I hesitate to make the API resilient because:

* This might cause unexpected results: some are updated and the others are not and it is hard for the user to expect what will happen.
* This might make the API difficult to use: if the API `UpdateStandardGamepadLayoutMappings` returns an error, how does the user treat the error? Ignoring it? Analyzing it?
* This would break backward compatibility.

**Comment by hajimehoshi** [comment]
So I recommend giving each line as you have already done. The code is very clear and explicit.

**Comment by divVerent** [comment]
> This might cause unexpected results: some are updated and the others are not and it is hard for the user to expect what will happen.

That's already the case - right now, all entries up to the broken one are updated.

> how does the user treat the error? Ignoring it? Analyzing it?

Already the case; depends on the game. If gamepad support is critical, may be worth crashing the game, otherwise, bark and continue.

> This would break backward compatibility.

True, however the behavior is not documented.

So maybe another option is to explicitly document how the function handles errors.

**Comment by hajimehoshi** [comment]
Ah, good point. So I'll make the function atomic: if an error happens, the state should be kept as if the function was not called. And then I'll document this. Does this make sense?

**Comment by divVerent** [comment]
Good idea. That is at least clearer.

**Comment by hajimehoshi** [comment]
Thanks. Probably, your suggestion was to have a detailed error to know what succeeded and what failed, but my concern is that the API would be complicated. Let me go with the way making the API atomic.

**Comment by divVerent** [comment]
Actually I just meant including the failed line number in the error text so that the user knows more about how to debug the error. Not a specific error object that would contain this as a field.

**Comment by hajimehoshi** [comment]
Making a logic based on an error message is very fragile in general. I'd do a specific error struct with fields, if I had to do.

**Comment by divVerent** [comment]
Right - I just thought it would be better to print the syntax error to
stderr with a line number.

Logging to stderr is all I am gonna do with it. And yes, if we both log a
line number, it may look weird, but I am OK with that.
