### ISSUE TITLE
internal/uidriver/glfw: remove an initial dummy window

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#1982]
This is needed to get the initial monitor, but there should be a better way to get the monitor without a dummy window.

This is one of the causes to slow the launching time (#1918).

**Comment by hajimehoshi** [comment]
https://github.com/glfw/glfw/issues/1699#issuecomment-723692566 might work (Thank you, @Zyko0!)

**Comment by hajimehoshi** [comment]
@divVerent Hi, do you know how to get the current cursor position with the X protocol?

With C functions, I think this is available with XQueryPointer, but I don't know how to get it without Cgo. Thanks,

**Comment by hajimehoshi** [comment]
OK I think I found the solution by myself:

```go
func initialMonitorByOS() (*glfw.Monitor, error) {
	xconn, err := xgb.NewConn()
	if err != nil {
		// Assume we're on pure Wayland then.
		return nil, nil
	}
	defer xconn.Close()

	root := xproto.Setup(xconn).DefaultScreen(xconn).Root
	rep, err := xproto.QueryPointer(xconn, root).Reply()
	if err != nil {
		return nil, err
	}
	x, y := int(rep.RootX), int(rep.RootY)

	// Find the monitor including the cursor.
	for _, m := range ensureMonitors() {
		w, h := m.vm.Width, m.vm.Height
		if x >= m.x && x < m.x+w && y >= m.y && y < m.y+h {
			return m.m, nil
		}
	}

	return nil, nil
}
```

**Comment by superloach** [comment]
does Wayland not support detecting an initial monitor?

**Comment by hajimehoshi** [comment]
Not yet so far. I have not tested Wayland very well.

**Comment by divVerent** [comment]
I can confirm this way of detecting pointer position should sort of work;
however with Xwayland it only works while the cursor is above an X window.

Of course, this assumes the window manager will actually place new windows
on the monitor with the mouse cursor, which may or may not be true in
practice (some WMs for X11 have config options for that). It's an okayish
heuristic though.

**Comment by hajimehoshi** [comment]
Thanks for elaborating.

In the current implementation, the primary monitor is adopted as a fallback. This should not be a serious problem though we want to address this in the future.

> Of course, this assumes the window manager will actually place new windows
> on the monitor with the mouse cursor, which may or may not be true in
> practice (some WMs for X11 have config options for that). It's an okayish
> heuristic though.

Yes, and this assumption might not work even on Windows and macOS so the result can be differ from the previous implementation using a temporary window. However, I think this should be a good compromise.

**Comment by divVerent** [comment]
I should add that even the temporary window is not a guarantee. A WM may
e.g. decide where to place a window based on its size (e.g. to prefer
placing in empty space).

So we are just changing one imperfect heuristic to another. Ultimately we
have to allow the window appearing on a different screen to happen.

**Comment by hajimehoshi** [comment]
Acknowledged. Thanks!
