### ISSUE TITLE
Kage: casting a float on a const declaration

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2011]
When casting a const to a float, it produces an error when compiling.

Shader code
```go
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
	const SOME_CONST = float(0.25)

	return vec4(0.)
}
```

Error:
`constant expresion must be a number but not: SOME_CONST`
(also expresion should be expresS*ion)

**Comment by hajimehoshi** [comment]
Confirmed.
