### ISSUE TITLE
feature request: provide existence of standard gamepad button/axis

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2040]
In addition to the existing API to detect whether a standard mapping exists for a gamepad, it'd be nice to also be able to query whether a specific button or axis of the standard mapping actually exists on the given gamepad.

E.g. when connecting a NES-like controller, it'd be nice if Ebiten could somehow tell the game that X and Y buttons do not exist.

My concrete use case is for auto assigning something to the "exit to menu" feature of my game. For now I am assigning this to all center buttons and all shoulder buttons; however I would like to assign this to the shoulder buttons only if there are no center buttons on the pad. Background is that some Android-focused gamepads exist that have no center buttons but are otherwise complete, and thus connecting those to a PC would be rather annoying, See also https://github.com/divVerent/aaaaxy/issues/20 for some lists of gamepads that lack center buttons.

IIRC both on Linux/evdev and in general when using SDL mappings, Ebiten can know this, so this would be a nice feature. In case some platforms do not support this, it would be nice to have this return a tristate (exists, doesn't exist, Ebiten doesn't know - that IIRC can be the case on the web).

**Comment by SolarLune** [comment]
Shouldn't it be possible to check the number of buttons on the gamepad and see if it exceeds the index of the standard mapping button you're searching for?

**Comment by divVerent** [comment]
Yeah, sadly there is no defined order of existence priority of gamepad buttons.

The canonical contradiction is, should the start button be ordered before the shoulder buttons or joystick buttons?

- Atari joystick: A.
- NES gamepad: Select, Start, A, B.
- SNES gamepad: Select, Start, A, B, X, Y, ShoulderL, ShoulderR.
- Xbox gamepad: Select, Start, Mode, A, B, X, Y, ShoulderL, ShoulderR, StickL, StickR.

Until here this looks great - every added gamepad just adds buttons. But then there's outliers like this:

- Ouya gamepad: A, B, X, Y, ShoulderL, ShoulderR, StickL, StickR and one touchpad.

Thus there exists no such ordering - e.g. not every gamepad that has a Start button has an X or StickL button, and not every gamepad that has a X or StickL button also has a Start button. This approach MAYBE could have worked before mobile gamepads came along, but it's too late now.

That's why I am asking for an API to detect existence - such as `HasStandardGamepadButton(id GamepadID, button StandardGamepadButton) bool`.

**Comment by hajimehoshi** [comment]
Would [`ebiten.IsStandardGamepadLayoutAvailable`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2#IsStandardGamepadLayoutAvailable) work?

**Comment by hajimehoshi** [comment]
Ah, you want to know availabilities of buttons.

**Comment by divVerent** [comment]
Yeah, as many gamepads report as standard layout but actually only have a subset of its buttons.

**Comment by divVerent** [comment]
The count tells me how many buttons exist, but not which they are.

E.g. I know gamepads that have AB and two center buttons only (NES), but
also some that have the entire standard layout except the center buttons
(Ouya). That is why I need this - to give both a nice mapping.

**Comment by hajimehoshi** [comment]
Do you have any further requests?

**Comment by divVerent** [comment]
No, that is precisely what I needed. Gotta implement use of it still.

Haven't checked source of it but I assume it verifies existence both via
gamepaddb mapping and, if using automatic mapping e.g. for xbox gamepads,
via input event API.
