### ISSUE TITLE
ebiten: support customizing the "screen" shader

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2046]
Forked from #1772

**Comment by hajimehoshi** [comment]
With #1772, what about

```
// DefaultScreenShader is the default shader to render the screen.
var DefaultScreenShader *Shader

// SetScreenShader sets the shader used to render the screen.
// The initial value is DefaultScreenShader.
// If shader is nil, the simplest shader is used.
func SetScreenShader(shader *Shader)

// Deprecated: as of v2.5. Use SetScreenShader(nil) instead.
func SetScreenFilterEnabled(enabled bool)
```

? /CC @divVerent

**Comment by hajimehoshi** [comment]
If there is `SetScreenShader`, don't we need a substitute of `SetScreenFilterEnabled`?

**Comment by hajimehoshi** [comment]
@divVerent Would it be ok to you if `SetScreenFilterEnabled` is deprecated without a simple substitution, but you can specify a shader at `SetScreenShader`?

**Comment by hajimehoshi** [comment]
For the API, I have not deterined how to pass a uniform variable... 🤔

**Comment by divVerent** [comment]
Would work for me; when doing so, please ideally provide an example of a
nearest neighbor shader.

**Comment by divVerent** [comment]
I would be OK without uniforms, given I already use text substitution (and
thus recompiling) in other places to enable/disable optional parts.

Would be nice and more consistent with other shader use though.

**Comment by hajimehoshi** [comment]
Another idea is to add a mode to use the use screen image at Draw instead of an offscreen, so that you can use any regular rendering functions

**Comment by divVerent** [comment]
That would probably fit best in Ebitengine's design, but IIRC you said the problem is that the screen image does not support all a regular Image does.

I could live with that (in video capture mode I would probably need to inject an intermediate image, but I already do that anyway for other reasons).

So I wonder if the real way to do that would be to add a second optional Draw method to Game that takes a ScreenImage that does not have the full Image feature set, and call that instead of Draw if it exists.

**Comment by hajimehoshi** [comment]
> That would probably fit best in Ebitengine's design, but IIRC you said the problem is that the screen image does not support all a regular Image does.

Ah yes, the screen image doesn't work a rendering source so this is different from other regular images. This should work as a rendering target, hopefully.

> So I wonder if the real way to do that would be to add a second optional Draw method to Game that takes a ScreenImage that does not have the full Image feature set, and call that instead of Draw if it exists.

Hmm, this might make things complicated. We cannot change the `Game` interface. It is actually possible to do a hack by casting an interface to check the existence of a new method (`Draw2`, for example) though, but I don't think it worth adding a new separate function so far.

**Comment by hajimehoshi** [comment]
Another restrictoin of the screen image is that it doesn't work with `WritePixels`.

**Comment by divVerent** [comment]
Sounds good; SetScreenFilterEnabled would be fully replaced by
SetScreenShader(nil) or SetScreenShader(DefaultScreenShader).

**Comment by hajimehoshi** [comment]
I think I'll go with `SetScreenShader(nil)` for the default shader as I don't want to add a new exposed variable `DefaultScreenShader`.

**Comment by hajimehoshi** [comment]
On the other hand, if there are use cases of the default shader, it might be fine to expose `DefaultScreenShader`, but are there such use cases?

**Comment by divVerent** [comment]
There is one interesting fact/problem here... normally Ebitengine doesn't actually use the screen shader when downscaling.

When using a custom shader, it'd be nice if the custom shader could be always forced, so one can also e.g. use it for dynamic fullscreen effects in a game.

Yes, there's no API to give them uniforms, which would be really nice for that purpose, but one can still somewhat efficitently for some flashing or similar effects by simply precompiling a few shaders initially and switching the screen shader as needed.

BTW, is switching the shader from Draw() valid and will it apply to this Draw() call?

So basically, my preferred behavior would be:

- If shader is set to nil, use the current logic that dynamically toggles between two shaders, depending on whether upscaling is needed or not.
- If a custom shader is set, the given shader will ALWAYS be used.
- Changing the shader from Draw() is valid.

This BTW speaks strongly against providing the DefaultShader as a global - after all, there is no shader that behaves precisely like default.

As an alternative, a way to _force_ the use of the configured screen shader could be nice. But I'd probably prefer "nil = default, anything else = Ebitengine's toggle logic", as after all, the toggle logic could in theory be implemented in Kage itself (doesn't mean Ebitengine has to).

**Comment by hajimehoshi** [comment]
> There is one interesting fact/problem here... normally Ebitengine doesn't actually use the screen shader when downscaling.
> [...]
> This BTW speaks strongly against providing the DefaultShader as a global - after all, there is no shader that behaves precisely like default.

Ahh, true, so originally it is impossible to represent the current situation by one shader.

> BTW, is switching the shader from Draw() valid and will it apply to this Draw() call?

Yes. So,

> So basically, my preferred behavior would be:
> 
> - If shader is set to nil, use the current logic that dynamically toggles between two shaders, depending on whether upscaling is needed or not.
> - If a custom shader is set, the given shader will ALWAYS be used.
> - Changing the shader from Draw() is valid.

I think this suggestion makes sense.

> As an alternative, a way to force the use of the configured screen shader could be nice. But I'd probably prefer "nil = default, anything else = Ebitengine's toggle logic", as after all, the toggle logic could in theory be implemented in Kage itself (doesn't mean Ebitengine has to).

I don't understand the 'anything else' part. If a shader is specified, the toggle logic is not used in your suggestion, right?

Yet another alternative we have already considered is to add a new optional `Game` function like `ScreenDraw`, whose argument is an `ebiten.Image` for the screen image. The problem is that `ebiten.Image` has a lot of restrictions (e.g. this can be used only as a rendering target of `Draw*` functions). With this, you can implement your own toggle logic by yourself.

**Comment by divVerent** [comment]
Yeah, that is the idea - I was wrong above, I meant nil = Ebiten's toggle logic, anything else = the given shader unconditionally.

Game code can of course implement its own toggle logic by checking window dimensions from Draw() or Layout().

**Comment by hajimehoshi** [comment]
OK I think I'll go with `SetScreenShader` way (nil = the default behavior, non-nil = the specified shader is used in any scales) so far. I'll revisit this tomorrow or later.

**Comment by hajimehoshi** [comment]
> And yeah, I kinda prefer the custom shader over the "special ebiten.Image that doesn't support all ops". Is cleaner, even though slightly less flexible.

What if the screen is given as an interface?

```go
type ScreenImage interface {
    DrawImage(src *ebiten.Image, op *DrawImageOptions)
    DrawTriangles(vertices []Vertex, indices []uint16, img *Image, options *DrawTrianglesOptions)
    DrawRectShader(src *ebiten.Image op *DrawRectShaderOptions)
    DrawTrianglesShader(vertices []Vertex, indices []uint16, shader *Shader, options *DrawTrianglesShaderOptions)
}

type Game interface {
    DrawScreen(screen ScreenImage)
}
```

**Comment by divVerent** [comment]
That would work, but also is a bit odd. I'd rather make it a concrete
opaque struct type with just those methods.

Am Mi., 12. Okt. 2022 um 12:11 Uhr schrieb Hajime Hoshi <
***@***.***>:

**Comment by hajimehoshi** [comment]
It's possible to have a struct, but I don't think there is a strong difference here. I'm fine with both.

The problem of `SetScreenShader` is that we cannot have uniform variables. The default shader used a uniform variable, and I realized it would be useless if we cannot have uniform variables. Now the deafult shader doesn't use uniform variables, but I still believe uniform variables are useful.

**Comment by divVerent** [comment]
Well, we could simply get uniforms by adding a second arg to SetScreenShader, or not?

**Comment by hajimehoshi** [comment]
> Well, we could simply get uniforms by adding a second arg to SetScreenShader, or not?

I don't think it is a good idea. If the variables are changed every frame, is `SetScreenShader` called every frame?

**Comment by divVerent** [comment]
That's what this would mean, yes; and SetScreenShader may internally avoid some work if it notices the shader is the same. Not much different from DrawRectShader.

Also, of course, we can't really change the Game interface - so if a game were to have a custom shader, it'd add an extra method which Ebitengine then would detect via a different interface in addition to Game by a runtime type check. That isn't a big issue though - yes, it'd make the Draw method unused and the Layout method _mostly_ unused (it'd still influence mapping of mouse or touch coordinates, and would dictate the size of the offscreen image passed to DrawScreen that isn't _really_ necessary, but that's it). BTW is passing the offscreen image to DrawScreen even useful? The game could just allocate its own of an arbitrary size when using DrawScreen, and then really just use Layout for pointer coordinate mapping.

The big advantage of the DrawScreen approach is that it can do more than just have a final upscale pass. For example, the final pass could use multiple images as source, which could enable some additional effects at a lower performance cost than now. I have no ideas what to do with this right now, but I do see it as an advantage. And of course, one could use multiple Draw calls right onto the screen image, meaning the final pass can also e.g. combine game content and a status bar, HUD or similar stuff.

**Comment by hajimehoshi** [comment]
> it'd make the Draw method unused

I thought that Draw would be still used with DrawScreen, so Draw would manipulate the offscreen and DrawScreen would manipulate the screen. As long as we aim to replace `SetScreenFilterEnabled`, this should be correct.

So If the user wants an additional effect, this should work, but if the user prioritizes performance, this might be problematic. Is that correct? Even if we go with the `SetScreenFilter` way, the offscreen would be still used.

> Layout method mostly unused

I didn't realize this point. `DrawScreen` could replace `Layout` at the same time!

> The big advantage of the DrawScreen approach is that it can do more than just have a final upscale pass. For example, the final pass could use multiple images as source, which could enable some additional effects at a lower performance cost than now. I have no ideas what to do with this right now, but I do see it as an advantage. And of course, one could use multiple Draw calls right onto the screen image, meaning the final pass can also e.g. combine game content and a status bar, HUD or similar stuff.

Yeah, `DrawScreen` way is more flexible.

**Comment by divVerent** [comment]
On Thu, Oct 13, 2022, 07:30 Hajime Hoshi ***@***.***> wrote:

> it'd make the Draw method unused
>
> I thought that Draw would be still used with DrawScreen, so Draw would
> manipulate the offscreen and DrawScreen would manipulate the screen. As
> long as we aim to replace SetScreenFilterEnabled, this should be correct.
>
> So If the user wants an additional effect, this should work, but if the
> user prioritizes performance, this might be problematic. Is that correct?
> Even if we go with the SetScreenFilter way, the offscreen would be still
> used.
>

Not that problematic - obviously even with what you say, the user can make
an empty Draw function, disable Ebitengine's clearing and do all work from
DrawScreen. The only efficiency loss would be an unused texture. Seems
harmless to me.

Personally I would actually prefer using DrawScreen as an extension like
you suggest and keep using Draw. Makes for cleaner code.

Layout method mostly unused

**Comment by hajimehoshi** [comment]
If you keep using `Draw`, `Layout` is still used to determine the offscreen size, right?

**Comment by divVerent** [comment]
This looks nice - one thing is a bit unfortunate, and that is that the aspect ratio keeping is the game's job. I.e. the game can't just scale the offscreen onto the screen, it should also center it keeping the aspect ratio.

I wonder if the API would be nicer if screen were already a same-aspect subrectangle. Not needed though - but this requirement may be worth documenting, especially as pointer coordinate mapping assumes this too.

**Comment by hajimehoshi** [comment]
Sure, let me consider.

**Comment by hajimehoshi** [comment]
SubImage would not be an option so far. SubImage returns image.Image and a user would mistakenly convert this to `*ebiten.Image`.

> possibly with exporting that scale factor function

By the way, would it be better to enable to adjust inputting (e.g. mouse cursor positions)? Now the scale and the offset is used for adjusting inputtings too.

**Comment by divVerent** [comment]
That would work too, of course - I think I would prefer keeping the current
upscaling approach and keeping input "cooked", i.e. translated to offscreen
coordinates, as well.

Just means we probably should make it easy to implement the letterboxing.
It isn't hard, but it might be ideal to just export the scaling and offset
values, either via function or passing them to the new Draw function.

**Comment by hajimehoshi** [comment]
I think passing the parameters via `DrawFinalScreen` is the best so far. I'll revisit this tomorrow. Thanks!

**Comment by divVerent** [comment]
Maybe in form of a GeoM that would just work for DrawImage and
DrawRectShader?

**Comment by hajimehoshi** [comment]
That makes sense!

**Comment by hajimehoshi** [comment]
OK I've implemented it
