### ISSUE TITLE
[linux] support gamepad standard layout without mapping when mapping is provided by kernel

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2052]
This Xbox gamepad has the following buttons and axes:

```
#     Event code 304 (BTN_SOUTH) = A
#     Event code 305 (BTN_EAST) = B
#     Event code 307 (BTN_NORTH) = Y
#     Event code 308 (BTN_WEST) = X
#     Event code 310 (BTN_TL) = left shoulder button
#     Event code 311 (BTN_TR) = right shoulder button
#     Event code 314 (BTN_SELECT) = left center button
#     Event code 315 (BTN_START) = right center button
#     Event code 316 (BTN_MODE) = middle center button
#     Event code 317 (BTN_THUMBL) = pushing down on left joystick
#     Event code 318 (BTN_THUMBR) = pushing down on right joystick
#     Event code 0 (ABS_X) = left joystick
#     Event code 1 (ABS_Y) = left joystick
#     Event code 2 (ABS_Z) = left trigger
#     Event code 3 (ABS_RX) = right joystick
#     Event code 4 (ABS_RY) = right joystick
#     Event code 5 (ABS_RZ) = right trigger
#     Event code 16 (ABS_HAT0X) = gamepad hat
#     Event code 17 (ABS_HAT0Y) = gamepad hat
```

This smells a lot like a mapping to standard layout - meaning this should be supportable even without a gamecontrollerdb mapping, which would make new devices instantly supported.

**Comment by divVerent** [comment]
To be 100% clear - if both these buttons and axes exist AND a gamepaddb entry exists, Ebiten should prefer the gamepaddb entry. After all, there may be gamepads where this is assigned wrong by the manufacturer.

However, if there is no gamepaddb entry, and a "critical mass" of these is defined (it seems like ABS_X and ABS_Y also have other uses, e.g. for touchpads), Ebiten should offer standard layout.

As for what that "critical mass" could be: I suggest ANY of the BTN_* codes here is enough, and if there are no BTN_* codes above, existence of ABS_HAT0X and ABS_HAT0Y is a strong indicator for a gamepad-ish device too. The other ABS_ axes are also used for non-gamepads, which is kinda sad as this means one can't really autodetect a good old PC joystick and map it to standard layout.

Additionally, existence of any other buttons that aren't in the BTN_GAMEPAD area (e.g. joystick ones, or misc ones) should probably turn off this mapping. Having a BTN_C, BTN_Z, BTN_TL2 or BTN_TR2 is probably OK though, as we know positively that they don't exist in standard layout and thus can't be mapped at all.

**Comment by hajimehoshi** [comment]
I was wondering how SDL solves this.

**Comment by divVerent** [comment]
Here: https://github.com/libsdl-org/SDL/blob/main/src/joystick/linux/SDL_sysjoystick.c#L1617

Apparently, if it has a `BTN_GAMEPAD == BTN_A`, SDL applies standard layout.

This function is reached via the OS-independent wrapper `SDL_PrivateJoystickGetAutoGamepadMapping`, and is called by `SDL_PrivateGetControllerMapping` whenever `SDL_PrivateGetControllerMappingForNameAndGUID` (the gamecontrollerdb lookup) returned no results as a last resort.

Interestingly, SDL defines this _only_ on Linux, even though I am pretty sure Windows also can provide a standard layout in some cases.

**Comment by hajimehoshi** [comment]
> Here: https://github.com/libsdl-org/SDL/blob/main/src/joystick/linux/SDL_sysjoystick.c#L1617

I think the code is already updated. Could you leave a link to a new line number?

**Comment by divVerent** [comment]
https://github.com/libsdl-org/SDL/blob/cfbeb438c102c6fa8291a015af743d8b248e56ef/src/joystick/linux/SDL_sysjoystick.c#L1756

I think this is the place now. Now with Sony specific hacks.

**Comment by hajimehoshi** [comment]
Thanks. There seems a lot of work to improve Linux gamepads, so let me delay the milestone.

**Comment by hajimehoshi** [comment]
Looking https://kernel.org/doc/html/v4.12/input/gamepad.html

**Comment by hajimehoshi** [comment]
https://github.com/torvalds/linux/blob/master/include/uapi/linux/input-event-codes.h#L380-L399

Is `BTN_X` a north button??

**Comment by divVerent** [comment]
As for X north, Y west: I think it uses SNES mappings, based on the naming. However, when I try with my actual gamepad, I find that the X Y A B names are correct and NORTH WEST are swaped while SOUTH EAST are not swapped, as confirmed using evemu-record.
