### ISSUE TITLE
Generics

### ISSUE THREAD

**Issue by w3bb** [hajimehoshi/ebiten#2054]
Games often use float32 instead of float64 for math, and it would be very useful if we could use Ebiten's functions that call for a float with said type without casting. Since 1.18 Go supports generics. There are some useful constraints in golang.org/x/exp/constraints[1], including a generic float type.

[1] https://pkg.go.dev/golang.org/x/exp/constraints

**Comment by hajimehoshi** [comment]
Interesting. What is your concrete suggestion on Ebiten's API?

**Comment by w3bb** [comment]
> Interesting. What is your concrete suggestion on Ebiten's API?

In particular GeoM/ColorM .Apply(), .Scale(), .Skew(), .Translate(), .ChangeHSV() would accept and return Float. There are other parts of the API that might be worth considering that I'm not familiar with. Once (and if) Go implements generic type inference functions like GamepadAxisValue can use generics to make things simpler.

**Comment by hajimehoshi** [comment]
I see. The different thing from the `math` functions is that `GeoM` and `ColorM` has their state as `float32` or `float64`, so explicit conversion of floats would hide the details. I don't think adopting generics for them is a good idea so far... As Ebiten still keeps using Go 1.15 and I don't plan to change this so far, we have a lot of time to discuss :-)

**Comment by MrWormHole** [comment]
@hajimehoshi is there a plan to go for 1.16 or 1.17 due to performance gains of the compiler? I agree, generics is still too early, the tooling like IDEs just breaks frequently, give it 6 months wait then we are talking. I just have seen Jetbrains has fixed 200+ issues related to generics for its IDEs and tooling

**Comment by hajimehoshi** [comment]
@MrWormHole Hi. I'm not sure what you meant by the Go version. You can still use the latest Go whatever Ebiten supports, right?

**Comment by MrWormHole** [comment]
@hajimehoshi yes that's correct but is there a reason to use 1.15 for ebiten?

**Comment by hajimehoshi** [comment]
The reason is that Debian's default Go version is 1.15

**Comment by hajimehoshi** [comment]
There are no concerete action items here. Let's revisit when we find a concerete action item.
