### ISSUE TITLE
inpututil: add a function to get the last touch position just before releasing

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2057]
Requested by @midorimici

**Comment by divVerent** [comment]
Yes! I am currently emulating this myself with some hacky code.

**Comment by hajimehoshi** [comment]
If someone wants to work on this, please discuss what API we want before starting to implement it.

**Comment by hajimehoshi** [comment]
I'm still not sure what API would be the best. What about

```go
func AppendJustReleasedTouchIDs(touchIDs []ebiten.TouchID) []ebiten.TouchID
func TouchJustReleasedPosition(id ebiten.TouchID) (int, int, bool)
```

?

**Comment by hajimehoshi** [comment]
Treating touches as IDs itself seems a not good idea in the first place 🤔
