### ISSUE TITLE
Repeated mouse events seem to tank framerate

### ISSUE THREAD

**Issue by Arc0re** [hajimehoshi/ebiten#2073]
In the most basic program (barebones ebiten really), the framerate drops around 10FPS when moving the mouse cursor fast on the window (shaking the mouse slows the application almost down to a halt), whether we're drawing an image or nothing at all but displaying the framerate with 

```
ebitenutil.DebugPrintAt(screen, fmt.Sprintf("FPS: %f", ebiten.CurrentFPS()), 0, 10)
```

Here is the whole source of the program:
```
package main

import (
	"fmt"
	_ "image/png"
	"os"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

const (
	gameWidth  = 320
	gameHeight = 240
)

type Game struct{}

func (g *Game) Update() error {
	if ebiten.IsKeyPressed(ebiten.KeyEscape) {
		os.Exit(0)
	}

	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ebitenutil.DebugPrintAt(screen, fmt.Sprintf("FPS: %f", ebiten.CurrentFPS()), 0, 10)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return gameWidth, gameHeight
}

func main() {
	ebiten.SetWindowSize(gameWidth*2, gameHeight*2)
	ebiten.SetWindowTitle("Testing Ebiten")
	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}
}

```

I've seen this issue before in SDL2, caused by too much events having to be polled out of the event queue, and there was a way to filter out specific event types (such as mousemove, etc.)
I wonder if it's specific to my setup/config, or GLFW.

I'm on Windows 10.

**Comment by hajimehoshi** [comment]
Hmm, I failed to reproduce the issue (on Parallels). Could you tall me more details about your environment? Thanks,

**Comment by hajimehoshi** [comment]
Now the render thread is separated from the main thread. Does v2.5.0-alpha.11 reproduce your issue?
