### ISSUE TITLE
examples/animation: warnings on Firefox

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2077]
```
WebGL warning: texSubImage: Texture has not been initialized prior to a partial upload, forcing the browser to clear it. This may be slow.
WebGL warning: texSubImage: Tex image TEXTURE_2D level 0 is incurring lazy initialization.
```

This is shown on any examples.

**Comment by christopher-weiss** [comment]
It appears that this warning is just there to warn that WebGL is doing some non-trivial work and is not a problem worth fixing. Here is a fitting Stackoverflow answer to the same issue: https://stackoverflow.com/a/57734917

**Comment by hajimehoshi** [comment]
I see, thanks!
