### ISSUE TITLE
ebiten-imgui doesn't render text correctly after update to v.2.3.0

### ISSUE THREAD

**Issue by eliasdaler** [hajimehoshi/ebiten#2080]
Hello.

I'm not sure if the issue at Ebiten's side of ebiten-imgui's side, but here are my investigation results.

**OS**: Ubuntu 20.04
**Renderer**: OpenGL

How to test.
1. Clone [ebiten-imgui](https://github.com/gabstv/ebiten-imgui)
2. Change Ebiten's version to 2.3.0 in `go.mod`
3. run `go run examples/demowindow/main.go`

How it should look:
![image](https://user-images.githubusercontent.com/1285136/165134862-1313da35-fcb2-4966-bfb9-11da65d7d542.png)
How it looks in 2.3.0:
![image](https://user-images.githubusercontent.com/1285136/165135033-0916b4cb-ffc2-4bbb-b57c-e6948828bbaf.png)

I found exact commit in Ebiten which breaks ebiten-imgui: f2209a0b

Inserting this code:

```glsl
  color.rgb = min(color.rgb, color.a);
```

after [this line](https://github.com/hajimehoshi/ebiten/blob/v2.3.0/internal/graphicsdriver/opengl/defaultshader.go#L274) fixes it, but I'm not sure that it's a proper fix, of course...

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look tomorrow

**Comment by hajimehoshi** [comment]
CC @divVerent

**Comment by divVerent** [comment]
Any idea what ebiten-imgui does special there? The clamping really should not be needed in that case.

I wonder if for some reason the color matrix shader variant isn't activated in this case?

**Comment by divVerent** [comment]
Without having checked for sure, could it be that a texture is used that has any "invalid" pixels, e.g. R:255 G:255 B:255 A:0, which isn't correctly premultiplied? Ebiten assumes all textures are premultiplied-alpha, and in fact, image.Color in Go assumes the same?

**Comment by divVerent** [comment]
FYI this is how I tried fixing this, which works:

```
diff --git a/renderer/render.go b/renderer/render.go
index 912f430..69f2c8f 100644
--- a/renderer/render.go
+++ b/renderer/render.go
@@ -115,6 +115,12 @@ func vmultiply(v, vbuf []ebiten.Vertex, bmin, bmax image.Point) {
 func getTexture(tex *imgui.RGBA32Image) *ebiten.Image {
 	n := tex.Width * tex.Height
 	pix := (*[1 << 28]uint8)(tex.Pixels)[: n*4 : n*4]
+	for i := 0; i < n; i++ {
+		alpha := uint16(pix[4*i+3])
+		pix[4*i] = uint8((uint16(pix[4*i]) * alpha + 127) / 255)
+		pix[4*i+1] = uint8((uint16(pix[4*i+1]) * alpha + 127) / 255)
+		pix[4*i+2] = uint8((uint16(pix[4*i+2]) * alpha + 127) / 255)
+	}
 	img := ebiten.NewImage(tex.Width, tex.Height)
 	img.ReplacePixels(pix)
 	return img
```

With this, things work pixel-perfectly again, and this code makes no visual difference in Ebiten 2.2.

From Ebiten's ReplacePixels docs:

> The given p must represent RGBA pre-multiplied alpha values. len(pix) must equal to 4 * (bounds width) * (bounds height). 

With print-debugging, I found that the pixel values contained a lot of "255 255 255 0" when running the example, so it clearly didn't follow documented requirements.

**Comment by eliasdaler** [comment]
@divVerent thanks, this indeed solves the issue.
Would you like to make a PR in ebiten-imgui? (it's your finding, after all)
If not, I can make a PR myself :)

**Comment by divVerent** [comment]
Sent https://github.com/gabstv/ebiten-imgui/pull/14 to fix this - thanks!

**Comment by hajimehoshi** [comment]
Thank you for the investigation, @divVerent !
