### ISSUE TITLE
Build breakage with osxcross

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2095]
I built just fine using osxcross until two weeks ago - now I am getting this:

```
PATH=/home/rpolzer/src/osxcross-sdk/bin:/home/rpolzer/perl5/bin:/home/rpolzer/src/update-sway/out/bin:/home/rpolzer/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/snap/bin CGO_ENABLED=1 CC=o64-clang CXX=o64-clang++ MACOSX_DEPLOYMENT_TARGET=10.13 go build -o packaging/AAAAXY.app/Contents/MacOS/aaaaxy-darwin-amd64 -tags=embed,ebitensinglethread -gcflags=all=-dwarf=false -ldflags=all=-s -ldflags=all=-w -a -trimpath -buildmode=pie
# github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      _Device_MakeLibrary in _x003.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

No idea yet why - right now looking what it takes to update osxcross.

**Comment by divVerent** [comment]
FYI, using the 11.3 SDK.

**Comment by hajimehoshi** [comment]
Maybe https://github.com/hajimehoshi/ebiten/commit/7409f01b17b95abb17ea4b07f9099e81102aee32 ?

**Comment by divVerent** [comment]
Yes, that is it:

```
int main() {                            
	if (@available(macOS 10.14, iOS 12.0, *)) {
		return 1;
	}
	return 0;
}
```

yields

```
~/src/osxcross-sdk-orig/bin/o64-clang -o foo foo.m
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      _main in foo-1f6af0.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by divVerent** [comment]
Filed https://github.com/tpoechtrager/osxcross/issues/346

This means I must now at least temporary make 10.14 a minimum requirement of my game. Kinda sad that this is just because of a compiler bug.

**Comment by divVerent** [comment]
Oddly setting MACOSX_DEPLOYMENT_TARGET=10.14 works around the upstream build, but doesn't work with Ebiten. Wonder if anything overrides that.

**Comment by divVerent** [comment]
From strace:
```
182159 execve("/home/rpolzer/src/osxcross-sdk/bin/o64-clang", ["/home/rpolzer/src/osxcross-sdk/bin/o64-clang", "-I", "/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.2/internal/graphicsdriver/metal/mtl", "-fPIC", "-arch", "x86_64", "-m64", "-pthread", "-fno-caret-diagnostics", "-Qunused-arguments", "-fmessage-length=0", "-fdebug-prefix-map=/tmp/go-build3962898579/b117=/tmp/go-build", "-gno-record-gcc-switches", "-fno-common", "-I", "/tmp/go-build3962898579/b117/", "-g", "-O2", "-mmacosx-version-min=10.12", "-fdebug-prefix-map=/home/rpolzer/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.3.2=/_/github.com/hajimehoshi/ebiten/v2@v2.3.2", "-o", "/tmp/go-build3962898579/b117/_x003.o", "-c", "mtl_darwin.m"], 0xc000776dc0 /* 83 vars */) = 0
```

So it looks like something's overriding my flags to 10.12.0.

**Comment by divVerent** [comment]
```
internal/graphicsdriver/metal/mtl/mtl_darwin.go:// #cgo !ios CFLAGS: -mmacosx-version-min=10.12
```

WHY, JUST, WHY... this breaks my environment variable overrides :(

Looks like I need to go back to patching Ebiten... :(

**Comment by divVerent** [comment]
Hm... there doesn't seem to be a great way to fix this. Can you maybe add a build tag condition to these lines that is something like `!ebitennomacosxversionmin` that allows me to provide my own?

**Comment by divVerent** [comment]
Hm... there doesn't seem to be a great way to fix this. Can you maybe add a build tag condition to these lines that is something like `!ebitennomacosxversionmin` that allows me to provide my own?

**Comment by hajimehoshi** [comment]
My understanding is that macOS 10.14 is the must due to the version of Metal. Do you really want to specify `-mmacosx-version-min=10.12`?

**Comment by divVerent** [comment]
I don't want to specify 10.12 anywhere - you are doing that.

```
$ git grep macosx-version-min
internal/graphicsdriver/metal/ca/ca_darwin.go:// #cgo !ios CFLAGS: -mmacosx-version-min=10.12
internal/graphicsdriver/metal/graphics_darwin.go:// #cgo !ios CFLAGS: -mmacosx-version-min=10.12
internal/graphicsdriver/metal/mtl/mtl_darwin.go:// #cgo !ios CFLAGS: -mmacosx-version-min=10.12
internal/graphicsdriver/metal/ns/ns_darwin.go:// #cgo !ios CFLAGS: -mmacosx-version-min=10.12
```

**Comment by hajimehoshi** [comment]
Ah I see. I'll try to fix

**Comment by divVerent** [comment]
FYI after this change you no longer need `@available` in the first place.

**Comment by hajimehoshi** [comment]
So was this issue fixed? I think the error message says `___isOSVersionAtLeast` so there is still an issue, but I am not sure

**Comment by divVerent** [comment]
Specifying the min version as 10.14 "fixes" the issue by simply no longer using the `___isOSVersionAtLeast` symbol.

So the toolchain bug remains, but it's no longer being triggered.

**Comment by hajimehoshi** [comment]
OK, there seems nothing I can do more for this issue. Let me close this.
