### ISSUE TITLE
WebAssembly: No getGamepads on Firefox for Android

### ISSUE THREAD

**Issue by Unrud** [hajimehoshi/ebiten#2100]
[Firefox for Android](https://play.google.com/store/apps/details?id=org.mozilla.firefox) doesn't have `navigator.getGamepads`:

```
panic: syscall/js: Value.Call: property getGamepads is not a function, got undefined
```

**Comment by hajimehoshi** [comment]
Thanks, I'll check this, but the API seems available on Firefox Android

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getGamepads

**Comment by hajimehoshi** [comment]
I could not reproduce this. Are you using an old Firefox browser?

**Comment by Unrud** [comment]
> I could not reproduce this. Are you using an old Firefox browser?

I've updated to version 100.3.0 and I still get the same error. Maybe it depends on the Android version or some other environment constraint if the API is available.

When I add the following workaround to the HTML page the program runs fine:

```js
if (!navigator.getGamepads) {
    navigator.getGamepads = () => [];
}
```

**Comment by hajimehoshi** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

I found that `getGamepads` was available only a secure context (HTTP) in Firefox.

So, I can 'fix' this issue by checking the availability and leaving a console log. You can use games only with HTTPS.

**Comment by hajimehoshi** [comment]
Please try `go get github.com/hajimehoshi/ebiten/v2@8d318fc4de868a188b5598efe2591f33d9d5a492`. Thanks

**Comment by Unrud** [comment]
Thank you. That fixed the issue.
