### ISSUE TITLE
internal/atlas: replacing pixels is heavier than Ebitengine v1.x 

### ISSUE THREAD

**Issue by GuillaumeLescure** [hajimehoshi/ebiten#2105]
Hi,

I'm using Ebitengine on a personnal (private) project.
I'm running it on a Manjaro with KDE (Xorg).

Linux : 5.15.41
Go : 1.18.2

I was stuck a long time on version v1.11.3 because there was an issue with high DPI screen (#1774) on my computer.
It's now fix since the v2.2.0-alpha.15 and I decide to upgrade to ebiten/v2 but I still have some issues with the v2.3.2.

The main issue is an high CPU usage when I load a scene that contain a lot of images (~100 smalls images).

With the v1.11.3, the scene takes ~1Go of RAM and has a little CPU usage spike (normal because of the heavy scene).
On my computer, there is a freeze of 2-3 seconds (I considered adding a progress bar one day but if was ok for now).

With the v2.3.2 the takes takes ~1.5Go of RAM (with eratic allocation and deallocation) and a long high CPU usage.
Still on my computer, now, there is a freeze of almost 30s ( :sob: ).

![IssueEbiten](https://user-images.githubusercontent.com/523524/170711618-2ecffa49-62da-44ee-9698-ced678c4f0e2.png)

I cannot make a simple reproducer and I cannot pinpoint the exact commit or version (because of the issue explained above).
I believe it's a regression and it's a blocker for me :disappointed: 

Is the issue known ?

**Comment by hajimehoshi** [comment]
Do you see this issue even with a very simple hello-world example?

Thanks,

**Comment by GuillaumeLescure** [comment]
No I don't see the issue on a light scene (a kind of hello word ^^). The CPU and RAM are low with 10 images (1 is big because of the background).

To reproduce it, I have to pass through 2-3 scenes without any issue.
It's only when I load the heavy scene that the issue occurs.

**Comment by GuillaumeLescure** [comment]
I added screenshots of KSysGuard widgets after my tests.

You can see that on the 1er test (with 2.3.2), one of my CPU is maxed (blue) then the second (orange) just after.
During that time, RAM is weird :confused:

**Comment by hajimehoshi** [comment]
Thanks!

Unfortunately, I couldn't do anything without a (minimal) reproducible case. I'd appreciate if you could make one, but I understand this is difficult as you have already said.

THanks,

**Comment by GuillaumeLescure** [comment]
I think I have a reproducer. I simulate some part on the complete scene in a "short" example.
Maybe it can be simplify to keep the issue but, in doubt, I prefere to give more than less.

[myIssue.tar.gz](https://github.com/hajimehoshi/ebiten/files/8791115/myIssue.tar.gz)
[myIssue2.tar.gz](https://github.com/hajimehoshi/ebiten/files/8791116/myIssue2.tar.gz)

The main idea is to make a scene loading a lot of different images (in the example, it's the same image but I reload it to simulate this).

 - `myIssue` is in 2.3.2
 - `myIssue2` is in 1.12.12
 
 Both should be the same (if I did not make mistake). But we can see a very different CPU and RAM consumption.

I look into it with `go tool pprof http://localhost:6060/debug/pprof/heap` :
 - heapDynamic{version}.png is the result with current code (dynamic means "allocation with function call" in that case)
 - heapStatic{version}.png is the result with commented code (static means "direct allocation" in that case)
 
The "static version" seems to be the same between 2.3.2 and 1.12.12 so it explains why most of usage don't have the issue.
The "dynamic version" differs between 2.3.2 and 1.12.12. I believe it's because of the evolution of Ebiten. Function calls are not the same so I think the issue can be around that.

I hope it helps, if you need more informations, I can try giving them to you :relaxed:

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look later!

**Comment by hajimehoshi** [comment]
Thanks, I think I understand the issue: creating an image and replacing pixels are now heavy in the atlas package. The atlas package creates the 1px border part for one image, and this allocates memories and consumes CPU.

**Comment by GuillaumeLescure** [comment]
I'm happy to help you figure out the issue :smiley: 
Thanks a lot for your time (and the game engine ^^).
Can't wait the v2.4.0 :wink:

**Comment by hajimehoshi** [comment]
This is a note to myself: can we avoid copying pixels by remembering its address? If the same addresses are used before graphics commands are flushed, then the pixels are copied.

**Comment by hajimehoshi** [comment]
Hmm, I read your `main.go` and you called `NewImageFromImage` in `Draw`. You should use `ReplacePixels` instead of `NewImage*`.

**Comment by hajimehoshi** [comment]
> The "static version" seems to be the same between 2.3.2 and 1.12.12 so it explains why most of usage don't have the issue.
> The "dynamic version" differs between 2.3.2 and 1.12.12. I believe it's because of the evolution of Ebiten. Function calls are not the same so I think the issue can be around that.

So, we should use the static version (not generating images every frame) whenever possible.

**Comment by GuillaumeLescure** [comment]
> Hmm, I read your main.go and you called NewImageFromImage in Draw. You should use ReplacePixels instead of NewImage*.

Hum ... I don't understand how I can use ReplacePixels to load a new image. NewImageFromImage allows to load an image from the binary/disk. ReplacePixels allows to replaces pixel in a sub-image. That's not the same purpose.

My example can obviously be optimised in a lot of way, but my purpose was to pinpoint the issue. If you prefere, imagine that evey square is a different new image.

> So, we should use the static version (not generating images every frame) whenever possible.

I agree the static version is better and I use that design when I can, but in some case, I need a more dynamic design. And because it's a regression from 1.12.12 I was pretty sure it can be fixed. I'm suprised you won't fix it.

I agree in that case the draw() function is heavier than in the static version but it's a trade that I'm willing to pay in some case but I was expected the same cost between 1.12.12 and 2.3.2.

**Comment by hajimehoshi** [comment]
> Hum ... I don't understand how I can use ReplacePixels to load a new image. NewImageFromImage allows to load an image from the binary/disk. ReplacePixels allows to replaces pixel in a sub-image. That's not the same purpose.

`NewImage` creates a new image instance and you should not have to call this every frame. You can cache an image an call `ReplacePixels` on the cached image.

> I agree the static version is better and I use that design when I can, but in some case, I need a more dynamic design. And because it's a regression from 1.12.12 I was pretty sure it can be fixed. I'm suprised you won't fix it.

This might be fixable but the fix would not be simple, and again, calling NewImage every frame should be avoided so I don't think it would be worth fixing.
