### ISSUE TITLE
internal/graphicsdriver/directx: crash when creating too many internal textures

### ISSUE THREAD

**Issue by harbdog** [hajimehoshi/ebiten#2109]
I tried to update my project to use the newest 2.3.x version of Ebiten (coming from 2.2.x), however I am getting the following error which crashes out before it can fully load the window, when trying to run on Windows 10:

`directx: ID3D12Device::CreateCommittedResource failed: The parameter is incorrect.`

The weird thing is that the new version works against the older code in the main branch, but I've got a lot of new features I've been working in a feature branch off to the side where it is failing only with the newer versions (`raycast_collision`).

Reproduce steps:

1. Download the Zip from this commit SHA: https://github.com/harbdog/raycaster-go/tree/6e4aa60fd9328d1ff1c6e39c968829035c2ec6d2
2. Download modules: `go mod download`
3. Run to verify works against previous version of Ebiten: `go run raycast.go`
4. Exit the game by holding CTRL key to unlock mouse from window to close it.
5. Update Ebiten: `go get github.com/hajimehoshi/ebiten/v2@v2.3.2`
6. Run again to see error: `go run raycast.go`

**Comment by hajimehoshi** [comment]
Thanks. Could you tell me your graphics card?

**Comment by hajimehoshi** [comment]
And, what about other Ebitengine applications (e.g. Ebitengine examples?)

**Comment by hajimehoshi** [comment]
I couldn't reproduce the issue on Parallels so far.

**Comment by hajimehoshi** [comment]
> The weird thing is that the new version works against the older code in the main branch

So your `main` branch works with v2.3.2, but your `raycast_collision` branch does not, right? Would it be possible to detect which commit was culprit by `git bisect`?

**Comment by harbdog** [comment]
Graphics card is Geforce RTX 3080 on latest drivers, I'll give it a try in the examples and then after that start going through git commits to help narrow down

**Comment by harbdog** [comment]
As expected no issues with the ebitengine examples

**Comment by harbdog** [comment]
Ok so git bisect narrowed down the first bad to this commit:

https://github.com/harbdog/raycaster-go/commit/6e4aa60fd9328d1ff1c6e39c968829035c2ec6d2

**Comment by harbdog** [comment]
I got ebitengine to not crash by reducing that large sprite sheet size to half (9600x150). 

However, a couple new behaviors I noticed with the newer version v2.3.2 (over previous v2.2.7) is that the first several seconds of rendering the game there is a huge hit in FPS/TPS before it smooths out. This video shows what is being experienced:

https://www.youtube.com/watch?v=OB4NICQl37Y


Additionally when I left click to trigger the "projectile" to fire, which is the sprite that comes from the very large sheet in question, it causes massive slowdown until it finally is removed. So it sounds like some regression in handling sub images of very large sprites possibly?

**Comment by hajimehoshi** [comment]
> The main difference I can tell as far as ebitengine is concerned was the addition of an extremely large sprite sheet (2.2MB, 19200x300), which I was planning to optimize by making it smaller anyway so will give that a try.

Yeah, I think that's the cause. What was the exact error message by the way? Is the error message still only `directx: ID3D12Device::CreateCommittedResource failed: The parameter is incorrect.`? If so, I'd have to make the message more user-friendly...

> Additionally when I left click to trigger the "projectile" to fire, which is the sprite that comes from the very large sheet in question, it causes massive slowdown until it finally is removed. 

My guess is that separating the images increased the number of draw calls. You can confirm this with `-tags=ebitendebug`.

Do you really need whole the image at one time? Would it be possible to edit your sprite sheet so that only necessary part are on one sheet?

**Comment by harbdog** [comment]
> > The main difference I can tell as far as ebitengine is concerned was the addition of an extremely large sprite sheet (2.2MB, 19200x300), which I was planning to optimize by making it smaller anyway so will give that a try.
> 
> Yeah, I think that's the cause. What was the exact error message by the way? Is the error message still only `directx: ID3D12Device::CreateCommittedResource failed: The parameter is incorrect.`? If so, I'd have to make the message more user-friendly...
> 

yes that's the only error I got

> > Additionally when I left click to trigger the "projectile" to fire, which is the sprite that comes from the very large sheet in question, it causes massive slowdown until it finally is removed.
> 
> My guess is that separating the images increased the number of draw calls. You can confirm this with `-tags=ebitendebug`.
> 
> Do you really need whole the image at one time? Would it be possible to edit your sprite sheet so that only necessary part are on one sheet?

I could (and should anyway) optimize the sprite used as a projectile, it's only that big because that's the exact size it was from the resource I obtained it from (opengameart.org). But it's in a sheet because it's an animated sprite with multiple frames.

When the animated sprite is loaded from a sheet I pre-generate each frame using subImage and store each in an index array for looping the animation.
https://github.com/harbdog/raycaster-go/blob/raycast_collision/engine/model/sprite.go#L230

**Comment by harbdog** [comment]
Similar performance issues are experienced even after cropping the 19200x300 image (48 frames) down to 1200x150 (only 6 frames). Would you like a separate issue for the performance problems aside from the original crash bug?

**Comment by hajimehoshi** [comment]
Yes, thanks!

**Comment by hajimehoshi** [comment]
> My guess is that separating the images increased the number of draw calls. You can confirm this with -tags=ebitendebug.

So have you executed your game with this build tag?

**Comment by harbdog** [comment]
Here's the log from the crash scenario with ebitendebug build flag:

[crash_ebitendebug_2.3.2.log](https://github.com/hajimehoshi/ebiten/files/8793526/crash_ebitendebug_2.3.2.log)

**Comment by hajimehoshi** [comment]
Thanks!

> [crash_ebitendebug_2.3.2.log](https://github.com/hajimehoshi/ebiten/files/8793526/crash_ebitendebug_2.3.2.log)

Hmm? Were you trying to create a big image (19200px)? This log doesn't say so.

**Comment by hajimehoshi** [comment]
OK so my current guess is that too many (about 279!) internal textures were created. This is unusual. I'll take a look at your program later.

**Comment by hajimehoshi** [comment]
In your program, you create many new images and call `DrawImage` on that. Do you really need to create a new image for each Sprite? (e.g. https://github.com/harbdog/raycaster-go/blob/526d9c27d46bcb81fa40f35efbae70b7b8a68781/engine/raycaster/Sprite.go#L36-L37)? Would it be possible to use the given image without creating a new image?

**Comment by harbdog** [comment]
Opened #2112 for the performance issues so we can continue the discussion over there on that aspect

**Comment by hajimehoshi** [comment]
Thanks!

**Comment by harbdog** [comment]
Setting the environment variable to force opengl resolves crashing issue as well, so crash appears specific to directx on windows

```batch
set EBITEN_GRAPHICS_LIBRARY=opengl
raycaster-go.exe
```

**Comment by hajimehoshi** [comment]
Could you try the latest Ebitengine? The situation might be changed.

**Comment by harbdog** [comment]
@hajimehoshi still getting the same crash with directx even on ebitengine v2.3.5, still works just fine when forcing opengl mode with EBITEN_GRAPHICS_LIBRARY=opengl

The original branch I reported on from my project no longer exists, so I'll update the reproduce steps accordingly from the specific commit SHA it is reproducible with when using that large image sheet.

**Comment by hajimehoshi** [comment]
Thanks.

So probably this is a restriction in the number and size of Direct textures, and there might be nothing we can do... 🤔

**Comment by harbdog** [comment]
I also tried updating to main branch, it gives a bit more in terms of errors in case it helps:

```bash
go get github.com/hajimehoshi/ebiten/v2@main
```

```bash
go run raycast.go
...
panic: atlas: the image being put on an atlas is too big: width: 19200, height: 300

goroutine 885 [running]:
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).allocate(0xc005732ec0, 0x1)
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/atlas/image.go:750 +0x2a5
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).replacePixels(0xc005732ec0, {0xc003fdc000, 0x15f9000, 0x15f9000}, {0x0, 0x0, 0x0})
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/atlas/image.go:517 +0xc7
github.com/hajimehoshi/ebiten/v2/internal/atlas.(*Image).ReplacePixels(0x100000000000000, {0xc003fdc000, 0x30, 0x40}, {0x0, 0x40, 0xc00059ac00})
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/atlas/image.go:503 +0xfc
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).ReplacePixels(0x4f6780, {0xc003fdc000, 0x4b00, 0x12c}, 0xc0000b9d48, 0x4f6c25, 0xc00006ca50, 0x0)
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/buffered/image.go:148 +0x22a
github.com/hajimehoshi/ebiten/v2/internal/buffered.(*Image).ReplacePixels.func1()
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/buffered/image.go:140 +0x39
github.com/hajimehoshi/ebiten/v2/internal/buffered.tryAddDelayedCommand.func1()
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/buffered/command.go:76 +0x1b
github.com/hajimehoshi/ebiten/v2/internal/buffered.flushDelayedCommands()
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/buffered/command.go:35 +0x44
github.com/hajimehoshi/ebiten/v2/internal/buffered.BeginFrame({0x696ff8, 0xc000120f00})
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/buffered/image.go:41 +0x39
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc005732000, {0x696ff8, 0xc000120f00}, 0x1, 0x4090000000000000, 0x4088000000000000, 0xc000e3fe90)
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/ui/context.go:96 +0xcb
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc00572e048, {0x696ff8, 0xc000120f00}, 0xc0003d20c0, 0xc0057340b8, 0xc0001b1860)
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/ui/context.go:65 +0x8e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop(0x871640)
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/ui/ui_glfw.go:1116 +0x23c
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/ui/run_notsinglethread.go:46 +0x13d
created by github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
        C:/Users/harbd/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0-alpha.7.0.20220624164240-0eb2f7642274/internal/ui/run_notsinglethread.go:33 +0x1fd
exit status 2
```

**Comment by hajimehoshi** [comment]
Yeah, I guess that the image size exceeded the maximum of the texture size.

**Comment by harbdog** [comment]
Understood, might be a good idea to add something in the doc about the directx specific limitation, but I'll go ahead and close this since there appears to be nothing you can do.

**Comment by hajimehoshi** [comment]
In general, 19200px width image is too big, whichever you use DirectX or not. If you create one texture atlas, I recommend extending the heights more instead of the width to make the imager closer to a square.
