### ISSUE TITLE
Performance issues after updating to Ebitengine v2.3.x (coming from v2.2.x)

### ISSUE THREAD

**Issue by harbdog** [hajimehoshi/ebiten#2112]
As found from issue #2109, the raycaster-go project has experienced major performance issues on Windows 10 with Geforce RTX 3080 after updating to Ebitengine v2.3.2, where before no issues with performance from v2.2.7. These performance issues remained even after scaling the one massive sprite sheet image from 19200x300 (48 sub image frames) down to 1200x150 (6 sub image frames), indicating it wasn't the only culprit of the performance issues.

https://www.youtube.com/watch?v=OB4NICQl37Y

When the game window first comes up it stutters with low FPS/TPS for a few seconds before seeming to get better. Then when spawning a projectile the low FPS/TPS comes back, after spawning a large number of projectiles it seems to finally catch up and the FPS normalizes.

For comparison purposes, here's a video of the game running on v2.2.7:
https://www.youtube.com/watch?v=4_HTojnDjHw

Here are the ebitendebug logs for before and after udpate to v2.3.2:

[raycaster-go_ebitendebug_2.2.7.log](https://github.com/hajimehoshi/ebiten/files/8793555/raycaster-go_ebitendebug_2.2.7.log)

[raycaster-go_bad_performance_ebitendebug_2.3.2.log](https://github.com/hajimehoshi/ebiten/files/8793556/raycaster-go_bad_performance_ebitendebug_2.3.2.log)

**Comment by harbdog** [comment]
From @hajimehoshi comment in #2109:

> In your program, you create many new images and call `DrawImage` on that. Do you really need to create a new image for each Sprite? (e.g. https://github.com/harbdog/raycaster-go/blob/526d9c27d46bcb81fa40f35efbae70b7b8a68781/engine/raycaster/Sprite.go#L36-L37)? Would it be possible to use the given image without creating a new image?

Possibly with some amount of refactoring, though considering that things worked just fine in v2.2.7 this appears like a regression in terms of performance.

**Comment by hajimehoshi** [comment]
> Possibly with some amount of refactoring, though considering that things worked just fine in v2.2.7 this appears like a regression in terms of performance.

Yes, but there is almost nothing I can do against creating almost 300 internal images... Please consider reducing `NewImage` + `DrawImage`. I believe you don't have to call them in your code.

**Comment by harbdog** [comment]
Thanks I'll go ahead and see what I can do there, I had recently implemented a [map to cache images](https://github.com/harbdog/raycaster-go/blob/2dbf19349cd1f56e5961834d4b6af688a7349d5d/engine/game.go#L219) for [spawning projectiles](https://github.com/harbdog/raycaster-go/blob/2dbf19349cd1f56e5961834d4b6af688a7349d5d/engine/game.go#L838), just had not gotten around to making every sprite use it yet.

**Comment by harbdog** [comment]
> I guess the regression happens due to DirectX. This might work with OpenGL, but I think this is just a coincidence and is still risky.

Setting the environment variable to force opengl also resolves performance issues, so does appear specific to directx on windows

```batch
set EBITEN_GRAPHICS_LIBRARY=opengl
raycaster-go.exe
```

**Comment by harbdog** [comment]
I was able to address the performance issue on directx by refactoring those excess calls to create/draw image, instead storing their sub image Rects and retrieving them later as offsets when raycasting the single pixel wide texture slices that ultimately gets drawn on the canvas.

https://github.com/harbdog/raycaster-go/commit/1390b956a41febd047eac29d3009af4d83c950b9

**Comment by harbdog** [comment]
While I can get the pre-scaled images done easily outside the create sprite funcs, I recall now why I had translation occur during them: it's because depending on the sprite I may need to translate towards the bottom center, center, or top center of the texture unit size (256px) since some images or subImages from sheets are smaller or larger than 256x256 which requires the used of op.GeoMto translate it within that texture unit size. For subImages coming from sprite sheets that's been the only no other way to get the correct image form passed into the raycasting.

There's a way to scale and translate without the use of op.GeoM in the raycasting methods I'm using, but the math and logic for doing it correctly based on dynamic size/scale has eluded me before when I tried it. I'll see if I can take another stab at that.

**Comment by hajimehoshi** [comment]
Thank you for reducing NewImage and confirming the performance is now better with DirectX!

> There's a way to scale and translate without the use of op.GeoM in the raycasting methods I'm using, but the math and logic for doing it correctly based on dynamic size/scale has eluded me before when I tried it. I'll see if I can take another stab at that.

OK, so does this mean there is more improvement on your side?

**Comment by harbdog** [comment]
> Thank you for reducing NewImage and confirming the performance is now better with DirectX!
> 
> > There's a way to scale and translate without the use of op.GeoM in the raycasting methods I'm using, but the math and logic for doing it correctly based on dynamic size/scale has eluded me before when I tried it. I'll see if I can take another stab at that.
> 
> OK, so does this mean there is more improvement on your side?

I'll try again to improve on my side, it's just the much harder way to go about it because it's so much easier to scale and transform an ebiten.Image, I had already spent hours one day trying to figure it out before resorting to the method seen today. All else fails I can just force use of opengl for the moment.

**Comment by hajimehoshi** [comment]
Let me close this. I think this was already solved by your improvement. Thank you for reporting!
