### ISSUE TITLE
Executing `MaximizeWindow` before init fails on DirectX

### ISSUE THREAD

**Issue by Erexo** [hajimehoshi/ebiten#2137]
Calling `ebiten.MaximizeWindow()` before `ebiten.RunGame(...)` produces an internal error `directx: the window handle is not initialized yet` in `graphics_windows.go`. Note that the "before init" logic will actually work and the window will be maximized, but it will fail shortly after.

**Comment by hajimehoshi** [comment]
Thanks. I could confirm this with `go run -tags=example .\examples\windowsize -maximize`
