### ISSUE TITLE
audio: float32-value streams in addition to int16-value streams

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2160]
Fix Oto first.

**Comment by hajimehoshi** [comment]
These exposed API would be affected

```go
package audio

func (c *Context) NewPlayer(src io.Reader) (*Player, error)
func (c *Context) NewPlayerFromBytes(src []byte) (*Player, error)
func NewInfiniteLoop(src io.ReadSeeker, length int64) *InfiniteLoop
func NewInfiniteLoopWithIntro(src io.ReadSeeker, introLength int64, loopLength int64) *InfiniteLoop
```

```go
package mp3

func Decode(context *audio.Context, src io.Reader) (*Stream, error)
func DecodeWithSampleRate(sampleRate int, src io.Reader) (*Stream, error)
func DecodeWithoutResampling(src io.Reader) (*Stream, error)
```

```go
package vorbis

func Decode(context *audio.Context, src io.Reader) (*Stream, error)
func DecodeWithSampleRate(sampleRate int, src io.Reader) (*Stream, error)
func DecodeWithoutResampling(src io.Reader) (*Stream, error)
```

```go
package wav

func Decode(context *audio.Context, src io.Reader) (*Stream, error)
func DecodeWithSampleRate(sampleRate int, src io.Reader) (*Stream, error)
func DecodeWithoutResampling(src io.Reader) (*Stream, error)
```

Adding option arguments to all the above APIs would not be feasiable 🤔

**Comment by hajimehoshi** [comment]
Though it is possible to add an option without breaking compatibility, it is not good to confuse users. Let's postpone this to v3, when we can break compatibility.

**Comment by hajimehoshi** [comment]
I revisited this and realized that changing this at v3 might be too agressive. Users would be hesitated to migrate to v3 if v3 starts to support only floats. Though it is inevitable to add some confusions, what about adding these APIs?

```go
package audio

func (c *Context) NewPlayerF32(src io.Reader) (*Player, error)
func (c *Context) NewPlayerF32FromBytes(src []byte) (*Player, error)
func NewInfiniteLoopF32(src io.ReadSeeker, length int64) *InfiniteLoop
func NewInfiniteLoopWithIntroF32(src io.ReadSeeker, introLength int64, loopLength int64) *InfiniteLoop
```

```go
package mp3

type SteamF32

func DecodeF32(src io.Reader) (*Stream, error)
```

```go
package vorbis

type SteamF32

func DecodeF32(src io.Reader) (*Stream, error)
```

```go
package wav

type SteamF32

func DecodeF32(src io.Reader) (*Stream, error)
```

**Comment by tinne26** [comment]
So, you want to keep *both* formats even for v3, or would you rather switch to only F32 format? Whatever the case, I think that F32 should become the "main" format, in which case creating `audio/v2` may be a more desirable transition path.

**Comment by hajimehoshi** [comment]
I'd like to switch to F32 in the future. I have not determined to keep S16 in v3.

**Comment by hajimehoshi** [comment]
Yeah audio/v2 sounds a good idea.

**Comment by hajimehoshi** [comment]
So, if we create audio/v2, this would be like this. The API seems almost the same, but `io.Reader` treats float32 data instead of int16.

```go
// audio/v2
func Resample(source io.ReadSeeker, size int64, from, to int) io.ReadSeeker

type Context
func CurrentContext() *Context
func NewContext(sampleRate int) *Context
func (c *Context) IsReady() bool
func (c *Context) NewPlayer(src io.Reader) (*Player, error)
func (c *Context) NewPlayerFromBytes(src []byte) *Player
func (c *Context) SampleRate() int

type InfiniteLoop
func NewInfiniteLoop(src io.ReadSeeker, lengthInBytes int64) *InfiniteLoop
func NewInfiniteLoopWithIntro(src io.ReadSeeker, introLengthInBytes int64, loopLengthInBytes int64) *InfiniteLoop
func (i *InfiniteLoop) Read(b []byte) (int, error)
func (i *InfiniteLoop) Seek(offset int64, whence int) (int64, error)

type Player
func (p *Player) Close() error
func (p *Player) IsPlaying() bool
func (p *Player) Pause()
func (p *Player) Play()
func (p *Player) Position() time.Duration
func (p *Player) Rewind() error
func (p *Player) SetBufferSize(bufferSize time.Duration)
func (p *Player) SetPosition(offset time.Duration) error
func (p *Player) SetVolume(volume float64)
func (p *Player) Volume() float64
```

```go
// audio/v2/vorbis
type Stream
func Decode(src io.Reader) (*Stream, error)
func (s *Stream) Length() int64
func (s *Stream) Read(p []byte) (int, error)
func (s *Stream) Seek(offset int64, whence int) (int64, error)
```

```go
// audio/v2/wav
type Stream
func Decode(src io.Reader) (*Stream, error)
func (s *Stream) Length() int64
func (s *Stream) Read(p []byte) (int, error)
func (s *Stream) Seek(offset int64, whence int) (int64, error)
```

**Comment by hajimehoshi** [comment]
Compared to `text/v2`, the API is not drastically changed, so I double it would be worth introducing a new package. Another concern is, `audio.Context` and `audio/v2.Context` cannot coexist, while `text` and `text/v2` are available at the same time (though I don't recomment it).

So, I slightly prefer the first idea (adding *F32 versions to the current packages) https://github.com/hajimehoshi/ebiten/issues/2160#issuecomment-1714185922

**Comment by quasilyte** [comment]
So, do the streams still need to implement a byte-oriented approach anyway?

I don't know about any other streams, but my XM stream operates on float32 values internally, but it needs to pack everything into bytes when Read is called.
https://github.com/quasilyte/xm/blob/966acb9af5982f2163d82fce416d1082a4dca1d2/stream.go#L747

I have to convert float32 into int16 and then put those into a `[]byte`.

```go
func putPCM(buf []byte, left, right uint16) {
	_ = buf[3] // Early bound check
	buf[0] = byte(left)
	buf[1] = byte(left >> 8)
	buf[2] = byte(right)
	buf[3] = byte(right >> 8)
}
```

This is performed for every sample (left+rigth), so if we could "read" into float32 directly it could improve the performance. I can even make a test to tell you how much computation time can be saved by avoiding these conversions.

**Comment by quasilyte** [comment]
Then maybe we can do it like this:

1. All function continue to accept an `io.Reader`
2. Inside these function, there can be a type assertion for the `ReadFloat32` function interface
3. If reader support ReadFloat32, we can use it instead

The question is: how to efficiently use either inside the types that use this reader. It would probably depend on how exactly they're using this `io.Reader`.

Ebitengine already has something like that for LayoutF thing where an interface is checked for another interface.

**Comment by hajimehoshi** [comment]
Yeah maybe this seems to make sense. You can take a benchmark if you want. However, I guess this reading part might not be a performance bottleneck in applications.

**Comment by quasilyte** [comment]
The reading is not a bottleneck, since we're calling Read for a block, but packing all sample bytes is another thing.

**Comment by hajimehoshi** [comment]
So is your suggestion just for implementation easeness?

**Comment by quasilyte** [comment]
Not exactly.
Maybe I made it too ambiguous initially.

What I meant is that around 30% of the work in `Read` is type conversions (float32 -> int16) and writing these int16s to a byte slice. Since pcm generation is ~90% of the run time of my XM stream, we can say that playing an XM music spends 0.3*0.9=0.27 (27%) time in extra bookkeeping. If the underlying library needs float32 anyway, these extra efforts can be avoided.

But since the Read's computations are usually spread across the time (because we don't process the entire track, but rather chunk by chunk) it's hard to tell how much of an impact it might have.

I don't mind if we don't add a new API, I just wanted to make sure that I understood things correctly.
I can't see how the suggested API changes would affect my code otherwise, so maybe it's something that I can skip entirely.

**Comment by hajimehoshi** [comment]
I think I'll go with https://github.com/hajimehoshi/ebiten/issues/2160#issuecomment-1714185922 without creating `audio/v2`. It seems critical that `audio` and `audio/v2` could not coexist.

**Comment by hajimehoshi** [comment]
> You cannot mix frameworks that use audio and audio/v2, for example.

Or, it is possible to make a wrapper to share the same context implementation so that audio and audio/v2 could coexist. In this case, `audio/v2`'s API would be like https://github.com/hajimehoshi/ebiten/issues/2160#issuecomment-1858890782.

**Comment by tinne26** [comment]
Regarding the coexistence issue, can't you simply register a variable on internal and then init it from both packages, panicking if the variable is already set (effectively preventing usage of both packages at the same time)?

**Comment by hajimehoshi** [comment]
> Regarding the coexistence issue, can't you simply register a variable on internal and then init it from both packages, panicking if the variable is already set (effectively preventing usage of both packages at the same time)?

I found these (a context for int16 and a context for float32) can coexist, so we don't have to care.

**Comment by hajimehoshi** [comment]
If we want to mix an existing int16 stream and a new float32 stream, the code would be like these:

```go
// Adding new APIs to the existing audio package

context := audio.NewContext(48000)
p0 := context.NewPlayer(int16Source)
p0.Play()
p1 := context.NewPlayerF32(float32Source)
p1.Play()
```

```
// Adding audio/v2
import (
    "github.com/hajimehoshi/ebiten/v2/audio"
    audiov2 "github.com/hajimehoshi/ebiten/v2/audio/v2"
)

context := audiov2.NewContext(48000)
p0 := audio.CurrentContext().NewPlayer(int16Source) // When a context is created by audio/v2, the same context exists in v1.
p0.Play()
p1 := context.NewPlayer(float32Source)
p1.Play()
```

So, if we migrate int16 streams to float32 streams, the former would be definitely better. On the other hand, if we finish migrating, the latter would be cleaner.

As the latter (audio/v2) code seems tricky, I'll go with former.

**Comment by quasilyte** [comment]
I tried looking at the referenced issues and it seems like the rationale behind it is mostly internals-related.
Is there anything Ebitengine users should be concerned about?

**Comment by hajimehoshi** [comment]
> Is there anything Ebitengine users should be concerned about?

Nothing much to be honest. The benefits are
1. It is slightly easier to modify your audio source
2. You can use other decoders a little more easily if these treat float values (and I think this is common)

**Comment by hajimehoshi** [comment]
I started to think that the benefit might not be big compared to the benefit. So, it might be a good idea to retract F32 APIs and revisit this in v3... 🤔

**Comment by tinne26** [comment]
Aren't we often applying effects to ogg streams by converting f32 to L16 internally in ebitengine, then back from L16 to f32 to work with it and apply the effects, and then back from f32 to L16 to return it to ebitengine? Saying it's only "slightly easier" is kind of an understatement. While once you get it it's true that it's not so difficult, having to work with 4 values for 2 samples instead of 2, and having to understand how Length() and loops and stream values correlate to samples and time is not trivial and **lots of users are confused about it**. So I would actually say that the main point is simplifying the model by not requiring users to understand a non-trivial format, and I think there are also some performance considerations.

**Comment by hajimehoshi** [comment]
> Aren't we often applying effects to ogg streams by converting f32 to L16 internally in ebitengine, then back from L16 to f32 to work with it and apply the effects, and then back from f32 to L16 to return it to ebitengine? 

The Oto layer already uses only f32 so the last conversion doesn't exist. With the new F32 APIs, no conversion happens in theory, which is good for everyone. With the existing APIs and `vorbis.DecodeWithoutResampling`, f32 -> i16 -> f32 conversion happens, which is waste of CPU power.

> I think there are also some performance considerations.

Apparently converting f32 <-> i16 was not a performance bottleneck as far as I know, though the new API should improve some performance.

> It's true that keeping both formats side by side in audio will still be confusing for users though, which is why I was in favor of having audio/v2 separately.

If v1 and v2 could be mixed easily, this would cause another confusion. Also, v2 doesn't improve the API drastically from v1 very much or improve performance very much, so users would have a little motivation to migrate to v2. IMHO v2 should have much improvement at the expense of compatibility break.

**Comment by hajimehoshi** [comment]
If a user generates its own PCM sound (like examples/piano or examples/pcm), they can use the F32 version for a smooth migration for v3 in the future. I think that's one of the reasons why we should have the F32 version of the API now. So now I'm now feeling like I should not retract the change. Sorry for going back and forth.

**Comment by tinne26** [comment]
Don't worry, although I'm of the opinion of "given similarly reasonable alternatives, let's just pick the one that most closely matches the final desired model", I don't have strong arguments against any of the discussed alternatives: I don't think there's anything "wrong" with them. I think we all agree that the main change happening here is *in the model itself*, not the capabilities/features of the audio package, so... it can be hard to make a decision from a purely "technical" perspective.
