### ISSUE TITLE
ebitenutil: add DrawCircle

### ISSUE THREAD

**Issue by tupini07** [hajimehoshi/ebiten#2163]
We have `DrawLine` , we have `DrawRect` , but no `DrawCirlcle`. I think it would be really useful for quick prototyping (and general use).

Is there a specific reason why there isn't a `DrawCircle`?

**Comment by hajimehoshi** [comment]
```
DrawCircle(dst *ebiten.Image, cx, cy, r float64, clr color.Color)
```

would be what we want. This should be easily implemented with the `vector` package.
