### ISSUE TITLE
trying to quit an application from Dock should focus the application

### ISSUE THREAD

**Issue by venning** [hajimehoshi/ebiten#2165]
MacOS 12.4 (My only tested OS.)
Ebiten v2.3.4

(I don't know if this is expected behavior.)

If you set `ebiten.SetRunnableOnUnfocused(false)` and `ebiten.SetWindowClosingHandled(true)` and then focus another window and attempt to close the game with the red X on the title bar without focusing the game, the window will not close until it receives focus again.

This also affects the Dock: right-click and Quit will also not work until it receives focus again (which seems like the bigger issue). Option+right-click to Force Quit works, of course.

Attempting to close it and then focusing the game will cause it to immediately close, as expected.

---

If Ebiten isn't receiving events from the system while `SetRunnableOnUnfocused` is false, I understand how changing this probably wouldn't make sense. But if Ebiten can tell that the system is quitting even while unfocused, it seems like running `Update()` once might make sense. (Perhaps commenting in `ebiten.IsWindowBeingClosed()` that it should be handled in `Update()`.) Unless that's too much, this is a pretty narrow corner case. I'm happy with a Won't Fix.

Test case:

```go
package main

import (
	"errors"

	"github.com/hajimehoshi/ebiten/v2"
)

type Game struct {
}

func (g *Game) Update() error {
	if ebiten.IsWindowBeingClosed() {
		return errors.New("closed")
	}
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 200, 200
}

func main() {
	ebiten.SetRunnableOnUnfocused(false)
	ebiten.SetWindowClosingHandled(true)
	ebiten.SetWindowSize(200, 200)
	ebiten.RunGame(&Game{})
}
```

**Comment by hajimehoshi** [comment]
I think this is a current expected behavior, and `Update` should not be called unless the window is focused. 

A possible fix is to make the window focused when trying to quit. Let me think...
