### ISSUE TITLE
internal/ui: IsKeyPressed() incorrect after fullscreen status change

### ISSUE THREAD

**Issue by venning** [hajimehoshi/ebiten#2183]
When changing the fullscreen status of the game, the list of keys reported by `IsKeyPressed()` (and related functions) does not "forget" the keys that were being pressed when the status change happened.

Meaning, if keys were depressed *during* the status change and then released *after* the status change, Ebiten will still report those keys as being pressed. (Pressing those keys again after releasing them will reset their reported state correctly.)

Using the minimum test case listed below, which can use the `F` key to toggle fullscreen, the following conditions result in incorrect values:

- Press and hold `F` until the fullscreen status changes (very short presses will be fine)
- Press and hold any keys while changing the fullscreen status with `F`
- Press and hold any keys while changing the fullscreen status with the window's native fullscreen button (tested on MacOS)

Minimum test case:

```go
package main

import (
	"fmt"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

type Game struct {
}

func (g *Game) Update() error {
	if inpututil.IsKeyJustPressed(ebiten.KeyF) {
		ebiten.SetFullscreen(!ebiten.IsFullscreen())
	}
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ebitenutil.DebugPrint(screen, fmt.Sprintf("Pressed keys: %v", inpututil.PressedKeys()))
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 1280, 720
}

func main() {
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeOnlyFullscreenEnabled)
	ebiten.SetWindowSize(1280, 720)
	ebiten.SetWindowTitle("Key Test")
	ebiten.RunGame(&Game{})
}
```

(`SetWindowResizingMode()` is not required to reproduce the bug, it just permits testing the native button.)

---

Ebiten v2.3.5
MacBook Pro (Retina, 15-inch, Mid 2015); Intel Iris Pro 1536 MB
MacOS 12.4 (Monterey)

**Comment by hajimehoshi** [comment]
Confirmed. Thank you for reporting this!

**Comment by hajimehoshi** [comment]
So I think GLFW doesn't work well with macOS's fullscreening 🤔

**Comment by venning** [comment]
(I'm trying my best to familiarize myself with Ebiten's codebase. It seemed like it was a GLFW function not returning correctly. Glad to see that might be correct.)

I don't really see this being a big deal, except when you use a key to activate fullscreen. That seems like it would be more of an issue in situations where Ebiten gets used to make a non-game utility.

I use `F` as a shortcut for fullscreening in testing and it took me by surprise when it wouldn't exit fullscreen sometimes, that's all. I don't think I would run into this in production.

**Comment by hajimehoshi** [comment]
> It seemed like it was a GLFW function not returning correctly. Glad to see that might be correct.

Yes. Ebitengines adds some hack to GLFW for the native fullscreen, and there should be some inconsistency there. I'll try to fix this.

**Comment by tinne26** [comment]
https://github.com/hajimehoshi/ebiten/issues/2053 also hinted at this being an issue.

**Comment by hajimehoshi** [comment]
Confirmed that `keyUp` event is not fired when the key is released during the window transition to fullscreen. Hmm, I think this is an issue in GLFW.

**Comment by hajimehoshi** [comment]
Can we use https://developer.apple.com/documentation/coregraphics/1408768-cgeventsourcekeystate?language=objc ?

**Comment by hajimehoshi** [comment]
Note the result of `glfwGetKey` and `CGEventSourceKeyState` are slightly different for some mapped keys. For example, CapsLock can be a control key, but this might be a left control key and a right control key. This depends on APIs.

**Comment by hajimehoshi** [comment]
Perhaps, `CGEventSourceKeyState` doesn't digtinugish left and right control keys...

**Comment by hajimehoshi** [comment]
I think I'll revert the change as 

* The current method cannot treat right modifier keys correctly
* Unpaired `keyup` and `keydown` are very common (especially on browsers) and this is not a serious issue
