### ISSUE TITLE
Allow building with GLES on "non-mobile" OS

### ISSUE THREAD

**Issue by mgord9518** [hajimehoshi/ebiten#2185]
Mobile constraints make it very difficult to compile for Linux gaming handhelds and similar embedded devices. Adding a new build tag such as `gles` should simplify this

**Comment by hajimehoshi** [comment]
Like `EBITEN_DIRECTX`, we can have `EBITEN_OPENGL` environment variable.

**Comment by hajimehoshi** [comment]
Hmm, as this should change the linking libraries, we would have to use build tags.

**Comment by hajimehoshi** [comment]
Duplicated with #292
