### ISSUE TITLE
[directx] Shader compile failure - debugging features would be nice

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2186]
I got this crash on Github Actions:

```
goroutine 1 [running, locked to thread]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.17.11/x64/src/runtime/debug/stack.go:[16](https://github.com/divVerent/aaaaxy/runs/7254679026?check_suite_focus=true#step:8:17) +0x19
github.com/divVerent/aaaaxy/internal/log.Fatalf({0x102811b, 0x1d}, {0xc000459f48, 0x1, 0x1})
	/home/runner/work/aaaaxy/aaaaxy/internal/log/log.go:101 +0x3c
main.main()
	/home/runner/work/aaaaxy/aaaaxy/main.go:106 +0x1d3
2022/07/08 16:02:45.821440 [FATAL] RunGame exited abnormally: directx: D3DCompile failed: D:\134a\134aaaaxy\134aaaaxy\134shader(128,6-[17](https://github.com/divVerent/aaaaxy/runs/7254679026?check_suite_focus=true#step:8:18)): error X30[19](https://github.com/divVerent/aaaaxy/runs/7254679026?check_suite_focus=true#step:8:20): if statement conditional expressions must evaluate to a scalar
	D:\134a\134aaaaxy\134aaaaxy\134shader(132,2-3): error X3000: unrecognized identifier 'l4'
	\000: Unspecified error
```

It'd be nice if I could see what was actually the shader code it compiled the Kage code to. Any way one can see it? It is possible that I can fix or work around this in my shader code if I knew what this actually is. For OpenGL errors of this kind, Ebiten prints the entire compiled GLSL code to the console so one can debug such issues; this however doesn't seem to exist for DirectX?

**Comment by hajimehoshi** [comment]
What shader caused this crash?

> It'd be nice if I could see what was actually the shader code it compiled the Kage code to.

Sure, I'll add a new log for `ebitendebug`.

> Valid Kage code should not be able to generate a type error like this

Yes, so I'd like to know your Kage program

**Comment by divVerent** [comment]
Well, as the message does not tell, I do not yet know which shader. I strongly suspect this one as it is the one I most recently changed:

https://github.com/divVerent/aaaaxy/blob/main/assets/shaders/dither.kage.tmpl

**Comment by hajimehoshi** [comment]
I added a source code in the error message: 3d5031571d05374450da9acc5b0781917e69a238

**Comment by hajimehoshi** [comment]
Comparing vectors also failed in Metal.

**Comment by hajimehoshi** [comment]
Now you can use `==` for vectors. Please take a look at c01821ca5c395dec74d374c5d8713029a5f6acd6

**Comment by divVerent** [comment]
Thanks, this seems right; I will note that I can remove my u.x == 0 && u.y == 0 && u.z == 0 workaround once this fix is out.

**Comment by hajimehoshi** [comment]
Thank you for confirming the fix!

**Comment by divVerent** [comment]
On another note, is it to be expected that my game is 4x slower on Ebiten/DirectX than Ebiten/OpenGL (i.e. 30fps vs 120fps)? This is why I am not enabling DirectX by default yet, but it might be specific to my only machine that has Windows on it. It has an Intel(R) HD Graphics 500 and I did not install any specific drivers, it has whatever comes with Windows.

**Comment by hajimehoshi** [comment]
DirectX is actually slow in some circumstance and this is a know issue (#2034), but 4x slower is not a known issue. Perhaps are you using a warp (software rendering) driver?

**Comment by divVerent** [comment]
With that set I get 5.4fps. Thanks, at least this helps - I had just spent an hour trying to hunt down DirectX SDKs that then failed to install in order to get dxcpl so I can force-enable it. Should have looked in Ebiten source first.

This tells me that warp is not the issue, as otherwise this variable would have changed nothing.

**Comment by divVerent** [comment]
Anyway, this issue here is closed; I guess we don't keep issues open until release? For performance I will open a separate one.

**Comment by hajimehoshi** [comment]
Let's keep this issue closed and discuss the performance issue at the new issues.
