### ISSUE TITLE
Vertices is misspelled as Verticles 

### ISSUE THREAD

**Issue by AdamGlazerMW** [hajimehoshi/ebiten#2194]
https://github.com/hajimehoshi/ebiten/blob/b8367da7e235036e9c1a9834de50a0a604ec69d8/ebitenutil/shapes.go#L73

The plural form of vertex is vertices, so there is an additional `l` in the variable name

**Comment by hajimehoshi** [comment]
It's correct.

https://en.wikipedia.org/wiki/Vertex_(geometry)
