### ISSUE TITLE
crash on Windows 11 when entering the lock screen

### ISSUE THREAD

**Issue by tinne26** [hajimehoshi/ebiten#2234]
When playing a game that uses the mouse and pressing `Ctrl + Alt + Del` to enter the lock screen for Windows, the following error happens:
```
panic: glfwwin: GetCursorPos failed: Access is denied.

goroutine 1 [running, locked to thread]:
github.com/hajimehoshi/ebiten/v2/internal/glfw.(*Window).GetCursorPos(...)
...
```

Other input methods may also suffer from similar issues, haven't tested that.

**Comment by hajimehoshi** [comment]
Thanks, but this was already fixed by https://github.com/hajimehoshi/ebiten/commit/47c65a92aeff143933761b3a9689f13c6c728ad9
