### ISSUE TITLE
ebiten: check `MaximizeWindow` does NOT work on fullscreen

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2240]
I don't know this is possible though...

**Comment by superloach** [comment]
What is the intended behaviour here? Exit fullscreen and maximize? Or do nothing?

**Comment by hajimehoshi** [comment]
When a user calls these functions in this order:

* `SetFullscreen(true)`
* `SetWindowMaximized(true)`
* `SetFullscreen(false)`

the window should be maximized, but currently this does not.

**Comment by superloach** [comment]
Ah, so the Maximized state is not preserved when it is applied during fullscreen

**Comment by hajimehoshi** [comment]
Right. This is tricky, and TBH I'm not sure we really need this feature.

**Comment by hajimehoshi** [comment]
#2546 is not a blocker but #2546 would make this task easier. Let's wait for this.

**Comment by hajimehoshi** [comment]
I changed my mind. Just ignoring `MaximizeWindow` calls on fullscreen is also fine. I have to check the current implementation.

**Comment by hajimehoshi** [comment]
Confirmed.
