### ISSUE TITLE
Audio : Locked to thread

### ISSUE THREAD

**Issue by amazinglySK** [hajimehoshi/ebiten#2251]
OS : Windows
Ebiten : v2 (2.3.7)
Vorbis : v1.0.2

I have been running into an error when I started implementing audio for my game. 
```
panic: EOF

goroutine 1 [running, locked to thread]:
github.com/---/chessgo/pkg/sounds.GetTracks(0xc000069d60?)
        E:/code/chess_go/pkg/sounds/sounds.go:25 +0xf4
github.com/---/chessgo/pkg/board.InitBoard(0xc000054000?, 0x100c000048058?, 0xc00011c180)
        E:/code/chess_go/pkg/board/board.go:104 +0x229
main.main()
        E:/code/chess_go/main.go:41 +0x75
```

Tried going through the documentation and source code, but cannot figure things out. I'm currently creating a new player like so : 

```go
package sounds

import (
        "github.com/hajimehoshi/ebiten/v2/audio"
        "github.com/hajimehoshi/ebiten/v2/audio/vorbis"
        "bytes"
        _ "embed"
)

// go:embed capture.ogg
var CaptureRaw []byte

// go:embed move.ogg
var MoveRaw []byte

func GetTracks(ctx *audio.Context) (*audio.Player){

        s, err := vorbis.Decode(ctx, bytes.NewReader(MoveRaw))
        if err != nil {
                panic(err)
        }
        capture, err := ctx.NewPlayer(s)
        if err != nil {
                panic(err)
        }


        return capture

}
```

And I call this function by simply passing in the reference to the audio context I've created

```go
  // Sounds
        log.Println(actx)
        move:= sounds.GetTracks(actx)
```

But as said previously it runs into some kind of deadlock. Would be great if someone could look into this !

**Comment by hajimehoshi** [comment]
Hi, did you find a minimal case to reproduce this issue?

**Comment by hajimehoshi** [comment]
And, does this happen with Ebitengine v2.4.0-alpha.11?

**Comment by hajimehoshi** [comment]
> panic: EOF

Which `vorbis.Decode` or `ctx.NewPlayer` returned this error?

**Comment by amazinglySK** [comment]
> Hi, did you find a minimal case to reproduce this issue?
> 
> I read https://github.com/amazinglySK/chessgo but I couldn't find the `sounds` package.

I haven't pushed the sounds package to the repo yet. And yes I tried out a minimal case right here
```go
package main

import (
        "bytes"
        "image/color"
        _ "embed"
        "github.com/hajimehoshi/ebiten/v2"
        "github.com/hajimehoshi/ebiten/v2/audio"
        "github.com/hajimehoshi/ebiten/v2/audio/vorbis"
)

type Game struct {
        AudioPlayer *audio.Player
}

func (g *Game) Update() error {
        g.AudioPlayer.Play()
        return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
        screen.Fill(color.White)
}

func (g *Game) Layout(o, i int) (int, int) {
        return 640, 320
}

//go:embed sound.ogg
var sound []byte

func main() {
        ebiten.SetWindowTitle("Sound Testing")
        ebiten.SetWindowSize(640, 320)


        audioContext := audio.NewContext(32000)

        stream, err := vorbis.Decode(audioContext, bytes.NewReader(sound))

        if err != nil {
                panic(err)
        }

        p, err := audioContext.NewPlayer(stream)

        if err != nil {
                panic(err)
        }

        if err := ebiten.RunGame(&Game{p}); err != nil {
                panic(err)
        }
}
```

Works perfectly fine there.



> And, does this happen with Ebitengine v2.4.0-alpha.11?

I haven't tried it.



> > panic: EOF
> 
> Which `vorbis.Decode` or `ctx.NewPlayer` returned this error?

Can't figure out that either.

**Comment by amazinglySK** [comment]
I'll give it one more shot in the project and try debugging. 

And also is it necessary to provide the right bitrate for the audio player to work ?

**Comment by hajimehoshi** [comment]
> I haven't pushed the sounds package to the repo yet. And yes I tried out a minimal case... But was not able to reproduce the same issue

If the issue is reproduced with the branch, I'd be happy if you could upload this as a branch.

> It apparently happens in vorbis.Decode

Thanks. I'll take a look further but as long as I cannot reproduce this on my machine, it is still hard to find a solution.

> And also is it necessary to provide the right bitrate for the audio player to work ?

Yes.

**Comment by amazinglySK** [comment]
> > I haven't pushed the sounds package to the repo yet. And yes I tried out a minimal case... But was not able to reproduce the same issue
> 
> If the issue is reproduced with the branch, I'd be happy if you could upload this as a branch.

Yes I have created a new branch and pushed the failing code... Also, I have tried both : Isolating sounds to a separate package and creating audio directly in the main package. None of them seem to work :/ .. But thank you for your time :D . Hopefully we'll be able to come up with the issue 👍

**Comment by hajimehoshi** [comment]
Thanks, I could reproduce the issue with your `sounds` branch. I'll take a look further.

**Comment by hajimehoshi** [comment]
@amazinglySK Where did you get `move.ogg`? I guess this file is too short, and actually I failed to play it with other players like Audacity.

**Comment by hajimehoshi** [comment]
`github.com/jfreymuth/oggvorbis`'s `NewReader` returned `io.EOF`

**Comment by amazinglySK** [comment]
> @amazinglySK Where did you get `move.ogg`? I guess this file is too short, and actually I failed to play it with other players like Audacity.

Yep it's pretty small.. Just a click... Got it from [lichess (lila)](https://github.com/lichess-org/lila/tree/38bfadac3e319516341771086e8edc594d4d4b07/public/sound/standard)

But I tried with longer sound tracks.. but to no avail

**Comment by amazinglySK** [comment]
I have pushed the longer (miscellaneous) track [the same track which I used in the minmal case] in the same branch. Didn't work with that too

**Comment by hajimehoshi** [comment]
```
//go:embed sound.ogg
var sound []byte
```

Isn't this `move.ogg`? You are passing an empty slice to the decoder.

**Comment by hajimehoshi** [comment]
And, in your branch, there is a space between `//` and `go:embed`.

https://github.com/amazinglySK/chessgo/blob/02ff37a54c3fc05d687f6edf6322b5c4a7755965/main.go#L38

**Comment by hajimehoshi** [comment]
In summary, I have succeeded to play a sound by this change:

```diff
diff --git a/main.go b/main.go
index 4cb5321..268976e 100644
--- a/main.go
+++ b/main.go
@@ -1,6 +1,7 @@
 package main
 
 import (
+       _ "embed"
        "log"
 
        "bytes"
@@ -35,13 +36,14 @@ func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeigh
        return cfg.WindowWidth, cfg.WindowHeight
 }
 
-// go:embed sound.ogg
+//go:embed move.ogg
 var moveRaw []byte
 
 func main() {
        ebiten.SetWindowSize(cfg.WindowWidth, cfg.WindowHeight)
        ebiten.SetWindowTitle("Chess In Go")
        var audioContext = audio.NewContext(32000)
+       println(len(moveRaw))
        s, err := vorbis.Decode(audioContext, bytes.NewReader(moveRaw))
        check(err)
        p, err := audioContext.NewPlayer(s)
```

**Comment by amazinglySK** [comment]
Thank you so much for the help !! 😄

**Comment by hajimehoshi** [comment]
I have reported this (when an empty stream is passed, `NewReader` just returned `io.EOF`, but I think we can get a better error) https://github.com/jfreymuth/oggvorbis/issues/9
