### ISSUE TITLE
Recovery from panic in game loop

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2262]
Currently I'm facing a strange bug in production that occurs very randomly and to random people. My strategy was to recover from panic and to log given message, but the problem is that the `ebiten.Run()` function is staging an internal goroutine for the loop, so I cant really catch given panic outside of that goroutine.
It would be really helpful to recover a panic of that goroutine and throw it back in the actual method, or return that panic as an error.

```
package main

import (
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

func main() {
	defer func() {
		if r := recover(); r != nil {
			// r will always be nil here
			log.Println(r)
		}
	}()
	if err := ebiten.RunGame(&game{}); err != nil {
		// err will be nil as well
		log.Println(err)
	}
}

type game struct{}

func (g *game) Update() error { return nil }

func (g *game) Draw(screen *ebiten.Image) {
	_ = []int{}[0]
}

func (g *game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return outsideWidth, outsideHeight
}
```

**Comment by hajimehoshi** [comment]
What panic is happening? Is this in Ebitengine or in your game?

**Comment by erexo** [comment]
> What panic is happening? 

This is the case, I have no idea and I would like to know, since this Issue was created 😄

The panic is probably somewhere in the code, something like given example. The main problem is that, as I mentioned, it happens randomly and to random people

**Comment by hajimehoshi** [comment]
I think you should catch the log in all of your game's goroutines first.

**Comment by hajimehoshi** [comment]
Unfortunately there is no way to recover a panic in a different goroutine. This is Go's restriction, and there is nothing we can do in Ebitengine.

**Comment by erexo** [comment]
You can catch it in the actual loop goroutine...

**Comment by erexo** [comment]
did you read the example I wrote? Ebitengine offers me no tool to actually know that the `Draw` method panicked...

**Comment by hajimehoshi** [comment]
> did you read the example I wrote? Ebitengine offers me no tool to actually know that the Draw method panicked...

What about recovering the panic in Draw?

**Comment by erexo** [comment]
and that might be the solution, thanks
