### ISSUE TITLE
Enable `EBITENGINE_SCREENSHOT_KEY` on browsers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2265]
What about letting browsers download a screenshot image?

`EBITENGINE_INTERNAL_IMAGES_KEY` might also work in the same way (creating a zip internally)

The issue is that it is hard to pass environment variables for browsers.

**Comment by superloach** [comment]
Is modifying env that difficult? `EBITENGINE_SCREENSHOT_KEY` and `EBITENGINE_INTERNAL_IMAGES_KEY` should primarily be used in development, and you should just be able to modify `go.env` after `const go = new Go();`, if I'm not mistaken. `wasmserve` could also be modified to pass environment variables to the webpage, if it doesn't already.

**Comment by hajimehoshi** [comment]
I think https://github.com/agnivade/wasmbrowsertest doesn't support environment variables yet.

**Comment by superloach** [comment]
Looks like it should, haven't tested myself though - https://github.com/agnivade/wasmbrowsertest/blob/master/handler.go#L35

**Comment by hajimehoshi** [comment]
Ok I'll take a look later

**Comment by superloach** [comment]
Mind if I take a stab at this?

**Comment by hajimehoshi** [comment]
Yes!

* Fixing `wasmserve` would be required
* We would have to split [`Dump`](https://github.com/hajimehoshi/ebiten/blob/70f5e84098d863b0e390f57ade6913c2c038235e/internal/graphicscommand/image.go#L199) into non-js and js versions

**Comment by superloach** [comment]
Sounds good to me. On the JS side, do you prefer using `eval`, or making function calls directly in Go?

**Comment by hajimehoshi** [comment]
I don't prefer `eval`. Let's make function calls directly in Go.

**Comment by superloach** [comment]
Thought so - just checking :)

**Comment by superloach** [comment]
I've made decent progress on this, but I keep getting malformed PNG files...

**Comment by superloach** [comment]
Ohhh is the internal pixel representation different on WASM?

**Comment by hajimehoshi** [comment]
I don't think so?

**Comment by superloach** [comment]
Hmm, I'm not really sure what's happening then. Let me clean this up and push it to my branch

**Comment by superloach** [comment]
Ah, could be string conversion. Let me try using a Uint8Array

**Comment by superloach** [comment]
(for the record, it *was* the string conversion. lol)
