### ISSUE TITLE
ebiten: API to terminate an application explicitly

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2266]
Now an Ebiten application can be terminated by returning an user-defined error at Update, but this is a little counterintuitive: even though the application exits in a regular way, the program treats 'error' values.

Instead of treating errors, what about having an explicit API to terminate an application, like `ebiten.Terminate`?

**Comment by superloach** [comment]
I like the idea of `ebiten.Termination` - it's something we've had to implement on our own 90% of the time anyway, it doesn't change any API, and it provides an intuitive way to terminate cleanly.

**Comment by superloach** [comment]
I can take this issue :)

**Comment by hajimehoshi** [comment]
* Define `Termination`
* When `Update` returns this error, `RunGame` should return but without error. Fix `RunGame` to do so.
* Replace all the `regularTermination` uasges in this repository with `Termiination`

**Comment by superloach** [comment]
Would you be opposed to using `ui.RegularTermination` as `ebiten.Termination`? Or should I create a separate error value?

**Comment by hajimehoshi** [comment]
Ah I forgot the existance of it. Let's use it like

```
var Termination = ui.RegularTermination
```

**Comment by hajimehoshi** [comment]
By the way, for naming, would `RegularTermination` be better than `Termination`?

**Comment by superloach** [comment]
perhaps, yeah, since you already used that name

**Comment by hajimehoshi** [comment]
Hmm, let's use `Termination` for the public API so far. We can rename this later until v2.5.0 is released.

**Comment by superloach** [comment]
fair enough :)
