### ISSUE TITLE
enable `EBITENGINE_INTERNAL_IMAGES_KEY` on browsers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2270]
This is forked from #2265. Probably downlonding a zip file is fine.

**Comment by hajimehoshi** [comment]
/CC @superloach I separated this issue from the original issue #2265 in order to avoid a big change. Now it's ready to implement `EBITENGINE_INTERNAL_IMAGES_KEY` thanks to your work at #2265 :-) If you are interested in it, I'm very happy to review your PR

**Comment by superloach** [comment]
Absolutely, after I implement Termination I will look back at this. My method for creating a ZIP worked, but it required exposing the ID from graphicscommand into restorable.

**Comment by hajimehoshi** [comment]
> Absolutely, after I implement Termination I will look back at this. My method for creating a ZIP worked, but it required exposing the ID from graphicscommand into restorable.

I still would like to avoid exposing IDs, so let me think how to implement this.

**Comment by superloach** [comment]
We could use a different identifier for the image names, like the image pointer value, or simply a counter in `DumpImages`

**Comment by superloach** [comment]
Exposing an ID from one internal package to another isn't the worst thing, though

**Comment by hajimehoshi** [comment]
This is my personal preference but I would like to avoid properties whenever possible even though this is in an internal package.

**Comment by superloach** [comment]
Totally understood. Just not really sure how I would solve it, since my solution would just be to expose it :P

**Comment by superloach** [comment]
Any new thoughts on this?

**Comment by hajimehoshi** [comment]
Sorry I was quite busy for a while. Would it be fine to you to send a PR with your current idea, and then think what we should do based on the PR?

**Comment by superloach** [comment]
Sounds good, I'll put something together and we'll work from there :)

**Comment by superloach** [comment]
a thought: since on desktop INTERNAL_IMAGES_KEY just dumps a bunch of files, is it necessary to create a zipfile for browsers?

**Comment by superloach** [comment]
If a zipfile isn't necessary, the simplest fix here would just be ignoring the error in dumpInternalImages on JS

**Comment by hajimehoshi** [comment]
> a thought: since on desktop INTERNAL_IMAGES_KEY just dumps a bunch of files, is it necessary to create a zipfile for browsers?

Yeah, creating a zip seems the way to go.

> If a zipfile isn't necessary, the simplest fix here would just be ignoring the error in dumpInternalImages on JS

What error?

**Comment by superloach** [comment]
The error from mkdir, if we were to leave the code as-is for JS

**Comment by superloach** [comment]
I'll create a zip though :)
