### ISSUE TITLE
audio suspends and somtimes doesn't restarts when Siri is invoked on iOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2279]
Found this issue on github.com/hajimehoshi/go-inovation

**Comment by hajimehoshi** [comment]
Hmmm, the behavior seems very flaky. The audio sometimes restarts.

**Comment by hajimehoshi** [comment]
```
goinovation[5908:268226] Inovation Error!: Error Domain=go Code=1 "oto: AudioQueueStart failed at Resume: 560557684" UserInfo={NSLocalizedDescription=oto: AudioQueueStart failed at Resume: 560557684}
```

**Comment by hajimehoshi** [comment]
Now we can get errors correctly by b53c68601715820727ce303550fdc2d5796309d0. Thank you @superloach !

**Comment by superloach** [comment]
Oh nice! I found this mistake using golangci-lint, I believe with the unchecked error linter. Might be helpful to run this periodically on Ebitengine :)
