### ISSUE TITLE
add a static analysis of error usages to GitHub actions

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2287]
See also https://github.com/hajimehoshi/ebiten/issues/2279#issuecomment-1233092966

**Comment by superloach** [comment]
Would you be opposed to using `golangci-lint`? In addition to errcheck, there are other linters that may be useful. And we can pick and choose which linters we want to use.

**Comment by hajimehoshi** [comment]
I'd like to adopt a static-analyzing way like what I did for atomicalign https://github.com/hajimehoshi/ebiten/blob/main/.github/workflows/test.yml#L75-L78

**Comment by superloach** [comment]
Ah okay, fair

**Comment by superloach** [comment]
Looks like errcheck (https://github.com/kisielk/errcheck) provides an Analyzer that we could use similarly to atomicalign
