### ISSUE TITLE
internal/ui: maximizing window via button is still available when window's max size is determined

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2289]
In #2259 there was an attempt to fix flickering size-dependent window during maximization, but given case can still be achieved by clicking on the "Maximize" button on the window frame.

![image](https://user-images.githubusercontent.com/6548968/187887247-8e82005c-a4bc-4cfa-a06c-d3d63e3c0067.png)

**Comment by hajimehoshi** [comment]
Same as linux.

**Comment by hajimehoshi** [comment]
I think this is an issue in GLFW

**Comment by hajimehoshi** [comment]
https://github.com/glfw/glfw/issues/1103#issuecomment-1236138054

**Comment by hajimehoshi** [comment]
#2546 is a blocker, if we try to modify GLFW by ourselves.

**Comment by hajimehoshi** [comment]
On X Window system, there seems no way to enable/disable a maximizing button. I saw the implementation of `updateNormalHints`, and apparently the maximizing button is disabled when the minimum size and the maximize size are the same.
