### ISSUE TITLE
internal/graphicsdriver/directx: HRESULT(2147942414) (out of memory)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2292]
On 32bit Windows, this often happens on GitHub Actions CI and Parallels
On 64bit Windows, this is pretty rare but was reported by @erexo

**Comment by erexo** [comment]
One of my players using Windows 11 Home on a "decent" machine reported that after approximately one minute after game launch this error occurs.
It is also happening on a basic setup like presented in #2290. I've sent a compiled version of this app to that player and he reported that the game is still closing after a short while, both when the source was compiled as arm64 and 386 arch

**Comment by hajimehoshi** [comment]
I can reproduce this with a 32bit binary on Parallels:

```ps
> $env:GOARCH = "386"
> go test .
--- FAIL: TestImageOptionsNegativeBoundsWritePixels (0.00s)
panic: directx: ID3D12Device::CreateCommittedResource failed: HRESULT(2147942414) [recovered]
        panic: directx: ID3D12Device::CreateCommittedResource failed: HRESULT(2147942414)

goroutine 108 [running]:
testing.tRunner.func1.2({0x352f60, 0x1180b650})
        C:/Program Files/Go/src/testing/testing.go:1396 +0x2ab
testing.tRunner.func1()
        C:/Program Files/Go/src/testing/testing.go:1399 +0x41f
panic({0x352f60, 0x1180b650})
        C:/Program Files/Go/src/runtime/panic.go:884 +0x1ba
github.com/hajimehoshi/ebiten/v2/internal/ui.(*Image).ReadPixels(0x11c9ba10, {0x11eb5a00, 0x4, 0x4}, 0x0, 0x0, 0x1, 0x1)
        //Mac/Home/ebiten/internal/ui/image.go:86 +0xdf
github.com/hajimehoshi/ebiten/v2.(*Image).at(0x11c31f40, 0xfffffff8, 0xfffffff8)
        //Mac/Home/ebiten/image.go:865 +0x152
github.com/hajimehoshi/ebiten/v2.(*Image).At(0x11c31f40, 0xfffffff8, 0xfffffff8)
        //Mac/Home/ebiten/image.go:833 +0x31
github.com/hajimehoshi/ebiten/v2_test.TestImageOptionsNegativeBoundsWritePixels(0x11885770)
        //Mac/Home/ebiten/image_test.go:2967 +0x424
testing.tRunner(0x11885770, 0x3a2894)
        C:/Program Files/Go/src/testing/testing.go:1446 +0x113
created by testing.(*T).Run
        C:/Program Files/Go/src/testing/testing.go:1493 +0x374
FAIL    github.com/hajimehoshi/ebiten/v2        67.973s
FAIL
```

So I think this is the key...

**Comment by erexo** [comment]
I do not call `At` or `ReadPixels` at all, I do however call `At` on `image.Image` which is usually an `image.NRGBA` which internal buffer is also used as `*ebiten.Image`

**Comment by hajimehoshi** [comment]
Thanks. Another question: are you calling `NewImage` or `NewImageFromImage` every frame?

**Comment by hajimehoshi** [comment]
So from @erexo a very simple application like https://pastebin.com/raw/UhV7DDFP crashed with the error after a minute with this card:

> AMD A8-6600K APU with Radeon HD Graphics 3.90GHz
> and NVIDIA GeForce GT 710

Right?

**Comment by erexo** [comment]
Right, this exact code: https://pastebin.com/raw/51J522d0
with this build method
`GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build -o test.exe`
produced this output
![image](https://user-images.githubusercontent.com/6548968/187951494-bb1ba7f7-82f9-4f3f-a983-6d3fd43acc64.png)

**Comment by hajimehoshi** [comment]
I have confirmed a monotonical increse of GPU memory usage in any applications. I'll try bisect.

**Comment by hajimehoshi** [comment]
9d303e8dc515053a0f4183f4632ea3253543c45d is the culprit!

**Comment by hajimehoshi** [comment]
@erexo  Could you test  5459036d1c654bb6da56231778450be3d0df1eb6? Thanks,

**Comment by hajimehoshi** [comment]
Probably we have a command list for each frame rather than one command list for all the frame...

**Comment by hajimehoshi** [comment]
Discussed on the chat and confirmed this was fixed. Thank you, @erexo!
