### ISSUE TITLE
internal/ui: the window size is not correctly restored after fullscreen on macOS

### ISSUE THREAD

**Issue by Toyking10** [hajimehoshi/ebiten#2295]
[bugtest.zip](https://github.com/hajimehoshi/ebiten/files/9475587/bugtest.zip)
I have attached the most basic example I could make.
I'm using Mac Studio macOS 12.5.1.
Occurs on vertical screen, horizontal screen, 4k, 1080p and anything I could test on.

Originally 0,0 is top left. On resizing, if it's a horizontal screen the top is still y=0 but the left is now x = -100 ish. For vertical screen it's the opposite.

Upon resizing to original size, the top left is now +-15ish for both x and y.

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
I needed `SetWindowResizable(true)` for v2.3.8, but this is a regression.

**Comment by Toyking10** [comment]
> I needed `SetWindowResizable(true)` for v2.3.8, but this is a regression.

I see. Thanks for acknowledging so fast. This is affecting me.

**Comment by hajimehoshi** [comment]
7a936f70527a1d88073eeaa3ea328dfa72961f50 was the culprit.

**Comment by hajimehoshi** [comment]
![image](https://user-images.githubusercontent.com/16950/188081153-6d767801-8a9d-4dd4-ab3a-50072e00f08c.png)

So the problem is that the window size is not correctly reverted after fullscreen.

**Comment by hajimehoshi** [comment]
My current guess is that `(*glfw.Window).SetSize` is called just after recovering from fullscreen and `SetSize` does NOT consider the window's title bar as this doesn't exist in the fullscreen mode. So, I would have to defer `SetSize` call after the fullscreen mode is completely finished...

**Comment by hajimehoshi** [comment]
`setFrame` in `windowDidExitFullScreen` seems troublesome

**Comment by hajimehoshi** [comment]
This should be fixed.

@Toyking10 could you try 40052f6e3568f68c2f11ded461ea967e1d465435?

```sh
go get github.com/hajimehoshi/ebiten/v2@40052f6e3568f68c2f11ded461ea967e1d465435
```

Thanks,

**Comment by Toyking10** [comment]
> This should be fixed.
> 
> @Toyking10 could you try [40052f6](https://github.com/hajimehoshi/ebiten/commit/40052f6e3568f68c2f11ded461ea967e1d465435)?
> 
> ```shell
> go get github.com/hajimehoshi/ebiten/v2@40052f6e3568f68c2f11ded461ea967e1d465435
> ```
> 
> Thanks,

@hajimehoshi This fixed it for me, thank you!
