### ISSUE TITLE
windows/opengl: v2.4.0 Regression: allow running with software rendering again

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2302]
internal/glfwwin/wglcontext_windows.go seems to no longer allow running w/o acceleration:

```
                        if findAttribValue(_WGL_ACCELERATION_ARB) == _WGL_NO_ACCELERATION_ARB {
                                continue
                        }
```

```
                        if pfd.dwFlags&_PFD_GENERIC_ACCELERATED == 0 && pfd.dwFlags&_PFD_GENERIC_FORMAT != 0 {
                                continue
                        }
```

This is breaking my integration testing on GitHub Actions, which works by installing Mesa: https://github.com/divVerent/aaaaxy/blob/main/.github/workflows/go-anypercent.yml#L118

Can you provide an environment variable or other hack to allow skipping this checks if one really, really desires so?

**Comment by hajimehoshi** [comment]
I think this was my mistake. I'll fix this

**Comment by divVerent** [comment]
Hm... I find the same code in glfw's code base though. How come it even works then for me?

**Comment by hajimehoshi** [comment]
On Actions you can use DirectX by the way.

**Comment by divVerent** [comment]
I guess the best way to try this issue out is to unpack Mesa the same way as I do in my actions on real Windows, and to set the `LIBGL_ALWAYS_SOFTWARE=1` environment variable to make 100% sure. I can check this later, but I have no Windows machine that can actually compile Ebiten at this time.

**Comment by divVerent** [comment]
Hm... for Win32 I still need OpenGL support as v2.4.0 doesn't support 32bit Windows in DirectX yet (v2.5.0 apparently will), but confirmed that Win64/DirectX works on GitHub Actions.

**Comment by hajimehoshi** [comment]
> Hm... for Win32 I still need OpenGL support as v2.4.0 doesn't support 32bit Windows in DirectX yet (v2.5.0 apparently will), but confirmed that Win64/DirectX works on GitHub Actions.

Correct.

**Comment by divVerent** [comment]
https://github.com/divVerent/aaaaxy/runs/8169335498?check_suite_focus=true#step:8:17 - rejection reasons

**Comment by hajimehoshi** [comment]
Now the DirectX driver is supported by 32bit Windows.

https://github.com/hajimehoshi/ebiten/commit/313c70f4b444d48ce15826c08de898f6bbe1664a
