### ISSUE TITLE
internal/gamepad: the gamepad names are unexpectedly cutoff to 7 characters

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2303]
Fix is #2300 by @divVerent

**Comment by hajimehoshi** [comment]
Fixed by https://github.com/hajimehoshi/ebiten/commit/9bc571af5ef9f37df2ee6e001f5ac7b6a7b9e7ee

**Comment by hajimehoshi** [comment]
I don't plan to backport the fix to 2.4 branch so far, buf if this is serious to @divVerent, I'm fine to backport this.

**Comment by divVerent** [comment]
That's absolutely fine - in my concrete case it only affects logging anyway. Even when it's in the game menu, it won't be particularly critical.
