### ISSUE TITLE
Number of pow's arguments must be 1 but 2

### ISSUE THREAD

**Issue by cedriclikescode** [hajimehoshi/ebiten#2304]
To reproduce: use the pow function anywhere in a shader (.kage) file then use ebiten.newShader to load it.
Minimal reproducible case (uses ebitengine 2.4.1 but the same issue happens in ebitengine 2.4.0): `go run github.com/cedriclikescode/ebitengineShaderPow@main`
Expected behavior: should behave as it was in ebitengine 2.3.x or older (it shouldn't throw this error) which in the case of using the minimal reproducible case returns "fragment shader entry point 'Fragment' is missing"
Is there a specific reason as to why the pow function would take only one argument?

**Comment by hajimehoshi** [comment]
https://registry.khronos.org/OpenGL-Refpages/gl4/html/pow.xhtml
https://docs.microsoft.com/en-us/windows/win32/direct3dhlsl/dx-graphics-hlsl-pow

pow function takes 2 arguments, right?

**Comment by hajimehoshi** [comment]
> Number of pow's arguments must be 1 but 2

Or, you mean "Number of pow's arguments must be 2 but 1"?

**Comment by hajimehoshi** [comment]
Please try

```sh
go get github.com/hajimehoshi/ebiten/v2@ead48ca5ab9804fa8d8d877e45bab83d4b9bfef4
```

Thanks,

**Comment by cedriclikescode** [comment]
Explain this then:
![Screenshot 2022-09-04 193557](https://user-images.githubusercontent.com/104719938/188326378-605508ac-42e1-4b15-8dc4-ef16afb4ac07.png)

**Comment by cedriclikescode** [comment]
The latest commit fixed the issue. Thanks
