### ISSUE TITLE
linux/gamepad: crash inside snap

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2307]
I am getting in AAAAXY:

2022/09/05 08:27:44.415955 [FATAL] RunGame exited abnormally: gamepad: Open failed: operation not permitted

This is apparently due to https://github.com/hajimehoshi/ebiten/blob/main/internal/gamepad/gamepad_linux.go#L108 receiving EPERM instead of EACCES.

Not sure if that's snap's fault or Ebitengine's, but I'd opt for ignoring EPERM here too.

**Comment by divVerent** [comment]
Trying if that fixes things in the snap sandbox and I can still use gamepads. I do have the "joystick" interface connected.

**Comment by hajimehoshi** [comment]
Do you think this is a regression or not? Does the same thing happened with an old Ebitengine (v2.2.7)?

**Comment by divVerent** [comment]
Pretty sure something changed on Snap end, not Ebitengine end, as I also
had to make changes to the Snap to keep supporting AMD GPUs. So not really
a regression.

**Comment by divVerent** [comment]
I think what changed is that snap's sandboxing no longer permits all /dev/input/event* devices, but only those that are gamepads.

**Comment by hajimehoshi** [comment]
Sure. I'm fine to apply the change https://github.com/divVerent/ebiten/commit/42fa7d0f303cfa45800063bee5c69d15e217b260 is this is no harmful.

**Comment by hajimehoshi** [comment]
A PR is not sent yet.

Do you want me to backport the fix to 2.4?

**Comment by divVerent** [comment]
It'd be nice to include this in v2.4.2 as well - otherwise I'll keep backporting it myself on top of v2.4.x until v2.5 is released.

**Comment by divVerent** [comment]
Yes. The "second" software store (in addition to apt) that's enabled by default on Ubuntu.
