### ISSUE TITLE
internal/gamepaddb: standard layout is not correctly detected on Android

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2309]
I am connecting a generic X-Box gamepad (this one: https://github.com/gabomdq/SDL_GameControllerDB/pull/452) but am getting:

```
09-06 07:34:08.860 25521 25559 I GoLog   : 2022/09/06 11:34:08.860469 [INFO] gamepad Generic X-Box pad added
09-06 07:34:08.860 25521 25559 I GoLog   : 2022/09/06 11:34:08.860534 [ERROR] gamepad Generic X-Box pad has no standard layout - cannot use
```

This can't be right - it doesn't get much more standard layout than this.

However, on Android, Ebitengine always returns false to hasOwnStandardLayoutMapping, and for some reason we don't match the gamecontrollerdb entry either (not sure if that'd even work, as it depends on the order the OS returns buttons in, which likely differs between Android and Linux).

In addition, the Java code in `cmd/ebitenmobile/gobind.go` very much looks like Android does usually provide the standard layout mapping internally (see names like KEYCODE_BUTTON_SELECT).

**Comment by hajimehoshi** [comment]
So is this an issue only in Android or not?

**Comment by divVerent** [comment]
Only on Android, and apparently primarily because standard layout isn't implemented yet (but ALSO, gamecontrollerdb isn't working on Android either, probably due to different button indexes).

**Comment by hajimehoshi** [comment]
OK so `hasOwnStandardLayoutMapping` should return true on Android. I think the situation is also the same in iOS... Let me take a look

**Comment by hajimehoshi** [comment]
Yeah so both have the OS's standard layout, but these don't match with Ebitengine's standard layout. Then, just flipping `hasOwnStandardLayoutMapping` would not solve the issue. We have to re-map the buttons and axes.

**Comment by hajimehoshi** [comment]
Wait, for Android, `addAndroidDefaultMappings` in `internal/gamepaddb` should work

**Comment by divVerent** [comment]
I strongly suspect this string should have been converted from hex to binary first.

With that, buttonMask would become 0x07ff (= A, B, X, Y, Back, Guide, Start, LeftStick, RightStick, LeftShoulder, RightShoulder) and axisMask would be 0x003f (LeftX, LeftY, RightX, RightY, TriggerLeft, TriggerRight).

I should note that this is only _mostly_ correct - my gamepad has a Dpad but the buttonMask evaluated this way doesn't indicate it. So more might be wrong.

**Comment by hajimehoshi** [comment]
> id[14] is not a "h", which is good.

This should never be true. I referred SDL so I'll recheck the logic again.

**Comment by hajimehoshi** [comment]
@divVerent Could you check f383580d7b71d38990f8ef6705f0a68292b5aa79 ? Thanks,

**Comment by divVerent** [comment]
That fix makes the gamepad recognized, but the mapping is totally wrong; for example moving the right stick right looks down, left looks up. The left stick and the A button are mapped correctly.

**Comment by divVerent** [comment]
The code appears to assume that buttons 0 to 14 are mapped in SDL's order (see the Index: in the &mapping{} literals).

However, `input_android.go` has different indices. Is this the reason?

**Comment by hajimehoshi** [comment]
I found there is a map from Android keys to `ebiten.GamepadButton` in `input_android.go`, while gamepaddb treats SDL keys. So there are mismatches there.

**Comment by hajimehoshi** [comment]
> However, input_android.go has different indices. Is this the reason?

Yeah this is it... I'll fix this tomorrow.

**Comment by divVerent** [comment]
Great, thanks!

**Comment by divVerent** [comment]
I got some basics to work by trying to figure out the remapping, but must have gone wrong - there's still no Start button, of the ABXY block only A and B work, and of course (as expected) the D-pad still does not. Had to comment out the trigger axes as they were confusing my game as permanently held buttons - no idea how that happened.

[d.diff.txt](https://github.com/hajimehoshi/ebiten/files/9499282/d.diff.txt)

**Comment by hajimehoshi** [comment]
I confirmed the current situation by showing a similar screen of `examples/gamepad` on an Android device.

* The trigger buttons are always 0.5
* Button assignments are wrong
* DPAD doesn't work
* The right stick's Y doesn't work

**Comment by hajimehoshi** [comment]
Hm, the things don't seem easy. I'll work on this this week.

**Comment by hajimehoshi** [comment]
Note to myself: for axes, there is something wrong with couting the axis: the number of axis seems half than expected.

**Comment by hajimehoshi** [comment]
I think the standard mapping should work at a9653d1e7a3b148d01834c013d4d33c0906714c3.

The current problem is, after I fixed a gamepad's GUID, the GUID is now correct but the button/axis assignments don't match with SDL's and the database's. This means that we cannot use the current database so far. Now Ebitengine prioritize the original mapping for Android so far, but I'd like to change the order of them later.

**Comment by hajimehoshi** [comment]
Let me close this issue.

**Comment by hajimehoshi** [comment]
I don't plan to backport this fix as the fix is quite big and not mature yet, then might cause another issue...

**Comment by divVerent** [comment]
Waaait... does that mean SDL_gamecontrollerdb has entries for Android, but the button assignment order differs and that's what broke this all?

Also, your fix means that now _every_ function call to anything gamepad will call addAndroidDefaultMappings and reallocate all this data? Sounds slow, but probably OK - all this does is calculation and GC churn, after all.

Will test the fix soon.

**Comment by hajimehoshi** [comment]
> Waaait... does that mean SDL_gamecontrollerdb has entries for Android,

Yes https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt#L1496

> but the button assignment order differs and that's what broke this all?

Unfortunately yes, after fixing GUID to be 'correct'.

> Also, your fix means that now every function call to anything gamepad will call addAndroidDefaultMappings and reallocate all this data? Sounds slow, but probably OK - all this does is calculation and GC churn, after all.

Yes, but I'd like to change the situation at #2312.

**Comment by divVerent** [comment]
Seems mostly correct, except that the trigger button axes and the RightStick seem switched (which does break my game significantly - can only play while holding the trigger buttons halfway unless I disable RightStick support from my game).

**Comment by hajimehoshi** [comment]
Hmm ok. I hope #2312 would fix this.

**Comment by hajimehoshi** [comment]
I'll try this tomorrow. Thank you for your patience.

**Comment by divVerent** [comment]
Now this is peculiar - I have the same swap issue in the tester app. If I press the triggers, the "analog sticks" display changes.

**Comment by hajimehoshi** [comment]
> Now this is peculiar - I have the same swap issue in the tester app. If I press the triggers, the "analog sticks" display changes.

Hm ok, so this seems an issue on your side 🤔

**Comment by divVerent** [comment]
Except... the tester app shows it wrong on the display, HOWEVER the trigger does change AXIS_Z and AXIS_RZ, and the right stick does change AXIS_RX and AXIS_RY. Don't know why the tester app defaults to displaying the right stick as AXIS_Z and AXIS_RZ.

**Comment by divVerent** [comment]
Oh, the naming on Android is horrible:

> AXIS_Z:
>     For a joystick, reports the absolute Z position of the joystick. The value is normalized to a range from -1.0 (high) to 1.0 (low). On game pads with two analog joysticks, this axis is often reinterpreted to report the absolute X position of the second joystick instead. 

It's done this way because AXIS_RX doesn't mean "right X" but actually "rotate X" :(

**Comment by hajimehoshi** [comment]
Yeah, AXIS_Z and AXIS_RZ are for the second stick actually! 🤪

**Comment by divVerent** [comment]
In that case, Android maps my controller wrong, and there's nothing Ebitengine can rightfully do there. I think I'll just disable support for the right stick in my game (at least by default).

**Comment by hajimehoshi** [comment]
Sure. What is your game controller's SDL ID? If they might have a mapping for your controller to handle such a situation.

**Comment by divVerent** [comment]
It should be the one I posted above (05000000d620000002280000ff073f00), except that you've IIRC fixed it to also include the hats bits now.

**Comment by hajimehoshi** [comment]
> It should be the one I posted above (05000000d620000002280000ff073f00), except that you've IIRC fixed it to also include the hats bits now.

Correct, so the ID should be different now, but I couldn't find the closer one in the list https://github.com/gabomdq/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt

**Comment by divVerent** [comment]
On Linux it has the ID 03000000d62000000228000001010000

0d62:0228 is indeed the vendor ID. It's not in the DB for any other OS, as the entry is actually by me.

**Comment by divVerent** [comment]
Actually the ID is 20d6:2802. I got byte swapped a little ;)

**Comment by hajimehoshi** [comment]
Aha, so you are using a compatible controller https://www.amazon.com/dp/B07DHY6YLM

So this means that #2312 would not change your situation anyway, and I would have to keep `addAndroidDefaultMappings` for compatibility, maybe

**Comment by divVerent** [comment]
Well, I can always contribute a gamecontrollerdb entry.

On Linux, this one sends ABS_Z/RZ for the triggers and RX/RY for the right stick, too.

**Comment by divVerent** [comment]
Well, I can always contribute a gamecontrollerdb entry.

On Linux, this one sends ABS_Z/RZ for the triggers and RX/RY for the right stick, too.

**Comment by hajimehoshi** [comment]
Sure. Let me close this issue again. I'll work on #2312 tomorrow so that the gamepaddb (including your new entry) will work correctly :-)

**Comment by divVerent** [comment]
So on Linux, RX and RY are meant to be the right stick:

https://www.kernel.org/doc/html/latest/input/gamepad.html

So, why would Android define them differently... anyway, for now I'm gonna disable RX/RY/Z/RZ in my game when on Android.

**Comment by divVerent** [comment]
Filed an internal bug report for this axis discrepancy. I suspect this will yield to a documentation, not a code, fix, though ;)

**Comment by hajimehoshi** [comment]
> Filed an internal bug report for this axis discrepancy.

Where? Linux, Android, or the gamepad maker?

**Comment by divVerent** [comment]
For Android, as either the driver that ships with Android or the documentation is wrong.

**Comment by divVerent** [comment]
I have ideas how to implement this, however it seems like Ebitengine currently assumes that IF standard layout is supported, then buttons are numbered the same way whether using standard layout or not.

Of course I could just change that... probably will have to, as otherwise most gamepads won't have a consecutive set of buttons and thus button count would have to include buttons that don't exist.

**Comment by divVerent** [comment]
I am tentatively working on this now, tracking work on https://github.com/divVerent/aaaaxy/issues/106 as I can assign to myself there.
