### ISSUE TITLE
Forward compatibility with newer versions of glibc when built

### ISSUE THREAD

**Issue by sedyh** [hajimehoshi/ebiten#2310]
### Problem

It looks like a game built on a newer Linux distribution will not run on an older one with the following error:

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_X.XX' not found
```
I encountered this error very often during game jam, only manual reassembly helped.
Not sure if it depends on the Ebitengine version.

<details><summary><code>inxi -Fxz</code> Output</summary><br><pre>
System:
  Kernel: 5.4.0-125-generic x86_64 bits: 64 compiler: gcc v: 9.4.0 
  Desktop: Cinnamon 5.0.7 Distro: Linux Mint 20.2 Uma 
  base: Ubuntu 20.04 focal 
Machine:
  Type: Desktop Mobo: ASRock model: B450 Pro4 serial: <filter> 
  UEFI [Legacy]: American Megatrends v: P3.60 date: 07/31/2019 
CPU:
  Topology: 6-Core model: AMD Ryzen 5 3600 bits: 64 type: MT MCP arch: Zen 
  L2 cache: 3072 KiB 
  flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm 
  bogomips: 86241 
  Speed: 2196 MHz min/max: 2200/3600 MHz Core speeds (MHz): 1: 2195 2: 2195 
  3: 1865 4: 2745 5: 2196 6: 1864 7: 1887 8: 2681 9: 2195 10: 2195 11: 2196 
  12: 1886 
Graphics:
  Device-1: AMD Navi 10 [Radeon RX 5600 OEM/5600 XT / 5700/5700 XT] 
  driver: amdgpu v: kernel bus ID: 0c:00.0 
  Display: x11 server: X.Org 1.20.13 driver: amdgpu,ati 
  unloaded: fbdev,modesetting,radeon,vesa resolution: 2560x1440~60Hz 
  OpenGL: renderer: AMD Radeon RX 5700 XT (NAVI10 DRM 3.35.0 
  5.4.0-125-generic LLVM 12.0.0) 
  v: 4.6 Mesa 21.2.6 direct render: Yes 
Audio:
  Device-1: AMD Navi 10 HDMI Audio driver: snd_hda_intel v: kernel 
  bus ID: 0c:00.1 
  Device-2: AMD Starship/Matisse HD Audio vendor: ASRock 
  driver: snd_hda_intel v: kernel bus ID: 0e:00.4 
  Device-3: Realtek USB2.0 Microphone type: USB 
  driver: hid-generic,snd-usb-audio,usbhid bus ID: 3-1:2 
  Sound Server: ALSA v: k5.4.0-125-generic 
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet 
  vendor: ASRock driver: r8169 v: kernel port: d000 bus ID: 09:00.0 
  IF: enp9s0 state: up speed: 100 Mbps duplex: full mac: <filter> 
  IF-ID-1: br-ed9eba69972d state: down mac: <filter> 
  IF-ID-2: docker0 state: down mac: <filter> 
Drives:
  Local Storage: total: 2.41 TiB used: 488.50 GiB (19.8%) 
  ID-1: /dev/nvme0n1 vendor: Silicon Power model: SPCC M.2 PCIe SSD 
  size: 953.87 GiB 
  ID-2: /dev/sda vendor: Seagate model: ST9500325AS size: 465.76 GiB 
  ID-3: /dev/sdb vendor: Seagate model: ST1000DM010-2EP102 size: 931.51 GiB 
  ID-4: /dev/sdc vendor: Western Digital model: WDS120G2G0B-00EPW0 
  size: 111.80 GiB 
Partition:
  ID-1: / size: 937.33 GiB used: 488.50 GiB (52.1%) fs: ext4 
  dev: /dev/nvme0n1p5 
Sensors:
  System Temperatures: cpu: 56.6 C mobo: N/A gpu: amdgpu temp: 42 C 
  Fan Speeds (RPM): N/A gpu: amdgpu fan: 1209 
Info:
  Processes: 425 Uptime: 3h 24m Memory: 15.56 GiB used: 7.82 GiB (50.3%) 
  Init: systemd runlevel: 5 Compilers: gcc: 9.4.0 Shell: bash v: 5.0.17 
  inxi: 3.0.38 
</pre></details>

**Comment by hajimehoshi** [comment]
I have no idea. Is this an Ebitengine issue, or a general Go issue?

**Comment by sedyh** [comment]
I met this only in games made on Ebitengine, but maybe I'm wrong.

**Comment by hajimehoshi** [comment]
https://debian-facile.org/viewtopic.php?id=7218 ?

**Comment by sedyh** [comment]
I have same issue with some of the games on jam.

For example, same error for this one:
https://itch.io/jam/ebiten-game-jam/rate/1594759

```
./magnet
./magnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./magnet)
./magnet: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./magnet)
```

**Comment by hajimehoshi** [comment]
https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found

This seems a general issue of libc.

**Comment by hajimehoshi** [comment]
Removing Cgo from Ebitengine would solve the issue, but how...?

**Comment by sedyh** [comment]
Do I understand correctly that I must have a version of glibc not lower than that of the developer?

**Comment by sedyh** [comment]
It seems to me that its version is updated quite often. Can I forcibly build an application under a very old version so that it will run for everyone?

**Comment by hajimehoshi** [comment]
In theory, yes

**Comment by hajimehoshi** [comment]
> Can I forcibly build an application under a very old version so that it will run for everyone?

What about Docker?

**Comment by sedyh** [comment]
> > Can I forcibly build an application under a very old version so that it will run for everyone?
> 
> What about Docker?

Not sure if this will work for the end user. For example, the recent Dr. Kobushi's Labyrinthine Laboratory downloaded from steam won't launch natively due to this very issue.

**Comment by nadimkobeissi** [comment]
> For Steam games, there is a Steam SDK for the standard development environment:
> 
> https://github.com/hajimehoshi/ebiten/blob/main/.github/workflows/steam.yml
> 
> I don't know how Dr. Kobushi is built. /CC @nadimkobeissi

DKLL for Linux is built on Ubuntu 22.04.1 LTS. Not sure what I'm supposed to do here: intentionally use old Linux distributions?

**Comment by nadimkobeissi** [comment]
> For Steam games, there is a Steam SDK for the standard development environment:
> 
> https://github.com/hajimehoshi/ebiten/blob/main/.github/workflows/steam.yml
> 
> I don't know how Dr. Kobushi is built. /CC @nadimkobeissi

DKLL for Linux is built on Ubuntu 22.04.1 LTS. Not sure what I'm supposed to do here: intentionally use old Linux distributions?

**Comment by hajimehoshi** [comment]
> DKLL for Linux is built on Ubuntu 22.04.1 LTS. Not sure what I'm supposed to do here: intentionally use old Linux distributions?

I mean I recommend building it under the Docker environment Steam provides.

**Comment by superloach** [comment]
This is a general glibc issue. I would recommend using the Steam build enviroment, and for general Linux distribution, either static linking or a fairly old glibc version.

**Comment by hajimehoshi** [comment]
I hope this issue will be resolved by #2284 in the future...

**Comment by nadimkobeissi** [comment]
For the record, we're now building Dr. Kobushi's Labyrinthine Laboratory on the Valve-provided SteamOS Docker image, so this issue should no longer apply to our game. That being said, the build process is now significantly more painful, so moving towards `purego` would be a benefit here.

**Comment by sedyh** [comment]
> For the record, we're now building Dr. Kobushi's Labyrinthine Laboratory on the Valve-provided SteamOS Docker image, so this issue should no longer apply to our game. That being said, the build process is now significantly more painful, so moving towards `purego` would be a benefit here.

After reuploading the new build in steam, it works fine.

**Comment by hajimehoshi** [comment]
I think the case is closed by using old glibc, which SteamSDK provides.
