### ISSUE TITLE
internal/gamepaddb: enable to use the database for Android

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2312]
This is forked from #2309 

> The current problem is, after I fixed a gamepad's GUID, the GUID is now correct but the button/axis assignments don't match with SDL's and the database's. This means that we cannot use the current database so far. Now Ebitengine prioritize the original mapping for Android so far, but I'd like to change the order of them later.

**Comment by hajimehoshi** [comment]
On Android, button IDs and axis IDs are SDL's rather than raw OS's. This seems weried, but the database says so...

**Comment by hajimehoshi** [comment]
https://github.com/libsdl-org/SDL/blob/47f2373dc13b66c48bf4024fcdab53cd0bdd59bb/src/joystick/android/SDL_sysjoystick.c

So SDL doesn't treat raw buttons and converts them to SDL buttons

**Comment by divVerent** [comment]
Notable:

On Linux, SDL uses a remapping that skips indices, so the buttons are always indices from 0 to n-1: https://github.com/libsdl-org/SDL/blob/f398d8a42422c049d77c744658f1cd2bb011ed4a/src/joystick/linux/SDL_sysjoystick.c#L1423

On Android, however, the same function is called with a direct SDL controller button enum (or an integer that is larger), meaning on Android the indices can have holes. This then also goes through this mapping function, which seems to generate a 1:1 mapping but in gamecontrollerdb style: https://github.com/libsdl-org/SDL/blob/42cf6d6c56faaa0a4f8876f92b7254176030833e/src/joystick/SDL_gamecontroller.c#L456 - very odd.

**Comment by hajimehoshi** [comment]
For axis, SDL doesn't use Android's AXIS_* constants but enumerates available axes:

https://github.com/libsdl-org/SDL/blob/2df2da11f627299c6e05b7e0aff407c915043372/android-project/app/src/main/java/org/libsdl/app/SDLControllerManager.java#L182-L216

Yeah this is odd, but actually this is what they are doing.
