### ISSUE TITLE
examples/sinewave: crash when plugging out a headphone on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2314]
```
oto: IAudioClient2::Start failed: HRESULT(2290679812)
```

I'll check whether this can be reproduced or not on my machine.

EDIT: This could be reproduced very easily at `examples/sinewave`

```
$ GOOS=windows go run -tags=example ./examples/sinewave/
2022/09/10 15:00:49 oto: IAudioClient2::GetCurrentPadding failed: HRESULT(2290679812)
```

**Comment by superloach** [comment]
https://www.hresult.info/FACILITY_AUDCLNT/0x88890004 looks like this error occurs anytime a device is unplugged. should probably be gracefully ignored

**Comment by superloach** [comment]
well, it should attempt to find a new device that isn't unplugged, probably...

**Comment by hajimehoshi** [comment]
I think so. I'll try to reproduce this later.

**Comment by hajimehoshi** [comment]
Hmm I couldn't reproduce this, so I'm not confident just retyring is safe.

**Comment by hajimehoshi** [comment]
OK I could reproduce this (examples/audio cannot since this uses the sample rate 32000 and WASAPI doesn't accept it)

**Comment by hajimehoshi** [comment]
https://github.com/microsoft/Xbox-GDK-Samples/blob/main/Samples/Audio/SimpleWASAPIPlaySound/WASAPIManager.cpp is a good example how to resume the audio.
