### ISSUE TITLE
Crash on windows when attempting to play a sound with no sound output device to use

### ISSUE THREAD

**Issue by cedriclikescode** [hajimehoshi/ebiten#2316]
Might be related to #2314
1. disable all sound output devices in System/sound
2. type `go run -tags=example github.com/hajimehoshi/ebiten/v2/examples/sinewave@latest`
Expected beheavior: program should work as normally but without sound (because there is no sound output devices to use).
What actually happened:
```
2022/09/10 07:49:45 oto: initialization failed: WASAPI: oto: IMMDeviceEnumerator::GetDefaultAudioEndPoint failed: HRESULT(2147943568), WinMM: oto: waveOutOpen failed: MMSYSERR_BADDEVICEID
exit status 1
```

https://user-images.githubusercontent.com/104719938/189471465-411222ce-0f73-49ae-a247-c93bdf35eb5f.mp4

**Comment by hajimehoshi** [comment]
I think such a environment wihtout any audio devices should be rare, so let me set the milestone to v2.5.0.

**Comment by hajimehoshi** [comment]
Confirmed
