### ISSUE TITLE
internal/gamepaddb: interpret "-a0" correctly

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2334]
SDL source has:

```
        if (half_axis_input == '+') {
            bind.input.axis.axis_min = 0;
            bind.input.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
        } else if (half_axis_input == '-') {
            bind.input.axis.axis_min = 0;
            bind.input.axis.axis_max = SDL_JOYSTICK_AXIS_MIN;
        } else {
            bind.input.axis.axis_min = SDL_JOYSTICK_AXIS_MIN;
            bind.input.axis.axis_max = SDL_JOYSTICK_AXIS_MAX;
        }
```

Ebitengine has:

```
                min := -1
                max := 1
                numstr := str[1:]

                if str[0] == '+' {
                        numstr = str[2:]
                        min = 0
                } else if str[0] == '-' {
                        numstr = str[2:]
                        max = 0
                }
```

Observe that for the case of a lone '-', SDL maps [0, -1] to [-1, 1], while Ebitengine maps [-1, 0] to [-1, 1].

Or in other words, if SDL needs "-a0" for a certain gamepad, Ebitengine would currently need "-a0~" which is wrong.

Reference: https://github.com/divVerent/aaaaxy/issues/28

**Comment by hajimehoshi** [comment]
Nice finding. Could you send a PR to fix?

**Comment by divVerent** [comment]
Will do.

**Comment by hajimehoshi** [comment]
Is the correct code like this

```go
                min := -1
                max := 1
                numstr := str[1:]

                if str[0] == '+' {
                        numstr = str[2:]
                        min = 0
                } else if str[0] == '-' {
                        numstr = str[2:]
                        min = 0
                        max = -1
                }
```

?

**Comment by hajimehoshi** [comment]
I just followed GLFW's way

https://github.com/glfw/glfw/blob/fe2ac5027b617234670d400f800c4b6f1e5f24bb/src/input.c#L172-L187

This seems the same as Ebitengine's, doesn't this?

**Comment by divVerent** [comment]
This would be correct, yes.

**Comment by divVerent** [comment]
I would think GLFW has the same issue.

Not sure if even a bug or if SDL changed meaning there.

**Comment by hajimehoshi** [comment]
The odd thing in the SDL is that `min` > `max` can be true when `-` is used.

**Comment by divVerent** [comment]
Yeah; the intent is that `-a0` means "+a0 but reversed", so if `+a0` means "move axis 0 right", `-a0` must mean "move axis 0 left" and not "leave axis 0 at center". That's the rationale behind this.

Now trying the fix on my own gamepad, to make sure it does what is intended.

BTW SDL has some extra features there too... e.g. I can also write `+leftx:a0` which transforms axis 0 range -1..1 to leftx range 0..1 (so idle is 0.5) - not sure what that is good for, but I see it in SDL's source. I checked BTW, SDL does it this way since 2016 (commit 6d7da0887d1474adb2060c25ba6076ea04870ade).

**Comment by divVerent** [comment]
I cannot yet confirm the fix - it doesn't appear to be working right yet. Gonna debug more later, as it _looks_ right.

For reference, I am trying this adjusted definition of my gamepad:

```
export SDL_GAMECONTROLLERCONFIG='03000000d6200000
0228000001010000,PowerA Wired Controller for Xbox One,a:b0,b:b1,back:b6,dpdown:+a1,dpleft:-a0,dpright:+a0,dpup:-a1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux'
```

**Comment by divVerent** [comment]
Yeah, there was a second bug, also shared with glfw. Fix sent.

**Comment by hajimehoshi** [comment]
Thanks. I have reviewed.

> also shared with glfw.

Where did you report this?

**Comment by divVerent** [comment]
As for the glfw issue, reporting that now.

**Comment by hajimehoshi** [comment]
Nice. Did you reproduce the issue with GLFW?

**Comment by divVerent** [comment]
I did not - I have no GLFW program or game to try it with.
