### ISSUE TITLE
Atlas mutex crash (WASM on Mobile Device)

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#2339]
The demo version of my game built for WASM works fine on desktop browsers, but fails on my android device's browser: https://corfe83.github.io/IdleArmada/

I'm trying to figure out why.  To try to reproduce it on desktop, I set my desktop chrome to run as a "device" in developer tools, and I got  this crash in console.log. Possibly related to why my game is crashing? It looks like some kind of mutex error in ebiten / atlas. Is this a bug in ebiten, or could it be a bug in my code?

Tinne on discord had a theory: https://discord.com/channels/842049801528016967/842056438632939570/1021552848045088901

This is in ebiten v2.4.3. I suspect others can reproduce the issue by going to the URL above and setting chrome to act as a "device" as in this screenshot. Then look at console.log output. You must set chrome mode to "device emulation" mode in chrome developer tools to reproduce:
![image](https://user-images.githubusercontent.com/61067263/191136142-a940f9fe-e8c3-4585-b004-fa673d9f2ced.png)

Callstack:
[EbitenAtlasMutexError.txt](https://github.com/hajimehoshi/ebiten/files/9602882/EbitenAtlasMutexError.txt)

**Comment by hajimehoshi** [comment]
Thank you for reporting. Do you have a minimal reproducible case for this? I could reproduce the bug on the desktop Chrome with the smartphone emulation.

**Comment by hajimehoshi** [comment]
The minimum reproducible case:

```go
package main

import (
	"log"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
)

const (
	screenWidth  = 640
	screenHeight = 480
)

type Game struct {}

func (g *Game) Update() error {
	time.Sleep(time.Second)
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return screenWidth, screenHeight
}

func main() {
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

**Comment by corfe83** [comment]
Yes, I think you're right. And I believe if you resize the window during that frame, another parallel frame gets rendered from this line:

https://github.com/hajimehoshi/ebiten/blob/2.4/internal/ui/ui_js.go#L483

**Comment by hajimehoshi** [comment]
Please try

```
go get github.com/hajimehoshi/ebiten/v2@ef262677038b3dd5ab732dbd40a1370d1da2c840
```

Thanks,

**Comment by corfe83** [comment]
I believe this fixed it -- thanks for the fast fix!
