### ISSUE TITLE
ebiten: deprecate `SetFPSMode` and `ScheduleFrame`, and undeprecate `SetVsyncEnabled`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2342]
We discussed #2338 and `FPSModeVsyncOffMinimum` is useless: as the vsync is off, tearing happens and GPU power is consumed more than necessary. We might want `FPSModeVsyncOnMinimum` but it is odd that a FPS mode affects `Update` behavior in the first place.

Instead, let's give up blocking `Update` call for input, and instead, let's focus on a new API to handle input (#1704). This (Update is still called 60 times per second) might not be the best efficiency but is acceptable.

At the same time, `ScheduleFrame` should be deprecated too.

**Comment by erexo** [comment]
If we are in an FPS area, I would like to remind that it would be really useful to be able to explicitly set the maximum FPS somehow, https://github.com/hajimehoshi/ebiten/issues/1562 .
Players with old computers are deliberately reducing their FPSes to be able to use the system while the game is running, and game developers (especially beginners) would be able to debug the game and check if FPS has any negative impact on the game (ie. if there is any logic in Draw that should be in Update)

**Comment by hajimehoshi** [comment]
But how do I adjust FPS (refresh rate)?

**Comment by hajimehoshi** [comment]
We'll rever the optimization of skipping to swap buffers.

**Comment by hajimehoshi** [comment]
I think we should make another issue.
