### ISSUE TITLE
Kage: initializing vectors has some confusing outcomes without errors if curly brace initialization is used

### ISSUE THREAD

**Issue by LoparPanda** [hajimehoshi/ebiten#2348]
I had mistakenly used curly-braces initialization to make `vec4`s that affected some output colors in a shader, and ended up with some very unexpected colors. It looks like it accepts curly-braces, and works with literals, but operates strangely if it's merged with other vectors like regular parentheses initialization. It also seems to compile with arbitrary numbers of arguments with the curly braces. I did figure out after a little bit that I was just doing it wrong :) but it seems like this might be worth being an error case, though probably a pretty low priority bug.

I made some non-comprehensive test cases for shader_test just to demonstrate some of the results, in case that's helpful:

```go
func TestVec4Initialization(t *testing.T) {
	const w, h = 1, 1

	dst := ebiten.NewImage(w, h)
	for _, tc := range []struct {
		initCode  string
		wantColor color.RGBA
		wantErr   bool
	}{
		{
			initCode:  "vec4(0.25, 0.5, 0.75, 1.0)",
			wantColor: color.RGBA{64, 128, 192, 255},
		},
		{
			initCode:  "vec4{0.25, 0.5, 0.75, 1.0}",
			wantColor: color.RGBA{64, 128, 192, 255},
		},
		{
			initCode:  "vec4{0.25, 0.5}",
			wantColor: color.RGBA{64, 128, 0, 0},
		},
		{
			initCode: "vec4(0.25, 0.5)",
			wantErr:  true,
		},
		{
			initCode:  "vec4(vec2(0.25, 0.5), vec2(0.75, 1.0))",
			wantColor: color.RGBA{64, 128, 192, 255},
		},
		{
			initCode:  "vec4{vec2(0.25, 0.5), vec2(0.75, 1.0)}",
			wantColor: color.RGBA{64, 128, 192, 255},
		},
		{
			initCode:  "vec4(vec2{0.25, 0.5}, vec2(0.75, 1.0))",
			wantColor: color.RGBA{64, 128, 192, 255},
		},
		{
			initCode:  "vec4(vec2{0.25, 0.5}, vec2{0.75, 1.0})",
			wantColor: color.RGBA{64, 128, 192, 255},
		},
		{
			initCode: "vec4(vec2(0.25, 0.5))",
			wantErr:  true,
		},
		{
			initCode: "vec4{vec2(0.25, 0.5)}",
			wantErr:  true,
		},
		{
			initCode: "vec4{0.25, 0.5, 0.75, 1.0, 1.25}",
			wantErr:  true,
		},
	} {
		t.Run(tc.initCode, func(t *testing.T) {
			s, err := ebiten.NewShader([]byte(fmt.Sprintf(`package main
				var Mat2 mat2
				var F float

				func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
					return %s
				}
				`, tc.initCode)))
			if err != nil {
				if !tc.wantErr {
					t.Fatal(err)
				}
				return
			} else if tc.wantErr {
				t.Errorf("err == nil, want non-nil")
			}

			dst.DrawRectShader(w, h, s, nil)
			got := dst.At(0, 0).(color.RGBA)
			if !sameColors(got, tc.wantColor, 2) {
				t.Errorf("dst.At(0, 0) = %v, want: %v", got, tc.wantColor)
			}
		})
	}
}
```

One more concerning spot was the last test case, where I exceeded the 4 element count, and instead of returning an error, it panicked at the `dst.At` call with a direct3d compile error.

(I didn't try initializing matrices or anything else so I'm not sure if it's an issue anywhere else)

**Comment by hajimehoshi** [comment]
We should not accept `{}` for `vec4` as this is not a struct.

**Comment by LoparPanda** [comment]
One extra data point, if I tested `vec4(0.25, 0.5, 0.75, 1.0, 1.25)` with proper parens it does return a compile error at `NewShader` as expected, so having the curly braces error entirely would also catch the panic issue early.

**Comment by hajimehoshi** [comment]
> One extra data point, if I tested vec4(0.25, 0.5, 0.75, 1.0, 1.25) with proper parens it does return a compile error at NewShader as expected, so having the curly braces error entirely would also catch the panic issue early.

Wasn't this fixed after https://github.com/hajimehoshi/ebiten/commit/f89277fd85ee39a0baf599f7a9c62791d1611d7d ?
