### ISSUE TITLE
examples/windowsize: the green button is unexpectedly enabled on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2349]
1. Press F to make the window fullscreen (the window is still unresizable)
2. Press F to exit the fullscreen
3. Check the green button. This should be disabled, but was enabled.

**Comment by hajimehoshi** [comment]
This is on the main branch and not v2.4.

**Comment by hajimehoshi** [comment]
043397c20ebe5962b252c0512885592dedf853c3 is the culprit.

**Comment by hajimehoshi** [comment]
FYI @TotallyGamerJet

**Comment by TotallyGamerJet** [comment]
Good find! Are the casts actually needed? Or was it just the wrong operators?
