### ISSUE TITLE
ebiten: add `ColorScale` to `DrawRectShaderOptions`

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2361]
I need to pass color attributes to my shader by still using `DrawRectShader`, it's possible using triangles because we can specify them.
My use case is the need of passing extra data to the shader as a `vec4` without redefining an uniform value for each `DrawRectShader` because this prevents batching, therefore breaks my performances (tested).

I don't mind the implementation, I originally thought about providing `ColorM` to `DrawRectShaderOptions` since it already provides `GeoM`.

A reference: https://github.com/hajimehoshi/ebiten/issues/2171

**Comment by hajimehoshi** [comment]
Yeah, adding `ColorScale` suggested at #2171 to `DrawRectShaderOptions` should solve the issue.

**Comment by hajimehoshi** [comment]
Reopened this as we might change the scale to premultiplied-alpha style

**Comment by hajimehoshi** [comment]
Instead of `ColorScale`, `color.Color` might be better 🤔
