### ISSUE TITLE
Do you plan to support GIF format?

### ISSUE THREAD

**Issue by wangborong12345** [hajimehoshi/ebiten#2363]
Do you plan to support GIF format? love you

**Comment by hajimehoshi** [comment]
No so far. Do you request this?

**Comment by hajimehoshi** [comment]
Duplicated with #416

**Comment by hajimehoshi** [comment]
For non-animation GIFs, you can use `image/gif`

**Comment by superloach** [comment]
Doesn't `image/gif` also support multiple frames? It should be fairly straightforward to write a system that renders each frame into a set if Ebitengine images. Not a necessary feature for the library itself, although it might be useful in a util library
