### ISSUE TITLE
ebiten: use premultipled alpha scales for `Vertex.ColorR`/`G`/`B`/`A`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2365]
From https://github.com/hajimehoshi/ebiten/pull/1996

I realized I might have to use pre-multipled alpha scales for colors in vertices for consistency with other APIs. Now the built-in vertex shader converts the scale from straight-alpha scales to premultiplied-alpha sclaes, but this prevents us from converting the built-in shaders to Kage shaders.

Adding a customizable vertex shader (#2209) instead of not changing the interpretation of scales might be another option.

This will be a breaking change so we might not be able to change them.

@divVerent What do you think? Do you think using premultiplied-alpha scaling would be better in terms of consistency?

Related #2361 /CC @Zyko0

**Comment by hajimehoshi** [comment]
Considering linear interpolation of shaders, it seems more natural to use premultiplied-alpha values instead of straight-alpha values for scaling.

**Comment by hajimehoshi** [comment]
In order to keep backward compatibility, I think I'll add this enum for `DrawTrianglesOptions`

```go
type ColorScaleType int

type DrawTrianglesOptions struct {
    // ...

    // ColorScaleType indicates how the color scale part is used.
    //
    // When this is ColorScaleTypeStraightAlpha, the color scale is converted to the premultiplied-alpha internally.
    // If the performance matters, use ColorScaleTypePremultipliedAlpha.
    //
    // The default (zero) value is ColorScaleTypeStraightAlpha.
    ColorScaleType ColorScaleType
    // ...
}

const (
    ColorScaleTypeStraightAlpha ColorScaleType = iota
    ColorScaleTypePremultipliedAlpha
)
```

**Comment by divVerent** [comment]
Supporting premultiplied alpha means RGBA will be treated all the same, which allows using color as a generic vertex attribute (e.g. normal vector + light amount) instead. Would even enable some weak amount of 3D rendering.

**Comment by hajimehoshi** [comment]
OK I'll go with the option. Also I'll deprecate the straight-alpha version in v3.

> Would even enable some weak amount of 3D rendering.

Is that true? In `DrawTriangles` (not `DrawTrianglesShader`), would a user can do that?
