### ISSUE TITLE
internal/ui: Access Denied in `SetProcessDpiAwareness`

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2366]
One of my players is unable to launch the game using OpenGL, application panics at init with comment:
```
panic: glfwwin: SetProcessDpiAwareness failed: Access is denied.
goroutine 1 [running]:
github.com/hajimehoshi/ebiten/v2/internal/ui.init.2()
        C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/ui/ui_glfw.go:151
 +0xa8
 ```
 
His specs are:
OS: Win8
CPU: Intel(R) Pentium(R) CPU N3540  @ 2.16Ghz 
RAM: 4gb
GPU: Intel(R) HD Graphics

and the app was build using:
`GOOS=windows GOARCH=amd64 CGO_ENABLED=0 go build `

I'm not really sure what caused this and how "Access denied" should be treated here

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look.

Does this happen when the screen is locked?

Similar issue: https://github.com/hajimehoshi/ebiten/commit/47c65a92aeff143933761b3a9689f13c6c728ad9

**Comment by erexo** [comment]
I'm not sure and sadly I can't ask that player anymore since he stopped gaming.
I doubt it because he claimed that he just download the client and it was not working out of the box

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/blob/f6c4b29a3ddb0bee5a6e2001229f21bf6bc2559d/internal/glfwwin/win32init_windows.go#L249

There is already a code to handle this error. Hmm?

**Comment by hajimehoshi** [comment]
Oh, the error handling doesn't seem correct...

```go
ERROR_ACCESS_DENIED                                                       syscall.Errno = 5
```

while `E_ACCESSDENIED` is `0x80070005`

**Comment by hajimehoshi** [comment]
I'll check all the usages of `windows.ERROR_*` later.

**Comment by hajimehoshi** [comment]
I think this should fix the issue:

```sh
go get github.com/hajimehoshi/ebiten/v2@2b261c63149abebb81b4588e361472618b3a8d4c
```

Thank you for reporting this!

**Comment by hajimehoshi** [comment]
Have you confirmed the fix? (If might no longer be possible to confirm, but I'm asking just in case)

**Comment by erexo** [comment]
sadly no, it would be hard for me now to confirm it. I think we can mark this issue as resolved :)

**Comment by hajimehoshi** [comment]
I got it. Thanks!
