### ISSUE TITLE
ebiten: custom blend function/equation support

### ISSUE THREAD

**Issue by LoparPanda** [hajimehoshi/ebiten#2382]
The port I'm working on requires a specific subtractive blend mode for certain special effects:
```c
glBlendFuncSeparate(/* srcRgb */ GL_ONE, /* dstRgb */ GL_ONE, /* srcA */ GL_ZERO, /* dstA */ GL_ONE);
glBlendEquationSeparate(/* rgb */ GL_FUNC_REVERSE_SUBTRACT, /* a */ GL_FUNC_ADD);
```
Currently Ebitengine uses `glBlendFunc` and `glBlendEquation` without separating RGB and Alpha, and also defines specific choices for compositing. Having a way to specify custom blend funcs and equations for RGB/A would help to support these more niche blend modes without them having to be new built-in modes.

I thus far have been able to hack in my specific blend into OpenGL and DirectX (and will do Metal eventually if I need to). OpenGL required adding new bindings for the `*Separate` functions, while DirectX already supported splitting RGB/A and just needed to provide different values. I figure though if it's an engine feature it would be much nicer as an API than a hacked in extra composite mode. :)

**Comment by hajimehoshi** [comment]
Related: #1450

**Comment by hajimehoshi** [comment]
Note to myself:

OpenGL: https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlendFunc.xhtml
WebGL: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendFunc
Metal: https://developer.apple.com/documentation/metal/mtlblendfactor?language=objc
DirectX: https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_blend
Unity: https://docs.unity3d.com/Manual/SL-Blend.html

**Comment by hajimehoshi** [comment]
Equations:

OpenGL: https://registry.khronos.org/OpenGL-Refpages/gl4/html/glBlendEquationSeparate.xhtml
WebGL: https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/blendEquationSeparate
Metal: https://developer.apple.com/documentation/metal/mtlblendoperation?language=objc
DirectX: https://learn.microsoft.com/en-us/windows/win32/api/d3d12/ne-d3d12-d3d12_blend_op
Unity: https://docs.unity3d.com/Manual/SL-BlendOp.html

The common set seems:

* Add
* Subtract
* Reverse Subtract
* Min (not in WebGL 1)
* Max (not in WebGL 1)

**Comment by hajimehoshi** [comment]
@LoparPanda I'll ad more blend factors, but I think you should be able to use the subtract effect like this:

```go
op := &ebiten.DrawImageOptions{}
op.Blend = ebiten.Blend{
    BlendFactorSourceColor:      ebiten.BlendFactorOne,
    BlendFactorSourceAlpha:      ebiten.BlendFactorZero,
    BlendFactorDestinationColor: ebiten.BlendFactorOne,
    BlendFactorDestinationAlpha: ebiten.BlendFactorOne,
    BlendOperationColor:         ebiten.BlendOperationReverseSubtract,
    BlendOperationAlpha:         ebiten.BlendOperationAdd,
}
```

(The API like struct member names might be changed later.)

Thanks,

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/actions/runs/3262359687/jobs/5359402063

`GL_SRC_ALPHA_SATURATE` might be broken on some platforms 🤔

**Comment by hajimehoshi** [comment]
With OpenGLES, all `GL_ONE` blending doesn't work??

https://github.com/hajimehoshi/ebiten/actions/runs/3262359689/jobs/5360189809

```
=== RUN   TestImageBlendFactor
    image_test.go:3863: dst.At(0, 0): factors: 1, 1, 1, 1: got: {0 1 2 3}, want: {0 0 0 0}
    image_test.go:3863: dst.At(1, 0): factors: 1, 1, 1, 1: got: {52 53 54 55}, want: {0 0 0 0}
    image_test.go:3863: dst.At(2, 0): factors: 1, 1, 1, 1: got: {104 105 106 107}, want: {0 0 0 0}
    image_test.go:3863: dst.At(3, 0): factors: 1, 1, 1, 1: got: {156 157 158 159}, want: {0 0 0 0}
    image_test.go:3863: dst.At(4, 0): factors: 1, 1, 1, 1: got: {208 209 210 211}, want: {0 0 0 0}
    image_test.go:3863: dst.At(5, 0): factors: 1, 1, 1, 1: got: {4 5 6 7}, want: {0 0 0 0}
    image_test.go:3863: dst.At(6, 0): factors: 1, 1, 1, 1: got: {56 57 58 59}, want: {0 0 0 0}
    image_test.go:3863: dst.At(7, 0): factors: 1, 1, 1, 1: got: {108 109 110 111}, want: {0 0 0 0}
    image_test.go:3863: dst.At(8, 0): factors: 1, 1, 1, 1: got: {160 161 162 163}, want: {0 0 0 0}
    image_test.go:3863: dst.At(9, 0): factors: 1, 1, 1, 1: got: {212 213 214 215}, want: {0 0 0 0}
    image_test.go:3863: dst.At(10, 0): factors: 1, 1, 1, 1: got: {8 9 10 11}, want: {0 0 0 0}
    image_test.go:3863: dst.At(11, 0): factors: 1, 1, 1, 1: got: {60 61 62 63}, want: {0 0 0 0}
    image_test.go:3863: dst.At(12, 0): factors: 1, 1, 1, 1: got: {112 113 114 115}, want: {0 0 0 0}
    image_test.go:3863: dst.At(13, 0): factors: 1, 1, 1, 1: got: {164 165 166 167}, want: {0 0 0 0}
    image_test.go:3863: dst.At(14, 0): factors: 1, 1, 1, 1: got: {216 217 218 219}, want: {0 0 0 0}
    image_test.go:3863: dst.At(15, 0): factors: 1, 1, 1, 1: got: {12 13 14 15}, want: {0 0 0 0}
```

**Comment by hajimehoshi** [comment]
Now APIs for blending have been implemented!
