### ISSUE TITLE
Repository hygiene: .github/*TEMPLATE**

### ISSUE THREAD

**Issue by Skenvy** [hajimehoshi/ebiten#2405]
This is a meta feature request -- for a project with so many forks it'd be a _good idea_ to have a [PULL_REQUEST_TEMPLATE.md](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) and a set of [ISSUE_TEMPLATE](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms)'s (i.e. for bug reporting, feature requests, and security vulnerabilities).

**Comment by hajimehoshi** [comment]
Sounds nice but do you have a concrete suggestion of the templates?

**Comment by Skenvy** [comment]
I'd err on the side of an abundance of fields that could be optional. For the `ISSUE_TEMPLATE`'s I'd suggest;
* `.github/ISSUE_TEMPLATE/feature-request.yaml` should be minimal and open ended but request justification.
  * apply label `feature`
  * **Required** `textarea` "What would you like to be added?"
  * **Required** `textarea` "Why is this needed?"
* `.github/ISSUE_TEMPLATE/security-vulnerability.yaml` should be minimal and easy to submit with limited justification; i.e. just a CVE should be enough if there is a relevant one.
  * apply label `security`
  * **Required** `textarea` "What vulnerability have you discovered? Include any relevant details like a CVE."
  * _Optional_ `textarea` "What remediation steps are known, if any."
* `.github/ISSUE_TEMPLATE/bug-report.yaml` should be extensive and require a strict path to reproducing the bug
  * apply label `bug`
  * **Required** `textarea` "Ebitengine Version"
  * **Required** `dropdown` "Operating System"
  * **Required** `dropdown`|`textarea` "Go Version"
  * **Required** `textarea` "What were you doing (steps to reproduce the bug)?"
  * **Required** `textarea` "What actually happened as a result?"
  * **Required** `textarea` "What did you expect to happen?"
  * _Optional_ `textarea` "If you have a stack trace, please add it here."
  * _Optional_ `textarea` "Anything else you feel useful to add?"

**Comment by Skenvy** [comment]
For the `.github/PULL_REQUEST_TEMPLATE.md` I'd suggest something minimal such as the following, that points to the contrib and coc, and suggests the reference to the issue it's addressing.
```
<!--
Thanks for sending a pull request!
If this is your first time, please read the contributor guidelines:
https://github.com/hajimehoshi/ebiten/blob/main/CONTRIBUTING.md
Also please adhere to our Code of Conduct:
https://github.com/hajimehoshi/ebiten/blob/main/CODE_OF_CONDUCT.md
-->
# What issue is this addressing?
<!-- Fixes #<issue number> -->
## What _type_ of issue is this addressing?
<!-- bug | feature | security -->
## What this PR does | solves
<!-- Please be as descriptive as possible -->
```

**Comment by Skenvy** [comment]
I'd be happy to put them together, if those suggestions are alright?

**Comment by hajimehoshi** [comment]
Your suggestion basically seems fine.

* We don't need a template for security issues.
* Can we add OS tags automatically?

Yes, I'd be happy if you could create a PR.

**Comment by Skenvy** [comment]
Unfortunately the labels applied are static, although dynamic tags would be a great feature. If you want automatic dynamic tags, the current way to implement that is with https://github.com/github/issue-labeler -- which would be easy enough to add as well.

**Comment by hajimehoshi** [comment]
I mean I was wondering if os: labels were added based on the user's choice of the "Operating System" dropdown.

**Comment by Skenvy** [comment]
Will PR this later today; just want to confirm that you're sure you don't want a security issue template? It'd tie in to any future `SECURITY.md` for instance. i.e. if there was a more serious security issue than currently the only security advisory on https://deps.dev/go/github.com%2Fhajimehoshi%2Febiten%2Fv2/v2.4.8, `GO-2022-1059`, then it'd be the place to report them.

Besides that, just wondering what OS's you'd like in it? So far it's a combination of the ones listed in the readme and some in other tags. Any you want added or removed from the list?
```yaml
options:
  - Windows
  - MacOS
  - Linux
  - FreeBSD
  - OpenBSD
  - Android
  - iOS
  - Nintendo Switch
  - XBox
```

With regards to adding the tags automatically, the issue-labeler action could be used to do that, but it's just a regex parser; i.e. it could be set to add the `os:windows` label if it reads "Windows" in the text of the issue.

**Comment by hajimehoshi** [comment]
>  if there was a more serious security issue than currently the only security advisory on https://deps.dev/go/github.com%2Fhajimehoshi%2Febiten%2Fv2/v2.4.8, GO-2022-1059, then it'd be the place to report them.

This seems like a false positive. Ebitengine doesn't depend on x/text, so I'm not sure what to do.

> Besides that, just wondering what OS's you'd like in it? So far it's a combination of the ones listed in the readme and some in other tags. Any you want added or removed from the list?

Please add "Web Browsers" (GOOS=js, tag "os:js").

> XBox

I think "Xbox" is correct.

**Comment by hajimehoshi** [comment]
Probably one of the dependency used x/text. I'll take a look later.

>  just want to confirm that you're sure you don't want a security issue template? It'd tie in to any future SECURITY.md for instance

What is SECURITY.md?

**Comment by hajimehoshi** [comment]
https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository

I see.. I don't have a concrete policy so far. Do we have to determine the policy first?

**Comment by Skenvy** [comment]
Nah, you can add a policy seperate from adding the template. The template for reporting security issues is very minimal to remove any obstacles from raising that type of issue. Often, a security policy will often point to raising a new security issue _amongst whatever other details it describes_ i.e. what versions would get updates if they had issues, like if there's backwards support or if it's only supported forwards.

But yea totally fine to have the issue template first.

**Comment by hajimehoshi** [comment]
OK, so let's add `security-vulnerability.yaml` (or another name?) and revisit `SECURITY.md` later. Thanks!
