### ISSUE TITLE
ebiten.SetVsyncEnabled() causes a hang for me on IOS

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#2407]
In my simple repro, calling this function on the first frame's update call causes the app to hang (doesn't crash).

Hopefully the repro is as easy as calling this function. I'm using ebiten 2.4.8.

**Comment by hajimehoshi** [comment]
I'll take a look, thanks!

**Comment by hajimehoshi** [comment]
@corfe83 Have you called `ebiten.SetVsyncEnabled(true)` or `ebiten.SetVsyncEnabled(false)`?

**Comment by corfe83** [comment]
Sorry, I should have said I was calling 

`ebiten.SetVsyncEnabled(true)`

**Comment by hajimehoshi** [comment]
As vsync is enabled by default, you don't have to call `SetVsyncEnabled(true)`

On the other hand, calling `SetVsyncEnabled(true)` should not cause freezing. I'll keep investigating (maybe tomorrow)

**Comment by corfe83** [comment]
Thanks, it's a very old line of code added a year or so ago. I'll plan to remove it.

**Comment by hajimehoshi** [comment]
I could reproduce this issue by inserting `SetVsyncEnabled(true)` in `Update`.
