### ISSUE TITLE
update dependency on `golang.org/x/text/language`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2411]
Forked from #2405

https://pkg.go.dev/vuln/GO-2022-1059

```
$ go mod why golang.org/x/text/language
# golang.org/x/text/language
github.com/hajimehoshi/ebiten/v2/text
github.com/hajimehoshi/ebiten/v2/text.test
github.com/hajimehoshi/bitmapfont/v2
golang.org/x/text/language
```

The impact is very limited.

**Comment by tinne26** [comment]
The impact is actually zero. Only this code was added to `ParseAcceptLanguage`:
```Golang
if strings.Count(s, "-") > 1000 {
	return nil, nil, errTagListTooLarge
}
```
...to prevent attacks based on a malicious HTTP header, but bitmapfont doesn't use that method at all, only `Parse()` which is not affected.

**Comment by hajimehoshi** [comment]
An Ebitengine user might use x/text without specifying its version explicitly. In this case there is a potential volunability, so the impact is not zero to be exact (I think this is really close to zero though)
