### ISSUE TITLE
Standard layout is not working in Firefox under wasm

### ISSUE THREAD

**Issue by quasilyte** [hajimehoshi/ebiten#2424]
### Ebitengine Version

v2.3.7 + reproduces on v2.4.9 (latest) too

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.18.1

### What steps will reproduce the problem?

1. Run `examples/gamepad` via `wasmserve`:

```
wasmserve --tags example ./examples/gamepad
```

2. Open the firefox browser at `localhost:8080` (my firefox version is 105.0)

3. Connect the gamepad that is recognized as having a standard layout in a native build

### What is the expected result?

Gamepads are recognized as having a standard layout inside FF.

### What happens instead?

A gamepad is not recognized as a standard layout gamepad inside FF browser.

### Anything else you feel useful to add?

Running the game from firefox:

![image](https://user-images.githubusercontent.com/6286655/198865490-9a7d3af6-afc4-47ed-b1a1-52133d6cd042.png)

Running the Linux game:

![image](https://user-images.githubusercontent.com/6286655/198865502-29afca8d-12d5-49ac-b718-1f2c6d24e02c.png)

```
2022/10/30 10:30:54 Gamepad (ID: 0, SDL ID: 030000005e0400008e02000014010000) (Standard Layout):
  Name:    X360 Controller
```

Running it from chrome (works as expected, although the gamepad name/model seems different):

![image](https://user-images.githubusercontent.com/6286655/198865526-ce3c26c0-5698-42c3-b1f7-9ed088a3f8fc.png)

Maybe firefox doesn't support xinput gamepads or something?
I'm reporting this issue as searching the GitHub tracker gave no results for this.

I've tried two gamepads. Both are recognized as standard, but have this very issue in the FF browser.

![image](https://user-images.githubusercontent.com/6286655/198865687-103696d3-7a3b-4b34-a990-0fb211fcef6f.png)

![image](https://user-images.githubusercontent.com/6286655/198865696-a3d10db4-5a18-4f43-9d10-066aa6c52891.png)

```
2022/10/30 10:30:27 Gamepad (ID: 0, SDL ID: 030000006d0400001dc2000014400000) (Standard Layout):
  Name:    Logitech F310 Gamepad (XInput)
```

Some tags for an easier search: `gamepad`, `wasm`, `firefox`, `standard layout`, `sdl`.

## Why is it a problem?

Without a standard layout, it's harder to handle the gamepad inputs.

It's especially sad when some gamepad is actually a "standard" from the SDL database point of view, but it's failed to be mapped as such.

**Comment by quasilyte** [comment]
Thanks to the author and all the contributors for this wonderful project. :heart:

**Comment by hajimehoshi** [comment]
Hi!

Could you try https://gamepad-tester.com/ on your Firefox and Chrome?

Thanks,

**Comment by hajimehoshi** [comment]
> It's especially sad when some gamepad is actually a "standard" from the SDL database point of view, but it's failed to be mapped as such.

On browsers, Ebitengine relies on the browser's standard mapping, not the SDL database.

**Comment by quasilyte** [comment]
![image](https://user-images.githubusercontent.com/6286655/198866606-7a007a4a-6a67-478d-9e3e-bf6107f4add9.png)

![image](https://user-images.githubusercontent.com/6286655/198866624-8f01aa7f-a0e2-43db-a68d-f813c8e1c018.png)

**Comment by quasilyte** [comment]
When googling, I found this: https://bugzilla.mozilla.org/show_bug.cgi?id=855364

But this bug is way too old to be relevant, probably.

**Comment by hajimehoshi** [comment]
So unfortunately there is nothing we can do. The SDL database doesn't support browsers anyway.
