### ISSUE TITLE
util.go is missing from package

### ISSUE THREAD

**Issue by coneheed** [hajimehoshi/ebiten#2427]
### Ebitengine Version

2.4.9

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.18.3 darwin/amd64

### What steps will reproduce the problem?

Create a very simple project with a go.mod that contains:

`require github.com/hajimehoshi/ebiten/v2 v2.4.9`

Imports as follows:
```
import (
	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/vector"
)
```

Attempt to use the following in your code:
`
vector.DrawFilledCircle()
`

Compiler reports:
`undefined: vector.DrawFilledCircle`

This can be seen by browsing to the package here: https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/vector

There is no mention of the Public functions in util.go

Inspecting the file system shows that util.go is missing:

```
% ls go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.9/vector 
path.go
```

### What is the expected result?

vector.DrawFilledCircle function should be available

### What happens instead?

Compiler error

### Anything else you feel useful to add?

Many thanks!

**Comment by hajimehoshi** [comment]
vector.DrawFilledCircle is not available in v2.4. This was introduced as of v2.5.

Thanks,

**Comment by coneheed** [comment]
Thank you for fast response!

Apologies if I am missing something but I still do not see it in latest 2.5 alpha version

```
require github.com/hajimehoshi/ebiten/v2 v2.5.0-alpha.4
```

```
% ls -a go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.4/vector 
.       ..      path.go
```

https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.4/vector

**Comment by hajimehoshi** [comment]
Yeah this was introduced after v2.5.0-alpha.4. Try

```
go get github.com/hajimehoshi/ebiten/v2@083835af9accf611ad087a5d81e7b38131787e70
```

**Comment by coneheed** [comment]
Perfect. Thank you so much

**Comment by hajimehoshi** [comment]
For v2.4, you can use DrawCircle https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/ebitenutil#DrawCircle by the way.
