### ISSUE TITLE
Calling SubImage results in images which lack changes which were previously made to the parent image using Set

### ISSUE THREAD

**Issue by AmanitaVerna** [hajimehoshi/ebiten#2428]
### Ebitengine Version

2.4.10

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.2

### What steps will reproduce the problem?

1. Call image.NewRGBA and fill its Pix buffer with all one color.
2. Feed said image to ebiten.NewImageFromImage to get an *ebiten.Image.
3. Set pixels on your *ebiten.Image using Set.
4. Verify that they match what you set them to by calling At.
5. Call SubImage with a rect that contains the pixels that you set.
6. Check said pixels in the subimage by calling At, to see if they match what you set them to in step 3.

### What is the expected result?

That the pixel colors returned by At in step 6 would match the pixel colors which were set in step 3.

### What happens instead?

They instead match the pixel colors originally set on the source image in step 1. It seems like SubImage is somehow getting an old version of the image before Set was called on it.

### Anything else you feel useful to add?

I have only tested this on Windows. It seems to happen with both DirectX and OpenGL, at least on my PC. I don't know whether it happens on other OSes, and I don't know for certain what the actual cause is, so I haven't written any kind of patch for it (I also really don't understand Ebitengine's internals well enough to write one).

I've published a test on github which demonstrates this here: https://github.com/AmanitaVerna/ebitenSubimageTest

It doesn't seem to matter how the *ebiten.Image is created - I had code which created an *ebiten.Image and then set its initial pixel data with WritePixels, and then used Set to change a few of the pixels, and that exhibited this problem as well, but it was only the changes made by Set which were lost in the subimages.

And as a final note, setting pixels with Set and then creating SubImages worked on ebitengine 2.3.8 (and 2.3.5, and I don't remember what other versions I used before 2.3.5), and is broken on (at least - I didn't test every 2.4.* version) 2.4.0, 2.4.7, 2.4.8, 2.4.9, and 2.4.10.

**Comment by hajimehoshi** [comment]
```go
func TestImageSetAndSubImage(t *testing.T) {                                                                                                                                                                                                                                          
        const w, h = 16, 16                                                                                                                                                                                                                                                           
        img := ebiten.NewImage(w, h)                                                                                                                                                                                                                                                  
        img.Set(1, 1, color.RGBA{0xff, 0, 0, 0xff})                                                                                                                                                                                                                                   
        got := img.SubImage(image.Rect(0, 0, w, h)).At(1, 1).(color.RGBA)                                                                                                                                                                                                             
        want := color.RGBA{0xff, 0, 0, 0xff}                                                                                                                                                                                                                                          
        if got != want {                                                                                                                                                                                                                                                              
                t.Errorf("got: %v, want: %v", got, want)                                                                                                                                                                                                                              
        }                                                                                                                                                                                                                                                                             
}
```

Confirmed this test failed with v2.4. This test passed with v2.5.

**Comment by hajimehoshi** [comment]
Thank you for reporting. Please try

```
go get github.com/hajimehoshi/ebiten/v2@aecbf2344d597236821d5ee2f9ccbef46793e4a8
```

I'll release v2.4.11 including the fix few days later.
