### ISSUE TITLE
the go api text package does't include util.go file,please check！！！

### ISSUE THREAD

**Issue by eagle-1949** [hajimehoshi/ebiten#2434]
### Ebitengine Version

2.4.10

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19

### What steps will reproduce the problem?

check this url https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2@v2.4.10/vector
it does't include function DrawFilledRect,etc

### What is the expected result?

fix it

### What happens instead?

the function is go away

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/2427
