### ISSUE TITLE
examples/windowsize: F doesn't fullscreen window

### ISSUE THREAD

**Issue by TotallyGamerJet** [hajimehoshi/ebiten#2437]
### Ebitengine Version

@50021ef

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19 darwin/arm64

### What steps will reproduce the problem?

Run examples/windowsize and then press F

### What is the expected result?

The window goes into fullscreen

### What happens instead?

The window does nothing.

### Anything else you feel useful to add?

I think this is a bug inside of purego since I reverted commit #2329 and it was still broken.

**Comment by hajimehoshi** [comment]
I couldn't reproduce the issue. I've succeeded to make the window fullscreen by pressing F.

```
                    'c.          hajimehoshi@Hajimes-MacBook-Pro-2020.local 
                 ,xNMM.          ------------------------------------------ 
               .OMMMMo           OS: macOS 12.6 21G115 x86_64 
               OMMM0,            Host: MacBookPro16,2 
     .;loddo:' loolloddol;.      Kernel: 21.6.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 51 days, 9 hours, 1 min 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 188 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 3.2.57 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1680x1050@2x 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-1068NG7 (8) @ 2.30GHz 
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel Iris Plus Graphics 
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 21394MiB / 32768MiB 
       .cooc,.    .,coo:.
                                                         
                                                         
```

**Comment by hajimehoshi** [comment]
Ebitengine tries to make the window resizable temporarily:  https://github.com/hajimehoshi/ebiten/blob/50021ef3e4e3028e81ee77e3763a2b248cc8666f/internal/ui/ui_glfw_darwin.go#L273-L290

**Comment by TotallyGamerJet** [comment]
This actually might be a change in macOS 13 Ventura. Because once the window is able to be resized (using R)  I am able to press F and the window goes into fullscreen.

**Comment by TotallyGamerJet** [comment]
The program is trying to do something since the frames drop from 120 to ~60 when you spam F.

**Comment by hajimehoshi** [comment]
I'll take a look later with macOS 13...

**Comment by hajimehoshi** [comment]
Confirmed this is reproducible with macOS 13, with both Ebitengine 2.4 and main.

**Comment by hajimehoshi** [comment]
Also, `WindowResizingModeOnlyFullscreenEnabled` didn't work correctly.
