### ISSUE TITLE
can not call rungame in goroutine

### ISSUE THREAD

**Issue by Nyx2022** [hajimehoshi/ebiten#2441]
### Ebitengine Version

2.4.11

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19

### What steps will reproduce the problem?

go func() {
		if err := ebiten.RunGame(fdt); err != nil {
			log.Fatal(err)
		}
	}()

### What is the expected result?

run as 
if err := ebiten.RunGame(fdt); err != nil {
			log.Fatal(err)
		}

### What happens instead?

the window can not show , or the window is very lagged

### Anything else you feel useful to add?

add a function that can rungame asyncly

**Comment by hajimehoshi** [comment]
https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2#RunGame

> RunGame must be called on the main thread. Note that Ebitengine bounds the main goroutine to the main OS thread by runtime.LockOSThread.
