### ISSUE TITLE
Add additional mouse Keys

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2445]
### What feature would you like to be added?

I would like to be able to detect the state of additional mouse buttons (preferably as keys).
Currently we can monitor Left, Right and Middle mouse buttons but there might be more buttons on the mouse that we could utilize. ie. Unity has specific Key codes for such Keys (Mouse3-6) [Unity Docs](https://docs.unity3d.com/ScriptReference/KeyCode.Mouse3.html)

### Why is this needed?

In my game I have actions that could be assigned by the users to their preferable Keys, and some players reported that they would like to assign some of the most frequently used actions to their mouse and it would be very convenient for them

**Comment by erexo** [comment]
I know that such Keys suits better on `ebiten.MouseButton` rather than `input.Key`, but why do we need this separation in the first place? Wouldn't it be wise to get rid of the `ebiten.MouseButton` and move all the buttons there to the `input.Key` in 3.0.0 or sooner?

**Comment by hajimehoshi** [comment]
I set the milestone temporarily. I might change this later but I need more investigation anyway.

**Comment by hajimehoshi** [comment]
Yeah, if you can work on this, I welcome your work. Please share your plan before implementing it.

**Comment by erexo** [comment]
Primarily I would like to add `KeyMouse4`, `KeyMouse5`, `KeyMouse6`, `KeyMouse7` to the `ebiten.Key` enum and try to correctly integrate those new keys. If I succeed I would like to add `KeyMouseLeft`, `KeyMouseRight` and `KeyMouseMiddle` to that enum and mark `ebiten.MouseButton` as depreciated

**Comment by hajimehoshi** [comment]
Hmm? I'm against integrating MouseButton and Key now.

**Comment by erexo** [comment]
I feel you, that's why I would leave the `ebiten.MouseButton` as is, but mark it as Deprecated, as some things in ebitengine already are, so that we could clean that up in 3.0.0.
But if you don't even want to do that, that's fine, I would just add additional `KeyMouse4-7` to the `ebiten.Key` for now

**Comment by erexo** [comment]
Deprecating `MouseButton` is a part of that suggestion, as mentioned here.

> I know that such Keys suits better on `ebiten.MouseButton` rather than `input.Key`, but why do we need this separation in the first place? Wouldn't it be wise to get rid of the `ebiten.MouseButton` and move all the buttons there to the `input.Key` in 3.0.0 or sooner?

**Comment by hajimehoshi** [comment]
> In my game I have actions that could be assigned by the users to their preferable Keys, and some players reported that they would like to assign some of the most frequently used actions to their mouse and it would be very convenient for them

I see, but I still don't agree integrating them. You can have your own wrapper to integrate inputs.

**Comment by erexo** [comment]
That's fine, is adding those new keys `KeyMouse4-7` to the `ebiten.Key` ok?

**Comment by hajimehoshi** [comment]
No. Add MouseButtons, not Keys.

**Comment by erexo** [comment]
ok then, I'll see what I can do
