### ISSUE TITLE
Remove the restriction on len(indices)

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2460]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

`panic: ebiten: len(indices) must be <= MaxIndicesCount`

This happens when a user issues too many indices, even if the biggest index from the slice satisfies `<= MaxIndicesCount` (because some indices can be repeated).

I wonder if it is possible to push the limit further, or remove it completely for indices?

### Why is this needed?

* If `uint16` (which is a self-documenting restriction already) overflowing is programming knowledge, and there is a way to push more indices to a `DrawTriangles` command, I'm not sure that it makes sense to prevent it in ebitengine.
* It would allow users to push a single vertices/indices batch for a single command if numbers aren't too high and not have to arbitrarily split these slices and commands on the user side (would impact performance too).

**Comment by hajimehoshi** [comment]
Good point.

Some graphics driver implementations assume that the maximum size of the buffer depend on MaxIndicesNum. I have to refactor this first.
