### ISSUE TITLE
ebiten.RunGame fails in 2.4.13 on some GPUs if os.Setenv("EBITENGINE_GRAPHICS_LIBRARY", "directx")

### ISSUE THREAD

**Issue by AmanitaVerna** [hajimehoshi/ebiten#2466]
### Ebitengine Version

2.4.13

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.3

### What steps will reproduce the problem?

On a GPU that doesn't support DirectX 12, call os.Setenv("EBITENGINE_GRAPHICS_LIBRARY", "directx") before calling ebiten.RunGame(game).

### What is the expected result?

Ebitengine would just use DirectX 11.

### What happens instead?

RunGame returns an error whose string is "directx: DirectX 12 is not supported", rather than actually working.

### Anything else you feel useful to add?

I have a GTX 750 Ti, which doesn't support DirectX 12. This worked fine for me in 2.4.12 - it used DirectX 11.
Ebitengine works if the os.Setenv("EBITENGINE_GRAPHICS_LIBRARY", "directx") line is removed, but then it uses OpenGL, at least on my card (I checked with ebiten.ReadDebugInfo).

So, in 2.4.13, on cards that don't support DirectX 12, there's no longer any way to specify whether to use DirectX or OpenGL.

**Comment by hajimehoshi** [comment]
I'm not sure whether this is a bug. That's unfortunate that your machine doesn't support DirectX 12 (but 11), but is there a reason you want to use DirectX instead of OpenGL?

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/2447

There were some old card that supports DirectX 11 but not DIrectX 12, and this caused crashing when DirectX 12 was chosen. So, I changed the minimum requirement for DirectX 12: a graphics card must support DirectX 12.

**Comment by AmanitaVerna** [comment]
> I'm not sure whether this is a bug. That's unfortunate that your machine doesn't support DirectX 12 (but 11), but is there a reason you want to use DirectX instead of OpenGL?

I'm personally fine with using OpenGL, but there are a couple reasons I think it would be better if DirectX 11 was supported:
1. I remember from previous discussions that some other people have multiplayer games whose users expect to have the choice between DirectX and OpenGL.
2. Not being able to use DirectX means that I cannot test any of my code on DirectX. This is an issue, since it's possible there may be issues with Ebitengine's code for one graphics library but not the other, and I am doing some stuff that is perhaps unexpected, like using SubImages as image draw targets, for their clipping ranges, in order to implement scrolling panes.

I ran into a problem previously which only occurred on DirectX, which I never figured out a way to reproduce, and so never opened an issue for. Specifically, some, but not all, of my images, after being modified with At and Set, and split apart with SubScreen, were rendering as entirely blank, or sometimes as if only part of their image data was still there. It wasn't deterministic, either. Rarely it would work fine, sometimes it would have part of the images, sometimes they would just all blank. I actually found #2428 while I was trying to either find a way to reproduce or work around this weird DirectX-only issue. I ended up finding a workaround without finding a way to reproduce it, and have since been waiting to see if I run into it again at some future point, which is why I still had that os.Setenv line in my code.


> #2447
> 
> There were some old card that supports DirectX 11 but not DIrectX 12, and this caused crashing when DirectX 12 was chosen. So, I changed the minimum requirement for DirectX 12: a graphics card must support DirectX 12.

Why was it choosing DirectX 12 if the cards did not support it? That is, why wasn't it choosing a DirectX version that they did support? That seems like the problem to me, although I don't have any idea if it would be significantly more work to support both DX 11 and DX 12. If it would be, then nevermind.

**Comment by hajimehoshi** [comment]
So, the reason why you want to keep using DirectX 12 is that you want to test it, right?

> I actually found https://github.com/hajimehoshi/ebiten/issues/2428 while I was trying to either find a way to reproduce or work around this weird DirectX-only issue.

I think this is not a DirectX-only issue.

> Why was it choosing DirectX 12 if the cards did not support it? 

This is tricky. There is a compatbile adapter of DirectX 12 even if the graphics card doesn't support. The issue is that the compatible adapter might not work correctly.

**Comment by AmanitaVerna** [comment]
> So, the reason why you want to keep using DirectX 12 is that you want to test it, right?
Yes.

> 
> > I actually found #2428 while I was trying to either find a way to reproduce or work around this weird DirectX-only issue.
> 
> I think this is not a DirectX-only issue.
That isn't, but the one I was trying to track down when I found it was.

> 
> > Why was it choosing DirectX 12 if the cards did not support it?
> 
> This is tricky. There can be a compatbile adapter of DirectX 12 even if the graphics card doesn't support. The issue is that the compatible adapter might not work correctly.
Ah, I see.

**Comment by hajimehoshi** [comment]
I admit fixing #2447 was an unexpected breaking change. I'll add a new value for `EBITENGINE_DIRECTX` to specify a feature level.

**Comment by AmanitaVerna** [comment]
That sounds good to me.

**Comment by hajimehoshi** [comment]
Instead, I've introduced a new environment variable `EBITENGINE_DIRECTX_FEATURE_LEVEL` to specify `11_0`, `11_1`, `12_0`, `12_1`, or `12_2`.

I'm a little hesitate to back-port this to v2.4 (the stable branch). Let me think...

**Comment by hajimehoshi** [comment]
OK, I've decided to back-port this to v2.4, but I don't create a new tag v2.4.14 for a while (1 or 2 weeks) until a new bug fix is needed.

**Comment by hajimehoshi** [comment]
Please try `go get github.com/hajimehoshi/ebiten/v2@ed88559a5040b9da9116aa9d344fd887cc77116a` (v2.4 branch). Thanks

**Comment by hajimehoshi** [comment]
I'll remove `EBITENGINE_DIRECTX_FEATURE_LEVEL` environment variable from v2.4. As the default feature is now 11, we don't need for v2.4. We'll revisit the necessity of this environment variable later.
