### ISSUE TITLE
ebiten: swap the definition of `MouseButtonMiddle` (2) and `MouseButtonRight` (1)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2468]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

This change will follow the web standard https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button

We might do this now, but some program might depend on the integer values. I'm not sure. If we have `(MouseButton).MarshalText` and `UnmarshalText`, we might not have to care about this.

### Why is this needed?

Following the web standard whenever possible is more consistent (like keys' names, gamepad buttons, etc.)

**Comment by hajimehoshi** [comment]
@erexo I was wondering if it would be ok for you to change the definition of `MouseButtonMiddle` and `MouseButtonRight` in v2.

**Comment by erexo** [comment]
sure, I have no problem with that
