### ISSUE TITLE
Changing Fullscreen Mode while Mouse is Captured Moves Mouse

### ISSUE THREAD

**Issue by SolarLune** [hajimehoshi/ebiten#2475]
### Ebitengine Version

v2.4.3

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go 1.19.3 linux/amd64

### What steps will reproduce the problem?

When you toggle fullscreen with the cursor mode set to CursorModeCaptured, it moves the mouse's position.

### What is the expected result?

That the cursor doesn't change position (as the application's layout doesn't change), or that it changes position to be . If this is unavoidable, it might be advised to allow us to force the cursor's position with an API, like `ebiten.SetCursorPosition()`, or to return a delta of the cursor's movement over the previous frame, like `ebiten.CursorMovement()` or `ebiten.CursorDelta()`.

### What happens instead?

The cursor does, instead, change position.

### Anything else you feel useful to add?

Here's an example project:

```go

type Game struct{}

func (g *Game) Update() error {

	var err error

	if inpututil.IsKeyJustPressed(ebiten.KeyF4) {
		ebiten.SetFullscreen(!ebiten.IsFullscreen())
	}

	if inpututil.IsKeyJustPressed(ebiten.KeyEscape) {
		err = errors.New("quit")
	}

	fmt.Println(ebiten.CursorPosition())

	return err

}

func (g *Game) Draw(screen *ebiten.Image) {}

func (g *Game) Layout(w, h int) (int, int) {
	return 320, 240
}

func NewGame() *Game { return &Game{} }

func main() {

	ebiten.SetCursorMode(ebiten.CursorModeCaptured)

	if err := ebiten.RunGame(NewGame()); err != nil {
		panic(err)
	}

}


```

**Comment by hajimehoshi** [comment]
The original position when `CursorModeCaptured` is used is not preserved, so I am not sure this is a bug to fix.

**Comment by SolarLune** [comment]
> The original position when `CursorModeCaptured` is used is not preserved, so I am not sure this is a bug to fix.

I don't think Ebitengine needs to preserve the original position when the cursor's captured, but rather than when fullscreen mode is changed, the mouse position shouldn't change.

**Comment by hajimehoshi** [comment]
Confirmed the issue.

**Comment by hajimehoshi** [comment]
I guess this is not fixable until we port GLFW to Go.

**Comment by hajimehoshi** [comment]
A little minimized case

```go
package main

import (
	"fmt"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

type Game struct{}

func (g *Game) Update() error {
	if inpututil.IsKeyJustPressed(ebiten.KeyF) {
		ebiten.SetFullscreen(!ebiten.IsFullscreen())
	}
	if inpututil.IsKeyJustPressed(ebiten.KeyEscape) {
		return ebiten.Termination
	}
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	x, y := ebiten.CursorPosition()
	ebitenutil.DebugPrint(screen, fmt.Sprintf("%d, %d", x, y))
}

func (g *Game) Layout(w, h int) (int, int) {
	return 320, 240
}

func main() {
	ebiten.SetCursorMode(ebiten.CursorModeCaptured)
	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}

}
```

**Comment by hajimehoshi** [comment]
OK `clientPositionToLogicalPosition` is the cause. GLFW is not to blame...

**Comment by hajimehoshi** [comment]
I've confirmed the same thing happens on browsers.
