### ISSUE TITLE
ebiten: add more mouse cursor shapes

### ISSUE THREAD

**Issue by eliasdaler** [hajimehoshi/ebiten#2476]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### What feature would you like to be added?

It would be good to have more cursor shapes similar to what GLFW/SDL have. 

In particular, something close to:
* GLFW_RESIZE_ALL_CURSOR (arrows pointing in 4 directions)
* GLFW_NOT_ALLOWED_CURSOR ("crossed out circle" cursor)

If the platform doesn't support a particular cursor shape, I think it will be OK to not change cursor at all.

**Comment by erexo** [comment]
I would also make a great use of this feature, currently I'm drawing ebiten.Image on the cursor position (as probably everyone) and this has some frustrating limitations

**Comment by hajimehoshi** [comment]
https://github.com/glfw/glfw/issues/427 These were added to GLFW 3.4, not 3.3 unfortunately, but I can add some hacks for Ebitengine.

> `GLFW_RESIZE_ALL_CURSOR`

Probably this is `move` in CSS https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

> GLFW_NOT_ALLOWED_CURSOR

`not-allowed` in CSS.

**Comment by hajimehoshi** [comment]
Ha, in my environment (macOS 13), `_moveCursor` was not available. Apparently I would have to use WebKit's resource: https://stackoverflow.com/a/21786835/5435443  

See also: https://docs.rs/winit/latest/x86_64-apple-darwin/src/winit/platform_impl/macos/util/cursor.rs.html

**Comment by hajimehoshi** [comment]
Hmm, this requires a hack to GLFW and we would need to port GLFW to Go.

**Comment by eliasdaler** [comment]
Interesting. I thought that you planned to do this anyway, right?

**Comment by hajimehoshi** [comment]
Yes.
