### ISSUE TITLE
WebAssembly doesn't work or documentation seems wrong. Getting Incorrect response MIME type. Expected 'application/wasm'

### ISSUE THREAD

**Issue by yngvark** [hajimehoshi/ebiten#2482]
### Ebitengine Version

v2 I think. Based on this line:

https://github.com/hajimehoshi/ebiten/blob/main/examples/blocks/main.go#L23

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.18.8

### What steps will reproduce the problem?

* Run this

```sh
git clone https://github.com/hajimehoshi/ebiten.git
cd ebiten/examples/blocks
git checkout 724516a0e0ffffdd16b51e1a3dc051dd10b30780 # commit from 2022-12-03

# Based on https://ebitengine.org/en/documents/webassembly.html

cp $(go env GOROOT)/misc/wasm/wasm_exec.js .

env GOOS=js GOARCH=wasm go build -o blocks.wasm github.com/hajimehoshi/ebiten/v2/examples/blocks

cat <<EOF >index.html
<!DOCTYPE html>
<script src="wasm_exec.js"></script>
<script>
    // Polyfill
    if (!WebAssembly.instantiateStreaming) {
        WebAssembly.instantiateStreaming = async (resp, importObject) => {
            const source = await (await resp).arrayBuffer();
            return await WebAssembly.instantiate(source, importObject);
        };
    }

    const go = new Go();
    WebAssembly.instantiateStreaming(fetch("blocks.wasm"), go.importObject).then(result => {
        go.run(result.instance);
    });

</script>
EOF

docker run -p 8081:80 -v $(pwd)://usr/share/nginx/html nginx
```

* Open http://localhost:8081
* Open the browser's web console, and you should see this error

```
localhost/:1 Uncaught (in promise) TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
Promise.then (async)
(anonymous) @ (index):13
```

### What is the expected result?

I expected the game to run like in https://ebitengine.org/en/examples/blocks.html

### What happens instead?

* A white screen with no content
* The error mentioned in the reproduction of the problem

### Anything else you feel useful to add?

The `blocks.wasm` looks like this:

```sh
$ head -3 blocks.wasm
asm򀀀
go.buildid� Go build ID: "R7wvTnN4kDMMSB-g9K63/10wvF4W-9BkUQh4yoItY/Mv7fBhUNw2z6aMTybysn/bAZqMt1b0OeqbLE-nY7q"
 ���
    ```~~~~~``~~~~`~~`````~~~`|~����godebuggountime.resetMemoryDataViewgoruntime.wasmExitgoruntime.wasmWritegoruntime.nanotime1goruntime.walltimegoruntime.scheduleTimeoutEventgoruntime.clearTimeoutEventgoruntime.getRandomDatagosyscall/js.finalizeRefgosyscall/js.stringValgosyscall/js.valueGetgosyscall/js.valueSetgosyscall/js.valueDeletegosyscall/js.valueIndexgosyscall/js.valueSetIndexgosyscall/js.valueCallgosyscall/js.valueInvokegosyscall/js.valueNewgosyscall/js.valueLengthgosyscall/js.valuePrepareStringgo�syscall/js.valueLoadStringgo�syscall/js.valueInstanceOfgosyscall/js.copyBytesToGogosyscall/js.copyBytesToJS�����+
```

**Comment by hajimehoshi** [comment]
This is not an Ebitengine issue but an issue in your settings of the HTTP server. The WebAssembly must be provided with the MIME type application/wasm.

**Comment by yngvark** [comment]
Thanks, that fixed it.

It would be nice if the documentation gave a full working example of how to run a game using WebAssembly, which states details such as this explicitly. Users just want to get started without having to figure out such details themselves. This is not criticism, just a wish.

---

For anyone who stumbles upon the same, one way of fixing this is the following:

In shell block above, instead of `docker run`, create and run a custom built docker container using the Dockerfile:

```sh
FROM nginx

COPY mime.types etc/nginx/mime.types
```

where the `mime.types` file contains

```
application/wasm                                 wasm;
```
