### ISSUE TITLE
internal/graphicsdriver: both OpenGL and DirectX graphics engines are not working on given machine

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2484]
### Ebitengine Version

760e6b9ebd228554bed191410ce47d8a93a329dd

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.1

### What steps will reproduce the problem?

One of my players with rather old computer is not able to run my games completely, either with DirectX or OpenGL.
When engine is set to "auto", the error is: `glfwwin: the driver does not appear to support OpenGL` which probably means that the engine selection falls from DirectX to OpenGL but that lib is also not supported. Engine set to "directx" produces: `directx: DirectX 12 is not supported`.
His `dxdiag` looks like so:
![image](https://user-images.githubusercontent.com/6548968/205920840-66e1194e-0ca7-49ea-baaa-26d7c12d739d.png)
![image](https://user-images.githubusercontent.com/6548968/205920861-86e9d6fb-21ed-4174-8f65-15be00d79c06.png)
The player is claiming that he updated Windows, DirectX and all his drivers.

I have no clue why OpenGL is not working for him, but in terms of DirectX it's because he has the "feature levels" od dx12 capped at 10_1, where as far as I know ebitengine supports dx12 from 11_0.
I do understand that his computer is old, and who's using such hardware nowadays, it'd be hard to fix and all that. But the biggest problem is that my previous client written in C++ (using GL/glx.h) is working just fine, so that particular player is kinda furious because for him it was a pretty massive, game breaking downgrade.

### What is the expected result?

I would like to tell that player that he's able to run my game.

### What happens instead?

The games does not launch

### Anything else you feel useful to add?

God knows how many people had this problem and didn't write to me but just give up.
This particular player is responsive and cooperative, so if any further tests are required I think I would be able to arrange it.

**Comment by hajimehoshi** [comment]
I'm not 100% sure but this might be related: https://www.intel.com/content/www/us/en/support/articles/000058790/graphics.html

**Comment by hajimehoshi** [comment]
Is this still an issue?
