### ISSUE TITLE
internal/graphicsdriver/directx: unstable performance (sometimes suspending) with DirectX

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2485]
### Ebitengine Version

760e6b9ebd228554bed191410ce47d8a93a329dd

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.1

### What steps will reproduce the problem?

*Note: This is a developing Issue that I will try to update when I gather more information.*

One of my players (and probably more) are experiencing "unpleasant" experience on DirectX, that is low FPS, lags between frames, and most importantly white screen (not responding state).
Given that this player's machine is quite good, and on OpenGL everything is perfectly normal (2 white screens during 4 hours on dx, and no white screens on opengl for 15+hours and counting).
His `dxdiag`:
![image](https://user-images.githubusercontent.com/6548968/205980595-99713ad8-a672-467c-910b-a201f62844c0.png)
![image](https://user-images.githubusercontent.com/6548968/205980622-cf553d03-e4ac-4e32-8b23-b3ccde12f77b.png)

DirectX having observable worse performance than OpenGL on this particular machine is repeatable, and there is no shadow of a doubt that OpenGL is much better for this particular player.
I have no evidence that this not responding state is because of ebitengine's DirectX, there are more players who reported this issue but I did not ask about details, I will from now on and I'll update this Issue to gather as many informations as possible.

### What is the expected result?

No "not responding" state, better DirectX performance.

### What happens instead?

Measurably worse DirectX performance on Windows.

### Anything else you feel useful to add?

I don't really expect anyone to do something with this case right now, as I already mentioned I'll treat this Issue as a documenting page for my observations regarding those issues, especially the "not responding" state since there are a couple of players who reported that and I don't think that this is my game's fault since most of the players are doing the same activities, and only a handful of them are reporting such scenario.

**Comment by erexo** [comment]
It seems that the not responding state is *not* limited to DirectX, because one of my players experienced this issue on OpenGL. I'll investigate further

**Comment by hajimehoshi** [comment]
I thought GC was the cause first, but the number of CPU cores is more than 1, right?

**Comment by erexo** [comment]
yes.
Currently I'm searching for someone who has this problem consistently, a few (<10) people reported such issue but it's usually once per day or less often

**Comment by erexo** [comment]
I found a player who's game always enters the unresponsive state (white screen) and then crash a few seconds after launching the game. He's claiming that he doesn't even need to touch the mouse or keyboard, just launch the app and watch it dies.
It happens only on DirectX (GraphicsEngine: Auto), on OpenGL he can run the game normally.
His `dxdiag`:
![image](https://user-images.githubusercontent.com/6548968/208898601-caba9b7e-bf46-4e2e-ba41-65d0a6af1f3b.png)
![image](https://user-images.githubusercontent.com/6548968/208898623-bd2d101e-0809-4b76-810f-a5cb1912a7c9.png)

and the error returned by `ebiten.RunGameWithOptions` is a well known random fella:
`directx: ID3D12Device::CreateCommittedResource failed: HANDLE(2289696773)`
which was already mentioned a few times #2478, #2292, #2283, #2114, #2109, #2294.

This particular problem is somehow related to my particular game, because the launcher (separate app also built with Ebitengine) is working fine for this player, only the actual game client crash after a very short while.
I *do not* think that this is related to "too many internal images" because as I mentioned, that player claims that the game is crashing just after a few seconds in the login screen and he doesn't even touch the inputs. 
This is my internal images dump with the ebitendebug log when I launch the client and wait for a while: https://we.tl/t-RmxGobAwcm
22 images (and 42 generated in total) is not that much, my game can easily reach 3k+ used and generated in total and I'm perfectly aware that this is not optimal, but a vast majority of players have no problems with that at all.

I am aware that this problem is kinda random and frustrating, to you, to me and to my players. But if there is no one unified fix for it maybe we can extend the logs? Maybe we can scrap more informations on this problem like where exactly in the lib that error occurs, maybe we could add info about how many internal images are currently in use to `ebiten.ReadDebugInfo`?

**Comment by hajimehoshi** [comment]
Let's discuss the error 2289696773 at #2198.

> I do not think that this is related to "too many internal images" because as I mentioned, that player claims that the game is crashing just after a few seconds in the login screen and he doesn't even touch the inputs.

I think you are confused with another error 2147942414 (#2294)

**Comment by hajimehoshi** [comment]
Is this still an issue?
