### ISSUE TITLE
internal/glfwwin: OpenGL panics

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2489]
### Ebitengine Version

b3be3348dc63b0445f1ca7ba8f74331e4d9d583b ?

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.1

### What steps will reproduce the problem?

One of my players sent me his logs to test why his game crashes, the main reason was
`opengl: creating framebuffer failed: 36054` which as already mentioned is probably because my game is using too many images.

But while I was looking though the log, I found completely new panic reason:
```
FATAL|2022/12/04 00:36:08 glfwwin: ReleaseCapture failed: Operacja ukończona pomyślnie.
panic({0x8aa180, 0xc01c582000})
	C:/Program Files/Go/src/runtime/panic.go:884 +0x212
github.com/hajimehoshi/ebiten/v2/internal/glfw.PollEvents()
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/glfw/glfw_windows.go:348 +0xa6
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).update(0x6611780)
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/ui/ui_glfw.go:1078 +0xeb
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loop.func2()
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/ui/ui_glfw.go:1128 +0x4a
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc004b61cb8?, 0xc004b61ca8?)
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/thread/thread.go:54 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc00849bc80)
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/thread/thread.go:55 +0x2e
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run(0x6611780, {0x62c8788?, 0xc00921f180})
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/ui/run_notsinglethread.go:52 +0x231
github.com/hajimehoshi/ebiten/v2.RunGame({0x62c5f50, 0xc0004ce030})
	C:/Users/Erexo/go/src/github.com/erexo/ebiten/run.go:233 +0x9d
```
`Operacja ukończona pomyślnie` means `The operation completed successfully`, and the error is very similar to #2478, but the error message is different.
There is a chance that this was already resolved, as the log is from `2022/12/04` so 4 days ago.

### What is the expected result?

No panic

### What happens instead?

Panic

**Comment by hajimehoshi** [comment]
This was not covered by #2478. Please check 8a95b1d85c61621892c5b6f8fd47eb3c80944d36 out.
