### ISSUE TITLE
 undefined: `vector.LineJoin` and other `vector` items

### ISSUE THREAD

**Issue by impopular-guy** [hajimehoshi/ebiten#2494]
### Ebitengine Version

v2.4.14 and v2.5.0-alpha.4

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.19 windows/amd64

### What steps will reproduce the problem?

I tried to run the example https://github.com/hajimehoshi/ebiten/tree/main/examples/lines

### What is the expected result?

Expected to see some Lines Demo

### What happens instead?

```
> go run .\main.go
# command-line-arguments
.\main.go:78:20: undefined: vector.LineJoin
.\main.go:79:10: undefined: vector.LineJoinMiter
.\main.go:80:10: undefined: vector.LineJoinMiter
.\main.go:81:10: undefined: vector.LineJoinBevel
.\main.go:82:10: undefined: vector.LineJoinRound
.\main.go:84:19: undefined: vector.LineCap
.\main.go:85:10: undefined: vector.LineCapButt
.\main.go:86:10: undefined: vector.LineCapRound
.\main.go:112:82: undefined: vector.LineCap
.\main.go:112:103: undefined: vector.LineJoin
.\main.go:86:10: too many errors
```

### Anything else you feel useful to add?

Tried to change ebiten version from `v2.4.14` to `v2.5.0-alpha.4` but still got the same error.

**Comment by hajimehoshi** [comment]
Try v2.5.0-alpha.14.
