### ISSUE TITLE
internal/graphicsdriver/directx: IDXGISwapChain4 error

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2499]
### Ebitengine Version

9911b760c509381895274d882b548498fe07124e

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.1

### What steps will reproduce the problem?

the `ebiten.RunGameWithOptions` returns an unexpected directx related error
`directx: IDXGISwapChain4::Present failed: HANDLE(2289696773)`

### What is the expected result?

no error

### What happens instead?

error

### Anything else you feel useful to add?

I have absolutely no clue what has happened. One of the players sent me his logs to fix one game related issue, but during log browsing I discovered this one. The player agreed that the game recently crashed, but he has no clue what he was doing.
I can't really tell if this was on runtime or when game was launching.

**Comment by hajimehoshi** [comment]
The error is DXGI_ERROR_DEVICE_REMOVED. I'm not sure this is fixable.

https://steamcommunity.com/app/235540/discussions/8/483367798506343525/

**Comment by hajimehoshi** [comment]
Let's merge this to #2198
