### ISSUE TITLE
internal/ui: `inpututil.IsMouseButtonJustReleased` does not kick in a tick after the Button is actually released

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2502]
### Ebitengine Version

8ccfa7bec15d8d9daead7c540d2faf94d2382170

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.1

### What steps will reproduce the problem?

As far as I understand the `Update` method should be executed each Tick (as of Ticks Per Second, TPS).
And so if each Tick the buttons state (or input state in general) is changed, then if any button was pressed a Tick ago and now it's not, then now it should be marked as "just released".
It was working like that before d1b9a0a9a14f0f2b0d36c786f66aacc9e71043c1, but this commit kinda messed it up and now there is a one Tick delay before `inpututil.IsMouseButtonJustReleased` is marked as true.
`ebiten.IsKeyPressed` and `inpututil.IsKeyJustReleased` is also *incorrect* atm.
Please take a look at the example below, any commit above d1b9a0a9a14f0f2b0d36c786f66aacc9e71043c1 will throw a panic when you press and release left or right mouse button.

### What is the expected result?

fix the behavior to before d1b9a0a9a14f0f2b0d36c786f66aacc9e71043c1

### What happens instead?

n\a

### Anything else you feel useful to add?

```
package main

import (
	"fmt"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

func main() {
	ebiten.RunGameWithOptions(&game{}, &ebiten.RunGameOptions{})
}

type game struct {
	wasLeftPressed, wasRightPressed         bool
	leftWillBeReleased, rightWillBeReleased bool
}

func (g *game) Update() error {
	leftPressed := ebiten.IsMouseButtonPressed(ebiten.MouseButtonLeft)
	rightPressed := ebiten.IsMouseButtonPressed(ebiten.MouseButtonRight)
	leftReleased := inpututil.IsMouseButtonJustReleased(ebiten.MouseButtonLeft)
	rightReleased := inpututil.IsMouseButtonJustReleased(ebiten.MouseButtonRight)
	fmt.Println(leftPressed, leftReleased, "|", rightPressed, rightReleased)

	if g.leftWillBeReleased {
		if leftReleased {
			panic("Left \"IsMouseButtonJustReleased\" kicks in a tick too late")
		}
		panic("Left \"IsMouseButtonJustReleased\" didn't kick in either on the correct tick nor on the tick after")
	}
	if !leftPressed && g.wasLeftPressed { // first tick (Update) when left is not pressed
		if !leftReleased { // it should be noted by "IsMouseButtonJustReleased"
			g.leftWillBeReleased = true // Left release was not noted (it will be on next tick), <<< this is a problem already
		}
	}

	if g.rightWillBeReleased {
		if rightReleased {
			panic("Right \"IsMouseButtonJustReleased\" kicks in a tick too late")
		}
		panic("Right \"IsMouseButtonJustReleased\" didn't kick in either on the correct tick nor on the tick after")
	}
	if !rightPressed && g.wasRightPressed { // first tick (Update) when right is not pressed
		if !rightReleased { // it should be noted by "IsMouseButtonJustReleased"
			g.rightWillBeReleased = true // Right release was not noted (it will be on next tick), <<< this is a problem already
		}
	}

	g.wasLeftPressed = leftPressed
	g.wasRightPressed = rightPressed
	return nil
}
func (g *game) Draw(screen *ebiten.Image) {}
func (game) Layout(x, y int) (int, int)   { return x, y }
```

**Comment by hajimehoshi** [comment]
Very good catch. Thank you for your reports! I'll fix this soon.

**Comment by hajimehoshi** [comment]
Fixed.

Your code snippet was very helpful to reproduce the issue and confirm the issue fixed.
