### ISSUE TITLE
inpututil.IsMouseButtonJustPressed does not behave as expected in goroutine- multiple events fire at same timestamp

### ISSUE THREAD

**Issue by a34729t** [hajimehoshi/ebiten#2507]
### Ebitengine Version

v2.5.0-alpha.8.0.20221216152014-bb39f3a79729

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19

### What steps will reproduce the problem?

Tracking mouse presses with `inpututil.IsMouseButtonJustPressed` directly in `Update()` works as expected. If however at game init time I launch a goroutine that instead listens to mouse presses off the main thread, I get hundreds of mouse presses detected (via logs). Mouse release however works as expected in both cases. Per the documentation, both of these methods are concurrent-safe- and the code uses locks too, so I assume this is unexpected.

I've put together a minimal example of this behavior at https://github.com/a34729t/ebiten-mouseclick-example with instructions.

### What is the expected result?

inpututil.IsMouseButtonJustPressed even when running in goroutine should produce a single log/event for a single press.

### What happens instead?

inpututil.IsMouseButtonJustPressed produces multiple logs/events for a single press.

### Anything else you feel useful to add?

If this is the expected behavior, is the best practice to generate input events on the main thread and push them on the channel at `Update()` time instead?

**Comment by hajimehoshi** [comment]
This is expected. The input state doesn't change during Update (#2496). The state is also frozen between two frames.

We plan to introduce a new package to detect inputs in finer granularity (#1704).
