### ISSUE TITLE
windows: GDI objects are leaking

### ISSUE THREAD

**Issue by IMadering** [hajimehoshi/ebiten#251]
All Examples
![02](https://cloud.githubusercontent.com/assets/449423/17475592/73f0c766-5d64-11e6-9227-9e1348d2f7a2.png)

GDI - 2190

next 2 minutes

![02](https://cloud.githubusercontent.com/assets/449423/17475649/ae17755c-5d64-11e6-905c-83aad0e25d79.png)

GDI - 7707 !!!!!
and Memory ....

????????????????????????

**Comment by hajimehoshi** [comment]
Thank you for reporting a problem. Unfortunately I can't read Russian language and I don't understand what number indicates memory usage. Additionally, what does GDI mean you said?

**Comment by hajimehoshi** [comment]
I guess you mean number of GDI object is increasing monotonically. Let me check.

https://blogs.msdn.microsoft.com/dsui_team/2013/04/23/debugging-a-gdi-resource-leak/

**Comment by hajimehoshi** [comment]
Reproduced: memory usage was increasing even with calling `runtime.GC()`

**Comment by hajimehoshi** [comment]
OK, I found the culprit:

```go
package ui

// #cgo LDFLAGS: -lgdi32
//
// #include <windows.h>
//
// static int getDPI() {
//   HDC dc = GetWindowDC(0);
//   return GetDeviceCaps(dc, LOGPIXELSX);
// }
import "C"

func deviceScale() float64 {
	dpi := int(C.getDPI())
	return float64(dpi) / 96
}

func glfwScale() float64 {
	return deviceScale()
}
```

Whenever this function is called, GDI object is created and will never be released.

**Comment by hajimehoshi** [comment]
Fixed. I appreciate your bug report again! Feel free to reopen this issue if you find the same problem.
