### ISSUE TITLE
ebiten: add an API to allow cursor to pass through window

### ISSUE THREAD

**Issue by miniscruff** [hajimehoshi/ebiten#2511]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

An option to allow cursor clicks to pass through the game window and not take focus. My idea was another cursor mode such as `CursorModePassThrough` as it would be exclusive of the existing modes.

This would of course only apply to desktop and probably only before Run.

### Why is this needed?

Creating a transparent overlay window like: [mascot](https://github.com/hajimehoshi/ebiten/tree/main/examples/mascot) or [neko](https://github.com/crgimenes/neko) but where the screen is large or where clicking, dragging or keys have no effects and we want to just use the window behind it.
This would be especially required if the window was a full screen window displaying some sort of full screen effect such as the weather or whatever.

**Comment by hajimehoshi** [comment]
This will be possible in GLFW 3.4, instead of 3.3: https://www.glfw.org/docs/3.4/window_guide.html#GLFW_MOUSE_PASSTHROUGH_hint

I'll take a look more but probably we have to wait for GLFW 3.4 stable.

**Comment by hajimehoshi** [comment]
Windows: https://github.com/glfw/glfw/blob/d299d9f78857e921b66bdab42c7ea27fe2e31810/src/win32_window.c#L1951
macOS: https://github.com/glfw/glfw/blob/d299d9f78857e921b66bdab42c7ea27fe2e31810/src/cocoa_window.m#L1481
Linux (X11): https://github.com/glfw/glfw/blob/00967cbb8a4a51ea8ff6f8b8a7efcf1f761cc664/src/x11_window.c#L2713

**Comment by hajimehoshi** [comment]
Oops, on Linux, this requires a new dependency `libXext`...

https://github.com/glfw/glfw/blob/3eaf1255b29fdf5c2895856c7be7d7185ef2b241/src/x11_init.c#L879-L908
