### ISSUE TITLE
Tearing when moving an image on the screen

### ISSUE THREAD

**Issue by drum445** [hajimehoshi/ebiten#2515]
### Ebitengine Version

v2.4.15

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.18.4 windows/amd64

### What steps will reproduce the problem?

Run any example or code that moves a sprite (ebiten.Image) around the screen, tearing is occuring very often.

Could possibly be due to my ActualFPS being > 1k whilst ActualTPS correctly sitting at 60~

I tried to dig into this a bit and found that when deploying as WASM, the browser shows no sign of tearing (ActualFPS there is == ActualTPS)

Also tried running this game (https://ebitengine.org/en/blog/steam.html), when running through steam there is no tearing, however, when cloning and running locally I again see tearing. What is strange here is that when running through steam the game's FPS counter sits at 60, but locally is again > 1k

### What is the expected result?

No image/screen tearing and the rendering is smooth when moving images

### What happens instead?

Fairly aggressive tearing occurs. Not limited to one project as it happens on all the examples I've tried too

### Anything else you feel useful to add?

Doesn't happen when deployed to browser
Strangely it seems to happen on certain parts of the window (different each time), e.g. if I load the game and move around till I find tearing, when I move my character sprite back to that area of the screen it will always tear, but anywhere else in the window will be smooth

Many Thanks

**Comment by drum445** [comment]
Updated: tested this on my mac (m1) and there is no tearing.
ActualFPS here == ActualTPS

Does seem likely that it is the fact my windows machine has 1k frames per second

Ta

**Comment by hajimehoshi** [comment]
Did you disable vsync explicitly?

**Comment by drum445** [comment]
@hajimehoshi No I haven't the only thing I've done is `ebiten.SetTPS(60)` (which I think is the default anyway)
Tested on another windows machine and it's much better as FPS is 144 (144hz monitor) and TPS is 60, so no visible tearing

**Comment by hajimehoshi** [comment]
Thanks. Could you tell me what the monitor is?

> Also tried running this game (https://ebitengine.org/en/blog/steam.html), when running through steam there is no tearing, however, when cloning and running locally I again see tearing. What is strange here is that when running through steam the game's FPS counter sits at 60, but locally is again > 1k

I think there is a regression. I would git-bisect Ebitengine to know the problematic commit, but would it be possible for you to do it on your machine?

**Comment by drum445** [comment]
My bad, I wasn't very clear, the machine it's working on was connected to a 144hz monitor. The machine it isn't working on, is just an old 60hz.

> I think there is a regression. I would git-bisect Ebitengine to know the problematic commit, but would it be possible for you to do it on your machine?

What do you mean by this sorry, as in go back and see if a previous version on Ebitengine fixes the problem?

**Comment by hajimehoshi** [comment]
> My bad, I wasn't very clear, the machine it's working on was connected to a 144hz monitor. The machine it isn't working on, is just an old 60hz.

I would like to know the details of the monitor which caused tearing (maybe the old 60Hz monitor?)

> What do you mean by this sorry, as in go back and see if a previous version on Ebitengine fixes the problem?

Basically yes, but if you are not familiar with git-bisect, it's OK. I'll look for another way...

**Comment by drum445** [comment]
Using `ebiten.CurrentFPS()` in `v2.2.0` I get the expected 60fps, however, in `v2.3.0` I get close to 1k again

Is there anything more specific I can do to find when it was introduced?

**Comment by hajimehoshi** [comment]
Thanks! My guess is that this issue was introduced at the same time when DirectX was adopted. v2.3 started to use DirectX.

I'd like to know the details of your graphic card and your monitor. Thanks,

**Comment by drum445** [comment]
My monitor is an HP 2311x - I'll try to test this on another monitor later just to rule that out
GPU: NVIDIA GeForce RTX 3060 Ti

I converted my app to v2.2.7 and along with the stable 60 FPS the tearing is also not present 👍 

Thanks

**Comment by hajimehoshi** [comment]
> My monitor is an HP 2311x - I'll try to test this on another monitor later just to rule that out
> GPU: NVIDIA GeForce RTX 3060 Ti

Thanks! I'll take a look...

https://docs.google.com/document/d/1djz7cUKPP2UTtyQD-aBb5836wPkqBDSOZYPhgCtJHRU/edit#

FYI, you can force to use OpenGL for Ebitengine v2.4. This should resolve your machine's issue but this is just a temporary solution.

**Comment by hajimehoshi** [comment]
Could you check the current settings of your NVIDIA graphics card? There should be a setting for vsync.

https://www.nvidia.com/en-us/geforce/technologies/adaptive-vsync/technology/

**Comment by drum445** [comment]
Great find! In NVIDIA control pannel I switched the vsync setting to "Use the 3D application setting" and after upgrading back to the latest Ebitengine I have a stable 60 FPS and there is no tearing

Thanks

**Comment by hajimehoshi** [comment]
I'm happy that your issue was resolved, and I think there is nothing Ebitengine can do for this. Let me close this as 'won't fix'.

**Comment by drum445** [comment]
that's fair thanks, I'm curious as to why other games don't have this problem, but agreed that it doesn't sound like an Ebitengine problem

Ta

**Comment by hajimehoshi** [comment]
> I'm curious as to why other games don't have this problem, but agreed that it doesn't sound like an Ebitengine problem

TBH I have no idea, but did DirectX applications work with vsync without the setting?

**Comment by drum445** [comment]
After testing a few steam games I own, I found that a couple of them were also showing incredibly high FPS even with the in-game vsync enabled **if** the NVIDIA vsync setting you mentioned was off. After changing the NVIDIA setting back to what it "should" be, those games now also run at 60fps

Thanks again

**Comment by hajimehoshi** [comment]
Thank you for your experiments!
