### ISSUE TITLE
ebiten: wrong frame rendering with `SetScreenClearedEveryFrame(false)`

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2517]
### Ebitengine Version

70183185460a5fc1297bb81c897e213c73d8373e

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.19.4 windows/amd64

### What steps will reproduce the problem?

Sometimes OpenGL may render the frame in a "weird" way, that is the frame may be horizontally flipped and strangely scaled.
This happens the most during game start (for the first few frames) but it may also occur later.
I've noticed this issue when I deliberately lowered the frame rate using `ebiten.SetScreenClearedEveryFrame(false)` and I think (but I can't prove it) that this setting may be the cause. 
It is clearly visible when the "real frame rate" in the example below is set to a very low value (like 1fps), but it also happens when the `Clear()` is executed more often (when the program is set to 100fps) but then that single invalid frame may be harder to catch.
I didn't notice that the vsync (`ebiten.SetVsyncEnabled()`) has any major connection with this issue, it mayhappen on both vsync on and off.
I can't reproduce this issue on DIrectX.

### What is the expected result?

correctly rendered frames

### What happens instead?

From example below:
![image](https://user-images.githubusercontent.com/6548968/210186015-9c9e0176-a1a1-4d66-beb0-9a7885fb9bd1.png)

### Anything else you feel useful to add?

```
package main

import (
	"fmt"
	"time"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"golang.org/x/image/colornames"
)

func main() {
	ebiten.SetScreenClearedEveryFrame(false)
	img := ebiten.NewImage(25, 25)
	img.Fill(colornames.Cornflowerblue)
	g := game{
		img: img,
	}
	g.SetFpsLimit(1)
	ebiten.RunGameWithOptions(&g, &ebiten.RunGameOptions{
		GraphicsLibrary: ebiten.GraphicsLibraryOpenGL,
	})
}

type game struct {
	fpsCount         int
	realFps          float64
	lastUpdated      time.Time
	desiredFrameTime time.Duration

	img *ebiten.Image
}

func (g *game) SetFpsLimit(limit float64) {
	g.lastUpdated = time.Now()
	if limit <= 0 {
		g.desiredFrameTime = 0
		return
	}
	g.desiredFrameTime = time.Duration(int64(float64(time.Second) / limit))
}

func (g *game) Update() error {
	return nil
}
func (g *game) Draw(screen *ebiten.Image) {
	now := time.Now()
	diff := now.Sub(g.lastUpdated)
	if g.desiredFrameTime > 0 && diff < (time.Duration(g.fpsCount)+1)*g.desiredFrameTime {
		return
	}
	g.fpsCount++
	if diff >= time.Second {
		g.realFps = float64(g.fpsCount) / (float64(diff) / float64(time.Second))
		g.fpsCount = 0
		g.lastUpdated = now
	}

	screen.Clear()

	op := ebiten.DrawImageOptions{}
	op.GeoM.Translate(100, 100)
	screen.DrawImage(g.img, &op)
	ebitenutil.DebugPrint(screen, fmt.Sprintf("RealFPS: %f\nFPS: %f\nTPS: %f\n", g.realFps, ebiten.ActualFPS(), ebiten.ActualTPS()))
}
func (game) Layout(x, y int) (int, int) { return x, y }
```

**Comment by hajimehoshi** [comment]
Confirmed. Thanks!

**Comment by erexo** [comment]
I would also like to add that in my particular game, in given settings (SetScreenClearedEveryFrame set to false and OpenGL) the game may not only flicker as a whole but also random draws may change their place. I was not able to reproduce it on a simple environment so I've reported what is reproducible and I'm crossing my fingers that fix for those issues will also fix the issues for my particular game 😅

**Comment by hajimehoshi** [comment]
Another issue is that vsync doesn't work for Metal and DirectX. I think I'll disable this optimization so far.

**Comment by hajimehoshi** [comment]
> I would also like to add that in my particular game, in given settings (SetScreenClearedEveryFrame set to false and OpenGL) the game may not only flicker as a whole but also random draws may change their place

Thanks. I think your minimized reproducible case is enough to know what's going on. Apparently the screen framebuffer MUST be cleared every frame with OpenGL, even though this seemed skippable. That's unfortunate.

**Comment by hajimehoshi** [comment]
Whoa, simply disabling this optimization didn't solve the issue with OpenGL...

**Comment by hajimehoshi** [comment]
The culprit was 0a6813c17f8d7fa6b9d4d73c488634c92df8c218

**Comment by erexo** [comment]
> Another issue is that vsync doesn't work for Metal and DirectX. I think I'll disable this optimization so far.

In my case adding adjustable fps limiter (the thing that started this case) is needed because vsync was often reducing the fps to 60 even if player had >60hz monitor (mainly because their monitor was set to 60hz in windows options). And so such players were not enjoying the game in 60fps, and they didn't want to overuse their mechines ram and play on >140fps. I've helped countless players changing their display refresh rate to above 60, but I assume that there were at least twice as many that didn't bother contacting me and just assume that the game is just running in 60fps natively. 
That's why I want to implement an option to run the game by default on solid 140fps regardless of any other setting, and this is just one of many cases where manual fps adjustment is helpful.

That being said, I'm a greenhorn in terms of how vsync optimizations works internally in given platforms, but if vsync is redundant and you are planning to remove it, what would you say about implementing fps limiter similar to what I've shown here directly into the ebitengine?

**Comment by hajimehoshi** [comment]
Just a quick reply..

> but if vsync is redundant and you are planning to remove it,

I don't plan to remove this.

**Comment by hajimehoshi** [comment]
> In my case adding adjustable fps limiter (the thing that started this case) is needed because vsync was often reducing the fps to 60 even if player had >60hz monitor (mainly because their monitor was set to 60hz in windows options). And so such players were not enjoying the game in 60fps, and they didn't want to overuse their mechines resources and play on >140fps.

So, Unclear things to me is that the player uncomfortable with 60FPS games, and at the same time, they don't want to overuse their monitor. What do they do for other games..?

**Comment by hajimehoshi** [comment]
Note to myself: if `SetScreenClearedEveryFrame(false)`, the uniform variable's lifetimes seem much longer than I expected. This easy patch fixed the issue:

```diff
diff --git a/internal/graphicscommand/command.go b/internal/graphicscommand/command.go
index e79eb6f58..d8992c43c 100644
--- a/internal/graphicscommand/command.go
+++ b/internal/graphicscommand/command.go
@@ -670,6 +670,7 @@ type uint32sBuffer struct {
 }
 
 func (b *uint32sBuffer) alloc(n int) []uint32 {
+       return make([]uint32, n)
        buf := b.buf[b.index]
        if len(buf)+n > cap(buf) {
                buf = make([]uint32, 0, max(roundUpPower2(len(buf)+n), 16))
```

**Comment by erexo** [comment]
weird problems with my game are also fixed, thanks 😉
