### ISSUE TITLE
internal/graphicsdriver/opengl: crash when terminating on Windows

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2518]
### Ebitengine Version

70183185460a5fc1297bb81c897e213c73d8373e

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.19.4 windows/amd64

### What steps will reproduce the problem?

Quitting the game with the top "X" button do panic.
![image](https://user-images.githubusercontent.com/6548968/210186093-05f07872-2afa-4d81-a9f7-c19b6ae6dcfb.png)

### What is the expected result?

no panic

### What happens instead?

glfwwin: wglDeleteContext failed: Żądane zasoby są w użyciu."
Stack:
 2  0x00000000003ecd87 in github.com/hajimehoshi/ebiten/v2/internal/glfw.Terminate
	 at c:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/glfw/glfw_windows.go:378
 3  0x0000000000452217 in github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame.func1
	 at c:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/ui/ui_glfw.go:1009
 4  0x000000000033b5f3 in github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1
	 at c:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/thread/thread.go:51
 5  0x000000000033b54a in github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop
	 at c:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/thread/thread.go:52
 6  0x000000000044b295 in github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run
	 at c:/Users/Erexo/go/src/github.com/erexo/ebiten/internal/ui/run_glfw_notsinglethread.go:59
 7  0x0000000000474354 in github.com/hajimehoshi/ebiten/v2.RunGameWithOptions

`Żądane zasoby są w użyciu` means `Requested resources are in use`

### Anything else you feel useful to add?

```
package main

import (
	"github.com/hajimehoshi/ebiten/v2"
)

func main() {
	ebiten.RunGameWithOptions(&game{}, &ebiten.RunGameOptions{
		GraphicsLibrary: ebiten.GraphicsLibraryOpenGL,
	})
}

type game struct{}

func (g *game) Update() error             { return nil }
func (g *game) Draw(screen *ebiten.Image) {}
func (game) Layout(x, y int) (int, int)   { return x, y }
```

**Comment by hajimehoshi** [comment]
This seems a suspicious behavior in GLFW (https://github.com/glfw/glfw/issues/2239) but I'll take a look.
