### ISSUE TITLE
Mouse: specify a cursor sprite

### ISSUE THREAD

**Issue by martinlindhe** [hajimehoshi/ebiten#252]
I'm attempting to build a small game UI using ebiten and would be interested in the ability to use a custom mouse cursor.

So this is a feature request :-)

A Mouse cursor should be a sprite, with transparency, and a image.Point telling what is the top-left position of the cursor. (Similar requirement as of the https://wiki.libsdl.org/SDL_CreateCursor)

**Comment by hajimehoshi** [comment]
Thank you for requesting!

Ebiten uses GLFW and fortunately there is a way to create a custom cursor (http://www.glfw.org/docs/latest/input_guide.html#cursor_custom). Let me consider if I should do this.

**Comment by hajimehoshi** [comment]
How about drawing an cursor image by yourself and hiding the default cursor with a new function introduced at #258 ?

**Comment by martinlindhe** [comment]
That should work! Will give it a try when time permits

**Comment by hajimehoshi** [comment]
Great! Let me close this issue. Please feel free to reopen this if you find a new concern.
