### ISSUE TITLE
internal/ui: `time.Sleep` never returns on Steam Deck

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2524]
### Ebitengine Version

df7b7b731e26adcda06e94882d209d0cf74e211b

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.19.4

### What steps will reproduce the problem?

Just run a game via Steam.

### What is the expected result?

No freeze

### What happens instead?

A game freezes on a launch. "Bear's Restaurant" with the latest Ebitengine can freeze for example. Sometimes a game can run but switching application in a desktop mode makes the game frozen.

**Comment by hajimehoshi** [comment]
Apparently, `(u *userInterfaceImpl) waitForFramebufferSizeCallback` sometimes never returns. `time.Sleep(time.Millisecond)` never returns forever.

**Comment by hajimehoshi** [comment]
This issue never happens with a simple game like go-inovation.

**Comment by SolarLune** [comment]
Does this happen if the Windows version of the game is run through Proton?

**Comment by hajimehoshi** [comment]
> Does this happen if the Windows version of the game is run through Proton?

I have not tested. I've tested only the Linux version.

**Comment by hajimehoshi** [comment]
When an application stops by unfocusing, another sleeping in `userInterfaceImpl.update` never returns.

**Comment by hajimehoshi** [comment]
Apparently this is not an issue in Ebitengine.

`time.Sleep` freezes when you define your own `runtime.overrideWrite` and redirect `runtime.write` to a file under a Steam local storage. That's still mysterious...
