### ISSUE TITLE
OpenGL: sometimes wrong texture being written to

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2525]
### Ebitengine Version

2.2.0 to 2.5.0

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19 linux/amd64

### What steps will reproduce the problem?

This happens in my game AAAAXY when disabling blurs and font glyph caching (or in 2.5.0-alpha.10, always happens as font glyph caching no longer works due to the new better hinting support - I may need to work around that separately, but first will benchmark if font rendering is still a problem anyway).

Repro and apitrace debug see https://github.com/divVerent/aaaaxy/issues/68#issuecomment-1374303258

Basically compile AAAAXY and run:

./aaaaxy -pin_fonts_to_cache=false -draw_blurs=false

Then when the game launched, press escape for menu.

Or use the "ebi25" branch on https://github.com/divVerent/aaaaxy/ and just run "make run" then in game press escape - in 2.5.0-alpha.10, the issue happens right away.

### What is the expected result?

Fonts appear in game.

![20230106-193853](https://user-images.githubusercontent.com/251568/211122752-f42f7ee7-a100-4723-a8ff-643f4f0324e5.png)

### What happens instead?

Some or all characters missing. (The circle is OK, I pressed esc at a different time)

![20230106-193908](https://user-images.githubusercontent.com/251568/211122765-33c26cfc-4b75-49a9-8027-42e798851457.png)

### Anything else you feel useful to add?

Seems like some glBindTextures calls are forgotten. The state tracking seems broken; if glActiveTexture is used, glBindTexture in Ebitengine keeps the previous texture index while in OpenGL it now has the new texture unit's index.

Going to send a pull request. Sadly I have no shorter repro, and the fix may be suboptimal for performance.

**Comment by divVerent** [comment]
This issue seems to exist for ages; 2a8e8d0eb66ec909486b75c4717ff00d33c1b2d8 was found by bisecting but that just switched the code path away from PBOs.

**Comment by divVerent** [comment]
I tried but it's not that simple to reproduce.

But while at it, there seems to be more weird - it seems like after useProgram(), ActiveTexture is not reset, which _might_ be fine (subsequent code then is on texture unit 1 or 2, not 0, until the next shader draw call) but is at the very least weird.

**Comment by divVerent** [comment]
I found a way - but this is quite intricate and depends on the specific bug and will not detect possible other texture unit mishaps.

**Comment by divVerent** [comment]
This test is pre-failing on both checks: in the first dst test, it verifies that src1, not src2, was copied to dst, and in the second dst test, it verifies that WritePixels on src2 actually overwrote src1.

**Comment by divVerent** [comment]
BTW, I am intentionally not reading back src1 or src2 directly - only the state on the GPU is messed up, but the CPU copies of the textures should be fine.

**Comment by hajimehoshi** [comment]
As this bug appears only when using multiple textures, shaders, and a quite tricky code, I don't backport this to v2.4.

**Comment by divVerent** [comment]
Yeah; I can repro it with my game in 2.4 but only by turning off the glyph caching flag. It's been there since 2.2 and I hadn't even noticed; so probably OK not to backport.
