### ISSUE TITLE
text: request a variant of CacheGlyphs that caches glyphs _entirely_

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2528]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [X] Android
- [X] iOS
- [X] Nintendo Switch
- [X] Xbox
- [X] Web Browsers

### What feature would you like to be added?

For performance reasons, I need to pin all glyphs to cache that my font may be using.

I am aware of CacheGlyphs(), which until recently has done that; however, now it only caches the glyphs necessary to render the given string.

The difference is that since recently, each glyph can have four variants depending on its x offset.

I do think CacheGlyphs() is within spec, which is why I am considering this a FR, not a bug. Maybe what I need is something like CacheAllGlyphs which then takes a []rune and not a string, and caches all that is needed to render any string consisting of these runes, not just one specific string?

(Obviously I could implement my own workaround: manipulate a font so a character - say, "\001" - I am not using has a width of 1/4 pixel, and call CacheGlyphs with "charset\n\001charset\n\001\001charset\n\001\001\001charset" to cover all cases - but I do not think this would be a great idea, and relies heavily on how Ebitengine does glyph coordinate rounding)

Edit: scratch that about cache size - any glyph used or cached within the last 60 frames is not freed, so if I call CacheGlyphs once per frame, I can already have any cache size I want.

### Why is this needed?

Otherwise, frames where a new text appears occasionally have lag spikes in my game AAAAXY because font rendering can be expensive. It is just a single spike as subsequent frames have all they need in glyph cache, but still is annoying and jarring.

**Comment by hajimehoshi** [comment]
I believe AAAAXY uses only Latin glyphs. Currently the size of the cache is 512 for one face. Isn't this really enough?

**Comment by hajimehoshi** [comment]
> The difference is that since recently, each glyph can have four variants depending on its x offset.

Ah sorry, I forgot that. That makes sense then.

**Comment by divVerent** [comment]
This is the cache size; the second issue here is that I want to cache glyphs in all four variants.

For now I coded up this workaround: https://github.com/divVerent/aaaaxy/commit/19dba865b79f5ead294bcb7e3f275c8250f0ddf9

But better would be having an API to cache all "versions" of a glyph right away.

**Comment by hajimehoshi** [comment]
As the PR seems fine to you, I'll close this issue after the PR is merged. We can adjust the cache size but this is risky. Let's revisit this later.
