### ISSUE TITLE
Feature request: Custom app icon

### ISSUE THREAD

**Issue by martinlindhe** [hajimehoshi/ebiten#253]
This would be useful at least for desktop apps,
possibly also to be used as app icon on mobile / favicon on web.

**Comment by hajimehoshi** [comment]
Thank you for requesting! IMO this is not Ebiten task, but it should be worth writing a document about icons in Ebiten Wiki.

As far as I know:
* Windows: Maybe you can embed the icon with resource files: http://stackoverflow.com/questions/25602600/how-do-you-set-the-application-icon-in-golang
* Mac OS X: There should be a place where icon should be present in .app directory.
* Linux: I don't know :-P
* Android/iOS: You should follow the project file rule. Actually I created mobile apps with Ebiten with icons https://github.com/hajimehoshi/go-inovation

**Comment by martinlindhe** [comment]
Thanks for the info. Indeed it seems this is a packaging task rather than a ebiten feature
