### ISSUE TITLE
examples/audio: no sound plays when a PS5 controller is connected

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2535]
### Ebitengine Version

edc3c829fb699ae08a935115aa3b4917ffb2887c (2.4)

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.19.4

### What steps will reproduce the problem?

1. Run `examples/audio`
2. Connect a PS5 controller

### What is the expected result?

A BGM continues to play

### What happens instead?

A BGM cannot be heard

### Anything else you feel useful to add?

Apparently a PS5 controller is recognized as an audio device.

**Comment by hajimehoshi** [comment]
```
                                ..,   hajimehoshi@HAJIMEHOSHI112E
                    ....,,:;+ccllll   ---------------------------
      ...,,+:;  cllllllllllllllllll   OS: Windows 10 Pro x86_64
,cclllllllllll  lllllllllllllllllll   Host: Parallels Software International Inc. Parallels Virtual Platform
llllllllllllll  lllllllllllllllllll   Kernel: 10.0.19044
llllllllllllll  lllllllllllllllllll   Uptime: 23 hours, 1 min
llllllllllllll  lllllllllllllllllll   Packages: 9 (scoop)
llllllllllllll  lllllllllllllllllll   Shell: bash 5.2.12
llllllllllllll  lllllllllllllllllll   Resolution: 3360x2100
                                      DE: Aero
llllllllllllll  lllllllllllllllllll   WM: Explorer
llllllllllllll  lllllllllllllllllll   WM Theme: aero
llllllllllllll  lllllllllllllllllll   Terminal: Windows Terminal
llllllllllllll  lllllllllllllllllll   CPU: Intel i7-1068NG7 (2) @ 2.310GHz
llllllllllllll  lllllllllllllllllll   GPU: Caption
`'ccllllllllll  lllllllllllllllllll   GPU: Parallels Display Adapter (WDDM)
       `' \*::  :ccllllllllllllllll   GPU
                       ````''*::cll   Memory: 5352MiB / 8169MiB
                                 ``
```

**Comment by superloach** [comment]
doesn't the ps5 controller have a speaker in it? it's probably windows being weird and reporting it as an output device.

**Comment by hajimehoshi** [comment]
Yes, a PS5 controller is a speaker.

![image](https://user-images.githubusercontent.com/16950/211887827-1f38b94e-8862-46c9-93af-941192378f83.png)

This issue doesn't happen when not selecting the controller as a speaker explicitly. So there is a way to avoid this issue.

**Comment by hajimehoshi** [comment]
On second thought, I'm not sure this is fixable.

**Comment by hajimehoshi** [comment]
So, it sounds like a user's responsibility which speaker is used. The user can avoid selecting the controller explicitly.

At least, the latest Oto fixed a crash issue by connecting a PS5 controller (this is mysterious but this happens w/ a Steam game).

Let's mark this issue 'won't fix'.
