### ISSUE TITLE
text: allow use of []rune besides string in Draw* functions

### ISSUE THREAD

**Issue by pierrec** [hajimehoshi/ebiten#2538]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Having a way to render runes directly and without allocating.

### Why is this needed?

I am writing a text editor which uses []rune buffers and currently string conversions need to be performed for text.Draw().
I am caching those strings but it adds unnecessary complexity.
I am willing to implement the change :).

**Comment by hajimehoshi** [comment]
If the reason is just you are treating `[]rune` instead of strings in your applications, I don't want to add such a variation so far unfortunately.

**Comment by pierrec** [comment]
I use strings whenever is possible, but here I need to edit its content, so slices are more appropriate.
You can close if you think it doesnt make sense for Ebitengine though :) I would implement it on the side.

**Comment by hajimehoshi** [comment]
If the cost of converting `[]rune` -> `string` matters, the cost of converting `string` to `[]rune` should also matter, but you have already done this conversions in your applications. This is what I don't understand.

I'm afraid I don't introduce `[]rune` version of the function.

**Comment by pierrec** [comment]
No problem. Indeed []rune to string is only my issue, as string to []rune is only done once so acceptable.
