### ISSUE TITLE
libGL loading on Linux does not work without dev package

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2539]
### Ebitengine Version

2.5 (abd293fae63df43114cf05cbd62b06a5598dca18)

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19 linux/amd64

### What steps will reproduce the problem?

Use an Ebitengine based game on a Debian system that has libgl1 but not libgl-dev installed.

### What is the expected result?

Game runs.

### What happens instead?

Game fails with "gl: failed to load libGL.so and libGLESv2.so"

### Anything else you feel useful to add?

On many distros, including Debian, the libGL.so symlink only exists if the developer package (libgl-dev) is installed.

Ebitengine has a search functionality via listLibsInDirectory, but this only works if LD_LIBRARY_PATH is used to point at the library, which isn't the case by default on Debian.

Suggest something dumb like

```
libNames := []string{libName, libName + ".2", libName + ".1", libName + ".0"}
```

(BTW, I also noticed that the code prefers the unsuffixed one which matches the dev package and thus is usually latest, but then .1 over .2 over .3... I suppose the ordering of the suffixed versions should be reversed like above to always prefer the newest; IIRC this only applies to NetBSD, as anywhere else there only ever has been a libGL.so.1)

**Comment by hajimehoshi** [comment]
Thanks,

> libNames := []string{libName, libName + ".2", libName + ".1", libName + ".0"}

My worry is that `2` is always the latest or not.

> but then .1 over .2 over .3... I suppose the ordering of the suffixed versions should be reversed like above to always prefer the newest; IIRC this only applies to NetBSD, as anywhere else there only ever has been a libGL.so.1)

1) Is the suffix always a number?
2) If a file name has multiple version suffixes (e.g. `libGL.so.1.0`), what kind of order should be applied?

My understanding is that the suffixes are always numbers, and we should prefer less suffixes first and then prefer the bigger versions if the numbers of suffixes are the same. Is that correct?

**Comment by hajimehoshi** [comment]
On second thought, depending on `dlopen` for searching an appropriate library would be the best way. So just trying `dlopen` with these file names

```go
libNames := []string{libName, libName + ".2", libName + ".1", libName + ".0"}
```

should work. I'm not sure libGL.so.3 can exist (in the future).

**Comment by hajimehoshi** [comment]
Do this change work to you?

```diff
diff --git a/internal/graphicsdriver/opengl/gl/procaddr_others.go b/internal/graphicsdriver/opengl/gl/procaddr_others.go
index 88df71393..7d84e0cc9 100644
--- a/internal/graphicsdriver/opengl/gl/procaddr_others.go
+++ b/internal/graphicsdriver/opengl/gl/procaddr_others.go
@@ -40,9 +40,7 @@ import "C"
 import (
 	"fmt"
 	"os"
-	"path/filepath"
 	"runtime"
-	"sort"
 	"strings"
 	"unsafe"
 )
@@ -52,59 +50,6 @@ var (
 	libGLES unsafe.Pointer
 )
 
-// listLibs returns an appropriate library file paths based on the given library paths and the library name as a prefix.
-// Note that the found libraries might not be available e.g. due to architecture mismatches.
-func listLibs(libraryPaths []string, libName string) ([]string, error) {
-	// LD_LIBRARY_PATH might be empty. Use the original name as a candidate.
-	libNames := []string{libName}
-
-	// Look for a library file. In some environments like Steam, a library with the exactly same name might not exist (#2523).
-	// For example, libGL.so.1 might exist instead of libGL.so.
-	for _, dir := range libraryPaths {
-		libs, err := listLibsInDirectory(dir, libName)
-		if err != nil {
-			return nil, err
-		}
-		if len(libs) == 0 {
-			continue
-		}
-
-		// The file names are sorted in the alphabetical order.
-		// TODO: What is the best version to use?
-		sort.Strings(libs)
-
-		libNames = append(libNames, libs...)
-	}
-
-	return libNames, nil
-}
-
-// listLibsInDirectory returns library file paths with the given prefix in the directory.
-// Note that the found libraries might not be available e.g. due to architecture mismatches.
-func listLibsInDirectory(dir string, prefix string) ([]string, error) {
-	ents, err := os.ReadDir(dir)
-	if err != nil {
-		return nil, err
-	}
-
-	var files []string
-	for _, ent := range ents {
-		if ent.IsDir() {
-			continue
-		}
-		if ent.Name() == prefix {
-			files = append(files, filepath.Join(dir, ent.Name()))
-			continue
-		}
-		if strings.HasPrefix(ent.Name(), prefix+".") {
-			files = append(files, filepath.Join(dir, ent.Name()))
-			continue
-		}
-	}
-
-	return files, nil
-}
-
 func (c *defaultContext) init() error {
 	var preferES bool
 	if runtime.GOOS == "android" {
@@ -120,15 +65,9 @@ func (c *defaultContext) init() error {
 		}
 	}
 
-	libraryPaths := filepath.SplitList(os.Getenv("LD_LIBRARY_PATH"))
-
 	// Try OpenGL first. OpenGL is preferrable as this doesn't cause context losts.
 	if !preferES {
-		names, err := listLibs(libraryPaths, "libGL.so")
-		if err != nil {
-			return err
-		}
-		for _, name := range names {
+		for _, name := range []string{"libGL.so", "libGL.so.2", "libGL.so.1", "libGL.so.0"} {
 			cname := C.CString(name)
 			lib := C.dlopen(cname, C.RTLD_LAZY|C.RTLD_GLOBAL)
 			C.free(unsafe.Pointer(cname))
@@ -140,11 +79,7 @@ func (c *defaultContext) init() error {
 	}
 
 	// Try OpenGL ES.
-	names, err := listLibs(libraryPaths, "libGLESv2.so")
-	if err != nil {
-		return err
-	}
-	for _, name := range names {
+	for _, name := range []string{"libGLESv2.so", "libGLESv2.so.2", "libGLESv2.so.1", "libGLESv2.so.0"} {
 		cname := C.CString(name)
 		lib := C.dlopen(cname, C.RTLD_LAZY|C.RTLD_GLOBAL)
 		C.free(unsafe.Pointer(cname))
```

**Comment by hajimehoshi** [comment]
http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/pkgtools/x11-links/files/xfree.MesaLib NetBSD has much more versions...

**Comment by hajimehoshi** [comment]
From https://lists.freedesktop.org/archives/mesa-dev/2012-September/027295.html, I think

```go
[]string{"libGL.so", "libGL.so.1"}
```

and

```go
[]string{"libGLESv2.so", "libGLESv2.so.2"}
```

seem enough.

**Comment by hajimehoshi** [comment]
Confirmed my suggestion worked on Steam Deck.
