### ISSUE TITLE
Example: infinite scroll

### ISSUE THREAD

**Issue by martinlindhe** [hajimehoshi/ebiten#254]
Hello, I created an example for "infinite tile scrolling", and published it here: https://github.com/martinlindhe/eb-tilescroll

If interested, i can prepare a pull request to add this as an example to ebiten.

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look!

**Comment by hajimehoshi** [comment]
One question: what's the license of the image?

**Comment by martinlindhe** [comment]
not sure about the image, found it here https://shannisgit294.files.wordpress.com/2012/11/desert.png

**Comment by hajimehoshi** [comment]
Hmm, it's risky to use this at least in Ebiten repository. I'm fine with your example with another clearly-licensed image.

**Comment by martinlindhe** [comment]
would cc0 license work? (https://creativecommons.org/publicdomain/zero/1.0/), looking for some other tile to use from http://opengameart.org/ ...

**Comment by hajimehoshi** [comment]
CC0 works perfectly!

**Comment by martinlindhe** [comment]
great :) updated repo with image http://opengameart.org/node/8016 which has a cc0 license

**Comment by hajimehoshi** [comment]
Thank you! Please create a PR.

**Comment by martinlindhe** [comment]
PR is #255, closing this one

**Comment by hajimehoshi** [comment]
Thank you!
