### ISSUE TITLE
Set() doesn't work with Fill(); DebugPrint() fixes it

### ISSUE THREAD

**Issue by venning** [hajimehoshi/ebiten#2542]
### Ebitengine Version

v2.4.15

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19.1 darwin/amd64

### What steps will reproduce the problem?

```
package main

import (
	"image/color"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

var showFill = true
var showDebug = true
var grey = color.RGBA{0x55, 0x55, 0x55, 0xff}
var red = color.RGBA{0xff, 0x00, 0x00, 0xff}

type Game struct{}

func (g *Game) Update() error {
	if inpututil.IsKeyJustPressed(ebiten.KeyF) {
		showFill = !showFill
	}
	if inpututil.IsKeyJustPressed(ebiten.KeyD) {
		showDebug = !showDebug
	}
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	if showFill {
		screen.Fill(grey)
	}

	cx, cy := ebiten.CursorPosition()
	screen.Set(cx, cy, red)

	if showDebug {
		ebitenutil.DebugPrint(screen, "Press [D] to toggle debug\nPress [F] to toggle fill")
	}
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return 200, 100
}

func main() {
	ebiten.SetWindowSize(800, 400)
	ebiten.SetWindowTitle("test")
	ebiten.RunGame(&Game{})
}
```

### What is the expected result?

`Set()` should be drawing a single red pixel that follows the cursor.

(You can press `D` to toggle the `DebugPrint()` usage; and press `F` to toggle the `Fill()` usage.)

### What happens instead?

`Set()` does *not* draw the pixel if:
 - `Fill()` is used, and `DebugPrint()` is not used

`Set()` draws the pixel if:
 - `Fill()` is used, and `DebugPrint()` is used
 - `Fill()` is not used, and `DebugPrint()` is used
 - `Fill()` is not used, and `DebugPrint()` is not used

### Anything else you feel useful to add?

MacOS Monterey 12.4
Macbook Pro (15-inch, Retina, Mid 2015)
This was tested under both Metal and OpenGL.

**Comment by hajimehoshi** [comment]
I'll take a look later soon, thanks!

**Comment by venning** [comment]
For future reference, should I be testing things like this against a different branch?

**Comment by hajimehoshi** [comment]
> For future reference, should I be testing things like this against a different branch?

Yeah, testing various branches is very helpful.
