### ISSUE TITLE
DirectX Performance vs OpenGL for many textures

### ISSUE THREAD

**Issue by Distortions81** [hajimehoshi/ebiten#2562]
### Ebitengine Version

2.4.16

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.20

### What steps will reproduce the problem?

https://github.com/Distortions81/Ebiten24DirectXIssueDraw
This replicates the problem.

### What is the expected result?

The performance should be vaguely similar.

### What happens instead?

DirectX performance is roughly 30% of OpenGL in this case.

### Anything else you feel useful to add?

If the answer to this is "won't fix", I have no issue with that at all.
Mostly reporting in case there is an underlying issue, and you asked for a minimal example.

Using filter_linear makes the slowest scenes render faster, but the overall performance drops.
I am using filter_nearest intentionally.

I will probably use some LoD/mipmap and more render batching in my game to avoid the issue.

**Comment by hajimehoshi** [comment]
Thanks, I'll take a look!

**Comment by hajimehoshi** [comment]
I've confirmed this issue with v2.4, and also confirmed that this worked well with v2.5. Please try Ebitengine v2.5.0-alpha.12 (not released yet though).

Your program seems to create too many draw command after a while. You can confirm this with `-tags=ebitenginedebug`. Optimizing such a situation is out of scope so far.

So, let me close this issue as wont-fix.
