### ISSUE TITLE
Crashing on monitor sleep

### ISSUE THREAD

**Issue by TTSKarlsson** [hajimehoshi/ebiten#2568]
### Ebitengine Version

v2.4.16

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.20

### What steps will reproduce the problem?

I can reproduce this on Windows. Let monitor go to sleep, wait a few seconds then wake it up. Tested both by waiting for 5 minutes as in power options for the screen to go to sleep (no hibernation/computer sleep), and by explicitly letting monitor go to sleep with `nircmd monitor off` (a well known Windows tool) and then waking it up. 

### What is the expected result?

That it doesn't lose it's monitor context / doesn't crash.

### What happens instead?

It crashes with this error:

![20230207_104350_1024x759](https://user-images.githubusercontent.com/9962943/217210172-877e0b70-2a11-440e-8aca-10769a4ea606.png)

### Anything else you feel useful to add?

I see similar problems in the descriptions of issues #2554 and #2551

The app itself is simple, drawing some ebiten.Image's just to test the engine and see if it's usable for me.

**Comment by hajimehoshi** [comment]
I'll take a look, thanks!

**Comment by TTSKarlsson** [comment]
I discovered something that might be important for reproducing.

If I go to monitor off mode and wake it up **_before_** the screens actually have gone in to power save mode (it takes about 10-15 seconds or so before mine does), it doesn't crash.

One important ramification this can have when reproducing is that not all screens report power save, but there driver card acts like they are still connected even when off (often with HDMI / laptops).

I tried a portable screen I have, that I connect through HDMI, and with my normal screens disconnected. With this it doesn't crash, and the OS believes the screen is still there even though it shouldn't be. (I can see that with a remote desktop app, that needs a connected screen to remote the desktop).

This led me to test what happens if I pull out the cable to the screen that the app window is running on.

The result is the same as with sleep / monitor power save, it crashes with the same message.

**Comment by hajimehoshi** [comment]
Seems related to #2488

**Comment by hajimehoshi** [comment]
I think this is the same issue as #2488, and this was already fixed in v2.5. I have not backport the fix to v2.4, but if you want, I'm fine to backport this.

**Comment by TTSKarlsson** [comment]
Is there a simple way to get 2.5 ? If so I could use that.

But maybe it's best to have a working stable branch anyways. Up to you, mate! 👍

**Comment by hajimehoshi** [comment]
> Is there a simple way to get 2.5 ? If so I could use that.

You can try this in your project:

```
go get github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.12
```

> But maybe it's best to have a working stable branch anyways. Up to you, mate! 👍

I didn't backport this fix since I was worried that backporting itself might cause another issue. However, the fix seemed safe so far. I'll consider this tomorrow. Thanks!

**Comment by TTSKarlsson** [comment]
I did a quick test, and it works perfectly!
