### ISSUE TITLE
vector: intermittent stroke on vector.CubicTo()

### ISSUE THREAD

**Issue by sedyh** [hajimehoshi/ebiten#2572]
### Ebitengine Version

v2.5.0-alpha.12

### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.20

### What steps will reproduce the problem?

Example:
```go
package main

import (
	"image"
	"image/color"
	"log"
	"math"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/vector"
)

func main() {
	ebiten.SetWindowResizingMode(ebiten.WindowResizingModeEnabled)
	if err := ebiten.RunGame(NewGame()); err != nil {
		log.Fatal(err)
	}
}

type Game struct {
	Empty *ebiten.Image
}

func NewGame() *Game {
	return &Game{Empty: Empty()}
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	sw, sh := screen.Bounds().Dx(), screen.Bounds().Dy()
	size := int(math.Min(float64(sw), float64(sh)) * 0.2)
	bounds := image.Rect(sw/2, sh/2, sw/2, sh/2).Inset(-size)
	var path vector.Path
	path.MoveTo(float32(bounds.Min.X), float32(bounds.Min.Y))
	path.CubicTo(
		float32(bounds.Min.X),
		float32(bounds.Max.Y),
		float32(bounds.Max.X),
		float32(bounds.Min.Y),
		float32(bounds.Max.X),
		float32(bounds.Max.Y),
	)
	g.DrawPath(screen, path, 15, color.White)
	vector.StrokeRect(
		screen,
		float32(bounds.Min.X),
		float32(bounds.Min.Y),
		float32(bounds.Dx()),
		float32(bounds.Dy()),
		2,
		color.White,
	)
}

func (g *Game) Layout(w, h int) (int, int) {
	return w, h
}

func (g *Game) DrawPath(screen *ebiten.Image, path vector.Path, stroke int, color color.Color) {
	op := &ebiten.DrawTrianglesOptions{
		FillRule:  ebiten.EvenOdd,
		Filter:    ebiten.FilterLinear,
		AntiAlias: true,
	}
	strokeOp := &vector.StrokeOptions{}
	strokeOp.Width = float32(stroke)
	strokeOp.LineCap = vector.LineCapRound
	vs, is := path.AppendVerticesAndIndicesForStroke(nil, nil, strokeOp)
	cr, cg, cb, ca := color.RGBA()
	for i := range vs {
		vs[i].SrcX = 1
		vs[i].SrcY = 1
		vs[i].ColorR = float32(cr) / float32(0xffff)
		vs[i].ColorG = float32(cg) / float32(0xffff)
		vs[i].ColorB = float32(cb) / float32(0xffff)
		vs[i].ColorA = float32(ca) / float32(0xffff)
	}
	screen.DrawTriangles(vs, is, g.Empty, op)
}

func Empty() *ebiten.Image {
	emptyImage := ebiten.NewImage(3, 3)
	emptyImage.Fill(color.White)
	return emptyImage.SubImage(image.Rect(1, 1, 2, 2)).(*ebiten.Image)
}
```

### What is the expected result?

Continuous stroke.

### What happens instead?

<img width="241" alt="" src="https://user-images.githubusercontent.com/19890545/218331564-852d3d4e-fb35-4c68-b062-b51829e89560.png">

**Comment by sedyh** [comment]
Also, when parts of the curve are superimposed on each other, there is an overlap like xor.

![image](https://user-images.githubusercontent.com/19890545/218331721-017d34f6-4de3-432e-9dab-c73dbafb6a71.png)

**Comment by sedyh** [comment]
Looks like `ebiten.DrawTrianglesOptions.FillRule = ebiten.FillAll` resolves it.
But it still shouldn't behave like this with EvenOdd right?

![image](https://user-images.githubusercontent.com/19890545/218337951-5a054942-3caf-48e4-bed6-9b8966e6ea94.png)

**Comment by hajimehoshi** [comment]
https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.12/vector#Path.AppendVerticesAndIndicesForStroke

> The returned values are intended to be passed to DrawTriangles or DrawTrianglesShader with a solid (non-transparent) color with the FillAll fill rule (not the EvenOdd fill rule).

So this is working as intended. I have a plan to support transparent colors btw.
