### ISSUE TITLE
.github/workflows: use `https://go.dev/dl/?mode=json` to get Go versions for vuln.yml

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2573]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

https://stackoverflow.com/questions/46623153/how-do-download-the-latest-version-of-go

> The problem with using curl https://golang.org/VERSION?m=text is that on some days, it will give "bleeding edge" result that is not actually available for download. Like today 2022-04-12 (: It returns 1.18.1 which is not yet available for download.

**Comment by nitinmewar** [comment]
can I work on it?

**Comment by hajimehoshi** [comment]
Yes
