### ISSUE TITLE
ebitenmobile: document minimum Android and iOS SDK versions

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2579]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [X] Android
- [X] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

It would be very useful if the documentation at https://ebitengine.org/en/documents/mobile.html could state what is the minimum SDK version of Android and iOS for which ebitenmobile is known to work.

I currently can't get this info from either ebitenmobile's nor gomobile's docs (but ebitenmobile may have higher requirements than gomobile due to using additional APIs).

### Why is this needed?

In my concrete case, it'd e.g. help me know if buying a cheap iPhone 6 would help me port my game to iOS, or if that phone is already too old to run anything ebitengine.

(Min SDK version info would probably also help for Windows and macOS targets, but is usually less of an issue there)

**Comment by hajimehoshi** [comment]
The minimum iOS version is 13.0, and the minimum Android SDK is 16 (there was an outdated note in gomobile https://go-review.googlesource.com/c/mobile/+/472236).
