### ISSUE TITLE
Allow hiding cursor

### ISSUE THREAD

**Issue by blixt** [hajimehoshi/ebiten#258]
GLFW has an option to make the cursor hidden:

```go
window.SetInputMode(glfw.CursorMode, glfw.CursorHidden)
```

This would be useful to have control of.

**Comment by hajimehoshi** [comment]
Thank you for your suggestion. Let me consider this.

Compared with #252, this seems easier to introduce and less risky.

**Comment by hajimehoshi** [comment]
> window.SetInputMode(glfw.CursorMode, glfw.CursorHidden)

Hmm, does GLFW3.1 or 3.2 has such API? I couldn't find that.

**Comment by blixt** [comment]
This is the official GLFW doc (`glfwSetInputMode`): http://www.glfw.org/docs/latest/group__input.html#gaa92336e173da9c8834558b54ee80563b

The one I referenced was from the Go bindings: https://github.com/go-gl/glfw/blob/master/v3.2/glfw/input.go#L320-L324

**Comment by hajimehoshi** [comment]
Thanks!

**Comment by hajimehoshi** [comment]
Done.
