### ISSUE TITLE
internal/atlas: unexpectedly inefficient texture packing

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2581]
### Ebitengine Version

b08b7409144710d8342655fb823700318257ca9c

### Operating System

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20 darwin/amd64

### What steps will reproduce the problem?

1. Run this program with `-tags=ebitenginedebug`

```go
package main

import (
        "fmt"
        "image/color"

        "github.com/hajimehoshi/ebiten/v2"
        "github.com/hajimehoshi/ebiten/v2/ebitenutil"
        "github.com/hajimehoshi/ebiten/v2/inpututil"
)

type game struct {
        imgs      []*ebiten.Image
        made1k    int
        made2k    int
        made4k    int
        made8k    int
        pixCount  uint64
}

func (g *game) maybeAddImage(key ebiten.Key, size int, counter *int) {
        if inpututil.IsKeyJustPressed(key) {
                img := ebiten.NewImage(size, size)
                switch size {
                case 1024:
                        img.Fill(color.RGBA{0x30, 0xff, 0xff, 0xff})
                case 2048:
                        img.Fill(color.RGBA{0x60, 0xff, 0xff, 0xff})
                case 4096:
                        img.Fill(color.RGBA{0x90, 0xff, 0xff, 0xff})
                case 8192:
                        img.Fill(color.RGBA{0xc0, 0xff, 0xff, 0xff})
                }
                g.imgs = append(g.imgs, img)
                *counter++
                g.pixCount += uint64(size * size * 4)
        }
}

func (g *game) Update() error {
        g.maybeAddImage(ebiten.Key1, 1024, &g.made1k)
        g.maybeAddImage(ebiten.Key2, 2048, &g.made2k)
        g.maybeAddImage(ebiten.Key4, 4096, &g.made4k)
        g.maybeAddImage(ebiten.Key8, 8192, &g.made8k)
        return nil
}

func (g *game) Draw(screen *ebiten.Image) {
        ebitenutil.DebugPrint(screen, fmt.Sprintf("(1)k: %3d (2)k: %3d (4)k: %3d (8)k: %3d Raw bytes: %dM", g.made1k, g.made2k, g.made4k, g.made8k, g.pixCount/1024/1024))
}

func (g *game) Layout(w, h int) (int, int) {
        return w, h
}

func main() {
        ebiten.SetWindowSize(640, 480)
        ebiten.RunGame(&game{})
}
```

2. Press 1, 2, 4, 8

### What is the expected result?

All the images are on the same texture atlas

### What happens instead?

Texture atlases are created for each image

### Anything else you feel useful to add?

```
Update count per frame: 1
Internal image sizes:
  1: (1024, 1024)
  2: (16, 16)
  3: (16, 16)
  4: (16, 16)
  5: (1024, 512)
  6: (1280, 960)
  7: (2048, 2048)
  8: (4096, 4096)
  9: (8192, 8192)
  10: (16384, 16384)
Graphics commands:
  draw-triangles: dst: 5 <- src: [1, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 5 <- src: [1, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 432, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
```

I don't think this is a macOS-specific issue.

**Comment by hajimehoshi** [comment]
Failed to create a good test for this

```diff
diff --git a/internal/atlas/export_test.go b/internal/atlas/export_test.go
index dc7529963..666449d2d 100644
--- a/internal/atlas/export_test.go
+++ b/internal/atlas/export_test.go
@@ -59,6 +59,12 @@ func (i *Image) EnsureIsolatedForTesting() {
        i.ensureIsolated()
 }
 
+func (i *Image) BackendForTesting() *backend {
+       backendsM.Lock()
+       defer backendsM.Unlock()
+       return i.backend
+}
+
 var FlushDeferredForTesting = flushDeferred
 
 var FloorPowerOf2 = floorPowerOf2
diff --git a/internal/atlas/image_test.go b/internal/atlas/image_test.go
index 972f31dee..cb1d1f711 100644
--- a/internal/atlas/image_test.go
+++ b/internal/atlas/image_test.go
@@ -784,4 +784,25 @@ func TestPowerOf2(t *testing.T) {
        }
 }
 
+func TestExtend2(t *testing.T) {
+       img0 := atlas.NewImage(512, 512, atlas.ImageTypeRegular)
+       defer img0.MarkDisposed()
+       img0.WritePixels(make([]byte, 4*512*512), 0, 0, 512, 512)
+
+       img1 := atlas.NewImage(1024, 1024, atlas.ImageTypeRegular)
+       defer img1.MarkDisposed()
+       img1.WritePixels(make([]byte, 4*1024*1024), 0, 0, 1024, 1024)
+
+       img2 := atlas.NewImage(2048, 2048, atlas.ImageTypeRegular)
+       defer img2.MarkDisposed()
+       img2.WritePixels(make([]byte, 4*2048*2048), 0, 0, 2048, 2048)
+
+       if img0.BackendForTesting() != img1.BackendForTesting() {
+               t.Errorf("img0 and img1 should share the same backend but not")
+       }
+       if img0.BackendForTesting() != img2.BackendForTesting() {
+               t.Errorf("img0 and img2 should share the same backend but not")
+       }
+}
+
 // TODO: Add tests to extend image on an atlas out of the main loop
```

This passed (unexpectedly)

**Comment by hajimehoshi** [comment]
Damn, this is due to `Fill`. The same thing also happen with `Clear`.

**Comment by erexo** [comment]
This may be completely unrelated but I do have a case where I call `ebiten.NewImage` (and fill that new image from other ebiten.Image's) for each panel and scrollbar resize, the images are not packet together as well. So each `ebiten.NewImage` is a new internal atlas.
![image](https://user-images.githubusercontent.com/6548968/220774055-c5b9bf7a-027d-4b06-a255-bcb255b7531c.png)

As I mentioned I'm not sure if this is anyhow related to this issue or if this is an issue at all, but I felt like that this is worth mentioning here

**Comment by hajimehoshi** [comment]
I think this is related. The number of the images should be reduced by fixing this issue.

**Comment by hajimehoshi** [comment]
@erexo This is an experimental change and I might update this later, but there is an experimental commit: b94ed0f24cd3415c20a5a644b9d9bb70e3525770

**Comment by erexo** [comment]
this change actually improved a lot!
![image](https://user-images.githubusercontent.com/6548968/221402165-7c19514e-ed94-4e44-8f2d-541f291dd4a5.png)
![image](https://user-images.githubusercontent.com/6548968/221402173-1a717ce7-70ca-4047-80be-d8d241378b33.png)
Everything is packed into two internal images and disposed images are cleared properly. I even noticed that when GC needs to clear a lot (>500+) of images at once, there is no lag! Thanks for contribution

**Comment by hajimehoshi** [comment]
Thank you for confirming!

I'll brush up this change and commit it to the main branch later.

**Comment by erexo** [comment]
I just found out that this commit has some performance issues, when I tested it against current 'main' 62e08e735665709c4e1dde205a2a4539e721be77 I found a noticeable difference with OpenGL and a massive difference with DirectX.
OpenGL: 300-350 -> 270-300
DirectX: 240-250 -> 25-30

The sidenote is that I was not upgrading to the main for a little while (I was around 60 commits behind), and when I did I noticed quite large fps drop as well. I will investigate that further to try to pick actual commits that could cause that and I'll report it in a separate issue if needed.
OpenGL: 700-800 -> 300-350
DirectX: 300-440 -> 240-250
So in general, I was not updating my `main` for ~month, and after I did to check your commit in this issue my fps drop by around 60% for opengl and around 90% for directx.

**Comment by hajimehoshi** [comment]
My guess is that this increases draw calls unfortunately. I'll take a look...

**Comment by hajimehoshi** [comment]
Confirmed `TestImageEdge` calls `(*atlas.Image).allocate` much more times than before.

**Comment by hajimehoshi** [comment]
@erexo Colud you try f6660bd2e0dd1ad505f6512e4e02a4405d133585? Thanks,

**Comment by erexo** [comment]
f6660bd2e0dd1ad505f6512e4e02a4405d133585 is working just fine, I didn't notice any fps drops and it still merges images into one or few internal atlases. Good job!

**Comment by hajimehoshi** [comment]
Thank you for confirming!

**Comment by hajimehoshi** [comment]
After this change, the result of the original program is like this:

```
Update count per frame: 1
Internal image sizes:
  1: (1024, 1024)
  2: (16, 16)
  4: (1024, 512)
  5: (1280, 960)
  9: (16384, 16384)
Graphics commands:
  draw-triangles: dst: 4 <- src: [1, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 4 <- src: [1, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 330, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 5 (screen) <- src: [4, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
```
