### ISSUE TITLE
Kage: uniform variable assignment

### ISSUE THREAD

**Issue by mymmrac** [hajimehoshi/ebiten#2590]
### Ebitengine Version

v2.5.0-alpha.13

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.1 linux/amd64

### What steps will reproduce the problem?

```go
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
    texCoord += 1 // OK
    return vec4(1)
}
```

```go
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
    texCoord = 1 // Error
    return vec4(1)
}
```
Error:
`Compile shader<line>:<col>: a uniform variable cannot be assigned`

### What is the expected result?

Consistent behavior for uniform variables assignment

### What happens instead?

One ok, one error

**Comment by hajimehoshi** [comment]
Good catch!

**Comment by hajimehoshi** [comment]
While this is an issue, this is not urgent. Let me change the milestone.

**Comment by hajimehoshi** [comment]
Fixed
