### ISSUE TITLE
ebitenutil.DrawRect draws a different color in ebiten 2.5 vs ebiten 2.4 when transparency is involved

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#2591]
### Ebitengine Version

2.5 06c141475c0d

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.20.1

### What steps will reproduce the problem?

all a function like this, draw it over a black background:

`ebitenutil.DrawRect(screen, 100, 100, 200, 200, color.RGBA{0xff, 0x63, 0x47, 0xa0})`

This draws different colors in ebiten 2.4 vs 2.5. Which one is correct?

### What is the expected result?

In ebiten 2.4, this draws a brown semi-transparent box. I expect similar behavior on ebiten 2.5. Or perhaps this is an intended change.

### What happens instead?

In ebiten 2.5, it draws a pink semi-transparent box.

### Anything else you feel useful to add?

On the left is how this rect looks in ebiten 2.4. On the right, how it looks in ebiten 2.5. Both are when drawn over a black background.

![image](https://user-images.githubusercontent.com/61067263/222816575-a3959760-4cb0-4886-9d3c-19ae4ea43715.png)

**Comment by corfe83** [comment]
Is this an intended behavior change? Or a bug?

**Comment by hajimehoshi** [comment]
```
color.RGBA{0xff, 0x63, 0x47, 0xa0}
```

This value is not correct as a premultiplied alpha value as the red (0xff) exceeds the alpha (0xa0). This is an expected change in v2.5. 

See also: https://github.com/hajimehoshi/ebiten/issues/2082

**Comment by corfe83** [comment]
Thanks for confirming, I'll fix up my code then!
