### ISSUE TITLE
android: trigger buttons start out pressed

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2598]
### Ebitengine Version

main (36e2d0ec40c9956d9ae1e8514d2912651df61f00)

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [X] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.19.5 linux/amd64

### What steps will reproduce the problem?

Run the gamepad demo, or any game supporting gamepads. Move any OTHER axis on the gamepad (like the left stick) to force a motion event.

### What is the expected result?

Trigger buttons should start out non-pressed.

### What happens instead?

They start out pressed.

### Anything else you feel useful to add?

Likely an Android bug we may need to work around. Seems like MotionEvent does report trigger axes as having a center value until they're first touched by the user.

Need to debug further though to know exact root cause and suggest a solution.

**Comment by hajimehoshi** [comment]
> Ebitengine Version
> main

Could your write the hash?

**Comment by divVerent** [comment]
Added: 36e2d0ec40c9956d9ae1e8514d2912651df61f00

**Comment by hajimehoshi** [comment]
As this is a bug that remains for long time, I don't think this is a release blocker. Let me reset the milestone. If necessary, I can cherry-pick the fix to 2.5.

**Comment by divVerent** [comment]
SGTM. No need to set a milestone for this already. Right now I will stick with my current workaround on simply not using these axes on Android.

**Comment by hajimehoshi** [comment]
Now it's hard to test mobiles as gomobile-build doesn't work unfortunately... https://github.com/hajimehoshi/ebiten/issues/2741

**Comment by hajimehoshi** [comment]
@divVerent Does this issue happen with any gamepads, or a specific gamepad?

**Comment by divVerent** [comment]
Sorry, I have no other gamepad to try this with. I strongly suspect this
affects all though.

**Comment by hajimehoshi** [comment]
I guess onKeyDown was called unexpectedly, but I am not sure. @divVerent Do you have a suggestion to fix this?

**Comment by divVerent** [comment]
It seems events work fine. What happens:

- Normally nothing is pressed.
- Once I touch ANY axis on the gamepad, Ebitengine suddenly considers the trigger buttons pressed.

I found that the MotionEvent does include the trigger values at value zero (center, not depressed), but they have not moved.

I guess a potentially good solution would be to increase trigger travel, i.e. have the trigger buttons only be considered active at, like, > 0.2 (instead of > 0 from the -1 to 1 range)?

**Comment by hajimehoshi** [comment]
Are you talking about a standard button that is mapped to a physical axis? Then we already have a threshold https://github.com/hajimehoshi/ebiten/blob/cd90f083bc1db4bcdda45531182dbdac0f88eb77/internal/gamepaddb/gamepaddb.go#L516 Is the axis value exceeds this threshold?

**Comment by divVerent** [comment]
Yes, it exceeds it - the axis value starts at 0 in the axis range, which is mapped to 0.5 in the button range.

Basically, starting axis values at 0 makes total sense for most axes on a gamepad, as that means they're centered - the bug is that the trigger axes start out centered too. Treating them as a button then maps the centered value to a "50% pressed button", which gets interpreted as a press.

I propose that for trigger buttons we use a higher button press threshold that's above 1/2 - or that we do not perform the mapping (axisValue + 1) / 2 for those, but just max(0, axisValue) (which BTW is what in SDL's syntax "lefttrigger:+a2" would do).

**Comment by hajimehoshi** [comment]
That's odd. For trigger axes, -1 should be the default value which is mapped to 0 as a button value. Is there something wrong in the current gamepad database file for your gamepad?

**Comment by divVerent** [comment]
Maybe I was not clear: this is not about the gamepad database, but about handling gamepads using the default mapping (i.e. NOT using the database).

Android provides APIs that are already gamepad-generic and should usually not need the database - and my gamepad ALMOST works this way, except that trigger buttons start at 0, not -1.

The reason for this is in Android, not Ebitengine, as the same issue exists when using third party gamepad test apps: initially the buttons have no value at all (which is probably where Ebitengine fills in -1), but once I touch ANY axis (e.g. move the joystick), the trigger buttons suddenly report as center value in the first MotionEvent Android sends.

So we actually need to work around an Android bug here, I suppose.

**Comment by hajimehoshi** [comment]
Now Ebitengine does NOT use the Android OS's default mapping (i.e. `(*nativeGamepadImpl).hasOwnStandardLayoutMapping()` returns false), and relies on the database. I refered SDL's implementation.

>  and my gamepad ALMOST works this way

Do you mean you are using non-standard (phyisical) Gamepad APIs intead of standard-gamepad APIs?

**Comment by hajimehoshi** [comment]
So assuming you are using the standard-gamepad APIs that uses the database,

> I am aware I can work around the issue by creating a gamepaddb entry for my gamepad, as the workaround feature is part of the gamepaddb implementation (when registering the trigger axis as +a2 and not a2).

I guess we should update the original database in this case. https://github.com/mdqinc/SDL_GameControllerDB

**Comment by divVerent** [comment]
To be clear: my gamepad is not in the database at all - it uses synthetic mappings from https://github.com/hajimehoshi/ebiten/blob/4b1c0526a7cda62d26fd48f0a1aa6a5dda3392e3/internal/gamepaddb/gamepaddb.go#L593C9-L593C16

And I honestly don't know why Ebitengine does it this way rather than using Android's named button and axis identifiers, which recognize my gamepad correctly, for any other reason than "SDL does it this way too". Clearly this really _tries_ to be a very weird way to do native mappings.

So yes, I could fix this for my gamepad alone by adding a mapping entry, but I'd much prefer a solution that instantly fixes this for ALL gamepads at once (or at the very least all non-mapped ones).

If we want to fix it by adjusting mappings, we could just change AxisScale and AxisOffset in these entries here:

https://github.com/hajimehoshi/ebiten/blob/4b1c0526a7cda62d26fd48f0a1aa6a5dda3392e3/internal/gamepaddb/gamepaddb.go#L752

However as SDL doesn't have a workaround here, I strongly suspect this is the wrong approach, as that likely means that existing mappings do NOT currently work around for this issue.

And the bug is really in Android: the very first MotionEvent - and any subsequent MotionEvent until I ever touch the trigger axis - has the trigger button at center value, but the moment I touch that button and release it, it will return back to -1.

So I suggest one of the following fixes:

- Find a way to only report the actually _changed_ axis values from MotionEvent to Ebitengine and not all axes.
  - It seems to me though that the MotionEvent class doesn't actually expose information about which axes have changed, so reporting all seems necessary.
- On Android (maybe directly in EbitenView.java), do not call `Ebitenmobileview.onGamepadAxisChanged` until the axis value has changed at least once.
  - Variant: same but in `Ebitenmobileview.onGamepadAxisChanged`'s Go implementation itself.
  - As this causes minor issues for gamepads that represent a digital button as an axis (as it can cause the first button press to be ignored), I would suggest limiting this workaround to Android only.
- Set a higher threshold - namely one above the 50% mark - for axis-mapped buttons (at least on Android, at least limited to trigger buttons).
  - That however may change gameplay on devices or platforms where this issue is not happening.
- Map trigger axes to only the upper range, EVEN if the mapping specifies the full range.
- And here comes the crazy solution: implement a double-action/single-action trigger: the FIRST button press after gamepad connect requires going above the 50% mark, but from then on, as the axis now will return to -1 where it should go, use the 30/255 threshold for any further press from then on.

**Comment by hajimehoshi** [comment]
> To be clear: my gamepad is not in the database at all - it uses synthetic mappings from https://github.com/hajimehoshi/ebiten/blob/4b1c0526a7cda62d26fd48f0a1aa6a5dda3392e3/internal/gamepaddb/gamepaddb.go#L593C9-L593C16

In this case, you cannot use the standard-gamepad API. Are you really using [`StandardGamepadButtonValue`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2#StandardGamepadButtonValue)?

> And I honestly don't know why Ebitengine does it this way rather than using Android's named button and axis identifiers, which recognize my gamepad correctly, for any other reason than "SDL does it this way too". Clearly this really tries to be a very weird way to do native mappings.

It's because Android's API might not map to Ebitengine/SDL's standard layout. For example, an "A" button might be mapped to a bottom button or a right button, but we don't know. That's why Ebitengine and SDL rely on the database.

**Comment by hajimehoshi** [comment]
I'll take a look your suggestion carefully tomorrow or later. Thank you for clarifying the situation.

**Comment by divVerent** [comment]
The way I understand it, the native mapping always serves to provide defaults, and then the database is used to override as needed. My issue is clearly not specific to any given gamepad, but should affect ALL gamepad that contain axis-mapped analog buttons, which on standard Xbox gamepads the trigger buttons are.

**Comment by hajimehoshi** [comment]
> And the bug is really in Android: the very first MotionEvent - and any subsequent MotionEvent until I ever touch the trigger axis - has the trigger button at center value, but the moment I touch that button and release it, it will return back to -1.

I didn't know the value went back to -1. In this case, modifying the database would not solve the issue 🤔

**Comment by divVerent** [comment]
Well, modifying the database by just mapping the upper half of the range would just serve to move the button's threshold from 30/255 to 285/510 which is > 0.5 and thus "fixes" the issue. Clearly that's a hack though, and it would require pressing the trigger buttons much farther than currently, but it'd at least fix this bug.

**Comment by hajimehoshi** [comment]
The current issue is that the same axis can take [0, 1] and then [-1, 1] after a while, right? So adding an entry to the database doesn't solve this issue in the first place. Of course, your point that modifying the database is not a general solution is correct.

**Comment by hajimehoshi** [comment]
Let me ask questions:

* Does the axis value take only 0 before touching, and [-1, 1] after touching?
  e.g. 0, 0, 0, 0, ..., 0, (touch), -1, -1, -1, -0.5, 0, 0.5, 1, ...
* Or, does the axis value take [0, 1] before touching and [-1, 1] after touching and releasing?
  e.g. 0, 0.25, 1, 0.5, 0, (release), -1, -1, -1, -0.5, ...

**Comment by divVerent** [comment]
The former behavior is what I observe. To be exact, assuming we only talk about two axes, the behavior is as follows:

```
# First: no option events
# Ebitengine: 0 0 button values.
# Then: slowly pressing down left trigger.
-0.98 0  # Ebitengine: 0.01 0.5
-0.8 0  # Ebitengine: 0.1 0.5
-0.2 0  # Ebitengine: 0.4 0.5
0.2 0  # Ebitengine: 0.6 0.5
1 0  # Ebitengine: 1 0
# Then: releasing left trigger.
0.4 0  # Ebitengine: 0.7 0.5
-0.4 0  # Ebitengine: 0.3 0.5
-1 0  # Ebitengine: 0 0.5
# Then: slowly pressing down right trigger.
-1 -0.98  # Ebitengine: 0 0.01
# From here on, as now both triggers have been touched, all is normal.
```

**Comment by divVerent** [comment]
Which also tells me, the underlying issue is really in how Android builds the MotionEvent. The gamepad has only ever sent an evdev event for the left trigger to the OS, but the OS has to build a MotionEvent including an axis value for the right trigger, and mistakenly fills in a center value there (whereas correct would be the minimum value).

**Comment by hajimehoshi** [comment]
Thank you for clarifying!

> Trigger axes are special there in that their resting position is at the bottom of the range, not at the center.

I agree this assumption. I'm fine to add a workaround to Ebitengine. My current idea is,

* Add a new funciton like `IsAxisInitialized(index int)` to `gamepaddb.GamepadState` interface.
  * `IsAxisInitialized` returns false before a non-zero MotionEvent comes for the axis in Android.
  * `IsAxisInitialized` returns true otherwise.
* Add a hack to return 0 at `gamepaddb.standardButtonValue` and `gamepaddb.StandardAxisValue` if a mapping type is an axis and `IsAxisInitialized` for the axis return false.

Do you think this would work?

**Comment by divVerent** [comment]
Yes, that will work.

**Comment by hajimehoshi** [comment]
Thanks. I'll try to implement this tomorrow.

**Comment by hajimehoshi** [comment]
@divVerent Could you try 46d95eaa6f111c99718ad517e010bfb5e9bd691d? Thanks,

**Comment by divVerent** [comment]
Yes, what happens is:

- The trigger axes immediately get axis values -1 when I connect the gamepad
- On first motion event for a different axis, the trigger axes jump to a zero value

So it seems slightly harder than that.

**Comment by divVerent** [comment]
Ah, the issue is that this code needs to be removed then:

https://github.com/hajimehoshi/ebiten/blob/4b1c0526a7cda62d26fd48f0a1aa6a5dda3392e3/cmd/ebitenmobile/_files/EbitenView.java#L248

**Comment by hajimehoshi** [comment]
> As for my own game - I can't build it at all against your change (but that might be caused by me using just "replace" to build against your change, and not updating go.mod pointing at a release tag):

That's odd. Have you done `go mod tidy`? Also, the latest Ebitengine doesn't use golang.org/x/mobile any longer so you would have to use Ebitengine's RunOnJVM for example.

**Comment by divVerent** [comment]
> > As for my own game - I can't build it at all against your change (but that might be caused by me using just "replace" to build against your change, and not updating go.mod pointing at a release tag):
> 
> That's odd. Have you done `go mod tidy`? Also, the latest Ebitengine doesn't use golang.org/x/mobile any longer so you would have to use Ebitengine's RunOnJVM for example.

That's indeed the issue - gonna fix that when updating to Ebitengine v2.7.0.

Anyway, I think I mostly confirmed the patch and found the one thing still wrong with it by cherrypicking on v2.6.6. So I guess we're good to go.

**Comment by hajimehoshi** [comment]
> Ah, the issue is that this code needs to be removed then:

I'll try to fix this. Thanks,

**Comment by divVerent** [comment]
Confirmed OK.

**Comment by hajimehoshi** [comment]
@divVerent As this change seems less risky, I'm OK to cherry-pick this fix to 2.6 if you want. Do you want it in 2.6?

**Comment by divVerent** [comment]
That would be quite nice. Right now I am working around by entirely disabling the trigger buttons - if this is cherrypicked into 2.6, my next release will enable using trigger buttons as additional jump and action buttons (like on PC), which actually doesn't feel bad when playing even in comparison to the right thumb buttons.

So, your call.

**Comment by hajimehoshi** [comment]
Done (e2f26b9dac546ff80f2713c9e307d086ed0e0041). I'll release v2.6.7 a few days later. Thank you for reporting and investigating the issue!
