### ISSUE TITLE
internal/graphicsdriver/directx: physical screen flickering

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2604]
### Ebitengine Version

v2.6.0-alpha

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.19.6

### What steps will reproduce the problem?

When I upgraded my game to `v2.6.0-alpha` some players reported that their screen started to flicker whenever (but not always) they launch my game on DirectX graphics engine (OpenGL works perfectly fine).

user1:
https://user-images.githubusercontent.com/6548968/225981973-c200c2f4-e902-4007-a3fe-81a17aada786.MOV
user2:
![image](https://user-images.githubusercontent.com/6548968/225982493-31d78d6f-faf5-4b62-ad04-c4e84e7b2bb6.png)

user1 specs:
![image](https://user-images.githubusercontent.com/6548968/225981906-538eddd5-7cca-4439-ad40-c422fa89b6aa.png)

user2 specs:
![image](https://user-images.githubusercontent.com/6548968/225982575-eabbea0a-ba89-4069-8954-0f52967ea468.png)
![image](https://user-images.githubusercontent.com/6548968/225982600-cdf72eb8-fafa-4a66-bc2b-e20f281a62c3.png)

### What is the expected result?

No screen flickering on DX

### What happens instead?

Screen flickering on DX

### Anything else you feel useful to add?

The flickering is only happening on the physical screen layer. ie. PrintScreen would render perfectly fine image where the actual user will see a lot of random noise on the screen.
It looks like my game is burning my player's GPUs so it's kinda worrying

**Comment by hajimehoshi** [comment]
Thank you for reporting. I failed to understand what is flickering from your screenshots.

**Comment by hajimehoshi** [comment]
> It looks like my game is burning my player's GPUs so it's kinda worrying

Could you share the draw commands by -tags=ebitenginedebug ?

**Comment by hajimehoshi** [comment]
> When I upgraded my game to v2.6.0-alpha

What was the last version that worked correctly?

**Comment by erexo** [comment]
> Could you share the draw commands by -tags=ebitenginedebug ?
> 
> EDIT: It's ok to test the build tag on your machine. The draw commands should be the same on any machines.

```
Update count per frame: 0
Internal image sizes:
  8: (2048, 2048)
  10: (1920, 1027)
  16: (4096, 2048)
  18: (1024, 512)
  35: (16384, 2048)
  36: (8192, 2048)
Graphics commands:
  draw-triangles: dst: 8 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 8 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 12, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 18 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 18 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 4446, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 8 <- src: [18, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 8 <- src: [35, (nil), (nil), (nil)], num of dst regions: 12, num of indices: 5892, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 10 (screen) <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 10 (screen) <- src: [8, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
----
Update count per frame: 1
Internal image sizes:
  8: (2048, 2048)
  10: (1920, 1027)
  16: (4096, 2048)
  18: (1024, 512)
  35: (16384, 2048)
  36: (8192, 2048)
Graphics commands:
  draw-triangles: dst: 8 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 8 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 12, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 18 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 18 <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 4446, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 8 <- src: [18, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 8 <- src: [35, (nil), (nil), (nil)], num of dst regions: 12, num of indices: 5892, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 10 (screen) <- src: [35, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 0, dst-alpha: 0, op-color: 0, op-alpha: 0}, even-odd: false
  draw-triangles: dst: 10 (screen) <- src: [8, (nil), (nil), (nil)], num of dst regions: 1, num of indices: 6, blend: {src-color: 1, src-alpha:  1, dst-color: 5, dst-alpha: 5, op-color: 0, op-alpha: 0}, even-odd: false

```

it looks like so on my machine

> What was the last version that worked correctly?

It is actually hard to tell since I was always just pulling changes from main branch and building my game with those up-to-date sources, and my game is in the maintenance state for over 3 months now. I'm positive that 70183185460a5fc1297bb81c897e213c73d8373e was working just fine, and I know that's a very far away commit, but maybe if you get any clue what could be the cause I could build the game on a commit prior to that change and I can sent it to the audience that suffer from this bug

**Comment by hajimehoshi** [comment]
Thanks. This doesn't seem insane so I'm not sure what's going on...

Probably reducing the internal textures changed the situation. Hmm.

**Comment by hajimehoshi** [comment]
>  but maybe if you get any clue what could be the cause I could build the game on a commit prior to that change and I can sent it to the audience that suffer from this bug

I'm afraid I don't have a clue so far. I'll try to reproduce the issue with my low-end laptop.

**Comment by hajimehoshi** [comment]
I couldn't reproduce the issue with my machine so far:

```
                                ..,   USER@DESKTOP-16QDNLN
                    ....,,:;+ccllll   --------------------
      ...,,+:;  cllllllllllllllllll   OS: Windows 10 Home x86_64
,cclllllllllll  lllllllllllllllllll   Host: Jumper EZbook
llllllllllllll  lllllllllllllllllll   Kernel: 10.0.19043
llllllllllllll  lllllllllllllllllll   Uptime: 24 mins
llllllllllllll  lllllllllllllllllll   Packages: 4 (scoop)
llllllllllllll  lllllllllllllllllll   Shell: bash 4.4.23
llllllllllllll  lllllllllllllllllll   Resolution: 1920x1080
                                      DE: Aero
llllllllllllll  lllllllllllllllllll   WM: Explorer
llllllllllllll  lllllllllllllllllll   WM Theme: Custom
llllllllllllll  lllllllllllllllllll   CPU: Intel Celeron J3455 (4) @ 1.500GHz
llllllllllllll  lllllllllllllllllll   GPU: Caption
llllllllllllll  lllllllllllllllllll   GPU: Intel(R) HD Graphics 500
`'ccllllllllll  lllllllllllllllllll   GPU
       `' \*::  :ccllllllllllllllll   Memory: 4366MiB / 5992MiB
                       ````''*::cll
                                 ``
```

@erexo Would it be possible to run your program on my machine? I guess the program is in a private repository. Thanks,

**Comment by hajimehoshi** [comment]
> it looks like so on my machine

By the way, did you test a similar scene to what the reporter reported? You said the program uses too much power of GPU (burning the player's GPU), but the commands doesn't seem so.

**Comment by erexo** [comment]
> I'm afraid I don't have a clue so far. I'll try to reproduce the issue with my low-end laptop.

The thing is that it doesn't necessarily occur on the low-end machines I guess, user2 specs are pretty decent but still it happens.

> @erexo Would it be possible to run your program on my machine? I guess the program is in a private repository. Thanks,

Yes the game is on private repo but you have access there right? 😄 There is `data` dir missing so I can guide you on how to launch the app, if you wish we can do that.

> By the way, did you test a similar scene to what the reporter reported?

Players who experienced this claims that this is happening almost always and almost from the beginning, they absolutely had to switch to OpenGL because the game was unplayable from the start - they claim.

> You said the program uses too much power of GPU (burning the player's GPU), but the commands doesn't seem so.

I didn't claim that the program uses too much GPU power, I wrote that it looks like the case (the whole physical screen is going wild just because my app was launched, it's crazy that it's even possible). My actual game code didn't change almost at all since last, stable release, so there is very huge probability that the ebitengine directx stuff was somewhat changed so that a very few group of players experience those issues

**Comment by hajimehoshi** [comment]
> Yes the game is on private repo but you have access there right?

I thought so but go.mod indicated Ebitengine v2.4 so I was not 100% confident. I'll take a look.

> There is data dir missing so I can guide you on how to launch the app, if you wish we can do that.

Thanks, I'd like to know. Also, if there is a 'debug' mode to emulate a similar situation easily, this would be the best.

> And since only a small portion of my players are experiencing this, and they experience it so frequently, it would be very noticeable if this was the case for every player.

Hmm, interesting. There might be a common situation among the players (e.g. do they use the same settings for monitors?).

> I didn't claim that the program uses too much GPU power, I wrote that it looks like the case (the whole physical screen is going wild just because my app was launched, it's crazy that it's even possible).

Oh I see, so I was misunderstanding. I don't think an app does not 'burn' machines but I understand your worry.

**Comment by erexo** [comment]
> Thanks, I'd like to know. Also, if there is a 'debug' mode to emulate a similar situation easily, this would be the best.

If I was able to actually invoke this flickering situation on my machine it would be a thousand times easier 😄

> Hmm, interesting. There might be a common situation among the players (e.g. do they use the same settings for monitors?).

I'm not sure since I wasn't asking, right now I have no clue what might be the problem but I do know that previous game version (70183185460a5fc1297bb81c897e213c73d8373e) was working perfectly fine on those machines which suffer now. Those players were playing before and everything was all alright.

**Comment by hajimehoshi** [comment]
> I'm not sure since I wasn't asking, right now I have no clue what might be the problem but I do know that previous game version (https://github.com/hajimehoshi/ebiten/commit/70183185460a5fc1297bb81c897e213c73d8373e) was working perfectly fine on those machines which suffer now. Those players were playing before and everything was all alright.

As this is reproducible on their machines, we probably can ['git-bisect'](https://git-scm.com/docs/git-bisect) between 70183185460a5fc1297bb81c897e213c73d8373e and v2.6.0-alpha, and know the culprit. Would it be practical? As this would take the user's time and resources, I'm fine if it cannot.

**Comment by erexo** [comment]
> As this is reproducible on their machines, we probably can ['git-bisect'](https://git-scm.com/docs/git-bisect) between https://github.com/hajimehoshi/ebiten/commit/70183185460a5fc1297bb81c897e213c73d8373e and v2.6.0-alpha, and know the culprit. Would it be practical? As this would take the user's time and resources, I'm fine even if it cannot.

I will try to do everything in my power but I cant promise anything

**Comment by hajimehoshi** [comment]
Thanks! I appreciate your help!

**Comment by hajimehoshi** [comment]
We think #2613 fixed this!
