### ISSUE TITLE
Consider making keys/keys.go:keyNameToKeyCode public

### ISSUE THREAD

**Issue by c-robinson** [hajimehoshi/ebiten#2608]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

I would love if the private function `keys/keys.go:keyNameToKeyCode` were made public

### Why is this needed?

I have a use-case for pulling keyboard controls out of a configuration file, which means I need to assert that they are an ebiten.Key when I load them. This is easy enough for a but more challenging for escape or numpad7. You have a function keys/keys.go:keyNameToKeyCode that is a perfect solution to this need, but it is private, so if someone needs to use it they need to copy it, which means they also need to track if you update or change it. The utility functions in keys/keys.go are all useful and I wonder if you'd consider making them public.

**Comment by hajimehoshi** [comment]
You can use Key.UnmarshalText. https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2#Key.UnmarshalText
