### ISSUE TITLE
Coredump on OSX [not reproducible]

### ISSUE THREAD

**Issue by kalexmills** [hajimehoshi/ebiten#2609]
### Ebitengine Version

2.5.0

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.1 darwin/arm64

### What steps will reproduce the problem?

@hajimehoshi you should have an invite to a private repo named [kalexmills/2d-platformer](https://github.com/kalexmills/2d-platformer). There's a tag on that repo named [coredump-03-21-2023](https://github.com/kalexmills/2d-platformer/releases/tag/coredump-03-21-2023) which I was running when the problem occurred.

I cannot (at present) reproduce from that tag.

### What is the expected result?

No MacBook crashes

### What happens instead?

MacBook crashed.

### Anything else you feel useful to add?

I've included the coredump that would be sent to Apple, in case it's helpful.

This issue _might_ need to be closed; but I'm including it in case the below coredump ends up being useful in any way.

[coredump-03-21-2023.txt](https://github.com/hajimehoshi/ebiten/files/11034142/coredump-03-21-2023.txt)

**Comment by hajimehoshi** [comment]
I couldn't reproduce the issue by running `run.sh`. My machine is:

```
                    'c.          hajimehoshi@Hajimes-MacBook-Pro-2020.local 
                 ,xNMM.          ------------------------------------------ 
               .OMMMMo           OS: macOS 13.2.1 22D68 x86_64 
               OMMM0,            Host: MacBookPro16,2 
     .;loddo:' loolloddol;.      Kernel: 22.3.0 
   cKMMMMMMMMMMNWMMMMMMMMMM0:    Uptime: 6 days, 23 hours, 45 mins 
 .KMMMMMMMMMMMMMMMMMMMMMMMWd.    Packages: 194 (brew) 
 XMMMMMMMMMMMMMMMMMMMMMMMX.      Shell: bash 3.2.57 
;MMMMMMMMMMMMMMMMMMMMMMMM:       Resolution: 1680x1050@2x 
:MMMMMMMMMMMMMMMMMMMMMMMM:       DE: Aqua 
.MMMMMMMMMMMMMMMMMMMMMMMMX.      WM: Quartz Compositor 
 kMMMMMMMMMMMMMMMMMMMMMMMMWd.    WM Theme: Blue (Light) 
 .XMMMMMMMMMMMMMMMMMMMMMMMMMMk   Terminal: tmux 
  .XMMMMMMMMMMMMMMMMMMMMMMMMK.   CPU: Intel i7-1068NG7 (8) @ 2.30GHz 
    kMMMMMMMMMMMMMMMMMMMMMMd     GPU: Intel Iris Plus Graphics 
     ;KMMMMMMMWXXWMMMMMMMk.      Memory: 21312MiB / 32768MiB 
       .cooc,.    .,coo:.
                                                         
                                                         
```

**Comment by hajimehoshi** [comment]
> MacBook crashed.

If this means a crash in the OS, this is an issue in the OS. IIUC, there can be some kernel issues in macOS unfortunately.

**Comment by kalexmills** [comment]
Let's close it out then! Thanks for your help.
