### ISSUE TITLE
internal/graphicsdriver/directx: use DirectX 11 instead of DirectX 12 for stability

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2613]
### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

DirectX 12 is 8 years old but seems not matured yet.

* There is an unsolvable bug of [DXGI_ERROR_DEVICE_REMOVED](https://www.nvidia.com/en-us/geforce/forums/geforce-experience/14/150018/dxgi-error-device-removed/)
* [ANGLE adopts DirectX 11](https://chromium.googlesource.com/angle/angle)
* [Final Fantasy 14 adopts DirectX 11](https://www.reddit.com/r/ffxiv/comments/o8zwek/are_there_any_plans_to_add_dx12_dlss_or_ray/)
* [A discussion about stability](https://www.reddit.com/r/gamedev/comments/d3ozq8/why_do_so_many_games_have_problems_with_directx/)

DirectX 11 seems much more matured and has less troubles. Can we implement a DirectX 11 drivers for desktops?

For Xbox, DirectX 12 should be fine.

### Why is this needed?

This might resolve these issues:

* #2148
* #2198
* #2484
  * [DirectX 11 can support some old feature levels](https://learn.microsoft.com/en-us/windows/win32/direct3d11/overviews-direct3d-11-devices-downlevel-intro)
  * For https://github.com/hajimehoshi/ebiten/issues/1431, the feature level 10+ is the must.
* #2485 
* #2604

/CC @erexo 

I have not decided I'll do this in v2.6, as the implementation cost is huge.

**Comment by hajimehoshi** [comment]
First I'll estimate the implementation cost.

**Comment by hajimehoshi** [comment]
https://learn.microsoft.com/en-us/windows/win32/direct3d12/important-changes-from-directx-11-to-directx-12

**Comment by erexo** [comment]
Thanks for CC, I appreciate it.
My main concern is to allow to play as many players as possible. My players have a impressively huge variety of machines from very good and new to surprisingly old and outdated ones, and I want to provide as many of them (ideally all of them) an environment to play.
That being said, I don't really know how DirectX features are implemented on various (new, old and very old) machines, but if all (or >98%) of machines that implement dx12 also have dx11 and it will work at least decent I'm all good for that. I do not need spectacular experience for a few, I would want to provide at least decent experience for everyone

**Comment by hajimehoshi** [comment]
@erexo Thank you very much! I think I'll ask you to test the DirectX 11 implementation after I finished this. I hope this will be finished next week.

**Comment by hajimehoshi** [comment]
I've implemented the DirectX 11 driver, and this should be used by default.

@erexo Could you try 78d76945adb0e463e1fec9a75c4a11525606e8ac ? Thanks!

**Comment by erexo** [comment]
So I pushed 1017161c369090a0b17e3b8fae9c72a685257f45 on production and I've noticed that my FPSes on dx increased dramatically from ~300 to ~800. This is actually the first time since I'm working on Ebitengine where DirectX has better FPS than OpenGL, previously it was not even close.
I have asked the "user2" from my #2604 issue is his machine still has similar monitor issues while using dx and he claims that now everything works fine so I guess that was the fix.
I'll keep it on prod and if anyone report anything new I'll keep you updated.
Thank you for your work 💝

**Comment by hajimehoshi** [comment]
Woo hoo! Thank you for confirming!

I hope every issue due to DirectX 12 will be fixed.

**Comment by erexo** [comment]
Sadly I have to report that we have our first casualties 😅
One of my players reported that after updating to 1017161c369090a0b17e3b8fae9c72a685257f45 the game is not launching anymore, like at all. Before that (commit around 2.5.0 release) everything was working fine for this user, ogl is working and was working fine.

The error:
![image](https://user-images.githubusercontent.com/6548968/228558852-2038b50a-f5ab-446a-ac65-78db60aa8d31.png)
Statement is that `CreateDXGFactory2` procedure is not found in `dxgi.dll`.

his specs:
![image](https://user-images.githubusercontent.com/6548968/228559447-d372df8b-43ca-4166-8d3a-7c033924f1fe.png)

It's kinda weird because his `dxdiag` is stating that he has DX11 right? And afaik we are kinda downgrading Ebitengine to the 11 so it's kinda counter intuitive

**Comment by hajimehoshi** [comment]
@erexo `CreateDXGFactory2` was added in Windows 8.1, so if the Windows version is Windows 8 or older, this would not work. I'll look for a substitution. Thank you for reporting!

**Comment by erexo** [comment]
> @erexo `CreateDXGFactory2` was added in Windows 8.1, so if the Windows version is Windows 8 or older, this would not work. I'll look for a substitution. Thank you for reporting!

Thank you for finding a cause of this issue, I was terrified that this may be our next "god knows what is happening" bug, at least we know that current Ebitengine is not suitable for anything before Win 8.1 😄
As I stated above I'd like to offer my game to as broad amount of machines as possible and my players are capable of operating really old and weird setups so I'd really appreciate if despite being old, Win7 was still supported (automatically switching to ogl when on a system that is not supported is also fine for me)

**Comment by hajimehoshi** [comment]
I think it is possible to support Windows 7 as CreateDXGFactory2 should not be necessary for DirectX 11. Please stay tuned!

**Comment by hajimehoshi** [comment]
@erexo Could you try c9f1696a5b9f5c64f71fc57238d14c4be246d91f? Now this doesn't use `CreateDXGFactory2`.

**Comment by erexo** [comment]
I updated to 7fa65ae983b2b9ecd95d1a49f0a5793e240f4347 and the game still do not launch for this particular user.
This is the new error:
![image](https://user-images.githubusercontent.com/6548968/228594614-14dca288-54cc-4f84-bea1-fd02a9405bbe.png)

Generally the first line is saying "Given module was not found".

**Comment by erexo** [comment]
> Hmm insteresting. In the user's machine, do other DirectX 11 applications work?
I'm not sure how to test it out. It's true that his machine is rather old and deprecated, but previous version of my game was working fine and now it's not

**Comment by hajimehoshi** [comment]
https://walbourn.github.io/hlsl-fxc-and-d3dcompile/

OK I'll enumerate possible DLL names for such a machine.

**Comment by hajimehoshi** [comment]
Updated: 3e477d0bbb6bb5c4f61ec725bc0aee9b7086a038

**Comment by hajimehoshi** [comment]
> I'm not sure how to test it out. It's true that his machine is rather old and deprecated, but previous version of my game was working fine and now it's not

My guess is that now the initialization of DirectX 11 succeeded and the game tried to use it, instead of OpenGL.

**Comment by erexo** [comment]
> My guess is that now the initialization of DirectX 11 succeeded and the game tried to use it, instead of OpenGL.

oh right! He was probably secretly falling back to OpenGL.


![image](https://user-images.githubusercontent.com/6548968/228609399-3fdab404-093d-4564-b018-b1ee83c75766.png)
now he as this issue

**Comment by hajimehoshi** [comment]
Thanks. My current guess is that I had to use https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgioutput-findclosestmatchingmode to find a matched description.

**Comment by hajimehoshi** [comment]
I'm gonna sleep so I'll tackle this tomorrow. Thank you very much for a lot of feedbacks!

**Comment by hajimehoshi** [comment]
If possible, I would like to see the debug messages. As this is tricky, it is ok if you cannot do this on his machine:

1. Set an environment variable `EBITENGINE_DIRECTX` with `debug`.
2. Launch [`Dbgview64.exe` or `Dbgview.exe`](https://learn.microsoft.com/en-us/sysinternals/downloads/debugview)
3. Run the application
4. See the log

**Comment by erexo** [comment]
Another player approached me with the inability to launch the game after the initial update but he claims that the latest version works fine for him. And he also has Win7 so it seems that the initial Win7 problem is resolved and now we are dealing with this particular machine's problem

**Comment by erexo** [comment]
I was being able to reach to that player again, and when I prepared the same client with the same Ebitengine version but with `os.Setenv("EBITENGINE_DIRECTX", "debug")` at the beginning, that player claimed that the client is working fine now...
I asked him 5 times if he's using DirectX engine and I even sent him the same executable but without that line and again he claimed that the game is not working again 😅
It seems like the `_D3D11_CREATE_DEVICE_DEBUG` is actually fixing this issue for some reason

**Comment by hajimehoshi** [comment]
Hmm ok, I think it's possible that the debug flag changed some situations. Could you ask him to remove the environment variable so that we can try to fix the root cause? Thanks,

**Comment by hajimehoshi** [comment]
Ah, DXGI_SWAP_EFFECT_FLIP_DISCARD is available from Windows 10, and I think that's why...

https://learn.microsoft.com/en-us/windows/win32/api/dxgi/ne-dxgi-dxgi_swap_effect

**Comment by hajimehoshi** [comment]
@erexo Could you try d22158b156b03c4a2415b1604d079fdf0a590de9 ? Thanks,

**Comment by erexo** [comment]
That user has the same problem on 61ced5127b4ce61d0514eabf6afd9d4a3c7672cd, but currently it happens only sometimes.
![image](https://user-images.githubusercontent.com/6548968/228821085-bc814fc0-6347-4126-9bdb-14c39a5cca62.png)

He tried to launch the game and surprisingly it worked, but then when he launched it a couple more times the game did not want to launch again, with the same error as previously. I'm not entirely sure if this was the case previously

**Comment by erexo** [comment]
So this particular player still has the same problem on 09250ff4f3ee62e734970370d9d4670b4caacca7, but two other players (one on Win8.1 and one on Win7) reported that the game is not working for them as well. When I sent them 09250ff4f3ee62e734970370d9d4670b4caacca7 build both of them claimed that the game is working fine now. I'm not sure which game version they were using but with 95% confidence I can say that they were trying to run the game after we fix the initial Win7 issue. So whatever it was, one of latest commits actually fixed the situation for other players, but not for this particular one

**Comment by erexo** [comment]
> Hmm? I'm confused. Now [09250ff](https://github.com/hajimehoshi/ebiten/commit/09250ff4f3ee62e734970370d9d4670b4caacca7) didn't work for some users, but old commits worked?

Kinda opposite.
1. The game was working fine for them before we did all this dx11 thing (probably due to fallback to ogl)
2. Today morning they reported that the game is no longer working (after I added some of the recent commits to production, probably the Win7 fix I'm not really sure)
3. I sent them 09250ff4f3ee62e734970370d9d4670b4caacca7 and both of them claimed that now the game is working fine again

So although those recent commits did not fix the game for our "patient 0", it seems like it was a fix for other problems

**Comment by hajimehoshi** [comment]
Thanks, I'm relieaved the situation is getting better :D 

I'm continuing to investigate the issue at https://github.com/hajimehoshi/ebiten/issues/2613#issuecomment-1490133270, which seems quite tough as I couldn't reproduce this on my Windows 7 :/

**Comment by hajimehoshi** [comment]
@erexo Could you try a4bfe8a869406b4e1065f56db685aa1d0b030b76 ? I couldn't find other candidates to fix the issue...

**Comment by erexo** [comment]
do you think that it would be somehow possible to try to relaunch the game using OpenGL if DX fails?
Maybe in the same run, or maybe to somehow save that previous launch failed on initialization (or shortly after) and decide that OpenGL would be better?

**Comment by hajimehoshi** [comment]
This might be hard since the initialization already succeeded in this case. I'll try to create the swap chain earlier, but I am not sure I can do that.

**Comment by hajimehoshi** [comment]
In the current implementation,

1. The graphics library must be determined when initializing the window by GLFW
2. Creating a swap chain requires the window handle

So, the graphics library has to be determined first and then the swap chain is created. I cannot reverse the order unfortunately...

**Comment by hajimehoshi** [comment]
@erexo Is his machine 32bit or 64bit by the way?

**Comment by hajimehoshi** [comment]
@erexo I've created an experimetal branch with an experimental fix: 4d98875db30400f30de81015fd1e24ea96ab6823. I don't think this fixes the issue, but if you could try, I'd appreciate... Thanks

**Comment by hajimehoshi** [comment]
I think this is a pretty bad know-how, but there is a report that changing the language/region settings solved a similar issue... https://answers.ea.com/t5/Battlefield-4/DirectX-Error/td-p/1721345

I don't think this is a fix for the root cause. I'd like to continue to investigate, or, look for a good solution to fallback to OpenGL.

**Comment by erexo** [comment]
> Thanks. One more question: What is his display's refresh rate (e.g. 60[Hz])? Does he have multiple monitors?

60hz

**Comment by hajimehoshi** [comment]
I googled this and failed to find a good solution. I guess this is an issue in old graphics drivers, and if so, there is nothing we can do.

I decided to use OpenGL as a primary graphics library for old Windows. This should be the same behavior as v2.5 since v2.5 supports only DirectX 12, which works only on Windows 10 and newer.

You can still use DirectX (11) by specifying the graphics library explicitly at `RunGameWithOptions` or `EBITENGINE_GRAPHICS_LIBRARY`.

**Comment by erexo** [comment]
That's probably a very good move, players didn't even notice that they are on OpenGL until they were switched to dx and the game was not working 😄
Thank you for your efforts and cooperation 💝

**Comment by hajimehoshi** [comment]
Thank you!

Let me close this as this was fixed. Please file a new issue if you find a new problem.

I appreciate your a lot of testings!
