### ISSUE TITLE
Cross compile fails

### ISSUE THREAD

**Issue by ea7kir** [hajimehoshi/ebiten#2614]
### Ebitengine Version

v2@v2.5.0

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.20.2 darwin/amd64

### What steps will reproduce the problem?

Using the lines demo.  It compiles and runs on macOS, but refuses to cross compile for a 64bit raspberry pi 4.

GOOS=linux GOARCH=arm64 go build -o bin/ebiten-lines main.go

### What is the expected result?

A compile binary for arm64.

### What happens instead?

# github.com/hajimehoshi/ebiten/v2/internal/glfw
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/glfw_notwindows.go:26:24: undefined: glfw.Window
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/glfw_notwindows.go:61:10: undefined: glfw.Cursor
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/glfw_notwindows.go:70:10: undefined: glfw.Monitor
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/glfw_notwindows.go:98:10: undefined: glfw.Window
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:24:33: undefined: glfw.CharModsCallback
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:25:33: undefined: glfw.CloseCallback
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:26:33: undefined: glfw.DropCallback
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:27:33: undefined: glfw.FramebufferSizeCallback
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:28:33: undefined: glfw.MonitorCallback
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:30:33: undefined: glfw.SizeCallback
../../../go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0/internal/glfw/type_notwindows.go:28:33: too many errors

### Anything else you feel useful to add?

I can cross compile a simple hello world (non GUI) ok - and it runs on the RPi.

**Comment by hajimehoshi** [comment]
You cannot cross-compile Ebitengine for Linux. I would use Docker.

**Comment by sedyh** [comment]
Hello, please reopen this one. It's not only the mac -> linux problem.
Now we can't cross-compile from linux to m1 too.

```
GOOS=darwin GOARCH=arm64 go build -o roboden-mac-arm cmd/game/main.go

# github.com/hajimehoshi/ebiten/v2/internal/glfw
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/glfw_notwindows.go:26:24: undefined: glfw.Window
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/glfw_notwindows.go:61:10: undefined: glfw.Cursor
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/glfw_notwindows.go:70:10: undefined: glfw.Monitor
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/glfw_notwindows.go:98:10: undefined: glfw.Window
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:24:33: undefined: glfw.CharModsCallback
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:25:33: undefined: glfw.CloseCallback
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:26:33: undefined: glfw.DropCallback
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:27:33: undefined: glfw.FramebufferSizeCallback
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:28:33: undefined: glfw.MonitorCallback
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:30:33: undefined: glfw.SizeCallback
/home/sedyh/.local/share/go/path/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.2/internal/glfw/type_notwindows.go:28:33: too many errors

```

**Comment by hajimehoshi** [comment]
It is also impossible

**Comment by sedyh** [comment]
That is very strange. As far as I remember the build used to work before 2.5.
isn't that cross compilation was the whole point of getting rid of cgo and adding purego?

**Comment by hajimehoshi** [comment]
Ebitengine is NOT purego for macOS yet. See the issue #1162.
