### ISSUE TITLE
text.Draw seems to ignore alpha value

### ISSUE THREAD

**Issue by clkbug** [hajimehoshi/ebiten#2624]
### Ebitengine Version

2.5.0

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.20.2

### What steps will reproduce the problem?

The problem occurs when drawing white text with alpha value.

```go
	col := color.RGBA{255, 255, 255, uint8(a)}
	text.Draw(screen, t, mplusNormalFont, x, y, col)
```

The full code is as follows:
```go
package main

import (
	"fmt"
	"image/color"
	"log"

	"golang.org/x/image/font"
	"golang.org/x/image/font/opentype"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/examples/resources/fonts"
	"github.com/hajimehoshi/ebiten/v2/text"
)

const (
	screenWidth  = 640
	screenHeight = 480
)

var (
	mplusNormalFont font.Face
)

func init() {
	tt, err := opentype.Parse(fonts.MPlus1pRegular_ttf)
	if err != nil {
		log.Fatal(err)
	}

	const dpi = 72
	mplusNormalFont, err = opentype.NewFace(tt, &opentype.FaceOptions{
		Size:    24,
		DPI:     dpi,
		Hinting: font.HintingVertical,
	})
	if err != nil {
		log.Fatal(err)
	}
}

type Game struct {
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	for i := 0; i <= 16; i++ {
		a := 16 * i
		if i == 16 {
			a = 255
		}
		t := fmt.Sprintf("alpha = %3d", a)
		x := 30
		y := 30 + i*24
		col := color.RGBA{255, 255, 255, uint8(a)}
		text.Draw(screen, t, mplusNormalFont, x, y, col)
	}

}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return screenWidth, screenHeight
}

func main() {
	ebiten.SetWindowSize(screenWidth, screenHeight)
	ebiten.SetWindowTitle("Debug")
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

### What is the expected result?

The expected result is as follows (this is built with ebitengine v2.4.0);

![image](https://user-images.githubusercontent.com/7815537/229331508-0f643cd2-a7ba-46a3-86ca-5143d842a6dd.png)

### What happens instead?

Regardless of the alpha values, full white texts are displayed:

![image](https://user-images.githubusercontent.com/7815537/229331552-4f5cdcb1-3f1b-4f10-9778-de72fdf45f18.png)

**Comment by hajimehoshi** [comment]
> col := color.RGBA{255, 255, 255, uint8(a)}

[`color.RGBA` is a premultiplied-alpha value](https://pkg.go.dev/image/color#RGBA). Reduce RGB values or use `color.NRGBA` instead.
