### ISSUE TITLE
Browser mouse capture not capturing on first load

### ISSUE THREAD

**Issue by harbdog** [hajimehoshi/ebiten#2637]
### Ebitengine Version

2.5

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.19.6

### What steps will reproduce the problem?

This is noticed only from browser wasm version. Visit the mouse capture example (#2636): https://harbdog.github.io/ebiten/

Note that it captures the mouse on first load, yet the OS mouse cursor is still showing which is not expected. Toggling the mouse capture off and back on again then hides the OS mouse cursor as expected.

### What is the expected result?

The OS cursor should be hidden when captured on first load.

### What happens instead?

The OS cursor still shows even while captured only on first load.

**Comment by hajimehoshi** [comment]
Did the developer console show anything?

**Comment by harbdog** [comment]
@hajimehoshi here's what's in the console:

```
wasm_exec.js:349 pointerlockerror event is fired. 'sandbox="allow-pointer-lock"' might be required at an iframe. This function on browsers must be called as a result of a gestural interaction or orientation change.
syscall/js.valueCall @ wasm_exec.js:349
$syscall_js.valueCall @ 0271b102:0x17e37c
$syscall_js.Value.Call @ 0271b102:0x17b857
$wasm_pc_f_loop @ 0271b102:0xeb9f5
$wasm_export_resume @ 0271b102:0xeb9d6
_resume @ wasm_exec.js:538
(anonymous) @ wasm_exec.js:549
harbdog.github.io/:1 Uncaught (in promise) DOMException: A user gesture is required to request Pointer Lock.
```

**Comment by harbdog** [comment]
I understand if it's a limitation, probably just needs to be documented and worked around by instructing the user to first press something to initiate capture.

I'm also wondering if it's just a timing issue, maybe just delaying the automatic capture until after the first update/draw is performed?

**Comment by harbdog** [comment]
After playing around with various options it seems most likely a browser security limitation that expects direct user interaction to engage the mouse capture, so a key/button must be pressed.

I'll update the example to not attempt to capture on startup.
