### ISSUE TITLE
ebiten not working on wsl

### ISSUE THREAD

**Issue by ksXV** [hajimehoshi/ebiten#2643]
### Ebitengine Version

latest

### Operating System

- [X] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.18.3 linux/amd64

### What steps will reproduce the problem?

I installed the dependencies as in the docs and installed the ebiten engine and then tried to ran an example. 
e.g : go run github.com/hajimehoshi/ebiten/v2/examples/rotate@latest

### What is the expected result?

![image](https://user-images.githubusercontent.com/90782294/232089874-1d85de1a-d97b-4ace-bdaa-d8d3632882ee.png)

### What happens instead?

![image](https://user-images.githubusercontent.com/90782294/232090019-90feeb46-bd9b-47c1-bb8a-6199f72b1378.png)

**Comment by hajimehoshi** [comment]
Add `GOOS=widows` before `go run`.

**Comment by ksXV** [comment]
Thank you very much this fixed it but what does that do exactly ?

**Comment by ksXV** [comment]
no like i got that but what does this do `GOOS=windows` that it made it work ?

**Comment by hajimehoshi** [comment]
This specifies an environment variable GOOS to windows so that your go command compiles the game as a Window binary instead of a Linux binary.
