### ISSUE TITLE
Kage: Fail to compile scoped one-line assignation of different types

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2655]
### Ebitengine Version

v2.6.0-alpha.2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.18.3

### What steps will reproduce the problem?

```go
a, b, c := 0., vec2(0), vec3(0) // declaration => supported
a, b, c = 0., vec2(0), vec3(0)  // assignation => supported
// assignation => not supported if 'scoped'
if a > 0 {
	a, b, c = 0., vec2(0), vec3(0)
}
// not compiling
{
	a, b, c = 0., vec2(0), vec3(0)
}
// not compiling either
for i := 0; i < 0; i++ {
	a, b, c = 0., vec2(0), vec3(0)
}
```

### What is the expected result?

Successful compilation (like line 2), whether the multi-var multi-type assignation is scoped or not

### What happens instead?

I get this shader compilation error:
```
rungame: opengl: fragment shader compile error: opengl: shader compile failed: 0(178) : warning C7011: implicit cast from "float" to "vec3"
0(179) : warning C7623: implicit narrowing of type from "vec3" to "float"
0(180) : warning C7623: implicit narrowing of type from "vec3" to "float"
0(181) : warning C7011: implicit cast from "float" to "vec3"
0(182) : warning C7011: implicit cast from "vec3" to "vec2"
0(183) : error C1035: assignment of incompatible types
```

### Anything else you feel useful to add?

Good luck!

**Comment by hajimehoshi** [comment]
Confirmed.
