### ISSUE TITLE
text: crash with an unhashable face

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2669]
### Ebitengine Version

556ec7053ae445859e2033b2f3bc4fc24759649b

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.4 darwin/amd64

### What steps will reproduce the problem?

Run this program:

```go
package main

import (
	"image"
	"image/color"
	"log"

	"golang.org/x/image/font"
	"golang.org/x/image/math/fixed"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/text"
)

type unhashableFace []byte

func (u unhashableFace) Close() error {
	return nil
}

func (u unhashableFace) Glyph(dot fixed.Point26_6, r rune) (dr image.Rectangle, mask image.Image, maskp image.Point, advance fixed.Int26_6, ok bool) {
	return image.Rectangle{}, nil, image.Point{}, 0, false
}

func (u unhashableFace) GlyphBounds(r rune) (bounds fixed.Rectangle26_6, advance fixed.Int26_6, ok bool) {
	return fixed.Rectangle26_6{}, 0, false
}

func (u unhashableFace) GlyphAdvance(r rune) (advance fixed.Int26_6, ok bool) {
	return 0, false
}

func (u unhashableFace) Kern(r0, r1 rune) fixed.Int26_6 {
	return 0
}

func (u unhashableFace) Metrics() font.Metrics {
	return font.Metrics{}
}

type Game struct {
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	text.Draw(screen, "foo", unhashableFace{}, 0, 0, color.White)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 640, 480
}

func main() {
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

### What is the expected result?

No crash

### What happens instead?

Crash

```
panic: runtime error: hash of unhashable type main.unhashableFace

goroutine 36 [running]:
github.com/hajimehoshi/ebiten/v2/text.getGlyphBounds({0x10033ed48, 0xc0003a6078}, 0x0?)
        /Users/hajimehoshi/ebiten/text/text.go:79 +0x3e
github.com/hajimehoshi/ebiten/v2/text.DrawWithOptions(0xc00011bb80?, {0x1002e397d, 0x3}, {0x10033ed48, 0xc0003a6078}, 0xc0003a6078?)
        /Users/hajimehoshi/ebiten/text/text.go:256 +0x251
github.com/hajimehoshi/ebiten/v2/text.Draw(0x1005affff?, {0x1002e397d, 0x3}, {0x10033ed48, 0xc0003a6078}, 0x0?, 0x0?, {0x10033c188?, 0xc00039c0b8?})
        /Users/hajimehoshi/ebiten/text/text.go:198 +0xdd
main.(*Game).Draw(0xc00011bc90?, 0x100235e68?)
        /Users/hajimehoshi/ebiten/examples/test/main.go:49 +0x6f
github.com/hajimehoshi/ebiten/v2.(*gameForUI).DrawOffscreen(0xc0002ae150)
        /Users/hajimehoshi/ebiten/gameforui.go:161 +0x2d
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).drawGame(0xc000216380, {0x100340628, 0xc0001ad200}, 0x0)
        /Users/hajimehoshi/ebiten/internal/ui/context.go:187 +0xe9
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrameImpl(0xc000216380, {0x100340628, 0xc0001ad200}, 0x1, 0x4084000000000000, 0x407e000000000000, 0x100008f98?, 0x10056f0a0, 0x80?)
        /Users/hajimehoshi/ebiten/internal/ui/context.go:155 +0x4c5
github.com/hajimehoshi/ebiten/v2/internal/ui.(*context).updateFrame(0xc0001a8df0?, {0x100340628, 0xc0001ad200}, 0x0?, 0x1?, 0x0?, 0x1?)
        /Users/hajimehoshi/ebiten/internal/ui/context.go:73 +0x85
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).updateGame(0x10056f0a0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:1086 +0x205
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).loopGame(0x10056f0a0)
        /Users/hajimehoshi/ebiten/internal/ui/ui_glfw.go:1046 +0x99
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func2()
        /Users/hajimehoshi/ebiten/internal/ui/run_glfw_notsinglethread.go:57 +0x46
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /Users/hajimehoshi/go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5
exit status 2
```

**Comment by hajimehoshi** [comment]
Unfortunately this might be unfixable.

**Comment by CNLYB** [comment]
i copy the code and
change
type unhashableFace []byte
to
type unhashableFace [100]byte.it ran.

**Comment by hajimehoshi** [comment]
Yes.

**Comment by lostByl** [comment]
Add an interface for caching.
type FaceCache interface {
	// it return a string and will as key for glyphImageCache and glyphBoundsCache  .for example:typeName
	getFaceCacheKey() string
}
Combine font.Face and FontCache  into a new text.Face.
type Face interface {
	font.Face
	FaceCache
}
use the text. Face instead of font.Face as a function parameter.
change
glyphImageCache = map[font.Face]map[glyphImageCacheKey]*glyphImageCacheEntry{}
glyphBoundsCache = map[font.Face]map[rune]fixed.Rectangle26_6{}
to
glyphImageCache = map[string]map[glyphImageCacheKey]*glyphImageCacheEntry{}
glyphBoundsCache = map[string]map[rune]fixed.Rectangle26_6{}

faceCachekey = Face.getFontCacheKey().use faceCachekey as KeyValue.
glyphImageCache = map[faceCachekey ]map[glyphImageCacheKey]*glyphImageCacheEntry{}
glyphBoundsCache = map[faceCachekey ]map[rune]fixed.Rectangle26_6{}

**Comment by hajimehoshi** [comment]
Who implements `getFontCacheKey`? If users have to do it, this would break compatibility.

**Comment by hajimehoshi** [comment]
There can be multiple different values for the same type, so `reflect.TypeOf(face).String()` would not work unfortunatley.

**Comment by lostByl** [comment]
what about this:
glyphFaceCacheIndex = map[int]face or glyphCacheIndex = []face
glyphImageCache = map[int]map[glyphImageCacheKey]*glyphImageCacheEntry{}
glyphBoundsCache = map[int]map[rune]fixed.Rectangle26_6{}
It's like three associated data tables.
 Use the reflect.DeepEqual() function to get(set) the index from glyphFaceCacheIndex . Update data in glyphImageCache and glyphBoundsCache  by index.

**Comment by hajimehoshi** [comment]
Please use ``` to format your code

**Comment by hajimehoshi** [comment]
I don't think this works as == for an unhashable value and it is impossible to get the index from a face

**Comment by lostByl** [comment]
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"reflect"
)

type unhashable []byte

func (uh unhashable) afun() {}

type Face interface {
	afun()
}

var gFaceCacheIndex = map[int]Face{}

func getFaceCache(face Face) (int, bool) {
	var getCache bool = false
	var getCacheIndex int
	for index, v := range gFaceCacheIndex {
		if reflect.DeepEqual(face, v) {
			getCache = true
			getCacheIndex = index
		}
	}
	return getCacheIndex, getCache
}
func addFaceCache(face Face) int {
	index := len(gFaceCacheIndex) + 1
	gFaceCacheIndex[index] = face
	return index
}
func main() {
	var first, second, third unhashable
	third = []byte("text")

	index, ok := getFaceCache(first)
	fmt.Println("index:", index)
	if !ok {
		index = addFaceCache(first)
		fmt.Println("add new face and index:", index)
	}

	index, ok = getFaceCache(second)
	fmt.Println("index:", index)
	if !ok {
		index = addFaceCache(second)
		fmt.Println("add second and index:", index)
	}

	index, ok = getFaceCache(third)
	fmt.Println("index:", index)
	if !ok {
		index = addFaceCache(third)
		fmt.Println("add third and index:", index)
	}

	fmt.Println(first, second, third)
}

**Comment by hajimehoshi** [comment]
> Use the reflect.DeepEqual() function to get(set) the index from glyphFaceCacheIndex

Actually I have tried DeepEqual but found this was problematic in terms of performance.

**Comment by lostByl** [comment]
```
// You can edit this code!
// Click here and start typing.
package main

import (
	"fmt"
	"reflect"
)

type unhashable []byte

func (uh unhashable) afun() {}

type Face interface {
	afun()
}

var gFaceCacheIndex = map[int]Face{}

func getFaceCache(face Face) (int, bool) {
	var getCache bool = false
	var getCacheIndex int
	for index, v := range gFaceCacheIndex {
		if reflect.DeepEqual(face, v) {
			getCache = true
			getCacheIndex = index
		}
	}
	return getCacheIndex, getCache
}
func addFaceCache(face Face) int {
	index := len(gFaceCacheIndex) + 1
	gFaceCacheIndex[index] = face
	return index
}
func main() {
	var first, second, third unhashable
	third = []byte("text")

	index, ok := getFaceCache(first)
	fmt.Println("index:", index)
	if !ok {
		index = addFaceCache(first)
		fmt.Println("add new face and index:", index)
	}

	index, ok = getFaceCache(second)
	fmt.Println("index:", index)
	if !ok {
		index = addFaceCache(second)
		fmt.Println("add second and index:", index)
	}

	index, ok = getFaceCache(third)
	fmt.Println("index:", index)
	if !ok {
		index = addFaceCache(third)
		fmt.Println("add third and index:", index)
	}

	fmt.Println(first, second, third)
}

```

**Comment by hajimehoshi** [comment]
See also https://github.com/hajimehoshi/ebiten/issues/554

**Comment by hajimehoshi** [comment]
I don't think this is a solvable issue. Let's move on a brand new API (#2454).

**Comment by hajimehoshi** [comment]
text/v2 (#2454) aims to resolve this issue.
