### ISSUE TITLE
Fullscreen support on desktops

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#267]

**Comment by egonelbre** [comment]
I would also add option to make window resizable.

**Comment by hajimehoshi** [comment]
I've created a separated issue https://github.com/hajimehoshi/ebiten/issues/320

**Comment by otraore** [comment]
[This is the line where you disabled resize](https://github.com/hajimehoshi/ebiten/blob/master/internal/ui/ui_glfw.go#L58 ), it's as simple as that to enable it. I would send a PR but I'm not sure if you want to make it optional or not.

**Comment by hajimehoshi** [comment]
As for resizing, I replied at #320.

**Comment by hajimehoshi** [comment]
I'm considering to use 'windowed fullscreen' http://www.glfw.org/docs/latest/window_guide.html#window_windowed_full_screen

**Comment by hajimehoshi** [comment]
Fundamental parts have been implemented. Done. Let's create new issues for other tasks.
