### ISSUE TITLE
Potentially beneficial for ebiten mobile implementation

### ISSUE THREAD

**Issue by lugorian** [hajimehoshi/ebiten#268]
Do you aware of this proposals:

https://github.com/golang/go/issues/17102
https://github.com/golang/go/issues/16876

Android one has first few commits in gomobile repository..

What do you think?

**Comment by hajimehoshi** [comment]
I wasn't aware of this. Thank you!

Implementation in Ebiten would be simpler so that's a good news at least to me, but nothing changes for Ebiten users.

**Comment by hajimehoshi** [comment]
Huh? For example `gomobile bind golang.org/x/mobile/example/reverse/reverse` doesn't work. `Java/android/databinding/DataBindingUtil` is not found.

**Comment by hajimehoshi** [comment]
Merged to #269
