### ISSUE TITLE
mobile/ebitenmobileview: Android: pressing unknown keys is ignored, even if Android assigns a text to them

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2684]
### Ebitengine Version

v2.5.4

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [X] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.20.5 darwin/arm64

### What steps will reproduce the problem?

Assuming you can't buy a keyboard with an unsupported key, do this:

1. Edit `genkeys.go` to start the loop of `ASCII: 0 - 9` at `'1'`.
2. Patch AAAAXY, or any other game, with the same change as https://github.com/hajimehoshi/ebiten/issues/2682.
3. Compile, deploy, connect external keyboard.
4. Press the `0` key.

### What is the expected result?

Expected result is that although `ebiten.IsKeyPressed` will not be able to return this unknown key, `ebiten.AppendInputChars` should still return it.

### What happens instead?

`ebiten.AppendInputChars` does not return the key.

### Anything else you feel useful to add?

This is rather theoretical in most cases, but practical implication exists when using a keyboard with extra keys not known to the engine (e.g. some "weird" international keyboards). Whether a key is supported by Ebitengine or not should not impact text entry, as the mapping from key to character is already being done by the OS.

**Comment by hajimehoshi** [comment]
I'll cherry-pick this to v2.5
