### ISSUE TITLE
ebiten.CursorModeCaptured not supported in browsers

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2686]
### Ebitengine Version

v2.6.0

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.18.3

### What steps will reproduce the problem?

Try setting the mouse mode `ebiten.CursorModeCaptured` in a wasm ebitengine application

### What is the expected result?

The cursor is hidden and doesn't leave the game canvas (in fullscreen or not)

### What happens instead?

Cursor is free, and gets out like it was not captured at all

**Comment by hajimehoshi** [comment]
Is there a message in the devtools?

**Comment by Zyko0** [comment]
> Is there a message in the devtools?

```
pointerlockerror event is fired. 'sandbox="allow-pointer-lock"' might be required at an iframe. This function on browsers must be called as a result of a gestural interaction or orientation change.
```

Maybe it's specific to the parent iframe actually..

**Comment by hajimehoshi** [comment]
Is this still an issue? From the Discord discussion, you have already found a solution, right?

**Comment by Zyko0** [comment]
> Is this still an issue? From the Discord discussion, you have already found a solution, right?
Still an issue to me, I was mentioning ideas, but I didn't find any ways to fix it so far
It might not be related to ebitengine, but I don't what could be causing this

I'm experiencing it here on my last game, for example: https://zyk0.itch.io/siden

**Comment by Zyko0** [comment]
After discussing with @hajimehoshi it appears it's on me, I was setting the cursor mode before there was a user interaction on with the window (canvas)
Thank you!

**Comment by hajimehoshi** [comment]
We confirmed that this was just a browser restriction (capturing cursors requires user interaction first)
