### ISSUE TITLE
ebiten.CursorPosition: X result seems broken in browser + CursorModeCaptured

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2690]
### Ebitengine Version

2.6.0

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.18.3

### What steps will reproduce the problem?

- Run `wasmserve github.com/hajimehoshi/ebiten/v2/examples/windowsize`
- Press 'C' twice to enable `CursorModeCaptured`
- Move the cursor anywhere, try to get back to your original position

### What is the expected result?

X, Y coordinates consistency, growing at the same scale

### What happens instead?

The X axis seems to scale infinitely no matter which direction we move the mouse to.
It's getting huge negative values in my case (on both Edge and Chrome)
![chrome_FFhhi62A7Z](https://github.com/hajimehoshi/ebiten/assets/13394516/d6e1d7e9-39d7-45ea-b9d4-5115834ea677)

**Comment by hajimehoshi** [comment]
I couldn't find such an extreme result, but found that the original position was weird (not scaled correctly, maybe?).

**Comment by hajimehoshi** [comment]
@Zyko0 Could you try  eb5c1ee8181d57f154494924f244081dedaee69a?

**Comment by Zyko0** [comment]
This seems to fix it, thanks!
