### ISSUE TITLE
ebiten: `SetCursorMode(CursorModeCaptured)` fails just after escaping captured (wasm)

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2693]
### Ebitengine Version

2.6.0-alpha-4

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.18.3

### What steps will reproduce the problem?

Run <https://gist.github.com/Zyko0/d17ce3bb51c4df4ecd2373f472ca65a3>
Try left-clicking to enable cursor capture

### What is the expected result?

CaptureMode being switched to `Visible` and `Captured` when pressing left-click / Escape

### What happens instead?

The cursor is simply never captured

### Anything else you feel useful to add?

In this example, `ebiten.SetCursorMode(ebiten.CursorModeCaptured)` is set at the very beginning, which fails because it is too early, so there's no chance of even seeing the cursor mode being captured for the lifetime of the application.

However, removing line 38 and starting with visible cursor (default), allows the captured mode after a left-click.
But then, pressing Escape prevents you from ever get into captured mode ever again.

The following error shows up in the console whenever it can't lock the cursor.
When it happens, there's no way of locking the cursor again in the currently running application.
![image](https://github.com/hajimehoshi/ebiten/assets/13394516/d4126933-3d73-4695-8911-a3a391c8e435)

Tested on Chrome & Edge (OS: Windows).

**Comment by hajimehoshi** [comment]
> In this example, ebiten.SetCursorMode(ebiten.CursorModeCaptured) is set at the very beginning, which fails because it is too early, so there's no chance of even seeing the cursor mode being captured for the lifetime of the application.

I don't think there is a solution for this issue unfortunately so far. You have to be careful not to call `ebiten.SetCursorMode(ebiten.CursorModeCaptured)` before user inputting happens.

I'll take a look more, but this is my current insight.

**Comment by Zyko0** [comment]
> I don't think there is a solution for this issue unfortunately so far. You have to be careful not to call ebiten.SetCursorMode(ebiten.CursorModeCaptured) before user inputting happens.
I'll take a look more, but this is my current insight.

Yeah, but as I said, removing l.38, just delayed the error
Allows to get cursor captured a single time, but if we leave it (Escape) we can't come back

**Comment by hajimehoshi** [comment]
```
func main() {
	os.Setenv("EBITEN_GRAPHICS_LIBRARY", "opengl")
	ebiten.SetFullscreen(true)
	ebiten.SetVsyncEnabled(true)
	ebiten.SetCursorMode(ebiten.CursorModeCaptured)

	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

Calling `SetCursorMode(ebiten.CursorModeCaptured)` before user interaction is the cause.

I might be able to improve the error message.

**Comment by hajimehoshi** [comment]
A further minimized example:

```go
package main

import (
        "log"

        "github.com/hajimehoshi/ebiten/v2"
)

type Game struct{}

func (g *Game) Update() error {
        if ebiten.IsMouseButtonPressed(ebiten.MouseButtonLeft) {
                ebiten.SetCursorMode(ebiten.CursorModeCaptured)
        }
        return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
        return 1920, 1080
}

func main() {
        if err := ebiten.RunGame(&Game{}); err != nil {
                log.Fatal(err)
        }
}
```

So the issue is that the cursor is not captured at the second click after once escape from capturing.
