### ISSUE TITLE
internal/graphicsdriver/directx: disabling vsync doesn't work

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2697]
### Ebitengine Version

v2.6.0-alpha.4

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.18.3

### What steps will reproduce the problem?

```go
package main

import (
	"fmt"
	"log"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/ebitenutil"
)

type Game struct{}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ebitenutil.DebugPrint(screen, fmt.Sprintf("FPS %.2f", ebiten.ActualFPS()))
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 1920, 1080
}

func main() {
	ebiten.SetVsyncEnabled(false)
	if err := ebiten.RunGameWithOptions(&Game{}, &ebiten.RunGameOptions{
		GraphicsLibrary: ebiten.GraphicsLibraryDirectX,
	}); err != nil {
		log.Fatal(err)
	}
}
```

### What is the expected result?

ActualFPS() going higher than my display refresh rate (here 240 but it's capped)

### What happens instead?

239 fps

**Comment by hajimehoshi** [comment]
I don't have a display with 240Hz so unfortunately I cannot test this.

**Comment by Zyko0** [comment]
Seems to be introduced by https://github.com/hajimehoshi/ebiten/commit/78d3e4273b0daee8f82dc20debf5fa4e68da5955 from git bisect

**Comment by hajimehoshi** [comment]
Hmm, allowing tearing had a potential risk as the commit describes. I'm looking for another way to disable vsync.

**Comment by hajimehoshi** [comment]
@Zyko0 Would this change work on your machine?

```diff
diff --git a/internal/graphicsdriver/directx/graphics_windows.go b/internal/graphicsdriver/directx/graphics_windows.go
index 80d1c0e94..a8e4c0d5f 100644
--- a/internal/graphicsdriver/directx/graphics_windows.go
+++ b/internal/graphicsdriver/directx/graphics_windows.go
@@ -40,7 +40,7 @@ const (
        noStencil
 )
 
-const frameCount = 2
+const frameCount = 3
 
 func pow2(x uint32) uint32 {
        if x > (math.MaxUint32+1)/2 {
```

**Comment by Zyko0** [comment]
> Would this change work on your machine?

No, this doesn't change anything unfortunately :/

**Comment by hajimehoshi** [comment]
Hmm? This change affect `grahics_windows.go`, right?

**Comment by hajimehoshi** [comment]
Ah you mean that `frameCount` is used only for `*12_windows.go`? Then you are right..

**Comment by Zyko0** [comment]
After testing on last version, it appears I was wrong about the origin
It appears in `windowed mode`, and it's not related to any driver (directx or opengl)

**Comment by hajimehoshi** [comment]
Admitting tearing would fix this issue, but I think this would cause another issue. I'll leave this open, but I might not fix this.

**Comment by hajimehoshi** [comment]
https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingHelloWorld/DeviceResources.cpp#L520

> Recommended to always use tearing if supported when using a sync interval of 0.

Hmm..

**Comment by hajimehoshi** [comment]
@Zyko Please take a look at the latest commit: 6f41a05264ffdb84f50cf42f90e2c0e613eb0f06
