### ISSUE TITLE
Performance issues when playing audio on chrome mobile

### ISSUE THREAD

**Issue by drum445** [hajimehoshi/ebiten#2699]
### Ebitengine Version

v2.5.5

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go version go1.19.4

### What steps will reproduce the problem?

Load an ebiten wasm app that plays audio and notice that when audio is playing, the performance is significantly decreased which causes the audio to stutter and the game to become laggy

### What is the expected result?

The audio plays without a drop in performance

### What happens instead?

Performance drops and the game becomes unplayable

### Anything else you feel useful to add?

This also happens on firefox for mobile, but to a much less extent

Small example app that plays the sound every second, if you run on chrome mobile you'll hear the difference and see the fps drop. In this example I have tried only creating one `audio.Player` for each sound instead of one per play, but it still has the same problem.

[audio_example.tar.gz](https://github.com/hajimehoshi/ebiten/files/12093010/audio_example.tar.gz)

Thanks

**Comment by hajimehoshi** [comment]
The main performance bottleneck is decoding an MP3 data:

![image](https://github.com/hajimehoshi/ebiten/assets/16950/e930ba1b-401e-4170-93e9-0e1b17d17e1b)

One thing you can do for short SEs is that decode the data only once and reuse this:

```go
        d, _ := mp3.DecodeWithoutResampling(f)
        bs, _ := io.ReadAll(d)
        p, _ := audioContext.NewPlayer(bytes.NewReader(bs))
```

**Comment by drum445** [comment]
Thanks for this, using that change the performance no longer drops so the game remains playable, however, the audio sounds rather laggy still, but I guess it's not a bug here, so will have to just disable sound on mobile. Cheers

**Comment by drum445** [comment]
@hajimehoshi I realise it's been a while since we spoke about this issue, but I'm struggling to play sound via the browser without causing a large performance drop, even after trying several different sample projects.
Could you perhaps point me in the right direction please, if you know a potential solution?

**Comment by hajimehoshi** [comment]
Have you tried my proposal? https://github.com/hajimehoshi/ebiten/issues/2699#issuecomment-1643215099 Or does the performance drop happens even with this proposal?

**Comment by drum445** [comment]
@hajimehoshi even with that I'm afraid - the fps doesn't drop as much, but the sound is very laggy/crackly. Also when using that for the larger background sounds it just adds too much time to startup

**Comment by drum445** [comment]
Profiling looks okay to me, can't quite figure out why the sound is so crackly on mobile though. I'll keep an eye out
