### ISSUE TITLE
NewImageFromImage runs indefinitely

### ISSUE THREAD

**Issue by x-46** [hajimehoshi/ebiten#2702]
### Ebitengine Version

2.5.3

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

20.6 linux/amd64

### What steps will reproduce the problem?

```go
//go:embed images/img.png
var imgArr []byte

func foo(){
 	img, _, _ := image.Decode(bytes.NewReader(imgArr))
        newImg := ebiten.NewImageFromImage(img)
        fmt.Println(newImg) // <-- never gets there
        ...
}
``` 

Build for the web:
`GOOS=js GOARCH=wasm go build -o ./../assets/main.wasm`

### What is the expected result?

Should return the image as *ebiten.Image. Which also works perfectly if I run the program local (with `go run .`) 

### What happens instead?

Nothing happens. The program is stuck at this point.

### Anything else you feel useful to add?

![NewImageFromImage](https://github.com/hajimehoshi/ebiten/assets/37456798/e6eca8df-c0a1-413c-a33f-1ddf19f47d9d)

This is the call stack. On the left you can see the call of NewImageFromImage and then from 2707.60 it doesn't come out on the call stack you can see there

**Comment by hajimehoshi** [comment]
* Please provide a minimum reproducible code.
* What does the console say?

**Comment by x-46** [comment]
I have indeed just solved it. 
It seems that you can't call a function that calls NewImageFromImage from JS.


JS code: 
`GoFunction()`

Go code: 
```go
func main() {
	js.Global().Set("GoFunction", js.FuncOf(GoFunction))

}

func GoFunction(){
        .....
        newImg := ebiten.NewImageFromImage(img)
        .....
}
``` 

**is not possible**
