### ISSUE TITLE
kage: improve specs and robustness for uniform passing

### ISSUE THREAD

**Issue by tinne26** [hajimehoshi/ebiten#2708]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Clearer specs for the requirements and behaviors when passing uniform values through Ebitengine APIs to Kage. In particular, the following points seem worth mentioning:
- What happens to a uniform whose value is not explicitly set (zero-value vs panic vs undefined). Currently the behavior is undefined, and uniforms may take junk values when you start using multiple shaders. This can lead to subtle and hard to debug bugs. If I understand correctly, adding something like `if len(uniforms) != len(s.uniformTypes) { panic(...) }` around the start of [`shader.AppendUniforms()`](https://github.com/hajimehoshi/ebiten/blob/ef08873f30fad34e6b431bc960f326c175f5aeb5/internal/ui/shader.go#L48) could go a long way to make usage safer (though there may be reasons why this may not be desirable or even correct, I'm not that knowledgeable about all the possible uses of that function).
- Behavior for invalid uniform names. There's currently an apparently trivial `TODO` in the same function linked before, I don't know if there's any specific reason holding us back from materializing that.
- Clearer spec and improved enforcement of `You cannot assign a value into a uniform variable in Kage` (as noted on [ebitengine.org shader's document](https://ebitengine.org/en/documents/shader.html#Uniform_variables)). Currently, assignations within functions already result in a shader compilation error, but assigning a value on the global definition (e.g. `var MyUniform float = 3.3`) does not trigger any error. This can lead to confusion for users: is the variable a uniform or not? (yes). Is the value doing anything? (no). Etc. This may be the hardest issue to fix. Alternatively, panicking when a uniform value is not explicitly set, as mentioned in the first point, would also make this issue less problematic in practice, as you would still get a panic at runtime.

### Why is this needed?

Uniform-passing behavior is underspecified in the aforementioned points, which can lead to bugs and confusions that should otherwise be easily preventable. The cost to make the changes also seems fairly minor compared to the benefits.

Of course, there may be a reason why this hasn't been tackled yet. In that case, I'd be happy to learn more about why making a final decision for these specs may be premature.

**Comment by hajimehoshi** [comment]
I think filing each issue would be better so that I can address on each item. I have not decided to write a spec so far as I am pretty busy with other tasks. Helpings are welcome!

**Comment by hajimehoshi** [comment]
So please file new three issues for the above three problems. Thanks,
