### ISSUE TITLE
kage: panic if a uniform in *ShaderOptions.Uniforms is missing

### ISSUE THREAD

**Issue by tinne26** [hajimehoshi/ebiten#2709]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Improve safety when dealing with unset uniform values in a shader. Currently, the behavior is undefined, and uniform values may inherit garbage from previous shader calls. In my opinion, panicking would be a more strict but safer approach. Setting the uniform values to zero may also be viable.

### Why is this needed?

Current behavior can lead to subtle and hard to debug bugs.

**Comment by hajimehoshi** [comment]
> Setting the uniform values to zero may also be viable.

I slightly prefer this solution.
