### ISSUE TITLE
kage: panic if a uniform in *ShaderOptions.Uniforms has an invalid name

### ISSUE THREAD

**Issue by tinne26** [hajimehoshi/ebiten#2710]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Improve safety when dealing with incorrectly named uniform values in a shader (e.g., shader declares `var MyUniform float` but we pass a value for `"MyUnifrom"`). Currently, the uniform value will not be set and may inherit garbage from previous shader calls. In my opinion, panicking would be a more strict but safer approach.

### Why is this needed?

Current behavior can lead to subtle and hard to debug bugs.

**Comment by hajimehoshi** [comment]
Unfortunately this fix caused an issue on our applications. The applications takes a user-defined shader, and we cannot expect which uniform variables are used there. So, panicking when unused uniform variables are specified is too strict. I'll revert this once. If we don't, at least we would need a new way to get a uniform variable set from a shader.
