### ISSUE TITLE
Kage cannot compile if statement comparing local int variable to number

### ISSUE THREAD

**Issue by SolarLune** [hajimehoshi/ebiten#2722]
### Ebitengine Version

v2.5.0

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.0

### What steps will reproduce the problem?

Try to create a shader with the following source text:

```
func Fragment(pos vec4, tex vec2, col vec4) vec4 {

    v := 1

    if v > 0 {

    }

    return vec4(1, 0, 0, 1)

}
```

The shader will not compile because literal numbers default to the float type if not set to a variable, I believe - either changing v to be 1.0 instead of 1, or changing the if statement to `if v > int(0)` compiles correctly.

### What is the expected result?

The shader compiles correctly.

### What happens instead?

The shader crashes, either with a segmentation fault, or the following error message:

```
panic: opengl: fragment shader compile error: opengl: shader compile failed: 0:58(6): error: could not implicitly convert operands to relational operator
0:58(6): error: if-statement condition must be scalar boolean
, source:
#if defined(GL_ES)
precision highp float;
precision highp int;
#else
#define lowp
#define mediump
#define highp
#endif

int modInt(int x, int y) {
        return x - y*(x/y);
}

ivec2 modInt(ivec2 x, int y) {
        return x - y*(x/y);
}

ivec3 modInt(ivec3 x, int y) {
        return x - y*(x/y);
}

ivec4 modInt(ivec4 x, int y) {
        return x - y*(x/y);
}

ivec2 modInt(ivec2 x, ivec2 y) {
        return x - y*(x/y);
}

ivec3 modInt(ivec3 x, ivec3 y) {
        return x - y*(x/y);
}

ivec4 modInt(ivec4 x, ivec4 y) {
        return x - y*(x/y);
}

uniform vec2 U0;
uniform vec2 U1[4];
uniform vec2 U2;
uniform vec2 U3;
uniform vec2 U4[3];
uniform vec2 U5;
uniform vec2 U6;
uniform mat4 U7;
uniform sampler2D T0;
uniform sampler2D T1;
uniform sampler2D T2;
uniform sampler2D T3;
varying vec2 V0;
varying vec4 V1;

vec4 F12(in vec4 l0, in vec2 l1, in vec4 l2);

vec4 F12(in vec4 l0, in vec2 l1, in vec4 l2) {
        int l3 = 0;
        l3 = 1;
        if ((l3) > (0.0)) {
        }
        return vec4(1.0, 0.0, 0.0, 1.0);
}

void main(void) {
        gl_FragColor = F12(gl_FragCoord, V0, V1);
}

```

The relevant part seems to be the error: `if-statement condition must be scalar boolean`

### Anything else you feel useful to add?

I'm on Linux, EndeavourOS, which would use OpenGL as the rendering backend, I suppose.

**Comment by hajimehoshi** [comment]
Could you try the latest commit in the main branch?

**Comment by maladroitthief** [comment]
I was able to reproduce this in the 2.5 branch, but not in main.

**Comment by hajimehoshi** [comment]
Sure. So this was already fixed.
