### ISSUE TITLE
Some example/shader shaders don't work on M1 mac

### ISSUE THREAD

**Issue by hackborn** [hajimehoshi/ebiten#2724]
### Ebitengine Version

2.5.6

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.20.3

### What steps will reproduce the problem?

I compiled and ran the examples/shader app and stepped through each shader. The shaders that don't work are: Default, texel, radial blur, chromatic abberation and water. The lighting and dissolve shaders work fine.

### What is the expected result?

The compiled shader app produces the same results as the [(example shader app).](https://ebitengine.org/en/examples/shader.html) on the web 

### What happens instead?

Here are screen shots from the non-working shaders:

![Shader default](https://github.com/hajimehoshi/ebiten/assets/4147095/a9a1eeb9-5639-4573-b8ec-07ba4e0ac34e)
![Shader texel](https://github.com/hajimehoshi/ebiten/assets/4147095/1d46961b-7921-4528-9970-5b12d4596b3d)
![Shader radial blur](https://github.com/hajimehoshi/ebiten/assets/4147095/cafcb279-8024-4f40-b800-7fd4e26c2943)
![Shader chromatic](https://github.com/hajimehoshi/ebiten/assets/4147095/4c3fca92-b906-4377-b782-315904683fbe)
![Shader water](https://github.com/hajimehoshi/ebiten/assets/4147095/45bfc544-3220-4ac1-819b-92036f8c4ef1)

### Anything else you feel useful to add?

Happy to help with any debugging if there are some suggestions on how to debug shaders.

**Comment by hajimehoshi** [comment]
I'll take a look soon later.

**Comment by tinne26** [comment]
> Happy to help with any debugging if there are some suggestions on how to debug shaders.

Using git bisect or checking with previous Ebitengine versions to see if this is a regression (and in that case, when did that regression happen) would be a very helpful first step.

**Comment by hajimehoshi** [comment]
@hackborn Does this issue happen with the latest commit of the main branch?

**Comment by hajimehoshi** [comment]
Apparently you run the main branche's shaders with Ebitengine 2.5.6, right? I am not sure why you are in this situation, but I could reproduce the issue by these steps:

```sh
# Under the Ebitengine directory:
git switch 2.5
git restore -s main ./examples/shader
go run ./examples/shader
```

**Comment by hajimehoshi** [comment]
@hackborn friendly ping

**Comment by hackborn** [comment]
Ahh yes, sorry. Looks like user error: I'm running 2.5.6 but had just grabbed the latest example code on main. Swapped out the texel shader with the proper 2.5.6 version and it works. My apologies!

**Comment by hajimehoshi** [comment]
No problem!
