### ISSUE TITLE
Setting a background color for the window when opening it, before starting the rendering

### ISSUE THREAD

**Issue by mat007** [hajimehoshi/ebiten#2725]
### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

A way to control the initialization of the window when the game opens up, e.g. at least be able to set a color.

### Why is this needed?

My game intro screen has a black background, and when launching it, there is a not very pleasing white background that flashes in the window, before the first draw.

This can be reproduced by running the `paint` example with the following changes:
```
diff --git a/examples/paint/main.go b/examples/paint/main.go
index de3b5df1..362977b0 100644
--- a/examples/paint/main.go
+++ b/examples/paint/main.go
@@ -27,8 +27,8 @@ import (
 )

 const (
-       screenWidth  = 640
-       screenHeight = 480
+       screenWidth  = 1024
+       screenHeight = 768
 )

 var (
@@ -76,7 +76,7 @@ func NewGame() *Game {
        g := &Game{
                canvasImage: ebiten.NewImage(screenWidth, screenHeight),
        }
-       g.canvasImage.Fill(color.White)
+       g.canvasImage.Fill(color.Black)
        return g
 }
```
The bigger the window, the more visible it seems to be.

**Comment by hajimehoshi** [comment]
I am not sure this is controllable. Let me investigate this

**Comment by mat007** [comment]
Thanks @hajimehoshi !

On Windows I believe it could just be doing
```
wc.hbrBackground = …
```
in https://github.com/hajimehoshi/ebiten/blob/3b67b91bb2c4c44af7e187670e54895ede6e4b30/internal/goglfw/win32window_windows.go#L1351 passing it a brush.

But I have no clue for other platforms.

I’m also thinking I could perhaps delay the showing of the window after it’s been created somehow, to make sure there is at least of rendering that’s been done?
