### ISSUE TITLE
texCoord changes when attaching second image to DrawRectShaderOptions

### ISSUE THREAD

**Issue by lowfatcode** [hajimehoshi/ebiten#2734]
### Ebitengine Version

2.5.7

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21

### What steps will reproduce the problem?

While working on a project I came across odd behaviour where the first 11 frames would render correctly but the twelfth would be corrupted. I managed to narrow that issue down to the `texCoord` parameter of my fragment shader being messed up.

While trying to create a minimal example of the problem I came across another issue (which is likely related). The following code demonstrates it:

```go
package main

import (
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

type Game struct{}

var test_image1 *ebiten.Image
var test_image2 *ebiten.Image
var test_shader *ebiten.Shader
var test_shader_options ebiten.DrawRectShaderOptions
var ticks = 0

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ticks++

	if ticks > 120 {
		test_shader_options.Images[1] = test_image2
	}

	screen.DrawRectShader(720, 568, test_shader, &test_shader_options)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return 720, 568
}

func main() {
	ebiten.SetWindowSize(720, 568)
	ebiten.SetWindowTitle("texCoord bug example")

	var err error
	test_shader, err = ebiten.NewShader([]byte(`//kage:unit pixels
		package main

		func Fragment(position vec4, texCoord vec2, color vec4) vec4 {

			var result vec4
			result.r = texCoord.x 
			result.g = texCoord.y
			result.b = 0
			result.a = 1

			return result
		}
	`))
	if err != nil {
		log.Fatal(err)
	}

	test_image1 = ebiten.NewImage(720, 568)
	test_image2 = ebiten.NewImage(720, 568)

	test_shader_options.Images[0] = test_image1

	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

The program starts with a single image attached to the shader (the image data is not used at all) and the shader simply uses the `x` value of the `texCoord` to set the output red channel value.

### What is the expected result?

Initially you will see a gradient from black to red horizontally across the window. The red channel will cover the full range of `0 .. 1` starting at pure black on the left and finishing with pure red on the right. This is correct as I understand it. 

### What happens instead?

After two seconds the program attaches a second image to the shader and this causes the `texCoord` parameter to change behaviour. You'll see that now the red channel only goes from `0 .. 0.5` instead of covering the full range.

It's almost as if the `texCoord` is being scaled to twice the image width instead of a single image width but I'm pretty sure that isn't intended behaviour.

### Anything else you feel useful to add?

As an aside I believe that `//kage:unit pixels` should actually mean that the `texCoord` parameter is in pixels, not UV coordinates - I can't see why that isn't the case here.

**Comment by hajimehoshi** [comment]
`//kage:unit pixels` works in the main branch but not in 2.5. Have you checked this with the main branch?

**Comment by lowfatcode** [comment]
> `//kage:unit pixels` works in the main branch but not in 2.5. Have you checked this with the main branch?

This is the entry in my `go.mod` (apologies, I'm completely new to Go so please be gentle! 😄) which was added when I followed the install guide here: https://ebitengine.org/en/documents/install.html

`	github.com/hajimehoshi/ebiten/v2 v2.5.7 // indirect`

**Comment by hajimehoshi** [comment]
OK so you are using v2.5.7, and the pixel unit mode is not implemented there. I'll close this issue as this works as expected. Thanks,

**Comment by lowfatcode** [comment]
I have noticed something else, if I place the images in the second and third positions of `test_shader_options.Images` then it works as expected (even fixing the issues with not using pixel coordinates!).

So...

```go
test_shader_options.Images[0] = image1
...
test_shader_options.Images[1] = image2
```

...breaks, but...

```go
test_shader_options.Images[1] = image1
...
test_shader_options.Images[2] = image2
```

...seems to work fine (you'll need to change the shader to scale the `texCoord` properly though as it is now in pixels not UV coordinates).

That's odd... is `test_shader_options.Images[0]` somehow special? Should it even be accessible via the API if it breaks things to overwrite it?

**Comment by hajimehoshi** [comment]
Yeah, the implementation detects whether the 0th image is set or not to calculate the source size, so the answer is yes, `test_shader_options.Images[0]` is special. This should affects the values of `texCoord`. If the 0th image is not specified, there is no way to calculate 'texels', so just pixels are used as they are. I think this is a quite odd behavior, but this was inevitable. The new pixel mode will resolve this incosistent behavior.

**Comment by lowfatcode** [comment]
For someone starting a new project which version do you recommend? I pretty much just went off the install documentation to get started.

I'm completely new to Go but have a lot of experience with C++, OpenGL, and shaders...

**Comment by hajimehoshi** [comment]
I recommend using the stable version (2.5.7 for now) if you don't have special reasons. Things newly implemented in the main branch can be changed anytime.

**Comment by lowfatcode** [comment]
I've forced myself onto the 2.5.7 release and I believe this bug is still present.

Ignore my comment about pixel coordinates previously - I understand how that works now and have ensured the example works only using UV coordinates.

If you run this program you'll see a red/green gradient rendered by the shader - there is a single image attached as `test_shader_options.Images[0] = test_image1` which is the same size as the destination for the `DrawRectShader` call but this image isn't referenced in the shader code at all.

After 2 seconds you'll see the output of the shader change, this happens when I attach a second image `test_shader_options.Images[1] = test_image2` which again isn't referenced in the shader at all.

It's like the bounds of `texCoord` change when the second image is attached but I don't believe that is correct behaviour.

This is the line from my `go.mod`: `require github.com/hajimehoshi/ebiten/v2 v2.5.7`

This is the full example program that demonstrates the issue:

```go

package main

import (
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

type Game struct{}

var test_image1 *ebiten.Image
var test_image2 *ebiten.Image
var test_shader *ebiten.Shader
var test_shader_options ebiten.DrawRectShaderOptions
var ticks = 0

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	ticks++

	if ticks > 120 {
		test_shader_options.Images[1] = test_image2
	}

	screen.DrawRectShader(720, 568, test_shader, &test_shader_options)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return 720, 568
}

func main() {
	ebiten.SetWindowSize(720, 568)
	ebiten.SetWindowTitle("texCoord bug example")

	var err error
	test_shader, err = ebiten.NewShader([]byte(`
		package main

		func Fragment(position vec4, texCoord vec2, color vec4) vec4 {

			var result vec4
			result.r = texCoord.x
			result.g = texCoord.y
			result.b = 0
			result.a = 1

			return result
		}
	`))
	if err != nil {
		log.Fatal(err)
	}

	test_image1 = ebiten.NewImage(720, 568)
	test_image2 = ebiten.NewImage(720, 568)

	test_shader_options.Images[0] = test_image1

	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}

```

**Comment by hajimehoshi** [comment]
I am not sure what is your expectation. An image is on a big texture, so `texCoord` can take any range.

In order to normalize `texCoord` to [0, 1], see https://github.com/hajimehoshi/ebiten/blob/2.5/examples/shader/texel.go for example.

**Comment by hajimehoshi** [comment]
See also https://ebitengine.org/en/documents/shader.html#Textures_and_images

**Comment by lowfatcode** [comment]
My expectation is that `texCoord` would be consistent whether one or two images are attached to the shader.

All attached images and the destination are the same size (720 x 568) as is required (it errors if they don't match). So why does the range of `texCoord` change depending on whether one or two images are attached to the shader?

**Comment by hajimehoshi** [comment]
> My expectation is that texCoord would be consistent whether one or two images are attached to the shader.

Unfortunately this is not consistent in Ebitengine. An internal texture holding images can be extended anytime. Using a different source image might trigger this extention and affect the result.

**Comment by lowfatcode** [comment]
Ahh! I see, so the various attached images are all combined onto a single super image...

I guess I wonder why this...

```go
			origin, size := imageSrcRegionOnTexture()
			texCoord -= origin
			texCoord /= size
```

...isn't always done to `texCoord` by the engine before it is passed into the fragment shader then - it seems that's the behaviour you'd always want?

**Comment by hajimehoshi** [comment]
I don't do that as this would require re-conversion when retriaving a texel value by imageSrc0At, which would affect performance.

As you know, I plan to introduce the pixel mode in v2.6, so the confusion would be mitigated to some extent.

**Comment by lowfatcode** [comment]
Ok - and I'm sorry for taking up your time, I'm just trying to wrap my head around why my code won't work.

Basically I want to be able to look up a specific pixel in two attached images and then write that same coordinate to the output. My naive assumption was the `texCoord.x` was basically `0 .. 1` across the width of the image and `texCoord.y` was `0 .. 1` from top to bottom. And that I can then use `imageSrc0At(texCoord)` and `imageSrc1At(texCoord)` to fetch the corresponding pixel data from my two attached images.

I think I'm fundamentally misunderstanding something now. It seems that the two attached images are internally merged onto a texture and `texCoord` is not actually bound to the destination so I'm not sure what the correct process is...

**Comment by hajimehoshi** [comment]
No problem! I admit Kage shader and things behind it is pretty confusing.

By the way, could you reply to https://github.com/hajimehoshi/ebiten/issues/2732#issuecomment-1694215122 ? My guess is that nothing (or an empty line) is shown with echo, but env includes `DYLD_FALLBACK_FRAMEWORK_PATH` with an empty string in your environment.
