### ISSUE TITLE
ebiten: add an option to disable a menubar to appear when playing in full-screen mode on macOS

### ISSUE THREAD

**Issue by quasilyte** [hajimehoshi/ebiten#2745]
### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

When playing a game in fullscreen mode on macos, a window title bar will appear if you move the mouse pointer to the upper part of the screen.

It looks like this:

![image](https://github.com/hajimehoshi/ebiten/assets/6286655/a115db5c-7804-414e-97e6-22e836ba62d3)

I'm **not** sure that there is anything Ebiten can do here, but let's create an issue and give an opportunity for some investigation; or maybe someone will come and comment the workaround!

### Why is this needed?

When playing a game with camera controls via the mouse cursor, there is usually an edge scrolling.
If the player moves the cursor to the top to move the camera up, they open the window title bar instead, which is annoying.

**Comment by hajimehoshi** [comment]
So your request is to have an option not to show the top menubar on macOS?

**Comment by quasilyte** [comment]
Yes, that's correct. It would be great to have.

**Comment by hajimehoshi** [comment]
By the way, in your game, capturing a cursor by `ebiten.SetCursorMode(CursorModeCaptured)` might fit. What do you think?

**Comment by quasilyte** [comment]
Some extra info:
* I tried it in another game (Hades), and it also behaves this way :'(
* I'm using Ebitengine `v2.6.0-alpha` when building for `GOOS=darwin` and `GOARCH=amd64` with `CGO_ENABLED=1`
* Setting `ebiten.SetCursorMode(CursorModeCaptured)` does make the problem go away; I just need to render the cursor myself I guess
* I tried `v2.5.0` as Alex suggested in the Discord chat, but it doesn't change anything; I guess they're using `ebiten.SetCursorMode(CursorModeCaptured)`?

I wonder if there is anything that can be done on the Ebitengine side tbh since some other games have the same issue.
I tried to avoid the captured cursor since it makes the cursor feel less responsive.

**Comment by hajimehoshi** [comment]
>  I just need to render the cursor myself I guess

Yeah that's right.

> I tried v2.5.0 as Alex suggested in the Discord chat, but it doesn't change anything; I guess they're using ebiten.SetCursorMode(CursorModeCaptured)?

v2.5.0 should behave in the same way. Probably we were not on the same page.

> I wonder if there is anything that can be done on the Ebitengine side tbh since some other games have the same issue.
I tried to avoid the captured cursor since it makes the cursor feel less responsive.

I was trying to find a way but these seems no way to keep hiding the menubar so far. I feel like this is not a fixable issue as long as Ebitengine uses the native fullscreen mode.

**Comment by kalexmills** [comment]
> * I tried `v2.5.0` as Alex suggested in the Discord chat, but it doesn't change anything; I guess they're using `ebiten.SetCursorMode(CursorModeCaptured)`?

Good catch. I absolutely am using a captured cursor.

**Comment by tinne26** [comment]
By the way, isn't there an option in the OS to change this behavior? Asking because I don't use macOS, but it would be nice to at least know and be able to help actual players. The cursor simulation can always be offered as an in game option too (even only for macOS), but yeah, it's bad for responsivity.

**Comment by hajimehoshi** [comment]
https://osxdaily.com/2022/03/17/keep-menu-bar-visible-mac-full-screen/ You can disable automatic hiding the menu bar. But that's all.

**Comment by gophun** [comment]
> Setting `ebiten.SetCursorMode(CursorModeCaptured)` does make the problem go away; I just need to render the cursor myself I guess

I tried this, but now the cursor can go off into infinity, see #1480. I don't see how captured mode is usable at all with this behaviour.

**Comment by hajimehoshi** [comment]
Unfortunately this issue doesn't seem fixable without a dirty hack like https://apple.stackexchange.com/questions/70985/make-the-menu-bar-never-show-while-in-full-screen. Let me close this. If anyone can fine a good solution, please let me know.
