### ISSUE TITLE
Kage: Multiple return values of different types

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2747]
### Ebitengine Version

v2.6.0-alpha.6.0.20230903081539-f82114e8eb30

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.18.3

### What steps will reproduce the problem?

```go
package main

import (
	"log"

	"github.com/hajimehoshi/ebiten/v2"
)

var (
	src = []byte(
		`
package main

func ok() (float, bool) {
	return 0., false
}

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
	bk, k := ok()
	_, _ = bk, k
	return vec4(0)
}
`)
	s *ebiten.Shader
)

func init() {
	var err error

	s, err = ebiten.NewShader(src)
	if err != nil {
		log.Fatal(err)
	}
}

type Game struct {}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return 1, 1
}

func main() {
	_ = ebiten.RunGame(&Game{})
}
```

### What is the expected result?

Running successfully

### What happens instead?

Compilation error: `9:2: cannot use type float as type bool in variable declaration`

### Anything else you feel useful to add?

Looks similar to <https://github.com/hajimehoshi/ebiten/issues/2655> but might not be related

**Comment by hajimehoshi** [comment]
Confirmed.
