### ISSUE TITLE
Installation:  libopenal-dev is required

### ISSUE THREAD

**Issue by tSU-RooT** [hajimehoshi/ebiten#275]
Hi!
I tried to install ebiten by `go get -u github.com/hajimehoshi/ebiten/...`
I had already installed [these libraries](https://github.com/hajimehoshi/ebiten/wiki/Linux) for my Ubuntu system, 
but build was failed.

```
$ go get github.com/hajimehoshi/ebiten/...
# github.com/timshannon/go-openal/openal
In file included from ../../timshannon/go-openal/openal/alcCore.go:24:0:
./local.h:5:18: fatal error: AL/al.h: No such file or directory
compilation terminated.

$ apt-file search "AL/al.h"
emscripten: /usr/share/emscripten/system/include/AL/al.h
libopenal-dev: /usr/include/AL/al.h
```

Seems ebiten requires libopenal-dev library.
I think it is good to add name of this library to the list.

**Comment by hajimehoshi** [comment]
Thank you for reporting! You're right, I missed to add this. I've just fixed the document.
