### ISSUE TITLE
internal/shader: support shift operators for ints and int vectors

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2755]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

`<<` is available at e.g. GL ES 3.0.

**Comment by RiXelanya** [comment]
I am interested in doing this.

**Comment by hajimehoshi** [comment]
PRs are always welcome!
