### ISSUE TITLE
Transparent pixels rendering as white since v2.3.0

### ISSUE THREAD

**Issue by sinisterstuf** [hajimehoshi/ebiten#2756]
### Ebitengine Version

since @f2209a0b5

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

BTW I didn't try different OSes but I don't think this is OS-specific.

### Go Version (`go version`)

go version go1.21.1 linux/amd64

### Problem description

_(sorry for breaking format from the issue template)_

I tried updating an old game from v2.2.4 to v2.5.9 and noticed something strange.  First I thought I'd made a mistake or missed something from the release notes, but now I think it might be a bug in Ebitengine.  I have a palletted image with transparency that's generated from code and previously the corners were transparent (in the game this is a cursor, and you can see what it's hovering over underneath) but after the update instead of transparent they seem white.

<table>
  <tr align="center">
    <td colspan="2" align="center"><b>The corners of the cursor are now rendered white</b></td>
  </tr>
  <tr>
    <td align="center">BEFORE (476f4e3f9) GOOD</td>
    <td align="center">AFTER (f2209a0b5) BAD</td>
  </tr>
  <tr>
    <td><img src="https://github.com/hajimehoshi/ebiten/assets/840466/eacae07c-7935-46b6-aea9-9034a76a2589" width="288"></td>
    <td><img src="https://github.com/hajimehoshi/ebiten/assets/840466/ac988a0e-488e-482c-b741-56856b68b3cc" width="288"></td>
  </tr>
</table>

I did some manual bisecting with different Ebitengine versions and found that this behaviour was introduced in v2.3.0-alpha.6, specifically in commit f2209a0b5 which talks about _"internal/atlas: optimization: send premultiplied alpha from vertex to fragment shader. (#1996)"_ so it seems very relevant to this problem.  The release notes don't mention user/dev-facing changes to how alpha is handled and this comment from the commit message, makes me think that this change in behaviour might not be intentional:

> _I assume this is a strict improvement, however this may warrant some testing._

The code that generates this is in [nokia-defence/cursor.go:100](https://github.com/sinisterstuf/nokia-defence/blob/main/cursor.go#L100-L109):

```go
w := 3
i := image.NewPaletted(
    image.Rect(0, 0, w, w),
    NokiaPalette,
)
i.Pix = []uint8{
    0, 1, 0,
    1, 0, 1,
    0, 1, 0,
}
```

and the colour palette comes from [nokia-defence/main.go:32](https://github.com/sinisterstuf/nokia-defence/blob/main/main.go#L24-L32)

```go
// ColorTransparent is completely transparent, used for images that aren't square shaped to show the underlying colour
ColorTransparent color.Color = color.RGBA{67, 82, 61, 0}
// ColorLight is the ON or 1 screen colour, similar to white
ColorLight color.Color = color.RGBA{199, 240, 216, 255}
// ColorDark is the OFF or 0 screen colour, similar to black
ColorDark color.Color = color.RGBA{67, 82, 61, 255}
// NokiaPalette is a 1-bit palette of greenish colours simulating Nokia 3310
NokiaPalette color.Palette = color.Palette{ColorTransparent, ColorDark, ColorLight}
```

Changing the values of ColorTransparent I can see they have an effect but it doesn't give me full transparency any more.  Let me know if I can provide any more details.

**Comment by hajimehoshi** [comment]
This is a kind of FAQ.

```go
color.RGBA{67, 82, 61, 0}
```

`color.RGBA` is a premultiplied-alpha value then RGB should not exceed the alpha value.

**Comment by sinisterstuf** [comment]
OK sorry, so the API I was changed and I was using it incorrectly before?

**Comment by hajimehoshi** [comment]
The implementation was changed to treat premultiplied alpha values more strictly. The API has not changed.

**Comment by hajimehoshi** [comment]
>  I was using it incorrectly before?

Yes. Old Ebitengine worked as you expected at that time, but this was a coincident.

**Comment by sinisterstuf** [comment]
Thanks, that makes sense, it really wasn't clear from the commit message that this change was intentional, sorry for the noise.

**Comment by hajimehoshi** [comment]
No problem!
