### ISSUE TITLE
ebiten: API to get mapping between a physical button and a standard gamepad layout

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2775]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Sometimes a gamepad has more buttons than the standard gamepad layout. If someone wants to use such extra buttons, the current standard gamepad layout APIs are useless since there is no way to know which button ID is an extra button or a button in the standard layout. So, let's consider to have APIs to know the mapping.

**Comment by hajimehoshi** [comment]
Things are complicated. A button might be mapped to a standard axis, or an axis might be mapped to a standard button. So, I want to stand with these API that return just a bool value in order to avoid confusions.

```go
func GamepadMapping(id GamepadID) GamepadMapping

type GamepadMappingType struct {}

func (*GamepadMappingType) IsButtonMapped(button GamepadButton) bool
func (*GamepadMappingType) IsAxisMapped(axis GamepadAxis) bool
```

**Comment by hajimehoshi** [comment]
Another suggestion:

```
type GamepadMappingItem struct {
    Type GamepadMappingItemType // std button or std axis
    // Details...
}

func (*GamepadMappingType) ButtonMappings() []GamepadMappingItem // A index is a gamepad button ID
func (*GamepadMappingType) AxisMappings() []GamepadMappingItem // A index is a gamepad axis ID
```

**Comment by tinne26** [comment]
Knowing the exact mapping is also useful for display purposes during input configuration and similar. Like, if you have a standard layout for a controller and want to show a schematic indicating which actions correspond to each button under the current configuration in your game, you can't do it without knowing the exact mapping. So, the methods from the first proposal wouldn't help for that case.

Just to offer yet another perspective, the lowest level solution to get back all the relevant information would be `GetStandardLayoutGamepadMapping() string`. Of course, this is far from ideal and a struct would seem like a much better option, but `UpdateStandardLayoutGamepadMappings(string) (bool, error)` is already that low level and dependant on the SDL format.

**Comment by hajimehoshi** [comment]
> Just to offer yet another perspective, the lowest level solution to get back all the relevant information would be GetStandardLayoutGamepadMapping() string.

My last suggestion is actually close to your suggestion. My suggestion treats a struct instead of a string. Returning a string doesn't work on browsers. In web browsers, there is a standard layout mapping wihtout SDL string formats.

**Comment by hajimehoshi** [comment]
This proposal might not be efficient, but this should reflect what we need:

```go
// GamepadMapping returns a mapping of pairs with a standard button/axis and a physical button/axis.
func GamepadMapping(id GamepadID) []GamepadMappingPair

type GamepadMappingPair struct {
    Standard any // Either StandardGamepadButton or StandardGamepadAxis
    Physical any // Either GamepadButton or int // This will be type GampadAxis (#1718)
}
```

Go doesn't have a union type (yet).

**Comment by tinne26** [comment]
I was thinking about `UpdateStandardGamepadLayoutMappings(mappings string)` and whether we would be able to unify getting the mappings and setting them with this new struct. Like, `GetGamepadMapping(id GamepadID) []GamepadMappingPair` and `SetGamepadMapping(SDLID string, []GamepadMappingPair) error`. The current update method is more general and powerful (updating multiple gamepad mappings at once), but in my opinion being able to manage this with the more explicit `GamepadMappingPair` structs would make the job easier for ebitengine users.

**Comment by hajimehoshi** [comment]
> ```go
> type GamepadMappingPair struct {
>     Standard any // Either StandardGamepadButton or StandardGamepadAxis
>     Physical any // Either GamepadButton or int // This will be type GampadAxis (#1718)
> }
> ```

A mapping was not so simple. This has to consider axis scales and axis offsets. Hmm

**Comment by hajimehoshi** [comment]
I've implemented a prototype, and realized that the API might be useless to know actually unmapped physical buttons. For example, a PS5 controller has trigger buttons on its shoulder. These physical buttons are not mapped, but physical axes are mapped instead. So, `StandardGamepadButtonFrontBottomLeft/Right` are still available as buttons though the mapping doesn't include items for these physical buttons.

**Comment by hajimehoshi** [comment]
Let me postpone this task. I assume that this request is relatively niche.

**Comment by hajimehoshi** [comment]
Note to myself: apparently the index 17 and more are assigned for extra buttons in the Web API. This doesn't seem standardized or speced.

![image](https://github.com/hajimehoshi/ebiten/assets/16950/c8c45d3d-d7b0-462f-b28c-cc170958d9c3)

**Comment by hajimehoshi** [comment]
I think https://github.com/hajimehoshi/ebiten/issues/2775#issuecomment-2001940682 is not solvable.
