### ISSUE TITLE
ebiten: remove `(*Monitor).Bounds`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2780]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Now the unit of Bounds is device-dependent pixels, and this is useless and Ebitengine API always treat device-independent pixels. Rather, this might confuse users.

Until we find a good solution, let's remove Bounds() for v2.6. MonitorType itself is still useful to specify a monitor to show a window.

/CC @kettek

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/a269cf378557688f4baa21eee1bcf9c825a780c0

**Comment by kettek** [comment]
I think Bounds can be useful for identifying a monitor in a large multi-monitor setup, especially since acquiring names of monitors via glfw isn't reliable between platforms. However, I suppose it's okay to just use indices for monitor identification.

**Comment by hajimehoshi** [comment]
Yeah, I admit Bounds would be useful e.g. to show monitor lists as a UI, but I wanted to avoid risk of adding public APIs. Anyway let's revisit this later when we really need.

**Comment by hajimehoshi** [comment]
Note to myself: GLFW's coordinate systems are really chaotic. See https://github.com/glfw/glfw/issues/1961

Ebitengine distinguishes these units.

* **Device-independent pixels**: This is an exposed coordinate to Ebitengine users. This is bascailly GLFW pixels divided by the device scale factor.
* **GLFW pixels**: This is the unit most GLFW API treats
* **GLFW monitor pixels**: This is the unit of GLFW monitor sizes (not position!) This is different from GLFW pixels on Linux so far due to the issue https://github.com/glfw/glfw/issues/1961. Our fix is in https://github.com/hajimehoshi/ebiten/blob/7664647ad17ef5b09b3398655ce38e24e647c9c3/internal/ui/ui_glfw_linbsd.go#L54-L142

In order to put a window on the center of the screen by [`glfwSetWindowPos`](https://www.glfw.org/docs/3.3/group__window.html#ga1abb6d690e8c88e0c8cd1751356dbca8), this calculation in pseudo code worked:

```go
func SetWindowPosition(w glfwWindow, x, y int, m glfwMonitor) {
    x, y = convertDIPPixelsToGLFWPixels(x, y)
    wx, wy := glfwGetWindowPos(w) // A window position is in GLFW pixels
    ww, wh := glfwGetWindowSize(w) // A window size is in GLFW pixels
    mx, my := glfwGetMonitorPos(m) // A monitor position is in GLFW pixels
    v := glfwGetVideoMode(m)
    mw, mh := v.width, v.height // A monitor size is in GLFW monitor pixels, not GLFW pixels (especially on Linux)
    mw, mh = convertGLFWMonitorPixelsToGLFWPixels(mw, mh)
    glfwWindowSetPos(mx + x + (mw - w)/2, my + y + (mh - h)/2)
}
```

As a monitor position unit and a monitor size unit are different, it would be hard to return bounds that makes sense.
