### ISSUE TITLE
ebiten: add a function to get a position and/or a size of a monitor

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2781]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

As the title says, we want a function to get a position and/or a size of monitors [in a virtual coordinate](https://www.glfw.org/docs/3.3/intro_guide.html#coordinate_systems)

`Bounds()` was not added in v2.6 since there are more complex underlying issues around units. See https://github.com/hajimehoshi/ebiten/issues/2780

### Why is this needed?

This would be useful to make a better UI to choose monitors for users.

**Comment by hajimehoshi** [comment]
@divVerent might have insights about the monitor sizes (see https://github.com/glfw/glfw/issues/1961). IIUC the sizes in GLFW's Vidmode is sometimes not correct and then we have to adjust the scale. Is that correct?

/CC @kettek

**Comment by divVerent** [comment]
Well, the problem is - they're not really _incorrect_, but at the wrong
layer. GLFW returns hardware pixels, but the resolutions one actually has
to specify or use are in "desktop environment pixels" (which can again be
different from virtual, "LoDPI", pixels).

**Comment by hajimehoshi** [comment]
From my brief investigation, this values seem the most consistent, and two adjacent monitors have two adjacent bounds. The units are GLFW pixels (i.e. pixels GLFW directly treats).

X: VideoMode's X
Y: VideoMode's Y
Width: width in XRandR's info
Height: height in XRandR's info

> Well, the problem is - they're not really _incorrect_, but at the wrong layer. 

Oh I see... Thanks!

**Comment by hajimehoshi** [comment]
The native size information is less useful as the unit is not compatible with other Ebitengine APIs. So, this information is only for debugging or auxiliary information to show to users. Then, I'm thinking we should return this as a string, instead of integer values... 🤔 

(Note that `(*Monitor).Size` (#2795) returns a size in device-independent pixels, which is compatible with the other Ebitengine APIs)

**Comment by divVerent** [comment]
Sounds good to me. Note though that a game may have a good reason to find
out whether its scaling factor is 1:1 or not - but that is still possible
with a string.

**Comment by hajimehoshi** [comment]
> Note though that a game may have a good reason to find out whether its scaling factor is 1:1 or not 

For this purpose, `(*ebiten.Monitor).DeviceScaleFactor()` works, right?

**Comment by hajimehoshi** [comment]
Hmm, I decided not to implement this so far, since it was not clear to me how useful this API would be useful. If you want to get the size (in Ebitengine units), you can use the new API `(*Monitor).Size` (#2795). Let me close this. I'm fine to revisit this when we need.
