### ISSUE TITLE
Kage: integer arithmetics functions support

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2788]
### Ebitengine Version

v2.7.0-alpha.2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21

### What steps will reproduce the problem?

Kage shader compilation:
```go
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4 {
	_ = sign(int(8))
	return vec4(0)
}
```
abs, sign, min/max and clamp functions with integer types (int, ivec2, ivec3, ivec4) (noticed by @tinne26)

### What is the expected result?

no error

### What happens instead?

compilation error: `cannot use int as float, vec2, vec3, or vec4 value in argument to sign`

**Comment by tinne26** [comment]
To be fair, this currently works as advertised on <https://ebitengine.org/en/documents/shader.html#Built-in_functions_(mathematics)>. The main offenders would be only min/max, as they don't work like Go1.21 built-in functions if ints are not supported. But then, if you support ints for min/max, it seems weird to not also support them for the few other functions mentioned.

**Comment by hajimehoshi** [comment]
See also https://github.com/hajimehoshi/ebiten/issues/2677

**Comment by hajimehoshi** [comment]
Note to myself:

https://registry.khronos.org/OpenGL/specs/gl/GLSLangSpec.4.60.pdf

Some function like `sin` takes only floats and ths is represented as genFType.

**Comment by hajimehoshi** [comment]
So the build-in functions that can take integers are:

* `abs`
* `sign`
* `min`
* `max`
* `clamp`
