### ISSUE TITLE
Kage: Output a non-alpha premultiplied color

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2798]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

I'd like for this feature to be kept* and was wondering if we could rely on the following behaviour (Kage):
```go
//kage:unit pixels // doesn't matter I think

package main

func Fragment(dst vec4, src vec2, color vec4) vec4 {
    return vec4(10, 20, 30, 5)/255 // Alpha value lower than r,g,b components
}
```

The above shader produces a color that is not correctly alpha-premultiplied, but:
- The resulting dst `*ebiten.Image`'s pixels can be queried with `*ebiten.Image.At(x, y int) color.Color` and would still return the `color.RGBA{10,20,30,5}`
- The resulting image can be used as a source image for another shader and would correctly interpret these values

The functions `*ebiten.Image.Set` and `*ebiten.Image.WritePixels` also behave this way (as they just write what's given to the dst image, whether the color is valid or not)

### Why is this needed?

I don't think this has been problematic so far, but it should be kept this way in my opinion.

This would keep the API just more generally flexible, to treat textures as "data" array for example, or use Kage as a sort of "compute shader" (`Set`, `WritePixels` in this case are also relevant to build the proper input data for a Kage shader in the first place, with "invalid" alphas, being treated as data).

- This would help me in a project where I'm using 24 bits out of the 32 from r,g,b,a to encode more data
- This could for example help @solarlune achieve more precision in tetra3D's depth buffer by using 32bits instead of 24 (https://github.com/SolarLune/tetra3d/blob/v0.14.0/camera.go#L117)

**Comment by SolarLune** [comment]
I think I'm not using the alpha channel because I actually need it for rendering, not because of color multiplication, but I think it'd still be useful to output non-alpha premultiplied colors in some circumstances.

**Comment by hajimehoshi** [comment]
@Zyko0  I thought this works as you intended (sorry if not), but is your request documentation?

**Comment by Zyko0** [comment]
> I thought this works as you intended (sorry if not), but is your request documentation?

Yes it does, I was just concerned if that part of the API could remain that way: `At`, `Set`, `WritePixels` and the result of a custom kage shader can produce non-premultiplied alpha colors without an internal transformation by ebitengine.

That's the current state (which I appreciate), and just wanted to know if it was reliable and wouldn't change in the future!
