### ISSUE TITLE
How to print texts (not for debugging) with specified position, color on the screen?

### ISSUE THREAD

**Issue by YamiOdymel** [hajimehoshi/ebiten#280]
In _Lua Player_ I can do things like this:

```lua
-- Defines the color of the text
red = Color.new(255, 0, 0)
-- The position of the text
x = 200
y = 100

-- Print the text on the screen
screen:print(x, y, "Look! I made text appear!", red)
```

But I have no idea how do I implement it with Ebiten, 

I know that there's an `ebitenutil.DebugPrint` but it's used for Debugging, 

what I wanted is to print a game message.

&nbsp; 

By the way, is it possible to take your time to write a **fully tutorial** instead of a documentation?

Just a suggestion because it's hard for me to learn things about Ebiten with examples and the documentation, 

not trying to forcing you but Ebiten is the best 2D game engine so far in Golang, so I don't want to miss this game engine, thanks.

**Comment by hajimehoshi** [comment]
> But I have no idea how do I implement it with Ebiten,

I have no idea about Lua binding, but I suggest ['font' example](https://github.com/hajimehoshi/ebiten/tree/master/examples/font) to learn how to draw texts on the screen.

> not trying to forcing you but Ebiten is the best 2D game engine so far in Golang, so I don't want to miss this game engine, thanks.

Thank you for saying that! Yeah, I understand tutorial is required whichever it'd be full or not, but am not sure what kind of tutorial is demanded. Games vary and tutorial for shooting game wouldn't be useful for role-playing game tutorial. In your words "fully tutorial", what kind of game did you mean?

BTW, I think API usage itself is not so difficult if you understand very basic linear-algebra (for geometry/color matrices).

**Comment by YamiOdymel** [comment]
Sorry for my first question that might be misleading you, I'll make a real example here.

![2016-10-23 8 23 55](https://cloud.githubusercontent.com/assets/7308718/19626200/ab04546c-995e-11e6-9e5a-a1657e5c43aa.png)

```go
ebitenutil.DebugPrint(screen, "Hello Ebiten!")
```

Looks great! But how do I print the text with the **color**, or **change the position**? (_this is a fake screenshot_)

![2016-10-23 8 23 552](https://cloud.githubusercontent.com/assets/7308718/19626297/a47848b8-9960-11e6-85df-1aa4225063f9.png)

Is there any function like this?

```go
x1, y1 := 0, 100
x2, y2 := 10, 120
red    := color.RGBA{0xff, 0x00, 0x00, 0xff}

ebite.Print(screen, x1, y1, "Hello Ebiten!")
ebite.Print(screen, x2, y2, "Hello Ebiten!", red)
```

---

Here's the example about how might the tutorial look like (and of course it's my _opinion_), it might seems stupid but useful for a newbie who's the first time play with Ebiten.

> 1. Prepare to write your first game with Ebiten!
  1. Create a color
  2. Print the text to your screen
  3. Load the custom fonts
2.  Let the keyboard works for you
  1. Keyboard mapping
  2. Gamepad also supports!
3. Use the images
  1. Load the image
  2. Display the image
  3. Get the width or the height of the image
  4. Image effects
4. Play with the audio
5. ...
6. Examples
   1. ...

As you see those are kind of the basic things that might even makes you wondering _why making such tutorial._ A tutorial actually tells people **how**, **why** and **what can Ebiten do**, **three things in the same time**, which makes people **more impressive**.

I actually wrote a post about "_how to write `Hello, world` with Ebiten_", and some of my friends saw the post, they **start to having some interest with Ebiten**, so I would like to make more tutorials about Ebiten, and I hoping that there can be a tutorial for Ebiten, please make a tutorial in your free time if you planned to do it, because a tutorial might takes a lot of time to make. 

I might be a little verbose but it's fun to play with Ebiten, thanks for making such great game library 😊

**Comment by hajimehoshi** [comment]
> Looks great! But how do I print the text with the color, or change the position? (this is a fake screenshot)
> Is there any function like this?

Unfortunately, there is no such function. You can draw a text on a temporary image, and draw it on the final destination with adjusted color matrix (or, you could use CompositionMode with colored image). Yeah, maybe this kind of know-how should be explained in some documentation!

As for DebugPrint, I don't think we need to specify color for debug texts.

> Here's the example about how might the tutorial look like (and of course it's my opinion), it might seems stupid but useful for a newbie who's the first time play with Ebiten.

Ah, I understood. I agree such documentation is very important for newbies. A user would want to know how to use the API when they find what they want with Ebiten.

> As you see those are kind of the basic things that might even makes you wondering why making such tutorial. A tutorial actually tells people how, why and what can Ebiten do, three things in the same time (But documentation doesnt.), which can makes people more impressive with the usage, and after people know how to use Ebiten, they can start to make their own thing.
>
> I actually wrote a post about "how to write Hello, world with Ebiten", and some of my friends saw the post, they start to having some interest with Ebiten, so I would like to make more tutorials about Ebiten, and I hoping that there can be a tutorial for Ebiten, please make a tutorial in your free time if you planned to do it, because a tutorial might takes a lot of time to make.

Sounds great! Well, you can share your tutorial on [Wiki](https://github.com/hajimehoshi/ebiten/wiki)! I think everyone can edit the wiki. I'd appreciate if you could do that. Of course I would add and improve the articles.

> I might be a little verbose but it's fun to play with Ebiten, thanks for making such great game library 😊

No problem. I'm pretty glad to know that. Thank you for using Ebiten!
