### ISSUE TITLE
Kage: Using screen position to sample an image in DrawTrianglesShader() calls offsets the sample incorrectly

### ISSUE THREAD

**Issue by SolarLune** [hajimehoshi/ebiten#2811]
### Ebitengine Version

2.6.2

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.3

### What steps will reproduce the problem?

Run this reproducible test case:

```go

package main

import (
	"errors"
	"fmt"
	"image/color"
	"math/rand"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/inpututil"
)

type Game struct {
	Shader      *ebiten.Shader
	Texture     *ebiten.Image // We don't actually use this texture, but it gets on the internal atlas
	Texture2    *ebiten.Image
	UsingShader bool
}

func NewGame() *Game {

	shaderText := `
	
	package main
	
	//kage:unit pixels

	func Fragment(dstPos vec4, srcPos vec2, color vec4) vec4 {
		return imageSrc1At(dstPos.xy) // This doesn't work
		// return imageSrc1At(dstPos.xy + imageSrc1Origin()) // This also doesn't work
		// return imageSrc1At(dstPos.xy + imageSrc0Origin()) // This, however, does work
	}
	
	`

	shader, err := ebiten.NewShader([]byte(shaderText))

	if err != nil {
		panic(err)
	}

	texture := ebiten.NewImage(100, 100)

	for y := 0; y < texture.Bounds().Dy(); y++ {
		for x := 0; x < texture.Bounds().Dx(); x++ {
			texture.Set(x, y, color.RGBA{
				R: uint8(rand.Intn(256)),
				G: uint8(rand.Intn(256)),
				B: uint8(rand.Intn(256)),
				A: 255,
			})
		}
	}

	texture2 := ebiten.NewImageFromImage(texture)

	return &Game{
		Shader:   shader,
		Texture:  texture,
		Texture2: texture2,
	}
}

func (g *Game) Update() error {

	if ebiten.IsKeyPressed(ebiten.KeyEscape) {
		return errors.New("quit")
	}

	if inpututil.IsKeyJustPressed(ebiten.KeySpace) {
		g.UsingShader = !g.UsingShader
		if g.UsingShader {
			fmt.Println("Drawing using the shader.")
		} else {
			fmt.Println("Not drawing using the shader.")
		}
	}

	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {

	if g.UsingShader {

		screen.DrawTrianglesShader(
			[]ebiten.Vertex{
				{DstX: 0, DstY: 0},
				{DstX: 100, DstY: 0},
				{DstX: 100, DstY: 100},
				{DstX: 0, DstY: 100},
			},
			[]uint16{
				0, 1, 2,
				2, 3, 0,
			},
			g.Shader,
			&ebiten.DrawTrianglesShaderOptions{
				Images: [4]*ebiten.Image{
					g.Texture,
					g.Texture2,
				},
			},
		)

	} else {

		screen.DrawImage(g.Texture, nil)

	}

}

func (game *Game) Layout(w, h int) (int, int) { return 320, 240 }

func main() {

	ebiten.RunGame(NewGame())

}


```

When it starts, you'll see a multi-colored static-y square at the top-left of the window; it's being drawn with `Image.DrawImage`. Pressing space will instead render that texture as an input through an `Image.DrawTrianglesShader()` call.

### What is the expected result?

Because the shader simply samples the given texture and draws it using the screen position of the fragment, drawing the texture through a shader shouldn't really do anything visibly. It should be the same, either rendering through `DrawTrianglesShader()` or `DrawImage()`.

### What happens instead?

When you press space, instead, the texture either offsets to the right by about 4 pixels or so (if the shader is left in its default state), offsets and then disappears (if the second returning line is uncommented instead of the first one) or appears correctly if the last option is uncommented.

**Comment by SolarLune** [comment]
Ah, the issue was resolved by @Zyko0 - needed to add in the origin of the texture on the underlying atlas.

**Comment by SolarLune** [comment]
OK, false alarm on closing it; there is a bug here, but it arises if you use multiple input textures. I've updated the first post with the problematic code.

**Comment by hajimehoshi** [comment]
> `return imageSrc1At(dstPos.xy)`

This should be `return imageSrc1At(srcPos.xy)`.

**Comment by hajimehoshi** [comment]
Or, is this your intention?

```go
return imageSrc1At(dstPos.xy - imageDstOrigin() + imageSrc0Origin())
```

**Comment by SolarLune** [comment]
`return imageSrc1At(dstPos.xy - imageDstOrigin() + imageSrc0Origin())`

This works and is what I'm looking for. Thanks~
