### ISSUE TITLE
example/drag: significant delay of a sprite move with Metal

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2822]
### Ebitengine Version

f6ffd86ca82ef6f9b25d25293750b31a3461ccf0

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.21.1 darwin/amd64

### What steps will reproduce the problem?

1. Run `examples/drag`
2. Drag a sprite quickly

### What is the expected result?

The sprite keeps up with the cursor position

### What happens instead?

The sprite failed to keep up with the cursor position.

https://github.com/hajimehoshi/ebiten/assets/16950/23be3eee-ce1c-4fe0-93f2-bc871db18321

### Anything else you feel useful to add?

OpenGL also has a similar delay, but this is much smaller.

https://github.com/hajimehoshi/ebiten/assets/16950/aeee0789-3ab3-4861-80fb-f5c913f1bd3a

I have not tested DirectX yet.

Handling events (#1704) didn't improve this situation significantly.

**Comment by hajimehoshi** [comment]
I found that asynchronous rendering (#2664) caused delays. 

![image](https://github.com/hajimehoshi/ebiten/assets/16950/28de9651-fc4c-4497-850e-06fed5282ab1)

From the above figure, the time lag between the game's updatings and the rendering is increased in theory, and apparently this actually happened.

I'll disable this when vsync is on.

**Comment by hajimehoshi** [comment]
Now the situation with Metal was quite improved. Windows has a similar issue with both OpenGL and DirectX, but the delay seems almost the same as the current Metal.

An experimental implementation to handle events (#1704) didn't solve this issue.

Apparently disabling vsync improved the delay very much. For GUI applications or some special game applications, disabling vsync would be an option to suppress delays.

**Comment by hajimehoshi** [comment]
Reopen this. "2" didn't work well with fullscreen.

**Comment by hajimehoshi** [comment]
> Apparently disabling vsync improved the delay very much. For GUI applications or some special game applications, disabling vsync (+ SetScreenClearedEveryFrame(false)) would be an option to suppress delays.

This conclustion is not changed.

**Comment by philhassey** [comment]
I've observed this problem quite a bit on my MacBook Air M1 2020.  So I always run my games with OpenGL.

This is a screenshot from the drag demo running on my external monitor.  I wonder if the FPS is a contributor to the problem?  As you can see in the examples below, the metal FPS is always lower than the OpenGL FPS.

```
External monitor, Metal:
EBITENGINE_GRAPHICS_LIBRARY=metal go run .
```
<img width="640" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/1282d5b0-2b07-42b4-bdc3-c9d60a7ad2f6">

```
External monitor, OpenGL:
EBITENGINE_GRAPHICS_LIBRARY=opengl go run .
```
<img width="640" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/eecda36e-f960-42e7-9b2b-957f7690441c">

When I run it on my laptops built in screen, I can still see the drag issue, but it's not nearly as obvious.
```
Builtin screen, Metal:
EBITENGINE_GRAPHICS_LIBRARY=metal go run .
```
<img width="640" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/aa166ada-8b46-4015-aedb-e159e79745a0">

```
Builtin screen, OpenGL:
EBITENGINE_GRAPHICS_LIBRARY=opengl go run .
```
<img width="635" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/4fb32ccb-2240-418c-8ea3-bc262a1dc78e">

The only change I made to the drag example was to replace the Debug info with one that includes the ActualFPS and ActualTPS.

```
% git rev-parse HEAD   
6cdabf09d1ef3d04933c7a707f05a0339961a9d3

-       ebitenutil.DebugPrint(screen, "Drag & Drop the sprites!")
+       // ebitenutil.DebugPrint(screen, "Drag & Drop the sprites!")
+       msg := fmt.Sprintf("ActualFPS: %0.2f\nActualTPS: %0.2f", ebiten.ActualFPS(), ebiten.ActualTPS())
+       ebitenutil.DebugPrint(screen, msg)
```

As suggested, I also tried without VSYNC enabled.  This made the drag feel perfect for openGL, but I don't necessarily want my game running at an insanely high FPS.  For metal, it started out with a high FPS (400) but quickly dropped down to 30, making the drag feel bad again.

```
External monitor, Metal, With VSYNC enabled:
EBITENGINE_GRAPHICS_LIBRARY=meta go run .
```
<img width="638" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/e0a4fa8c-3f0c-424d-aa3b-e7b2a659eebe">


```
External monitor, OpenGL, With VSYNC enabled:
EBITENGINE_GRAPHICS_LIBRARY=opengl go run .
```
<img width="638" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/723344/52cfb23b-d9ca-4932-8ac5-2ffc4196adf1">

I hope this helps a bit.  Thanks for Ebitengine!

**Comment by hajimehoshi** [comment]
@philhassey Which version of Ebitengine have you tested?

**Comment by hajimehoshi** [comment]
Well, I've sometimes noticed FPS is unstable with Metal (more unstanble than OpenGL, as we see), and the behavior is often flaky so I'm confused how to fix this issue. Especially if this happens with an external monitor, this is quite hard to reproduce this in my environment.

**Comment by philhassey** [comment]
The version I was using was a clone from today off this hash:
```
% git rev-parse HEAD   
6cdabf09d1ef3d04933c7a707f05a0339961a9d3
```

I've seen this in practice for the last few months since I started using Ebiten (~November 2023.) 

I think the external display only makes it more obvious, so not required to reproduce. 

On the built-in laptop screen, you can see in my tests `Builtin screen, Metal:` and `Builtin screen, OpenGL:` that the FPS in OpenGL is 120hz, whereas with Metal it's 60hz.  My guess is that the lower the FPS, the less "fresh" the events are that my game is fed before drawing the screen.  By having a higher FPS in OpenGL, it looks that much more up-to-date.  

With my external monitor (which is running at 30hz as per the Display settings on the Mac), this becomes very obvious.  It almost seems like a bug that OpenGL runs at 90hz on my external display.  However, since that makes the event handling work better, it accidentally fixes it.

That's my guess anyways!  If you want me to try it out on a specific version of Ebiten, I'm glad to do whatever.

**Comment by hajimehoshi** [comment]
I failed to reproduce 60 FPS w/ Metal in my MacBook M3 Pro.

![image](https://github.com/hajimehoshi/ebiten/assets/16950/eb7308d0-8b64-4165-9628-a639c973ddbd)

Actually FPS heavily depends on whether the application window is focused or not. When unfocused, the FPS dropped to 60.

**Comment by philhassey** [comment]
Thanks for checking it out.  Could be just an early M1 issue.  

Did you notice if  
```
	ebiten.SetVsyncEnabled(false)
```
was effective when using Metal?

On my machine the FPS would spike to 400 or so then drop down after about 30 seconds to whatever the screen's FPS was (60 or 30 on mine.). 

I also found that if I changed `ebiten.SetTPS(240)` the behavior was a bit stranger, never really settling anywhere, but FPS would vary wildly between 60 and 2000.

**Comment by hajimehoshi** [comment]
> Did you notice if [...] was effective when using Metal?

Yes, this worked with 500-1000 FPS. I confirmed this with `examples/windowsize` and pressing V. This worked even after 30 seconds.

**Comment by hajimehoshi** [comment]
Could you file your issue as a new issue? Unstable FPS seems a different issue than this. Thanks,

**Comment by philhassey** [comment]
Filed issue https://github.com/hajimehoshi/ebiten/issues/2931
