### ISSUE TITLE
Marshaling and Unmarshaling json and data structures

### ISSUE THREAD

**Issue by Esa824** [hajimehoshi/ebiten#2823]
### Ebitengine Version

v2.6.2

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.21.2 linux/amd64

### What steps will reproduce the problem?

When I marshal a populated data structure into bytes. Then I log the string version into a file it prints {}. I also send it to my server. I then check my server and it also has {}. And when I unmarshal it also gives me {} because of the marshaling the unmarshaling also fails.

### What is the expected result?

It is supposed to print and unmarshal and marshal correctly.

### What happens instead?

The result is empty of the marshaling and unmarshaling.

**Comment by hajimehoshi** [comment]
This is out of Ebitengine's scope.

**Comment by Esa824** [comment]
Okay

**Comment by Esa824** [comment]
Never mind I figured it out
