### ISSUE TITLE
exp/textinput: easier API to handle IME states

### ISSUE THREAD

**Issue by bjorndm** [hajimehoshi/ebiten#2827]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### What feature would you like to be added?

Support for the Kanji key on a Japanese keyboard. 

### Why is this needed?

To toggle the Japanese input method more easily. The exp/textinput package works well on macOS, but it's difficult to decide when to call Start(). Support for the Kanji key would be useful to be able to start the input method more conveniently.

**Comment by hajimehoshi** [comment]
See #2735 #2736

**Comment by hajimehoshi** [comment]
> Support for the Kanji key on a Japanese keyboard.

I'm not sure what supporting Kanji keys here. Doesn't `examples/textinput` work as you expected on macOS?

**Comment by bjorndm** [comment]
Sorry I mistook the name, I'm talking about the Japanese Language input keys. It would be nice if we could detect key presses and releases of those as Keys. 

https://en.wikipedia.org/wiki/Language_input_keys 

The example is working well, but in my own code I am reading the channel in a goroutine, using a for loop and that seems to cause some problems. Or maybe I'm not using the close() function correctly.

**Comment by hajimehoshi** [comment]
OK so what you want is easier APIs to treat IMEs (as the example already works as you expected), rather than handling some specific keys, right?

**Comment by bjorndm** [comment]
Yes, I guess so. I'm writing a  GUI with ebitengine and the current API, while it works, is a bit complicated to use correctly. 

Looking at the code of the example, it seems like now I have to call textinput.Start(x, y) on every Game.Update, and then read all state events while focused. It seems easier if the channel could be kept open while the IME is active. 

Also it seems like once the IME is started, ebiten.AppendInputChars stops working correctly, even if you call close() to close the IME, or also when I switch between input languages.

**Comment by bjorndm** [comment]
Another problem is the handling of the DEL key, is returns a State with a single DEL character in it on MacOSX. Backspace doesn't return a state with a DEL in it. On the example, if you type DEL, you'll get a "space".

**Comment by bjorndm** [comment]
Thanks for implementing this!
