### ISSUE TITLE
doc: Write tutorials

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#283]
See #280

**Comment by hajimehoshi** [comment]
I'll write a doc at the Wiki when I find my time, but contributions are always welcome!

**Comment by YamiOdymel** [comment]
I'll also add some basic tutorials once I've got the time 😊.

**Comment by hajimehoshi** [comment]
Thank you for writing https://github.com/hajimehoshi/ebiten/wiki/Your-first-game-in-Ebiten! That's amazing! I have fixed some sentences and might change the URL later, but you don't have to care.

**Comment by hajimehoshi** [comment]
I couldn't understand the sentences below:

> Anything in the game is always being updating (or refreshing). Sometimes you can hear people talking about FPS, which means frames per second. We would have to clean the previous screen and refresh the screen each time we move an element like an image, so the element won't leave a long track on the screen like a snake 🐍.

This means that FPS means frames per second, and a frame is a place where elements like images are rendered, and if you render those elements at same positions, those elements would stick to the screen, right?

> If we want to display a text on the screen, it will be disappeared before we see it. Why? Because we don't keep it on the screen to do this, we'll need to call update() function per frame, then put our code inside of the function, so the text will keep on the screen.

In what kind of situation is the text disappeared? (At least, this never happens when you use Ebiten).

(Note that I have fixed some details)

**Comment by YamiOdymel** [comment]
Oops, I think that I just brought my old thoughts from Lua Player to Ebiten before I tried more with Ebiten, I'm really sorry for that.

> This means that FPS means frames per second, and a frame is a place where elements like images are rendered, and if you render those elements at same positions, those elements would stick to the screen, right?

The render system of Lua Player is a little bit different with Ebiten, In Lua Player you would have to **clean the previous screen** in the `update()` function **manually** (_but it seems Ebiten did this automatically?_), **otherwise the old screen will still be displayed on the screen**, I drew a picture about how this part works in Lua Player, hope you understand:

![23123](https://cloud.githubusercontent.com/assets/7308718/19689224/38881318-9aff-11e6-9d76-05cdbe7ea50b.png)

And since user can print the text **from the outside** of the `update()` function in _Lua Player_, the text will be cleaned very soon (because we didn't keep it on the screen), this is what I'm trying to explain in Wiki but I think that I just mixed Lua Player and Ebiten together makes it harder to explain, I'm so sorry for that, also thanks for your correction.

**Comment by hajimehoshi** [comment]
Thank you for explanation. I have just removed those 2 paragraphs. Explanation about FPS might be required later here. BTW, are you developing Lua biding of Ebiten?

**Comment by YamiOdymel** [comment]
Excuse me, what do you mean by "_biding of_"?

**Comment by hajimehoshi** [comment]
Oops, s/biding/binding/

**Comment by YamiOdymel** [comment]
I'm not sure if this answers your question, 

but, no, I wrote things with Lua like 5 years ago 😔. 

I'm developing web applications nowadays, 

just wondering if there's any 2D game engine in Golang, then I found Ebiten.

**Comment by hajimehoshi** [comment]
Oh I see, I was misunderstanding. It seems like your Lua programming has nothing to do with Ebiten :-)

**Comment by hajimehoshi** [comment]
Thank you for writing great documents!

https://github.com/hajimehoshi/ebiten/wiki/Screen,-colors-and-the-squares
The content is perfect! I'm afraid I've removed most of emphasis using `**`.

BTW,

> how you named the variables, just remember you can only name the variables with alphanumeric.

That's not true. You can name a variable with Kanji like 海老天. https://play.golang.org/p/uGqNqQUXzD

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/wiki/Handles-the-user-inputs is also great! AFAIK, PlayStation 3 controller doesn't work with Windows without installing a driver. Do you assume the platform is macOS in the document?

**Comment by YamiOdymel** [comment]
Yeah, I skip the part because that might be long enough to write it in another tutorial (and since my computer _exploded_, I don't really use Windows much).

I'm also thank you that you always point out my problems, which really helps me alot. 😃 

> That's not true. You can name a variable with Kanji like 海老天. https://play.golang.org/p/uGqNqQUXzD

**Comment by hajimehoshi** [comment]
https://gobyexample.com/ would be a good format.

**Comment by hajimehoshi** [comment]
https://star.one/ebiten.pdf I've written a book about Ebiten in Japanese and tried to translate them in English, but I think it would take much long time. Let me delete the milestone on this issue.

**Comment by hajimehoshi** [comment]
Though this is a very important task, there is no concrete goal. Close this once.
