### ISSUE TITLE
Rename `ebiten.Image` to `ebiten.Canvas`?

### ISSUE THREAD

**Issue by YamiOdymel** [hajimehoshi/ebiten#284]
It's a suggestion, but I'll explain why.

At the first time I have touched with Ebiten, I thought that `Image` is a **Picture**, but I realized it's actually something like a `screen` or `canvas`, it might confuses people when you called it as an `Image`.

So I suggest to rename it to `Canvas`(like how HTML5 did), so you can tell everyone that **everything on the screen is a `Canvas` (_but not an image_)**.

For another point:

* `screen.DrawImage(ebitenImage, op)` sounds like "**To draw a picture on the screen**".

If we changed it to `canvas`, it might sounds better like `screen.DrawCanvas(ebitenCanvas, op)`, `ebitenCanvas.Size()` it fits for most of the time and gets more semantics.

It's like the issue of #29.

**Comment by hajimehoshi** [comment]
Thank you for suggestion!

I agree the name Image is a little abstract. It is true that ebiten.Image is an image, but it might be hard to image ebiten.Image can also be a render target.

IMHO, ebiten.Image is not a bad name. This is a little abstract, but not wrong. Canvas might be a good candidate but creating a 'canvas' from an image file looks a little odd to me. In the first place, it is impossible to change the struct name in terms of backward compatibility.

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen this.
