### ISSUE TITLE
Kage: kage considers variable unused when it's used for assigning value to array

### ISSUE THREAD

**Issue by imprity** [hajimehoshi/ebiten#2848]
### Ebitengine Version

v2.6.2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.21.0

### What steps will reproduce the problem?

When compling shader code, kage thinks that local variable is unused even though it's used for assigning value to array.

Here's the code for reproducing the error.

```
package main

import (
	"github.com/hajimehoshi/ebiten/v2"
	"log"
)

const (
	ScreenWidth  = 600
	ScreenHeight = 600
)

const ShaderCode = `
package main

func Fragment(position vec4, texCoord vec2, color vec4) vec4{
	var randomMatrix [5]float

	for x:=-2; x<=2; x++{
		//kage thinks that i is unused even though it's not
		i := x + 2 
		randomMatrix[i] = float(x)
	}

	var sum float = 0.0

	for x:=-2; x<=2; x++{
		//j is fine though
		j := x + 2
		sum += randomMatrix[j]
	}

	return vec4(0)
}
`

var Shader *ebiten.Shader

type Game struct {}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	shaderOp := &ebiten.DrawRectShaderOptions{}
	screen.DrawRectShader(ScreenWidth, ScreenHeight, Shader, shaderOp)
}

func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return ScreenWidth, ScreenHeight
}

func main() {
	var err error

	if Shader, err =  ebiten.NewShader([]byte(ShaderCode)); err != nil{
		log.Fatal(err)
	}

	ebiten.SetWindowSize(ScreenWidth, ScreenHeight)
	ebiten.SetWindowTitle("Cool Window")
	if err := ebiten.RunGame(&Game{}); err != nil {
		log.Fatal(err)
	}
}
```

At line 23, even though i is being used for indexing array, Kage thinks it's unused. And outputs this error :
`local variable i is not used`

### What is the expected result?

I think it should be compiled. ❤️ 

### What happens instead?

It refused to compile. 😢

**Comment by imprity** [comment]
I'm not sure if it's the fix And I haven't tested it yet since I'm very new to open source projects,

But I think the fix is changing one line

in `internal\shader\expr.go:890`

change this
`exprs, _, ss, ok := cs.parseExpr(block, fname, e.Index, markLocalVariableUsed)`
to
`exprs, _, ss, ok := cs.parseExpr(block, fname, e.Index, true)`

When checking left hand side, markLocalVariableUsed is set to false, but I think it should be always marked as used since values are used for indexing.

I might be wrong but I hope this helps.

**Comment by hajimehoshi** [comment]
Thanks! I'll take a look.

**Comment by hajimehoshi** [comment]
> But I think the fix is changing one line

You are correct, thank you!

Usually, I don't backport the fix for shaders to the stable branch 2.6. However, if you want it, I'm fine to do it.

**Comment by imprity** [comment]
I think it would be really cool if it's backproted to 2.6!

Thanks!

**Comment by hajimehoshi** [comment]
Cherry-picked. I'll add a tag v2.6.3 few days later. If you are in hurry, use the commit hash tag directly:

```
go get github.com/hajimehoshi/ebiten/v2@2c967dd24e63b388479c71f2648418c14f7b94b7
```
