### ISSUE TITLE
internal/graphicsdriver/directx: add an option to prevent tearing even when vsync is off on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2858]
### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Now tearing can happen when vsync is off on Windows (https://github.com/hajimehoshi/ebiten/issues/2697), but would it be nice to have an option to prevent this? Especially when we create a GUI application, we might want to disable vsync to make the application more responsive. In this case, we want to suppress tearing. Without tearing, some machines might not work with vsync disabled, but this should not be critical.

**Comment by tinne26** [comment]
Context for everyone except Hajime: this refers to the "mailbox" presentation model. Vulkan has a good explicit API that showcases all the main presentation modes: https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPresentModeKHR.html. wgpu also has a good API that exposes the same options more or less but relies heavily on fallbacks for the unavailable modes: <https://docs.rs/wgpu/latest/wgpu/enum.PresentMode.html>.  Ideally, "mailbox" would be supported by all the graphical APIs, but neither OpenGL nor Metal seem to support it. If it was actually supported everywhere, an explicit model directly matching Vulkan's would probably be preferable on Ebitengine's API.

**Comment by hajimehoshi** [comment]
I'm not talking about the mailbox thing?

**Comment by hajimehoshi** [comment]
If vsync is off and tearing is off, an application might work in a mailbox mode, but this might not do. (e.g. On Parallels, this works with 2 buffers IIUC. I don't know which mode is used TBH)

**Comment by tinne26** [comment]
Hmm, so what's the IDXGISwapChain configuration then? I understand this doesn't map to any VkPresentModeKHR then?

**Comment by hajimehoshi** [comment]
See also https://github.com/hajimehoshi/ebiten/issues/2697

Now tearing is enabled for higher FPS (https://github.com/hajimehoshi/ebiten/commit/6f41a05264ffdb84f50cf42f90e2c0e613eb0f06), but this might not be good for GUI applications that disables vsync. I think I'll go with tearing disabled by default, and add an option to enable this (probably EBITENGINE_DIRECTX env variable). /CC @Zyko0

**Comment by hajimehoshi** [comment]
With PowerShell, you can test this by:

```powershell
# Disallow tearing
go run .\examples\windowsize\ -vsync=false
# Allow tearing
& (Get-Process -Id $PID).Path { $env:EBITENGINE_DIRECTX="tearing"; go run .\examples\windowsize\ -vsync=false }
```

**Comment by hajimehoshi** [comment]
I decided to revert the change since

* I saw tearing on macOS when vsync=off
* In @Zyko0's environment,  tearing is not avoidable when vsync=off to get high FPS
* It's weird that DirectX provided an option to disallow tearing at the same time vsync is off, so we need more investigation
