### ISSUE TITLE
crash on macOS 13.6.1 (22G313) on M1 with panic: purego: fn is nil

### ISSUE THREAD

**Issue by prologic** [hajimehoshi/ebiten#2863]
### Ebitengine Version

latest

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.21.4 darwin/arm64

### What steps will reproduce the problem?

```
prologic@JamessMacStudio
Sat Dec 16 20:49:29
~/tmp/ebiten-games/snake-ebiten
 (main) 0
$ go build && ./snake-ebiten
panic: purego: fn is nil

goroutine 1 [running]:
github.com/ebitengine/purego.SyscallN(0x100eddc00?, {0x0?, 0x140003e40a0?, 0x1?})
	/Users/prologic/go/pkg/mod/github.com/ebitengine/purego@v0.0.0-20220829192423-0acfce66fb4a/syscall.go:29 +0xc4
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl.CreateSystemDefaultDevice()
	/Users/prologic/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0/internal/graphicsdriver/metal/mtl/mtl_darwin.go:553 +0x30
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal.init.0()
	/Users/prologic/go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.4.0/internal/graphicsdriver/metal/graphics_darwin.go:336 +0x1c
```

### What is the expected result?

This used to work on my Intel iMac

### What happens instead?

See above

**Comment by hajimehoshi** [comment]
Does this happen with the latest Ebitengine v2.6.3?

**Comment by prologic** [comment]
I _believe_ that's what's being compie,d against:

```
$ sift ebiten go.mod
1:module github.com/anilkonac/snake-ebiten
6:	github.com/hajimehoshi/ebiten/v2 v2.6.3
11:	github.com/ebitengine/oto/v3 v3.1.0 // indirect
12:	github.com/ebitengine/purego v0.5.1 // indirect

```

**Comment by hajimehoshi** [comment]
The stacktrace shows `v2.4.0`.

**Comment by hajimehoshi** [comment]
https://github.com/anilkonac/snake-ebiten/blob/d12af054574eb98b19d73924ca43106507db87c1/go.mod This seems v2.4.0

**Comment by hajimehoshi** [comment]
If this still happens with the latest Ebitengine, please let me know.
