### ISSUE TITLE
Gamepad button IDs are incorrect on macOS native

### ISSUE THREAD

**Issue by YamiOdymel** [hajimehoshi/ebiten#287]
**macOS version**: Sierra 10.12.1

When was I using my **PlayStation 3 Controller** on **Google Chrome**, key map **works perfectly fine**. (Like the following picture).

![normal](https://cloud.githubusercontent.com/assets/7308718/19827547/7de9f6d6-9de0-11e6-8ce6-a40a36cd6e1d.png)

But when I compiled the example on my **macOS** and execute it, the key map is **wrong**:

![osx unormal](https://cloud.githubusercontent.com/assets/7308718/19827548/80a715f2-9de0-11e6-990f-92e03cb371ab.png)

I'm not sure if this is the system problem or Ebiten's issue.

**Comment by hajimehoshi** [comment]
Thank you for reporting.

Would you test your game pad with http://html5gamepad.com/ ? Some browsers can return different key maps unfortunately.

**Comment by YamiOdymel** [comment]
macOS with **Firefox** and **macOS native**:

![osx unormal](https://cloud.githubusercontent.com/assets/7308718/19828327/96a98e74-9df5-11e6-99ea-0c51f72b0d98.png)

macOS with **Google Chrome**:

![normal](https://cloud.githubusercontent.com/assets/7308718/19828328/9b76a0d6-9df5-11e6-9687-fe83f395dbcb.png)

Thanks for the notice that I don't know even different browsers return the different results.

**Comment by hajimehoshi** [comment]
Yeah, and Ebiten just uses the returned keys and doesn't care what they actually are. I think it is almost impossible for Ebiten to care this. Implementing key configuration feature in your game would work.
