### ISSUE TITLE
an option to specify color space for macOS and iOS

### ISSUE THREAD

**Issue by mjbartholomew** [hajimehoshi/ebiten#2871]
### Ebitengine Version

2.6.3

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.21.5 darwin/amd64

### What steps will reproduce the problem?

Explicitly define the screen color via ebiten.Image.Fill()

```go
func (g *Game) Draw(screen *ebiten.Image) {
    screen.Fill(color.RGBA{0x3b, 0x90, 0x30, 0xff})
}
```

As can be seen in the image under the **"What happens instead?"** section, it also impacts colors defined by images.

### What is the expected result?

The expected result would be that the colors would appear the same in the app's window as they do in other applications (like Chrome, Safari, Slate, Preview)

### What happens instead?

The colors are rendered differently. Using the Digital Color Meter on macOS, I can see that the color #3b9030 renders as expected in Safari, Chrome, Preview, and Slate, yet when displayed in an Ebitengine application window, I instead see #009219.

The top-half of the following image is from an app created with Ebitengine, whereas the bottom half is from the app Slate. As you can see, the colors are off when drawn by Ebitengine. Every channel (Red, Green, and Blue) have been altered, with the Red channel changing from 0x3b in the code to 0x00 on screen.

<img width="638" alt="Screenshot 2023-12-23 at 3 50 58 PM" src="https://github.com/hajimehoshi/ebiten/assets/16119136/2ec688a8-dff0-482a-8e71-66b3c0f657fc">

The brown block colors are also off, but just not as pronounced as can be seen with the green background color.

**Comment by hajimehoshi** [comment]
This is a difference of color space. Ebitengine uses [kCGColorSpaceDisplayP3](https://developer.apple.com/documentation/coregraphics/kcgcolorspacedisplayp3) and this might be different from other applications.

> The expected result would be that the colors would appear the same in the app's window as they do in other applications (like Chrome, Safari, Slate, Preview)

What about Firefox?

**Comment by mjbartholomew** [comment]
Firefox is the same as Chrome and Safari. Here is a screenshot of the browsers in the following order: Firefox, Chrome, and Safari.

<img width="1526" alt="Screenshot 2023-12-23 at 11 36 03 PM" src="https://github.com/hajimehoshi/ebiten/assets/16119136/1eb40662-28a7-447c-be47-1836b90bde9e">

The content of the test file is:
```html
<!DOCTYPE html>
<html>
    <head>
        <style>
            body {
                color: red;
                background-color: #3b9030;
            }
        </style>
    </head>
    <body></body>
</html>
```

All 3 of the browsers display the same color for #3b9030. Consulting the Digital Color Meter app, when I hover over the pixels in each of the browser windows, it displays the decimal equivalent for #3b9030.

<img width="449" alt="Digital Color Meter on Firefox" src="https://github.com/hajimehoshi/ebiten/assets/16119136/ba8ef1eb-8566-4045-84e5-0f293b358b15">

I wondered if colorspace played a part in this issue. I believe the browsers interpret CSS colors, as well as untagged images, as sRGB. Firefox [made changes in version 89](https://cameratico.com/color-management/firefox/) to follow this approach.

**Comment by hajimehoshi** [comment]
OK so the differences are color spaces, and now all the modern browsers now adopt sRGB by default.

I don't think this is a bug in Ebitengine. Ebitengine is not responsible to output colors that are compatible with other applications. 

Also, with OpenGL mode, there is no way to control color spaces and probably Display P3 is used. Ebitengine tries to emulate this with Metal for consistency. You can try it with `EBITENGINE_GRAPHICS_LIBRARY=opengl go run path/to/your/game`.

**Comment by mjbartholomew** [comment]
Using `EBITENGINE_GRAPHICS_LIBRARY=opengl go run path/to/your/game` made a difference, and the green color now renders correctly. Is there a way to bake this environment value into the binary? When I try `EBITENGINE_GRAPHICS_LIBRARY=opengl go build` the resulting binary still produces the unexpected colors.

Or is it possible to add an option in Ebitengine to use the sRGB color profile for macOS (e.g. [MTKView.colorPixelFormat = .bgra8Unorm_srgb](https://developer.apple.com/documentation/metalkit/mtkview/1535940-colorpixelformat))?

**Comment by mjbartholomew** [comment]
For those researching how to change the graphics library, you need to use `ebiten.RunGameWithOptions()` instead of `ebiten.RunGame()`

`ebiten.RunGameWithOptions()` has a second parameter, which takes a variable of type `RunGameOptions`. The following is an example of how to create that variable (in this case, named `op`), and make the change to the GraphicsLibrary value to select OpenGL. 

```
op := &ebiten.RunGameOptions{}
op.GraphicsLibrary = ebiten.GraphicsLibraryOpenGL
```

**Comment by hajimehoshi** [comment]
> Using EBITENGINE_GRAPHICS_LIBRARY=opengl go run path/to/your/game made a difference, and the green color now renders correctly.

That's odd. I got the same result with OpenGL and Metal. I'm using MacBook Pro 2020.

![image](https://github.com/hajimehoshi/ebiten/assets/16950/a7db2c7e-b906-4327-83a7-cc7958c03d59)

Also, the Metal version is not incorrect. This just uses a different color space than sRGB and some colors might not be able to be represented in sRGB.

**Comment by hajimehoshi** [comment]
> Or is it possible to add an option in Ebitengine to use the sRGB color profile for macOS (e.g. MTKView.colorPixelFormat = .bgra8Unorm_srgb)?

I can consider this if you want, but as I said, this is not controllable when OpenGL is used.

**Comment by mjbartholomew** [comment]
> > Or is it possible to add an option in Ebitengine to use the sRGB color profile for macOS (e.g. MTKView.colorPixelFormat = .bgra8Unorm_srgb)?
> 
> I can consider this if you want, but as I said, this is not controllable when OpenGL is used.

As OpenGL has been deprecated by Apple in favor of Metal, I would greatly appreciate it if you would consider adding that as an option.

**Comment by mjbartholomew** [comment]
> > Using EBITENGINE_GRAPHICS_LIBRARY=opengl go run path/to/your/game made a difference, and the green color now renders correctly.
> 
> That's odd. I got the same result with OpenGL and Metal. I'm using MacBook Pro 2020.

Here are the results I have on my 2018 Mac mini (EBITENGINE_GRAPHICS_LIBRARY=opengl on the right window):

<img width="269" alt="Screenshot 2023-12-24 at 2 40 38 AM" src="https://github.com/hajimehoshi/ebiten/assets/16119136/9e6f8fc6-22e2-4b8c-9ab7-7e912390b301">

**Comment by hajimehoshi** [comment]
# Metal

Use [`CAMetalLayer`'s `colorSpace` property](https://developer.apple.com/documentation/quartzcore/cametallayer/1478170-colorspace?language=objc). [Possible values](https://developer.apple.com/documentation/coregraphics/cgcolorspace/color_space_names) are:

- [kCGColorSpaceP3](https://developer.apple.com/documentation/coregraphics/kcgcolorspacedisplayp3) (the current default)
- [kCGColorSpaceSRGB](https://developer.apple.com/documentation/coregraphics/kcgcolorspacesrgb)
- [kCGColorSpaceLinearSRGB](https://developer.apple.com/documentation/coregraphics/kcgcolorspacelinearsrgb)
- etc.

# DirectX

(TBD)

# OpenGL

There is no way to specify a color space.

**Comment by hajimehoshi** [comment]
We need more investigation.

**Comment by hajimehoshi** [comment]
I failed to find a good solution for DirectX. Probably just ignoring the option would be fine.
