### ISSUE TITLE
wasm: handle onblur event to clear pressed keys set

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2874]
### Ebitengine Version

2.6.3

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go version go1.20.3 linux/amd64

### What steps will reproduce the problem?

- Run e.g. the game AAAAXY e.g. from https://rm.cloudns.org/aaaaxy/current/aaaaxy.html (not tried anything else, but I assume any input demo that uses `ebiten.IsKeyPressed` will work too).
- Have a second window open next to your browser.
- Make sure the game is not fullscreen (if needed, hit the F key to toggle).
- In the game, walk right by holding the right arrow key.
- While holding the right arrow key, move the mouse cursor to focus another window and possibly click if your environment requires that to switch focus.
- Release the right arrow key again.

### What is the expected result?

Player will stop moving. Even when focusing the game window again, the player will not move until the right arrow key is pressed again.

(Also, given I am not setting RunnableOnUnfocused to true, actually the game should pause in this state)

### What happens instead?

Player keeps moving right even when the window is unfocused and the right arrow key has been released. Pressing and releasing the right arrow key again fixes the situation.

### Anything else you feel useful to add?

Fun fact is, my son found this very bug on Scratch (not Ebitengine related), and I merely tried out similar steps in my game. Linux/X11 is not affected by the same bug - the game pauses, and when refocusing, the player stops walking.

I checked via debug console to verify that the `window.onblur` event is raised when focus switches to another window:

```
window.onblur = function() { console.debug('blur'); }
```

So Ebitengine should be able to use this mechanism to detect focus change and pause the game as well as clear input state.

**Comment by divVerent** [comment]
The GLFW code doing this is here: https://github.com/glfw/glfw/blob/master/src/window.c#L45

**Comment by divVerent** [comment]
Wait, I have runnableWhenUnfocused defaulting to true in my wasm build because "focus was not working" at the time. Changing that would make the game pause, but it will still not release all keys.

IMHO what we need is something like

```
func (u *UserInterface) update() error {
  // ...
  if !u.isFocused() {
    for k := range u.inputState.KeyPressed {
      u.inputState.KeyPressed[k] = false
    }
    for b := range u.inputState.MouseButtonPressed {
      u.inputState.MouseButtonPressed[b] = false
    }
    u.touchesInClient = u.touchesInClient[:0]
  }
}
```

But I am unsure if this is really the best approach - it reuses most existing logic though instead of adding event handlers, which may be good or bad here, no idea.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/2183

We have a similar issue even on desktops and I found there was not a good solution.

**Comment by hajimehoshi** [comment]
> IMHO what we need is something like

I guess this causes a situation where IsKeyPressed returns false though a key is still pressed.

**Comment by hajimehoshi** [comment]
>  https://rm.cloudns.org/aaaaxy/current/aaaaxy.html 

This doesn't seem to work any longer.

**Comment by divVerent** [comment]
Still works 100% fine for me - just be aware, it takes a while to load and I have not yet managed to find a way to show a progress bar or something.

**Comment by divVerent** [comment]
Issue also still reproduces: run my game while another tab is open. Hold right while pressing Ctrl-Tab. Release all keys, and switch back to the game's tab. Player is now moving right until you hit the right button.

**Comment by hajimehoshi** [comment]
I could reproduce the issue with examples/keyboard


https://github.com/hajimehoshi/ebiten/assets/16950/20d2fc1d-9f30-4d56-8faf-7c5c262018a5
