### ISSUE TITLE
GetWindowPosition reports incorrect position on X11 Gnome

### ISSUE THREAD

**Issue by airtonix** [hajimehoshi/ebiten#2876]
### Ebitengine Version

v2.6.3

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

v1.21.5

### What steps will reproduce the problem?

have linux
have gnome shell 40+
have two screens

in `settings > displays` arrange screens like: 

```
[ screen two ] [ screen one ]
```

now run https://github.com/airtonix/pixelclicker/tree/581c141c4524118f813931b1b8820702bc79f8c0

### What is the expected result?

that accumulative pixel coordinates respect defined monitor layout

### What happens instead?

i imagine it's just enumerating the attached monitors and just assuming a layout of : 

```
[ screen one ] [ screen two ]
```

### Anything else you feel useful to add?

[Screencast from 2023-12-29 14-32-24.webm](https://github.com/hajimehoshi/ebiten/assets/61225/81748bf3-84ed-42e2-a7ad-4b38243ebd32)

**Comment by airtonix** [comment]
nvm looks like i'm supposed to do something with the monitor bounds but i'm unable to access it

**Comment by hajimehoshi** [comment]
(0, 0) is alwasy the current monitor's left-upper, so this is expected.

**Comment by airtonix** [comment]
@hajimehoshi can we at least get this available? 

```
windowX, windowY := ebiten.WindowPosition()
screenX,screenY := ebiten.Monitor().Bounds()
```
