### ISSUE TITLE
ebiten.Monitor() doesn't allow accessing the Bounds so we can't work with custom screen layouts

### ISSUE THREAD

**Issue by airtonix** [hajimehoshi/ebiten#2877]
### Ebitengine Version

v2.6.3

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.5

### What steps will reproduce the problem?

see https://github.com/hajimehoshi/ebiten/discussions/1834

### What is the expected result?

 see https://github.com/hajimehoshi/ebiten/discussions/1834

### What happens instead?

 see https://github.com/hajimehoshi/ebiten/discussions/1834

### Anything else you feel useful to add?

what I'm trying to do: 

https://github.com/airtonix/pixelclicker/blob/581c141c4524118f813931b1b8820702bc79f8c0/app/ui/window.go#L401C2-L409C1

the thing i'd like exposed: 

https://github.com/hajimehoshi/ebiten/issues/2876#issuecomment-1871720085

**Comment by hajimehoshi** [comment]
See #2781
