### ISSUE TITLE
does not contain package github.com/hajimehoshi/ebiten/v2/text/v2

### ISSUE THREAD

**Issue by SadriShehu** [hajimehoshi/ebiten#2878]
### Ebitengine Version

v2.6.3

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.4

### What steps will reproduce the problem?

Try to use the package `github.com/hajimehoshi/ebiten/v2/text/v2`

### What is the expected result?

To be able to import it and use it in the project

### What happens instead?

```
github.com/hajimehoshi/ebiten/v2/text/v2: module github.com/hajimehoshi/ebiten/v2@latest found (v2.6.3), 
but does not contain package github.com/hajimehoshi/ebiten/v2/text/v2
```

**Comment by hajimehoshi** [comment]
text/v2 is not in v2.6 (the stable branch) yet

**Comment by abbychau** [comment]
which version should we use?

**Comment by hajimehoshi** [comment]
The main branch
