### ISSUE TITLE
internal/graphicsdriver/metal/mtl: test fails on MacBook M3 Pro

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2885]
### Ebitengine Version

f27402ee44196cd798d20ebd5fd230e290ce7d80

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.21.6 darwin/arm64

### What steps will reproduce the problem?

Run `go test ./internal/graphicsdriver/metal/mtl`

### What is the expected result?

The tests pass

### What happens instead?

```
2024/01/18 16:11:51 pipeline descriptor is nil
FAIL    github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/metal/mtl      0.167s
FAIL
```

### Anything else you feel useful to add?

The culprit is 59487e491ccf0cfac31db8f3f95288e7b06f4aee

**Comment by hajimehoshi** [comment]
[babd452e909b4f96f78751d5650aed286cd28117](https://github.com/ebitengine/purego/commit/babd452e909b4f96f78751d5650aed286cd28117) is the culprit

**Comment by hajimehoshi** [comment]
* [`MakeRenderPipelineState`](https://github.com/hajimehoshi/ebiten/blob/f27402ee44196cd798d20ebd5fd230e290ce7d80/internal/graphicsdriver/metal/mtl/mtl_darwin.go#L658-L684) started to fail with the latest purego.
* The test passes with `CGO_ENABLE=0` but not with `CGO_ENABLED=1`

@TotallyGamerJet Do you have any insights? Thanks,

**Comment by TotallyGamerJet** [comment]
My guess is that it's caused by Oto having a different version of purego

**Comment by TotallyGamerJet** [comment]
I just confirmed the issue is caused by [purego#197](https://github.com/ebitengine/purego/pull/197)

**Comment by hajimehoshi** [comment]
I'll try to make a minimized test case
