### ISSUE TITLE
Can NOT get the delta time between 2 frames.

### ISSUE THREAD

**Issue by Nigh** [hajimehoshi/ebiten#289]
I hope that there could be a way to get the delta time between frames in ebiten but not using the system function.

**Comment by hajimehoshi** [comment]
I was wondering why you don't want to use system functions.

**Comment by Nigh** [comment]
the code below works. but when the game paused because of focus losing on game window, it goes wrong... I don't know how to solve it now.

    func getDt() func() time.Duration {
    	lastUpdate := time.Now()
    	dt := time.Since(lastUpdate)
    	return func() time.Duration {
    		dt = time.Since(lastUpdate)
    		lastUpdate = time.Now()
    		return dt
    	}
    }
    
    var dt func() time.Duration = getDt()
    
    func update(screen *ebiten.Image) error {
    	fmt.Printf("%d\n", dt())
    	return nil
    }

**Comment by Nigh** [comment]
the code below works. but when the game paused because of focus losing on game window, it goes wrong... I don't know how to solve it now.

    func getDt() func() time.Duration {
    	lastUpdate := time.Now()
    	dt := time.Since(lastUpdate)
    	return func() time.Duration {
    		dt = time.Since(lastUpdate)
    		lastUpdate = time.Now()
    		return dt
    	}
    }
    
    var dt func() time.Duration = getDt()
    
    func update(screen *ebiten.Image) error {
    	fmt.Printf("%d\n", dt())
    	return nil
    }

**Comment by Nigh** [comment]
the code below works. but when the game paused because of focus losing on game window, it goes wrong... I don't know how to solve it now.

    func getDt() func() time.Duration {
    	lastUpdate := time.Now()
    	dt := time.Since(lastUpdate)
    	return func() time.Duration {
    		dt = time.Since(lastUpdate)
    		lastUpdate = time.Now()
    		return dt
    	}
    }
    
    var dt func() time.Duration = getDt()
    
    func update(screen *ebiten.Image) error {
    	fmt.Printf("%d\n", dt())
    	return nil
    }

**Comment by Nigh** [comment]
the code below works. but when the game paused because of focus losing on game window, it goes wrong... I don't know how to solve it now.

    func getDt() func() time.Duration {
    	lastUpdate := time.Now()
    	dt := time.Since(lastUpdate)
    	return func() time.Duration {
    		dt = time.Since(lastUpdate)
    		lastUpdate = time.Now()
    		return dt
    	}
    }
    
    var dt func() time.Duration = getDt()
    
    func update(screen *ebiten.Image) error {
    	fmt.Printf("%d\n", dt())
    	return nil
    }

**Comment by Nigh** [comment]
the code below works. but when the game paused because of focus losing on game window, it goes wrong... I don't know how to solve it now.

    func getDt() func() time.Duration {
    	lastUpdate := time.Now()
    	dt := time.Since(lastUpdate)
    	return func() time.Duration {
    		dt = time.Since(lastUpdate)
    		lastUpdate = time.Now()
    		return dt
    	}
    }
    
    var dt func() time.Duration = getDt()
    
    func update(screen *ebiten.Image) error {
    	fmt.Printf("%d\n", dt())
    	return nil
    }

**Comment by hajimehoshi** [comment]
In Ebiten, it is assured that `update` is called 60 times in one second. If you want to measure logical time, which means how long the game runs except for posing, you don't need even `time` package. Just count a frame and divide by 60.

```go
var frameCount = 0

func update(screen *ebiten.Image) {
}
```

**Comment by YamiOdymel** [comment]
@Nigh Could you please explain what happened for "it goes wrong"?

**Comment by YamiOdymel** [comment]
I implemented the DeltaTime (I'm not sure if this is called as `DeltaTime` as well) in `update()` function:

```go
func update(screen *ebiten.Image) error {
	newTime    = time.Now().UnixNano()
	deltaTime := float64(((newTime - oldTime) / 1000000)) * 0.001
	oldTime    = newTime

    // .... Code ....

    // Move the block based on DeltaTime
	x += speed * deltaTime
	y += speed * deltaTime

	return nil
}

func main() {
	oldTime = time.Now().UnixNano()
	speed = 50
	x = 64
	y = 64

	ebiten.Run(update, 320, 240, 2, "Hello world!")
}
```

And I think it goes pretty well and works fine?

![a](https://cloud.githubusercontent.com/assets/7308718/20003858/b2d1bebe-a2c3-11e6-809c-8d75cc059dd7.gif)

**Comment by Nigh** [comment]
@YamiOdymel I think that time should be freeze while your game is paused. Not like your example, the block blink to another position.

**Comment by hajimehoshi** [comment]
So, does https://github.com/hajimehoshi/ebiten/issues/289#issuecomment-258404051 solve your problem?

**Comment by Nigh** [comment]
@hajimehoshi could you set up a focus losing callback? that would solve the problem.

**Comment by hajimehoshi** [comment]
I have no plan to do that (IMO Ebiten should not care that). Is what you want the game 'logical' time?

**Comment by Nigh** [comment]
in some case, the fluctuations of framerate would be great. but in that case, I still want the time flows smooth and stable, not floating with the fps.

**Comment by hajimehoshi** [comment]
Hmm, I'm sorry but I'm not sure what you meant by 'smooth and stable' in this case. What about the below code?

```
var frameCount = 0

func update(screen *ebiten.Image) {
    frameCount++
    currentTime := time.Duration(frameCount) * time.Second / 60
    // ...
}
```

**Comment by YamiOdymel** [comment]
@Nigh I'm not sure if this is a good solution but hajimehoshi gave me the idea.

Try to create a `focusing` detector.

![default](https://cloud.githubusercontent.com/assets/7308718/20015108/e4dcbfb8-a2f4-11e6-9f1d-e664430e9571.gif)

```go
var oldFrame = 0
var newFrame = 0

func update(screen *ebiten.Image) error {
	newFrame++

	if oldFrame != newFrame {
		// ... Code ...
	}

	oldFrame = newFrame
	return nil
}
```

**Comment by hajimehoshi** [comment]
@YamiOdymel  Huh? `oldFrame != newFrame` is always `true`.

**Comment by YamiOdymel** [comment]
@hajimehoshi Okay you're right, I am dumb. LOL

**Comment by YamiOdymel** [comment]
> In Ebiten, it is assured that update is called 60 times in one second.

So the delta time is around `0.016` **while the game is running**.

![2016-11-05 3 24 59](https://cloud.githubusercontent.com/assets/7308718/20019467/74f70d9e-a307-11e6-88b2-9632cc31743e.png)


If delta time **tells the time between the last frame**, why don't we just reset the delta time **once it's over than `0.050`** since delta time **should be under around `0.018` ~ `0.025`**?

```go
var deltaTime float64
var speed     float64 = 70
var newTime, oldTime  = time.Now().UnixNano(), time.Now().UnixNano()

func update(screen *ebiten.Image) error {

	newTime    = time.Now().UnixNano()
	deltaTime := float64((newTime-oldTime)/1000000) * 0.001

    // Reset the delta time if the game got froze about 0.050 secs
	if deltaTime > 0.050 {
        // TODO: Add another calculation to reduce the "bounce back"
        deltaTime = 0
	}

    // ... Code ...

    x += speed * deltaTime
    y += speed * deltaTime

    oldTime = newTime
}
```

But I found it's a little bit tricky because it **might be wrong** when the computer got temporary stuck, and there should be some other calculations to reduce the object bouncing back (see the GIF).

![default](https://cloud.githubusercontent.com/assets/7308718/20019686/751043e4-a308-11e6-87c6-168af7f19cc9.gif)

@Nigh What's the actual situation that you will need to use this by the way? Ebiten is forced to be 60fps, since the game is out of focus, the game paused as well, there should be no reason to use delta time .. right?

**Comment by Nigh** [comment]
@YamiOdymel in ideal case, the game would run in 60fps. but on some old machines or in some complex scenarios, I can not assure that. So the game speed will slow down exactly as fps. And it will greatly reduce the difficulty of the game.

**Comment by hajimehoshi** [comment]
@Nigh If `update` is not called 60 times in a second, this is a bug of Ebiten.

**Comment by hajimehoshi** [comment]
@Nigh Ah, you want to adjust the timing of `update` with the display's refresh rate so that the game would run slowly when busy? In this case, how about using `ebiten.IsRunningSlowly` and skipping anything in `update` if this is true?

**Comment by YamiOdymel** [comment]
So what you need is a `delta time` right? And when the game is out of focus, it paused as well, you think this shouldn't happen? Or..?
所以你需要的是 `delta time` 沒錯嗎？然後因為遊戲在離開聚焦的時候會卡住，這部分不符合你的預期？或是⋯？

Could you please explain the issue with the following format?
可以請你用像下列的方式再次敘述一次問題嗎？

---

**Steps to reproduce**
**重現步驟**

```go
func getDt() func() time.Duration {
    lastUpdate := time.Now()
    dt := time.Since(lastUpdate)
    return func() time.Duration {
        dt = time.Since(lastUpdate)
        lastUpdate = time.Now()
        return dt
    }
}

var dt func() time.Duration = getDt()

func update(screen *ebiten.Image) error {
    fmt.Printf("%d\n", dt())
    return nil
}
```

**What is Expected?**
**你原本期望發生什麼？**

> ?

**What is actually happening?**
**結果真正發生了什麼？**

> ?

**Comment by Nigh** [comment]
@hajimehoshi @YamiOdymel I think that I have understood how ebiten works. The sample code below is modded from sprites in the example. 



```go
	// Copyright 2015 Hajime Hoshi
	
	package main
	
	import (
		"fmt"
		_ "image/png"
		"log"
		"math/rand"
		"time"
	
		"github.com/hajimehoshi/ebiten"
		"github.com/hajimehoshi/ebiten/ebitenutil"
	)
	
	const (
		screenWidth  = 600
		screenHeight = 400
	)
	
	var (
		ebitenImage       *ebiten.Image
		ebitenImageWidth  = 0
		ebitenImageHeight = 0
	)
	
	type Sprite struct {
		imageWidth  int
		imageHeight int
		x           int
		y           int
		vx          int
		vy          int
	}
	
	func (s *Sprite) Update() {
		s.x += s.vx
		s.y += s.vy
		if s.x < 0 {
			s.x = -s.x
			s.vx = -s.vx
		} else if screenWidth <= s.x+s.imageWidth {
			s.x = 2*(screenWidth-s.imageWidth) - s.x
			s.vx = -s.vx
		}
		if s.y < 0 {
			s.y = -s.y
			s.vy = -s.vy
		} else if screenHeight <= s.y+s.imageHeight {
			s.y = 2*(screenHeight-s.imageHeight) - s.y
			s.vy = -s.vy
		}
	}
	
	type Sprites struct {
		sprites []*Sprite
		num     int
	}
	
	func (s *Sprites) Update() {
		for _, sprite := range s.sprites {
			sprite.Update()
		}
	}
	
	func (s *Sprites) Len() int {
		return s.num
	}
	
	func (s *Sprites) Dst(i int) (x0, y0, x1, y1 int) {
		if s.num <= i {
			return 0, 0, 0, 0
		}
		ss := s.sprites[i]
		return ss.x, ss.y, ss.x + ebitenImageWidth, ss.y + ebitenImageHeight
	}
	
	func (s *Sprites) Src(i int) (x0, y0, x1, y1 int) {
		if s.num <= i {
			return 0, 0, 0, 0
		}
		return 0, 0, ebitenImageWidth, ebitenImageHeight
	}
	
	const (
		MinSprites = 40000
		MaxSprites = 50000
	)
	
	var sprites = &Sprites{make([]*Sprite, MaxSprites), 40000}
	
	func getDt() func() time.Duration {
		lastUpdate := time.Now()
		dt := time.Since(lastUpdate)
		return func() time.Duration {
			dt = time.Since(lastUpdate)
			lastUpdate = time.Now()
			return dt
		}
	}
	
	var tc = time.Tick(1 * time.Second)
	var frameDiscard int = 0
	var frameDiscardCount int = 0
	
	func update(screen *ebiten.Image) error {
		sprites.Update()
	
		if ebiten.IsRunningSlowly() {
			frameDiscardCount += 1
			return nil
		}
		op := &ebiten.DrawImageOptions{
			ImageParts: sprites,
		}
		op.ColorM.Scale(1.0, 1.0, 1.0, 0.5)
		if err := screen.DrawImage(ebitenImage, op); err != nil {
			return err
		}
		msg := fmt.Sprintf(`FPS: %0.2f
		Frame discard per second: %d
	Num of sprites: %d
	Press <- or -> to change the number of sprites`, ebiten.CurrentFPS(), frameDiscard, sprites.Len())
		if err := ebitenutil.DebugPrint(screen, msg); err != nil {
			return err
		}
		return nil
	}
	
	func counter() {
		for {
			<-tc
			frameDiscard = frameDiscardCount
			frameDiscardCount = 0
		}
	}
	
	func main() {
		var err error
		ebitenImage, _, err = ebitenutil.NewImageFromFile("./ebiten.png", ebiten.FilterNearest)
		if err != nil {
			log.Fatal(err)
		}
		ebitenImageWidth, ebitenImageHeight = ebitenImage.Size()
		for i := range sprites.sprites {
			w, h := ebitenImage.Size()
			x, y := rand.Intn(screenWidth-w), rand.Intn(screenHeight-h)
			vx, vy := 2*rand.Intn(2)-1, 2*rand.Intn(2)-1
			sprites.sprites[i] = &Sprite{
				imageWidth:  w,
				imageHeight: h,
				x:           x,
				y:           y,
				vx:          vx,
				vy:          vy,
			}
		}
	
		go counter()
	
		if err := ebiten.Run(update, screenWidth, screenHeight, 1, "Sprites (Ebiten Demo)"); err != nil {
			log.Fatal(err)
		}
	}
```

The `update()` runs 60 times per second. If last frame takes too long to draw, I could detect it by `ebiten.IsRunningSlowly()`, then discard this frame. So, the time between this two valid frame (not discard) could be calculated. 

Is that right ?

**Comment by hajimehoshi** [comment]
@Nigh Yes, though I still don't understand what you want to do with the time interval yet. And you are right: when `ebiten.IsRunningSlowly()` is true, what Ebiten does is just to skip rendering the screen and you can also skip all rendering, which usually takes most part of time in a frame.

**Comment by Nigh** [comment]
solved. issue close.

**Comment by Nigh** [comment]
solved. issue close.
