### ISSUE TITLE
`SetVsyncEnabled(false)` + `SetScreenClearedEveryFrame(false)` consumes more CPU than expected on desktops

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2890]
### Ebitengine Version

v2.6.4 and main (006f14ac196211d6cba6e4754cd8e69baa4cc69f)

### Operating System

- [X] Windows
- [x] macOS
- [x] Linux
- [x] FreeBSD
- [x] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.21.6 windows/arm64

### What steps will reproduce the problem?

Run this program and see the CPU usage on the task manager:

```go
package main

import (
	"sync"

	"github.com/hajimehoshi/ebiten/v2"
)

type Game struct {
	once sync.Once
}

func (g *Game) Update() error {
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
}

func (g *Game) Layout(width, height int) (int, int) {
	return width, height
}

func main() {
	ebiten.SetScreenClearedEveryFrame(false)
	ebiten.SetVsyncEnabled(false)
	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}
}
```

### What is the expected result?

The CPU usage should be low (less than 5% or so)

### What happens instead?

The CPU usage was about 50%

### Anything else you feel useful to add?

This was found at https://github.com/hajimehoshi/ebiten/issues/2889 (CC @erexo)

Let's check Linux too.

**Comment by hajimehoshi** [comment]
Even on macOS, this optimization doesn't work with OpenGL.

**Comment by erexo** [comment]
thanks ❤
