### ISSUE TITLE
Build errors on different OSS/ARCH

### ISSUE THREAD

**Issue by xescugc** [hajimehoshi/ebiten#2892]
### Ebitengine Version

2.6.4

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.21.5 linux/amd64

### What steps will reproduce the problem?

Go to the `/examples/ui` (or any ebiten code) and run `GOOS=linux GOARCH=arm64 go build -o ui .` it happens also with other combination. The output is:

```bash
~/.../ebiten/examples/ui [(HEAD detached at 3be6c78e8)] $> GOOS=linux GOARCH=arm64 go build -o ui .
package github.com/hajimehoshi/ebiten/v2/examples/ui
	imports github.com/hajimehoshi/ebiten/v2
	imports github.com/hajimehoshi/ebiten/v2/internal/ui
	imports github.com/hajimehoshi/ebiten/v2/internal/devicescale
	imports github.com/hajimehoshi/ebiten/v2/internal/glfw
	imports github.com/hajimehoshi/ebiten/v2/internal/cglfw: build constraints exclude all Go files in /home/xescugc/repos/ebiten/internal/cglfw
```

The error is different in different verisions but for example on the current ` v2.7.0-alpha.6` the error is:

```
~/.../ebiten/examples/ui [main] $> GOOS=linux GOARCH=arm64 go build -o ui .
# github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl/gl
../../internal/graphicsdriver/opengl/gl/procaddr.go:24:7: undefined: defaultContext
```

Did not test with other versions 

### What is the expected result?

To not happen and build the binary

### What happens instead?

Fails to build

### Anything else you feel useful to add?

I found this while trying to use https://goreleaser.com/quick-start/ to have different distributions of my game for different platforms.

**Comment by hajimehoshi** [comment]
Install appropriate C compilers and specify CGO_ENABLED=1

**Comment by phouse512** [comment]
just wanted to add some potential clarity @xescugc if you are compiling for linux. some of the headers you may need installed are listed in the github actions below for linux environments. once I ran the commands to install those packages, I was able to compile and use `CGO_ENABLED=1` as mentioned above

https://github.com/hajimehoshi/ebiten/blob/main/.github/workflows/test.yml#L39-L43

**Comment by xescugc** [comment]
Yes you are all totally right, at the end I used `xgo` to cross-compile to other platforms successfully :)
