### ISSUE TITLE
SetWindowTitle should properly set CLASS_NAME and INSTANCE_NAME on X11 platforms 

### ISSUE THREAD

**Issue by elee1766** [hajimehoshi/ebiten#2904]
### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

SetWindowTitle should properly set  CLASS_NAME and INSTANCE_NAME on X11
 
 
in the case of GLFW, which is the default backend being used for x11, this is not happening. one can see using `xprop` that the class_name and instance_name are the defaults, despite a custom title having been set.

![image](https://github.com/hajimehoshi/ebiten/assets/2260857/2a2c2918-860a-4eb5-93ac-be59d237eca0)

two things need to be done
1. initial WINDOW_HINTS when creating the glfw window here https://github.com/hajimehoshi/ebiten/blob/main/internal/glfw/x11_window_linbsd.c#L781-L793
2. change WINDOW_HINTS when SetWindowTitle is called, perhaps using this function https://github.com/hajimehoshi/ebiten/blob/main/internal/glfw/window_unix.c#L376

### Why is this needed?

on X11, it is standard for programs to differentiate themselves to the WM or other applications via their window and instance class. 

the most common use is for window managers to read the initial window hints in order to perform different behaviors, for instance, starting an application in windowed, tiled, fullscreen mode, a specific desktop, etc.

window_class/instance is also sometimes used to identify applications for automation. technically, "instance" should be unique and "class" not necessarily unique, though these conventions are hardly followed. 

can read more here: 
https://tronche.com/gui/x/icccm/sec-4.html#WM_CLASS

https://manpages.ubuntu.com/manpages/bionic/man3/X11::Protocol::WM.3pm.html (ctrl-f WM_CLASS)

**Comment by tinne26** [comment]
While I agree that this would be nice to have, I think a new `RunGameOptions` field would be a more suitable target than `SetWindowTitle`. Some programs will use the title for changing values, like indicating the latest changes haven't been saved with a `*`, indicating the current scene / status, debugging fps or others. Also, they might include emojis or other characters that you wouldn't generally want on the internal window name. To me, the internal window name should be customizable but more static in nature. I would be against coupling it to the window title.

**Comment by elee1766** [comment]
> While I agree that this would be nice to have, I think a new `RunGameOptions` field would be a more suitable target than `SetWindowTitle`. Some programs will use the title for changing values, like indicating the latest changes haven't been saved with a `*`, indicating the current scene / status, debugging fps or others. Also, they might include emojis or other characters that you wouldn't generally want on the internal window name. To me, the internal window name should be customizable but more static in nature. I would be against coupling it to the window title.

I agree it makes more sense to me to have a separate field. if that's the case it probably makes sense to allow setting a separate instance and class as well?

**Comment by hajimehoshi** [comment]
While we can provide such API, this API would work only on Linux (and other UNIX family). Let me implement this to sync with the window title so far, and let's revisit Tinne's idea later.

**Comment by hajimehoshi** [comment]
On second thought, as GLFW provides separate options for a class name and an instance name, providing this as different options sounds better. Hmm 🤔

**Comment by hajimehoshi** [comment]
Added `RunOptions.X11ClassName` and `RunOptions.X11InstanceName`.
