### ISSUE TITLE
Use bit manipulation for function power of 2 -like functions

### ISSUE THREAD

**Issue by aoyako** [hajimehoshi/ebiten#2914]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Replace the current implementation of functions `isPositivePowerOf2`  and `floorPowerOf2` with bit manipulation techniques.

### Why is this needed?

1. The current version of `floorPowerOf2` will stuck in an infinite loop when passed an integer with the highest bit set due to integer overflow at 
`for p2*2 <= x`

2. This improves the performance. The benchmark shows an increase in speed of up to 7 times.
Benchmark results:
- **Floor power of 2**
```
FloorPowerOf2New-16               1.165n ± 2%
FloorPowerOf2Old-16               7.131n ± 4%
```
- **Is power of 2**
```
IsPositivePowerOf2New-16          0.2427n ± 2%
IsPositivePowerOf2Old-16          1.434n ± 8%
```
You can see the benchmark and test code below with a possible implementation:
```
package main

import (
	"math"
	"math/bits"
	"testing"
)

func IsPositivePowerOf2New(x int) bool {
	if x <= 0 {
		return false
	}

	if x&(x-1) == 0 {
		return true
	} else {
		return false
	}
}

func IsPositivePowerOf2Old(x int) bool {
	if x <= 0 {
		return false
	}
	for x > 1 {
		if x/2*2 != x {
			return false
		}
		x /= 2
	}
	return true
}

func FloorPowerOf2Old(x int) int {
	if x <= 0 {
		return 0
	}
	p2 := 1
	for p2*2 <= x {
		p2 *= 2
	}
	return p2
}

func FloorPowerOf2New(x int) int {
	if x <= 0 {
		return 0
	}

	return 1 << (bits.Len(uint(x)) - 1)
}

func TestPositivePowerOf2Eq(t *testing.T) {
	for x := math.MinInt32; x <= math.MaxInt32; x++ {
		if IsPositivePowerOf2Old(x) != IsPositivePowerOf2New(x) {
			t.Errorf("Old != New for %d", x)
		}
	}
	edgeCases := []int64{
		math.MinInt64, math.MinInt64 + 1, math.MinInt64 + 2,
		math.MaxInt64, math.MaxInt64 - 1, math.MaxInt64 - 2,
	}

	for _, x := range edgeCases {
		if IsPositivePowerOf2Old(int(x)) != IsPositivePowerOf2New(int(x)) {
			t.Errorf("Old != New for %d", x)
		}
	}
}

func TestFloorPowerOf2Eq(t *testing.T) {
	for i := math.MinInt16; i <= math.MaxInt16; i++ {
		if FloorPowerOf2Old(i) != FloorPowerOf2New(i) {
			t.Errorf("Old != New for %d", i)
		}
	}
}

func BenchmarkIsPositivePowerOf2New(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = IsPositivePowerOf2New(i)
	}
}

func BenchmarkIsPositivePowerOf2Old(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = IsPositivePowerOf2Old(i)
	}
}

func BenchmarkFloorPowerOf2Old(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = FloorPowerOf2Old(i)
	}
}

func BenchmarkFloorPowerOf2New(b *testing.B) {
	for i := 0; i < b.N; i++ {
		_ = FloorPowerOf2New(i)
	}
}

**Comment by hajimehoshi** [comment]
Thanks, but

> The current version of floorPowerOf2 will stuck in an infinite loop when passed an integer with the highest bit set due to integer overflow at for p2*2 <= x

This should never happen for the current internal/atlas usages. (Adding a check might be better)

> This improves the performance. The benchmark shows an increase in speed of up to 7 times.

I don't think the performance improvement would be worth there as this is not a hot spot. Rather, your suggestion would degrade code readability.

**Comment by hajimehoshi** [comment]
I re-read your proposal.

```go
func IsPositivePowerOf2New(x int) bool {
	if x <= 0 {
		return false
	}

	if x&(x-1) == 0 {
		return true
	} else {
		return false
	}
}
```

This is a little tricky, but I think this is acceptable. `return x&(x-1) == 0` would be better.

```go
func FloorPowerOf2New(x int) int {
	if x <= 0 {
		return 0
	}
	return 1 << (bits.Len(uint(x)) - 1)
}
```

This seems nice also in terms of readability.

Please send a PR if you want. In a PR, we don't need benchmarks. Just a code change is fine.
