### ISSUE TITLE
g.loseAndRestoreContext undefined in contextlost example

### ISSUE THREAD

**Issue by geniot** [hajimehoshi/ebiten#2917]
### Ebitengine Version

cc3db584

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.22rc2

### What steps will reproduce the problem?

Check out the source code, try to compile the contextlost example. 

### What is the expected result?

Example is started.

### What happens instead?

> GOROOT=C:\Users\vitaly\sdk\go1.22rc2 #gosetup
GOPATH=C:\Users\vitaly\go #gosetup
C:\Users\vitaly\sdk\go1.22rc2\bin\go.exe build -o C:\Users\vitaly\AppData\Local\JetBrains\GoLand2023.3\tmp\GoLand\___2go_build_main_go__1_.exe -gcflags "all=-N -l" C:\development_golang\ebiten\examples\contextlost\main.go #gosetup
#command-line-arguments
.\main.go:47:5: g.loseAndRestoreContext undefined (type *Game has no field or method loseAndRestoreContext)
Compilation finished with exit code 1

### Anything else you feel useful to add?

I don't have problems with other examples, thanks!

**Comment by hajimehoshi** [comment]
This example is only for browsers

**Comment by hajimehoshi** [comment]
If you want to run this on Windows, run `go run .` instead of `go run main.go` by the way
