### ISSUE TITLE
disable IME by default

### ISSUE THREAD

**Issue by divVerent** [hajimehoshi/ebiten#2918]
### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

See https://github.com/divVerent/aaaaxy/issues/341 - it'd be nice if games that contain no text input could globally disable all IME shortcuts.

### Why is this needed?

Right now, in AAAAXY, if the player by accident hits the Kanji key in-game (in the concrete case together with Shift), further space keypresses (which is for the jump action) are silently ignored until the Kanji key is pressed again.

As a current workaround, the game also supports other key mappings, but it'd be really nice if I could just disable the handling of the key.

I think what I want is to call this Windows API function:

https://learn.microsoft.com/en-us/windows/win32/api/imm/nf-imm-immdisableime

However, it requires to be called before any window is created, and Ebitengine already creates a window during its init() functions, so I couldn't find a reliable way to inject my own init() handler before any of Ebitengine's.

**Comment by hajimehoshi** [comment]
1. Do we have similar solutions for other OSes?
2. Doesn't this break compatibility for `AppendInputChars`?

**Comment by hajimehoshi** [comment]
I'd add this option for `ImmDisableIME`

```go
type RunGameOptions struct {
    // ...

    DisableIME bool
}
```

and this option would work only on Windows so far. I'm investigating if there are counterparts for other platforms. Even if there are not, I plan to add an option for Windows.

**Comment by hajimehoshi** [comment]
I came up with an idea. 

* Ebitengine invokes `ImmDisableIME` by default.
* However, if `github.com/hajimehoshi/ebiten/v2/exp/textinput` is imported, Ebitengine doesn't invoke `ImmDisableIME`.

Then this doesn't have to modify the public APIs. Thoughts?

**Comment by hajimehoshi** [comment]
I found a different answer

https://learn.microsoft.com/en-us/answers/questions/731701/how-to-enable-disable-ime-input-for-an-application

**Comment by hajimehoshi** [comment]
Yet another solution

https://ftp.zx.net.nz/pub/Patches/ftp.microsoft.com/MISC/KB/en-us/171/154.HTM

**Comment by hajimehoshi** [comment]
@divVerent Try 42209606b1cfe815bbfe9d935a555e8f4e6d1461. Thanks,

**Comment by divVerent** [comment]
Given I don't even own a keyboard with a kanji key, I do not really know how to repro it myself, and I have no more contact with the original reporter.

You have a Japanese keyboard and system setup though.

I suggest if you can no longer reproduce the issue in the "keyboard" example, consider it done.

Thanks!
