### ISSUE TITLE
internal/graphicsdriver/opengl/gl: use OpenGL ES instead of OpenGL 2 when necessary

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#292]
* It would be possible to unify API between mobiles and desktops.
* On some Linux platforms (like PocketCHIP), it looks like OpenGL 2 is not supported but OpenGL ES 2 is supported instead.

The initializing should include the below code:

```
glfw.WindowHint(glfw.CLIENT_API, glfw.OPENGL_ES_API);
```

**Comment by AndreRenaud** [comment]
Has there been any update on this issue? I am building for an embedded Linux platform which is using OpenGLES2/Wayland. I have build libglfw for this environment, but my Ebiten code still links against libGL rather than libGLES.
I assume the correct fix for this is to change the go:build rules in `ebiten/internal/graphicsdriver/opengl/*`, but I haven't started looking into it yet.

**Comment by hajimehoshi** [comment]
No progress so far.

To fix this,

* Introduce a new build tag like `ebitengles`
* Fix internal/graphicsdriver/gl to use GLES on Linux desktop
* Fix internal/graphicsdriver/gles to use go-gl/gl

Thanks,

**Comment by hajimehoshi** [comment]
If https://github.com/hajimehoshi/ebiten/issues/2284 succeeds, we can use an environment variable instead of a build tag...

**Comment by hajimehoshi** [comment]
I have added the build tag `opengles`.

**Comment by hajimehoshi** [comment]
OpenGL ES (libGLESv2.so) requires EGL instead of GLX.

https://github.com/glfw/glfw/blob/master/src/glx_context.c
https://github.com/glfw/glfw/blob/master/src/egl_context.c

**Comment by hajimehoshi** [comment]
Final goal is to choose GL or GLES automatically, or based on an environment variable, rather than a build tag

**Comment by hajimehoshi** [comment]
Now GL and GL ES are chosen based on libGL.so and libGLESv2.so existences. Ebitengine should check profile availability instead.

**Comment by hajimehoshi** [comment]
glxinfo?
https://wiki.archlinux.org/title/OpenGL

**Comment by hajimehoshi** [comment]
Revisit this later. We might need to have some GLFW code in Go.
