### ISSUE TITLE
Kage: DirectX function returning an array type

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2923]
### Ebitengine Version

v2.6.3 - until now

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.1

### What steps will reproduce the problem?

```go
//kage:units pixels

package main

func f() [25]int {
	return [25]int{}
}

func Fragment(dst vec4, src vec2, color vec4) vec4 {
	v := float(f()[0])
	return vec4(v)
}
```

Compile the above shader on windows+directx
(works with OpenGL)

### What is the expected result?

Compilation successful

### What happens instead?

```
directx: D3DCompile failed: shader(51,4): error X3000: syntax error: unexpected token '['    
: HANDLE(2147500037)
```
```hlsl
struct Varyings {
        float4 Position : SV_POSITION;
        float2 M0 : TEXCOORD0;
        float4 M1 : COLOR;
};

float mod(float x, float y) {
        return x - y * floor(x/y);
}

// [...]

Texture2D T0 : register(t0);
Texture2D T1 : register(t1);
Texture2D T2 : register(t2);
Texture2D T3 : register(t3);
SamplerState samp : register(s0);

int[25] F0(void); // Line 51!

int[25] F0(void) {
        int l0[25];
        l0[0] = 0;
        l0[1] = 0;
        l0[2] = 0;
        l0[3] = 0;
        l0[4] = 0;
        l0[5] = 0;
        l0[6] = 0;
        l0[7] = 0;
        l0[8] = 0;
        l0[9] = 0;
        l0[10] = 0;
        l0[11] = 0;
        l0[12] = 0;
        l0[13] = 0;
        l0[14] = 0;
        l0[15] = 0;
        l0[16] = 0;
        l0[17] = 0;
        l0[18] = 0;
        l0[19] = 0;
        l0[20] = 0;
        l0[21] = 0;
        l0[22] = 0;
        l0[23] = 0;
        l0[24] = 0;
        return l0;
}

float4 PSMain(Varyings varyings) : SV_TARGET {
        float l0 = 0.0;
        l0 = float((F0())[0]);
        return (float4)(l0);
}
```

### Anything else you feel useful to add?

Before v2.6.3 there was a panic nil pointer dereference on a drawTriangle command internally, and I can't tell if it's related.

I don't think it ever worked or that it could be due to a breaking change, because the case seems a bit special.

**Comment by hajimehoshi** [comment]
Interesting. Apparently HLSL cannot return an array from a function.

Instead, we should be able to use `out` parameters.
