### ISSUE TITLE
internal/ui: Window no more focused on windows+fullscreen

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2924]
### Ebitengine Version

v2@5774cf808f82903148eaf9bcae3beba880978df7

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.21.1

### What steps will reproduce the problem?

Run an ebitengine application in fullscreen on Windows and try to submit an input.

### What is the expected result?

I expect the window to be focused on launch like it used to, accepting inputs directly.
I noticed because I always bind 'Esc' to quit the game, and now go-running an ebitengine app requires me to issue a click before it can accept any input.

### What happens instead?

The window now requires a click to be focused.

### Anything else you feel useful to add?

It seems to be introduced by this PR: https://github.com/hajimehoshi/ebiten/commit/5774cf808f82903148eaf9bcae3beba880978df7

Note that this seems to happen in fullscreen especially, running the same program in windowed mode doesn't seem to have any focus issue (I can press 'Esc' directly)

**Comment by hajimehoshi** [comment]
Thanks, I could reproduce this by

1. Run `go run .\examples\windowsize\ -fullscreen`
2. Press F
