### ISSUE TITLE
Provide a normalized mode for Kade shaders

### ISSUE THREAD

**Issue by TLINDEN** [hajimehoshi/ebiten#2927]
### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Currently one can use texel or pixel mode. However, most tutorials on shaders out there work with normalized vectors. So something like this:
```go
//kage:unit normalizedpixels
```

I tried to do the conversion myself but it doesn't work:
```go
//kage:unit pixels

func Fragment(_ vec4, fragcoord vec2, _ vec4) vec4 {
	curnorm := norm(fragcoord)
	newpx := pixelize(curnorm)
	return imageSrc0UnsafeAt(newpx)
}

func pixelize(norm vec2) vec2 {
	return vec2(norm.x*Resolution.x, norm.y*Resolution.y)
}

func norm(pix vec2) vec2 {
	return vec2(pix.x/Resolution.x, pix.y/Resolution.y)
}
```
This should just display the unmodified image.

### Why is this needed?

By providing a builtin (correct) normalized pixel mode on could easier follow tutorials and try examples.

Thanks a lot,
Tom

**Comment by hajimehoshi** [comment]
Isn't what you want `//kage:unit texels`?

**Comment by hajimehoshi** [comment]
Oh, so you want to have [0, 1] values for destination regions. Unfortunately this is difficult as a destination image is on a big texture atlas. It is possible to pass a destination image size as uniform variables, but this prevents batching. I think I don't introduce a new mode.

**Comment by TLINDEN** [comment]
Hi, thanks for answering this. Yes, texel mode was indeed what I wanted :)

**Comment by hajimehoshi** [comment]
Note that, even with the texel mode, the value range might not be [0, 1] as images on a big texture atlas in general.
