### ISSUE TITLE
shader: Alpha value not being respected in fragment shader

### ISSUE THREAD

**Issue by SnareChops** [hajimehoshi/ebiten#2928]
### Ebitengine Version

2.6

### Operating System

- [X] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.22

### What steps will reproduce the problem?

Created [reproduction repo](http://github.com/SnareChops/shader-issue)

### What is the expected result?

Expected result is for the white square rendered with the shader to be blended with the blue background, making the shader seem semi-transparent.

![image](https://github.com/hajimehoshi/ebiten/assets/3210560/b506a53a-dd46-4f72-bd91-d1c7f9d7a46a)

(Simulated image created using drawing program) The white in this screenshot is `255,255,255,25.5` which is equivalent to `1,1,1,.1` in shader language

### What happens instead?

The white square is at full alpha no matter what value is returned in the 4th position of the vec4. Even setting alpha to 0 still draws the full white square

![image](https://github.com/hajimehoshi/ebiten/assets/3210560/7eebb46d-29a5-4ff9-94d1-893d53645cc9)

### Anything else you feel useful to add?
Shader code
```golang
package main

// kage:unit pixels

func Fragment(pos vec4, tex vec2, _ vec4) vec4 {
    return vec4(1, 1, 1, .1) 
}
```
Draw code
```golang
func (g *Game) Draw(screen *ebiten.Image) {
	screen.Fill(color.RGBA{0, 0, 255, 255})
	options := &ebiten.DrawRectShaderOptions{}
	options.GeoM.Translate(100, 100)
	screen.DrawRectShader(100, 100, Shader, options)
}
```

There may be some misunderstanding with how shaders work in ebiten + kage. If there is a different solution or setting that i've missed, please let me know.

**Comment by hajimehoshi** [comment]
The result has to be a premultiplied alpha color value.

https://github.com/tinne26/kage-desk/blob/main/docs/tutorials/premult.md

**Comment by SnareChops** [comment]
Confirmed fixed when switching to NRGBA for colors with lower alpha values. Thank you for your response.
