### ISSUE TITLE
Kage: wrong types inferred for constants in webgl

### ISSUE THREAD

**Issue by Zyko0** [hajimehoshi/ebiten#2933]
### Ebitengine Version

v2.7.0-alpha.9.0.20240310104919-63e97c70645e

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.21

### What steps will reproduce the problem?

```go
//kage:units pixels

package main

func Fragment(dst vec4, src vec2, color vec4) vec4 {
	x := vec4(0)
	x.w++
        // x.w--
        // x.w = 1
	return x
}
```

`wasmserve` any ebitengine application using such kage shader.

### What is the expected result?

Shader successful compilation and run.

### What happens instead?

```
opengl: fragment shader compile error: opengl: shader compile failed: ERROR: 0:33: '+' : wrong operand types - no operation '+' exists that takes a left-hand operand of type 'highp float' and a right operand of type 'const int' (or there is no acceptable conversion)
```

### Anything else you feel useful to add?

We can fix this by transforming `x++` to `x+=1.` for example, but that doesn't seem right since it's handled for other platforms 👀

**Comment by hajimehoshi** [comment]
> v2.7.0

This is not released yet. Which version did you indicate?

**Comment by Zyko0** [comment]
Sorry, I've been lazy, I edited: v2.7.0-alpha.9.0.20240310104919-63e97c70645e

**Comment by hajimehoshi** [comment]
Should we allow ++/-- for vectors in the first place..?? 🤔

**Comment by Zyko0** [comment]
> Should we allow ++/-- for vectors in the first place..?? 🤔

I realized I could've minimized further, but this happens when a `float` variable is getting assigned a (wrongly assumed) `const int`.
In case of `++` or `= 1` for example in Kage.

To answer the question now, I think we should yeah, since a float vector should only be a `[N]float`

**Comment by hajimehoshi** [comment]
Found GLSL allowed ++ and -- for vec2, so then, we should :-)
