### ISSUE TITLE
internal/gamepaddb: split the text file for each platform

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2936]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Now the text file is about 525 kb. Splitting this file and keeping a necessary part of it for each platform should reduce the executable binary sizes.

### Why is this needed?

The smaller executable size, the happier we are.

**Comment by kungfukennyg** [comment]
I'd like to pick this up as a first issue if that's alright.

**Comment by hajimehoshi** [comment]
Thanks. As 2.7 is close to releasing, I might keep you waiting to merge your PR, but contributions are welcome.

**Comment by kungfukennyg** [comment]
Sounds good! I've been looking at the code and my current theorized approach is:

- write a script to automate fetching the controller db from SDL_GameControllerDB and splitting into a text file per platform (delineated by `#` lines)
- create `db.go` files for each platform with respective build tags and embeds pointed at each platform's respective controller text file 

One area I'm not sure about yet are the platforms listed in this ticket that are not directly mentioned in the controller DB file. The file only references Windows, Mac OS, Linux, Android, and iOS. I'm not sure if e.g. Playstation 5, Switch, and Xbox fall under one of those umbrellas. I can see that js is explicitly excluded from the current controller db embed.

**Comment by hajimehoshi** [comment]
> write a script to automate fetching the controller db from SDL_GameControllerDB and splitting into a text file per platform (delineated by # lines)
> create db.go files for each platform with respective build tags and embeds pointed at each platform's respective controller text file

Yeah we should have a 'script' as `gen.go`, which runs by `go generate`. We would need these `db_*.go` files:

* `db_windows.go` (Windows)
* `db_macos_darwin.go` (macOS) with the build tag `//go:build !ios`
* `db_linbsd.go` (Linux and other UNIX excpet for Darwin)
* `db_ios.go` (iOS)
* `db_android.go` (Android)

>  I'm not sure if e.g. Playstation 5, Switch, and Xbox fall under one of those umbrellas.

Consoles don't use the database, so we should treat this like js.
