### ISSUE TITLE
add Mask to `DrawImageOptions`

### ISSUE THREAD

**Issue by eihigh** [hajimehoshi/ebiten#2947]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [X] Android
- [X] iOS
- [X] Nintendo Switch
- [X] PlayStation 5
- [X] Xbox
- [X] Web Browsers

### What feature would you like to be added?

Add the ability to mask and draw the source image with a mask image without custom shaders or off-screen buffers, as in [image/draw.DrawMask](https://pkg.go.dev/image/draw#DrawMask).

### Why is this needed?

Off-screen rendering should be avoided as it slows down the ebitengine rendering.

However, the majority of situations where off-screen rendering is desired are considered to be drawing with masks.

Therefore, if DrawImage, the most basic drawing API, has masking capabilities, masking can be achieved efficiently and easily without additional shaders or off-screen buffers.

However, the detailed design is yet to be worked out. For example, DrawMask has an argument called Op, but the handling of this has not yet been decided.

**Comment by hajimehoshi** [comment]
For a rectangle mask, you can use `SubImage`. For other shape masks, you can use a Kage shader.

Do we have to introduce a new feature?

**Comment by eihigh** [comment]
As Hajime explained, any way to achieve the mask would increase the number of draw calls. Therefore, there was no point in adding new capabilities to DrawImage.
