### ISSUE TITLE
examples/skipdraw: wrong rendering result with `SetScreenClearedEveryFrame(false)`

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2952]
### Ebitengine Version

Both v2.6.7 and v2.7.0

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.22.0 linux/arm64

### What steps will reproduce the problem?

Run [github.com/crgimenes/neko](github.com/crgimenes/neko) commit: eb5fed9b4f321d7914da25d03e88c0710d423c02

### What is the expected result?

The rendering result is correct

https://github.com/hajimehoshi/ebiten/assets/16950/1ad4c010-fbd3-4140-bf59-6d98460f6809

### What happens instead?

The rendering result is not correct

### Anything else you feel useful to add?

This issue is forked from #2951 

After removing `SetScreenClearedEveryFrame(false)` and fixing the code to always render the sprite, the issue was fixed.

**Comment by hajimehoshi** [comment]
This could be reproduced with examples/skipdraw.

**Comment by hajimehoshi** [comment]
This doesn't seem a fixable issue as vsync doesn't work in my environment

```go
       _,met$$$$$gg.          parallels@debian-gnu-linux-12 
    ,g$$$$$$$$$$$$$$$P.       ----------------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux 12 (bookworm) aarch64 
 ,$$P'              `$$$.     Host: Parallels ARM Virtual Machine 0.1 
',$$P       ,ggs.     `$$b:   Kernel: 6.1.0-9-arm64 
`d$$'     ,$P"'   .    $$$    Uptime: 5 hours, 6 mins 
 $$P      d$'     ,    $$P    Packages: 1905 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: bash 5.2.15 
 $$;      Y$b._   _,d$P'      Resolution: 1800x1126 
 Y$$.    `.`"Y$$$$P"'         DE: Cinnamon 5.6.8 
 `$$b      "-.__              WM: Mutter (Muffin) 
  `Y$$                        WM Theme: cinnamon (Default) 
   `Y$$.                      Theme: Adwaita [GTK2/3] 
     `$$b.                    Icons: gnome [GTK2/3] 
       `Y$$b.                 Terminal: gnome-terminal 
          `"Y$b._             CPU: (2) 
              `"""            GPU: 00:0a.0 Red Hat, Inc. Virtio 1.0 GPU 
                              Memory: 1081MiB / 1978MiB 
```

**Comment by DarkReaper231** [comment]
@hajimehoshi If you send me the example skipdraw code, I can test it on my machine. Idk if that would help in any way.

**Comment by hajimehoshi** [comment]
Thanks. I need to test this with a proper Linux machine rather than a Parallels VM first.

**Comment by hajimehoshi** [comment]
On ChromeOS's Debian, the first frame blinked. This might be related but is another issue.

**Comment by hajimehoshi** [comment]
I failed to reproduce this on ChromeOS's Linux. My guess is that there is an issue in OpenGL driver for Parallels...

**Comment by hajimehoshi** [comment]
This hack fixes the issue (a patch to b9dce05ca1b490a643b949e794231dab46f6c17e)

```go
diff --git a/internal/ui/context.go b/internal/ui/context.go
index 8c4795886..064a07bf5 100644
--- a/internal/ui/context.go
+++ b/internal/ui/context.go
@@ -15,6 +15,7 @@
 package ui
 
 import (
+       "image"
        "math"
        "time"
 
@@ -197,19 +198,24 @@ func (c *context) drawGame(graphicsDriver graphicsdriver.Graphics, ui *UserInter
        // isOffscreenModified is updated when an offscreen's modifyCallback.
        c.isOffscreenModified = false
 
+       const maxSkipCount = 4
+
        // Even though updateCount == 0, the offscreen is cleared and Draw is called.
        // Draw should not update the game state and then the screen should not be updated without Update, but
        // users might want to process something at Draw with the time intervals of FPS.
        if ui.IsScreenClearedEveryFrame() {
                c.offscreen.clear()
+       } else {
+               if c.skipCount < maxSkipCount {
+                       pixels := make([]byte, 4)
+                       c.offscreen.ReadPixels(pixels, image.Rect(0, 0, 1, 1))
+               }
        }
 
        if err := c.game.DrawOffscreen(); err != nil {
                return false, err
        }
 
-       const maxSkipCount = 4
-
        if !forceDraw && !c.isOffscreenModified {
                if c.skipCount < maxSkipCount {
                        c.skipCount++
```

**Comment by hajimehoshi** [comment]
My current understanding is that there is an issue in the graphics driver in Linux Parallels. Vsync doesn't work. Just adding a small wait fixed the issue.

**Comment by hajimehoshi** [comment]
As this is a driver issue, I'll close this as 'won't fix'.
