### ISSUE TITLE
enable to choose samplers (nearest and linear) at a Kage program

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#2962]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Now Kage doesn't provide a linear sampler and a user has to do their own linear interpolation. This is troublesome. We want an option to specify a sampler.

### Why is this needed?

A linear fileter is useful (e.g. implementing a SDF font).

**Comment by hajimehoshi** [comment]
Hmm, this might not match well with the current pixel mode, where an integer position is specified.

Other notes:

OpenGL: there is no way to choose a sampler in GLSL programatically. This is bound to a texture by `glTexParameteri`. As of OpenGL 3.3, a sampler object is available.
DirectX: A sampler can be chosen in HLSL?
Metal: A sampler can be chosen in MSL.

**Comment by hajimehoshi** [comment]
So, "why not both"? We can have funcitons to get a texel data without interpolations (like `texelFetch`) and with interpolations (like `texture2D`)?

**Comment by Zyko0** [comment]
Just my opinion, but I don't think it's necessary, and I couldn't image a clean way to integrate the notion of samplers in ebitengine/kage.
Also, linear sampler is one example, but there are many different filtering techniques so when should we stop? (linear, bilinear, trilinear, etc...)
I would rather write an example implementation in Kage, or (what this issue aims for) wait for other user inputs 😅

**Comment by hajimehoshi** [comment]
Thanks,

> Also, linear sampler is one example, but there are many different filtering techniques, so when should we stop? (linear, bilinear, trilinear, etc...)

IIUC nearest and linear is the two common preset filter in various libraries/GPU.

**Comment by hajimehoshi** [comment]
> So, "why not both"? We can have funcitons to get a texel data without interpolations (like texelFetch) and with interpolations (like texture2D)?

`texture2D` requires texels, not pixels. In the pixel-unit mode, this requires the size of the texture and this would require uniform variables. Unfortunately this is not efficient...

**Comment by tinne26** [comment]
I was reviewing this issue and the technical hurdles. It seems like the most straightforward solution would involve passing 2 vertex attributes for the atlas size, so Kage can translate to use `texture()` and do the `pixelCoords/atlasSize` division, right?

Given the potential benefits of hardware bilinear filtering[^1], even if the pipeline needs to be adjusted to allow varying number of vertex attributes, I think this should be reconsidered, at least moving towards v3.

Having no way to choose a sampler within the shader seems fine. Having this option on the shader options should be sufficient. Even having separate functions for sampling that can't be used at the same time in a single shader would be ok. I don't think this is much of a concern (though... I think this could be written by leaving bilinear on and using texelFetch for nearest and texture for bilinear, so it might not be technically impossible).

[^1]: I think the benefits of bilinear filtering are quite understated in the discussion. Drawing at non-integer coordinates and zoom/scaling would massively benefit from bilinear filtering. Particle systems would become way more efficient. Every post-processing effect in the book would massively benefit from bilinear filtering (blurs, glows, outlines and morphology, warps and deformations, any form of image masking and composition to be drawn at non-integer coordinates). Custom bicubic and anisotropic filtering would become far more viable for downscale/upscale fx pipelines and abitrary projections. Raymarching and SDF field sampling would benefit too. The list of use-cases is substantial.

**Comment by hajimehoshi** [comment]
A hardware bilinear filtering doesn't work with a function to get a pixel data based on pixels (not texels).

**Comment by hajimehoshi** [comment]
> so Kage can translate to use texture() and do the pixelCoords/atlasSize division, right?

I see your point, but when a multiple source images are mixed, the calculation would be nightmare unfortunately

**Comment by tinne26** [comment]
I see, for some reason I thought all sources had to be in the same atlas. I understand the complications with multiple sources. To be fair, though, 99% use-cases don't require multiple sources to benefit from this, and even a restriction of "can only do bilinear sampling for images in the base atlas" would be good, as only advanced users are even trying that.
