### ISSUE TITLE
examples/gamepad: PS4 (Dualshock) bluetooth controller inputs not detected on Windows

### ISSUE THREAD

**Issue by Hatchibombotar** [hajimehoshi/ebiten#2967]
### Ebitengine Version

2.7.2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.22.0 windows/amd64

### What steps will reproduce the problem?

- Connect gamepad to computer
- Create new go project with `go mod init example/project`
- Create main.go files with the contents of https://ebitengine.org/en/examples/gamepad.html#Code
- run `go mod tidy`, then `go run .`
- Read console output.

### What is the expected result?

Button inputs are recognised

### What happens instead?

![image](https://github.com/hajimehoshi/ebiten/assets/72224591/10137934-afda-410d-bdaa-31549c4392c6)
No other output appears after these lines.

### Anything else you feel useful to add?

Using a ps4 dualshock controller, but may not be exclusive to this one. I don't have another one to test with.
Windows 11 Home, 23H2
Example works in the web browser

**Comment by Hatchibombotar** [comment]
It was connected by bluetooth. Just tested now and connecting by USB does work

**Comment by hajimehoshi** [comment]
OK, this doesn't work only when connecting it via bluetooth. Another question: does this work with Ebitengine v2.6.7?

**Comment by SolarLune** [comment]
@Hatchibombotar - Hello, just to double-check, did you iterate through other gamepad ID's, just to see if it's reported as ID 1 or 2, by chance?

**Comment by hajimehoshi** [comment]
I failed to reproduce this issue on my Windows (Parallels):

```
PS Microsoft.PowerShell.Core\FileSystem::\\Mac\Home\ebiten> go run .\examples\gamepad
2024/04/26 00:29:04 gamepad connected: id: 0, SDL ID: 78696e70757401000000000000000000
2024/04/26 00:29:08 button pressed: id: 0, button: 1
2024/04/26 00:29:08 standard button pressed: id: 0, button: 1
2024/04/26 00:29:08 button pressed: id: 0, button: 0
2024/04/26 00:29:08 standard button pressed: id: 0, button: 0
2024/04/26 00:29:08 button released: id: 0, button: 1
2024/04/26 00:29:08 standard button released: id: 0, button: 1
2024/04/26 00:29:08 button released: id: 0, button: 0
2024/04/26 00:29:08 standard button released: id: 0, button: 0
```

**Comment by hajimehoshi** [comment]
Your ID was 030000004c050000c405000000000000 (PS4 Controller) while mine was 78696e70757401000000000000000000 (XInput Gamepad (GLFW)). I'm not 100% sure but upgrading or installing DirectX might resolve the issue.

**Comment by hajimehoshi** [comment]
Does this still happen with v2.7.8? This might be related to #3046

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to revisit this when you still have this issue.
