### ISSUE TITLE
examples/flappy: Audio not working on Wasm/Firefox

### ISSUE THREAD

**Issue by johanbrandhorst** [hajimehoshi/ebiten#2970]
### Ebitengine Version

v2.7.2

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go version go1.22.0 linux/arm64

### What steps will reproduce the problem?

Build the flappy example for Wasm:
```
$ GOOS=js GOARCH=wasm go build -o flappy.wasm ./examples/flappy/
```

Execute in the browser

### What is the expected result?

Flappy gopher with sound is playing

### What happens instead?

Flappy gopher without sound is playing

### Anything else you feel useful to add?

I see a console warning:
```
An AudioContext was prevented from starting automatically. It must be created or resumed after a user gesture on the page.
```
Seems very suspicious.

**Comment by hajimehoshi** [comment]
I failed to reproduce the issue. https://ebitengine.org/en/examples/flappy.html worked with audio.

**Comment by johanbrandhorst** [comment]
That page works for me, and I finally got it to work _sometimes_ locally. I can't tell what it was that made it work, but it seems... temperamental. I'll close this for now and let you know if I can establish a pattern. Thank!

**Comment by hajimehoshi** [comment]
Thanks! Feel free to reopen this when you find this issue often happens again.
