### ISSUE TITLE
Kage: Use color argument as the source image color on `DrawRectShader`

### ISSUE THREAD

**Issue by npinochet** [hajimehoshi/ebiten#2973]
### Operating System

- [X] Windows
- [X] macOS
- [X] Linux
- [X] FreeBSD
- [X] OpenBSD
- [X] Android
- [X] iOS
- [X] Nintendo Switch
- [X] PlayStation 5
- [X] Xbox
- [X] Web Browsers

### What feature would you like to be added?

Hello, First, thanks for this great engine.

I don't know if this feature/issue has been addressed somewhere, but I couldn't find it.

I was using Kage to create a grayscale shader and found out that the `color vec4` argument on `Fragment` is not the color of the source image when using `DrawRectShader`. Like if I run `screen.DrawRectShader`, color is not the one get from `screen`, as far as I can tell, it is always set to white. Which force me to copy the `screen` with `screen.SubImage` and add it to the `Images` option on `DrawRectShaderOptions`. The [docs here](https://ebitengine.org/en/documents/shader.html) state that `color vec4` is "_This value is meaningful only when DrawTrianglesShader is used._", which I find as a missed opportunity to set it as the source color when `DrawRectShader` is used.

I don't know if this could break some standards or even if it's possible, but I couldn't find a discussion about it.

Thank you for your time.

### Why is this needed?

It make simple fragment shaders like grayscale or color filters much simpler and performant to write. As it does not requires a copy of the screen image to be used in the shader.

**Comment by hajimehoshi** [comment]
The color value is the value of `ColorScale`. I'll update the documentation later.

**Comment by npinochet** [comment]
I understand, thank you for the quick response, I will try to find another solution that does not involve calling `screen.SubImage`  on every frame. Thanks you.

**Comment by hajimehoshi** [comment]
By the way, it is impossible to get a color on a destination texture in a shader in general.

**Comment by npinochet** [comment]
Ahh I see, thanks for the clarification I didn't knew that
