### ISSUE TITLE
ebiten: calling `ScreenSizeInFullscreen` panics on browsers

### ISSUE THREAD

**Issue by tinne26** [hajimehoshi/ebiten#2975]
### Ebitengine Version

v2.7.2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go1.22.2

### What steps will reproduce the problem?

Compiling and executing the following program on the browser (e.g. `$env:GOOS="js"; $env:GOARCH="wasm"; go build -o exec.wasm main.go`):
```Golang
package main

import "github.com/hajimehoshi/ebiten/v2"

type Game struct {}
func (*Game) Layout(w, h int) (int, int) { return w, h }
func (*Game) Update() error { return nil }
func (*Game) Draw(*ebiten.Image) {}

func main() {
	w, h := ebiten.ScreenSizeInFullscreen()
	_, _ = w, h
	err := ebiten.RunGame(&Game{})
	if err != nil { panic(err) }
}
```

I also tried with `runtime.LockOSThread()`, go1.18.10, both Firefox and Chrome, etc.; everything panics. Using `Monitor().Size()` works, though.

Sample Firefox error output:
```
panic: syscall/js: call of Value.Int on undefined
<empty string>
goroutine 1 [running]:
syscall/js.Value.float({{}, 0x0, 0x0}, {0x82666, 0x9})
	syscall/js/js.go:454 +0x10
syscall/js.Value.Int(...)
	syscall/js/js.go:471
github.com/hajimehoshi/ebiten/v2/internal/ui.(*UserInterface).ScreenSizeInFullscreen(0x19bc008)
	github.com/hajimehoshi/ebiten/v2@v2.7.2/internal/ui/screensizeinfullscreen_js.go:19 +0x5
github.com/hajimehoshi/ebiten/v2.ScreenSizeInFullscreen(...)
	github.com/hajimehoshi/ebiten/v2@v2.7.2/run.go:358
main.main()
	./main.go:14 +0x6
```

### What is the expected result?

No panic.

### What happens instead?

Panic.

**Comment by hajimehoshi** [comment]
What about Chrome?
