### ISSUE TITLE
Feature request: Ability to set the pixel density of the HTML canvas

### ISSUE THREAD

**Issue by setanarut** [hajimehoshi/ebiten#2987]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### What feature would you like to be added?

Feature request: Ability to set the pixel density of the HTML canvas. At resolutions with pixel density greater than one, Ebitengine always scales the HTML Canvas size (`Canvas size * DeviceScaleFactor`). It would be nice to have an option to disable this. The equivalent of [pixelDensity()](https://p5js.org/reference/#/p5/pixelDensity) in the p5.js library.

## Additional info

> The canvas's width and height properties are set to 800 because you are running this sketch on a high DPI (i.e. Apple Retina) display. When p5.js detects this it sets pixel density to 2 by default so it's taking 800 pixel square of graphics and squishing it into a 400 "pixel" square on the screen. If you want an image that is exactly 400 actual pixels, you could set pixel density to 1 in your `setup()` function: `pixelDensity(1)`.
>
> -- *[stackoverflow.com/a/69890360](https://stackoverflow.com/a/69890360)*

### Why is this needed?

Reasons for this feature:
- Large-sized HTML canvases cause dramatic GPU usage.
- Energy savings for portable devices.
- Higher FPS performance.

**Comment by hajimehoshi** [comment]
Adjusting the size of the framebuffer would be a good feature not only for framebuffers but also for any environments.

**Comment by hajimehoshi** [comment]
Unfortunately there is no way to adjust the framebuffer scale on desktops (not browsers)... 🤔 

> Large-sized HTML canvases cause dramatic GPU usage.
> Energy savings for portable devices.
> Higher FPS performance.

I was wondering how the performance is changed.

**Comment by setanarut** [comment]
> > Large-sized HTML canvases cause dramatic GPU usage.
> > Energy savings for portable devices.
> > Higher FPS performance.
> 
> I was wondering how the performance is changed.

I don't get it. Are you asking me to give GPU percentage?

**Comment by hajimehoshi** [comment]
> I don't get it. Are you asking me to give GPU percentage?

Yes. How much would the GPU power be changed by `pixelDensity(1)` from the default?

**Comment by setanarut** [comment]
You can test it by commenting the `pixelDensity(1)` line.
https://editor.p5js.org/zolt/sketches/shG1sCNej

`pixelDensity(1)` -> %9 GPU
`//pixelDensity(1)` -> %15 GPU

**Comment by hajimehoshi** [comment]
Thanks. Unfortunately I failed to find a significant difference on my machine (MacBook M3 Pro). Both took 5-15% and it was dynamically changed.

**Comment by hajimehoshi** [comment]
> pixelDensity(1) -> %9 GPU
> //pixelDensity(1) -> %15 GPU

On your machine, were the percentages constant?

**Comment by setanarut** [comment]
> > pixelDensity(1) -> %9 GPU
> > //pixelDensity(1) -> %15 GPU
> 
> On your machine, were the percentages constant?

Yes constant. My machine is [MacBook Pro 2016](https://support.apple.com/en-us/111975) 15 Dual GPU. These percentages are integrated GPU (intel) results. I am using [Stats](https://github.com/exelban/stats) app.

**Comment by hajimehoshi** [comment]
On my machine GPU usage still dynamically changed, but I admit there is a slight difference.

For Ebitengine,

```diff
diff --git a/internal/ui/ui_js.go b/internal/ui/ui_js.go
index f3c90da44..e162db301 100644
--- a/internal/ui/ui_js.go
+++ b/internal/ui/ui_js.go
@@ -814,6 +814,8 @@ func (m *Monitor) Name() string {
 }
 
 func (m *Monitor) DeviceScaleFactor() float64 {
+       return 1
+
        if m.deviceScaleFactor != 0 {
                return m.deviceScaleFactor
        }
```

running `wasmserve ./example/highdpi` with and without the above patch would be the simplest experiment. Unfortunately, I failed to find a performance difference between them on my machine. I'll take a look more later, but Ebitengine might not have a good solution compared to p5js.

**Comment by hajimehoshi** [comment]
Hm, I made a separate Chome tab for testing and observed 5-10% GPU power differences. Then it seems worth introducing the option to 'ignore' the device scale factor for browsers.

**Comment by hajimehoshi** [comment]
I've introduced `RunGameOptions.DisableHiDPI`. Please try this with `ebiten.RunGameWithOptions` on browsers.

**Comment by setanarut** [comment]
> I've introduced `RunGameOptions.DisableHiDPI`. Please try this with `ebiten.RunGameWithOptions` on browsers.
> 
> ```shell
> go get github.com/hajimehoshi/ebiten/v2@35f9b1c22425a07bca5b11ba6b8dc26d1a6cd2cb
> ```

thanks

**Comment by setanarut** [comment]
It works as I expected, thank you.

https://setanarut.github.io/bulimia/ - GPU %23
https://setanarut.github.io/bulimialow/ - GPU %11
