### ISSUE TITLE
ebiten: add `RequestAttention`

### ISSUE THREAD

**Issue by erexo** [hajimehoshi/ebiten#2998]
### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

I'm in need to inform the player that there is something going on in the game even when the game is minimized, that is to call the [FlashWindow](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-flashwindowex).
I've noticed that we already have the `RequestAttention` method in the `Window` platform specific struct, but I don't think that I'm able to call this code externally from my game, can we push that to mby `ebiten.RequestAttention()` or smth?

**Comment by hajimehoshi** [comment]
So do you want GLFW's `RequestAttention`? I'll consider this

**Comment by erexo** [comment]
I'm not sure how that `RequestAttention` work, but I'm specifically in need of `when game is not focused then flash`, if the game is focused there is no need for flashing. So if this RequestAttention flash regardless of focus state then maybe an additional `IsFocused` func could be implemented?
