### ISSUE TITLE
Resized window still returns old size when calling ebiten.WindowSize() on macOS

### ISSUE THREAD

**Issue by mat007** [hajimehoshi/ebiten#3029]
### Ebitengine Version

f6fbb3d

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.22.0 darwin/amd64

### What steps will reproduce the problem?

- `go run ./examples/windowsize/main.go -resizable`
- drag window border to resize

### What is the expected result?

The Window Size displayed to be updated

### What happens instead?

It stays at 480x480

<img width="1169" alt="image" src="https://github.com/hajimehoshi/ebiten/assets/2386884/0a9abbd7-7697-4e93-80b0-cc30671add3d">

### Anything else you feel useful to add?

It works fine on e.g. Windows

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
This issue is not a regression and existed in v2.5, v2.6, and v2.7. However, as this is a very inconsistent behavior among platforms, I'll fix this and cherry-pick the fix to the stable branch.

**Comment by hajimehoshi** [comment]
Probably the culprit is https://github.com/hajimehoshi/ebiten/commit/e150745598f246f4a1236f6da0f87dcc2dad16b7
