### ISSUE TITLE
Unicode chars don't get drawn

### ISSUE THREAD

**Issue by mbolis** [hajimehoshi/ebiten#3031]
### Ebitengine Version

v2.7.5

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.22.1 linux/amd64

### What steps will reproduce the problem?

Draw some Unicode runes (from the "Supplemental Mathematical Operators" block, in my case)

```go
fontPath, err := findfont.Find("Roboto-Regular")
if err != nil {
	panic(err)
}

fontReader, err := os.Open(fontPath)
if err != nil {
	panic(err)
}
defer fontReader.Close()
fontSource, err = text.NewGoTextFaceSource(fontReader)
if err != nil {
	panic(err)
}

face := text.GoTextFace{
	Source: fontSource,
	Size:   24,
}
opts = text.DrawOptions{}
text.Draw(screen, "⨯", &face, &opts) // example character is '⨯' (\u2a2f, Vector or Cross Product)
```

### What is the expected result?

The `⨯` glyph gets drawn on the screen

### What happens instead?

An unrecognized symbol glyph gets drawn instead
![immagine](https://github.com/hajimehoshi/ebiten/assets/5601754/43020fc1-44f2-40a1-94af-ba3709be29b5)

### Anything else you feel useful to add?

I tried with different fonts, and the result is always similar

**Comment by hajimehoshi** [comment]
Apparently Roboto doesn't have a glyph for "⨯" (U+2A2F), so there is nothing Ebitengine can do.

![image](https://github.com/hajimehoshi/ebiten/assets/16950/f3cefa1f-bec6-49d3-b6c0-93b6b6b68812)

**Comment by mbolis** [comment]
Excuse me @hajimehoshi I'm sure you are more knowledgeable than me in this regard.
If Roboto doesn't have that glyph (which I'm sure is the truth), then why is a text editor like LibreOffice showing the glyph when I input it while using Roboto? Is it implementing some sort of fallback?? Then I wonder what font it is using as fallback!
Thank you, and sorry for raising a nonexistent issue

**Comment by hajimehoshi** [comment]
> If Roboto doesn't have that glyph (which I'm sure is the truth), then why is a text editor like LibreOffice showing the glyph when I input it while using Roboto? Is it implementing some sort of fallback?? Then I wonder what font it is using as fallback

Such applications likely have fallbacks and fallback fonts depends on applications.

**Comment by mbolis** [comment]
As a record for posterity, I discovered the fallback font using the following command:
```sh
$ fc-match :charset=2a2f
DejaVuSans.ttf: "DejaVu Sans" "Regular"
```
Here of course `2a2f` is the Unicode codepoint for `⨯`
