### ISSUE TITLE
Check build with `go build -ldflags "-H windowsgui` on Windows

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#304]

**Comment by gonutz** [comment]
You could hide the Windows console window in normal build mode by getting the app's console window and hiding it. You could use `github.com/AllenDang/w32` and do
`w32.ShowWindow(w32.GetConsoleWindow(), w32.SW_HIDE)`
This way, the console might show up in a flicker for a millisecond on program start but will be hidden right away so no one will notice really. The benefit is, that you can get rid of this specific build flag on Windows.

**Comment by hajimehoshi** [comment]
Sounds great. Thank you for the information!

**Comment by gonutz** [comment]
I just shot you a PR with the minimal necessary changes.

**Comment by hajimehoshi** [comment]
Done

**Comment by hajimehoshi** [comment]
I realized that 93684d5 might not work when the process is launched by a launcher other than explorer.exe. This is not a critical problem anyway...

**Comment by hajimehoshi** [comment]
On second thought, Ebiten now depends on GLFW which uses cgo, and cgo is inevitable. So just 

```go
// #cgo ldflags: -H windowsgui
import "C"
```

might work. I'll try.

**Comment by hajimehoshi** [comment]
I was misunderstanding: `-H windowsgui` is go linker's option, not ld's option. It is impossible to pass this via cgo.

**Comment by gonutz** [comment]
I once tought the same thing:
http://stackoverflow.com/questions/38187789/specify-go-build-flag-h-windowsgui-in-code-comment
:-)

**Comment by hajimehoshi** [comment]
Looks like GetWindowThreadProcessId works perfectly. This checks the console creator and if the console creator is the current process, the console can be closed.

See also: http://stackoverflow.com/questions/9009333/how-to-check-if-the-program-is-run-from-a-console

**Comment by hajimehoshi** [comment]
> I once tought the same thing:

Everyone thinks the same way :-)
