### ISSUE TITLE
internal/ui: Safari and Firefox does not handle multiple files dropped correct

### ISSUE THREAD

**Issue by cowboymacke** [hajimehoshi/ebiten#3045]
### Ebitengine Version

v2.7.5

### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

go1.22.3 darwin/arm64

### What steps will reproduce the problem?

Run `examples/dropfile` in safari or firefox
Select two or more files and drop onto the canvas.

### What is the expected result?

Multiple files showing upp inside the canvas

### What happens instead?

Only one of the file shows up 

https://github.com/user-attachments/assets/125c71c0-0f82-4bf5-afcc-c7670b707ebc

**Comment by hajimehoshi** [comment]
Thank you for reporting!

I've not 100% determined, but I would not backport the fix to the stable branch 2.7 since the fix would be a little tricky.
