### ISSUE TITLE
Can WebAssembly (Wasm) be supported to run in environments without DOM, such as in WeChat Mini Programs?

### ISSUE THREAD

**Issue by zhanjunjie2019** [hajimehoshi/ebiten#3048]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### What feature would you like to be added?

Currently, I'm attempting to run a game using Wasm in WeChat or Douyin Mini Programs. However, due to the absence of DOM in this environment, it results in the following error message.

![image](https://github.com/user-attachments/assets/ec7ab8a3-1857-4247-9a69-8c06d1da3290)

I found that the issue lies in "ebiten\internal\ui\ui_js.go", where using "js.Global().Get("window")" results in obtaining undefined. Could you provide support that is compatible with such environments?

**Comment by hajimehoshi** [comment]
Ebitengine uses a canvas so cannot support an environment where this doesn't exist.
