### ISSUE TITLE
Ebiten causes an access error in 'go mod vendor' forcing a system reboot.

### ISSUE THREAD

**Issue by dineth-lochana** [hajimehoshi/ebiten#3050]
### Ebitengine Version

2.7.7

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.22.5

### What steps will reproduce the problem?

Running 'go mod vendor' in Windows cmd, and trying to update it after some time.
I think? this issue is being caused by the same reason here (https://github.com/golang/go/issues/46867)

### What is the expected result?

For 'go mod vendor' to update the files in the vendor folder.

### What happens instead?

![image](https://github.com/user-attachments/assets/6cb15ae6-6f52-462b-a4d1-e5b10557ad29)
The command causes the vendor directory to be unworkable.
The only solution I've found so far is to reboot.

### Anything else you feel useful to add?

The same issue seems to be faced here -> https://github.com/golang/go/issues/46867

**Comment by hajimehoshi** [comment]
If this is the same as https://github.com/golang/go/issues/46867, there is nothing we can do.

**Comment by dineth-lochana** [comment]
Yeah, you're correct.
I've been travelling without data, so that's why I tried to use go mod vendor.
I suppose manually copying the pkg directory is possible.

Thanks @hajimehoshi .
I'll close the isssue

**Comment by dineth-lochana** [comment]
I'll try building go with the suggest change, but yes, this is not regarding Ebiten.
