### ISSUE TITLE
flappy can't be compiled

### ISSUE THREAD

**Issue by skyqvn** [hajimehoshi/ebiten#3059]
### Ebitengine Version

v2

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go1.21

### What steps will reproduce the problem?

.\main.go:160:23: undefined: vorbis.DecodeF32
.\main.go:164:37: g.audioContext.NewPlayerF32 undefined (type *"github.com/hajimehoshi/ebiten/v2/audio".Context has no field or method NewPlayerF32)
.\main.go:169:19: undefined: wav.DecodeF32
.\main.go:173:36: g.audioContext.NewPlayerF32 undefined (type *"github.com/hajimehoshi/ebiten/v2/audio".Context has no field or method NewPlayerF32)

### What is the expected result?

nothing

### What happens instead?

nothing

### Anything else you feel useful to add?

 nothing

**Comment by skyqvn** [comment]
if i don't use go.mod,it can run.but if so ,goland cant analyze code

**Comment by hajimehoshi** [comment]
> v2

Which version?
