### ISSUE TITLE
Different gamepad button numbers when running locally vs in wasm

### ISSUE THREAD

**Issue by Palessan** [hajimehoshi/ebiten#3079]
### Ebitengine Version

v2.7.8

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.22.5

### What steps will reproduce the problem?

Run your `examples\gamepad\main.go` locally and on wasm. 
When you press the same buttons (for example middle central button and touchpad) you will see that they are are mapped to different button numbers:

``` go
	GPButtonMiddle    = ebiten.GamepadButton12
	GPButtonMiddleWeb = ebiten.GamepadButton16 // dpad-left on not wasm

	GPButtonTouchPad    = ebiten.GamepadButton13
	GPButtonTouchPadWeb = ebiten.GamepadButton17  // dpad-top on not wasm
```

This is a problem since the touchpad is the left DPad up for example

### What is the expected result?

i would expect the same key number to be used in both local application and wasm

### What happens instead?

different key numbers on same buttons when run in local application vs wasm

### Anything else you feel useful to add?

If you would add the middle central button and touchpad as an ebiten.StandardGamepadButton, then i could use that instead of using the older(?) ebiten.GamepadButtonXX

**Comment by hajimehoshi** [comment]
This is expected. Button mappings vary among platforms. 

To mitigate the issue, use StandardGamepadButton.

**Comment by hajimehoshi** [comment]
> If you would add the middle central button and touchpad as an ebiten.StandardGamepadButton

Unfortunately I cannot control this (how the center touch pad is assigned)

**Comment by hajimehoshi** [comment]
b34f9977f6d36ca054178071641933a5ed24745c might change the situation as this updated the gamepad database.

**Comment by Palessan** [comment]
Is it possible to add the touchpad and main center button as a StandardGamepadButton?

**Comment by Palessan** [comment]
> [b34f997](https://github.com/hajimehoshi/ebiten/commit/b34f9977f6d36ca054178071641933a5ed24745c) might change the situation as this updated the gamepad database.

no change unfortunately

**Comment by hajimehoshi** [comment]
> Any idea about touchpad?

There is no easy solution. If a browser doesn't treat the touchpad as a pointer device, there is nothing we can do.
