### ISSUE TITLE
Font cache causing memory leak

### ISSUE THREAD

**Issue by t-geindre** [hajimehoshi/ebiten#3110]
### Ebitengine Version

master

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.23

### What steps will reproduce the problem?

When calling
```go
text.DrawWithOptions(screen, "some text", myFace, opts)
```
Font is cached [here](https://github.com/hajimehoshi/ebiten/blob/main/text/cache.go#L73)
I'm working on an application using a lot of various fonts and I can't keep all of them loaded.

### What is the expected result?

Memory usage remains stable.

### What happens instead?

Memory is leaking.

### Anything else you feel useful to add?

I couldn't find a way to clear this cache.
Here is what I found when debugging the memory usage:
![image](https://github.com/user-attachments/assets/64d36c89-cce0-485a-884d-1c98dd6236dc)

**Comment by t-geindre** [comment]
For now, I'm solving the issue like this:
```go
//go:linkname FontCache github.com/hajimehoshi/ebiten/v2/text.faceWithCacheCache
var FontCache map[font.Face]any

func switchFont() {
     // loading new one, removing old one, and then clear ebiten cache
     delete(FontCache, oldFont)
}
```

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/498
