### ISSUE TITLE
32bit float audio not working on Windows or web/WASM

### ISSUE THREAD

**Issue by benc-uk** [hajimehoshi/ebiten#3117]
### Ebitengine Version

2.8.0

### Operating System

- [X] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [X] Web Browsers

### Go Version (`go version`)

1.23.1

### What steps will reproduce the problem?

The new functions for 32bit audio `NewPlayerF32FromBytes()` doesn't appear to work on Windows or with web/WASM.
I am using Windows 11 and I also compile to WASM and open in a browser.  
I've been unable to test on Linux as I don't have audio setup (I use WSL)

The below code is a minimal reproduction of the issue, if you change the creation function to `NewPlayerFromBytes` then audio will be heard on both Win 11 executable and in browser

```go
package main

import (
	"os"

	"github.com/hajimehoshi/ebiten/v2"
	"github.com/hajimehoshi/ebiten/v2/audio"
)

type game struct{}

var player *audio.Player

func (g *game) Update() error {
	player.Rewind()
	player.Play()

	return nil
}

func (g *game) Draw(screen *ebiten.Image) {}

func (g *game) Layout(outsideWidth, outsideHeight int) (screenWidth, screenHeight int) {
	return 320, 240
}

func main() {
	ctx := audio.NewContext(44100)

	d, err := os.ReadFile("test_wav.wav")
	if err != nil {
		panic(err)
	}

	player = ctx.NewPlayerF32FromBytes(d)

	if err := ebiten.RunGame(&game{}); err != nil {
		panic(err)
	}
}
```

### What is the expected result?

Sound is heard

### What happens instead?

Silence

**Comment by benc-uk** [comment]
Here's the WAV file I am testing with

[test_wav.zip](https://github.com/user-attachments/files/17166875/test_wav.zip)

**Comment by hajimehoshi** [comment]
Does the wav file work with the 16bit integer version?

**Comment by hajimehoshi** [comment]
```go
	d, err := os.ReadFile("test_wav.wav")
	if err != nil {
		panic(err)
	}
```

Use [`wav.DecodeF32`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/audio/wav#DecodeF32) to decode the wave file.

**Comment by benc-uk** [comment]
Doh, I missed the fact the source WAV needed to be converted too
I used Audacity to convert to 32bit float and it's working now

Sorry!
Thanks for closing the issue

**Comment by hajimehoshi** [comment]
If you pass the wav file directly to `NewPlayer` without `wav.Decode` or `wav.DecodeF32`, you might hear some noise since the player tries to play a wav file's header data as PCM. So, I strongly recommend always using `wav.Decode` or `wav.DecodeF32`.
