### ISSUE TITLE
vector: expose `(*Path).Reset()`

### ISSUE THREAD

**Issue by tslocum** [hajimehoshi/ebiten#3123]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Please consider making `Path.reset` public. This would allow developers to reset a vector.Path so they can reuse this memory for different drawing operations.

### Why is this needed?

To reduce the amount of memory allocations needed when drawing vector graphics.

**Comment by hajimehoshi** [comment]
Sure!

**Comment by hajimehoshi** [comment]
Oops, I mistakenly exposed (*subPath).Reset(), not `(*Path).Reset()`
