### ISSUE TITLE
[text/v2] `text.GoTextFace` doesn't implement `font.FontFace` interface

### ISSUE THREAD

**Issue by brymer-meneses** [hajimehoshi/ebiten#3126]
### Operating System

- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

The `Close` method is missing from the current implementation of `text.GoTextFace`.

### Why is this needed?

 I tried to use `face.BoundString` which is the recommended approach to get the bounds of a text to be rendered. But this isn't possible because of the missing implementation.

**Comment by hajimehoshi** [comment]
Yeah, this is expected. `text.GoTextFace` is not `font.Face`.

**Comment by hajimehoshi** [comment]
On second thought, it might be possible to implement `font.Face` for `text.GoTextFace` in theory, but you should use [`Measure`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/text/v2#Measure) and [`Metrics`](https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2/text/v2#GoTextFace.Metrics).

**Comment by hajimehoshi** [comment]
I looked at the implementation of [`BoundsString`](https://cs.opensource.google/go/x/image/+/refs/tags/v0.21.0:font/font.go;l=245-261) and this iterates each rune in one string. This could be different from how `text/v2` renders texts with `GoTextFace` considering ligatures and various glyphs. So unfortunately it is not possible to implement `font.Face` for `text.GoTextFace`.
