### ISSUE TITLE
cmd/ebitnmobile: ebitenmobile fails on go1.23 if you have GOEXPERIMENT=loopvar set

### ISSUE THREAD

**Issue by corfe83** [hajimehoshi/ebiten#3128]
### Ebitengine Version

2.8.1

### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.23.2

### What steps will reproduce the problem?

Run ebitenmobile bind with conventional commandline arguments such as:

ebitenmobile bind -target android -javapkg your.package.name -o path/to/yourgame.aar .

### What is the expected result?

Bind is successful

### What happens instead?

Bind gives error:

2024/10/12 22:55:53 go [mod tidy] failed: go: errors parsing go.mod:
go.mod:5: toolchain directive expects exactly one argument

**Comment by hajimehoshi** [comment]
IIUC, specifying `GOEXPERIMENT=loopvar` with Go 1.23 doesn't make sense as Go 1.23 already applies the loopvar change, but anyway this is a bug.
