### ISSUE TITLE
scaling of non-square images behaves oddly

### ISSUE THREAD

**Issue by hailstorm01** [hajimehoshi/ebiten#313]
we're having a problem where a rectangular image (30x12) displays in a strange manner. It rotates the image 90 degrees. I don't know if this is a problem with our code:

https://github.com/ranchblt/labyrinthofthechimera/blob/master/labyrinth/fireball.go

Or a problem within Ebiten.

**Comment by hajimehoshi** [comment]
Thank you for the report. I'll look into it.

**Comment by hajimehoshi** [comment]
https://github.com/ranchblt/labyrinthofthechimera/blob/master/labyrinth/fireball.go#L63 Isn't this `f.center.x - width` instead of `f.center.x - height`?

**Comment by hajimehoshi** [comment]
I go-got you project, but I don't know how to reproduce your problem. After `go run main.go`, what should I do? Thanks.

**Comment by hailstorm01** [comment]
You're almost certainly right about x-width vs. x-height. Unfortunately I'm at work or I'd try it right now. 

Use spacebar to shoot a fireball. We thought we were rotating it weirdly, but if you edit the image (under root/resource) and put something like a blue dot on the image, it's getting squeezed.

**Comment by hajimehoshi** [comment]
OK, so if my suggestion is right, the fact is that the image is squeezed rather than rotated. I pressed the space bar and confirmed fireballs. Thanks.

**Comment by hailstorm01** [comment]
Awesome. Thanks a lot for the second set of eyes, much appreciated. I will take a look at it this evening.

**Comment by hailstorm01** [comment]
Confirmed that we goofed it. Thanks again for your help, and I'll give you a shout when our new game is ready for a playtest. :)

**Comment by hajimehoshi** [comment]
I'm really looking forward to it :-)
