### ISSUE TITLE
New API to call the default behavior of DrawFinalScreen

### ISSUE THREAD

**Issue by noppikinatta** [hajimehoshi/ebiten#3139]
### Operating System

- [ ] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

I may want to call the following code in DrawFinalScreen that I have implemented in my Game.

https://github.com/hajimehoshi/ebiten/blob/v2.8.1/gameforui.go#L139-L155

I would like this code to be a function and be able to call it like `ebiten.DrawFinalScreenDefault(screen, offscreen, geoM)`.

### Why is this needed?

Whether or not a filter is applied when drawing a game depends on the situation. For example, I may want to draw the Ebitengine splash screen unfiltered when the game starts up, and apply the CRT filter on the title screen and beyond.
Now Ebitengine does not allow me to call the default behavior if Game implements FinalScreenDrawer.

**Comment by hajimehoshi** [comment]
Makes sense.

**Comment by noppikinatta** [comment]
Thanks for adding the feature!
The function name is DefaultDrawFinal “s” Screen, is this a typo?
https://github.com/hajimehoshi/ebiten/blob/366f4899a2c54082afa47f7a095a1795c35d8117/gameforui.go#L145

**Comment by hajimehoshi** [comment]
This was typo. Thanks!

**Comment by noppikinatta** [comment]
The type of first argument of DefaultDrawFinalScreen `screen` is *Image, but wouldn't it be better to have the FinalScreen interface, same as FinalScreenDrawer.DrawFinalScreen?

I want to call DefaultDrawFinalScreen from my own FinalScreenDrawer.DrawFinalScreen, so I think it would save me the trouble of casting FinalScreen to *Image or preparing an *Image of the same size as FinalScreen.

**Comment by hajimehoshi** [comment]
Oh that's true... Let me fix this

**Comment by hajimehoshi** [comment]
Fixed!
