### ISSUE TITLE
API to detect very short input (shorter than 1/60 seconds)

### ISSUE THREAD

**Issue by 1l0** [hajimehoshi/ebiten#314]
Currently input feedbacks have 1/60 second latency at most and pulse signals of input can be ignored by update loop due to releasing {key, mouse button, touch}s before the next update frame.

**Comment by hajimehoshi** [comment]
You are right, too short input can be ignored. However, I don't think this is a strong demand.

**Comment by hajimehoshi** [comment]
Probably we would need to switch VSYNC off for this feature. When VSYNC doesn't work, we would see tearing, or even better performance without tearing if your GPU supports triple buffering (#405).
