### ISSUE TITLE
Debug breakpoint make High GPU

### ISSUE THREAD

**Issue by diiyw** [hajimehoshi/ebiten#3160]
### Ebitengine Version

2.8.1

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.22.5 windows/amd64

### What steps will reproduce the problem?

My GPU: RTX 3060
Test code: 
```go
package main

import (
	"github.com/hajimehoshi/ebiten/v2"
	"image/color"
)

type game struct {
}

func (g *game) Update() error {
	return nil
}

func (g *game) Draw(screen *ebiten.Image) {
	for i := 0; i < 1000; i++ {  // breakpoint here
		screen.Fill(color.White)
	}
}

func (g *game) Layout(outsideWidth, outsideHeight int) (int, int) {
	return outsideWidth, outsideHeight
}

func main() {
	ebiten.SetTPS(60)
	ebiten.SetVsyncEnabled(true)
	ebiten.SetWindowSize(800, 600)
	ebiten.MaximizeWindow()
	ebiten.RunGame(&game{})
}
```
Add beakpoint here. 
![1731249805210](https://github.com/user-attachments/assets/8529c0a0-c60c-4d59-a946-063854a8f5fd)
When the program first breaks, remove this breakpoint, let Ebiten continue running, and you will observe the high GPU usage.

### What is the expected result?

GPU less 1%

### What happens instead?

Very very high GPU usage
![1731249291230](https://github.com/user-attachments/assets/4c33d9cc-69de-44a6-a81c-086d7cac7cf6)

**Comment by hajimehoshi** [comment]
This doesn't sound like a real world issue, so I perhaps don't fix this.

**Comment by hajimehoshi** [comment]
> When the program first breaks, remove this breakpoint, let Ebiten continue running, and you will observe the high GPU usage.

Oh, does this happen when you added a breakpoint?

**Comment by diiyw** [comment]
Yes, I added this breakpoint before launching, and when I start the game in Debug mode, the breakpoint is effective. At this point, if I remove the breakpoint, Ebiten runs normally, but it uses a very high amount of GPU.

**Comment by hajimehoshi** [comment]
What about using OpenGL?

```go
op := &ebiten.RunGameOptions{
    GraphicsLibrary: ebiten.GraphicsLibraryOpenGL
}
ebiten.RunGame(&game{}, op)
```

**Comment by diiyw** [comment]
> What about using OpenGL?
> 
> ```go
> op := &ebiten.RunGameOptions{
>     GraphicsLibrary: ebiten.GraphicsLibraryOpenGL,
> }
> ebiten.RunGame(&game{}, op)
> ```

Using OpenGL seems to be running normally, with an 8% GPU usage. I noticed that with the default settings, when I hit a breakpoint and then resume for the first time, the window displays but is not active. When I pause the program a second time and disable the breakpoint, it no longer runs in the foreground and consumes a high amount of GPU resources. Once I bring it back to the foreground, the GPU usage gradually returns to a normal 0.5% after a short wait.
