### ISSUE TITLE
Undecorated windows are offset by an invisible margin

### ISSUE THREAD

**Issue by rdnt** [hajimehoshi/ebiten#3162]
### Ebitengine Version

v2.8.4

### Operating System

- [X] Windows
- [ ] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

go version go1.23.0 windows/amd64

### What steps will reproduce the problem?

- Configure ebiten with `ebiten.SetWindowDecorated(false)`
- Start a window having the same resolution as the monitor

### What is the expected result?

- The window should cover the entirety of the screen

### What happens instead?

- The window is offset by an invisible margin
  - On a 4k screen with 150% scaling, it is 34px high
  
![image](https://github.com/user-attachments/assets/f678a572-ac05-4b23-acb1-ff419030fb89)

### Anything else you feel useful to add?

I have found that if the `isInitWindowDecorated` check is added on the last lines of the `adjustWindowPosition` function, then the window is properly positioned. I am unsure if it is a valid fix or more work is needed to configure it (e.g. if window decorations are enabled/disabled during runtime).

```go
func (u *UserInterface) adjustWindowPosition(x, y int, monitor *Monitor) (int, int) {
    
    ...
    
    //if y < my+int(t) {
    if u.isInitWindowDecorated() && y < my+int(t) { // i.e. if decorated && y above the expected bottom of the title bar
        y = my + int(t)
    }
    return x, y
}
```

I am aware that if I use SetFullscreen *then* it can become a true fullscreen, but my usecase is around a transparent, click-pass-through, fullscreen overlay.

**Comment by hajimehoshi** [comment]
I failed to reproduce this:

```go
//go:build ignore

package main

import (
	"image/color"

	"github.com/hajimehoshi/ebiten/v2"
)

type Game struct {
}

func (g *Game) Update() error {
	if ebiten.IsKeyPressed(ebiten.KeyEscape) {
		return ebiten.Termination
	}
	return nil
}

func (g *Game) Draw(screen *ebiten.Image) {
	screen.Fill(color.RGBA{0x80, 0x80, 0x80, 0xff})
}

func (g *Game) Layout(width, height int) (int, int) {
	return width, height
}

func main() {
	ebiten.SetWindowDecorated(false)
	ebiten.SetWindowPosition(0, 0)
	ebiten.SetWindowSize(ebiten.Monitor().Size())
	if err := ebiten.RunGame(&Game{}); err != nil {
		panic(err)
	}
}
```

Could you show me a minimized code to reproduce your issue? Thanks,

**Comment by rdnt** [comment]
Hi @hajimehoshi thanks for the quick response!

The example code you posted perfectly manages to reproduce the issue on my machine:
![image](https://github.com/user-attachments/assets/b3b2f99a-5bf0-425c-be4e-9758c66ed62f)

It has to be something setup-specific, I assume.

![image](https://github.com/user-attachments/assets/3baa4bc4-9403-48bf-8780-18e85412ee5e)

It wouldn't surprise me if this is a GPU thing, even. If I use a floating, transparent overlay at exactly the monitor's resolution, the GPU performs optimizations that remove the transparency, as if it's a full screen game of sorts.

So, for completeness:

![image](https://github.com/user-attachments/assets/3cc73b8e-4e06-4a4b-81ac-3fed56658090)
![image](https://github.com/user-attachments/assets/dc9509ed-9cf2-4514-b6bc-ef03efccceb3)

**Comment by hajimehoshi** [comment]
Hmm, that's pretty odd. In your machine, does `u.window.GetAttrib(glfw.Decorated)` in `adjustWindowPosition` return `glfw.True`, even though you call `ebiten.SetWindowDecorated(false)`?

**Comment by rdnt** [comment]
`u.window.GetAttrib(glfw.Decorated)` called within `adjustWindowPosition ` returns `0 <nil>`.

**Comment by hajimehoshi** [comment]
Thanks. In this case, didn't this return at the early return?

```go
	if d == glfw.False {
		return x, y, nil
	}
```

**Comment by rdnt** [comment]
Something like this?

```go
func (u *UserInterface) adjustWindowPosition(x, y int, monitor *Monitor) (int, int) {
	if microsoftgdk.IsXbox() {
		return x, y
	}
	
	d, err := u.window.GetAttrib(glfw.Decorated)
	if err != nil {
		panic(err)
	}

	mx := monitor.boundsInGLFWPixels.Min.X
	my := monitor.boundsInGLFWPixels.Min.Y
	// As the video width/height might be wrong,
	// adjust x/y at least to enable to handle the window (#328)
	if x < mx {
		x = mx
	}
	t, err := _GetSystemMetrics(_SM_CYCAPTION)
	if err != nil {
		panic(err)
	}

	if d == glfw.False {
		return x, y
	}

	if y < my+int(t) {
		y = my + int(t)
	}

	return x, y
}
```

If yes then it properly renders in full screen on my machine.

**Comment by hajimehoshi** [comment]
Ah, I'm sorry but I was looking at the main branch, not the 2.8 branch. This means this was already fixed by https://github.com/hajimehoshi/ebiten/commit/8b0c930c2dbc538c64be2871ab924a28ac179eea

**Comment by hajimehoshi** [comment]
As there are multiple reports for the same issue, I'll cherry-pick the fix to 2.8. Let me close this issue later as a duplication with #3118.

**Comment by hajimehoshi** [comment]
Please try

```sh
go get github.com/hajimehoshi/ebiten/v2@53090f31055ee868f1eb2f0c68860fbc4c6f3a2f
```

I'll tag v2.8.5 a few days later.

**Comment by rdnt** [comment]
Can confirm the issue is no longer present on `main`. Lovely!
Apologies for having missed the original issue. Thanks for looking into it.
