### ISSUE TITLE
Image Glitch When Window Loses Focus

### ISSUE THREAD

**Issue by temidaradev** [hajimehoshi/ebiten#3163]
### Ebitengine Version

v2.8.4

### Operating System

- [ ] Windows
- [X] macOS
- [ ] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

1.23.2

### What steps will reproduce the problem?

Implementing assets by using esset library: `var GopherIdle = esset.GetAsset(assets, "gopher/mainchar.png")`

Drawing background like this:
```
func MakeBackground(screen *ebiten.Image) {
	for i := 0; i < 100; i++ {
		for j := 0; j < 100; j++ {
			dio := &ebiten.DrawImageOptions{}
			dio.GeoM.Translate(1800-float64(i*50), 1700-float64(j*50))
			cam.Draw(assets.Tiles[1], dio, screen)
		}
	}
}
```

and also I used kamera library https://github.com/setanarut/kamera and here is the code of movement:
```
func Axis() (axisX, axisY float64) {
	if ebiten.IsKeyPressed(ebiten.KeyW) {
		axisY -= 1
	}
	if ebiten.IsKeyPressed(ebiten.KeyS) {
		axisY += 1
	}
	if ebiten.IsKeyPressed(ebiten.KeyA) {
		axisX -= 1
	}
	if ebiten.IsKeyPressed(ebiten.KeyD) {
		axisX += 1
	}
	return axisX, axisY
}
```

and here is the ``cam.LookAt`` usage

```
        var low float64 = 0
        var high float64 = 1500

        camPosX := Clamp(g.player.X, low, high)
	camPosY := Clamp(g.player.Y, low, high)

	cam.LookAt(camPosX, camPosY)
```

and here is player's ``Update()`` func
```
func (p *Player) Update() error {
	x, y := Axis()

	p.X += x * p.speed
	p.Y += y * p.speed

	p.DIO.GeoM.Reset()

	p.DIO.GeoM.Translate(
		p.X-float64(assets.GopherIdle.Bounds().Dx()/2),
		p.Y-float64(assets.GopherIdle.Bounds().Dy()/2),
	)

	//p.X = min(max(p.X, -230), 1740)
	//p.Y = min(max(p.Y, -120), 1610)

	p.X = Clamp(p.X, -230, 1740)
	p.Y = Clamp(p.Y, -120, 1610)

	return nil
}
```

and here is the ``Draw()`` func
```
func (g *Game) Draw(screen *ebiten.Image) {
	MakeBackground(screen)
	g.player.Draw(screen)
}
```

### What is the expected result?

Stable and normal behavior of gopher.

### What happens instead?

Glitchy and scary gopher

https://github.com/user-attachments/assets/1d4b3ed9-048c-4464-994e-9cff1df51acc

**Comment by temidaradev** [comment]
https://github.com/temidaradev/RpiZeroWEbiten.git here is the repo

**Comment by hajimehoshi** [comment]
Could you minimize the reproducible case?

**Comment by temidaradev** [comment]
> Could you minimize the source code to reproduce this issue?

OK, I tried to minimize it by putting important codes

**Comment by temidaradev** [comment]
ah wait let me test it

**Comment by temidaradev** [comment]
ah yes when I tried to use ``screen.DrawImage(assets.GopherIdle, p.DIO)`` instead of ``cam.Draw(assets.GopherIdle, p.DIO, screen)`` my gopher doesn't do any flicker or glitches

**Comment by hajimehoshi** [comment]
So there might be an issue there. Ask the author.
