### ISSUE TITLE
text/v2 draw.Text does not handle newlines correctly

### ISSUE THREAD

**Issue by vzx** [hajimehoshi/ebiten#3169]
### Ebitengine Version

v2.8.5 and main

### Operating System

- [ ] Windows
- [X] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [ ] Android
- [ ] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### Go Version (`go version`)

* go version go1.23.4 linux/amd64
*  go version go1.23.4 darwin/arm64

### What steps will reproduce the problem?

```
go run github.com/vzx/ebitengine-text-v2-newlines@main
```

### What is the expected result?

On the right (v2), each line of text should appear on a separate line, just like on the left (v1).

### What happens instead?

Lines of text are written on the same line, overwriting each other.

**Comment by hajimehoshi** [comment]
Specify LineSpacing.

https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2@v2.8.5/text/v2#LayoutOptions

**Comment by vzx** [comment]
Thank you very much for responding so quickly.

Then I would like to suggest that this line of documentation on `Draw` be revised: https://github.com/hajimehoshi/ebiten/blob/52be3859c0a20092ee468aaf4d42855a42d1e8b9/text/v2/layout.go#L69

```
// The '\n' newline character puts the following text on the next line.
```

And/or perhaps an amendment of the example https://ebitengine.org/en/examples/font.html

Since I was unable to intuitively find this option.

**Comment by hajimehoshi** [comment]
Makes sense. Thank you for pointing this out!
