### ISSUE TITLE
Tilt & Accelerometer input

### ISSUE THREAD

**Issue by RileySun** [hajimehoshi/ebiten#3171]
### Operating System

- [ ] Windows
- [ ] macOS
- [X] Linux
- [ ] FreeBSD
- [ ] OpenBSD
- [X] Android
- [X] iOS
- [ ] Nintendo Switch
- [ ] PlayStation 5
- [ ] Xbox
- [ ] Web Browsers

### What feature would you like to be added?

Considering we can build for wasm, would it not be possible to access some kind of tilt & accelerometer inputs?
I'm not sure how different they are from iOS and Android touch api.

### Why is this needed?

Mobile Browser Game Development

**Comment by hajimehoshi** [comment]
Duplicated with #1348, maybe?
