### ISSUE TITLE
Resizable window on desktops by the user's dragging

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#320]

**Comment by otraore** [comment]
Aren't you already able to do this using `SetWindowSize` in the update function like it's done [here](https://github.com/hajimehoshi/ebiten/blob/dc0254db400029cd677c7ab7500062febf9e4704/examples/windowsize/main.go#L86)?

**Comment by hajimehoshi** [comment]
Yep, I know it's possible, but I'm thinking that this breaks assumption that the screen size never changes as long as SetWindowSize is not called. This is just Ebiten API problem.

**Comment by hajimehoshi** [comment]
https://stackoverflow.com/questions/27210379/setting-a-glfw-window-as-not-resizable

Looks like it is impossible to change resizable state later. It is in the same situation as `SetWindowDecorated`

BTW, the window also will be able to be maximized, which causes interesting result when fullscreening is done at the same time :-P

**Comment by hajimehoshi** [comment]
That's unfortunate but resizing window makes 'maximizing' button available, this causes several semantic issues: e.g. what `SetScreenSize` does when the window is maximized? How about changing the scale?

As it is impossible to forbid the maximizing button, I might revert this feature and defer this to 1.10.

**Comment by hajimehoshi** [comment]
> what `SetScreenSize` does when the window is maximized? How about changing the scale?

Probably just ignoring would make sense when the window is maximized.

**Comment by hajimehoshi** [comment]
> Probably just ignoring would make sense when the window is maximized.

Instead, invalidating the maximum state would make more sense.

**Comment by hajimehoshi** [comment]
When resizing the window, should we change the scale instead of the screen size? How about adding an option to choose which the size or the scale will be changed? 🤔 Hmmm

**Comment by hajimehoshi** [comment]
Experimental branch: https://github.com/hajimehoshi/ebiten/tree/issue-320-resize

I started to think that changing only the scale makes more sense than changing the size.

**Comment by hajimehoshi** [comment]
Let's wait for #943. I'm now writing documents.
