### ISSUE TITLE
customizable FPS

### ISSUE THREAD

**Issue by neonmori** [hajimehoshi/ebiten#321]
Can we have the FPS not fixed as 60 and have more flexibility? I am trying to port an old DOS game by using ebiten while that game only runs at 10FPS and with the default 60 fps setup I will have to valve control the repaint process and that creates a huge hassle in code. Thanks.

**Comment by hajimehoshi** [comment]
Thank you for suggestion. I understand you want to avoid redundant drawing, but I was wondering how much code you would need to implement your valve control. If the game's FPS is exactly 10FPS, would this be just using modulo operation?

**Comment by hajimehoshi** [comment]
Introduced `SetTPS()`.

https://godoc.org/github.com/hajimehoshi/ebiten#SetTPS
