### ISSUE TITLE
How to draw some shape by the mesh vertices and triangle data?

### ISSUE THREAD

**Issue by Think-Jumper** [hajimehoshi/ebiten#326]
Hi, author,How to draw some shape by the mesh vertices and triangle data? I want to use the ebiten draw the map which generate by mesh data.

**Comment by hajimehoshi** [comment]
Hi,

Ebiten doesn't expose a notion of mesh for simplicity and I don't plan to do that. I recommend you use other libraries to use OpenGL API directly like:

* https://github.com/go-gl/gl
* https://github.com/faiface/glhf

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen this if you find any other problems.
