### ISSUE TITLE
There is a way to quit a game?

### ISSUE THREAD

**Issue by honix** [hajimehoshi/ebiten#327]
Hi,
I want to quit my game by key. Found nothing about it in api or examples...
```golang
func update(screen *ebiten.Image) error {
	if ebiten.IsKeyPressed(ebiten.KeyEscape) {
		// code to close window
	}
```
How it can be done?
Thanks!

**Comment by hajimehoshi** [comment]
Hi,

There is no direct way, but it is possible like this way:

```go
var Terminated = errors.New("terminated")

func update(screen *ebiten.Image) error {
	if ebiten.IsKeyPressed(ebiten.KeyEscape) {
		return Terminated
	}
        // ...
        return nil
}

func main() {
        if err := ebiten.Run(update, 320, 240, 2, "test"); err != nil {
                if err == Terminated {
                        // Regular termination
                        return
                }
                // Irregular termination
                log.Fatal(err)
        }
}

```

**Comment by honix** [comment]
Got it!
I thought about this solution, but not sure im right.
Thanks for the answer.

**Comment by hajimehoshi** [comment]
Yeah, it is not clear what kind of error `ebiten.Run` returns. I'll add a doc later. Thanks.

**Comment by jacksterdealeo** [comment]
Is there any advantage to that over os.Exit(0)?

**Comment by hajimehoshi** [comment]
`os.Exit(0)` is also fine, but if you need a graceful shutdown like cleaning up after RunGame, I recommend `ebiten.Termination`
