### ISSUE TITLE
graphics: Palette animation

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#330]
There is no idea how to implement this so far.

**Comment by hajimehoshi** [comment]
Note: http://techblog.sega.jp/entry/2017/02/27/100000 (Japanese) palette animation by shader

**Comment by crgimenes** [comment]
In my projects I'm using an array of colors, in my case only 16 but could be any number.

It is very easy to change some colors of this vector, we can even save the modified colors, draw and then return the original palette.

Array
https://github.com/crgimenes/graphos/blob/master/coreGame/screen.go#L38

DrawPix
https://github.com/crgimenes/graphos/blob/master/coreGame/screen.go#L97

**Comment by hajimehoshi** [comment]
Thanks, but in the current Ebiten implementation, `ReplacePixels` would be necessary and this is expensive. I'm thinking another way with help of hardware. That's why I indicated shaders.

**Comment by hajimehoshi** [comment]
Shaders will be introduced.
