### ISSUE TITLE
Terminated with a message `signal: killed` with Xcode 8.3 (8E162)

### ISSUE THREAD

**Issue by crgimenes** [hajimehoshi/ebiten#334]
After update to macOS 10.12.4 (16E195) and Xcode 8.3 (8E162) this morning, I'm geting the following error:

```
go run main.go                                             
signal: killed
```

I deleted the package and reinstalled with:
```
go get -u github.com/hajimehoshi/ebiten
```
But the problem persists.

go version go1.8 darwin/amd64

**Comment by hajimehoshi** [comment]
Thank you, I'm looking into this.

**Comment by hajimehoshi** [comment]
I'm now installing Xcode 8.3. macOS 10.12.4 hasn't come to my machine yet.

What do you see if you do `go run -x main.go`?

**Comment by hajimehoshi** [comment]
What is in `main.go`? Is it possible to create a minimum case to reproduce this?

**Comment by hajimehoshi** [comment]
Reproduced with examples/blocks with Xcode 8.3.

**Comment by hajimehoshi** [comment]
Ugh, this bug can be reproduced without Ebiten!

```
package main

import "C"

func main() {

}
```

``

**Comment by hajimehoshi** [comment]
Already reported https://github.com/golang/go/issues/19734

**Comment by hajimehoshi** [comment]
There seems no workaround that we can do in Ebiten. `-ldflags -s` would work when building as that issue comment says. Let me close this issue.

**Comment by medyagh** [comment]
I get same issue on mac os sierra

**Comment by hajimehoshi** [comment]
Now updating Go to 1.8.1 would solve the problem.
