### ISSUE TITLE
Get the delta time between updates

### ISSUE THREAD

**Issue by crgimenes** [hajimehoshi/ebiten#335]
What is the idiomatic way to get the delta time between ```update(screen *ebiten.Image)``` calls to move images smoothly across the screen or create animations or rotation, etc?

For example, I'm looking for ways to make something like ```position.x -= velocity * deltaTime``` to move an object across the screen at the same speed regardless of FPS or processing speed.

**Comment by hajimehoshi** [comment]
It is guaranteed that `update` is called 60 times per second, so you don't have to measure the delta time. https://godoc.org/github.com/hajimehoshi/ebiten#Run

**Comment by crgimenes** [comment]
Very good, so I'll just do dt = 1/60 this should be enough by now.

**Comment by hajimehoshi** [comment]
That's right!
