### ISSUE TITLE
Drawing a lot of small images drops FPS siginifcantly

### ISSUE THREAD

**Issue by BobbyRaduloff** [hajimehoshi/ebiten#338]
I've tried making a small minesweeper clone to test the library out but hit a wall. A bit of backstory: I was done with the drawing of the board and started adding mouse support. I wrote the mouse code, but sometimes a mouse click wouldn't register or would register in the next second. I checked the `IsRunningSlowly()` function which returned true and realized that my game was running at three FPS. I started looking at the reason and reached the conclusion that the drawing was very slow. I hadn't written anything else in my update function other than it. Here is that function:
```
func update(screen *ebiten.Image) error {
	options := &ebiten.DrawImageOptions{}

	left, _, mx, my := utils.GetMouseState()
	if left {
		fmt.Printf("LEFT! X: %d || y: %d || SLOW?: %t\n", mx, my, ebiten.IsRunningSlowly())
	}

	for i := 0; i < minesHeight; i++ {
		for j := 0; j < minesWidth; j++ {
			switch field[i][j] {
			case minefield.BOMB:
				screen.DrawImage(bombImage, options)
			case minefield.EMPTY:
				screen.DrawImage(emptyImage, options)
			case minefield.FLAG:
				screen.DrawImage(flagImage, options)
			case minefield.UNCLICKEDBOMB:
				screen.DrawImage(unclickedBombImage, options)
			case minefield.CLICKED:
				screen.DrawImage(clickedImage, options)
			default:
				if field[i][j]%minefield.MAGIC != 0 {
					screen.DrawImage(numbersImage[field[i][j]/minefield.MAGIC-1], options)
				} else {
					screen.DrawImage(emptyImage, options)
				}
			}
			options.GeoM.Translate(float64(16), float64(0))
		}
		options.GeoM.Translate(float64(-16*minesWidth), float64(16))
	}
	options.GeoM.Translate(float64(-screenHeight), float64(-screenWidth))
	fmt.Println(ebiten.CurrentFPS())
	return nil
}
```
I presume that the library handles drawing a lot of images slowly, but I might be doing something wrong. What is happening here and is there something I can do about it?

**Comment by hajimehoshi** [comment]
Hi,

Certainly, calling DrawImage too many times might hit the performance. In such cases, I recommend to use `DrawImage` with `ImageParts` to reduce the number of callings. See [API doc](https://godoc.org/github.com/hajimehoshi/ebiten#Image.DrawImage) and [an example using ImageParts](https://hajimehoshi.github.io/ebiten/examples/alphablending.html).

**Comment by hajimehoshi** [comment]
To use `ImageParts`, you'd need to integrate your images like `bombImage` or `emptyImage` into one big image.

**Comment by BobbyRaduloff** [comment]
Thanks! Will try it

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to ask me whenever you find a problem. Thank you.
