### ISSUE TITLE
Add more keys

### ISSUE THREAD

**Issue by crgimenes** [hajimehoshi/ebiten#339]
I'm creating a terminal similar to that of the MSX computers of the 80s.

In this terminal the user will type BASIC commands and for this I need some more keys, like double quotation marks, double quotes, semicolon, etc. But not all keys are implemented.

Is it possible to add the missing keys in the package?

**Comment by hajimehoshi** [comment]
Good point, but my implementation for keys is very conservative. For example, there is no portable way to get 'quote' key between US and Japanese keyboards on browsers: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode. I'm not sure how to add the keys you want with keeping portability so far. Any ideas?

**Comment by hajimehoshi** [comment]
Hm, https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code seems nice, this doesn't work on Edge though. I'll try. Thanks.

**Comment by crgimenes** [comment]
This is a problem because without some keys is impossible to edit text using Ebiten. If you know a hack so that I can read the other keys even without web/mobile support please let me know.

**Comment by hajimehoshi** [comment]
Ugh, Safari will support `code` as of 10.1, which will be released on May this year...

> This is a problem because without some keys is impossible to edit text using Ebiten. If you know a hack so that I can read the other keys even without web/mobile support please let me know.

Well, I understand the problem. My idea is to add keys of US QWERTY keyboards.

**Comment by hajimehoshi** [comment]
I started this work on `more-keys` branch https://github.com/hajimehoshi/ebiten/tree/more-keys. When Safari 10.1 is released, I'll merge this to the master branch.

**Comment by crgimenes** [comment]
For now my application was not intended for web, I'm already very satisfied if it works stand alone on Mac and Linux. I will test the new code ASAP.

Thank you!

**Comment by hajimehoshi** [comment]
I added these keys on `more-keys` branch. Please check the example/keyboard out.

KeyMinus: -
KeyEqual: =
KeyLeftBracket: [
KeyRightBracket: ]
KeyBackslash: \
KeySemicolon: ;
KeyApostrophe: '
KeySlash: /
KeyGraveAccent: `

Please note that these Ebiten keys represent physical keys of US QWERTY keyboards.

**Comment by crgimenes** [comment]
Great!
I'm going to do the tests tonight. (UTC/GMT -3)
With these I can check if shift is pressed and do the others.

Thank you!

**Comment by crgimenes** [comment]
I can capture the keys now but shitf is showing a strange behavior.
Apparently the system does not always detect that the shift key is pressed and as a result, from time to time I get a "=" instead of a "+"

I'm trying something like this:
```
shift = ebiten.IsKeyPressed(ebiten.KeyShift)

if ebiten.IsKeyPressed(ebiten.KeyEqual) {
	if shift {
		println("+")
		return
	} else {
		println("=")
		return
	}
}
```

This is the link to the point in my code where I am capturing the keys if you want to take a look.
https://github.com/crgimenes/metal/blob/master/main.go#L300

Also if possible add the backslash \ in the extra keys.

Thanks for the help!

**Comment by crgimenes** [comment]
I'm investigating the problem.
The example in ebiten/examples/keyboard also presents the problem, the shift is the only key that flashes, the others are solid.

The problem disappears if I hold the two shifts.

**Comment by crgimenes** [comment]
I found the cause of the problem.

The control keys are duplicate values in glfwKeyCodeToKey, to simplify obviously.

```
	glfw.KeyLeftAlt:      KeyAlt,
	glfw.KeyRightAlt:     KeyAlt,
	glfw.KeyLeftControl:  KeyControl,
	glfw.KeyRightControl: KeyControl,
	glfw.KeyLeftShift:    KeyShift,
	glfw.KeyRightShift:   KeyShift,
```

But when the system tries to process the keys to find out which one is processed, one will be pressed and the one on the other side will not. So sometimes the system will show the control key as pressed and sometimes as not. Depends on the order of the vector and the point where the update thread is.

```
func (i *input) update(window *glfw.Window, scale float64) {
.
.
.
for g, e := range glfwKeyCodeToKey {
	i.keyPressed[e] = window.GetKey(g) == glfw.Press
}
```

I have some ideas on how to solve the problem, the simplest is not to simplify the keys and then we would have the right and left key differentiation in ebiten as well.

At the moment I simply commented the left keys and now my code works ... since I use only the right side for the control keys :D

**Comment by hajimehoshi** [comment]
Thank you for investigating! I didn't realize that. I've fixed this bug on `master` and `more-keys` branches. Now shift keys is always recognized pressed whichever side of shift keys is pressed.

**Comment by crgimenes** [comment]
Very good!
I quickly tested here and now this is working as expected.
Now I have a terminal very close to an MSX from the late 80's.

I suggest leaving this issue open until you merge in the main branch.

Thank you for your help!

**Comment by hajimehoshi** [comment]
Awesome! I'm looking forward your product.

> Also if possible add the backslash \ in the extra keys.

I think KeyBackslash exists.

2017年4月11日(火) 12:11 Cesar Gimenes <notifications@github.com>:

Very good!
I quickly tested here and now this is working as expected.
Now I have a terminal very close to an MSX from the late 80's.

I suggest leaving this issue open until you merge in the main branch.

Thank you for your help!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/hajimehoshi/ebiten/issues/339#issuecomment-293137562>,
or mute the thread

**Comment by hajimehoshi** [comment]
I'm thinking of implementing this on master branch now and adding special implementation for Safari.

**Comment by crgimenes** [comment]
I like the idea.

I'm thinking of ways to have other interesting inputs without changing Ebiten directly, for example, for me it's interesting to have mouseButtonUp and mouseDuttonDown, the same thing with the keyboard and other input devices. 

Without this it is more complicated to detect click and double click, or if a key was pressed once or several times. I can simulate these events with little code, but I think I'm going to end up re-creating something that comes ready-made from the hardware.

**Comment by hajimehoshi** [comment]
> I'm thinking of ways to have other interesting inputs without changing Ebiten directly, for example, for me it's interesting to have mouseButtonUp and mouseDuttonDown, the same thing with the keyboard and other input devices.
> 
> Without this it is more complicated to detect click and double click, or if a key was pressed once or several times. I can simulate these events with little code, but I think I'm going to end up re-creating something that comes ready-made from the hardware.

Yeah, actually Ebiten hides hardware details on purpose and offers abstract API so that Ebiten users doesn't have to care about environment in which their game runs. I understand your demand but the current API is minimal and I prefer such minimalistic. If I do, this would be another package to wrap Ebiten's existing input API and emulate hardware-like events.

**Comment by crgimenes** [comment]
> Yeah, actually Ebiten hides hardware details on purpose and offers abstract API so that Ebiten users doesn't have to care about environment in which their game runs. I understand your demand but the current API is minimal and I prefer such minimalistic. If I do, this would be another package to wrap Ebiten's existing input API and emulate hardware-like events.

I also find interesting to keep Ebiten minimalist.

Wrap Ebiten in another package and emulating the hardware events is exactly what I'm doing.
I created the project Graphos to play with these ideas.

https://github.com/crgimenes/graphos

Maybe we can work together on it.

**Comment by hajimehoshi** [comment]
Well, I don't plan to do so far since it seems not so easy to define a common and clean API for that. However, when I need to implement such package, your work would be a great help.

**Comment by hajimehoshi** [comment]
Finally I added the new keys to `master` branch! I'll remove `more-keys` branch in a week or so. Thank you!

**Comment by hajimehoshi** [comment]
Removed `more-keys` branch.
