### ISSUE TITLE
Primitives

### ISSUE THREAD

**Issue by crgimenes** [hajimehoshi/ebiten#341]
Do we have any support for graphic primitives? Lines, circles, etc.

**Comment by hajimehoshi** [comment]
No so far since I'd like to keep the API and implementation simple. I'm not sure but doesn't ReplacePixels work in your case?

**Comment by crgimenes** [comment]
I also like the idea of keeping implementation as simple as possible.
I'm doing the implementation the following way, drawing the pixels in a temporary image and then using ReplacePixels to draw on the screen.

```

func drawPix(x, y int, color byte) {
	pos := 4*y*screenWidth + 4*x
	img.Pix[pos] = CGAColors[color].R
	img.Pix[pos+1] = CGAColors[color].G
	img.Pix[pos+2] = CGAColors[color].B
	img.Pix[pos+3] = 0xff
}

func update(screen *ebiten.Image) error {
.
.
.
	screen.ReplacePixels(img.Pix)
	return nil
}

func main() {
	img = image.NewRGBA(image.Rect(0, 0, screenWidth, screenHeight))
	if err := ebiten.Run(update, screenWidth, screenHeight, 2, "test"); err != nil {
		log.Fatal(err)
	}
}

```

It's working fine for now, but I wonder if that's the best way.

**Comment by hajimehoshi** [comment]
`ReplacePixels` is a heavy task. Using a temporary image is a nice idea, but do you really need to call `ReplacePixels` in every frame?

I remember I created https://github.com/hajimehoshi/ebiten/issues/137 before.

**Comment by crgimenes** [comment]
I believe that I still have not understood correctly the ebiten operation, I believe that I do not need to call ReplacePixels every frame but when I removed the screen it just turns black. In other words, I redesign the whole screen every frame.  What function should I call in update function if there was no change on the screen?

**Comment by hajimehoshi** [comment]
How about:
1. Preparing a temporary image (A) that size is same as the screen.
2. Call `A.ReplacePixels` only when necessary
3. Call `screen.DrawImage` with A every frame

**Comment by hajimehoshi** [comment]
In your case,

```
var tmp ebiten.Image

func init() {
}

func update(screen *ebiten.Image) error {
.
.
.
	screen.ReplacePixels(img.Pix)
	return nil
}
```

**Comment by hajimehoshi** [comment]
In your case, I suggest

```
var tmp ebiten.Image

func init() {
	tmp, _ = ebiten.NewImage(ScreenWidth, ScreenHeight, ebiten.FilterNearest)
}

func update(screen *ebiten.Image) error {
	if when necessary like img.Pix is changed {
		tmp.ReplacePixels(img.Pix)
	}
        screen.DrawImage(tmp, nil)
	return nil
}
```

**Comment by crgimenes** [comment]
I will try this!
Thank you for your help!

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen.
