### ISSUE TITLE
doc: Omit the word 'SNES-style'

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#342]
Ebiten has enough capability for general 2D games, and I started to think I can omit this word. This is not determined yet.

**Comment by crgimenes** [comment]
What about:

A simple and easy to use Go Package to create 2D games

**Comment by hajimehoshi** [comment]
Sounds nice, but I want to use just 'simple' because it's simple :-) So my current idea is:

A simple 2D game library in Go

**Comment by hajimehoshi** [comment]
Done. Also I sent a PR to fix this.
