### ISSUE TITLE
support for 30 FPS?

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#343]
My game is an RPG which does not require 60FPS. I think 30FPS (even 20FPS) can work with my game. It does not seem there is a way to change this with ebiten. The goal here is, to save the battery life as much as possible (Yes, I am running the game on iPhone/Android)

Could you please consider adding the capability of specifying 30 FPS?

**Comment by hajimehoshi** [comment]
Let's take profile in your application before doing this.

**Comment by hajimehoshi** [comment]
This can be emulated without new APIs by skipping drawing at one of two frames.

**Comment by hajimehoshi** [comment]
See #321
