### ISSUE TITLE
Logo for Ebiten

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#350]
EDIT:
The concept is:
* Tempura shrimps
* Minimalism
* 2D game

**Comment by hajimehoshi** [comment]
The current idea: 
![logo](https://cloud.githubusercontent.com/assets/16950/26074136/acc88af6-39eb-11e7-8737-bc82d9ec7701.png)

**Comment by 1l0** [comment]
One-minute job:
![white](http://i.imgur.com/bLsZd0W.png)
![black](http://i.imgur.com/knSi4Xg.png)

**Comment by hajimehoshi** [comment]
Thank you for your suggestion :-)

**Comment by hajimehoshi** [comment]
The current idea:
![logo](https://user-images.githubusercontent.com/16950/29244601-30bcf2ce-7ff7-11e7-951d-e5761ba3495e.png)

**Comment by hajimehoshi** [comment]
The new logo!

![logo](https://user-images.githubusercontent.com/16950/29373033-e08cd672-82e7-11e7-8551-f548a3ba0d8d.png)

I'll update the page to fit the design later.
