### ISSUE TITLE
do you have any performance test on android/ios ?

### ISSUE THREAD

**Issue by fastfading** [hajimehoshi/ebiten#355]
gomobile lib gl app seem to have a performance issue.
the fps is ok on mac but very bad on android.

I wounder if this engine has the performance test

**Comment by fastfading** [comment]
your game inovation 2007 only 52 fps on my android device.
since it is a simple game , I wonder what is the performance if it is a more complicate game

**Comment by hajimehoshi** [comment]
I'm not sure what kind of Android device you are using. Performance depends on it.

**Comment by hajimehoshi** [comment]
> I wounder if this engine has the performance test

Ebiten doesn't have a performance test so far. BTW, on Android, it is very hard to get stable performance results.

**Comment by hajimehoshi** [comment]
Let me close this.
