### ISSUE TITLE
Low FPS at the very beginning of running

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#365]
On any platforms, FPS is about 30 or 40 and the application is very heavy just after launching the application. First I need to take profiling.

**Comment by Zireael07** [comment]
Considering it's OpenGL, it could be shaders compiling?

**Comment by hajimehoshi** [comment]
Yeah that makes sense.

**Comment by hajimehoshi** [comment]
No actionable items
