### ISSUE TITLE
how to build the go-innovation example without android studio installed?

### ISSUE THREAD

**Issue by joeblew99** [hajimehoshi/ebiten#371]
i did 
``` 
brew install gradle 
```
but with the new way android works, i get:
``` 
sdkmanager build 
Warning: Failed to find package build
```
if anyone happens to know :)

**Comment by hajimehoshi** [comment]
Just out of curiosity, why don't you use Android Studio?

**Comment by joeblew99** [comment]
Because i want to make sure it works in CI as part of the build system.
You dont have a GUI there.

Same with Xcode. I use xcrun, etc etc

**Comment by hajimehoshi** [comment]
OK so the problem would be more general: "Is it possible to build Android application without Android Studio on a CI"?

**Comment by joeblew99** [comment]
I caved in and installed android studio :)
