### ISSUE TITLE
audio: Resampling performance is bad on browsers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#385]
Can we use OfflineAudioContext for resampling?

**Comment by gedw99** [comment]
i think so.  I used this webaudio API 3 years and its was pretty slick even then...

**Comment by hajimehoshi** [comment]
Right, I have confirmed how to do that.

**Comment by hajimehoshi** [comment]
Before doing this, noises should be eliminated on mobile browsers...

**Comment by hajimehoshi** [comment]
Found that resampling is already at the same time as MP3 decoding on mobile browsers.
