### ISSUE TITLE
audio: Audio doesn't work well on Linux on Parallels

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#388]
To make matters worse, game loop is too fast since audio clock doesn't work correctly.

**Comment by joeblew99** [comment]
Btw have you seen this ?
https://github.com/dskinner/snd/blob/master/example/rhythm/main.go

**Comment by hajimehoshi** [comment]
No. What is this?

**Comment by joeblew99** [comment]
Well its an audio sequencer. I thought it might be a good reference for the audio work your doing..
Not saying its perfect.. but more that it might help..

**Comment by hajimehoshi** [comment]
I guess this is `oto` problem and `oto` uses ALSA. `oto` basically does the same thing as dskinner/snd.

**Comment by hajimehoshi** [comment]
#1179 might be related.

**Comment by hajimehoshi** [comment]
From my experience, it is hard to fix an issue in Linux VM on Parallels.
