### ISSUE TITLE
Shader precision

### ISSUE THREAD

**Issue by j7b** [hajimehoshi/ebiten#390]
To get mobile package to work on a Kindle Fire I added ```precision mediump float;``` to shaderFragmentTexture, my (possibly faulty) understanding is there may be other implementations that require similar and some preprocessor directives are in order but I'm not clear on the best approach.

**Comment by hajimehoshi** [comment]
Thank you for your advice! I'd like to know what happens without `precision mediump float`

**Comment by j7b** [comment]
I don't have the stack trace handy but the panic was at line 149 of program.go and err was "S0032: no default precision defined for variable" and I think it referred to 0:3 of the shader, ```color.rgb /= color.a;``` and I think that error actually supposed to indicate an operation with undefined precision but I don't know too much about opengl or glsl. I'll try to get full stack trace next time tablet is hooked up.

**Comment by hajimehoshi** [comment]
That's a great information. I don't have a Kindle Fire and it is impossible to me to test this, but I'll fix this as you suggested in a day since adding `precision ...` wouldn't break other platforms. I'll get a (used?) Kindle Fire in a near future if possible.

**Comment by hajimehoshi** [comment]
I'd appreciate if you could test the latest Ebiten. Thanks.

**Comment by j7b** [comment]
Will test soon. I was thinking of setting up something to test/exercise using https://aws.amazon.com/device-farm/ too, seems an easy way to get runtime/render testing and benchmarks for a cross section of devices..

**Comment by hajimehoshi** [comment]
Or probably https://firebase.google.com/docs/test-lab/ ?

**Comment by hajimehoshi** [comment]
ping @j7b: Does this fix work on your Kindle Fire?

**Comment by hajimehoshi** [comment]
I'll close this as fixed. Feel free to reopen.
