### ISSUE TITLE
Test with Firebase Test Lab for Android

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#391]
https://firebase.google.com/docs/test-lab/ There is a free plan.

**Comment by j7b** [comment]
Device Farm also first 1000 minutes/month free. I'm curious to benchmark, especially how many screen-size DrawImage() per update() before IsRunningSlowly() on popular devices.

**Comment by hajimehoshi** [comment]
Interesting, but `IsRunningSlowly` is not a good function for benchmarks. When this function returns true, this just means that the drawing result is not used. As Ebiten's core timer is audio timer, this can be easily true when adjusting gap between OS timer and audio timer.

**Comment by hajimehoshi** [comment]
Tried Test Lab and this was nice.

![img](https://i.gyazo.com/886eab3f847007911aeac27e6eee12ce.png)

I'll revisit this when I need a more concrete test plan.
