### ISSUE TITLE
Projection transformation

### ISSUE THREAD

**Issue by j7b** [hajimehoshi/ebiten#392]
I thought about using a screen-sized *Image as a buffer and using GeoM.Scale() to fit an irregular surfaceview.

It occurred to me it may be possible to apply a GeoM-style implementation of a matrix to the projection, which would allow scaling "screen" x and y separately and allow some interesting effects like rotating and shaking.

A possible implementation would be a global ProjectionM variable with GeoM's method set.

Is this a reasonable train of thought?

**Comment by hajimehoshi** [comment]
I'm not sure I understand what you meant, but you can use an empty large-enough image as a target and draw that to the final target (the screen image passed via the update function) with a GeoM as you like. Isn't this enough?

**Comment by hajimehoshi** [comment]
Here is a pseudo Go code:

```go
var offscreen *ebiten.Image

func init() {
    offscreen, _ = ebiten.NewImage(640, 480, ebiten.FilterNearest)
}

func update(screen *ebiten.Image) error {
    offscreen.Clear()
    if err := updateImpl(offscreen); err != nil {
        return err
    }
    op := &ebiten.DrawImageOptions{}
    op.GeoM.TransformAsYouLike()
    screen.DrawImage(offscreen, op)
    return nil
}

func updateImpl(screen *ebiten.Image) error {
    // write your game here
}
```

**Comment by j7b** [comment]
I've been rethinking this into relative GeoM (GeoM's with parents) and screen-oriented affine transform, both of which I think would be separate PRs. Thank you!
