### ISSUE TITLE
API to get device scale for handling high-DPI mode manually

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#395]

**Comment by joeblew99** [comment]
Detecting DPi is something i need, so that i can then scale everything properly and do constraint based layout.

Is there anything in Ebiten yet for detection of DPI ?

**Comment by hajimehoshi** [comment]
> Is there anything in Ebiten yet for detection of DPI ?

Not so far, and let me think if I should make the API. This is risky because this might break assumptions of Ebiten's graphics system.

**Comment by joeblew99** [comment]
I can see what you mean about risky as you presume a fixed X and Y screen space.
If its really not something you want to put in yet thats OK. I can always try out some ideas in a fork..

**Comment by megapctr** [comment]
In #469 @hajimehoshi said
> Thanks, but let me think a little more about how the new API would be. My concern is to pass 0 to Run might be confusing.

Another API I can think if is `ebiten.RunWithoutDpiScaling(update, 800, 600, "My app")` but that seems too verbose 😕

**Comment by hajimehoshi** [comment]
My concern is not only making `Run` counterintuitive, but also making `SetScreenScale` and `ScreenScale` counterintuitive.

My current idea is to add `IsScreenAutoScaled() bool` and `SetScaleAutoScaled(value bool)`. When `SetScaleAutoScaled(false)` is called, the set scale in `Run` is just ignored. This 'ignoring-scale' behavior is similar to current `SetFullscreen` and `IsFullscreen`.

**Comment by hajimehoshi** [comment]
Now I have implemented on desktops and not on browsers and mobiles. 

I found another concern: if auto-scaling is disabled, what if fullscreen scaling? Probably making the game fullscreen without scaling would be the answer, but this would be the first case that `SetFullscreen` affects the actual screen (`*ebiten.Image` instance) width and height.

**Comment by hajimehoshi** [comment]
Yet another concern: As MacBook (Pro) or iPhone can't render pixel-perfect way, this option might not be useful for 'perfectly-crisp' rendering.

**Comment by hajimehoshi** [comment]
Oh, I came up with much more elegant solution! Assuming we have `DeviceScale()`,

* Pass the invert of device scale (`1 / DeviceScale()`) to `Run`
* Multiply screen width and height with `DeviceScale()` if necessary

As a result, auto scaling by device scale would be invalidated without introducing a new state to Ebiten. What I have to do is add `DeviceScale()`.

@megapctr, do you think this would work in your case?

**Comment by megapctr** [comment]
Wouldn't that stretch the image back and forth? If not then it's neat :) I'll try this in a moment

**Comment by hajimehoshi** [comment]
> Wouldn't that stretch the image back and forth? If not then it's great :) I'll try this in a moment

It's not. Actually the number of scaling is not changed and the final scale (1/devicescale * devicescale = 1 in this case) is just adopted.

**Comment by megapctr** [comment]
I just tried this, works perfectly 👏 Thank you very much!
I'll just hardcode `1 / 1.25` until the new API is shipped :)

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/d18fc36040357143359a1d6af5e527b03b728cb0 Added `DeviceScale()` function experimentally. There is no doc, but I'll add this later.

> I just tried this, works perfectly 👏 Thank you very much!
> I'll just hardcode 1 / 1.25 until the new API is shipped :)

Oh, I'm glad to hear that!

**Comment by megapctr** [comment]
As for the fullscreen issue, I think we'd need to know the screen resolution. Knowing this, if user wants to toggle fullscreen, the `update` func could return a specific `error` which tells our main function to re-run Ebiten with updated dimensions and toggle `ebiten.SetFullscreen`.

Perhaps this code will better explain the idea:

```go
var enableFullscreen = errors.New('enableFullscreen')
var width, height = 800, 600

func main() {
  while true {
    err := ebiten.Run(update, width, height, 1 / ebiten.GetDeviceScale(), "My app")
    if err == enableFullscreen {
      width, height = ebiten.GetScreenResolution() /* new api? */
      ebiten.SetFullscreen(true)
    } else if err != nil {
      panic(err)
    }
  }
}

func update(screen *ebiten.Image) error {
  return enableFullscreen
}
```

By the way, is it even possible for `ebiten.Run` to return nil?

**Comment by hajimehoshi** [comment]
Yeah I agree we need to have a new API for screen resolution. I think we should have another ticket.

> By the way, is it even possible for ebiten.Run to return nil?

This returns nil when the window is closed. IIUC there are not other cases. If you want to terminate the game without errors, you can define an error value, return this in update func, and detect this at `Run`'s return.
