### ISSUE TITLE
OSX touchpad touches not always registering on examples/ui/main.go

### ISSUE THREAD

**Issue by joeblew99** [hajimehoshi/ebiten#399]
i was trying out the new UI example here:
https://github.com/hajimehoshi/ebiten/blob/master/examples/ui/main.go

BTW the text rendering looks very smooth as does the scrolling.

Here are the minor issues on OSX.
1. For the 2 buttons and the checkbox when touching on the touchpad it sometimes works and sometimes does not. There is nothing deterministic at all about how it fails.

2. 2 finder scrolling on the touch bar does not cause the scroll bar to scroll.

**Comment by hajimehoshi** [comment]
Thank you for the reporting.

> 1. For the 2 buttons and the checkbox when touching on the touchpad it sometimes works and sometimes does not. There is nothing deterministic at all about how it fails.

I couldn't reproduce this. Actually, when fingers leave from the touch pad in a little different time, macOS might recognize this as different two clicks.

> 2 finder scrolling on the touch bar does not cause the scroll bar to scroll.

True. This is TBD :-)

**Comment by joeblew99** [comment]
![screen shot 2017-08-04 at 00 07 23](https://user-images.githubusercontent.com/11999859/28945995-16cc833e-78a9-11e7-84ca-a33b7538270c.png)

Are your sure you have the same setup ?

**Comment by hajimehoshi** [comment]
Oh I didn't check 'Tap to click'.

**Comment by hajimehoshi** [comment]
So I enabled 'Tap to click' and tried 1. again, but I couldn't reproduce your situation.

**Comment by 1l0** [comment]
The tap issue might be related on https://github.com/hajimehoshi/ebiten/issues/314.

**Comment by joeblew99** [comment]
Trying to work out whats going on... :)
i just tried the demo again, and noticed that when i click the buttons or checkbox its only the unclicked event that is firing the handler. I woudl have thought it woudl be the onclick event that fire the handler... 

Maybe this has something to do with the touchpad issue too..

**Comment by hajimehoshi** [comment]
Sorry but now I could reduce this. Hmm

**Comment by joeblew99** [comment]
The joy of GUI coding :) no unit tests for it.

I guess I have to make a video

**Comment by hajimehoshi** [comment]
Looks like this is already fixed.
