### ISSUE TITLE
detect locale and remap the key names for the screen

### ISSUE THREAD

**Issue by joeblew99** [hajimehoshi/ebiten#400]
I was playing with this demo in web and OSX, the "Z" key is actually a "Y" key on my keyboard.
So, i guess we need a way of detecting the keyboard locale and then remapping the displayed Key.
So, for my german keyboard, the "Z" text display shoudl say "Y". 

https://en.wikipedia.org/wiki/German_keyboard_layout

https://github.com/hajimehoshi/ebiten/blob/master/examples/hsv/main.go#L67

**Comment by hajimehoshi** [comment]
Thank you for the reporting.

Yeah, Ebiten keys assume US keyboard, so you should remap keys in your game if you want. I know there are differences among German, French, UK, Japanese, US and other keyboards and it is not feasible to accept all of them.

**Comment by joeblew99** [comment]
great - so now its just a matter of detecting the locale at runtime on all platforms ?

**Comment by hajimehoshi** [comment]
Oh I didn't know GLFW had a feature to detect a Unicode character instead of a physical key
http://www.glfw.org/docs/latest/input_guide.html#input_char

Probably it seems the best that Ebiten supports that. Let me think.

**Comment by hajimehoshi** [comment]
> great - so now its just a matter of detecting the locale at runtime on all platforms ?

Yeah I thought that first, but I don't know how to detect this...

**Comment by joeblew99** [comment]
I looked into it.
Going to require some cgo to work on all desktops and mobiles.

I think it's best left out for now. Is better to revisit it if you decide to integrate virtual keyboard support. Then can do the mobile keyboard stuff all in the same package

**Comment by hajimehoshi** [comment]
> Is better to revisit it if you decide to integrate virtual keyboard support. Then can do the mobile keyboard stuff all in the same package

Supporting virtual keyboards on mobiles would be different things. I don't plan to do that so far.

**Comment by joeblew99** [comment]
Fair enough. I think it's quite hard but have found decent examples of how to do it from golang to jni and objc.
If you want I can add the links here as I might not get time to do it myself fully integrated with ebiten..
