### ISSUE TITLE
Make CurrentFPS smoother

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#406]
Now CurrentFPS's value is updated per second. Technically it is possible to update this value every frame. This would break backward compatibility, so we should do this at ver 2.0.

**Comment by megapctr** [comment]
I can't speak for all users, but IME refreshing FPS every second is a good thing. If FPS was updated on each frame, or every few frames, reading it becomes difficult as the number will flicker all the time.

**Comment by hajimehoshi** [comment]
Hm, fair enough.
