### ISSUE TITLE
Extending Ebiten 

### ISSUE THREAD

**Issue by joeblew99** [hajimehoshi/ebiten#409]
There is a go GUI project here that has lots of the things ebiten does not have yet:
https://github.com/gomatcha/matcha/tree/master/layout

Its designed to render using native IOS GUI controls, but everything else is controlled at the golang side.

I see great possibilities of combining ebitne and matcha to make a cross platform gui that has some of the things already in matcha:
- proper layout solver as well as layout components.
- good access to all native stuff needed via protobufs. Responder to open the keyboard on ios. Cut and paste, etc
- react like nesting of controls / widget trees with them only rendering if they are dirty because data has changed or layout has changed.
- the use of protobufs makes it nice to extend to android and desktops for getting high quality development environment so that you can write native code where needed and not get into the complex cross language call issues. 

It has awesome documentation too btw.

Have a look and let me know what you think..

**Comment by hajimehoshi** [comment]
I'm afraid this would not match with Ebiten's policy (minimalism), so I don't tend to support this inside Ebiten. github.com/go-gl/glfw is enough for this purpose on desktops, but you want to make apps on iOS?

**Comment by joeblew99** [comment]
true enough. i cant argue with you that the minimalism in ebiten is great and made it very easy to get going and maintain code. 
But eventually need more:
I need to layout GUI widgets with layout contrainst and also have access to native hward stuff like keyboard and cut and paste.
Need speed and dirty tracking so that widget trees onyl update if they need to
Etc etc.

glfw, shiny do not provide any of these.

Also to answer your question, i want to make GUI for android, ios and desktop and web. Same as Ebiten...

You should have a look at it. Its really impressive..

**Comment by hajimehoshi** [comment]
Please list what you want Ebiten to need to support inside it. I think doing layout should be done outside of Ebiten.

**Comment by joeblew99** [comment]
Ok thanks for your confirmation.

I can play around with using the two together myself.  Will close this as it seems to be resolved
