### ISSUE TITLE
Support blend modes like 'multiply'

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#410]
https://drafts.fxtf.org/compositing-2/#blending

Ebiten supports composite mode (e.g. xor) but not blend mode (e.g. multiply). Is it possible to do the same way as CSS with OpenGL?

**Comment by nanoslayer** [comment]
Hello,

I have been using Ebiten to build a game. The game calculates light information and sends it to a shader, which draws the lighting to the screen. The game then needs to multiply the lighting drawn by the shader with the screen color, but cannot.

As a comparison, Godot allows you to use a shader with different render modes, including multiplicative blend mode.

If you could implement this feature, that would be great!

**Comment by hajimehoshi** [comment]
Sure, let me re-consider how to implement this.

**Comment by nanoslayer** [comment]
I propose adding a new field in `ebiten.DrawImageOptions`. Here's my envisioned use case:

```
// Draw an image with lighten blend mode
op := &ebiten.DrawImageOptions{}
op.BlendMode = ebiten.BlendModeLighten
screen.DrawImage(img, op)

// Draw an image with multiplicative blend mode
op := &ebiten.DrawImageOptions{}
op.BlendMode = ebiten.BlendModeMultiply
screen.DrawImage(img, op)
```

I'm not sure how it would be implemented, though.

**Comment by hajimehoshi** [comment]
In Ebiten, compositing and blending are different. This is the same way as CSS:

https://www.sarasoueidan.com/blog/compositing-and-blending-in-css/

Implementing blending like multiplying is not so trivial in OpenGL unfortunately...

**Comment by SolarLune** [comment]
> Implementing blending like multiplying is not so trivial in OpenGL unfortunately...

Do you mean it's not trivial in OpenGL, or it's not as easy as it is in OpenGL? Because in OpenGL, it should be as easy as just enabling and then setting the blend functions, right?

```
glEnable(GL_BLEND);
glBlendFunc(GL_DST_COLOR, GL_ONE_MINUS_SRC_ALPHA);  
```

Maybe it's different if you're modifying things using a shader first, though.

**Comment by hajimehoshi** [comment]
glBlendFunc is already used for composition like addition. Multiplying source and destination is not trivial. I'd need to use custom shader maybe.

**Comment by hajimehoshi** [comment]
> glBlendFunc(GL_DST_COLOR

Ah this might work, but I'm not sure multiplying premultiplied alpha color values...

**Comment by nanoslayer** [comment]
I believe this is possible with premultiplied alpha color values. https://en.wikipedia.org/wiki/Alpha_compositing#Straight_versus_premultiplied

Does OpenGL handle this automatically?

**Comment by nanoslayer** [comment]
@SolarLune Do you happen to know which operators correspond with each blend mode? The full list is here: https://drafts.fxtf.org/compositing-1/#blendingseparable

So far I have:

- Normal: `ONE`, `ONE`
- Multiply: `DST_COLOR`, `ONE_MINUS_SRC_ALPHA`

**Comment by hajimehoshi** [comment]
> From my testing, it seems that glBlendFunc(GL_DST_COLOR, GL_ONE_MINUS_SRC_ALPHA) works with premultiplied alpha, and achieves the desired effect.

As long as we follow the CSS blending/compositing way, this calculation would not be correct, unfortunately. I was wondering if there are evidence or documentation to support this calculation. If there is one and this doesn't conflict with the current compositing way, I'd be happy to accept this.

P.S. Probably another way is to expose an API to specify values to glBlendFunc directly.

**Comment by nanoslayer** [comment]
What exactly about the calculation would be incorrect? I'm not very familiar with CSS blending.

**Comment by hajimehoshi** [comment]
CSS blending assumes that the colors are straight-alpha colors.

https://drafts.fxtf.org/compositing-1/#blending

> The blending calculations must not use pre-multiplied color values.

**Comment by nanoslayer** [comment]
I wonder if it still gives the correct results, though.
Say I had a color of (1, 1, 1, 0.5), which would become (0.5, 0.5, 0.5, 0.5) in premultiplied alpha.
I want to multiply it by (0.5, 0.5, 0.5, 0.25), which would become (0.125, 0.125, 0.125, 0.25) in premultiplied alpha.
If I multiply the straight alpha colors, I get (0.5, 0.5, 0.5, 0.125).
If I multiply the premultiplied alpha colors, I get (0.0625, 0.0625, 0.0625, 0.125). Reverting to straight alpha gives me back (0.5, 0.5, 0.5, 0.125).

Therefore I believe that multiplying premultiplied alpha values should work. Not sure about the other blend modes, though. I only really need Multiply and Lighten blend modes.

**Comment by nanoslayer** [comment]
Here's a quick proof that multiplication works:

straight alpha:
(r1, g1, b1, a1) * (r2, g2, b2, a2) = (r1r2, g1g2, b1b2, a1a2)

premultiplied:
(r1a1, g1a1, b1a1, a1) * (r2a2, g2a2, b2a2, a2) = (r1a1 * r2a2, g1a1 * g2a2, b1a1 * b2a2, a1a2)
then back to straight alpha by dividing (r, g, b) by a1a2:
-> ((r1a1 * r2a2) / (a1a2), (g1a1 * g2a2) / (a1a2), (b1a1 * b2a2) / (a1a2), a1a2)
= (r1r2, g1g2, b1b2, a1a2)

Therefore we can prove that multiplying straight alpha and premultiplied alpha produces the same color.

**Comment by nanoslayer** [comment]
I think I can see how premultiplied alpha can be problematic for the lighten blend mode, though.

**Comment by hajimehoshi** [comment]
Thank you for proving! This seems correct.

> glBlendFunc(GL_DST_COLOR, GL_ONE_MINUS_SRC_ALPHA)

The result would be:

```
co = (αb × Cb) × αs × C_s + (1 - αs) × αb × Cb
αo = αb × αs + (1 - αs) × αb
```

On the other hand, from the general formula for blending/compositing: https://drafts.fxtf.org/compositing-1/#generalformula

```
co = αs × Fa × Cs_after_blending + αb × Fb × Cb
   = αs × Fa × ((1 - αb) × Cs + αb × B(Cb, Cs)) + αb × Fb × Cb // Cs_after_blending = (1 - αb) × Cs + αb × B(Cb, Cs)
   = αs × ((1 - αb) × Cs + αb × B(Cb, Cs)) + αb × (1 - αs) × Cb // Fa = 1, Fb = 1-αs (source over)
   = αs × (1 - αb) × Cs + αs × αb × B(Cb, Cs) + αb × (1 - αs) × Cb
   = αs × (1 - αb) × Cs + αs × αb × Cs × Cb + αb × (1 - αs) × Cb // B(Cb, Cs) = Cs × Cb
```

So the first term `αs × (1 - αb) × Cs` is extra. This means that your suggestion would not match with the CSS model. However, I tend to think it is OK to accept your suggestion as 1) multiplying is definitely useful and 2) your suggestion doesn't break our current existing implementation and 3) the calculation seems correct for premultiplied alpha colors, even though this would no longer follow the CSS rule.

Give me more time to think.

> Lighten

Which blend mode in CSS would be the same?

> I think I can see how premultiplied alpha can be problematic for the lighten blend mode, though. Perhaps for that I'll need to write a really simple custom shader, like I had done in Godot. The only thing that would be really tedious to implement in a shader is multiplicative blend mode.

Well, as I am implementing shaders, would it be possible to wait for that, and make your PR only for multiplying?

**Comment by hajimehoshi** [comment]
Interesting. Android's mixes composite modes and blend modes including multiplying 

https://developer.android.com/reference/android/graphics/PorterDuff.Mode#MULTIPLY

**Comment by hajimehoshi** [comment]
To follow the Android way instead of the CSS way,

```
glBlendFunc(GL_DST_COLOR, GL_ZERO)
co = αs × Cs × αb × Cb
α0 = αs × αb
```

would make more sense. However, the concern is that when the source alpha is 0, the result's alpha is also 0. This might be a little hard to use.

@nanoslayer, what do you think?

**Comment by nanoslayer** [comment]
> Thank you for proving! This seems correct.

No problem!

> Which blend mode in CSS would be the same?

https://drafts.fxtf.org/compositing-1/#blendinglighten
This can be implemented in a custom shader with a simple call to `max(color1, color2)`. So I don't really see a need to add it to Ebiten.

> would make more sense. However, the concern is that when the source alpha is 0, the result's alpha is also 0. This might be a little hard to use.

I think this might not work for my use case. When I multiply the colors I would like for any transparent areas in the source not to be drawn. If I am understanding correctly, this would mean that any areas with alpha=0 in the source would be erased from the destination?

**Comment by hajimehoshi** [comment]
> would it still make sense to have a BlendMode parameter in Ebiten? Or should the API change since we are only implementing multiply blend mode?

I think we don't have to add BlendMode besides CompositeMode. Based on the discussion and Android's API, we can add 'multiply' as a new composition value.

> If I am understanding correctly, this would mean that any areas with alpha=0 in the source would be erased from the destination? 

Yes, that's correct. I understand this is less useful.

> Perhaps that could be resolved by using CompositeModeSourceAtop?

Does this assume that blend mode is added besides the composite mode?

**Comment by nanoslayer** [comment]
> I think we don't have to add BlendMode besides CompositeMode. Based on the discussion and Android's API, we can add 'multiply' as a new composition value.

Sure, that is good with me.

> Yes, that's correct. I understand this is less useful.

Now that I think about this more I believe that this is desired behavior. It also did not cause a problem in my testing.

**Comment by hajimehoshi** [comment]
> Now that I think about this more I believe that this is desired behavior. It also did not cause a problem in my testing.

Sorry but I'm confused. Which idea is better to you?

1. `glBlendFunc(GL_DST_COLOR, GL_ONE_MINUS_SRC_ALPHA)`
2. `glBlendFunc(GL_DST_COLOR, GL_ZERO)`

**Comment by nanoslayer** [comment]
> Sorry but I'm confused. Which idea is better to you?

I tested the second option (2) and it seems to work well for my use case. So I think the Android way (`glBlendFunc(GL_DST_COLOR, GL_ZERO)`) should be fine.

**Comment by hajimehoshi** [comment]
Thanks! We have reached the agreement to add a new composition value 'CompositeModeMultiply', which indicates `glBlendFunc(GL_DST_COLOR, GL_ZERO)`! I'm happy to review your PR.
