### ISSUE TITLE
input: IsKeyJustPressed and other counterparts

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#415]
`IsKeyJustPressed` returns true only when the given key is just pressed, in other words, the key is not pressed in the previous frame and is pressed in the current frame.

Whereas this would be very useful, I don't want to add to `ebiten` package. I'm thinking of creating a new package or adding it to `ebitenutil`.

**Comment by megapctr** [comment]
It's possible to implement by the developer. Here's how I did it...
```
var pressedKeys = map[ebiten.Key]bool{}

func update(screen *ebiten.Image) error {
    if ebiten.IsKeyPressed(ebiten.KeyF11) {
        if !pressedKeys[ebiten.KeyF11] {
            // Key has been pressed
            ebiten.SetFullscreen(!ebiten.IsFullscreen())
        }
        pressedKeys[ebiten.KeyF11] = true
    } else {
        pressedKeys[ebiten.KeyF11] = false
    }
}
```

I wonder how expensive would it be to run this for every key in every frame? Perhaps there's an internal API that can make it simpler?

**Comment by hajimehoshi** [comment]
Yes, and this issue is to offer utility so that Ebiten users don't have to implement it themselves.

> I wonder how expensive would it be to run this for every key in every frame? Perhaps there's an internal API that can make it simpler?

The cost should not be expensive as the number of keys is not so big. I'm still not sure whether this API should be implemented internally or not.

**Comment by hajimehoshi** [comment]
Almost done

https://gist.github.com/hajimehoshi/25e97956da5c8e39221882201be37cd9

* Who calls `Update`? Should Ebiten users call this explicitly, or Ebiten calls this internally?
* Is there a better name for `PressingFrames`?

**Comment by megapctr** [comment]
I think Ebiten should call this internally. Otherwise (as I understand), if user calls `IsKeyJustPressed`, it'll always return `false because `keyStates` is empty.

As for the name, `PressDuration` could be a good name too.

**Comment by hajimehoshi** [comment]
Thank you for the great advice!

**Comment by hajimehoshi** [comment]
Done!
