### ISSUE TITLE
audio/mp3: monaural can't work with decode_js.go

### ISSUE THREAD

**Issue by j7b** [hajimehoshi/ebiten#421]
Chrome console:
```Failed to execute 'getChannelData' on 'AudioBuffer': channel index (1) exceeds number of channels (1)```

because

```
	oc.Call("decodeAudioData", js.NewArrayBuffer(b), func(buf *js.Object) {
		s.leftData = buf.Call("getChannelData", 0).Interface().([]float32)
		s.rightData = buf.Call("getChannelData", 1).Interface().([]float32) // <- not has
		close(ch)
	})
```

**Comment by hajimehoshi** [comment]
Does this work on desktops?

**Comment by j7b** [comment]
It was ok on desktop. Here's actual file it choked on.
[powerup.zip](https://github.com/hajimehoshi/ebiten/files/1254472/powerup.zip)

**Comment by hajimehoshi** [comment]
Thank you, fixed
