### ISSUE TITLE
ARM Architecture?

### ISSUE THREAD

**Issue by shingtaklam1324** [hajimehoshi/ebiten#429]
xgo gives an error to do with go-gl

**Comment by hajimehoshi** [comment]
Please tell me what commands you executed.

As for go-gl, go-gl requires Cgo and xgo might not work well without a C lib for the architecture you specified (ARM?). I've not tried xgo anyway.

**Comment by hajimehoshi** [comment]
Related issue: https://github.com/faiface/pixel/issues/53

**Comment by shingtaklam1324** [comment]
`xgo --targets=linux/arm` yields

`
In file included from ./glfw/src/internal.h:169:0,
                 from ./glfw/src/context.c:28,
                 from ../github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:
./glfw/src/x11_platform.h:36:22: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
                      ^
compilation terminated.
# github.com/go-gl/gl/v3.3-core/gl
../github.com/go-gl/gl/v3.3-core/gl/procaddr.go:52:21: fatal error: GL/glx.h: No such file or directory
  #include <GL/glx.h>
                     ^
compilation terminated.
`

**Comment by hajimehoshi** [comment]
So you should install X and GL first. See https://github.com/hajimehoshi/ebiten/wiki/Linux

**Comment by shingtaklam1324** [comment]
I ran `sudo apt-get install libglu1-mesa-dev libgles2-mesa-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev libasound2-dev` but still no luck with cross-compiling, same error is still present

**Comment by hajimehoshi** [comment]
Hmm, probably this is not a problem in Ebiten but xgo or go-gl. Sorry but I cannot help you with the question.
