### ISSUE TITLE
ui: Frameless window

### ISSUE THREAD

**Issue by constrom** [hajimehoshi/ebiten#430]
Hi !

is there a way to open screen frameless ? In this case, How can we minimize or close it ?

**Comment by hajimehoshi** [comment]
Hi,

No, Ebiten doesn't have such feature. I don't think this is not so useful since, as you expected, it would be hard to close the window. Do you really want that?

**Comment by constrom** [comment]
Yeah It could be a nice feature. Some games have a frameless mode, but we must have access to it. Goal of this future is to create desired UI / UX for window

here is an exemple of what we can do : 

![capture](https://user-images.githubusercontent.com/6690149/30344872-4bf3bbbc-9803-11e7-9703-dbd2761b1786.PNG)

**Comment by hajimehoshi** [comment]
Ah, I understood. Thank you for elaborating (the image is very helpful to me to understand what you want). Let me consider to implement that.

**Comment by constrom** [comment]
In this case (just to create a launcher), we should use another technical solution as [golang-nw](https://github.com/lonnc/golang-nw). Can you consider to implement

**Comment by hajimehoshi** [comment]
Hm, in the current stable GLFW version 3.2, glfwSetWindowAttrib is not introduced yet http://www.glfw.org/docs/3.3/group__window.html#gace2afda29b4116ec012e410a6819033e. This means that borderless property must be defined before the game starts and Ebiten can't have SetDecorated function that can be called anywhere. Hmm...

**Comment by hajimehoshi** [comment]
Implemented `SetWindowDecorated` and `IsWindowDecorated`. `SetWindowDecorated` must be called before `Run` so far. I'll fix this problem after GLFW is updated.
