### ISSUE TITLE
graphics: Implement GeoM/ColorM.Apply

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#432]
@j7b's request

Apply multiplies a vector with the matrix.

**Comment by hajimehoshi** [comment]
As for ColorM, because ColorM should be used for straight-alpha RGBA colors, the API would take color.Color, not four float64 values to avoid confusion.

**Comment by j7b** [comment]
ColorM.Apply has less utility (I can't think of a practical use case for Apply on a Color) so from my perspective the issue can be closed with my thanks.
