### ISSUE TITLE
Support mpeg versions other than 1

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#435]
It seems ebiten cannot play certain mp3 files in mpeg format other than 1.

```
mp3: only MPEG version 1 (want 3; got 2) is supported
```

This means, we cannot always expect MP3 we download from the internet to work all the time, this is pretty inconvenient. Currently I am looking for a way to convert MPEG version on my own, but it would be nice if ebiten can support multiple versions. Please let me know if I should open this issue for another repository.

**Comment by hajimehoshi** [comment]
Hi, Please report this at hajimehoshi/go-mp3

**Comment by hajimehoshi** [comment]
Context: we've already talked this problem each other, so I closed this issue
