### ISSUE TITLE
Error when using `go build` on Fedora Linux 26

### ISSUE THREAD

**Issue by hunterkepley** [hajimehoshi/ebiten#441]
```
[hunter@localhost test-game]$ go get github.com/hajimehoshi/ebiten
[hunter@localhost test-game]$ go build
# _/home/hunter/Documents/Programming/Go/test-game
/usr/bin/ld: $WORK/libglfw.a620294411(c_glfw_linbsd.cgo2.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//usr/lib64/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

```

I've installed every prerequisite you've asked and have a fully updated Fedora 26.

**Comment by hajimehoshi** [comment]
Disclaimer: I've not tested Fedora yet. I'll check it later as soon as possible. I guess order of `-l` is wrong somewhere. Thank you for reporting.

Similar error: https://forums.fedoraforum.org/showthread.php?t=79355

**Comment by hunterkepley** [comment]
Issue seems to be solved, installing gcc-go on Fedora sets it to the default compiler. Uninstalling it via `dnf remove go-gcc` allows me to compile. Closing.

**Comment by hajimehoshi** [comment]
No problem, I'm really glad that the problem has been solved!
