### ISSUE TITLE
Small resolutions cause the window to not open

### ISSUE THREAD

**Issue by Insood** [hajimehoshi/ebiten#444]
Hello, I've come across an issue where screen resolutions that are too small cause the window to not open with a "ui: Fail to set the screen size" error.

Resolution that don't work: 224x256
Resolution that work: 256x256, 256x224

Here's a test case:

```
package main

import (
	"fmt"

	"github.com/hajimehoshi/ebiten"
)

func update(screen *ebiten.Image) error {
	fmt.Println("Starting to draw frame")
	return nil
}

func main() {
	f := func(screen *ebiten.Image) error {
		fmt.Println("Starting to draw frame")
		return nil
	}
	runErr := ebiten.Run(f, 256, 224, 1, "Space Invaders")
	fmt.Println("Exited run() with error: ", runErr)
}
```

I'm using windows 10.

It's a bit of a trivial issue since I won't be using this resolution in the final product, but it was _amusing_ to come across. If this is a wontfix type issue, maybe a warning or a note in the docs would be nice?

**Comment by hajimehoshi** [comment]
Thank you for reporting. I admit there is an arbitrary limitation for window width.

https://github.com/hajimehoshi/ebiten/blob/master/internal/ui/ui_glfw.go#L514

And as you said, kinder error or warning should be necessary. Probably I'll fix this by adding a function to know the limitation.

**Comment by hajimehoshi** [comment]
I fixed this without warning or errors. Now even 16x16 window is allowed.
