### ISSUE TITLE
Linux > Windows Cross Compiled Binary Fails

### ISSUE THREAD

**Issue by AlmightyFloppyFish** [hajimehoshi/ebiten#445]
When i try to cross compile from Ubuntu 16 LTS to Windows it compiles successfully however when i try the exe on windows it doesn't do anything. All that happens is that a cmd window opens and closes instantly with no output.
To clarify, the program works perfectly on Linux from source and as compiled binary.

$ go env
`GOARCH="amd64"
GOBIN=""
GOEXE=".exe"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="windows"
GOPATH="/home/simon/Code/go/"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="x86_64-w64-mingw32-gcc"
GOGCCFLAGS="-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build529257225=/tmp/go-build -gno-record-gcc-switches"
CXX="x86_64-w64-mingw32-g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"`

**Comment by hajimehoshi** [comment]
I've not tested cross compiling. As Ebiten uses GLFW, I guess it is impossible to do that so far. How did you do that?

**Comment by AlmightyFloppyFish** [comment]
Why would using GLFW make it impossible? GLFW is multiplatform.

"How did you do that?"
I installed https://github.com/golang/sys/tree/master/windows and then ran go build with the go env specified above

Sense the executable doesn't work afterall, You might be correct in that it isn't possible. I didn't get any error during compiling though

**Comment by AlmightyFloppyFish** [comment]
Not sure what MessageBoxW is because I'm no expert. I have however cross compiled this way with other similar libraries like pixel and ui. The linux build-essentials package includes some windows compilers which I'm using (x86_64-w64-mingw32-gcc) and (x86_64-w64-mingw32-g++).

**Comment by hajimehoshi** [comment]
Ok, so how were the other libs? Did they work on Windows as you expected?

2017年10月20日(金) 16:34 Floppy <notifications@github.com>:

**Comment by AlmightyFloppyFish** [comment]
Yep, They were exactly the same as in Linux except for system borders etc.

**Comment by hajimehoshi** [comment]
Thanks, I'll look into this more later.

**Comment by AlmightyFloppyFish** [comment]
Cross compiling suddenly works. Most likely failed due to either human error or broken installation.
