### ISSUE TITLE
Question: is there any api to get the gamepad list?

### ISSUE THREAD

**Issue by qiukeren** [hajimehoshi/ebiten#447]
In `ebiten.IsGamepadButtonPressed(id,key)` here is a parameter called id,
which indicates the gamepad id.

So, is there any api to get the gamepad list? Or any suggesting library ? or none that i should find it myself?

**Comment by hajimehoshi** [comment]
Hi qiukeren,

Unfortunately no so far. I'll add such function as soon as possible. Thank you.

Note (for myself): glfwJoystickPresent is the function for the purpose http://www.glfw.org/docs/latest/group__input.html#gaffcbd9ac8ee737fcdd25475123a3c790

**Comment by qiukeren** [comment]
good job!

**Comment by hajimehoshi** [comment]
Done: added `IsGamepadPresent`.

**Comment by hajimehoshi** [comment]
I started to think this function should be `GemepadIDs`
