### ISSUE TITLE
graphics: Add DrawImageOptions.DestinationRect

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#454]
This is related to #398

**Comment by clebs** [comment]
Hi!

If I understand this feature correctly, I will be able to skew my drawing right?
something like: https://zackbellgames.com/2014/11/11/sprite-skewing-for-procedural-animation/

**Comment by clebs** [comment]
I see, then I probably did misunderstand this...

I do not have much knowledge about graphics rendering, so I am not sure, but I think #624 is what I am looking for.

I want to be able to stretch/bend an image. I am implementing this:
https://www.aurelienribon.com/post/2012-06-tutorial-animated-grass-using-libgdx 

Excuse me if I am not seeing how to do this in the current `GeoM`.

Thanks!

**Comment by hajimehoshi** [comment]
> I want to be able to stretch/bend an image. I am implementing this:
> https://www.aurelienribon.com/post/2012-06-tutorial-animated-grass-using-libgdx

This is actually 'linear' skewing represented by a matrix, so you can do this with the current Ebiten API :-)

Feel free to ask me whenever you have a question.

**Comment by clebs** [comment]
I will try it with `GeoM` then!

Thanks for your quick response 😄

**Comment by hajimehoshi** [comment]
#726 is the same task.
