### ISSUE TITLE
How to do hit tests / detect collisions?

### ISSUE THREAD

**Issue by megapctr** [hajimehoshi/ebiten#465]
Hi! I just completed the tutorial on the wiki and everything seemed very straightforward so far. Unfortunately I got stuck trying to detect when two Images/GeoMs overlap.

I think I could detect collisions if I accessed `GeoM.impl.tx/ty` somehow, but I don't see any way to do so. Perhaps I should use one of GeoM math methods instead?

**Comment by megapctr** [comment]
I tried looking at how other projects using ebiten handle this and it looks like they all keep track of the x/y coordinates manually. This feels redundant though...

**Comment by hajimehoshi** [comment]
Hi, thank you for using Ebiten!

Are `GeoM`'s `Element(2, 0)` and `Element(2, 1)` what you want? I am not sure what collisions mean here.

**Comment by megapctr** [comment]
Yes, I simply want to check for intersections. `GeoM.Element(0, 2)` gives me the X position, and `GeoM.Element(1, 2)` gives me the Y position. Thanks :)

**Comment by hajimehoshi** [comment]
Great. Note that `Element(2, 0)` and `Element(2, 1)` return the translate part of the GeoM, and if the GeoM includes scaling and rotating, detecting collision can't be done only with the translate part.
