### ISSUE TITLE
mobile: Reduce CPU power usage

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#468]
As we don't have measurement, there are no concrete action items so far, but I feel like mobile apps with Ebiten tend to consume more CPU power than necessary.

**Comment by lei-cao** [comment]
2048 game example is 100+ CPU on Mac. Some of my other app is also 100+ CPU.

**Comment by hajimehoshi** [comment]
Interesting. How about other apps (especially using GLFW)?

**Comment by hajimehoshi** [comment]
Close this until we find concrete action items.
