### ISSUE TITLE
Text rendering issues on high-dpi displays

### ISSUE THREAD

**Issue by megapctr** [hajimehoshi/ebiten#469]
I'm rendering text using `freetype/truetype`, `image/font` and `ebiten/text`, as per the [font example](https://hajimehoshi.github.io/ebiten/examples/font.html). I'm using Windows 10 with 125% UI scaling, and the displayed text is blurry. The text looks great if I switch the scaling to 100% or manually change `ui.deviceScale` to return `1.0`

I think that UI scaling should be handled by the app, instead of the library. This allows the app to produce crisp images whenever possible.

Here's one way to implement this change:
Ignore `deviceScale` internally and instead expose it as `func ebiten.GetDeviceScale() float64`. If the developer wishes to use the old-style scaling, they'd have to do:
```diff
-ebiten.Run(update, 800, 600, 1, "My app")
+ebiten.Run(update, 800, 600, ebiten.GetDeviceScale(), "My app")
```

Optionally, the scale value of `0` (which is invalid by the way) could be passed to implicitly use the device scale. (although this would add more complexity for no tangible benefit)

**Comment by hajimehoshi** [comment]
Thank you for the reporting!

This problem is probably same as https://github.com/hajimehoshi/ebiten/issues/395, where you want to disable automatic scaling in Ebiten. Is this correct? Now the current Ebiten doesn't this high-DPI mode intentionally to make Ebiten apps work samely on as many platform as possible.

I plan to do this feature in the future, but I was worried this might break the current assumptions (so I set the milestone 2.0). I didn't check this carefully so my worry might not be valid.

As there is a demand for this feature, I'll re-consider this feature as high priority.

> Ignore deviceScale internally and instead expose it as func ebiten.GetDeviceScale() float64. If the developer wishes to use the old-style scaling, they'd have to do:

Unfortunately this breaks the current API so I can't do such change.

**Comment by hajimehoshi** [comment]
> Optionally, the scale value of 0 (which is invalid by the way) could be passed to implicitly use the device scale. (although this would add more complexity for no tangible benefit)

Passing 0 to disable automatic scaling might be a good idea :-)

**Comment by megapctr** [comment]
Thanks! If I could disable auto scaling and then get device scale (e.g. by making `deviceScale()` public), it would be perfect.

**Comment by megapctr** [comment]
Should I try making a PR for this? 😃

**Comment by hajimehoshi** [comment]
> Thanks! If I could disable auto scaling and then get device scale (e.g. by making deviceScale() public), it would be perfect.

I'm thinking getting a device scale can be a separate Go package since this can be useful for any application. Not decided yet though.

> Should I try making a PR for this?

Thanks, but let me think a little more about how the new API would be. My concern is to pass 0 to `Run` might be confusing.

**Comment by hajimehoshi** [comment]
I'll integrate this issue into #395. Let's continue discussing there.

**Comment by Distortions81** [comment]
I can't get ebiten to draw unscaled in windows 10, so fonts are blurry.
Additionally, CPU usage is 2-3% on windows, and extremely high on Linux (50-100%)... when the app should be mostly idle.

**Comment by hajimehoshi** [comment]
Could you try to make your game be scaled along with hi-dpi?

https://github.com/hajimehoshi/ebiten/blob/master/examples/highdpi/main.go#L102-L107 is an example explaining how to do it.

**Comment by Distortions81** [comment]
Thanks for the response, this did fix the win10 scaling.
I'm still working/testing with the other issues.
I think ebiten is using the xorg dpi, but ignoring the global scaling.

**Comment by hajimehoshi** [comment]
On Linux, getting scales might not be implemented correctly

https://github.com/hajimehoshi/ebiten/blob/master/internal/devicescale/impl_unix.go
https://github.com/hajimehoshi/ebiten/issues/471

**Comment by Distortions81** [comment]
Thanks :) I'll take a look at fixing KDE scaling when I have the time.
