### ISSUE TITLE
Utility for TMX format

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#478]
http://doc.mapeditor.org/en/latest/reference/tmx-map-format/

**Comment by Pavel1986** [comment]
Hi, just curious, does this feature is planned to be delivered?

**Comment by hajimehoshi** [comment]
Not planned. I feel like this should be done in another package if we do.

**Comment by Noofbiz** [comment]
Engo currently has one but it's a couple versions behind latest and doesn't have all the features yet. It's also very integrated into the package. I think I'm going to try breaking it out so it can be used outside of engo as well as bringing it up to date with the latest version.

**Comment by hajimehoshi** [comment]
That's nice! It'd be the best the TMX lib would be independent from rendering layer.

Let me close this ticket since this would not be implemented in Ebiten directly in any cases.
