### ISSUE TITLE
How to get started

### ISSUE THREAD

**Issue by ShizuCarry** [hajimehoshi/ebiten#479]
I've tried to start with the engine but i din't undersand how to start, i've tried what is recommended but i always get this result:  http://prntscr.com/i0190r
Any idea about what i missed.
And where can i found doc about how to export my games ?
(i've also tryied on linux and got something similar)

**Comment by AlmightyFloppyFish** [comment]
This project uses cgo and therefore requires certain compilers. 

If you're running on Linux then this should fix your issues
`sudo apt install build-essential`
(Only works on debian based systems, on Arch systems use: `sudo pacman -S base-devel`)

I think you'll need this on windows.
http://tdm-gcc.tdragon.net/download
Make sure you check the checkbox "Add to path" during installation

**Comment by hajimehoshi** [comment]
If you are using Windows, the document https://github.com/hajimehoshi/ebiten/wiki/Windows would be helpful.

**Comment by hajimehoshi** [comment]
Let me close this. Feel free to reopen if you find another problem.
