### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by ArmaniL** [hajimehoshi/ebiten#480]
Installation went well. but every attempt to run an executable just ends up in a black screen.I`ve tried the examples and it happens with them too
![screenshot](https://user-images.githubusercontent.com/35434507/34920973-68ad7eee-f949-11e7-85cd-0827af58e24f.png)

**Comment by megapctr** [comment]
Since you closed this issue, I assume it is resolved. What was the problem?

**Comment by ArmaniL** [comment]
Turns out I was running it in my virtual machine,which is why nothing was
showing up.I am very sorry
