### ISSUE TITLE
ebiten: ReplacePixels should take []color.RGBA instead of []byte

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#488]

**Comment by hajimehoshi** [comment]
At least, this would require wasm ver or `[]color.RGBA` would be really inefficient.

**Comment by gabstv** [comment]
Hi! Would it still be inefficient to use []color.RGBA? I created a small test, but with using a (very) dirty unsafe trick to test the possibility os having `[]color.RGBA` on the ReplacePixels API:
```go
// extracted from reflect
type sliceHeader struct {
	Data uintptr
	Len  int
	Cap  int
}

func (i *Image) ReplacePixelsEx(fatpixels []color.RGBA) {
	i.copyCheck()

	if i.isDisposed() {
		return
	}
	r := i.Bounds()

	len4 := len(fatpixels)

	shdr := (*sliceHeader)(unsafe.Pointer(&fatpixels))
	shdr.Len = len4 * 4
	shdr.Cap = len4 * 4

	pixels := *(*[]uint8)(unsafe.Pointer(&fatpixels))

	// Do not need to copy pixels here.
	// * In internal/buffered, pixels are copied when necessary.
	// * In internal/shareable, pixels are copied to make its paddings.
	if err := i.buffered.ReplacePixels(pixels, r.Min.X, r.Min.Y, r.Dx(), r.Dy()); err != nil {
		theUIContext.setError(err)
	}

	// fix the slice header because it might be used by the caller
	shdr = (*sliceHeader)(unsafe.Pointer(&fatpixels))
	shdr.Len = len4
	shdr.Cap = len4

	return
}
```

It feels very wrong but the tests passed 🤷‍♂️
Anyways, it was just an experiment

**Comment by hajimehoshi** [comment]
Thanks! Using unsafe would solve the performance concerns. My concern was GopherJS, where you cannot use unsafe.

I'll revisit this issue when Ebiten suspends to support GopherJS. (I think this will come when Ebiten's major version becomes v2).

BTW, I'm not confident `[]color.RGBA` is really a good API compared to `[]byte`

**Comment by hajimehoshi** [comment]
I don't see an obvious benefit so far. Mark this wontfix.
