### ISSUE TITLE
iTerm2 version

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#493]
It looks like iTerm2 can show images.

(Inspired by https://sausheong.github.io/posts/space-invaders-with-go/)

**Comment by hajimehoshi** [comment]
A good thing of this is that this would not require cgo.

**Comment by peterhellberg** [comment]
The perfomance of rendering images in iTerm2 is (in my experience) fairly bad. But maybe it has improved recently.

**Comment by hajimehoshi** [comment]
Thanks!
