### ISSUE TITLE
text: Used fonts are never discarded

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#498]
As text package manages glyph cache with a map that key is `font.Face` instance, different glyph cache is created for different `font.Face` instance. Thus, for example, if a `font.Face` object is created every frame and used at `text.Draw`, this consumes unnecessarily a lot of cache (textures).

**Comment by hajimehoshi** [comment]
Another problem is that text package holds `font.Face` instances and never releases. My current idea is to set a timer to delete a ref to `font.Face` a few minutes (or hours?) after the instance is used at the last time.

**Comment by explodes** [comment]
My game is affected, in javascript versions only, in that the current workaround in [uniqFace(face font.Face) calls reflect.DeepEqual](https://github.com/hajimehoshi/ebiten/blob/master/text/text.go#L126) takes a very, very long time to process exactly one one of the four fonts I use: [DampfPlatz.ttf](https://www.dafont.com/dampfplatz.font)

**Comment by explodes** [comment]
Using `GlyphCacheEntries = 1` in `truetype.Options` removes a significant amount of time reflect.DeepEquals takes, but there is still a heavy delay when reusing a font face.

```go
	face := truetype.NewFace(f, &truetype.Options{
		Size:              size,
		GlyphCacheEntries: 1, // The workaround
	})
```

**Comment by hajimehoshi** [comment]
I think this is a different problem from this issue, so I'll file another one

**Comment by hajimehoshi** [comment]
One idea is to remove `font.Face` when all the glyphs of the face become old enough. What is an appropriate threshold? For example, 5 mins (= 1800 frames) is a good enough number?

**Comment by explodes** [comment]
Seems reasonable enough to me to have a goroutine running that will perform the periodic cleanup. 

5 minutes is decent enough estimate, as well. I'll keep on eye out for any performance hits that happen every 5 minutes

**Comment by explodes** [comment]
I think it is reasonable to have a goroutine performing cleanup. 5 minutes sounds like a reasonable default, but maybe it is worth making this cleanup value configurable. The value could be used for any other cleanup that might be added, though AFAIK only Faces/glyphs are of concern right now

**Comment by hajimehoshi** [comment]
BTW is this issue actually a problem to you? I'm curios since in most cases a few of faces are used in one game and the face set usually never changes in the life of the process, right?

**Comment by explodes** [comment]
The cache definitely does introduce a memory leak, but I don't think this area is where we would see the highest wins in terms of memory or performance.

**Comment by hajimehoshi** [comment]
This was resolved by text/v2.
