### ISSUE TITLE
ebitenutil: Replace go-bindata usages with some substitutions

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#499]
https://www.reddit.com/r/golang/comments/7vv9zz/popular_lib_gobindata_removed_from_github_or_why/

**Comment by Noofbiz** [comment]
That repo was actually unmaintained and wasn't updated for years before it was deleted. There was an issue on the old repo pointing to https://github.com/shuLhan/go-bindata as an actively maintained fork

**Comment by hajimehoshi** [comment]
Thanks. My current idea is to make a much simpler one by myself and use it since the current go-bindata usages should not be so complicated.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/file2byteslice Done. That's enough (at least to me).
