### ISSUE TITLE
scenes

### ISSUE THREAD

**Issue by arxdsilva** [hajimehoshi/ebiten#523]
Hi!

I was wondering if you already have some kind of scene management or intend to add it. Right now the way I see to make it happen is overwriting the update function to draw the next screen. Maybe it'd be better to make it more explicit for the lib, I also can provide help implementing it.

Keep on the good work!

**Comment by hajimehoshi** [comment]
Hi,

I'm not sure what kind of function or struct you want. Isn't it enough e.g. [a Scene interface in examples/blocks](https://github.com/hajimehoshi/ebiten/blob/master/examples/blocks/blocks/scenemanager.go#L33)? 

Thank you!

**Comment by arxdsilva** [comment]
Hi! Yes, that is it. Any chance to making it a part of the platform?

**Comment by hajimehoshi** [comment]
I tend not to want to add such scene system to Ebiten since scene system is a kind of upper later thing and I'd want to keep Ebiten as 'dumb' thing as possible. I think it is not hard to make it yourself, isn't it?
