### ISSUE TITLE
graphics: Optimization: is it possible to embed color matrix info into vertices?

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#531]
If this is possible, the number of draw calls would be much smaller.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/tree/colorm (Note that I might rebase this branch later)

On my MacBook Pro, I found some FPS drop from 55 FPS to 45 FPS with about 8000 sprites of examples/sprites. Let's wait for WebAssembly work (#528).

**Comment by hajimehoshi** [comment]
I think this is necessary for particle animations

**Comment by hajimehoshi** [comment]
Hmm, it is still slow on examples/sprites. (about 30 or more FPS on Chrome with 10000 sprites). Embedding all the color matrices data to vertices is too heavy.

Another idea is to pass multiple color matrices to the fragment shader as uniform variables, and make vertices have 'index' to one of the color matrices.

**Comment by hajimehoshi** [comment]
Yet another idea is to compress 20 float32 values into smaller array. It's ok even if it is lossy compression.

**Comment by hajimehoshi** [comment]
Only 8 float32 values for each vertex made `vertices` function slow... (40 FPS with 10000 sprites?)

Would it be feasible to replace `vertices` with asm.js or WebAssembly implementation?

**Comment by hajimehoshi** [comment]
I think adding 4 float32 values for each vertex would be allowed (I'm still not sure but let me do experiments later). If just scaling colors by ColorM is common enough, how about

1) fixing ColorM into scaling part and other part
2) embedding four scaling colors for vertex and
3) using them only when ColorM’s non-scale part is default

?

As for 2), if the ColorM doesn't have scaling part, we can skip embedding.

@seebs, what do you think? I was wondering if scaling is really common enough.

**Comment by hajimehoshi** [comment]
I started to think to simply add color values to vertices regardless of ColorM as @seebs suggested (probably), because I plan to add a new function to specify vertices directly to draw something on an image, and this would enable to change the color for each vertex, which is what @seebs wanted before as far as I remember.

**Comment by seebs** [comment]
I think scaling color is a particularly common application compared to translation or hue-rotation.

I would love a general vertex-specifying thing. I would also be super interested in a thing that would allow specifying the *type* of vertexes -- say, allowing triangle strips. (I'm not sure whether that's actually useful, but I think it would at least be nice to have something flexible enough that it became possible, because I'd like to benchmark triangle strips as an alternative way to render large polylines.)

**Comment by hajimehoshi** [comment]
> I would also be super interested in a thing that would allow specifying the type of vertexes 

Doesn't this require exposing shaders at the same time? I don't plan this though... (Mac/iOS tries to deprecate OpenGL and I plan to move to Metal, and shader languages are different).

**Comment by seebs** [comment]
I don't think it should require that, necessarily. You should be able to use the same shader with both triangle strips and regular triangles. I think you're doing quads, currently, and that's 4 vertexes per quad instead of 6 per two triangles, but I am not actually sure how much that differs in performance; I've seen claims that because triangles are the more common case, some hardware will do them enough faster that it's actually more efficient to just send triangles.

**Comment by hajimehoshi** [comment]
Let me confirm: what did you mean by types of vertices? I thought this meant something to decide whether vertices include color info or original info or not.

**Comment by seebs** [comment]
Hmm. That might not be insane; you couldn't do it fully generically, but you could handle with/without color data, perhaps, by having different prebuilt shaders for them.

But I was thinking quads vs. triangle strips, etcetera, so people who are writing their own vertices directly can write fewer of them for some use cases.

**Comment by hajimehoshi** [comment]
> But I was thinking quads vs. triangle strips, etcetera, so people who are writing their own vertices directly can write fewer of them for some use cases.

Ah that makes sense. Now quads are drawn as triangles with 4 vertices and 6 indices as two triangles. Two vertices are shared and this is specified by the indices. The new function I am planning accepts not only vertices but also indices, so I think this is what you want.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/tree/issue-531-color

Perhaps I've succeeded to embed all the values of a color matrix... @seebs , could you test this branch when you're available? Thanks!

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/tree/colorm-revert Experimental revert

**Comment by hajimehoshi** [comment]
Confirmed: on go-inovation, the FPS was

60 on colorm-revert
40+ on master

CC @wasedaigo

**Comment by hajimehoshi** [comment]
This is unfortunate, but the performance drop was inevitable. Let's revert this.
