### ISSUE TITLE
graphics: Texel violation with linear filter

### ISSUE THREAD

**Issue by Shnifer** [hajimehoshi/ebiten#546]
Edge glitches appears when i draw an image with not FilterDefault and not (45n) angle of rotation.
Is this a known issue?
![1](https://user-images.githubusercontent.com/35039664/37243354-e52aa7fc-2488-11e8-9a93-998bb88839e5.png)

**Comment by hajimehoshi** [comment]
I think it's a bug. I'd be glad if you could give me a minimum code to reproduce this.

**Comment by hajimehoshi** [comment]
And what machine are you using? If GPU is different, it might be hard to reproduce on my machine.

**Comment by Shnifer** [comment]
A few interesting details was found while composing minimum code. Here it is:
```
import (
	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/ebitenutil"
	_ "image/jpeg"
	_ "image/png"
)

var img *ebiten.Image

func update(image *ebiten.Image) error {
	op := &ebiten.DrawImageOptions{}
	op.GeoM.Rotate(0.234)           //random non 45-degree angle
	op.GeoM.Translate(100, 100)     //just for a fine pic, not important
	op.Filter = ebiten.FilterLinear //non DefaultFilter here needed
	image.DrawImage(img, op)
	return nil
}

func main() {
	//order is important: first load drawable image
	img, _, _ = ebitenutil.NewImageFromFile("ship.png", ebiten.FilterLinear) //non DefaultFilter here needed
	filter := ebiten.FilterDefault                                           //any, doesn't matter

	//then load another image
	//no matter png or jpg
	//as you see we do not do anything with it later
	//ebitenutil.NewImageFromFile("small.png", filter) without variable do the same
	img2, _, _ := ebitenutil.NewImageFromFile("small.png", filter)
	_ = img2

	ebiten.Run(update, 800, 800, 1, "minitest")
}

```

This error appears with any drawable images. 
But not any img 2 files cause a problem: it has to be non-transparent, and probably larger than 128x128. Nature of image doesnt matter, filled rectangle is enough.
This may be important: color is glitches is equal to color of img2 flood color! 
![scrshot2](https://user-images.githubusercontent.com/35039664/37244572-306f78a6-249c-11e8-82d1-56b7cc2115b4.png)
May it be some wicked effect with texture packaging when linear filter grabs an edge pixel of adjacent texture?

My system: Win7x64, Radeon HD 7800 series
i do not include images, cz first may be any of size ~100-400 px, and second is easy to generate, but i will attach it on first request

**Comment by hajimehoshi** [comment]
Thank you for the helpful information!

> This may be important: color is glitches is equal to color of img2 flood color!
> May it be some wicked effect with texture packaging when linear filter grabs an edge pixel of adjacent texture?

Your guess is right. Ebiten tries to share GL textures for multiple image instances as much as possible.

> My system: Win7x64, Radeon HD 7800 series
> i do not include images, cz first may be any of size ~100-400 px, and second is easy to generate, but i will attach it on first request

OK, I don't have Radeon HD machine, but I'll try this on another Windows machine.

**Comment by Shnifer** [comment]
Got same result with Win7x64 GForce GTX 560Ti

**Comment by hajimehoshi** [comment]
Looks like there was a bug in the linear filter. Could you update and take a look? Thank you!

**Comment by Shnifer** [comment]
Yay! Dat works! Thanks for fast response )

**Comment by hajimehoshi** [comment]
Great! Thank you very much for the bug reporting!
