### ISSUE TITLE
graphics: Replace an original struct with image.Rectangle at DrawImageOptions.SourceRect

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#549]
* `image.Rect` function causes copying, which is really problematic on browsers
* Making an `image.Rectangle` and taking a pointer is annoying.

My current idea is to create `SourceRect` struct and use this like:

```go
op := &ebiten.DrawImageOptions{}
op.SourceRect.Set(x0, y0, x1, y1) // It's ok even if SourceRect is nil
```

`DrawImageOptions`'s `SourceRect` type is `*SourceRect`, not `SourceRect` since it'd be confusing what zero-value mean: Should zero `SourceRect` mean using a whole image, or nothing (0, 0, 0, 0)? To avoid confusing, let's use pointer where `nil` means not specifying a source rect and using a whole image.

**Comment by hajimehoshi** [comment]
Now `SubImage` is the better way.

**Comment by bah2830** [comment]
@hajimehoshi is SubImage only available in the subimage branch at the moment?

**Comment by hajimehoshi** [comment]
`SubImage` is available on the master branch. (Not 1.8 branch)
