### ISSUE TITLE
New example with a physics engine like Box2D

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#550]
e.g. https://github.com/ByteArena/box2d

**Comment by hajimehoshi** [comment]
Blocker: https://github.com/ByteArena/box2d/issues/6

**Comment by jakecoffman** [comment]
you could rewrite one of these examples from my Chipmunk2D port instead: https://github.com/jakecoffman/cp/tree/master/examples

**Comment by hajimehoshi** [comment]
@jakecoffman Just out of curiosity, what's the difference from https://github.com/vova616/chipmunk ? Yours looks better since yours is a little more active project.

**Comment by jakecoffman** [comment]
Back before I did the port I tried using vova616 to implement the tank demo in the official Chipmunk2D examples and I was getting strange collision results. The tanks would collide and then spin uncontrollably. So I think it might not be an accurate or complete project. There are some missing joints as well. 

Mine has all of the examples implemented and I compared them to the C version for accuracy.

**Comment by jakecoffman** [comment]
I made this if you are interested in copying it into your project as a physics demo: 

https://github.com/jakecoffman/cpebiten

The gopherjs version is really slow for some reason!

**Comment by hajimehoshi** [comment]
That's really awesome! I think the calculation is too heavy for browsers and wasm might solve this in the future.

* Is it OK to adopt Apache 2.0 License to cpebiten?
* Would you mind creating a PR to add your cpebiten to Ebiten's examples? If you are busy, I'm fine with doing that instead of you.

**Comment by jakecoffman** [comment]
Apache 2.0 is good. I can make a PR right now!

**Comment by hajimehoshi** [comment]
Close per https://github.com/hajimehoshi/ebiten/pull/572

**Comment by hajimehoshi** [comment]
[![Screenshot from Gyazo](https://gyazo.com/7e4e08d3780ffaa8af4614d60aa6ac10/raw)](https://gyazo.com/7e4e08d3780ffaa8af4614d60aa6ac10)

Looks like copying objects is the biggest CPU consumer.
