### ISSUE TITLE
Taking screenshot without modifying game code

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#553]

**Comment by hajimehoshi** [comment]
* Signal?
* Environment Variable to specify a key?

**Comment by hajimehoshi** [comment]
Another problem: this forces Ebiten to import `image/png`, which is not what I want to do (#519 )

**Comment by silbinarywolf** [comment]
Not sure how nicely this works on Mac setups, but default key could be `KeyPrintScreen`? (Currently not exposed via `ebiten` library, but is at least available in GL.

**Comment by hajimehoshi** [comment]
PrintScreen key makes sense, I've not decided yet though (PrintScreen key might be hard to find in some keyboards like MacBook Pro).

Thank you for your PR!

**Comment by silbinarywolf** [comment]
Would you even need such a feature on a Mac considering it just has a button that pushes print screen images to your desktop?
https://support.apple.com/en-au/HT201361

**Comment by hajimehoshi** [comment]
This is close but what I want is to save the screen (`*ebiten.Image` object) to a PNG image file at any timing, thus window frames would not be included in the result image.

**Comment by hajimehoshi** [comment]
See also https://github.com/hajimehoshi/ebiten/wiki/FAQ#how-to-take-a-screenshot

**Comment by hajimehoshi** [comment]
Implementation is almost done and the remaining thing is to define the key.

I thought PrintScreen is a good idea, but tbh now I don't think since PrintScreen should be used by OS.

**Comment by hajimehoshi** [comment]
Added a feature to specify the screenshot key with `EBITEN_SCREENSHOT_KEY` environment variable. You can now take a screenshot like this:

`EBITEN_SCREENSHOT_KEY=escape go run examples/flappy.go`

**Comment by hajimehoshi** [comment]
Note: Adding a new key like PrintScreen is still fine. I'm waiting for a PR :-)
