### ISSUE TITLE
vorbis: Player plays audio for twice the duration of sample

### ISSUE THREAD

**Issue by windo** [hajimehoshi/ebiten#570]
This is sort of a continuation of https://github.com/hajimehoshi/ebiten/issues/569.

Using that same basic example program and example .ogg file, the audio plays for twice the duration of sample. In that example, the recap_1.ogg is about 8s longs but player plays 8 seconds of audio followed by 8 seconds of silence.

I don't immediately follow how the doubling and halving of byte counts is supposed to work so maybe this change breaks something else (stereo? my sample is mono), but the `Player` appears to play for the correct duration if I change the `decoded.totalBytes` calculation from multiplication of `* 4` to `* 2`:

https://github.com/hajimehoshi/ebiten/blob/master/audio/vorbis/vorbis.go#L165

Output with `totalBytes` `* 4` (current value):
```
2018/03/29 21:34:35 Player time: 0.0
2018/03/29 21:34:35 Starting player
2018/03/29 21:34:51 Player time: 16.4
2018/03/29 21:34:51 Starting player
```

Output with `totalBytes` `* 2`:
```
2018/03/29 21:32:57 Player time: 0.0
2018/03/29 21:32:57 Starting player
2018/03/29 21:33:05 Player time: 8.2
2018/03/29 21:33:05 Starting player
```

Slightly modified example to log play times:

```go
package main

import (
	"log"
	"os"

	"github.com/hajimehoshi/ebiten"
	"github.com/hajimehoshi/ebiten/audio"
	"github.com/hajimehoshi/ebiten/audio/vorbis"
)

var (
	ac     *audio.Context
	player *audio.Player
)

func loadAudio(path string) (*audio.Player, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	stream, err := vorbis.Decode(ac, f)
	if err != nil {
		return nil, err
	}
	return audio.NewPlayer(ac, stream)
}

func update(screen *ebiten.Image) error {
	if !player.IsPlaying() {
		log.Printf("Player time: %.1f", player.Current().Seconds())
		player.Rewind()
		log.Printf("Starting player")
		player.Play()
	}
	return nil
}

func main() {
	ac, _ = audio.NewContext(48000)
	player, _ = loadAudio("test.ogg")
	if err := ebiten.Run(update, 100, 100, 1, "vorbis test"); err != nil {
		log.Fatalf("Failed to run: %v", err)
	}
}
```

Audio example: https://p6drad-teel.net/~windo/tmp/recap_1.ogg

**Comment by hajimehoshi** [comment]
> (stereo? my sample is mono)

Ah right, that code assumed that the source is stereo. I need to fix that. Thank you for reporting!

**Comment by hajimehoshi** [comment]
Fixed. I think I'll add tests later.

**Comment by windo** [comment]
Confirmed, works here too. Thanks again!
