### ISSUE TITLE
Background service

### ISSUE THREAD

**Issue by gedw99** [hajimehoshi/ebiten#584]
I am having trouble working out how to run some of the code as a background service. 

As I understand it I need to build with gomobile bind and then have to correct code for iOS and Android to wrap it in.

Has anyone done this ?
I think the plist and Android manifest needs to have some different settings.

Then there is how the foreground and background apk needs to be bundled to hold both APK's. I am presuming this is how it should be packaged but am just guessing. If someone knows about this or has some tips it would help.

I can upload the code on GitHub if it helps !

If your curious the game runs as a foreground app and talks to the background service over grpc.
The background service has a db and asset store to allow need game levels to be loaded in the background as needed.

**Comment by hajimehoshi** [comment]
Hi,

> As I understand it I need to build with gomobile bind and then have to correct code for iOS and Android to wrap it in.

Yes, and now you can also use `gomobile build`. https://github.com/hajimehoshi/ebiten/wiki/Mobile

> Then there is how the foreground and background apk needs to be bundled to hold both APK's. I am presuming this is how it should be packaged but am just guessing.

I'm not sure what you want? Ebiten just updates the GL surface when `Update` is called, and that's it. Ebiten doesn't do anything special related to background.

**Comment by gedw99** [comment]
thanks for the response.

i did some research in the last hour. It seems that the backgroudn service
is actually the same package as the foregroudn gui service with an intent
linking them.
I think the backgroudn will have to be built manually and then i will use
protobufs between the Foreground and Background.

I think we should close this as its really not relevant now for Ebiten ?

**Comment by hajimehoshi** [comment]
Yeah if you want to do something on background, you would need to write code on Java/ObjC, and this would not be related to Ebiten. Let me close this.
