### ISSUE TITLE
affine: pretty-print GeoM/ColorM

### ISSUE THREAD

**Issue by seebs** [hajimehoshi/ebiten#586]
Because the GeoM/ColorM parts of DrawOptions are opaque to users, %v doesn't do anything very useful trying to print those members. Luckily, fmt has hooks for defining custom display routines for things. I'd like to propose adding interface implementations so that the objects satisfy Formatter, and can do printouts in some useful way.

The idea would be for `fmt.Printf("%v", op.GeoM)` to produce... well, anything useful, really.

**Comment by hajimehoshi** [comment]
My concern is that there is no example to implement `fmt.Formatter` except for the standard lib.

Isn't implementing `Stringer` a good start?

**Comment by seebs** [comment]
Formatter looks pretty straightforward to me. Stringer could also work, but I was thinking specifically that since there's floating point values, being able to specify width/precision seemed useful.

**Comment by hajimehoshi** [comment]
Fair enough. Let's implement like this:

GeoM: `fmt.Sprintf([[%v, %v, %v], [%v, %v, %v]], a, b, tx, c, d, ty)` where `%v` is an appropriate format
ColorM: `fmt.Sprintf([[%v, %v, %v, %v, %v], [%v, %v, %v, %v, %v], [%v, %v, %v, %v, %v], [%v, %v, %v, %v, %v]]), e(0, 0), e(0, 1), e(0, 2), ... e(3, 3), e(3, 4)` where `%v` is an appropriate format and `e(i, j)` is an element at (i, j).

https://golang.org/pkg/math/big/#Float.Format would be a good example of implementation.

**Comment by hajimehoshi** [comment]
@seebs Do you want to create a PR? :-)

I feel like `fmt.Sprintf` should be used instead of re-implementing the float number format as each element is just a float64.

**Comment by seebs** [comment]
Yes, was gonna use sprintf. My thought was roughly to use %*.*f, passing in width and precision from the format. So if you printed a GeoM with "%5.2f", it would print all its members with %5.2f.

The reason to use Formatter, rather than Stringer, is so we can forward the width/precision on.

**Comment by hajimehoshi** [comment]
I was wondering why. Would this really slow?

**Comment by seebs** [comment]
Doing it the fancy way I was thinking of would be pretty slow, I think. Unless I missed a thing. Doing it without user control over formatting/appearance would be simpler and faster.

**Comment by hajimehoshi** [comment]
How slow? Have you measured the actual performance??

**Comment by seebs** [comment]
I haven't, yet. I'm thinking about how to benchmark it. I'm guessing performance on printing is pretty irrelevant either way, but also I was busy this week so I haven't had a chance to do much with it.

**Comment by hajimehoshi** [comment]
I think such performance difference doesn't matter for usual usages, while just a `String` function without configuration would be fine.

**Comment by hajimehoshi** [comment]
@seebs I'll implement `String` soon if you are not working on this right now.
