### ISSUE TITLE
Enable to switch off the FPS adjuster to rely on display's vsync

### ISSUE THREAD

**Issue by yodamerlin** [hajimehoshi/ebiten#605]
Ability to specify some higher frame rate. Lower frame rates can be achieved by manually skipping frames. But as far as I am aware currently it wouldn't be possible to use higher frame rates such as 120fps or 144fps, which some monitors can provide.

This is not too important however it would help with future proofing.

**Comment by hajimehoshi** [comment]
Thank you for the suggestion. While logical FPS is always 60 in Ebiten regardless of the display's FPS, Ebiten does vsync and calculate how many logical frames are updated for each vsync. I think what you want is to change the logical FPS to the same as the display's FPS.

Related:

https://github.com/hajimehoshi/ebiten/issues/321: Customizable (logical) FPS
https://github.com/hajimehoshi/ebiten/issues/405: Enable to switch off vsync (for triple buffer)

**Comment by wanton7** [comment]
Related to this I would like to do a simple hobby game using Ebiten and would like to use frame rate interpolation technique described here https://gafferongames.com/post/fix_your_timestep/

This will make game play run smoothly in any display frame rate by running your game with virtual frame rate eg. 60fps and interpolating between previous and current frame to actual frame rate. Is there a way to remove 60fps limit from Ebiten or can I use my own game loop without this limit and still use Ebiten?

I would also need to check if vsync is enabled or not, if it's not then run game without interpolation.

**Comment by hajimehoshi** [comment]
Hi, thank you for using Ebiten.

I think your suggestion makes sense. Let me think to add functions to switch the logical-FPS-adjuster that forces 60 FPS now and detect if this is on or off. Note that this is just a plan, and I might change the plan in the future.

**Comment by hajimehoshi** [comment]
Now vsync is switchable: https://github.com/hajimehoshi/ebiten/issues/405

So the rest thing would be to disable logical-fps adjuster?

**Comment by hajimehoshi** [comment]
My current idea is to introduce`SetLogicalFPS(fps number)` (or a better name) to set the fps. If the specified number is -1, logical FPS adjustment is disabled. This solves this issue and #321 at the same time.

**Comment by hajimehoshi** [comment]
Introduced `SetTPS()`

https://godoc.org/github.com/hajimehoshi/ebiten#SetTPS

If a negative number like -1 is given, TPS is unfixed and the game is updated along with display's refresh rate.

**Comment by eliveikis** [comment]
What's the proper way to limit FPS to a max *and* have `SetTPS(-1)`?

**Comment by hajimehoshi** [comment]
`ebiten.SetFPSMode(FPSModeVsyncOffMaximum)` and `ebiten.SetTPS(ebiten.SyncWithFPS)`
