### ISSUE TITLE
Enable the test with GopherJS again

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#615]
This would be necessary to port to Wasm.

**Comment by hajimehoshi** [comment]
Wondering if headless-chrome is available.

**Comment by Noofbiz** [comment]
There's phantomjs http://phantomjs.org

**Comment by hajimehoshi** [comment]
Thanks. I'm trying to use [puppeteer](https://github.com/GoogleChrome/puppeteer). It looks like there is a [bug](https://github.com/gopherjs/gopherjs/issues/817) on GopherJS side (?) though.

**Comment by hajimehoshi** [comment]
https://github.com/myitcv/gjbt would be helpful

**Comment by hajimehoshi** [comment]
Close this and move on #618
