### ISSUE TITLE
ClockOfAtonement - translation to other languages

### ISSUE THREAD

**Issue by jhinrichsen** [hajimehoshi/ebiten#616]
Hi Hajime,

i just started to translate to german, but there is one problem. The english text sometimes refers to "it". In english "it" can refer to all of it/the car,  it/the dog and it/the cat. In german, it is "es/das Auto", "ihn/der Hund", "sie/die Katze", i.e. each and every thing has a gender specific article. Without knowing what "it" refers to, it is not possible to properly translate the proper so-called "article".

**Comment by hajimehoshi** [comment]
CC @wasedaigo, the original author of CoA

**Comment by hajimehoshi** [comment]
Hi Jochen,

Thank you for cooperating of translating our game! For your question, @wasedaigo would have a better answer :-)

Thanks!

**Comment by wasedaigo** [comment]
@jhinrichsen you can play the game for the best quality translation. However if you do not have time, you can leave comments on each cell so that I can provide you with a better context. Thank you.
