### ISSUE TITLE
[Request] make 'tx' and 'ty' globally accessible

### ISSUE THREAD

**Issue by DomLankutis** [hajimehoshi/ebiten#619]
This would allow the user to keep track of the objects position without having to create their own variables and so on...

**Comment by hajimehoshi** [comment]
Hi,

Thank you for requests, but I'm not sure what you mean by `tx` and `ty`.

**Comment by DomLankutis** [comment]
From what I can see ```Geom``` has a function called ```String()``` that prints ```tx``` and ```ty``` which are the 2 position vectors (from my understanding)

This code is located in ```/go/src/github.com/hajimehoshi/ebiten```
lines 33 - 37:
```go
// String returns a string representation of GeoM.
func (g *GeoM) String() string {
	a, b, c, d, tx, ty := g.impl.Elements()
	return fmt.Sprintf("[[%f, %f, %f], [%f, %f, %f]]", a, b, tx, c, d, ty)
}
```

**Comment by hajimehoshi** [comment]
How about `(*GeoM).Element(0, 2)` and `(*GeoM)Element(1, 2)`?

**Comment by DomLankutis** [comment]
Lol should've read up a bit more thanks for that....

**Comment by hajimehoshi** [comment]
No problem :-)
