### ISSUE TITLE
Use Metal on macOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#621]
https://developer.apple.com/macos/whats-new/

> Deprecation of OpenGL and OpenCL

**Comment by hajimehoshi** [comment]
This would mean I would need to give up using GLFW.

https://github.com/kovidgoyal/kitty/issues/972

It looks like Apple is really doing this.

**Comment by hajimehoshi** [comment]
I plan to use @shurcooL's https://dmitri.shuralyov.com/gpu/mtl

See also https://dmitri.shuralyov.com/blog/26

**Comment by hajimehoshi** [comment]
Current status: https://github.com/hajimehoshi/ebiten/tree/metal

Most rendering part has been implemented.

Remaining tasks:
* [MUST] Blending function
* [MUST] Correct memory management
* [WANT] Better performance by synchronization
* [WANT] Context lost? (Does this happen?)

**Comment by Noofbiz** [comment]
Are you still using glfw 3.2 or something else for the window?

**Comment by hajimehoshi** [comment]
I'm still using GLFW 3.2 as 'No API' mode. The application runs with a Cocoa window without OpenGL initialization and context. Metal's rendering works on the Cocoa window.

For more details, @dmitshur's https://dmitri.shuralyov.com/gpu/mtl/example/movingtriangle is a great example.

**Comment by hajimehoshi** [comment]
Most of them are implemented. Now I'm fixing a bug that screen flickers on fullscreen mode.

**Comment by hajimehoshi** [comment]
Now all the examples worked correctly!
