### ISSUE TITLE
graphics: Spine animation

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#626]
This requires #624 

http://ja.esotericsoftware.com/spine-json-format
https://pixijs.io/examples/#/spine/dragon.js

**Comment by hajimehoshi** [comment]
Oh, this doesn't require triangles? Not sure...

**Comment by aynakeya** [comment]
any progress on this spine animation

**Comment by hajimehoshi** [comment]
No progress.

**Comment by aynakeya** [comment]
I was looking at the Spine C runtime http://esotericsoftware.com/spine-c#Implementing-Rendering.

Given that *Image already implements DrawTriangle, would it be feasible to use the C runtime via cgo for controlling Spine and then making custom rendering based on C runtime?

**Comment by hajimehoshi** [comment]
I'm not familiar with the C runtime, so I have no idea to be honest. If the runtime just calculates vertices and Ebitengine can render them, I think this works by Cgo.

**Comment by aynakeya** [comment]
Thanks! I'll give it a try and see if it works.

**Comment by hajimehoshi** [comment]
Sure!

As this is a pretty old issue and there is no action item on the Ebitengine side, I'll close this issue. (i.e. I don't plan to provide Ebitengine API to treat Spine)
