### ISSUE TITLE
input: Implement `Wheel` for browsers

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#630]
This is a remaining task of https://github.com/hajimehoshi/ebiten/pull/628

**Comment by PSteinhaus** [comment]
btw: I forgot to add the TODO comment I was talking about to `input_js.go` for `ResetScrollValues()`, so I just comment on it here ;)

**Comment by hajimehoshi** [comment]
Thanks :-)

**Comment by hajimehoshi** [comment]
@PSteinhaus I'll rename this from `MouseWheel` to `Wheel` since this should work with non-mouse devices (e.g. touchpad). I was misunderstanding when I reviewed the PR. Sorry for the confusion.
