### ISSUE TITLE
Invalid rendering on iOS (Wasm)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#631]
http://hajimehoshi.github.io/go-inovation/wasm/

![img_3018](https://user-images.githubusercontent.com/16950/41813419-ea08d344-7770-11e8-8eb8-31f8ca52d717.JPG)

This screenshot is by Pontus Leitzler.

GopherJS ver (http://hajimehoshi.github.io/go-inovation/) works correctly.

**Comment by hajimehoshi** [comment]
It looks like vertices are correct, but texture data is broken. Hmm...

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/721 should be fixed in the first place?

**Comment by hajimehoshi** [comment]
With Go 1.12 beta1, the app shows the below error.

```
Unhandled Promise Rejection: Error: import function go:runtime.scheduleTimeoutEvent must be callable
```

**Comment by hajimehoshi** [comment]
Before this, we'd need to fix the OOM issue #678

**Comment by hajimehoshi** [comment]
With Go 1.13, the result has become more psychedelic...

![IMG_0003](https://user-images.githubusercontent.com/16950/59524902-fa695800-8f0f-11e9-8b5d-16fb2d0e8307.PNG)

**Comment by hajimehoshi** [comment]
Maybe other examples doesn't cause this issue, but examples/blocks caused. This doesn't extend the internal images, so extending logic is not the culprit. Hmm

**Comment by hajimehoshi** [comment]
```
diff --git a/examples/blocks/blocks/titlescene.go b/examples/blocks/blocks/titlescene.go
index 7b6c47fa..15782744 100644
--- a/examples/blocks/blocks/titlescene.go
+++ b/examples/blocks/blocks/titlescene.go
@@ -32,7 +32,9 @@ func init() {
        if err != nil {
                panic(err)
        }
-       imageBackground, _ = ebiten.NewImageFromImage(img, ebiten.FilterDefault)
+       println(img.At(16, 15).(color.RGBA).R, img.At(16, 15).(color.RGBA).A)
+       println(img.At(16, 16).(color.RGBA).R, img.At(16, 16).(color.RGBA).A)
+       imageBackground, _ = ebiten.NewImageFromImage(img, ebiten.FilterNearest)
 }
 
 type TitleScene struct {
```

Expected:

```
255 255
204 255
```

On iOS Safari:

```
0 255
255 255
```

Then, it looks like something is broken on Wasm side, not GPU side.

**Comment by hajimehoshi** [comment]
https://github.com/golang/go/issues/32635 Reported

**Comment by dmitshur** [comment]
Can you try again with iOS 13? See https://github.com/golang/go/issues/32635#issuecomment-533888835.

**Comment by hajimehoshi** [comment]
OK I'll try to update my device to iOS 1.13 first...

**Comment by hajimehoshi** [comment]
Unfortunately my devices don't get iOS 13 yet. I need more time.

**Comment by hajimehoshi** [comment]
Hmm, mine is iPhone 6 (not S) and iOS 13 never comes. I'd need to buy a new iPhone :-P

**Comment by hajimehoshi** [comment]
Fixed by iOS 13.
