### ISSUE TITLE
Write an IsInBackground() function

### ISSUE THREAD

**Issue by yuvallanger** [hajimehoshi/ebiten#646]
The function will return `false` if the game has the player's focus and `true` when something else is in focus, e.g. the focus is switched to another window, allowing to pause the game until focus is again acquired.

**Comment by hajimehoshi** [comment]
Hi,

Actually the game stops in background by default. I was wondering why you need the function.

**Comment by yuvallanger** [comment]
At the start of each update function I calculate the duration from last iteration. This, in theory, will allow me to create more realistic movements with something similar to:

```
x += dx * dt
```

where `dx` is speed and `dt` is the duration since last iteration.

**Comment by hajimehoshi** [comment]
I still don't understand why you need `IsInBackground()`. The game stops in the background. BTW, as it is guaranteed that update function is called 60 times per sec, you don't have to use real time here (dt should be always 1/60[s])?

**Comment by hajimehoshi** [comment]
Let me close this.
