### ISSUE TITLE
Add `RefreshRate()` to return display's refresh rate

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#647]

**Comment by Zyko0** [comment]
What about 4 years later? 😄

**Comment by hajimehoshi** [comment]
I got aged 4 more years

**Comment by hajimehoshi** [comment]
> The problem is that there is no API on browsers 🤔

This is a critical issue. Do you have any solutions?

**Comment by hajimehoshi** [comment]
In the first place, do we really need this API to get the refresh rate?

**Comment by Zyko0** [comment]
I thought I had a usecase, but no

> do we really need this API to get a refresh rate?
I don't think so 😃
