### ISSUE TITLE
Ebiten window opens on the first monitor as opposed to the primary monitor.

### ISSUE THREAD

**Issue by Kapho** [hajimehoshi/ebiten#650]
Hi!

Opening an ebiten window via ebiten.Run(...) will temporarily flash the window on my primary monitor in the top left corner before centering on my first (non-primary) monitor. Either the window should default to the primary monitor or there should be access to setting which monitor to use. Thanks <3

Experienced this issue on Ubuntu 18.04.

**Comment by hajimehoshi** [comment]
Thank you for reporting.

Yes, in the current implementation, Ebiten might use the default monitor instead of primary monitor. BTW, what is the default monitor and what is the primary monitor in your sentence?

There are several issues on multiple display environment, so I'd need to take care of them...

**Comment by hajimehoshi** [comment]
ping?

> what is the default monitor and what is the primary monitor in your sentence?

**Comment by Kapho** [comment]
A better way to put it: The window would flash where it should be placed (centered on what the OS recognizes as my primary monitor) but would then jump to the top left corner on my first monitor -- or what the BIOS would recognize for its little splash screen and such.

**Comment by hajimehoshi** [comment]
OK so your case is that OS-primary monitor and the first monitor are different, and the window jumps from the former to the latter, right? Hmm, this sounds like a GLFW issue, not sure though.

**Comment by hajimehoshi** [comment]
In the latest implementation, the window is shown on the 'current' window instead of the primary window. Can your problem still be reproduced? Thanks!

**Comment by hajimehoshi** [comment]
This should already be solved.
