### ISSUE TITLE
ebiten: add an option for smooth edges (especially for vector graphics)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#663]
e.g. https://github.com/mattdesl/glsl-fxaa

**Comment by hajimehoshi** [comment]
Well, multisampling might be the way to go, which requires to update OpenGL version from 2 to 3.2 or later

**Comment by Des-Nerger** [comment]
What do you mean by "requires OpenGL 3.2 or later"? I have a videocard that only supports OpenGL 2.1, and still this patch enables multisampling for me:
```diff
--- github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.orig.go	2018-11-14 21:08:53.182323975 +1000
+++ github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go	2018-11-14 21:10:33.022819057 +1000
@@ -96,6 +96,7 @@
 		decorated = glfw.True
 	}
 	glfw.WindowHint(glfw.Decorated, decorated)
+	glfw.WindowHint(glfw.Samples, 16)
 
 	// As start, create an window with temporary size to create OpenGL context thread.
 	window, err := glfw.CreateWindow(16, 16, "", nil, nil)
```

**Comment by hajimehoshi** [comment]
`glfw.Samples` sounds worth a try. Thank you!

For 'nearest' filter, I'd not want to use this multisampling but this seems a kind of global setting.

**Comment by hajimehoshi** [comment]
@Des-Nerger which example or what Ebiten program did you test with that patch?

**Comment by Des-Nerger** [comment]
Here's an example of running
```bash
$ go run "${GOPATH}/src/github.com/hajimehoshi/ebiten/examples/polygons/main.go"
```
on my Linux system with no-, 4x- and 16x- multisampling respectively:
![no-_vs_4x-_vs_16x-_multisampling](https://user-images.githubusercontent.com/7359990/48716438-1a2eeb00-ec63-11e8-85ca-073d8136522e.png)

Seems like `glfw.WindowHint(glfw.Samples, 4)` doesn't have any effect. Or at least I don't see one.

**Comment by hajimehoshi** [comment]
OK so my understanding is that there are some environments like Linux where `glfw.WindowHint(glfw.Samples, 4)` , but there are also environments where this doesn't have any effect. Right?

**Comment by hajimehoshi** [comment]
This was already achieved by adding paddings in a texture atlas (#1210)!

![image](https://user-images.githubusercontent.com/16950/86399017-81d36600-bce1-11ea-9226-7c9e3cb4dedb.png)

**Comment by hajimehoshi** [comment]
Realized that the right side is not blurred. Hmm 🤔

**Comment by hajimehoshi** [comment]
https://learnopengl.com/Advanced-OpenGL/Anti-Aliasing

**Comment by hajimehoshi** [comment]
I'll review how [NanoVG](https://github.com/memononen/nanovg) solved this issue without MSAA

**Comment by hajimehoshi** [comment]
In order to make a smooth result of vector graphics, FXAA might be a handy solution...

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/5d9acfe7ecbd3eee9b779b1f7cd7d050683c9b87

A pseudo MSAA (using a 2x sized offscreen as a rendering target and rendering it onto the screen with the linear filter) worked very well. For a Hi-DPI environment, we can use even bigger offscreen.

I learned how NanoVG works, but I think this is pretty complicated. (calculating vertices explansion and using a special shader to render it?)

I'll close this issue as resolved.
