### ISSUE TITLE
`go build` fails when using `dep`

### ISSUE THREAD

**Issue by yuvallanger** [hajimehoshi/ebiten#665]
Hi @hajimehoshi,

I have used `dep` to place your Ebiten code and all dependencies in the
`vendor/` directory of my repository. When I then try to build, it fails:

```
$ cd $GOPATH/src/gitgud.io/yuvallanger/golang-yasamsim/
$ go build -v
gitgud.io/yuvallanger/golang-yasamsim/vendor/github.com/go-gl/glfw/v3.2/glfw
# gitgud.io/yuvallanger/golang-yasamsim/vendor/github.com/go-gl/glfw/v3.2/glfw
vendor/github.com/go-gl/glfw/v3.2/glfw/c_glfw.go:4:10: fatal error: glfw/src/context.c: No such file or directory
 #include "glfw/src/context.c"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

Dep's configuration file:

```
$ cat Gopkg.toml |grep -v '^#'| grep -v '^$'
[[constraint]]
  branch = "master"
  name = "github.com/golang/freetype"
[[constraint]]
  name = "github.com/hajimehoshi/ebiten"
  version = "^1.7"
[[constraint]]
  branch = "master"
  name = "golang.org/x/image"
[prune]
  go-tests = true
  unused-packages = true
```

Versions:

```
$ go version
go version devel +1b870077c8 Fri Aug 3 17:21:10 2018 +0000 linux/amd64
$ dep version
dep:
 version     : devel
 build date  : 
 git hash    : 
 go version  : go1.10.3
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

Thank you!

**Comment by hajimehoshi** [comment]
Hi,

I have never used deps, but do other libs using Cgo (e.g. GLFW itself github.com/go-gl/glfw) work?

Thanks!

**Comment by hajimehoshi** [comment]
Perhaps https://github.com/golang/dep/issues/269 ?

**Comment by yuvallanger** [comment]
https://github.com/hajimehoshi/ebiten/issues/665#issuecomment-412739815

Maybe! I don't know much about C/C++ development, sorry. :(

**Comment by hajimehoshi** [comment]
This seems already solved.

**Comment by nizmow** [comment]
Hi, sorry to bump this old thread, but it's still happening to me using `dep`. Any idea what "solved" this last time? Is this more a `go-gl` issue I should investigate there?

**Comment by hajimehoshi** [comment]
I meant https://github.com/golang/dep/issues/269 was fixed.
