### ISSUE TITLE
Screen only fills a quarter of the screen on Mac OX

### ISSUE THREAD

**Issue by lei-cao** [hajimehoshi/ebiten#668]
Hi

I am running the games on my Mac Hi Sierra 10.13.6. Only left bottom quarter screen is being used as the 'screen'

![image](https://user-images.githubusercontent.com/136104/44276217-6db32680-a279-11e8-8e83-3b72473f31f4.png)

It's happening to all the games in the examples folder I am running.

**Comment by lei-cao** [comment]
it actually only happens if I run it from my Goland build in terminal. If I run it from iTerm, it's displaying normally.

**Comment by hajimehoshi** [comment]
That's interesting phenomenon. I'll take a look later. Thank you for reporting.

**Comment by lei-cao** [comment]
I found the why to reproduce it.

So I had two monitors. One on my Macbook and one DELL monitor. No matter on which monitor the terminal is running, the game screen is always init on my Macbook monitor. 
Depends on on which monitor the terminal is running, the game window will showing normally or only the quarter screen. 
If I drag the inited game window into another monitor, the scale changes accordingly. From normal to quarterly or from quarterly to normal.

**Comment by hajimehoshi** [comment]
OK so I think this is an already known issue with external displays (#644).

Thank you for additional information!
