### ISSUE TITLE
ebitenutil: `OpenFile` doesn't work with Wasm

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#673]
`NewCallback` should be used.

Reported by @silbinarywolf

**Comment by silbinarywolf** [comment]
I've put together a PR here:
https://github.com/hajimehoshi/ebiten/pull/674

* Change to use `js.NewCallback`
* Use `uint8contentWrapper := js.Global().Get("Uint8Array").New(content)`, without this all the bytes in `data` stays zeroed. (TypedArray cannot use `set` on an ArrayBuffer)
