### ISSUE TITLE
Keys on "Azerty" keyboard not OK

### ISSUE THREAD

**Issue by ryosama** [hajimehoshi/ebiten#677]
On an Azerty keyboard (French keyboard), some letters are not at the same place that in Qwerty keyboard.

"M", "A", "Q", "Z", "W" for example (many others).

For example : 
On Azerty ebiten.KeyM don't represente the "M" key but the semicolon key.

**Comment by hajimehoshi** [comment]
Yes, this is by definition:

https://godoc.org/github.com/hajimehoshi/ebiten#Key

> A Key represents a keyboard key. These keys represent pysical keys of US keyboard. For example, KeyQ represents Q key on US keyboards and ' (quote) key on Dvorak keyboards.

If you want to input keys as the keyboard say, use `InputChars`.

Thanks!

**Comment by ryosama** [comment]
Thanks for the help. I get what I want with InputChars
