### ISSUE TITLE
Freezes after attempting to make bg transparent

### ISSUE THREAD

**Issue by f0nkey** [hajimehoshi/ebiten#682]
Hi, I am attempting to make an overlay for a video game using ebiten, which has had much higher performance in my case.

I am using part of AllenDang's w32 repo to make all black pixels transparent while keeping colors visible. The moment I use `SetLayeredWindowAttributes()`, ebiten seems to freeze. 

Code:
https://gist.github.com/f0nkey/ed6c7e470b760d3cefd41f080eb3fa97

I have not had this issue using other graphics repos. Would anyone be able to help me make it so ebiten does not freeze when using `SetLayeredWindowAttributes()`?

Thank you!

**Comment by hajimehoshi** [comment]
Hi, thank you for using Ebiten!

Just read your code through. Is it ok to call that Win32API other than the main (OS) thread?

I'll check this feature later. GLFW already might have this feature, and I'll create a new API if this is on demand.

**Comment by hajimehoshi** [comment]
Now Ebiten can make the background transparent.
