### ISSUE TITLE
Have a coordinate free DebugPrint function

### ISSUE THREAD

**Issue by ryosama** [hajimehoshi/ebiten#683]
Hi,
It could be good to place the DebugPrint text where we want on the screen.

Just replacing DebugPrint function by this

```Go
// DebugPrint draws the string str on the image at X and Y coordinates (optionnals)
//
// The available runes are in U+0000 to U+00FF, which is C0 Controls and Basic Latin and C1 Controls and Latin-1 Supplement.
//
// DebugPrint always returns nil as of 1.5.0-alpha.
func DebugPrint(image *ebiten.Image, str string, coords... int) error {
	switch len(coords) {
		case 2: 	return debugPrintXY(image, str,coords[0],coords[1])	// 4 arguments
		case 1: 	return debugPrintXY(image, str,coords[0],0)	 		// 3 arguments
		default: 	return debugPrintXY(image, str,0,0)	 				// 2 arguments
	}
}

func debugPrintXY(image *ebiten.Image, str string, x,y int) error {
	drawDebugText(image, str, x+1,   y+1  , true)
	drawDebugText(image, str, x, y, false)
	return nil
}
```

**Comment by hajimehoshi** [comment]
Hi,

I prefer not adding `coords...` arguments since they are vague (what if `len(coords)` is 1 or 3 or more?).

If I'd do, I'd add a new function `DebugPrintAt` or similar thing, but I'm not confident that this is really useful.

**Comment by ryosama** [comment]
DebugPrintAt is OK.
Actually I need this ;-) I already hack debugprint.go to add this function.

**Comment by hajimehoshi** [comment]
Sure, accepted. I'll add this later :-)

**Comment by hajimehoshi** [comment]
Or, PRs are welcome.

**Comment by ryosama** [comment]
Thank you.
What is "PRs" ?

**Comment by ryosama** [comment]
OK it's Pull Request. I've never tried this functionnality. I will learn how it works.
