### ISSUE TITLE
cc1.exe: sorry, unimplemented: 64-bit mode not compiled in

### ISSUE THREAD

**Issue by emailtovamos** [hajimehoshi/ebiten#689]
I get this error when I do ```go get github.com/hajimehoshi/ebiten/...```
Even after I download mingw64 from here (https://sourceforge.net/projects/mingw-w64/) it still doesn't work. 
What could be the reason? 
I am using Windows 10. 
go1.9.4 windows/amd64

**Comment by hajimehoshi** [comment]
Hi,

What does `gcc --version` say?

Thanks,

**Comment by emailtovamos** [comment]
```gcc (tdm-1) 4.9.2```

**Comment by hajimehoshi** [comment]
I was wondering if this is actually 64bit GCC. (4.9.2 seems pretty old...)

**Comment by emailtovamos** [comment]
Ok thanks. Could you provide any link to the newest version for Windows? I tried downloading from multiple sources but not successful yet. And I had 'selected' the 64 bit option. So it is strange if it didn't install the 64 bit one.
 Thanks!

**Comment by hajimehoshi** [comment]
If you get gcc from https://sourceforge.net/projects/mingw-w64/, this should work. Have you fixed $PATH environment variable so that gcc indicates the installed gcc?

**Comment by emailtovamos** [comment]
I put this path of gcc in the $PATH environment variable without luck: 
![gccinstallation](https://user-images.githubusercontent.com/18745859/46243818-aa715200-c3cf-11e8-98e1-2b9414f30ed2.JPG)
![path](https://user-images.githubusercontent.com/18745859/46243834-edcbc080-c3cf-11e8-80c6-9610c5f24b9a.JPG)

**Comment by hajimehoshi** [comment]
I don't know how the installer works, but at least the binary names 'gcc' is required at $PATH.

**Comment by emailtovamos** [comment]
Could you elaborate a bit more please? Did you mean to create another system/user variable called gcc or simply add gcc in front of the corresponding PATH? Like: 
```C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc``` 
instead of : 
```C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin```

**Comment by hajimehoshi** [comment]
I mean there should be a file named `gcc` or `gcc.exe` in the `$PATH` directory. Is there a file named `gcc` or `gcc.exe` in `C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin`?  `x86_64-w64-mingw32-gcc.exe` seems the compiler but there should be an alias named `gcc` or `gcc.exe`. If not, do you know where it is?

**Comment by hajimehoshi** [comment]
Another suggestion is to use [scoop](https://scoop.sh/) and run `scoop install mingw-w64` (the command detail might be different)

**Comment by emailtovamos** [comment]
Thanks, there is a file named gcc.exe. I figured the main issue was that I had another installation of MINGW which was for 32 bit and that was becoming the default path for gcc. I got to know this by doing a ```where gcc``` and it showed me: 
```C:\Program Files (x86)\CodeBlocks\MinGW\bin\gcc.exe```
```C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin\gcc.exe```

I then changed the order in PATH variable list and no longer get the same error. 
However I am getting another error now: 

```#github.com/go-gl/glfw/v3.2/glfw```
```Assembler messages:```
```Fatal error: can't create $WORK\github.com\go-gl\glfw\v3.2\glfw\_obj\\_cgo_.o: Permission denied```

Any ideas about it? Sorry for so many questions, since this if my first time doing something like this.

**Comment by hajimehoshi** [comment]
No problem, Cgo is a kind of headache so I have a plan to eliminate this (https://github.com/hajimehoshi/ebiten/issues/171). Thank you for trying to use Ebiten :-)

> `Fatal error: can't create $WORK\github.com\go-gl\glfw\v3.2\glfw\_obj\\_cgo_.o: Permission denied`

That sounds odd since Windows doesn't have Unix-like permission system. There was a similar problem in Go 1.10 https://github.com/golang/go/issues/24674, so perhaps the newest Go 1.11 might solve this. Using the latest Go is always the best Go anyway.

**Comment by hajimehoshi** [comment]
Now Ebiten doesn't use Cgo on Windows. Let me close this.

**Comment by brijeshssd** [comment]
https://medium.com/@yaravind/go-sqlite-on-windows-f91ef2dacfe

**Comment by hajimehoshi** [comment]
I'm not sure the intention of the comment. Again, Ebiten no longer uses cgo on Windows.
