### ISSUE TITLE
Broken rendering under macOS Mojave

### ISSUE THREAD

**Issue by peterhellberg** [hajimehoshi/ebiten#691]
<img width="420" src="https://user-images.githubusercontent.com/565124/46242816-64b38a00-c3cd-11e8-9642-b6139e5e068e.png">
<img width="420" src="https://user-images.githubusercontent.com/565124/46242817-64b38a00-c3cd-11e8-9ecd-7a4695f947aa.png">

### Environment

```
$ go version
go version go1.11 darwin/amd64
$ xcodebuild -version
Xcode 10.0
Build version 10A255
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14
BuildVersion:	18A391
$ system_profiler SPHardwareDataType
Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro13,1
      Processor Name: Intel Core i7
      Processor Speed: 2,4 GHz
      Number of Processors: 1
      Total Number of Cores: 2
      L2 Cache (per Core): 256 KB
      L3 Cache: 4 MB
      Memory: 16 GB
      Boot ROM Version: MBP131.0223.B00
      SMC Version (system): 2.36f97
```

**Comment by peterhellberg** [comment]
The WebGL version work as expected.

**Comment by hajimehoshi** [comment]
Thank you for the reporting!

**Comment by peterhellberg** [comment]
The same "have to move the window" issue is present for code using https://github.com/faiface/pixel/ but the distortion of the rendering as seen in the Ebiten examples are not present.

**Comment by hajimehoshi** [comment]
After moving the window, does the rendering in Ebiten games become correct?

**Comment by peterhellberg** [comment]
No, unfortunately not.

**Comment by peterhellberg** [comment]
This is how the animation example looks after moving the window (no change)

<img width="640" alt="screenshot 2018-09-29 at 10 55 35" src="https://user-images.githubusercontent.com/565124/46243580-3a19ff00-c3d6-11e8-8534-fbb90513fbc0.png">

**Comment by hajimehoshi** [comment]
Thanks. I think I understood why this happens (viewport is too big).

**Comment by hajimehoshi** [comment]
I think it is fixed :-D

**Comment by hajimehoshi** [comment]
I couldn't reproduce https://github.com/glfw/glfw/issues/1334 though.

**Comment by peterhellberg** [comment]
Yes, the 2048 example now renders as it should 👍 

<img width="420" alt="screenshot 2018-09-29 at 14 09 58" src="https://user-images.githubusercontent.com/565124/46245637-655e1780-c3f1-11e8-8fab-993149a17951.png">
