### ISSUE TITLE
DrawTriangles do nothing

### ISSUE THREAD

**Issue by shnifer** [hajimehoshi/ebiten#696]
Hello!
There is a problem on one of my PC with DrawTriangle method: it do nothing. DrawImage works fine.
Sample code used github.com/shnifer/nigiri/samples/polygons/main.go, copy of ebiten samples for JS. It works fine on two other machines.
Problem system is Win 7 Prof 64, Phenom II, Redeon 7800 series, go 1.11

**Comment by hajimehoshi** [comment]
Thank you for the reporting! Have you tried to change the srcX and srcY value for vertices?

**Comment by hajimehoshi** [comment]
I couldn't reproduce this problem on Win10 machine (VAIO Z Canvas)

**Comment by hajimehoshi** [comment]
I'll try my Radon machine (Photon 2) later. Thank you for the great info!

**Comment by hajimehoshi** [comment]
(Not reproduced yet, but) my current guess is passing NaN doesn't work on some machines? (See internal/graphicsutils' Vertex function)

**Comment by hajimehoshi** [comment]
Now I avoided to use NaN in shaders.

@shnifer could you test the latest Ebiten when you are available? Thanks!

**Comment by shnifer** [comment]
Yay!  Now everything works totally fine!
I think the issue may be closed

**Comment by hajimehoshi** [comment]
👍
