### ISSUE TITLE
What's the most effective way to do splitscreen?

### ISSUE THREAD

**Issue by silbinarywolf** [hajimehoshi/ebiten#699]
Hey there!

I'm wondering how I could best implementation splitscreen (up to 4 players) with Ebiten. My assumption would be that I'd have to ensure each draw of each sprite clips it if it's outside the screen boundary, but I thought I'd raise an issue and see if there was a simpler or more effective way first (such as writing to a surface? or maybe a GL option exists to clip draw calls in a region of the screen?)

**Comment by hajimehoshi** [comment]
Hi,

Clipping is not supported in Ebiten yet. The simplest way is to create 4 offscreen image objects, render  something on the offscreens, and render the offscreens to the screen.

**Comment by silbinarywolf** [comment]
Alright, thank you :)
Feel free to close this if you wish!

**Comment by hajimehoshi** [comment]
Sure, if you find any problems, feel free to reopen this :-)
