### ISSUE TITLE
graphics: Hi-DPI mode

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#705]
Now Ebiten has a capability to show hi-dpi graphics by specifying `1 / ebiten.DeviceScaleFactor()` as scale at `Run`, but there are some drawbacks:

* This doesn't work on multi-monitor environment, where the monitors have different device scale factors.
* Simply, this is un-readable.

I propose a special value to specify the scale at `Run`, which means that Ebiten behaves as if `1 / ebiten.DeviceScaleFactor()` is specified but automatically updated for monitor change.

**Comment by hajimehoshi** [comment]
This would break assumptions that the screen given via `Run` is not changeable (unless `SetScreenSize` is called). It looks like what we really need is 'vector' mode?

**Comment by hajimehoshi** [comment]
I've not come up with a good idea. Let's postpone this.

**Comment by hajimehoshi** [comment]
Current idea:

* Add a new 'hi-DPI' mode to `Image`. An image can have more pixel data compared to its size. For example, a 320x240 image can have 640x480 pixel data if the device scale is 2. I was wondering if this setting should be global or not.
* `(*Image).At` might return an omitted data, or a linear-filtered data.

**Comment by hajimehoshi** [comment]
> I propose a special value to specify the scale at Run, which means that Ebiten behaves as if 1 / ebiten.DeviceScaleFactor() is specified but automatically updated for monitor change.

Hm, I think I missed this requirement 🤔

**Comment by fossegutten** [comment]
It would be nice if we could just set a boolean to enable Hi-DPI mode. Then we could get the actual monitor size when using functions like `ebiten.MonitorSize()`. I tried your example project on hidpi, and it seems very complicated and hard to use. What do you think?

**Comment by hajimehoshi** [comment]
This issue was created before `Game` interface was introduced.

Now the way to enable Hi-DPI is obvious:

https://github.com/hajimehoshi/ebiten/blob/master/examples/highdpi/main.go

```
func (g *Game) Layout(outsideWidth, outsideHeight int) (int, int) {
	// The unit of outsideWidth/Height is device-independent pixels.
	// By multiplying them by the device scale factor, we can get a hi-DPI screen size.
	s := ebiten.DeviceScaleFactor()
	return int(float64(outsideWidth) * s), int(float64(outsideHeight) * s)
}
```

> Then we could get the actual monitor size when using functions like ebiten.MonitorSize()

This doesn't work when the game screen is a window. I believe `Layout` function is the general solution.
