### ISSUE TITLE
Verify Ebiten works on Edge

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#71]

**Comment by otraore** [comment]
What are the current problems with internet explorer?

**Comment by hajimehoshi** [comment]
There is no problem but the priority is low to me :-)

**Comment by otraore** [comment]
I'm slightly confused, why have an issue with internet explorer if there's no issue with internet explorer?

**Comment by hajimehoshi** [comment]
Ah, yeah, I've not tested Ebiten on IE yet, and maybe it doesn't work because of a slightly different APIs.

**Comment by otraore** [comment]
Suggestion: Change title to "Verify ebitten works on internet explorer" or "Try out ebitten on internet explorer" or something of that nature.

**Comment by hajimehoshi** [comment]
Makes sense. Thank you.

(BTW, not Ebitten but Ebiten :-)

**Comment by martinlindhe** [comment]
tested (by visiting the examples in IE Edge),

* there seems to be an issue with font rendering, see screenshots below
* audio doesnt work in "audio" example
* audio works in piano example
* rendering issues in piano example
otherwise mostly functional

![ebiten-blocks-ie-edge](https://cloud.githubusercontent.com/assets/181531/17781558/04e68ab8-6570-11e6-9818-59dff403ac51.png)

![ebiten-sprites-ie-edge](https://cloud.githubusercontent.com/assets/181531/17781625/5a50200e-6570-11e6-9ac2-d04315087f23.png)

![ebiten-piano-ie-edge](https://cloud.githubusercontent.com/assets/181531/17781701/aa9fe7d8-6570-11e6-8112-912b9c6ea4f4.png)

**Comment by hajimehoshi** [comment]
Thank you! It looks like that alpha blending doesn't work and screen size is strange on your IE. The reasons can be 1) Ebiten's web implementation is not enough, 2) there is a bug in Edge or 3) your machine's graphic card has a problem. WebGL behavior heavily depends on the machine's graphics card, so if there is a strange behavior, there might be the same behavior on native apps. Have you run native Ebiten apps on your Windows?

**Comment by martinlindhe** [comment]
The same apps look OK in native windows 10, here is screenshots:
![ebiten-blocks-win10](https://cloud.githubusercontent.com/assets/181531/17805186/80ba63ba-65fe-11e6-90fa-6292c53b1d84.png)
![ebiten-piano-win10](https://cloud.githubusercontent.com/assets/181531/17805187/80bf861a-65fe-11e6-8d2b-e452cb2bd603.png)
![ebiten-sprites-win10](https://cloud.githubusercontent.com/assets/181531/17805188/80c68726-65fe-11e6-9654-092563699b15.png)

**Comment by martinlindhe** [comment]
Regarding your note of WebGL and drivers.

This is produced by using vmware player, with 3d acceleration pass thru to host os (which is Linux, with ATI drivers). But demos does appear to look properly in the guest windows 10, and on the host Linux using these gfx drivers. I do not have access to a "real" windows installation :(

**Comment by hajimehoshi** [comment]
Thank you for testing! The native apps seem to work correctly.

I've tried VMWare or other VMs and found that there can be 3D graphic problems in a guest OS. Not sure why the problem happens only on Edge (on a guest browser?), but I think Ebiten implementation is not mature for IE/Edge. I'll look at this on a real Windows later.

**Comment by hajimehoshi** [comment]
Taking care of Edge would make more sense than IE now.

**Comment by hajimehoshi** [comment]
Tested on Windows Edge on Parallels:

[![Screenshot from Gyazo](https://gyazo.com/a2d443892a92f8bd31077f5da6ce3264/raw)](https://gyazo.com/a2d443892a92f8bd31077f5da6ce3264)

That rendered with a very wrong scale :-(

**Comment by hajimehoshi** [comment]
Blocked by https://github.com/gopherjs/gopherjs/issues/695

**Comment by hajimehoshi** [comment]
Next blocker...: https://github.com/gopherjs/gopherjs/issues/688

**Comment by hajimehoshi** [comment]
Hm, my guess is that Edge doesn't work well with a viewport that size is bigger than the framebuffer. Probably, the viewport size should be always same as the framebuffer size. 

Similar problem report: http://connect.microsoft.com/IE/feedbackdetail/view/863381/webgl-setting-viewport-with-negative-offset-have-no-effect

**Comment by hajimehoshi** [comment]
Now Ebiten works on Edge!
