### ISSUE TITLE
Color changes because of scaling

### ISSUE THREAD

**Issue by shnifer** [hajimehoshi/ebiten#710]
Hello!
I caught something very interesting, and this is repeated on several machines.
An example of the minimum code is shown here: https://github.com/shnifer/nigiri/tree/master/samples/bugminimal/main.go
You can use the “1” and “2” buttons to scale the yellow and blue squares larger or smaller. When they become small enough (about half the size), the blue square turns green.

To eliminate this effect, there are four conditions:
1) Use the same srcImage. If you draw Particle and Particle2 - no errors
2) Draw different colors. If you draw it only once or do not change the color, there are no errors.
3) Use FilterLinear. if you use FilterDefault - no errors
4) And, as I said, you will need a ScaleFactor <0.5

It seems that the error does not depend on:
1) srcImage. White square filled and png sprite work the same
2) specific color values. Other colors produce a different color, but bug nature is the same
3) You can use the same *DrawOptions variable or create a new one
![image](https://user-images.githubusercontent.com/35039664/46750774-6a5c7a00-ccc1-11e8-99a0-c3f1063ff804.png)
![image](https://user-images.githubusercontent.com/35039664/46750825-8a8c3900-ccc1-11e8-9aa6-2311643622bb.png)

**Comment by hajimehoshi** [comment]
Thank you for reporting! Confirmed that this happened and didn't happen on 1.7.4. I guess there are some bugs in mipmap logic.

**Comment by hajimehoshi** [comment]
git bisect says 77e905eb251a69702bf4ffc229c9f16c319cda7f is the cause

**Comment by hajimehoshi** [comment]
Ha, this was a very simple bug!

```diff
diff --git a/image.go b/image.go
index cd3b7829..dab84564 100644
--- a/image.go
+++ b/image.go
@@ -310,7 +310,7 @@ func (i *Image) drawImage(img *Image, options *DrawImageOptions) {
                }
                vs := src.QuadVertices(0, 0, w, h, 0.5, 0, 0, 0.5, 0, 0, 1, 1, 1, 1)
                is := graphicsutil.QuadIndices()
-               s.DrawImage(src, vs, is, options.ColorM.impl, opengl.CompositeModeCopy, graphics.FilterLinear)
+               s.DrawImage(src, vs, is, nil/*options.ColorM.impl*/, opengl.CompositeModeCopy, graphics.FilterLinear)
                img.shareableImages = append(img.shareableImages, s)
                w = w2
                h = h2
```
