### ISSUE TITLE
Question about possibilities

### ISSUE THREAD

**Issue by mich4s** [hajimehoshi/ebiten#741]
Hello, because api and docs are quite weak I couldn't find any answer if that shape:
![test](https://user-images.githubusercontent.com/13378121/49366524-cce25d00-f6e9-11e8-9a33-a4d8551aaad9.png)
can be made in ebiten?

**Comment by hajimehoshi** [comment]
Hi,

In theory yes with `(*Image).DrawTriangles` specifying such vertices. You'd need to calculate such vertices yourself. There is no helper API to do this so far, but I plan to add some kind of such thing, I've not determined yet though.

https://godoc.org/github.com/hajimehoshi/ebiten#Image.DrawTriangles

**Comment by mich4s** [comment]
To bad my golang skills are not enough to provide good quality code for open source projects. Arcs would be great option since it would give possibility to create almost any shape.

**Comment by hajimehoshi** [comment]
Added QuadraticCurve. I plant to add BezierCurve soon.

**Comment by hajimehoshi** [comment]
This was duplicated with #844
