### ISSUE TITLE
Create a binding for Nintendo Switch

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#744]
SDL already supports this?

https://github.com/reswitched/sdl-libtransistor

**Comment by hajimehoshi** [comment]
The current plan is:

* With `go2cpp`, which converts Go to C++ via Wasm, let's create an OpenGL (WebGL) binding and run a C++ converted Ebiten application on Linux or macOS. As far as I can tell, OpenGL works on Nintendo Switch. We don't have to implement a new graphics binding like Vulkan.
* Then, run it on Nintendo Switch with some code. Unfortunately we cannot make it open due to NDA.

**Comment by arran4** [comment]
If not open could it be paid?

**Comment by hajimehoshi** [comment]
I don't plan to make it paid. This will be free (like MonoGame).

**Comment by AugusDogus** [comment]
> * Then, run it on Nintendo Switch with some code. Unfortunately we cannot make it open due to NDA.

What are you referencing by _it_ in this sentence? 

Related, is there any hope for support for switch homebrew via [devkitpro](https://switchbrew.org/wiki/Setting_up_Development_Environment)?

**Comment by hajimehoshi** [comment]
Though I cannot make the code open, I've implemented the binding.
