### ISSUE TITLE
Metal rendering is messed up

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#758]
I checked out the latest commit (https://github.com/hajimehoshi/ebiten/commit/ff628765522700e45de8ed82b16c3f9cf312f051) and tried to run my game. At certain point I can see the rendering result messes up very badly. 2013 Spring MacPro High Sierra

<img width="436" alt="screen shot 2018-12-20 at 10 24 17 pm" src="https://user-images.githubusercontent.com/182612/50287468-2dbdb380-04a6-11e9-99bb-39181aada7c8.png">

**Comment by hajimehoshi** [comment]
Couldn't reproduce this on MacBook 2018 Mojave.

**Comment by hajimehoshi** [comment]
I also couldn't reproduce this on MacBook Pro 2014 Mid High Sierra.

**Comment by hajimehoshi** [comment]
My guess is that extending a shareable image is failing on MacBook Pro 2013 (the original part (1024x1024) was missing). This is basically same as https://github.com/hajimehoshi/ebiten/issues/593
