### ISSUE TITLE
graphicsdriver/metal: Metal throws error on go get and hello world

### ISSUE THREAD

**Issue by kyeett** [hajimehoshi/ebiten#767]
Hi!

I've tried running ebiten on my Macbook, but I get the following error when running 
`go get github.com/hajimehoshi/ebiten/...` or go run main.go with the Hello world example.

\# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/mtl
mtl.m:33:24: error: property 'removable' not found on object of type 'id<MTLDevice>'
mtl.m:34:25: error: property 'registryID' not found on object of type 'id<MTLDevice>'
mtl.m:49:41: error: property 'removable' not found on object of type 'id<MTLDevice>'
mtl.m:50:42: error: property 'registryID' not found on object of type 'id<MTLDevice>'

**My computer:**
MacBook Pro (Retina, 13-inch, Early 2015)
Graphics: Intel Iris Graphics 6100 1536 MB

Any advice?

**Comment by hajimehoshi** [comment]
Hi, thank you for using Ebiten!

Which version of macOS are you using? It looks like `removable` property is supported from macOS 10.13 (High Sierra).

https://developer.apple.com/documentation/metal/mtldevice/2889851-removable?language=objc

**Comment by hajimehoshi** [comment]
I've removed these values since Ebiten didn't use them. There might be other places to fix, but could you try again?

**Comment by kyeett** [comment]
Thank you for your quick support!

Here is the new errors :-)

\# github.com/hajimehoshi/ebiten/internal/graphicsdriver/metal/ca
ca.m:51:36: error: property 'maximumDrawableCount' not found on object of type 'CAMetalLayer *'
ca.m:62:32: error: property 'displaySyncEnabled' not found on object of type 'CAMetalLayer *'

**Comment by hajimehoshi** [comment]
Now I've specified `-mmacos-version-min=10.11` and confirmed Ebiten worked.

What I don't understand is

> ca.m:51:36: error: property 'maximumDrawableCount' not found on object of type 'CAMetalLayer *'

since this was already nested by `@available` so we should not get error there even without specifying that...

**Comment by hajimehoshi** [comment]
We have confirmed the compilation error was fixed. Thank you for your cooperation!
