### ISSUE TITLE
Text rendering with system fonts

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#77]
Personally drawing image is enough, but is there demanding?

**Comment by hajimehoshi** [comment]
Is there a Go library to parse a True Type (or an Open Type) Font?

**Comment by hajimehoshi** [comment]
How do web browsers find font files from font names?

**Comment by peterhellberg** [comment]
Would something like the [pixfont](https://github.com/pbnjay/pixfont) package be enough?

**Comment by hajimehoshi** [comment]
Let me check that. Thank you.

**Comment by hajimehoshi** [comment]
IIUC, pixfont is utility to draw texts with bitmap font. That'd be enough as long as bitmap fonts are used.

I was wondering if system fonts installed in the user's machine are available on desktop or websites. Yeah, the title was not accurate. I'll fix that.

**Comment by hajimehoshi** [comment]
I guess github.com/shibukawa/nanovgo/tree/master/fontstashmini can solve this issue, I postpone this to v1.3 though.

**Comment by hajimehoshi** [comment]
Done!
