### ISSUE TITLE
opengl: shader compile fail

### ISSUE THREAD

**Issue by vence722** [hajimehoshi/ebiten#771]
I'm running the examples in Windows 10, with Golang version 1.11, and I got the following error:

opengl: shader compile failed: WARNING: 0:5: '' :  #version directive missing
ERROR: 0:20: 'filter' : reserved word 
ERROR: 0:20: 'filter' : syntax error syntax error

**Comment by hajimehoshi** [comment]
Thanks, I'll fix this asap.

**Comment by hajimehoshi** [comment]
I think it was fixed. Could you retry? Thanks!

**Comment by vence722** [comment]
It works fine now! Thanks very much for your quick fix!!!

**Comment by hajimehoshi** [comment]
@vence722 Thank you for your reporting.

I reopend this to merge the fix to 1.8 branch.

**Comment by hajimehoshi** [comment]
This was not a problem in 1.8 since `filter` variable was not used.
