### ISSUE TITLE
ebiten.Image.SubImage returns image.Image, not ebiten.Image

### ISSUE THREAD

**Issue by SolarLune** [hajimehoshi/ebiten#785]
Hello!

I have a quick question. It seems like `ebiten.Image.SubImage()` returns an `image.Image` instead of a `*ebiten.Image`. Is this by design? Shouldn't the function just return an `ebiten.Image`?

**Comment by SolarLune** [comment]
Oh, OK. Seems kind of inconvenient to have to cast it to a *ebiten.Image all of the time to use it with ebiten, but maybe I'm misunderstanding. Thanks for the explanation.

**Comment by anth0d** [comment]
Hey @hajimehoshi just FYI the docstring for `SubImage()` states erroneously `The returned value is always *ebiten.Image.`

**Comment by hajimehoshi** [comment]
Yes, the actual value is always `*ebiten.Image`, and the type is the interface `image.Image`. There is nothing wrong there.
