### ISSUE TITLE
graphics: Jaggy results on Chrome (not Firefox)

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#794]
@MrGru reported. This happens only when the scale is exactly 1.

Repository: github.com/MrGru/ChineseChess/
Environment: Chrome (not Firefox) / Nvidia 610M / Windows (100% scale)

@MrGru, can I put a screen shot here?

**Comment by MrGru** [comment]
Chrome:
[https://i.imgur.com/8iYf3PD.png](url)

Firefox:
[https://i.imgur.com/hufjzl5.png](url)

Build file:
https://drive.google.com/file/d/1_2_Sbr_YpaiJlYHh2Vt_F-lf-ZOHifKw/view?usp=sharing

**Comment by hajimehoshi** [comment]
Thank you for the info!

**Comment by hajimehoshi** [comment]
I think #1210 fixed this.
