### ISSUE TITLE
dispmanx - raspberry pi

### ISSUE THREAD

**Issue by fopina** [hajimehoshi/ebiten#806]
Any chance this could work with/as dispman x SDL driver in raspberry? meaning, no X11 requirement, just framebuffer? It'd be awesome

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/issues/760

I plan to do this after next version. I'm not familiar with Raspberry Pi, so I need to learn :-)

**Comment by fopina** [comment]
I think that can be as well though that’s related to performance under X server, as it is works now. But if it can use dispman, it won’t even Require X. A lot of popular Pi distros run without X, with emulators and Kodi using dispman SDL.

I’ll check if dispman works on x86 LINIX vm and if so, it’s an easier entry point than having to test on raspberry :)

**Comment by hajimehoshi** [comment]
Let me merge this to #760
