### ISSUE TITLE
go run fails on OS X

### ISSUE THREAD

**Issue by 1l0** [hajimehoshi/ebiten#82]
followed [here](http://hajimehoshi.github.io/ebiten/) and failed to run it on OS X 10.10.1
```
$ cd $GOPATH/src/github.com/hajimehoshi/ebiten/example
$ go run rotate/main.go
panic: reflect: slice index out of range
```
[full log on gist](https://gist.github.com/1l0/b44f3bba371962b8cbee)

BTW gopherjs build just works :+1: 
![screen shot 2015-01-13 at 04 53 37](https://cloud.githubusercontent.com/assets/3931445/5709950/73772876-9ae1-11e4-87c8-751851636a44.png)

**Comment by hajimehoshi** [comment]
Thank you for reporting! It seems that github.com/go-gl/gl's version is old. If so, please try to `go get -u github.com/go-gl/gl`.

**Comment by 1l0** [comment]
You are right! Now it works as well. Thank you.

**Comment by hajimehoshi** [comment]
No problem :-)
