### ISSUE TITLE
examples: Network game

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#827]
e.g. Pong

**Comment by silbinarywolf** [comment]
What kind of implementation are you going to use?
I've found Websockets can feel sluggish/incorrect for realtime games (ie. Agar.io uses them IIRC)

I've been keeping on an eye on [WebRTC ](https://github.com/pions/webrtc) in Go (to use Datachannels/UDP) but haven't personally experimented with it yet as WebRTC seems incredibly complex!

**Comment by hajimehoshi** [comment]
Not planned yet. As an example, I'd adopt the simplest way. Is WebSockets so bad?

**Comment by silbinarywolf** [comment]
I think its reasonable if you were to make a multiplayer turn-based game like Chess or Risk but its not ideal for Pong. I dont see the harm in putting it together and informing people via README/code comments that Websockets isn't ideal for this kind of game.

This article talks about why TCP isn't great:
- https://gafferongames.com/post/deterministic_lockstep/

This article talks about why you "cant" send UDP from the browser:
- https://gafferongames.com/post/why_cant_i_send_udp_packets_from_a_browser/

**Comment by hajimehoshi** [comment]
#600
