### ISSUE TITLE
graphics: Random crashes where "x must be positive"

### ISSUE THREAD

**Issue by silbinarywolf** [hajimehoshi/ebiten#832]
**The problem**
Occassionally and seemingly at random, my game will crash with the error message / stack dump below. I can't really reproduce this.

**Platform**
Windows 10

**Graphics Card**
NVIDIA GeForce GTX 970

```
panic: graphics: x must be positive

goroutine 51 [running]:
github.com/hajimehoshi/ebiten/internal/graphics.InternalImageSize(0x0, 0x48)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/graphics/math.go:26 +0x81
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).internalSize(0xc000184230, 0x48, 0xc000184230)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:233 +0x4e
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).fill(0xc000184230, 0xc000000000)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:194 +0xc5
github.com/hajimehoshi/ebiten/internal/restorable.(*Image).clear(...)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:173
github.com/hajimehoshi/ebiten/internal/restorable.NewScreenFramebufferImage(0x0, 0x0, 0x8f57d0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/restorable/image.go:162 +0x127
github.com/hajimehoshi/ebiten/internal/shareable.NewScreenFramebufferImage(0x0, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/shareable/shareable.go:448 +0x85
github.com/hajimehoshi/ebiten.newImageWithScreenFramebuffer(0x0, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/image.go:773 +0x40
github.com/hajimehoshi/ebiten.(*graphicsContext).SetSize(0xc000184000, 0x3c0, 0x280, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/graphicscontext.go:72 +0x23e
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).updateGraphicsContext(0x8cba80, 0x6ce3e0, 0xc000184000)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:742 +0xf6
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).update(0x8cba80, 0x6ce3e0, 0xc000184000, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:766 +0xf7
github.com/hajimehoshi/ebiten/internal/ui.(*userInterface).loop(0x8cba80, 0x6ce3e0, 0xc000184000, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:812 +0x7d
github.com/hajimehoshi/ebiten/internal/ui.Run(0x3c0, 0x280, 0x3ff0000000000000, 0x677cf0, 0xb, 0x6ce3e0, 0xc000184000, 0x402001, 0x8cfef0, 0x643d60)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/internal/ui/ui_glfw.go:679 +0x159
github.com/hajimehoshi/ebiten.run(0x3c0, 0x280, 0x3ff0000000000000, 0x677cf0, 0xb, 0xc000184000, 0x3ff0000000000001, 0x0, 0x0)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/run.go:99 +0xd5
github.com/hajimehoshi/ebiten.Run.func1(0xc0000220c0, 0xc00014e030, 0x3c0, 0x280, 0x3ff0000000000000, 0x677cf0, 0xb)
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/run.go:152 +0xf9
created by github.com/hajimehoshi/ebiten.Run
        D:/GoProjects/src/github.com/hajimehoshi/ebiten/run.go:147 +0x101
```

**Comment by hajimehoshi** [comment]
Hi, thank you for reporting!

It looks like the scale value becomes 0 🤔

**Comment by hajimehoshi** [comment]
@silbinarywolf Are you using multiple monitors?

**Comment by hajimehoshi** [comment]
Another question: does this happen on launching the app, or during playing?

**Comment by silbinarywolf** [comment]
- I do have multiple monitors
- I've recently seen it crash after a few inputs, so it's not immediate (ie. maybe the game runs for 2-5 seconds tops)

**Comment by hajimehoshi** [comment]
Thanks. I'll check this with multiple monitors. I couldn't reproduce this with a single monitor.

Would you mind inserting `println(actualScale)` at https://github.com/hajimehoshi/ebiten/blob/master/internal/ui/ui_glfw.go#L728 and checking `actualScale` becomes 0 or not when crashing?

**Comment by silbinarywolf** [comment]
Will do :)

**Comment by hajimehoshi** [comment]
Thank you!

I couldn't reproduce this even with multiple monitors.

**Comment by hajimehoshi** [comment]
I found `GetDpiForMonitor` function usage in Chromium https://cs.chromium.org/chromium/src/ui/display/win/screen_win.cc?q=getdpiformonitor&sq=package:chromium&dr=C&l=38, which considers the case when the dpi is 0. I think this is not documented, but apparently we also need to consider this case.

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/commit/1392129e417c13d1917570da434cb00524e29add

Now the chances of calling Win32API functions are drastically reduced, this bug might be fixed or become really really rare.

**Comment by hajimehoshi** [comment]
@silbinarywolf  What's going on this?

**Comment by silbinarywolf** [comment]
I haven't seen anything as of late but Im not 100% sure if the issue is completely gone either.
I think we can just close this and I can re-open if I see it again?

**Comment by hajimehoshi** [comment]
Sure, let's revisit when we find the same issue.

**Comment by mymmrac** [comment]
@hajimehoshi Hello, I see the same issue when resizing the window & getting screen size

Code example: https://go.dev/play/p/iCreoo1rtqJ

Steps to reproduce:
- Run game
- With enabled debug (on by default, toggled using F3)
- Resize window
- Game crashes from time to time with similar stack trace

If you do the same without debug (in debug I am calling `screen.Bounds()` it will not crash, at least I didn't experience that once), but with enabled debug it crashes really frequently

Ebitenengine version: v2.5.0-alpha.13 (on of latest commits right now)
Go: 1.20.1
OS: Pop_OS 22.04 LTS 

<details>
 <summary>Stack trace</summary>
<pre>
panic: graphics: x must be positive

goroutine 66 [running]:
github.com/hajimehoshi/ebiten/v2/internal/graphics.InternalImageSize(...)
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/graphics/math.go:26
github.com/hajimehoshi/ebiten/v2/internal/graphicsdriver/opengl.(*Graphics).NewImage(0xc000192700, 0x0, 0x0)
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/graphicsdriver/opengl/graphics.go:109 +0x17d
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*newImageCommand).Exec(0xc0001b79c0, {0x82f7a0?, 0xc000192700?}, 0x7f77bc5d08d8?)
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/graphicscommand/command.go:500 +0x84
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).flush(0xaea3a0, {0x82f7a0?, 0xc000192700?}, 0x1)
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/graphicscommand/command.go:240 +0x5c4
github.com/hajimehoshi/ebiten/v2/internal/graphicscommand.(*commandQueue).Flush.func1()
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/graphicscommand/command.go:168 +0x32
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop.func1(0xc0004dfef8?, 0xc0004dfed0?)
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/thread/thread.go:51 +0x53
github.com/hajimehoshi/ebiten/v2/internal/thread.(*OSThread).Loop(0xc000024140, {0x82cc40, 0xc0000ae0a0})
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/thread/thread.go:52 +0x85
github.com/hajimehoshi/ebiten/v2/internal/ui.(*userInterfaceImpl).Run.func1()
        /home/mymmrac/.go/pkg/mod/github.com/hajimehoshi/ebiten/v2@v2.5.0-alpha.13/internal/ui/run_glfw_notsinglethread.go:50 +0x5d
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/mymmrac/.go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/mymmrac/.go/pkg/mod/golang.org/x/sync@v0.1.0/errgroup/errgroup.go:72 +0xa5

</pre>
</details>

**Comment by hajimehoshi** [comment]
Could you file this as a new issue? Thanks,
