### ISSUE TITLE
Ebiten does not launch on Android Emulator

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#833]
We are trying to  run our app on Android emulator. However it appears in black screen.

**Comment by hajimehoshi** [comment]
[![Screenshot from Gyazo](https://gyazo.com/a69dbbb600b845207f4a283b9ce20684/raw)](https://gyazo.com/a69dbbb600b845207f4a283b9ce20684) It worked (Pixel 2 x86)

**Comment by hajimehoshi** [comment]
ping? @wasedaigo

**Comment by wasedaigo** [comment]
I let you know when I try next time

**Comment by wasedaigo** [comment]
Okay, it launched successfully, however the rendering sometimes shows a weird artifact. 

<img width="390" alt="Screen Shot 2019-03-26 at 8 41 37 PM" src="https://user-images.githubusercontent.com/182612/55049002-95d0e800-5007-11e9-9263-58e21108ae8e.png">

**Comment by hajimehoshi** [comment]
Let me close this. Let's revisit this later when we find the problem.

**Comment by hajimehoshi** [comment]
Oops, I missed your report, sorry.

What device did you emulate?

**Comment by hajimehoshi** [comment]
ping

**Comment by hajimehoshi** [comment]
Let's revisit later when we need. This looks like MacBook Pro 2013's issue (which I believe is your machine)
