### ISSUE TITLE
Test with Gokrazy

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#841]
https://gokrazy.org/

I'm not sure how graphics driver should be implemented.

**Comment by hajimehoshi** [comment]
http://seenaburns.com/2018/04/04/writing-to-the-framebuffer/

`/dev/fb0` is the way to go?

**Comment by hajimehoshi** [comment]
For Pi, I thought we could use DispmanX (https://github.com/hajimehoshi/ebiten/issues/760). I'm not sure this supports inputs though.

**Comment by db47h** [comment]
The examples have custom [keyboard handling code](https://github.com/AndrewFromMelbourne/raspidmx/blob/master/common/key.c). Short version: change terminal attributes and read stdin.

But... There's always the good old SDL2 which [works on Pi without X](https://solarianprogrammer.com/2015/01/22/raspberry-pi-raspbian-getting-started-sdl-2/). Added bonus: you can test the SDL2 driver on desktop!

**Comment by beoran** [comment]
Input handling from /dev/input/* devices is easy enough, I do it for joysticks already.
