### ISSUE TITLE
vector: Add various shapes

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#844]
* Rectangle
* Circle
* Ellipse
* Arc

This should be easily implemented by using `LineTo`.

**Comment by beoran** [comment]
As per our talk on slack, I propose we could port Allegro's triangulator to Go, 
(https://github.com/liballeg/allegro5/blob/master/addons/primitives/triangulator.c),
then implement the same functions as the allegro primitives, ported to Go. These are based on triangulations as well. The API is: https://www.allegro.cc/manual/5/primitives.html

**Comment by hajimehoshi** [comment]
Thank you for the info! Please give some time to consider since I don't have enough bandwidth...

**Comment by hajimehoshi** [comment]
* Let's add `ArcTo`
* Rename `BezierCurveTo` to `CubicTo`?
* Rename `QuadraticCurveTo` to `QuadTo`?
* Add `ConicTo`? (See https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/graphics/skiasharp/curves/beziers#the-conic-b%C3%A9zier-curve)

**Comment by hajimehoshi** [comment]
https://skia.org/user/api/SkPath_Reference#SkPath_arcTo

An arc is represented as a conic Bezier curve. Interesting.

**Comment by fr3fou** [comment]
any news?

**Comment by hajimehoshi** [comment]
There is a 'vector' package and an example using it.

* github.com/hajimehoshi/ebiten/vector
* github.com/hajimehoshi/ebiten/examples/vector

The API is still unstable.

**Comment by hajimehoshi** [comment]
Now vector has Path and you can add segments by `LineTo`, `QuadTo` and `CubicTo`. They are similar to Skia's functions. The path can also be filled with a solid color.

https://github.com/google/skia/blob/master/src/core/SkPath.cpp I'm referring Skia implementation to add more user-friendly functions like `arcTo`. It would take more time than I expected and I'll do this in the next milestone maybe...

**Comment by gabstv** [comment]
In the meantime, if anyone wants vectors (and they aren't rendered/updated on every frame) they can use https://github.com/fogleman/gg to render into a texture, and then create a new `*ebiten.Image` from it. If the shapes need to be dynamic, you could use a "is dirty" pattern: http://gameprogrammingpatterns.com/dirty-flag.html

**Comment by fr3fou** [comment]
Is this still ongoing or was it closed by #1111

**Comment by hajimehoshi** [comment]
This is not related to #1111. I don't have enough bandwidth to work on this now.

**Comment by hajimehoshi** [comment]
I'm busy with porting Ebiten to Switch and fixing audio issues for v2.1.0.

**Comment by beoran** [comment]
Do you mean the Nintendo Switch? That's great news! 🙂

Op za 16 jan. 2021 13:45 schreef Hajime Hoshi <notifications@github.com>:

**Comment by hajimehoshi** [comment]
Yes :-)

**Comment by beoran** [comment]
Wonderful! Please document it well, I would love to port my puzzle game to
the Switch.

Op za 16 jan. 2021 18:17 schreef Hajime Hoshi <notifications@github.com>:

**Comment by hajimehoshi** [comment]
Of course we're preparing documentations, but unfortunately I cannot make the document public due to the NDA.

**Comment by hajimehoshi** [comment]
Note to myself: how to render vector graphics with GPU:
* https://github.com/servo/pathfinder
* https://github.com/linebender/piet

**Comment by hajimehoshi** [comment]
Note to my self: APIs for vector
* https://pkg.go.dev/golang.org/x/image/vector

**Comment by hajimehoshi** [comment]
We found that we can draw convex polygons by stencil buffers (#1684). I'll be working on it

**Comment by hajimehoshi** [comment]
Note to myself: Arc in SVG: https://www.w3.org/TR/SVG/paths.html#PathDataEllipticalArcCommands

**Comment by hajimehoshi** [comment]
Hmm, an API to render arcs seems not easy to determine the specification. At least, SVG and a canvas have different APIs. Skia seems to have to APIs. Should we go with a canvas way or a SVG way?

**Comment by hajimehoshi** [comment]
To determine the API set, we have to make a clear goal first. For example, if the goal is to draw a SVG file, the canvas API is not good. What do we want to achieve...? 🤔

**Comment by beoran** [comment]
I think SVG is best because you can make SVG files easily with many
editors, such as Inkscape. There already is a SVG reader for golang, if
ebiten van draw such SVG directly, it will be very convenient and easy to
use.

Op do 15 jul. 2021 20:22 schreef Hajime Hoshi ***@***.***>:

**Comment by beoran** [comment]
For example this has a Mit license:
https://github.com/rustyoz/svg

Op do 15 jul. 2021 20:22 schreef Hajime Hoshi ***@***.***>:

**Comment by hajimehoshi** [comment]
Thanks! There are pros and cons for the canvas API and the SVG API. They can be converted each other anyway: https://stackoverflow.com/questions/6729056/mapping-svg-arcto-to-html-canvas-arcto

# The canvas API: 
`ArcTo(x1, y1, x2, y2, r float32)`
(See https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/arcTo)

This is simple but cannot draw ellipsed arcs.

# The SVG API:
`ArcTo(rx, ry, xAxisRotation float32, largeArc, sweep bool, x, y float32)`
(See https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths#arcs)

This is complex, but can draw ellipsed arcs.

Probably preparing the canvas API first, and then adding another API for SVG later seems fine.

**Comment by hajimehoshi** [comment]
> I think SVG is best because you can make SVG files easily with many
> editors, such as Inkscape. There already is a SVG reader for golang, if
> ebiten van draw such SVG directly, it will be very convenient and easy to
> use.

Thanks! The goal to render SVGs seemed reasonable, but on second thought, it was also pretty tough goal for me to implement most of features for SVG. Though SVG is a good long-term goal, we want smaller goals.

Probably Ebiten users just want an API to render simple shapes like circles. So, as I have already noted, creating a canvas-like API for arcs would work. This doesn't mean we give up SVG. We can add more APIs later.

**Comment by hajimehoshi** [comment]
Now Path has these functions

 * `MoveTo`
 * `LineTo`
 * `QuadTo`
 * `CubicTo`
 * `ArcTo`
 * `Arc`
 * `AppendVerticesAndIndicesForFilling`

I admit these are not enough, and I'll add more functions later as other issues.

**Comment by dawkrish** [comment]
Are there examples provided or docs, on how to use these methods ?
