### ISSUE TITLE
Touch example doesn't appear to work anymore

### ISSUE THREAD

**Issue by lucymhdavies** [hajimehoshi/ebiten#846]
Not sure if this a problem with the JS version, or a problem with touches more generally, as I only use the JS version for now.

For example:
https://jsgo.io/github.com/hajimehoshi/ebiten/examples/drag
Was last compiled 11 months ago

Worked on desktop, worked on mobile.

I triggered a new jsgo.io compilation, and now...

Still works on desktop, no longer works on mobile.

From my experimentation, it appears that `TouchIDs()` is no longer returning anything.

Here's a simple example:
https://play.jsgo.io/e575fc7d5eba5756f3b8fca46c86ec5cad0b071e
https://jsgo.io/d07ace64866e063a327816d8f3c2e1f28909290d

**Comment by hajimehoshi** [comment]
Thank you for reporting!

**Comment by lucymhdavies** [comment]
Confirmed, recompiled https://jsgo.io/github.com/hajimehoshi/ebiten/examples/drag now works :D

Thanks for the speedy fix
