### ISSUE TITLE
How hard is to add console support?

### ISSUE THREAD

**Issue by diegobernardes** [hajimehoshi/ebiten#850]
Just out of curiosity, do you have any plan on adding console support? PS4, Switch, etc...

**Comment by hajimehoshi** [comment]
Hi. This should not be hard, but the hardest point is to get a license to get developer toolkit. Another concern is that I don't know Go works on such environments.

**Comment by hajimehoshi** [comment]
Let me close this. I'll continue to consider to support consoles.
