### ISSUE TITLE
freeze after running for around 40-60 minutes windows 10

### ISSUE THREAD

**Issue by BoredKittenz** [hajimehoshi/ebiten#862]
games freeze after running for 40-60 minutes, no updates, no error messages. this was the case in a personal project as well as with two examples (flappy as well as platformer). I tested on windows 10 as well as on a friend's windows 10 machine.

**Comment by BoredKittenz** [comment]
I have tested this several times and it has happened 100% of the time on every machine I have tried. 
I am on commit 3ce8babd9bd0470bd5683158cc320277cc04d5ed and can test a newer version if needed.

**Comment by hajimehoshi** [comment]
Looks like there is an overflow issue in clock package.

**Comment by hajimehoshi** [comment]
> I have tested this several times and it has happened 100% of the time on every machine I have tried.
I am on commit 3ce8bab and can test a newer version if needed.

Thanks! You don't need to test the latest version now. I think I found the cause. I'll fix asap.

**Comment by hajimehoshi** [comment]
Note:

`QueryPerformanceFrequency` returns 2143475 on my environment, and this seems a typical number. This means that the counter value increases 2143475 for one second. The diff of `QueryPerformanceCounter` values is multiplied with 1e9 to fix the value to nanosecond. Then, after 40 minutes, the value can be `2143475 * 1e9 * 40 * 60 = 5144340000000000000`, which is more than half of `math.MaxInt64`.

**Comment by hajimehoshi** [comment]
@BoredKittenz I think this was fixed. I understand it is hard to test, but could you confirm when you are available? Thanks!

**Comment by BoredKittenz** [comment]
I tested both my own game and the flappy example running for two hours, the issue seems to be fixed. Thank you for your very fast response.
