### ISSUE TITLE
mobile: Create a library file available for Android/iOS

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#863]
Now we need to add wire between a GL surface and Go functions. If we had a library that offers a surface that is already wired with Go world, would it be useful?

**Comment by hajimehoshi** [comment]
I want this before iOS Metal to hide the implementation detail (GTKSurface vs MTKSurface)

**Comment by hajimehoshi** [comment]
Looks like it is possible to created an exported C function with gomobile, but without headers. That's a little unfortunate.

**Comment by hajimehoshi** [comment]
Succeeded to define an Objective-C class that are exported

```
// #import <Foundation/Foundation.h>
//
// FOUNDATION_EXPORT @interface Foo : NSObject
// -(void)foo;
// @end
//
// @implementation Foo
//
// - (void)foo {
//   NSLog(@"Foo is called");
// }
//
// @end
```

**Comment by hajimehoshi** [comment]
Looks like this is not feasible. I think it is impossible to define a Java class on Go side.

**Comment by hajimehoshi** [comment]
What if creating an original command instead of the direct usage of gomobile? (e.g. Gio)

**Comment by hajimehoshi** [comment]
Before implementing Metal (#737), let's finish this issue. It is because switching Metal and OpenGL for iOS is quite hacky. My current idea is

* Create `cmd/ebiten` (or another better name)
* The `ebiten build` calls `gomobile build` inside and inserts header files or Java files to the generated library.

**Comment by Noofbiz** [comment]
Why not try to improve gomobile itself? Like the ability to choose between OpenGL/Metal/Vulkan views could be added to gomobile, then it could work with bind and build, and it would be easier for you to not have to maintain something as fast-changing and easily broken like a gomobile command :P

**Comment by hajimehoshi** [comment]
> Why not try to improve gomobile itself? 

I think you are talking about `gomobile build`, that includes a GL view, but my interest is `gomobile bind`, that doesn't include any views. I don't think it is feasible for `gomoible bind` (not `build`) to include a specific view, and I think it should not. It would be possible to specify files when executing `gomobile bind`, and `ebitenmobile bind` would be just a wrapper to run `gomobile bind` + the view file.

**Comment by hajimehoshi** [comment]
* I'll create `ebitenmobile bind` command, which is a wrapper of `gomobile bind` but adds some additional header or Java files.
* I've succeeded to offer `EbitenViewController` that works with any `UIView` and show a game view. This is basically a wrapper of `GLKView(Controller)` but I'll be able to switch the implementation to Metal in the very near future. The rest task is to embed a header file to the result of `gomobile bind` and fix some files.
* I've not succeeded yet to embed a Java class, I know it should be possible though. This unzip `aar` and `jar`, run `javac`, insert compiled java files and zip them again. It is a little complicated. How about using `gobind` and packing by myself without `gomobile`?
* There is an idea to extend `ebitenmobile` to desktops to generate an exe file for Windows, .app directory for macOS, and so on. I don't do this right now since 1) offering a module instead of a complete exe might be flexible 2) I don't have enough bandwidth. For 1), for example, there might be demands to embed ads to the apps.

**Comment by hajimehoshi** [comment]
https://ebiten.org/mobile.html Done!
