### ISSUE TITLE
Corrupted graphics shown on my Mac 

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#887]
It seems after this commit(https://github.com/hajimehoshi/ebiten/commit/cddb93b9f61a09f94feb813917b3f7c99acf091d), some images stopped rendering properly. (Please check the numbers in the bottom of the screenshot) I have only checked this on my Mac.

<img width="484" alt="Screen Shot 2019-06-25 at 12 16 03 PM" src="https://user-images.githubusercontent.com/182612/60067294-0beb0500-9745-11e9-93fa-42877bc323d6.png">

**Comment by hajimehoshi** [comment]
Thanks!

**Comment by hajimehoshi** [comment]
https://github.com/hajimehoshi/ebiten/blob/master/internal/restorable/image.go#L233

OK the width/height for calculation are different before and after the change...
