### ISSUE TITLE
Question: how do you know who uses your library?

### ISSUE THREAD

**Issue by gonutz** [hajimehoshi/ebiten#891]
Hey there, I am just trying to get in contact with you but Github has long removed private messages. I am just curious how you always seem to know who uses your libraries? You always seem to star things when they are barely created :-)

**Comment by hajimehoshi** [comment]
Hi, I sometimes search GitHub with 'hajimehoshi/ebiten': https://github.com/search?o=desc&q=hajimehoshi%2Febiten&s=indexed&type=Code :)

**Comment by gonutz** [comment]
Oh I see, I did not know you could do that and find all usages with it in others' repos. That is very cool, thanks. Now I can find out how people use my stuff as well :-)
