### ISSUE TITLE
video support?

### ISSUE THREAD

**Issue by sk8245** [hajimehoshi/ebiten#905]
Hello,
Is there any way I could play a video with Ebiten? Maybe integrating FFMpeg with it? (see https://github.com/3d0c/gmf go ffmpeg bindings).
Concerning the video format, it is random (my program can be used to play videos) but I guess it shouldn't really be an issue as FFMpeg has support for them

However I have no idea how to do it, especially with sound. 
Thanks

**Comment by hajimehoshi** [comment]
Hi,

This seems the duplication with #110 .

**Comment by hajimehoshi** [comment]
> Is there any way I could play a video with Ebiten? 

No so far. Supporting video would be a really tough work (which format should be supported? Can they be in pure Go), so it is not feasible to implement this feature in near future so far.
