### ISSUE TITLE
completely transparent window

### ISSUE THREAD

**Issue by develf** [hajimehoshi/ebiten#906]
Is there a way to make the main window completely transparent? This is applicable in screen magnifier applications.

**Comment by hajimehoshi** [comment]
Hi,

Not so far. Let me think whether I implement this or not :-)

**Comment by develf** [comment]
I think it would be a very cool feature. According to my observations, this is probably one of the most annoying desktop problems :). In no other game engine or UI for Go, such an option is implemented so that it is simple and in one function. Everywhere you need to write a large amount of code.

**Comment by hajimehoshi** [comment]
https://www.glfw.org/docs/latest/group__window.html#gac31caeb3d1088831b13d2c8a156802e9

`SetWindowOpacity` was introduced as of GLFW 3.3.

**Comment by hajimehoshi** [comment]
> This is applicable in screen magnifier applications.

Actual example helps me to understand what is the actual usage :-)

The current blocker is the GLFW binding, but I'm thinking to make my own binding (actually, Windows has its original binding to avoid Cgo)

**Comment by develf** [comment]
Examples:
Screen Magnifier  
![image](https://user-images.githubusercontent.com/1009886/61991528-fde91680-b059-11e9-8de9-403220bdc161.png)

Desktop Virtual Pets (like old Felix)
![image](https://user-images.githubusercontent.com/1009886/61991603-1b6ab000-b05b-11e9-9bf6-30f56cdd9340.png)

Draw something right on your desktop
![image](https://user-images.githubusercontent.com/1009886/61991631-97fd8e80-b05b-11e9-9ff4-61cee13d72b6.png)

Screen recording tools
![image](https://user-images.githubusercontent.com/1009886/61991657-0c383200-b05c-11e9-9492-e9eb70e17a75.png)

And much more. The main idea is to as simple as possible to interact with the desktop. There are libraries on Go that simplify it, for example, a  github.com/go-vgo/robotgo. But there is a strong lack of the possibility of simply drawing anything directly on the screen on top of all windows. By simplicity is meant the same convenient approach as it is implemented in ebiten.

**Comment by hajimehoshi** [comment]
Thanks! I meant I already appreciated the comment "This is applicable in screen magnifier applications." as a concrete example, but screenshots are really nice to understand more!

Ebiten itself doesn't have a capability to get a screenshot. Do you plan to write it yourself?

**Comment by develf** [comment]
I have a desire to write like that. To get something of the type of some function or library interacting not direct with X11, Wayland or WinAPI . But as far as I understand, this is low-level graphics programming. In my case, it is not clear where to start, since I worked very little with low-level graphics.

**Comment by hajimehoshi** [comment]
Solved by #1001

**Comment by pcgeek86** [comment]
If you want to make your Ebitengine game transparent, use the `RunGameWithOptions` function instead of `RunGame()`.
Then you have to pass in an instance of the `RunGameOptions` struct with the `ScreenTransparent` field set to boolean `true`.

This works fine in Ubuntu Studio:

```go
ebit.RunGameWithOptions(game, &ebit.RunGameOptions{ScreenTransparent: true})
```

**Comment by AnotherPillow** [comment]
> 

Works on windows too if anyone is wondering.

**Comment by xescugc** [comment]
Just as a side note.

If you are running Linux with a window manager (in my case ArchLinux with i3) you need to install a `compositor` like https://wiki.archlinux.org/title/Xcompmgr in order for this to work, if not you'll see no result, just the normal screen with no transparency.
