### ISSUE TITLE
graphics: Use mipmaps not only for DrawImage but also DrawTriangles

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#909]

**Comment by hajimehoshi** [comment]
Let's move the mipmap part so that `buffered` package will be a user. This is required for #1044 .

**Comment by hajimehoshi** [comment]
On second thought, how can I determine the mipmap level from triangles?? 🤔

**Comment by hajimehoshi** [comment]
What about enabling to specify mipmap level?

**Comment by hajimehoshi** [comment]
I don't have a clear idea so far.

**Comment by hajimehoshi** [comment]
Unifying DrawImage and DrawTriangles before introducing shaders should be nice. Let's look for an algorithm to select mipmap level from triangles.

**Comment by gabstv** [comment]
being able to specify mipmaps would be nice!

**Comment by hajimehoshi** [comment]
> being able to specify mipmaps would be nice!

Now Ebiten automatically creates and uses mipmaps. Specifying it would be another task, but I'm not sure I'll do.

**Comment by gabstv** [comment]
I'm sorry. I didn't mean to assign/set mip maps directly, but to disable/enable or set the max level.

**Comment by hajimehoshi** [comment]
> to disable/enable or set the max level.

I see. This sounds good but let me defer this until we really want them :-)
