### ISSUE TITLE
graphics: A utility to support texture atlas

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#91]

**Comment by hajimehoshi** [comment]
I have no idea what to do when the filter is linear.

**Comment by faiface** [comment]
Are you reffering to the artifacts from adjacent textures in an atlas? I think putting gaps between them is sufficient. The gaps should be just fully transparent (0,0,0,0). If you're using premultiplied alpha, this should cause no artifacts.

**Comment by hajimehoshi** [comment]
Yeah, you're right. My concern was efficiency of memory usage, but small gaps would work without expense of much memory. Yes, I'm using premultiplied alpha.

**Comment by hajimehoshi** [comment]
#398 is a blocker

**Comment by hajimehoshi** [comment]
> Yeah, you're right. My concern was efficiency of memory usage, but small gaps would work without expense of much memory. Yes, I'm using premultiplied alpha.

This was solved by https://github.com/hajimehoshi/ebiten/commit/8e7e960b56c1c2bdeb3d5fbb7f8d6bf2a304e802

**Comment by hajimehoshi** [comment]
My current idea is `(*ebiten.Image).SubImage(r image.Rectangle) *ebiten.Image` to take a part of image, which can be passed to `DrawImage`.

**Comment by hajimehoshi** [comment]
Close this per #514. Now the texture atlas is created automatically and Ebiten users don't have to care :-)
