### ISSUE TITLE
How to set key color of a *ebiten.Image?

### ISSUE THREAD

**Issue by freeznet** [hajimehoshi/ebiten#914]
How to set a key color for a *ebiten.Image? A key color normally used to set image background transparent. Thanks.

**Comment by hajimehoshi** [comment]
Hi,

Ebiten treats only 32bit-colored images, Ebiten doesn't have such notion. 

https://golang.org/pkg/image/#NewPaletted A paletted image can have a transparent key color, and Ebiten's `NewImageFromImage` can accept this image.

**Comment by freeznet** [comment]
Thanks for your reply, this is what i did currently. But can I do it with ColorM or Blend?

**Comment by hajimehoshi** [comment]
Yes. `ColorM` can be applied to any Ebiten images at `DrawImage`.

**Comment by zombinome** [comment]
Can you please provide some example. I'm trying to write tool work with game archives from old game, and it uses png image without transparency. I would like to be able to render UI for that game based on ui configs.

**Comment by hajimehoshi** [comment]
1. Get an image [`image.Paletted`](https://pkg.go.dev/image#Paletted)
2. Replace an index in [`color.Palette`](https://pkg.go.dev/image/color#Palette) with a transparent color
3. Pass the image to `ebiten.NewImageFromImage`(https://pkg.go.dev/github.com/hajimehoshi/ebiten/v2#NewImageFromImage)
