### ISSUE TITLE
will cache NewImageFromImage's result get better performance?

### ISSUE THREAD

**Issue by freeznet** [hajimehoshi/ebiten#920]
Hi there, currently we are trying to use ebiten to write our first go based 2d game. while we draw the tiled game, we using `NewImageFromImage` to create tile image from paletted  images created by byte array from a custom binary file. Since some of the tiles are reused by one map, so we cached the `NewImageFromImage`'s result in a key-value map, but we want to know that if it is necessary? If a cache is necessary, what should we do if the image is `Dispose()`ed? Will ebiten `Dispose()` an image if it is not been used anymore?

**Comment by hajimehoshi** [comment]
Hi,

> so we cached the NewImageFromImage's result in a key-value map, but we want to know that if it is necessary?

This is technically not 'necessary', but good. Creating a new image by `NewImage` or `NewImageFromImage` is an expensive operation. Then reducing calls by cache is a good strategy in general.

> Will ebiten Dispose() an image if it is not been used anymore?

Yes. `Dispose` is automatically called by GC. `Dispose` is needed when the image is obviously no longer needed. (The godoc doesn't indicate this fact. I'll fix this later).

**Comment by freeznet** [comment]
thanks for your reply, following to the second problem. if `Dispose` is automatically called by GC, how can we ensure that cached `*ebiten.Image` is not been `Dispose`d?

**Comment by hajimehoshi** [comment]
The image is not disposed as long as there is a reference to the image (i.e., GC doesn't collect that object) and you don't call `Dispose` explicitly. Does this answer your question?

**Comment by freeznet** [comment]
ok, so this will cause another problem, that cached `*ebiten.Image` will prevent GC, am i right?

**Comment by hajimehoshi** [comment]
You are right. If you design a cache, you'd need to decide when to evict the images from cache. The simplest way is to use a fixed maximum number of objects and evict the oldest object when inserting a new object that will exceeds the maximum number of objects. If an image you need is not in the cache, it should be fine to call `NewImageFromImage`.

**Comment by freeznet** [comment]
i will try lru cache first. thanks.
