### ISSUE TITLE
Partial Wakelock on Android

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#931]
In our project we are seeing a wake lock acquired for AudioMix, which is not necessary for our game. The reason why I believe ebiten is the culprit is because this wake lock goes away when I do not call Mobile.Update().

```
Wake Locks: size=1
  PARTIAL_WAKE_LOCK              
  'AudioMix' ACQ=-15s316ms (uid=1041 ws=WorkSource{10227})
```

Repro step:
1. Run the game
2. type ```adb shell dumpsys power```
3. Observe wake lock is acquired after launching the game with ebiten audio.

**Comment by hajimehoshi** [comment]
There were 4 wake locks on go-inovation

```
Wake Locks: size=4
  PARTIAL_WAKE_LOCK              'AudioIn' ACQ=-7m12s324ms LONG (uid=1041 ws=WorkSource{10035})
  PARTIAL_WAKE_LOCK              '*gms_scheduler*/com.google.android.gms/.instantapps.routing.DomainFilterUpdateService' ACQ=-1m30s320ms LONG (uid=10014 pid=3343 ws=WorkSource{10014 com.google.android.gms})
  SCREEN_BRIGHT_WAKE_LOCK        'WindowManager' ON_AFTER_RELEASE ACQ=-30s33ms (uid=1000 pid=2526 ws=WorkSource{10218})
  PARTIAL_WAKE_LOCK              '*gms_scheduler*/com.google.android.gms/.instantapps.routing.DomainFilterUpdateService' ACQ=-27s649ms (uid=10014 pid=3343 ws=WorkSource{10014 com.google.android.gms})
```

**Comment by hajimehoshi** [comment]
Confirmed this with "Bear's Restaurant"

```
Wake Locks: size=1
  PARTIAL_WAKE_LOCK              'AudioMix' ACQ=-19s31ms (uid=1041 ws=WorkSource{10189})
```

**Comment by hajimehoshi** [comment]
I think this was fixed.

You need to check this by switching the app. Before the fix, `PARTIAL_WAKE_LOCK` by `AudioMix` remained even when you tried to switch the applications. After the fix, this is disappeared.

Note that `PARTIAL_WAKE_LOCK` by `AudioMix` remains when the app is active (not being switched).
