### ISSUE TITLE
Set/get window position

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#936]
Requested by @kyeett

**Comment by hajimehoshi** [comment]
The problem is that Ebiten doesn't expose the notion of a 'window', and I'm worried adding this API would break some assumptions... 🤔

**Comment by beoran** [comment]
This API only makes sense when the application is not in a full screen mode, and not on a mobile platform. So this is optional.  An alternative name could be a "view" or a "viewport".

**Comment by deckarep** [comment]
This would be a nice feature when not in full screen and upon changing the scale factor.

**Comment by hajimehoshi** [comment]
I think I'll be working on this after https://github.com/hajimehoshi/ebiten/issues/943

**Comment by hajimehoshi** [comment]
#943 would take more time than I expected. I'll do this first.

**Comment by hajimehoshi** [comment]
Oops, I closed this unexpectedly.

**Comment by deckarep** [comment]
Great! Thanks for doing this, I’m gonna try it out today.
