### ISSUE TITLE
example/sprites: Keep 60 FPS with 40k sprites on MacBook Pro 2018

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#941]
Unfortunately, mutex like 1f66c155ae68d0933e953a21e4326b69079ad679 slowed down the app :-/

**Comment by hajimehoshi** [comment]
Another cause is bc4e35a6c53abe38b0945747067086c37c7128af ?

**Comment by hajimehoshi** [comment]
Another cause: 1a2a0aeb76c4fd47ea1f3c7e9ecf2e0b9ad48d28 (now the implementation is different but mutex/channels are the cause)

**Comment by Zireael07** [comment]
Intel Kaby Lake, FPS drop on wasm sprites demo as soon as it starts (~1400).
Like, what? Pixi.js and their ilk can do four times that.

**Comment by hajimehoshi** [comment]
Interesting. It is possible that JavaScript can run faster than Go's WebAssembly, but I'll take a look later.

BTW, I found 40K sprites worked on MacBook pro (not wasm but a native app), then I'll close this issue.
