### ISSUE TITLE
cmd/ebitenmobile: Crash on iOS 13

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#963]
> Fatal Exception: NSInternalInconsistencyException
> Modifications to the layout engine must not be performed from a background thread after it has been accessed from the main thread.

**Comment by hajimehoshi** [comment]
I could not reproduce this.

**Comment by essial** [comment]
He’s calling ebiten from the wrong thread I believe. You have to do it from the main process thread. OpenGL is very picky about that.

**Comment by hajimehoshi** [comment]
Ebiten iOS uses Metal. And I believe they are called on a particular thread, but let me double check.

**Comment by essial** [comment]
Sorry that’s what I meant. His code is doing things on the wrong thread. I don’t think this is an ebiten  issue. We’d need example code to even confirm this is related to ebiten.

**Comment by hajimehoshi** [comment]
This issue is about iOS, not an OpenDiablo 2 issue.

**Comment by essial** [comment]
I know, was just trying to help as I’ve ran into this type of error

**Comment by hajimehoshi** [comment]
```
0
CoreFoundation
__exceptionPreprocess
1
libobjc.A.dylib
objc_exception_throw
2
Foundation
-[NSISEngine tryToOptimizeReturningMutuallyExclusiveConstraints]
3
Foundation
-[NSISEngine _optimizeWithoutRebuilding]
4
Foundation
-[NSISEngine optimize]
5
Foundation
-[NSISEngine performPendingChangeNotifications]
6
UIKitCore
-[UIView(Hierarchy) layoutSubviews]
7
UIKitCore
-[UIView(CALayerDelegate) layoutSublayersOfLayer:]
8
libobjc.A.dylib
-[NSObject performSelector:withObject:]
9
QuartzCore
-[CALayer layoutSublayers]
10
QuartzCore
CA::Layer::layout_if_needed(CA::Transaction*)
11
QuartzCore
CA::Layer::layout_and_display_if_needed(CA::Transaction*)
12
QuartzCore
CA::Context::commit_transaction(CA::Transaction*, double)
13
QuartzCore
CA::Transaction::commit()
14
QuartzCore
CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*)
15
CoreFoundation
__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__
16
CoreFoundation
__CFRunLoopDoObservers
17
CoreFoundation
CFRunLoopRunSpecific
18
WebCore
RunWebThread(void*)
19
libsystem_pthread.dylib
_pthread_start
20
libsystem_pthread.dylib
thread_start
```

**Comment by hajimehoshi** [comment]
`Layout` in `ebitenmobileview` might need `runtime.LockOSThread`?

**Comment by hajimehoshi** [comment]
> `WebCore`

Ooh, this sounds like an advertisement in the app reported by @wasedaigo

**Comment by hajimehoshi** [comment]
https://groups.google.com/forum/#!topic/google-admob-ads-sdk/PuHOKMX1mVI

This is an issue in AdMob.
