### ISSUE TITLE
audio: New mode that only SEs are played

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#967]
Especially on mobile applications, some people want the application to stop BGM (not SE) while other application plays music. First, Ebiten would require to understand the notion of BGM and SE. I am not sure Ebiten should care this, but I'd like to note this as an interesting idea.

CC @wasedaigo

**Comment by beoran** [comment]
In Allegro there is a difference between samples, meant to be played as sound effects and audio streams, meant to be played as BGM, and their functionality is different. Such a split could make sense for Ebiten as well.
