### ISSUE TITLE
Delay of sound after not focusing the game window

### ISSUE THREAD

**Issue by wasedaigo** [hajimehoshi/ebiten#975]
OS: Mac
ebiten version: ddba7f0ee05aa87f3a8dfc46a1e5d9ee5cb13010

Repro Step: 
1. Leave the game unfocused
2. Confirm the music delays after focusing the window

It seems the amount of delay is proportional to the time you were not focusing the window.

**Comment by hajimehoshi** [comment]
Confirmed.

**Comment by hajimehoshi** [comment]
The fix causes PARTIAL_WAKE_LOCK on Android.

**Comment by hajimehoshi** [comment]
I'll reflect this fix on 1.10 after Oto v0.5.3 is released.

**Comment by hajimehoshi** [comment]
Now Ebiten has Oto v0.5.3.
