### ISSUE TITLE
graphics: Calling NewImageFromImage or ReplacePixels too many times slows the game

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#976]
@essial and I discussed that calling `NewImageFromImage` or `ReplacePixels` invokes glTexSubImage2d and this is relatively slow.

For initialization, it is possible to call these functions often, and this slows the application.

In the case of OpenDiablo2, this created over 1000 images at the same time.

**Comment by hajimehoshi** [comment]
The idea is to integrate ReplacePixels commands like DrawTriangles, but I'm not sure this is feasible.

**Comment by hajimehoshi** [comment]
1. (Optional refactoring) Separate `Image` in `restorable` and `graphicscommand` in two: for `ReplacePixels` and for `DrawTriangles`. This would make things simpler.
2. Delay and merge `ReplacePixels` calls as possible

For 2., my concern is memory usage: this requires a successive memory allocation.

**Comment by hajimehoshi** [comment]
Another suggestion: use streaming textures

http://www.songho.ca/opengl/gl_pbo.html

**Comment by hajimehoshi** [comment]
OpenGL 2.0 supports PBO, so desktops are fine.

OpenGL ES 3.0 supports PBO and Android 5.0 should support this
https://developer.android.com/guide/topics/graphics/opengl

WebGL (2.0) does not support PBO, and I think PBO with JavaScript would not be efficient. Is that correct?
https://stackoverflow.com/questions/43530082/how-can-i-upload-a-texture-in-webgl2-using-a-pixel-buffer-object

**Comment by essial** [comment]
What would make sense in my mind is to have an 'animated image' of sorts, where you can add 'frames', and ebiten would swap out the current texture with the wanted frame when the frame index changes. Internally it'd allocate a single texture that is big enough for the largest frame. Each frame may or may not need an offset relative to the image.
If there was a GL test, it could have code that on GL2 simply setpixel's the image (or does an atlas), whereas in GL3 it could create a PBO and stream the data to it as necessary.

**Comment by hajimehoshi** [comment]
Thanks. If we'd introduce an 'animated image', sending pixels for each frame instead of preparing a big texture would make sense. My understanding is that the problem is the cost of sending pixels from CPU to GPU, so preparing a big texture would not solve the issue.

**Comment by essial** [comment]
I just meant a texture big enough for the largest frame.

**Comment by hajimehoshi** [comment]
> I just meant a texture big enough for the largest frame.

Oh then that makes sense :)

> If there was a GL test, it could have code that on GL2 simply setpixel's the image (or does an atlas), whereas in GL3 it could create a PBO and stream the data to it as necessary.

Looks like OpenGL 2.1 already supports PBO. https://en.wikipedia.org/wiki/OpenGL#Version_history

**Comment by hajimehoshi** [comment]
Introducing a new API should be considered carefully. So my plan is

1. Introduce PBO in the current `(*graphicsdriver/opengl.Image).ReplacePixels` for desktops and see what will happen
2. Try to optimize the current `ReplacePixels` by merging graphics commands.
3. Consider the animated image

I'll be working on 1. this weekend. The order of 2. and 3. is not determined yet. Both are not simple.

**Comment by hajimehoshi** [comment]
@essial As `ReplacePixels` now uses PBO, this works asynchronously as far as I understand. Would just calling `ReplacePixels` every frame work instead of introducing 'an animated image'?

**Comment by essial** [comment]
There is only one way to find out *loads cannon*

**Comment by hajimehoshi** [comment]
Sorry I'm not sure what you meant.

**Comment by essial** [comment]
ReplacePixels is now performant! I don’t knit if you should go through the trouble now honestly.

**Comment by hajimehoshi** [comment]
Great! Now let me close this issue. Let's revisit when we really need an animated image.
