### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by dataf3l** [hajimehoshi/ebiten#992]
Hello guys, I love the fact that this exists, I noticed the website and loved the documentation of the code, I'd like to know how the documentation was generated, did you guys use some sort of go documenting tool?
Also please keep creating cook stuff! :)

**Comment by hajimehoshi** [comment]
Hi,

I think you are talking about ebiten.org. It is hosted at https://github.com/ebiten/ebiten.org. HTMLs are edited by a text editor (Emacs) and automatically generated by a simple Go program.

**Comment by hajimehoshi** [comment]
Let me close this issue. Feel free to reopen this when you find another issues. Thanks!
