### ISSUE TITLE
graphics: Strange rendering with Radeon RX 580

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#993]
Version: https://github.com/OpenDiablo2/OpenDiablo2/commit/dba17fc5fe1e2510336c0601c330a5ea32bfcf5b
This is not reproduced with Ebiten 1.10.

GPU: RX 580 sapphire

**Comment by hajimehoshi** [comment]
Confirmed that this happens with examples/flappy

**Comment by hajimehoshi** [comment]
![flappy](https://user-images.githubusercontent.com/16950/69438542-908b8f00-0d88-11ea-996d-74e7ca5780db.png)

by Troispoils

**Comment by hajimehoshi** [comment]
Note that this worked before introducing `glMapBuffer`.

**Comment by hajimehoshi** [comment]
We might need to avoid `glMapBuffer` due to portability, maybe? On the other hand, `glTexSubImage2d` should be called once for multiple rectangle regions, or the performance would be poor.

My current idea is:

* If the number of the region is 1, call `glTexSubImage2d`.
* If not:
  * Create one big byte slice that includes the rectangle regions
  * Create a temporary texture (if needed)
  * Call `glTexSubImage2d` on the temporary texture with the big byte slice
  * Render the temporary texture to the target.

**Comment by hajimehoshi** [comment]
Radeon R4 Graphics (Bungbungame Photon2) didn't cause this issue.

**Comment by hajimehoshi** [comment]
https://www.reddit.com/r/blender/comments/e0iv5q/blender_suddenly_looks_like_this_looks_kinda_cool/ is similar to the previous report:

![opendiablo](https://user-images.githubusercontent.com/16950/69483131-e9c9f000-0e66-11ea-9111-5a3195fe1588.png)

**Comment by auyer** [comment]
Does not occur with Go1.12.5 / Go1.13.4 windows/amd64 on an AMD Vega 64.

**Comment by hajimehoshi** [comment]
Thanks! I think this means that not all external AMD GPUs caused this issue.

**Comment by hajimehoshi** [comment]
@auyer What is the SHA1 hash of Ebiten?

**Comment by hajimehoshi** [comment]
Meh, I could not reproduce this with MacBook Pro 2018 and an eGPU (Radeon RX 580)

**Comment by auyer** [comment]
> Thanks! I think this means that not all external AMD GPUs caused this issue.

The GPU I used is dedicated, but not external.

> @auyer What is the SHA1 hash of Ebiten?

f6390abad74f0cbff79fcb73efa7306d2c89e63e

I can re-test with a different commit if you want.

**Comment by hajimehoshi** [comment]
Thanks!

> I can re-test with a different commit if you want.

That commit is fine (this should include the reported problem). Thanks.

**Comment by hajimehoshi** [comment]
Now I replaced `glMapBuffer` / `glUnmapBuffer` with `glBufferSubData`, then this should not be problematic more.
