### ISSUE TITLE
ui: Add MaximizeWindow / MinimizeWindow

### ISSUE THREAD

**Issue by hajimehoshi** [hajimehoshi/ebiten#994]

**Comment by marti1125** [comment]
Hi @hajimehoshi  could I contribute with this?

**Comment by hajimehoshi** [comment]
Yes, I'm happy to review :-)

Before sending the PR, I'd like to know your plan. Thanks!

**Comment by marti1125** [comment]
Hi @hajimehoshi.
actually ebiten has https://github.com/hajimehoshi/ebiten/blob/6b12b02a05a3ff2be65a94e7b9cd9ab8af86c6c1/window.go#L66
could you help me, I'm  confused

**Comment by hajimehoshi** [comment]
This (`setWIndowResizable`, not `SetWindowResizable`) code looks old and is no longer used. I'll remove this later.

**Comment by hajimehoshi** [comment]
Now I've removed `setWindowResizable.` Does the things clear to you?

**Comment by marti1125** [comment]
@hajimehoshi thanks!
I reviewed the code, could you give more information about new feature?
by default it has 
![imagen](https://user-images.githubusercontent.com/223240/74361866-64d7de00-4da6-11ea-829a-6431859d22c9.png)
this new feature must has the possibility to setup maximize and minimize ?

**Comment by hajimehoshi** [comment]
The window is not resizable by default, and you need to call `SetWindowResizable(true)`.

So, for example, if we add these functions:

* `SetWindowMaximized(bool)`
* `SetWindowMinimized(bool)`

these functions should work only when the window is resizable. If the window is not resizable, I think it is OK that these functions panic.

**Comment by hajimehoshi** [comment]
I'll be working on it soon.
